### ISSUE TITLE
CaImAn on voltage reporter data

### ISSUE THREAD

**Issue by catubc** [flatironinstitute/CaImAn#100]
Hi

I'm looking to apply some of the tools to voltage data. It would be great if you could take a look at some of this data (sent separately). The SNR is quite low, and the acquisition rates are much higher.

Thanks,
catubc

**Comment by agiovann** [comment]
Sure

I would be happy to have a look.

Cheers

**Comment by catubc** [comment]
Hi Andrea. I sent this to Eftychios email below\;

*********************************

Thanks for helping, we're really excited about this project and have a lot
of data that Yuki (a postdoc at Rafa Yuste's lab) has collected that hasn't
been processed. I posted a querry on github, but I didn't want to share
these datasets with everyone:

6100 frames (after motion correction and filtering):
https://www.dropbox.com/s/sg7g3xnqf74k7l4/fov6_flash-
009_ArcLight2_turboreg_kalman.npy?dl=0

20 x 200 frames from above stack triggered off a stimulus:
https://www.dropbox.com/s/d0h0l3vq0ye5506/fov6_flash-
009_ArcLight2_turboreg_kalman_mean.npy?dl=0

I'm happy to meet at the institute to go over some of the data and
requirements if it helps.

Thanks,
Cat

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by epnev** [comment]
A solution in now provided with [VolPy](https://www.biorxiv.org/content/10.1101/2020.01.02.892323v1.full).
