### ISSUE TITLE
question about memmap order after motion correction

### ISSUE THREAD

**Issue by grg2rsr** [flatironinstitute/CaImAn#1000]
Hi, I have a question regarding the memory mapping functionalities of caiman.

When I run 
`caiman.motion_correct(save_movie=True)`, an F order memory mapped file is produced for each imaging data file. Later on in the pipeline, the CNMF requires a memmap of the entire recording, so the `caiman.save_memmap()` produces that, but seems to check if order C memmap files exist, and if not, first writes C ordered memmaps, then joins them.

The question is, why F ordered memmaps are produced in the first place, and how can I directly write C ordered memmaps from the motion correction routines? It seems not possible to pass this as a parameter. As a consequence, I am suffering from immense data inflation: first the F ordered memmap files are twice as large as my data files (16 -> 32 bit), then they are duplicated, and then once more when the single memmap that spans the entire recording is written. Of course I can remove those files, but maybe there is a way I can reduce the time caiman spends writing hundreds of GB on the disk? Thanks!

**Comment by pgunn** [comment]
Hello,
According to Johannes,

```
the motion correction uses F-order cause it parallelizes over frames and reading entire frames is fast. Afterwards C-order is used cause Caiman paralyzes over patches and reading the entire time series for one pixel is fast.
```

**Comment by kushalkolar** [comment]
I think that the reason for 16bit -> 32bit is because many opencv functions only work with 32bit arrays, and there are some routines specifically optimized for 32bit floats? Pat can probably answer this better.
