### ISSUE TITLE
mamba installation failed with problem of not finding provider

### ISSUE THREAD

**Issue by cathefly** [flatironinstitute/CaImAn#1006]
I had a caiman 1.9.7 installed in early spring 2022 without much difficult, but recently there is a unknown problem with running the same demo script. Somehow, i got the idea of uninstall my previous caiman and upgrade it to the latest one. I've waited hours for without returning any solution for solving environment with "conda install -c conda-forge caiman". Then I tried mamba, which gives me a quick return of an error message, as below. Thank you for your time and attention.

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Win10 Pro

 2. Python version (3.x): 
 # Name                    Version                   Build  Channel
ipython                   7.33.0           py37h03978a9_0    conda-forge
ipython_genutils          0.2.0              pyhd3eb1b0_1
opencv-python             4.5.1.48                 pypi_0    pypi
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py37haa95532_0
python_abi                3.7                     1_cp37m    conda-forge

 3. Working environment (Python IDE/Jupyter Notebook/other):
 Miniconda powershell (lastest conda updated, with default settings)
(base) PS C:\Users> conda list conda
# packages in environment at C:\Users\miniconda3:
#
# Name                    Version                   Build  Channel
conda                     4.14.0           py37h03978a9_0    conda-forge
conda-package-handling    1.8.1            py37h8cc25b3_0

 4. Which of the demo scripts you're using for your analysis (if applicable):
 N/A

 5. CaImAn version*: 
 N/A

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
mamba env create -f environment.yml -n caiman

Below is the content of  environment.yml file (saved from the official github site)
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - bokeh
  - coverage
  - cython
  - future
  - h5py
  - holoviews
  - ipykernel
  - ipython
  - ipyparallel
  - jupyter
  - matplotlib
  - mypy
  - nose
  - numpy
  - numpydoc
  - opencv
  - peakutils
  - pims
  - psutil
  - pynwb
  - pyqtgraph
  - scikit-image >=0.19.0
  - scikit-learn
  - scipy
  - tensorflow >=2.4.0
  - tifffile
  - tk
  - tqdm
  - yapf
  - z5py >=2.0.15

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)
N/A

- **Describe the issue that you are experiencing**
Encountered problems while solving:
  - package z5py-2.0.15-py310h5deb91e_0 requires numpy >=1.21.5,<2.0a0, but none of the providers can be installed

- **Copy error log below**
(base) PS C:\Users> mamba env create -f environment.yml -n caiman
pkgs/main/noarch                                              No change
pkgs/main/win-64                                              No change
pkgs/r/win-64                                                 No change
pkgs/r/noarch                                                 No change
pkgs/msys2/win-64                                             No change
pkgs/msys2/noarch                                             No change
conda-forge/noarch                                            No change
conda-forge/win-64                                            No change

Looking for: ["python[version='>=3.10']", 'bokeh', 'coverage', 'cython', 'future', 'h5py', 'holoviews', 'ipykernel', 'ipython', 'ipyparallel', 'jupyter', 'matplotlib', 'mypy', 'nose', 'numpy', 'numpydoc', 'opencv', 'peakutils', 'pims', 'psutil', 'pynwb', 'pyqtgraph', "scikit-image[version='>=0.19.0']", 'scikit-learn', 'scipy', "tensorflow[version='>=2.4.0']", 'tifffile', 'tk', 'tqdm', 'yapf', "z5py[version='>=2.0.15']"]

Encountered problems while solving:
  - package z5py-2.0.15-py310h5deb91e_0 requires numpy >=1.21.5,<2.0a0, but none of the providers can be installed

**Comment by kushalkolar** [comment]
As far as I know, the pre-built conda package is recommended for Windows. What if you try installing the prebuilt package directly with mamba:

```bash
mamba install -c conda-forge caiman
```

**Comment by cathefly** [comment]
Thank you @kushalkolar, you know what, it works today.

**Comment by pgunn** [comment]
I wonder if this was a momentary glitch with one of the upstream repos.
