### ISSUE TITLE
Running CAIMAN on large movies

### ISSUE THREAD

**Issue by fatihdinc** [flatironinstitute/CaImAn#1010]
Hi,

This one is also very straightforward. I am trying to run CAIMAN on a moderately large movie (200GB) and I receive the error that the computer cannot allocate 200GB size array due to RAM memory. Is there a way to run CAIMAN for movies that are larger than the RAM memory? Thank you!

Fatih

**Comment by kushalkolar** [comment]
I would try the online algorithms for something this large.

**Comment by pgunn** [comment]
If you really need to you can also set up a large swapfile, although the online methods, as Kushal said, are better at this.

**Comment by fatihdinc** [comment]
Thank you both for your answers. I would rather prefer the more accurate offline solver if I can. What if I had a 2TB movie (which I do)? Does Caiman have any inherent way to run movies that are larger than RAM memory? Or, should I go into the code and create a swapfile? Wouldn't this slow down the computation by a few factors?

My general question is, how is Caiman currently handling/planning to handle brain-wide large datasets (we currently have up to few TBs worth of data per movie) that calcium imaging nowadays is moving towards? If it cannot at the moment, that is completely fine. Would you mind letting me know so that I can consider alternatives? 

Thank you so much for your time!

**Comment by pgunn** [comment]
I don't think it's accurate to assume you'll get better results with the online algorithm; it has gotten more attention than the earlier-written offline one and I suspect for most workloads it will give you better results.

Dealing with larger datasets is one of the things I've been worrying about; chances are as the datasets get larger, we'll need some better distributed framework for working with them so they can spread the computational costs over a cluster. Alternatively, some people may find that they can downsample their movies with minimal loss to results. Whatever we develop, we're likely to do it with the online code as a basis unless we come up with something completely new.

**Comment by fatihdinc** [comment]
Thank you for the detailed response, much appreciated!

**Comment by fatihdinc** [comment]
Just a follow-up question: Is it fair to assume that the Matlab implementation of CNMF and the Python version are more or less similar, up to bug-fixes? I have been going through the code, and both seem pretty similar/almost identical? Thank you!

**Comment by pgunn** [comment]
I don't know; the Matlab implementation is something that was sunsetting when I joined the project over 5 years ago and we no longer have anyone around familiar with that codebase. Sorry.
