### ISSUE TITLE
num_frames_split not used in caiman.motion_correction.py

### ISSUE THREAD

**Issue by flmuk** [flatironinstitute/CaImAn#1011]
**Tell us a bit about your setup**: 
 1. Operating system (Linux): 
 
 2. Python version: 3.10.5
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Visual Studio Code, SLURM array jobs
 
 4. Which of the demo scripts you're using for your analysis: demo_motion_correction.ipynb
 
 5. CaImAn version: 1.9.11 
 
 6. CaImAn installation process: pip install .

- I have a question as to the code in the caiman/motion_correction.py (https://github.com/flatironinstitute/CaImAn/blob/49ad3e0754957fa14109e260f08c20f4a43f3d57/caiman/motion_correction.py)

In the demo notebook demo_motion_correction.ipynb the parameter 
"""
num_frames_split = 100 # length in frames of each chunk of the movie (to be processed in parallel)
"""

1. I suppose that this parameter, given an input file of e.g. (1000,300,300,300) (t,z,y,x), the parameter is supposed to split the processing of the input file into 10 frames of (100,300,300,300).

Q: Am I correct? When setting the 'num_frames_split' parameter, will the motion correction software keep the splitted files and use them automatically for cnmf algorithm?

2. In the documentation, under 'On file types and sizes', there is a section where it is recommended to split larger tiff files into shorter files with caiman. There is also a small script written there.
(https://caiman.readthedocs.io/en/master/On_file_types_and_sizes.html?highlight=split#on-file-types-and-sizes)

Q: Is this suggestion of splitting larger files into smaller chunks equivalent to setting the num_frames_split parameter in the motion correction object?

**Comment by pgunn** [comment]
Hello,
That variable is not actually passed into any of the Caiman APIs; it was accidentally introduced into the demo in #0f670e7d8 and never did anything.

**Comment by pgunn** [comment]
As for the num_frames_split in the motion correction object (which maybe the notebook was meant to feed into but it never got plumbed in that way), setting it there probably won't help with memory usage much.

Please let me know if you have further questions.
