### ISSUE TITLE
caimanmanager.py install fail

### ISSUE THREAD

**Issue by katesal327** [flatironinstitute/CaImAn#1012]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows 10
 2. Python version (3.x): 
 3.9.7
 3. Working environment (Python IDE/Jupyter Notebook/other):
 conda
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 recent
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
trying to install caimanmanager.py and not working. Used the instructions provided in the readme and did not work. Used the following as well and still did not unpack...also was looking for caimanmanager.py in the wrong directory...it is here: C:\Users\scott\anaconda3\envs\mesmerize-core\bin

- **Copy error log below**
>>> import sysconfig
>>> sysconfig.get_path('scripts')
'C:\\Users\\scott\\anaconda3\\envs\\mesmerize-core\\Scripts'
>>> python 'C:\\Users\\scott\\anaconda3\\envs\\mesmerize-core\\Scripts\\caimanmanager.py' install

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hello,
Can you provide the error message when the instructions first don't work?

**Comment by kas5dv** [comment]
**C:\Users\scott\anaconda3\envs\mesmerize-core\python.exe: can't open file 'C:\Users\scott\anaconda3\envs\mesmerize-core\Scripts\caimanmanager.py': [Errno 2] No such file or directory**

**Comment by kas5dv** [comment]
which makes sense because the caimanmanager.py file is not in that directory

**Comment by kas5dv** [comment]
I found a work around but wanted to let you know

**Comment by kas5dv** [comment]
is this a bug in the demo_motion_correction notebook?
Last block of the notebbook...the file is in the directory and exists

**FileNotFoundError                         Traceback (most recent call last)
Cell In [19], line 7
      5 plt.figure(figsize = (20,10))
      6 for cnt, fl, metr in zip(range(len(fls)),fls,['pw_rigid','rigid','raw']):
----> 7     with np.load(fl) as ld:
      8         print(ld.keys())
      9         print(fl)

File ~\anaconda3\envs\mesmerize-core\lib\site-packages\numpy\lib\npyio.py:417, in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    415     own_fid = False
    416 else:
--> 417     fid = stack.enter_context(open(os_fspath(file), "rb"))
    418     own_fid = True
    420 # Code to distinguish from NumPy binary files and pickles.

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\scott\\caiman_data\\example_movies\\Sue_2x_3000_40_-46_els__d1_170_d2_170_d3_1_order_F_frames_3000_._metrics.npz'**

**Comment by pgunn** [comment]
Can you cut'n'paste that filename as carefully as you can and do a `dir FILENAME` ? Perhaps there's some very subtle filename difference between what's there and what the code is looking for.

**Comment by kas5dv** [comment]
ah there are two of them...let me remove one and see if it works

**Comment by kas5dv** [comment]
dir('C:\\Users\\scott\\caiman_data\\example_movies\\Sue_2x_3000_40_-46_els__d1_170_d2_170_d3_1_order_F_frames_3000_._metrics.npz') 

output:
['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']
​

**Comment by kas5dv** [comment]
still same error

**Comment by pgunn** [comment]
Hello,
Sorry, I wasn't clear, please don't use the dir() function; use the dir command from the command prompt.

**Comment by kas5dv** [comment]
is that what you mean? sorry I am still new to python

**Comment by pgunn** [comment]
That is what I meant, and I am puzzled that you seem to be running on windows but the "dir" command doesn't seem to be working for you. Let's do this instead (do this from your python shell):

```
import glob
glob.glob('C:/Users/scott/caiman_data/example_movies/Sue*')
```

**Comment by kas5dv** [comment]
>>> glob.glob('C:/Users/scott/caiman_data/example_movies/Sue*')
['C:/Users/scott/caiman_data/example_movies\\Sue_2x_3000_40_-46.tif', 'C:/Users/scott/caiman_data/example_movies\\Sue_2x_3000_40_-46_els__d1_170_d2_170_d3_1_order_F_frames_3000_.mmap', 'C:/Users/scott/caiman_data/example_movies\\Sue_2x_3000_40_-46_els__d1_170_d2_170_d3_1_order_F_frames_3000__metrics.npz', 'C:/Users/scott/caiman_data/example_movies\\Sue_2x_3000_40_-46_metrics.npz', 'C:/Users/scott/caiman_data/example_movies\\Sue_2x_3000_40_-46_rig__d1_170_d2_170_d3_1_order_F_frames_3000_.mmap', 'C:/Users/scott/caiman_data/example_movies\\Sue_2x_3000_40_-46_rig__d1_170_d2_170_d3_1_order_F_frames_3000__metrics.npz']
>>>

**Comment by kas5dv** [comment]
okie doke, thanks

**Comment by pgunn** [comment]
I have reproduced the issue on my workstation and am working on a fix.

**Comment by EricThomson** [comment]
Just following up on this: it seems the original `caimanmanager.py` issue is resolved, and the issue is with file wrangling in the motion correction demo notebook?

**Comment by kushalkolar** [comment]
The mcorr file naming stuff was fixed, I had to update mesmerize-core for it as well a few months ago.

**Comment by EricThomson** [comment]
Ok I'll close please let me know if there are objections and I'll re-open. :)
