### ISSUE TITLE
VolPy Mask_RCNN does not work in CaImAn 1.9.9 or later

### ISSUE THREAD

**Issue by KawashimaLab** [flatironinstitute/CaImAn#1013]
- **Tell us a bit about your setup**: 

 1. Linux CentOS7
 
 2. Python 3.9.13, cuda 11, Tesla V100
 
 3. Jupyter Lab (remote)
 
 4. [demo_pipeline_voltage_imaging.py]
 
 5. CaImAn version : 1.9.9 or later
 
 6. mamba and pip

- **Describe the issue that you are experiencing**

We have been using VolPy and it has been working great with Mask_RCNN. We recently tried to upgrade CaImAn to newer versions and met trouble. The installation and most of the functionalities was OK. But MASK_RCNN module does not recognize neurons even in the demo code (0 neurons recognized).

There is no clear error code returned in the script. The code does not stop at MASK_RCNN part. 

We reverted the version to CaImAN to 1.9.8 (Tensorflow 2.7.0) and it works.  CaImAn 1.9.9 and Tensorflow 2.10.0 does not work. We tried to revert Tensorflow to 2.7.0, but couldn't figure out a way in caiman environment. 

Thanks for your help!

Takashi

**Comment by j-friedrich** [comment]
Thanks Takashi for letting us know. I tried, and ran into the same issue using a fresh clone of the current master branch. Changing the environment.yml to force python==3.9 I ended up with tensorflow 2.6 and it works. Oddly, updating tensorflow from 2.6 to 2.7 breaks it for me, whereas you say 2.7 works for you. Don't have a fix yet for this curious issue.

**Comment by pgunn** [comment]
@caichangjia This might be worth digging into

**Comment by caichangjia** [comment]
I will look into that

**Comment by KawashimaLab** [comment]
Thank you Johannes and Changjia! I just double-checked the version. In the current working CaImAn 1.9.8. environment, Python is 3.9.13. Both Tensorflow and Keras are 2.7.0.

**Comment by caichangjia** [comment]
Okay, I finally figure out the problem is because tensorflow changes function to load weights for the neural network in some version. Will ask for pull request soon. @KawashimaLab

**Comment by KawashimaLab** [comment]
Thank you so much!
