### ISSUE TITLE
Caiman not working well on linux mint 21

### ISSUE THREAD

**Issue by aidanortega** [flatironinstitute/CaImAn#1020]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linus Mint 21
 2. Python version (3.x): 
 3.10.8
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook (only with conda-forge installation method).
 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_pipeline_cnmfE.ipynb
 5. CaImAn version*: 
 1.19.12
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
ALL.

- **Describe the issue that you are experiencing**
I'll try to explain me the best and shortest. I started to work with caiman early this year in MacOS, all went well, but the most recent experiments in my lab push me to concatenate the videos to get better results but my macbook only has 8GB of RAM, so... I moved in to a desktop with linux mint 21 and 32GB no GPU... the problems starts here.... I've tried all the ways to install caiman into this PC and nothing works well:
1. First I tried to install with the development mode with "pip install -e ." and it makes a conflict with bokeh.models, speficifally with Box, It seems to have a conflict with python 3.10.8, the packages or the method change name, I dont know what happened.
2. Then, I tried the other mode without the -e, only "pip install .", so, caiman setups well buy when I tried to run de jupyter notebook said that No module named caiman.
3. The third, but not the last, was trying to push the old caiman version that was installed on my macbook to linux, but obviously that generates conflict with the versions of the libraries in the new conda in Linux.
4. Finally, the last try that I've made was trough conda-forge package installation, very easy, nothing raised an error... but now my kernel dies even if I run the first cell (the 'import' one) .

Would you please help me?

**Comment by j-friedrich** [comment]
Well, that was quick -- I bumped into the same issue today and was wondering how long it will take for someone to raise an issue ;).
The problem apparently is that holoviews isn't compatible with bokeh 3 that has just been released. I used `mamba install -c conda-forge holoviews==1.15.2` (in the activated caiman environment) to update holoviews, which automatically downgraded bokeh to version 2.4.3, and then CaImAn works perfectly. 
No idea why mamba chooses to install the most recent bokeh and an older version of holoviews instead of the most recent holoviews and an older version of bokeh, seems like a coin toss to me, but the latter works successfully. (not tested, but I suspect just downgrading bokeh could also work)

**Comment by aidanortega** [comment]
Hi there!
Thank you a lot for the fast response! Now, caiman is mounted... I've already run the demo notebook called  _demo_online_cnmfE_ but when I run the _demo_pipeline_cnmfE_ says the kernel died. Looking at the terminal it looks like a tensorflow conflict. Any idea here?

**Comment by pgunn** [comment]
@aidanortega Any chance we can get the error message you're seeing about tensorflow?

Longer term I hope that the bokeh/holoviews conflict gets worked out; in the meantime maybe we should pin holoviews 1.15.2

**Comment by aidanortega** [comment]
Sure! I add it below:
```
/tmp/ipykernel_123125/2442549514.py:2: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  get_ipython().magic(u'load_ext autoreload')
/tmp/ipykernel_123125/2442549514.py:3: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  get_ipython().magic(u'autoreload 2')
/tmp/ipykernel_123125/2442549514.py:4: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  get_ipython().magic(u'matplotlib qt')
       87055 [__init__.py:            <module>():47] [123125] Creating converter from 7 to 5
       87055 [__init__.py:            <module>():47] [123125] Creating converter from 5 to 7
       87056 [__init__.py:            <module>():47] [123125] Creating converter from 7 to 5
       87056 [__init__.py:            <module>():47] [123125] Creating converter from 5 to 7
2022-11-29 10:43:00.426074: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-29 10:43:00.520646: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/aidan/.local/lib/python3.10/site-packages/cv2/../../lib64:
2022-11-29 10:43:00.520663: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-11-29 10:43:00.535104: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
       89247 [tpu_cluster_resolver.py:            <module>():32] [123125] Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2022-11-29 10:43:00.965126: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/aidan/.local/lib/python3.10/site-packages/cv2/../../lib64:
2022-11-29 10:43:00.965183: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/aidan/.local/lib/python3.10/site-packages/cv2/../../lib64:
2022-11-29 10:43:00.965188: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```

**Comment by pgunn** [comment]
It looks like you're mixing pip local installs and conda, which is going to make problems for you. I suggest moving your python-local stuff out of the way; e.g.

`mv ~/.local/lib/python3.10 ~/old_python_310`

and see if that helps. It should. Try to avoid local environmentless installs in the future to avoid this.

**Comment by pgunn** [comment]
Pinned holoviews in dev in #fa1e3726e

**Comment by aidanortega** [comment]
Yep It works now! 
Now it raise this warning:
[IPKernelApp] WARNING | No such comm: hv-extension-comm

**Comment by pgunn** [comment]
Let's not worry about warnings; we get plenty of those. Happy that it works. The bokeh/holoviews fix will roll out with the next release, and I'll adjust the feedstock so it gets fixed there too.

**Comment by aidanortega** [comment]
Thank you a lot!
