### ISSUE TITLE
'CNMF' object has no attribute '_prepare_object'

### ISSUE THREAD

**Issue by XiaoqianSun0104** [flatironinstitute/CaImAn#1029]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS
 2. Hardware type (x86, ARM..) and RAM: X86, 16GB
 3. Python Version (e.g. 3.9): 3.8.8
 4. Caiman version (e.g. 1.9.12):1.9.11
 5. Which demo exhibits the problem (if applicable): demo_OnACID_mesoscope_sniper.py
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): anaconda
 7. Caiman version: 1.9.11
 8. Details: 
 Actually, I met several errors. I guess I solved some of those, but I'm not sure.
   - I initialized OnACID with bare initialization as instructed in sample code demo_OnACID_mesoscope_sniper.py on line 105. At this step, I met errors like: initialize_components() got an unexpected keyword argument 'rval_thr'. I commented out many paramters, such as minibatch_shape, use_dense... to make this step work
  
   - Then, at 'plot the initialization results' this step (line 115, 116), I have to change cnm_init.A to cnm_init.estimates.A, otherwise I got errors (similar for C, b, f...)
   
   - The error I'm working on is that I tried to called cnm_init._prepare_object  (line 127 in sample code), I got error message 'CNMF' object has no attribute '_prepare_object'.
 
Can someone help me to solve this question? Thanks.

**Comment by pgunn** [comment]
A lot of the content under use_cases no longer works; that's a kind of "junk drawer" (that I've been thinking about splitting off into a separate repo) and the code in it isn't kept up-to-date with the rest of the codebase.

If you're trying to get something working with your data it's better to start with one of the regular demos/notebooks.

**Comment by XiaoqianSun0104** [comment]
> A lot of the content under use_cases no longer works; that's a kind of "junk drawer" (that I've been thinking about splitting off into a separate repo) and the code in it isn't kept up-to-date with the rest of the codebase.
> 
> If you're trying to get something working with your data it's better to start with one of the regular demos/notebooks.

Thanks for the quick response. Appreciate it. Good to know that. 
Can you also please point out where can I find the definition of A, C, b, f, YrA, sn?

**Comment by pgunn** [comment]
There should be definitions for a lot of these things in the pydoc for various parts of the code (e.g. YrA's definition can be found with `pydoc caiman/source_extraction/cnmf/temporal.py` ); the docs are not perfect but we've been working on getting them good enough for people not super familiar with the code to use.

**Comment by XiaoqianSun0104** [comment]
Great! Thank you so much.

**Comment by kushalkolar** [comment]
Here's definitions for A, C, b, f, etc.
https://caiman.readthedocs.io/en/master/Getting_Started.html#result-variables-for-2p-batch-analysis

**Comment by XiaoqianSun0104** [comment]
Hi,
I have several follow up questions. Can you please take a look at them?
1. Does estimates.C represent the fluorescence of each neuron?
2. estimates.b: Set of background spatial components. What are the background spatial components? The rejected ones? 
3. Not quiet understand YrA. what does 'residual signal for each component' mean?
4. How to estimate the value of gSig?
5. I followed the demo/notebooks/demo_pipeline.jpynb and tried on my data (11190 frames). Motion correction took 90 minutes and CNMF fitting cost 10 minutes. I wonder if the time is normal?
Thank you!

**Comment by kushalkolar** [comment]
I would watch a recent talk by Andrea to understand the estimates: https://www.youtube.com/watch?v=5APzPRbzUIA 

The time spent on motion correction depends on a large variety of factors, your parameters, the amount of RAM You have (in case you overshoot your RAM and end up using swap/page file because n_processes is too high), the x-y dims of the movie, etc.

**Comment by EricThomson** [comment]
Closing because issue seems resolved. @XiaoqianSun0104 please reopen if this was a mistake.
