### ISSUE TITLE
Running Caiman GUI on 1p Data

### ISSUE THREAD

**Issue by jljavie** [flatironinstitute/CaImAn#1032]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Windows 10
 2. Hardware type (x86, ARM..) and RAM: 64-bit, x64 based processor; 32 GB RAM
 3. Python Version (e.g. 3.9): 3.10.9
 4. Caiman version (e.g. 1.9.12): 1.9.13
 5. Which demo exhibits the problem (if applicable): N/A
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): pure conda (I followed the instructions using conda-forge)
 7. Details: 
 
Hello! I am trying to run the Caiman gui (caiman_gui.py) for 1P data. I want to be able to look through neurons and discard accepted neurons as needed. When I run the gui on the demo data provided in demo_pipeline_cnmfE (the saved hdf5 and mmap), I get an error that reads

> Not launched under iPython
> Decode mmap filename C:/Users/labuser/caiman_data/example_movies\memmap_d1_128_d2_128_d3_1_order_C_frames_1000.mmap
> 
> > Traceback (most recent call last):
> >   File "C:\Users\malavikalabuser\caiman_data\demos\notebooks\caiman_gui.py", line 116, in <module>
> >     estimates.b = rotate90(estimates.b, right=True, vector=True)
> >   File "C:\Users\malavikalabuser\caiman_data\demos\notebooks\caiman_gui.py", line 101, in rotate90
> >     img = img.reshape((dims[1-a], dims[a], img.shape[1]), order='F')
> > AttributeError: 'NoneType' object has no attribute 'reshape'

When I looked at the type of variable cnm.estimates.b is, I get NoneType. I tried using .copy() which had worked to help me save the estimates.F_dff but that also did not work. 

Is there a way to use estimates.b0 instead? Or another way to get the gui to come up for 1P data?

**Comment by EricThomson** [comment]
Honestly I am not familiar with the caiman gui and am not sure if it is actively supported. @pgunn do you know?

**Comment by pgunn** [comment]
I think that's one of eftychios' experiments that hasn't seen use for a very long time:

https://github.com/flatironinstitute/CaImAn/commit/5fb432d247e96a95e031ff331a854003502bab15

I would not recommend people try to use it unless it gets some fresh attention (I had forgotten it exists).

**Comment by j-friedrich** [comment]
Replicates issue #741

**Comment by j-friedrich** [comment]
Added the solution pointed out in #741 to dev.
