### ISSUE TITLE
Use own data to analyze

### ISSUE THREAD

**Issue by ggmirandac** [flatironinstitute/CaImAn#1033]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS
 2. Hardware type (x86, ARM..) and RAM:
 3. Python Version (e.g. 3.9): 3.9
 4. Caiman version (e.g. 1.9.12): 1.9.14
 5. Which demo exhibits the problem (if applicable): I am trying to replicate the code of 
demo_pipeline_cnmfE.ipynb 
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): colab
 7. Caiman version: Last one
 8. Details: 

Hi, I am trying to replicate the pipeline that you have developed for the analysis of calcium signal images using my own data. The problem that I have stumble is that it doesn't seems to be a way to do an analysis with own data. This is because the code that I am using to handle my data is:

`
import caiman as cm
single_movie = cm.load('example_movies/demoMovie.tif')
print(single_movie.shape)
`
Which is the one that is presented in you documentation. My problem with this is that I can upload my data, but I can't work with it, because the functions that you developed use the parameter fname to work, and when I use the name of the file of the movie the program outputs:

Exception                                 Traceback (most recent call last)

[<ipython-input-30-f771e80ebb1a>](https://localhost:8080/#) in <module>
      1 #%% Run piecewise-rigid motion correction using NoRMCorre
----> 2 mc.motion_correct(save_movie=True)
      3 m_els = cm.load(mc.fname_tot_els)
      4 border_to_0 = 0 if mc.border_nan == 'copy' else mc.border_to_0
      5     # maximum shift to be used for trimming against NaNs

1 frames

[/usr/local/lib/python3.8/dist-packages/caiman/base/movies.py](https://localhost:8080/#) in load_iter(file_name, subindices, var_name_hdf5, outtype)
   2263     else:
   2264         logging.error(f"File request:[{file_name}] not found!")
-> 2265         raise Exception('File not found!')

Exception: File not found!

So, how can I use my own data to analyze it and get results from it. 

Is worth mentioning that I am using google colab to do the analysis because the software doesn't seems to work fine in my machine.

Hope to hear from you soon,

Kind regards,

Gabriel

**Comment by pgunn** [comment]
If you provide the full path to your data it should work

**Comment by ggmirandac** [comment]
Thanks for your help, another question that I have is about the DF/F values that can be extracted using your software. When I develop this analysis CaImAn outputs the following statement:
`
WARNING:root:Background components not present. Results should not be interpreted as DF/F normalized but only as detrended.
`
How can we upload the background components to CaImAn in order to generate the normalized DF/F expression

**Comment by EricThomson** [comment]
Closing because original issue was addressed. For the important issue of DF/F for 1p data, see #424, but also this comes up in Gitter fairly frequently, feel free to bring it up there @ggmirandac . It is an important issue that we need to address in the CNMFE notebook a bit better for sure!
