### ISSUE TITLE
decode mmap logging is noisy

### ISSUE THREAD

**Issue by kushalkolar** [flatironinstitute/CaImAn#1034]
the logs from this are quite noisy, can they be reduced or removed?

https://github.com/flatironinstitute/CaImAn/blob/master/caiman/paths.py#L100

**Comment by pgunn** [comment]
I'm open to it, although it can be nice for debugging to know what file we're working on (in case of a crash). Makes bug reports easier to make progress on.

**Comment by kushalkolar** [comment]
yea I was wondering if there was a way to do it so it's printed only once, during CNMF or motion correction there are constant messages every time a thread (I'm guessing) tries to access the memmap

**Comment by pgunn** [comment]
Even that could still be useful, but we could make it togglable. In general we're probably overdue to put in some effort to cut down on (and rephrase and improve) Caiman's messages. The normal logging libraries might be up to the task or we could roll our own. Unless you're keen to adjust this now, let's let this idea brew until we're in the same place later this month - can add it to the list of things we'll brainstorm/chat about?

**Comment by kushalkolar** [comment]
yup, nothing urgent but wanted to make a note of it!

**Comment by EricThomson** [comment]
Yikes we should probably push it to the `logging` module instead of a flat-out `print()` statement, so people can threshold it out.

**Comment by kushalkolar** [comment]
this is what I typically get, I haven't used the cnmf demo in a while not sure if it's like this there too 
![image](https://user-images.githubusercontent.com/9403332/235583934-4c18f225-a4bd-442d-8811-b4979d55aba3.png)

**Comment by EricThomson** [comment]
Definitely seems like a vestigial debugging step as Pat suggested (it's just printing the input to the function). It could probably just be cut, but if people want it, we could set a logger to `debug`. I'm open to either.

**Comment by EricThomson** [comment]
In #1078  just removed this print statement as it was coming up with runs of `sparse_nmf` and wasn't helpful . If anyone thinks it would be helpful, we can add a debug logger.
