### ISSUE TITLE
Save and visualize motion correction templates while code is running

### ISSUE THREAD

**Issue by RuiOSilva** [flatironinstitute/CaImAn#1038]
Some files are just too big to wait for the motion correction to run over all of it, just to find out that in the end it was not a good motion correction.

Would it be possible to add a multiseries tiff file saving of the templates, while motion correction is running online? Multiseries tiff fileallows to open one series and still keep saving onto the file without disrupting the code running and this could allow incorporation into fastplotlib in real time.

**Comment by kushalkolar** [comment]
@RuiOSilva thanks, can you make a PR to show how you implemented this? We can follow up and figure out a nice API to fetch & update these, it can be useful be many people.

**Comment by RuiOSilva** [comment]
I can try to make it, but I will have to adapt my code so it will take some time. I had to create functions almost from scratch yo adapt the code to do that and because the caiman did not open .nd2 and .ome.tif files, which I am using.
I will get back to you once I turn that into caiman-like code.

**Comment by kushalkolar** [comment]
It's always better to start with smaller PRs that do one thing, I wouldn't try to incorporate everything in one go. Just a PR of how you're saving templates as they're being created is a good start.

**Comment by RuiOSilva** [comment]
Hi Kushal,
I am not very used to working in GitHub in big public repositories, only small projects. Can you explain me or send me a link on how I would create a branch for CaImAn? I know how to do a fork a create branches for PRs that I need on my own fork but I do not have access to create branches on yours. Is that any other way to do it?

**Comment by EricThomson** [comment]
It would be nice to make a version of the motion correction algorithm that takes in start/stop frame as a parameter, so you can run it on a partial movie just to get a sense for how good your parameters are without having to run it on your whole movie. I'm not sure how the online versions differ, so can't say anything about that, but the offline versions this should be relatively easy to do and could be really useful to quickly iterate through parameters. I am going to look into doing this.
