### ISSUE TITLE
ImportError: The 'platformdirs' package is required

### ISSUE THREAD

**Issue by njm94** [flatironinstitute/CaImAn#1044]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Windows8
 2. Hardware type (x86, ARM..) and RAM: x86, 64GB
 3. Python Version (e.g. 3.9): 3.10
 4. Caiman version (e.g. 1.9.12): 1.9.13
 5. Which demo exhibits the problem (if applicable): caimanmanager.py installation
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): mamba
 7. Caiman version: 1.9.13
 8. Details: I am getting error while installing caimanmanager.py. I am pasting the command I run and the output below. I have already tried to install `platformdirs`  using mamba/conda/pip and the issue is still persisting. I am not sure what the recourse is.

>  (mescore) C:\Users\user>python C:\Users\user\anaconda3\envs\mescore\bin\caimanma
> nager.py install
> Traceback (most recent call last):
>   File "C:\Users\user\anaconda3\envs\mescore\bin\caimanmanager.py", line 16, in
> <module>
>     from caiman.paths import caiman_datadir
>   File "C:\Users\user\anaconda3\envs\mescore\lib\site-packages\caiman\__init__.p
> y", line 3, in <module>
>     import pkg_resources
>   File "C:\Users\user\anaconda3\envs\mescore\lib\site-packages\pkg_resources\__i
> nit__.py", line 82, in <module>
>     from pkg_resources.extern import platformdirs
>   File "C:\Users\user\anaconda3\envs\mescore\lib\site-packages\pkg_resources\ext
> ern\__init__.py", line 52, in create_module
>     return self.load_module(spec.name)
>   File "C:\Users\user\anaconda3\envs\mescore\lib\site-packages\pkg_resources\ext
> ern\__init__.py", line 44, in load_module
>     raise ImportError(
> ImportError: The 'platformdirs' package is required; normally this is bundled wi
> th this package so if you get this warning, consult the packager of your distrib
> ution.
>

**Comment by kushalkolar** [comment]
maybe try installing using `miniforge` instead: https://github.com/conda-forge/miniforge#miniforge3 

follow the same instructions, use the miniforge prompt, it comes preloaded with mamba

**Comment by njm94** [comment]
Thanks @kushalkolar that worked.
Just a note to others, miniforge did not come preinstalled with mamba but installing it with the command given worked fine.

**Comment by kushalkolar** [comment]
sorry if you use mambaforge it should come preinstalled with mamba, and you still use the miniforge prompt (the recent splintering of the conda space is kinda confusing) https://github.com/conda-forge/miniforge#mambaforge

**Comment by Sky-ShiKeyue** [comment]
> Thanks @kushalkolar that worked. Just a note to others, miniforge did not come preinstalled with mamba but installing it with the command given worked fine.

Hi! I have the same problem, did you use miniforge prompt to reinstall everything according to the instruction? My problem seems to be still present.
