### ISSUE TITLE
3D non-rigid motion correction crashes with multi-file recordings

### ISSUE THREAD

**Issue by oterocoronel** [flatironinstitute/CaImAn#1045]
My setup:
 1. Operating System (Linux, MacOS, Windows): Linux - Ubuntu
 2. Hardware type (x86, ARM..) and RAM: 256GB RAM
 3. Python Version (e.g. 3.9): Python 3.10.9
 4. Caiman version (e.g. 1.9.12): 1.9.13
 5. Which demo exhibits the problem (if applicable): demo_caiman_cnmf_3D.ipynb
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): mamba create -n caiman -c conda-forge caiman
 8. Details: 

I have two tif files with shape 1882, 337, 356, 30 (f,x,y,z) on which I am trying to do 3D motion correction, but this line is crashing for me:

> %%capture
> #%% Run motion correction using NoRMCorre
> mc.motion_correct(save_movie=True)

I think the rigid MC runs fine for the two files, same goes for the first non-rigid MC of the first file, but when starting with the second file I get these errors: 

> RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/home/freiwald/.mambaforge/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/freiwald/.mambaforge/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
>     return list(map(*args))
>   File "/home/freiwald/.mambaforge/envs/caiman/lib/python3.10/site-packages/caiman/motion_correction.py", line 3100, in tile_and_correct_wrapper
>     template = template[indices]
> IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
> """

And at the end:

> File ~/.mambaforge/envs/caiman/lib/python3.10/site-packages/caiman/motion_correction.py:3215, in motion_correction_piecewise(fname, splits, strides, overlaps, add_to_movie, template, max_shifts, max_deviation_rigid, newoverlaps, newstrides, upsample_factor_grid, order, dview, save_movie, base_name, subidx, num_splits, shifts_opencv, nonneg_movie, gSig_filt, use_cuda, border_nan, var_name_hdf5, is3D, indices)
>    3213     dview.map(close_cuda_process, range(len(pars)))
>    3214 elif 'multiprocessing' in str(type(dview)):
> -> 3215     res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)
>    3216 else:
>    3217     res = dview.map_sync(tile_and_correct_wrapper, pars)
> 
> File ~/.mambaforge/envs/caiman/lib/python3.10/multiprocessing/pool.py:774, in ApplyResult.get(self, timeout)
>     772     return self._value
>     773 else:
> --> 774     raise self._value
> 
> IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

I have been monitoring the RAM and it never goes above 80GB (for a maximum of 256GB).

After some checks, there seems to be an issue with the elastic 3D MC ('pw_rigid': True) when using more than 1 file containing 4D data. I confirmed this by going to the original demo and concatenating 2 copies of the same demo-data, and the error was the same.

**Comment by j-friedrich** [comment]
One has to use `new_templ = np.nanmedian(np.stack([r[-1] for r in res_el]), 0)` to construct the new template -- instead of `new_templ = np.nanmedian(np.dstack([r[-1] for r in res_el]), -1)` which works only for 2D data -- in `motion_correct_batch_pwrigid` analogously to how it is already done in `motion_correct_batch_rigid`.

Fixed in dev.
