### ISSUE TITLE
Caimanmanager.py install fail

### ISSUE THREAD

**Issue by Sky-ShiKeyue** [flatironinstitute/CaImAn#1046]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Windows
 2. Hardware type (x86, ARM..) and RAM: x86, 64
 3. Python Version (e.g. 3.9): 3.10.9
 4. Caiman version (e.g. 1.9.12): 1.9.12
 5. Which demo exhibits the problem (if applicable):
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): pure conda
 7. Caiman version: 
 8. Details: 
When I try to install caimanmanager.py, it happens an error:
(mescore) C:\Users\sky\anaconda3\envs\mescore\bin>python C:\Users\sky\anaconda3\envs\mesco
re\bin\caimanmanager.py install

ImportError: The 'platformdirs' package is required; normally this is bundled with this pa
ckage so if you get this warning, consult the packager of your distribution.

but I did install the 'platformdirs', and I can find it in my conda list:
platformdirs              2.5.2           py310haa95532_0

**Comment by pgunn** [comment]
Please file this bug against the mesmerise package; caiman itself doesn't, as far as I know, have this problem.
