### ISSUE TITLE
Motion Correction: IndexError

### ISSUE THREAD

**Issue by ggmirandac** [flatironinstitute/CaImAn#1047]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS
 3. Hardware type (x86, ARM..) and RAM: M1
 4. Python Version (e.g. 3.9): 3.9
 5. Caiman version (e.g. 1.9.12): last one
 6. Which demo exhibits the problem (if applicable): demo_pipeline_cnmfE.ipynb 
 7. How you installed Caiman (pure conda, conda + compile, colab, ..): colab
 8. Caiman version: 
 9. Details: 

When I try to run the video .tif that I have on the motion correction algorithm, I stumble into the following problem:

```
IndexError                                Traceback (most recent call last)

[<ipython-input-62-029d7e862888>](https://localhost:8080/#) in <module>
      3   # thus is the cored that will perform the correction
      4     mc = MotionCorrect(fnames, dview=dview, **opts.get_group('motion'))
----> 5     mc.motion_correct(save_movie=True)
      6     fname_mc = mc.fname_tot_els if pw_rigid else mc.fname_tot_rig
      7     if pw_rigid:

5 frames

[/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py](https://localhost:8080/#) in _getitem(self, key, validate, cache, aspage)
   7152             key %= len(self)
   7153         elif self._indexed and key >= len(pages):
-> 7154             raise IndexError(f'index {key} out of range({len(pages)})')
   7155 
   7156         tiffpage = TiffPage if aspage else self._tiffpage

IndexError: index 31 out of range(31)
```
I am trying to run a .tif file that contains 31 frames.

These are the parameters that I am using in the motion correction algorithm:

```
# Parameters which are dependent of the data set
frate = 10                       # The rate of the movie frames
decay_time = 0.4                 # This is the lenght of the transient, the units are seconds

# Parameters of the motion correction process
motion_correct = True    # This will flag the performing motion correction
pw_rigid = False         # This is a flag for the  performing piecewise-rigid motion correction (otherwise just rigid)
gSig_filt = (3, 3)       # This is the size of high pass spatial filtering, it is used when we are working with 1p data
max_shifts = (5, 5)      # This parameter marks the maximum allow rigid shift
strides = (48, 48)       # Is going to start a new patch of pw-rigid motion correction every x pixels
overlaps = (24, 24)      # Quantifies the overlap of patches(size of patch strides+overlaps)
max_deviation_rigid = 3  # Indicates the maximun deviation allow for a patch with respect to rigid shift
border_nan = 'copy'      # Indicates the replication along the border
splits_rig = 10          # 
shifts_opencv = True  # flag for correcting motion using bicubic interpolation (otherwise FFT interpolation is used)
# Now we store all the paremeters in a dictionary
mc_dict = {
    'fnames': fnames, # note that here we pass the file path
    'fr': frate,
    'decay_time': decay_time,
    'pw_rigid': pw_rigid,
    'max_shifts': max_shifts,
    'gSig_filt': gSig_filt,
    'strides': strides,
    'overlaps': overlaps,
    'max_deviation_rigid': max_deviation_rigid,
    'border_nan': border_nan,
    'splits_rig': splits_rig,
    'path_to_model': path_to_model, # here we pass tha path to the model's folder
    'shifts_opencv': shifts_opencv
}

# Finally we store the parameters in an object, this object is going to be read by the program
opts = params.CNMFParams(params_dict=mc_dict)
```

Kind regards

**Comment by kushalkolar** [comment]
I think you need a minimum of 200 or 1000 frames

**Comment by ggmirandac** [comment]
I don't think that's the problem, because I have analyzed data sets containing 30 frames

**Comment by kushalkolar** [comment]
cnmf might work with fewer frames, but I'm pretty sure normcorre requires many more frames for template generation

**Comment by EricThomson** [comment]
@ggmirandac I'm not sure what you have analyzed with 30 frames I'd be curious to see that! From what I've seen typically have problems when they are analyzing fewer than 200 frames. It would be nice to just have set numbers with the default parameters "If you have fewer than N frames, this will not work", and maybe just have caiman throw a clear error/warning message that it won't work.

**Comment by EricThomson** [comment]
Closing this is an issue we need to add better error messages for, definitely. Please reopen if you feel it needs more attention @ggmirandac

**Comment by ggmirandac** [comment]
Hi, 

I am back. 

I am here because I stumble on the same error. Now performing the cnmf_e algorithm both in batch and online. 

In this case, I get the following error:

`
/Users/gmiranda/micromamba/envs/ca_techniques/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:2017: UserWarning: nperseg = 256 is greater than input length  = 91, using nperseg = 91
  warnings.warn('nperseg = {0:d} is greater than input length '
`

I want to know if there is any way to change the parameter nperseg to allow analyzing .tif files with fewer frames. In this case, I am analyzing a 181 frames .tif file. 

The issue is that I am just the data analyst and I can't do anything on the experimental side of the experiment. Is there a way to perform the analysis even though the number of frames is smaller?

Best regards

**Comment by EricThomson** [comment]
I am not sure who will get to this in the near future: did you try playing with `nperseg` ?  If your goal is just to test algorithms and see how they work, take the movie and concatenate with itself a few times (maybe reversed so it connects to itself).  You are in such small sample regime, and things are just going to break there with signal processing algorithms that caiman calls (as happened here), it will just be hard to help with this I'm sorry. It is a very unusual corner case that we don't really focus on.  I'm not sure what data you are getting, but have your experimentalists reach out to me because this is not standard data they need to help you by getting you better data. :smile:

**Comment by ggmirandac** [comment]
Hi, thanks for your answer. And yes, hopefully the experimentalist understand that we need good data for the analysis :(.
How do you access to that parameter?

**Comment by EricThomson** [comment]
That isn't in caiman specifically but part of scipy so you would need to track it down.  But note it looks like you are getting a warning not an error, and it is resetting it for you automatically. This warning shouldn't actually stop the code from running.
