### ISSUE TITLE
1p Motion Correction

### ISSUE THREAD

**Issue by yunip20** [flatironinstitute/CaImAn#1052]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS
 3. Hardware type (x86, ARM..) and RAM: intel
 4. Python Version (e.g. 3.9): 3.10.9
 6. Caiman version (e.g. 1.9.12): 1.9.13
 7. How you installed Caiman (pure conda, conda + compile, colab, ..): conda 

Details: 
I'm fairly new to CaImAn and had a general question on optimizing the parameters to get desired outputs. I have been using the demo_pipeline_cnmfE to get traces from a 1photon video, which is in an avi file format.  

When I run with these parameters: 
```
motion_correct = True    # flag for performing motion correction
pw_rigid = False         # flag for performing piecewise-rigid motion correction (otherwise just rigid)
gSig_filt = (5, 5)       # size of high pass spatial filtering, used in 1p data
max_shifts = (10, 10)      # maximum allowed rigid shift
strides = (48, 48)       # start a new patch for pw-rigid motion correction every x pixels
overlaps = (24, 24)      # overlap between pathes (size of patch strides+overlaps)
max_deviation_rigid = 3  # maximum deviation allowed for patch with respect to rigid shifts
border_nan = 'copy'      # replicate values along the boundaries

```
I get this output: 
![Figure_1](https://user-images.githubusercontent.com/91842048/228471881-d60320dc-572b-47a8-8c87-678d8ed65805.png)
 
I played around with the **gSig_filt**, and increasing the value seems to allow for better motion detections (compared to **gSig_filt** of (3,3) where there were no marked x,y shifts). I read over the documentation, but am still not sure how the gSig_filt affects the data. Also, does decreasing the strides and overlaps values allow for more precise motion correction? Thank you!

**Comment by kushalkolar** [comment]
The `gSig_filt` is the sigma of a gaussian kernel used for high-pass filtering of the image data, it brings out the "landmarks" in the imaging data which makes motion correction better.

For example the bottom images here are filtered:

https://user-images.githubusercontent.com/9403332/228709575-b8f04b96-ef3c-44fd-80cd-7d57aa70bf03.mp4

btw, for parameter optimization you might want to try `mesmerize-core`, there is a cnmfe demo notebook and it has visualizations for `gSig_filt` https://github.com/nel-lab/mesmerize-core

**Comment by yunip20** [comment]
Great, thank you!
