### ISSUE TITLE
correlation_pnr fails on 4D arrays

### ISSUE THREAD

**Issue by oterocoronel** [flatironinstitute/CaImAn#1055]
1. Operating System (Linux, MacOS, Windows): Linux
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): conda
 7. Details: 
 
correlation_pnr fails on 4D arrays. Running this:

```
Y = np.zeros((40,40,10,10))
cn, pnr = cm.summary_images.correlation_pnr(Y)
``` 

... results in:
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[13], line 1
----> 1 cn, pnr = cm.summary_images.correlation_pnr(Y)

File ~/.mambaforge/envs/caiman-spyder/lib/python3.10/site-packages/caiman/summary_images.py:324, in correlation_pnr(Y, gSig, center_psf, swap_dim, background_filter)
    321     Y = np.transpose(Y, tuple(np.hstack((Y.ndim - 1, list(range(Y.ndim))[:-1]))))
    323 # parameters
--> 324 _, d1, d2 = Y.shape
    325 data_raw = Y.reshape(-1, d1, d2).astype('float32')
    327 # filter data

ValueError: too many values to unpack (expected 3)
```

The documentation of caiman.summary_images.correlation_pnr says it supports 4D arrays:

`Args:
        Y:  np.ndarray (3D or 4D).
            Input movie data in 3D or 4D format`

**Comment by j-friedrich** [comment]
correlation_pnr hasn't been implemented for volumetric data, only for 1p
data. However, local_correlations_fft already works with volumetric data.
