### ISSUE TITLE
Caiman not found M1 Mac

### ISSUE THREAD

**Issue by ambtetl** [flatironinstitute/CaImAn#1057]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS
 2. Hardware type (x86, ARM..) and RAM: M1 Max 64GB
 3. Python Version (e.g. 3.9): Python 3.6.13
 4. Caiman version (e.g. 1.9.12): 1.9.14
 5. Which demo exhibits the problem (if applicable):
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): mamba
 7. Details: 
I previously had an issue on a pc but the lab has since acquired a M1 Max Mac. I am currently trying to load caiman in the legacy version of mesmerize. When loading, there is the following error message " The caiman package could not be found in your python environment. Caiman features will not work. ". Also in the terminal there are the following messages as well "/Users/2Photon/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/mesmerize/common/configuration.py:38: UserWarning: Caiman package not found. Caiman features will be disabled.
  "Caiman package not found. "
/Users/2Photon/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/mesmerize/common/configuration.py:49: UserWarning: tensorflow not found. Nuset segmentation will be disabled
  "tensorflow not found. Nuset segmentation will be disabled"
/Users/2Photon/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)".

I have seen that there were previous issues with tensorflow with M1 Max. Is there a specific work around that is compatible for M1 and python 3.6? Ones I have found need newer versions of python. 

I know this is the optimal version of working with mesmerize but any assistance would be greatly appreciated.

**Comment by ambtetl** [comment]
With using mesmerize-core would there still be an issue with an M1 Mac?

**Comment by kushalkolar** [comment]
There were a number of people with M1 macs that were able to run it at the
January workshop. The bottleneck with new hardware or software is usually
tensorflow.

**Comment by pgunn** [comment]
It should be an option to use the x86 version of everything with rosetta?

**Comment by kushalkolar** [comment]
She's trying to use the old mesmerize desktop application which requires an
old caiman, I think it might even be tensorflow 1.15 old.

**Comment by EricThomson** [comment]
Closing because not a caiman issue. Please open issue at mesmerize if you need help: [.](https://github.com/kushalkolar/MESmerize/issues)
