### ISSUE TITLE
Q about differences in results using batch and online methods

### ISSUE THREAD

**Issue by XiaoqianSun0104** [flatironinstitute/CaImAn#1059]
Hi,

I used both batch and online methods to process one same tif file.
For batch method, I did motion correction, CNMF and seeded CNMF. For online method, I used OnACID and fit_online(). 
I used `nb_view_components` to plot fluorescence got from these two methods and I have several questions.

1. the denoised (red) trace in online result doesn't have negative part, more like denoised version compared to that from batch result.
2. why y-axis scale is so different, for online, it ranges from 0-0.4, but for batch, it ranges from -20 to 100
3. the correlation image for batch is much clearer, with less background noise. Does that mean more noise was added to neuron signals?

<img width="1189" alt="batch_example" src="https://user-images.githubusercontent.com/31903092/231322821-30c22f25-17c1-4d66-b695-5ed6cd21043f.png">
<img width="1158" alt="online_example" src="https://user-images.githubusercontent.com/31903092/231322824-6aa90f43-7273-49dd-93bb-017c5a33a611.png">

can you please take a look at it for me? Thank you.

**Comment by EricThomson** [comment]
Some good questions I'm not sure of the answers to all of them. In terms of negative values for batch processing, there is a useful discussion here that may help: https://github.com/flatironinstitute/CaImAn/issues/987 

In terms of the corr image looking different, my guess is that the online is using fewer frames to calculate/display it so it is noisier, or maybe there is a difference in the vmin/vmax in the display? I would have to look at it, and it will be a few days before I can.

In terms of the scaling, that is more puzzling: I don't run online processing and this is something I need to start looking into over the next few weeks (@j-friedrich might know).

**Comment by XiaoqianSun0104** [comment]
Thank you for the reply!

Also, I did some tests today and found that flag `use_residuals` doesn't work in estimates.detrend_df_f(), with use_residuals=False, I still got noised dff compare with that using utilities.detrend_df_f() without YrA as input. 

![image](https://user-images.githubusercontent.com/31903092/231528647-26680e86-d29b-45c3-ac6d-ffcbeee5d7b0.png)

**Comment by XiaoqianSun0104** [comment]
Also, the tif I'm working on contains 11190 frames with size (512, 512) and we expect around 50 neurons. With that, which method do you recommend, batch or online? Greatly appreciate your response.

**Comment by XiaoqianSun0104** [comment]
That makes sense. Much appreciate your response and instructions. 
For now, RAM is not a problem. I submitted jobs to my institution's computing platform to process data and it took about 40-50 minutes to process one tif, including motion correction, memory mapping, CNMF, seeded CNMF and saving results. 
I guess I'll continue using offline method. Thank you.

**Comment by EricThomson** [comment]
Closing because issue seems resolved. Please reopen if this was a mistake, @XiaoqianSun0104
