### ISSUE TITLE
Cannot find min_size and max_size in cnmf.params

### ISSUE THREAD

**Issue by oterocoronel** [flatironinstitute/CaImAn#1061]
Here are the spatial parameters that I get after running cnm.params:

```
spatial_params:

{'block_size_spat': 1000,
 'dist': 3,
 'expandCore': array([[0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0]]),
 'extract_cc': True,
 'maxthr': 0.1,
 'medw': None,
 'method_exp': 'ellipse',
 'method_ls': 'lasso_lars',
 'n_pixels_per_process': 1000,
 'nb': 1,
 'normalize_yyt_one': True,
 'nrgthr': 0.9999,
 'num_blocks_per_run_spat': 20,
 'se': array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]], dtype=uint8),
 'ss': None,
 'thr_method': 'nrg',
 'update_background_components': True}
```

It seems like the min_size and max_size parameters are missing in there. These should be used during spatial update when method_exp is set to ellipse. It is possible to pass them directly if one invokes caiman.source_extraction.cnmf.spatial.update_spatial_components() directly, but I am invoking refit(), which in turn calls update_spatial_components() under the hood, so I don't know how to pass min_size and max_size.

**Comment by EricThomson** [comment]
I believe `min_size` and `max_size` are not CNMF parameters that you directly pass anywhere. They are parameters of the "hidden" `update_spatial_components()` function that you don't directly control. The way it these parameters are actually set depends on your use case (e.g., iirc it is sometimes set based on `gSig`). It would be nice to expose/explain more of these hidden algorithm mechanics and what is going on under the hood, and how they are set.

**Comment by EricThomson** [comment]
Closing as I believe this is resolved. Please reopen if this was a mistake, @oterocoronel
