### ISSUE TITLE
Pass file list to load_iter

### ISSUE THREAD

**Issue by Marekthegeck** [flatironinstitute/CaImAn#1073]
Hey, 
just a quick question: How can I pass a list to the iterator in the realtime_cnmfE demo? It demands a single file as input, however, all my recordings are split up into avi files containing 1000 frames each. So do I have to conc them beforehand or is there a simple way to pass a file list just as to load_movie_chain?

Many thanks

Marek

**Comment by pgunn** [comment]
I think you'd need to make a few changes to the notebook (@j-friedrich correct me if I'm wrong on any of this).

For the call to get_iterator that loads about 3000 frames for initialisation, you can probably comment out the call to get_iterator, instead just do a cm.load of your first data file (maybe 1000 frames is enough? If not, you could do maybe 3 of them to match the demo more closely); that will get you a movie object that the notebook can use for a few steps.

Then later, in the cell that does `cn, pnr = `, where it reloads the entire file, you can pass your entire list. I believe this will match intent of what the demo is doing.

(Let's see if Johannes agrees)

**Comment by j-friedrich** [comment]
You can call load_iter recursively for each file:
```
def load_iter(file_name):
    if isinstance(file_name, list) or isinstance(file_name, tuple):
        for fname in file_name:
            iterator = cm.base.movies.load_iter(fname)
            while True:
                try:
                    yield next(iterator)
                except:
                    break
    else:
        """already exisiting code goes here"""
```
now you get the same behavior for load_iter when passing a list of files instead of a single file.

I added the above code to the dev branch.
