### ISSUE TITLE
Notebook Demo Error

### ISSUE THREAD

**Issue by ambtetl** [flatironinstitute/CaImAn#1074]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS
 2. Hardware type (x86, ARM..) and RAM: 
 3. Python Version (e.g. 3.9):3.10
 4. Caiman version (e.g. 1.9.12): 1.9.14
 5. Which demo exhibits the problem (if applicable): mcorr_cnmf.ipynb
 6. How you installed Caiman (pure conda, conda + compile, colab, ..):conda
 7. Details: When running through the mcorr_cnmf.ipynb demo notebook and trying to create a new batch I receive the following error. There were no previous errors. 

# create a new batch
df = create_batch(batch_path)
# to load existing batches use `load_batch()`
# df = load_batch(batch_path)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[12], line 2
      1 # create a new batch
----> 2 df = create_batch(batch_path)
      3 # to load existing batches use `load_batch()`
      4 # df = load_batch(batch_path)

NameError: name 'batch_path' is not defined

**Comment by pgunn** [comment]
Hello,
I don't know of a notebook with that name in Caiman, nor do we have functions with those names. Are you sure this is meant to be a Caiman issue?

**Comment by EricThomson** [comment]
Looks like mesmerize-core notebook-- I would open an issue there @ambtetl

**Comment by ambtetl** [comment]
@EricThomson Thank you. I wasn't sure which one would be more appropriate.
