### ISSUE TITLE
Can't install caiman

### ISSUE THREAD

**Issue by rosullivan1226** [flatironinstitute/CaImAn#1077]
Appreciate the help!!

Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Windows running Windows 11
 2. Hardware type (x86, ARM..) and RAM: 192 GB RAM
 3. Python Version (e.g. 3.9): 3.10.9
 4. Caiman version (e.g. 1.9.12): ...
 5. Which demo exhibits the problem (if applicable): ...
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): ...
 7. Details: trying to install caiman and it won't work. I follow all the steps and create the environment, but the caiman folder that emerges in my envs folder is empty and when i go to install the caiman manager it says it does not exist

**Comment by pgunn** [comment]
Hello,
What command(s) did you use to create the conda environment, and what messages did you get from it? What happens when you do `conda env list` ?

**Comment by rosullivan1226** [comment]
Hi! I used the 'mamba create -n caiman -c conda-forge caiman' command. It seems to go okay until the verifying transaction step where it says failed. And then it has a handful of conda erification errors regarding the tensorflow-base . when I type conda env list it just says base

**Comment by pgunn** [comment]
Can you get me the text immediately before the `verifying transaction` step and then any errors after it? It sounds like this is failing somewhere in conda rather than our code (we'll still try to help you, of course).

**Comment by rosullivan1226** [comment]
Got it. Thank you! Errors are posted below
Downloading and Extracting Packages                                                                                                                                                                                                             Preparing transaction: done                                                                                             Verifying transaction: failed                                                                                                                                                                                                                   CondaVerificationError: The package for tensorflow-base located at C:\Users\rosullivan\AppData\Local\anaconda3\pkgs\ten0appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/external/llvm-project/mlir/_virtual_includes/Af'specified in the package manifest cannot be found.                                                                                                                                                                                              CondaVerificationError: The package for tensorflow-base located at C:\Users\rosullivan\AppData\Local\anaconda3\pkgs\ten0appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/external/llvm-project/mlir/_virtual_includes/Al'specified in the package manifest cannot be found.                                                                                                                                                                                              CondaVerificationError: The package for tensorflow-base located at C:\Users\rosullivan\AppData\Local\anaconda3\pkgs\ten0appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/external/llvm-project/mlir/_virtual_includes/Bu'specified in the package manifest cannot be found.                                                                                                                                                                                              CondaVerificationError: The package for tensorflow-base located at C:\Users\rosullivan\AppData\Local\anaconda3\pkgs\ten0appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/external/llvm-project/mlir/_virtual_includes/Bu'specified in the package manifest cannot be found.                                                                                                                                                                                              CondaVerificationError: The package for tensorflow-base located at C:\Users\rosullivan\AppData\Local\anaconda3\pkgs\ten0appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/external/llvm-project/mlir/_virtual_includes/Pa'specified in the package manifest cannot be found.                                                                                                                                                                                              CondaVerificationError: The package for tensorflow-base located at C:\Users\rosullivan\AppData\Local\anaconda3\pkgs\ten0appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/tensorflow/compiler/mlir/hlo/_virtual_includes/'specified in the package manifest cannot be found.                                                                                                                                                                                              CondaVerificationError: The package for tensorflow-base located at C:\Users\rosullivan\AppData\Local\anaconda3\pkgs\ten0appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/tensorflow/compiler/mlir/hlo/_virtual_includes/'specified in the package manifest cannot be found.                                                                                                                                                                                              CondaVerificationError: The package for tensorflow-base located at C:\Users\rosullivan\AppData\Local\anaconda3\pkgs\ten0appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/tensorflow/compiler/mlir/hlo/_virtual_includes/'specified in the package manifest cannot be found.

**Comment by pgunn** [comment]
Two things:
1) Are you anywhere close to having your C:\ volume full? If not, have you bumped into filesystem corruption of any kind?
2) If neither of the above are true, try doing this: `conda clean --all` and then retry making the environment

**Comment by rosullivan1226** [comment]
C is not near full and I have not run into any issues with corruption. I try the conda clean --all and I get an error.

(base) C:\Users\rosullivan>conda clean --all                                                                            Will remove 345 (1003.1 MB) tarball(s).                                                                                 Proceed ([y]/n)? y                                                                                                                                                                                                                              Will remove 1 index cache(s).                                                                                           Proceed ([y]/n)? y                                                                                                                                                                                                                                                                                                                                                      # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<                                                                                                                                                                                        Traceback (most recent call last):                                                                                        File "C:\Users\rosullivan\AppData\Local\anaconda3\lib\site-packages\conda\exceptions.py", line 1132, in __call__          return func(*args, **kwargs)                                                                                          File "C:\Users\rosullivan\AppData\Local\anaconda3\lib\site-packages\conda\cli\main.py", line 69, in main_subshell         exit_code = do_call(args, p)                                                                                          File "C:\Users\rosullivan\AppData\Local\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 122, in do_call                                                                                                                            return getattr(module, func_name)(args, parser)                                                                       File "C:\Users\rosullivan\AppData\Local\anaconda3\lib\site-packages\conda\cli\main_clean.py", line 298, in execute        json_result = _execute(args, parser)                                                                                  File "C:\Users\rosullivan\AppData\Local\anaconda3\lib\site-packages\conda\cli\main_clean.py", line 282, in _execute                                                                                                                               json_result["packages"] = pkgs = find_pkgs()                                                                          File "C:\Users\rosullivan\AppData\Local\anaconda3\lib\site-packages\conda\cli\main_clean.py", line 98, in find_pkgs                                                                                                                               size = sum(                                                                                                           File "C:\Users\rosullivan\AppData\Local\anaconda3\lib\site-packages\conda\cli\main_clean.py", line 99, in <genexpr>                                                                                                                               _get_size(root, file, warnings=warnings)                                                                              File "C:\Users\rosullivan\AppData\Local\anaconda3\lib\site-packages\conda\cli\main_clean.py", line 28, in _get_size                                                                                                                               if stat.st_nlink > 1:                                                                                               UnboundLocalError: local variable 'stat' referenced before assignment                                                                                                                                                                       `$ C:\Users\rosullivan\AppData\Local\anaconda3\Scripts\conda-script.py clean --all`                                                                                                                                                               environment variables:                                                                                                                 CIO_TEST=<not set>                                                                                             CONDA_DEFAULT_ENV=base                                                                                                          CONDA_EXE=C:\Users\rosullivan\AppData\Local\anaconda3\condabin\..\Scripts\conda.                                                  exe                                                                                                          CONDA_EXES="C:\Users\rosullivan\AppData\Local\anaconda3\condabin\..\Scripts\conda                                                  .exe"                                                                                                      CONDA_PREFIX=C:\Users\rosullivan\AppData\Local\anaconda3                                                       CONDA_PROMPT_MODIFIER=(base)                                                                                                 CONDA_PYTHON_EXE=C:\Users\rosullivan\AppData\Local\anaconda3\python.exe                                                       CONDA_ROOT=C:\Users\rosullivan\AppData\Local\anaconda3                                                                 CONDA_SHLVL=1                                                                                                        CURL_CA_BUNDLE=<not set>                                                                                                      HOMEPATH=\Users\rosullivan                                                                                            LD_PRELOAD=<not set>                                                                                                          PATH=C:\Users\rosullivan\AppData\Local\anaconda3;C:\Users\rosullivan\AppDat                                                  a\Local\anaconda3\Library\mingw-                                                                                        w64\bin;C:\Users\rosullivan\AppData\Local\anaconda3\Library\usr\bin;C:                                                  \Users\rosullivan\AppData\Local\anaconda3\Library\bin;C:\Users\rosulli                                                  van\AppData\Local\anaconda3\Scripts;C:\Users\rosullivan\AppData\Local\                                                  anaconda3\bin;C:\Users\rosullivan\AppData\Local\anaconda3\condabin;C:\                                                  Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System                                                  32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program                                                        Files\MATLAB\R2023a\runtime\win64;C:\Program                                                                            Files\MATLAB\R2023a\bin;C:\Program                                                                                      Files\MATLAB\R2017b\runtime\win64;C:\Program                                                                            Files\MATLAB\R2017b\bin;C:\Program Files (x86)\NVIDIA                                                                   Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA Nv                                                  DLISR;C:\Users\rosullivan\AppData\Local\anaconda3;C:\Users\rosullivan\                                                  AppData\Local\anaconda3\Library\mingw-                                                                                  w64\bin;C:\Users\rosullivan\AppData\Local\anaconda3\Library\usr\bin;C:                                                  \Users\rosullivan\AppData\Local\anaconda3\Library\bin;C:\Users\rosulli                                                  van\AppData\Local\anaconda3\Scripts;C:\Users\rosullivan\AppData\Local\                                                  Programs\Python\Python311\Scripts;C:\Users\rosullivan\AppData\Local\Pr                                                  ograms\Python\Python311;C:\Users\rosullivan\AppData\Local\Microsoft\Wi                                                  ndowsApps                                                                                                  PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows                                                  PowerShell\v1.0\Modules                                                                              REQUESTS_CA_BUNDLE=<not set>                                                                                                 SSL_CERT_FILE=<not set>                                                                                                                                                                                                                  active environment : base                                                                                              active env location : C:\Users\rosullivan\AppData\Local\anaconda3                                                               shell level : 1                                                                                                    user config file : C:\Users\rosullivan\.condarc                                                                   populated config files : C:\Users\rosullivan\.condarc                                                                            conda version : 23.3.1                                                                                            conda-build version : 3.24.0                                                                                                 python version : 3.10.9.final.0                                                                                       virtual packages : __archspec=1=x86_64                                                                                                     __cuda=12.1=0                                                                                                           __win=0=0                                                                                            base environment : C:\Users\rosullivan\AppData\Local\anaconda3  (writable)                                             conda av data dir : C:\Users\rosullivan\AppData\Local\anaconda3\etc\conda                                           conda av metadata url : None                                                                                                     channel URLs : https://repo.anaconda.com/pkgs/main/win-64                                                                              https://repo.anaconda.com/pkgs/main/noarch                                                                              https://repo.anaconda.com/pkgs/r/win-64                                                                                 https://repo.anaconda.com/pkgs/r/noarch                                                                                 https://repo.anaconda.com/pkgs/msys2/win-64                                                                             https://repo.anaconda.com/pkgs/msys2/noarch                                                             package cache : C:\Users\rosullivan\AppData\Local\anaconda3\pkgs                                                                        C:\Users\rosullivan\.conda\pkgs                                                                                         C:\Users\rosullivan\AppData\Local\conda\conda\pkgs                                                   envs directories : C:\Users\rosullivan\AppData\Local\anaconda3\envs                                                                        C:\Users\rosullivan\.conda\envs                                                                                         C:\Users\rosullivan\AppData\Local\conda\conda\envs                                                           platform : win-64                                                                                                     user-agent : conda/23.3.1 requests/2.29.0 CPython/3.10.9 Windows/10 Windows/10.0.22000                               administrator : False                                                                                                      netrc file : None                                                                                                     offline mode : False                                                                                                                                                                                                                                                                                                                                         An unexpected error has occurred. Conda has prepared the above report.                                                                                                                                                                          If submitted, this report will be used by core maintainers to improve                                                   future releases of conda.                                                                                               Would you like conda to send this report to the core maintainers? [y/N]: N                                                                                                                                                                      No report sent. To permanently opt-out, use                                                                                                                                                                                                         $ conda config --set report_errors false

**Comment by pgunn** [comment]
It looks like your conda installation has gotten pretty messed up (you may actually have two separate condas installed); if you don't have too many other conda environments, I suggest removing it - remove entirely these directories:

```
C:\Users\rosullivan\AppData\Local\conda
C:\Users\rosullivan\AppData\Local\anaconda3
C:\Users\rosullivan.condarc
```

Then reinstall conda (maybe use the miniconda installer) and after that you'll have a better shot at building a working environment.

**Comment by rosullivan1226** [comment]
Followed those steps and then reinstalled directly into C:\Users\rosullivan and that seemed to do the trick! Thank you!

**Comment by pgunn** [comment]
Glad it worked out!
