### ISSUE TITLE
Explain how to run CNMF/CNMFE on file that is already motion corrected, not memmapped

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#1083]
It would be good to explain how to to run source separation on files that are motion corrected but not (yet) memmapped. E.g., someone has a tif from culture/slice with zero motion artifact. This shouldn't be too hard, maybe as simple as adding a sidebar in main notebook to describe how to memmap the file (e.g., if you don't need motion correction, then memmap your file). 

I think the route of having it run directly on non-memmapped files is a longer tougher issue as in #750

**Comment by loftusa** [comment]
I second this - I was trying to figure out how to do this and it took me a bit. Would have been nice to just have some code to copy/paste!

**Comment by EricThomson** [comment]
This is already illustrated in CNMFE demo notebook (in the alternate to the `if motion_correct` branch). I'm currently adding it to CNMF notebook as a "sidebar". Will close when this is pushed to main.

**Comment by EricThomson** [comment]
This is merged in PR #1075 will be in next release.
