### ISSUE TITLE
Buffering and freezing of Vmax/Vmin during motion correction with small file size

### ISSUE THREAD

**Issue by zfyke** [flatironinstitute/CaImAn#1084]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Mac Ventura 13.3.1
 2. Hardware type (x86, ARM..) and RAM: M2Pro 16GB Ram 
 3. Python Version (e.g. 3.9): 3.10.8
 4. Caiman version (e.g. 1.9.12): 1.9.15
 5. Which demo exhibits the problem (if applicable): practice_mcorr
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): Pure conda
 7. Details: 

While processing a small (1.05GB) 512x512 .tif file, after applying motion correction and visualization, I could not set Vmax or Vmin due to persistent freezing and buffering. My connection was stable, and I was able to get some initial feedback after rerunning the code.

**Comment by EricThomson** [comment]
Are you working with caiman or mesmerize, `practice_mcorr` sounds like a mesmerize demo

**Comment by zfyke** [comment]
Im working with the mesmerize demo>

On Thu, May 18, 2023 at 9:41 AM Eric Thomson ***@***.***>
wrote:

> Are you working with caiman or mesmerize, practice_mcorr sounds like a
> mesmerize demo
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflatironinstitute%2FCaImAn%2Fissues%2F1084%23issuecomment-1553168592&data=05%7C01%7Czfyke2%40groute.uic.edu%7Ca3e184a8d5624574a77b08db57adfa90%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638200176973593265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fr0Hqy8JTahKzhKJAnc6hl8JPZVg4hLGREnmQipXKuY%3D&reserved=0>,
> or unsubscribe
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA75UZFARBDGNAGTM2VDRJWLXGYYJ5ANCNFSM6AAAAAAYGRQWFA&data=05%7C01%7Czfyke2%40groute.uic.edu%7Ca3e184a8d5624574a77b08db57adfa90%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C638200176973593265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l4Wz7vvo%2Bxc%2BJW0GYvYNtdZ9W%2F7WbivM8ZO0t9Ckv8w%3D&reserved=0>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 

Zach Fyke

Lab Technician | Yoshii Lab

College of Medicine | Dept. of Anatomy and Cell Biology

The University of Illinois at Chicago

E: ***@***.***

**Comment by EricThomson** [comment]
Please open an issue at the relevant mesmerize repo, closing this.
