### ISSUE TITLE
Save final results to csv and other formats

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#1086]
Currently the save function after running CNMF just packs away the entire CNMF object so it can be reconstructed later. This is helpful for stopping/starting analysis of caiman, but not super helpful for users who just want to save analysis results for downstream processing. It would be helpful to provide a generic function to save (and load) results (C/S/YrA/dF_F), and it's pretty easy to implement.

I am thinking: csv, pkl, npz, hdf5, mat, zarr (give or take a couple). 

One issue is with csv and volumetric data. That isn't a very natural fit, so I'm tempted to just throw an exception, and have people save in another format in that case until there is huge demand.

Some wrinkles include which results from estimates to save, whether to save all indices or good indices, how much control to give users over these wrinkles.

**Comment by kushalkolar** [comment]
I think you'd want to save all the results from the estimates, not just the ones you mentioned. Things like b, f, can be very useful (like detecting z axis shifts for example). I think people are really not leveraging what caiman can do.

One important thing is you probably want the API to clearly distinguish export formats and serialization (which is currently implemented). I'm assuming you don't want to support creating a cnmf object from a CSV file, this could get very messy very fast if types can't be encoded reliably.

**Comment by EricThomson** [comment]
Right we definitely don't want to support creation of cnmf object, just saving main results, and loading them for postprocessing/analysis. 

One thing I want to do for now in the notebooks is just to be better about showing people how to save and load data (e.g., how do you save your results as a csv file for analysis later). 

For design, we could start with a simple 'save time series' (things that have components by frames as dimensions like C). Another function could save spatial components (which would include image shaped objects like A and b).  Another could be saving parameters.  A final method could be a wrapper that users could call that lets them determine which of those they actually want to save. I would not want to force people to save things they don't want. Most people want just the time series and to get on with it.  Just spitballing here, not sure what else, or if those are the exact right categories. 

But make a few very simple methods each doing one thing really well, and then let people decide how to combine and use them, and we can combine into one mega method with very few calls. :) 

It may be that only a subset of these things will get csv support (i.e., export time series). Everyone I have interacted with that wants csv only wants time series so that should be fine.

In terms of volumetric vs others I assumed the mapping to spatial footprints (A) was more literal in C. I should take a closer look I've only done single plane analysis.

**Comment by EricThomson** [comment]
Closing as this is now demonstrated in PR #1207 which is merged into dev. I don't plan to make a separate method for this (though do plan to work more on NWB save).
