### ISSUE TITLE
tensorflow corrupted error when first installing CaImAn

### ISSUE THREAD

**Issue by ziyizhu1996** [flatironinstitute/CaImAn#1089]
Please fill in the following for any issues

Your setup:
 1. Operating System : Windows
 2. Hardware type and RAM: 32G ram
 3. Python Version : Python 3.10.11; conda 23.3.1
 4. Caiman version (e.g. 1.9.12): uninstalled
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): installation either through 'mamba create -n caiman -c conda-forge caiman' or 'mamba env create -n caiman -f environment.yml'
 7. Details: 
 
when first installing CaImAn, mamba tries to install  caiman==1.9.15, python ==3.10.8 and tensorflow=2.10.0. However, it would always throw an error saying tensorflow is corrupted after downloading and extracting the packages

`Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: failed
The package for tensorflow-base located at C:\Users\zzhu34\AppData\Local\anaconda3\pkgs\tensorflow-base-2.10.0-mkl_py310h6a7f48e_0
appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/external/llvm-project/mlir/_virtual_includes/BufferizableOpInterfaceIncGen/mlir/Dialect/Bufferization/IR/BufferizableOpInterface.cpp.inc'
specified in the package manifest cannot be found.

The package for tensorflow-base located at C:\Users\zzhu34\AppData\Local\anaconda3\pkgs\tensorflow-base-2.10.0-mkl_py310h6a7f48e_0
appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/tensorflow/compiler/mlir/hlo/_virtual_includes/compose_set_interface_inc_gen/mlir-hlo/Dialect/gml_st/transforms/compose_set_interface.h.inc'
specified in the package manifest cannot be found.

CondaVerificationError: The package for tensorflow-base located at C:\Users\zzhu34\AppData\Local\anaconda3\pkgs\tensorflow-base-2.10.0-mkl_py310h6a7f48e_0
appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/external/llvm-project/mlir/_virtual_includes/BufferizableOpInterfaceIncGen/mlir/Dialect/Bufferization/IR/BufferizableOpInterface.cpp.inc'
specified in the package manifest cannot be found.

CondaVerificationError: The package for tensorflow-base located at C:\Users\zzhu34\AppData\Local\anaconda3\pkgs\tensorflow-base-2.10.0-mkl_py310h6a7f48e_0
appears to be corrupted. The path 'Lib/site-packages/tensorflow/include/tensorflow/compiler/mlir/hlo/_virtual_includes/compose_set_interface_inc_gen/mlir-hlo/Dialect/gml_st/transforms/compose_set_interface.h.inc'
specified in the package manifest cannot be found.`

**Comment by pgunn** [comment]
Hello,
Please try doing this:
`conda clean --all`

 and then delete and recreate the caiman environment as per the instructions. Hopefully that will fix things.

**Comment by ziyizhu1996** [comment]
Hi, turns out this is an issue of windows not allowing file path of more than 256 characters, an error happening when creating path for tensorflow. Here is the solution: https://github.com/tensorflow/tensorflow/issues/35935
I edited the registry in windows according to it and it solved the problem

**Comment by pgunn** [comment]
Ah, thanks; I thought those were enabled by default in all modern versions of windows. I wonder if Windows 11 has that enabled by default. Hopefully.
