### ISSUE TITLE
unable to upload the .tif

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1091]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS m1
 2. Hardware type (x86, ARM..) and RAM: x86(?)
 3. Python Version (e.g. 3.9): 3.9
 4. Caiman version (e.g. 1.9.12): 
 5. Which demo exhibits the problem (if applicable): 
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): terminal 
 7. Details: 

Hello, I tried to modify the demo code for my own file, I think the path is right. But it encounters an error. Here are the details. I also tried entering the path in fnames = 'User/....../.....tif', but still not working.

Thank you very much for your help!!

 0%|                                                    | 0/28 [00:00<?, ?it/s]     1407863 [movies.py:                load():1727] [11403] File request:[C] not found!
  0%|                                                    | 0/28 [00:00<?, ?it/s]
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[12], line 2
      1 fnames = 'C068C1d24.tif'
----> 2 m_orig = cm.load_movie_chain(fnames) 
      3 downsample_ratio = .2  # motion can be perceived better when downsampling in time
      4 m_orig.resize(1, 1, downsample_ratio).play(q_max=99.5, fr=30, magnification=2)   # play movie (press q to exit)

File ~/CaImAn/caiman/base/movies.py:1773, in load_movie_chain(file_list, fr, start_time, meta_data, subindices, var_name_hdf5, bottom, top, left, right, z_top, z_bottom, is3D, channel, outtype)
   1771 mov = []
   1772 for f in tqdm(file_list):
-> 1773     m = load(f,
   1774              fr=fr,
   1775              start_time=start_time,
   1776              meta_data=meta_data,
   1777              subindices=subindices,
   1778              in_memory=True,
   1779              outtype=outtype,
   1780              var_name_hdf5=var_name_hdf5)
   1781     if channel is not None:
   1782         logging.debug(m.shape)

File ~/CaImAn/caiman/base/movies.py:1728, in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype, is3D)
   1726 else:
   1727     logging.error(f"File request:[{file_name}] not found!")
-> 1728     raise Exception(f'File {file_name} not found!')
   1730 return movie(input_arr.astype(outtype),
   1731              fr=fr,
   1732              start_time=start_time,
   1733              file_name=os.path.split(file_name)[-1],
   1734              meta_data=meta_data)

Exception: File C not found!

**Comment by j-friedrich** [comment]
Short answer:
Just use `m_orig = cm.load(fnames)` instead of `m_orig = cm.load_movie_chain(fnames)`

Long answer:
`cm.load_movie_chain` expects `fnames` to be a list, `fnames = ['User/....../.....tif']`. It iterates over the list that can contain multiple filenames. If you only provide a string, it results in a loop over single character, and thus your error. 
`cm.load` works with either, a list or a single string.

Note to developers:
Replace `cm.load_movie_chain` with `cm.load` in the demo?
Get rid of  `cm.load_movie_chain` altogether and let `cm.load` recursively call itself if `fnames` is a list?

**Comment by EricThomson** [comment]
@j-friedrich I plan to simplify this in the demo just as you said, and have a kind of "appendix" on working with multiple movies. But I like the idea of just getting rid of `load_movie_chain()` it is a consistent source of confusion. @pgunn mentioned this recently too.

**Comment by zhouyi0812** [comment]
May I ask a follow-up question? 
I am going to analyze a widefield calcium imaging, which demo do you think would be the best to follow?
Thank you so much!!!!

**Comment by EricThomson** [comment]
That's 1p right? I would suggest demo_pipeline_cnmfE.ipynb to start with.

**Comment by kushalkolar** [comment]
why not just a type check within one function to load a movie/movie chain?

```python
if isinstance(fnames, (str, Path):
  fnames = [fnames]

# otherwise assume iterable
```
