### ISSUE TITLE
Dendritic/axonal contours

### ISSUE THREAD

**Issue by vkonan** [flatironinstitute/CaImAn#1092]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS Monterey v12.6.5
 2. Hardware type (x86, ARM..) and RAM: Apple M2 2022, 24GB RAM
 3. Python Version (e.g. 3.9): 3.10.8
 4. Caiman version (e.g. 1.9.12): 1.9.13
 5. Which demo exhibits the problem (if applicable): demo_dendritic.ipynb
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): mamba create -n mescore -c conda-forge mesmerize-core 
 7. Details: 

My dataset contains dendritic activity. I've used the demo notebook successfully. However I'd like to draw contours and view activity similar to what is possible with cell body activity. However, when I try to use fastplotlib to do this, [this is what I get.](https://imgur.com/Z5AROYK)

Do you know if there is a better way to look at contours? or is the nature of the contours such that it's too distributed to meaningfully draw bounds?

**Comment by kushalkolar** [comment]
I also got something similar with one of the dendritic init methods, I'm not too familiar with how to tune params for dendrites. What's your mean image look like?

**Comment by kushalkolar** [comment]
Ah interesting! It's possible that the way the x, y coordinates are stored for dendrites is non-contiguous so they can't be drawn as contigous lines. Try scatter plot?

Any insight @j-friedrich @EricThomson ? 

(btw you can copy paste images into github issues :D )

**Comment by EricThomson** [comment]
I would consider thresholding based on percentile (basically what the contour plotter does), do some basic morphological operations to trim away the nonsense, and then plot the surviving blobs (filtered by size perhaps, or maybe better yet use the surviving blobs to make a mask for the original estimate). 

Note if you do this please share it would be useful to see how it works. :)

**Comment by vkonan** [comment]
> I would consider thresholding based on percentile 

I'm not sure if I understand what you mean here. Percentile of what? Is there an example of what the contour plotter does to distinguish by percentile? In the notebooks, I only see examples of "cnmf.get_contours" and plotting it by "add_line_collection".

I'm still learning how to manipulate data and plotting in python, so I apologize for my ignorance.

**Comment by kushalkolar** [comment]
Eric is talking about the caiman bokeh visualizers, mesmerize's cnmf.get_contours does a threshold too (it directly uses caiman contour function). But I would try plotting individual components as a scatter and see if it makes sense, then try the same one with a line. 

Or if you can provide me with your hdf5 output file I can take a look.

**Comment by EricThomson** [comment]
Sorry @vkonan that response was very telegraphic. 

Basically, each spatial component A is an image, the same size as the original image, with float values localized to the little blob for standard (somatic) CNMF/CNMFE. As you noticed, `get_contours()` uses percentile to determine how restricted to make the blob to plot individual lines. 

I _think_ you could use a similar trick to extract more restricted regions of the parts of dendritic area (or a mask), after some morphological operations (Matlab has a good description of the morphological operations to extract shapes/blobs: https://www.mathworks.com/help/images/morphological-dilation-and-erosion.html, but you can do them in scikit-image: https://scikit-image.org/docs/stable/api/skimage.morphology.html).

**Comment by EricThomson** [comment]
If your goal is just to plot the component and its activity, the standard notebook viewer works in the dendritic demo. There is already a threshold parameter for that, which should work (though they often look not amazing). 

If your question is how to do that in fastplotlib, I'm not sure I would open an issue at mesmerize or fastplotlib.

**Comment by vkonan** [comment]
Update: I have decided to take the output from mesmerize-core and visualize/process the data in MATLAB, since I'm much more familiar with MATLAB coding.
@EricThomson your comment regarding morphological operations is very helpful and I'll pursue that in MATLAB. I'm going to close this issue since my questions were answered. Thank you!

**Comment by kushalkolar** [comment]
I just dug into caiman's holoviews viz code and I now understand why the contours look nonsensical like the image you showed for dendritic CNMF. It's because contours are probably not the best way to visualize dense and branched structures like dendrites. The holoviews visualization in caiman basically just displays `A` without computing the contours, so it's actually pretty simple!

Equivalent fpl code:

```python
import fastplotlib as fpl
from ipywidgets import VBox

A_dense = np.asarray(cnm.estimates.A.todense()).reshape((*cnm.dims, -1), order='F')
for i in range(A_dense.shape[-1]):
    A_dense[:, :, i] += cnm.estimates.A.mean(1).reshape(cnm.dims, order='F')

iw = fpl.ImageWidget(
    data=A_dense.T, # so it [t, x, y]
    cmap="viridis", 
    vmin_vmax_sliders=True,
    grid_plot_kwargs={"size": (400, 400)},
)

temporal_plot = fpl.Plot(size=(700, 200))

temporal = cnm.estimates.C[0] + cnm.estimates.YrA[0]
temporal_plot.add_line(temporal, name="line")

def update_component(change):
    i = change["new"]
    temporal = cnm.estimates.C[i] + cnm.estimates.YrA[i]
    temporal_plot["line"].data = temporal
    temporal_plot.auto_scale(maintain_aspect=False)
    
iw.sliders["t"].observe(update_component, "value")

VBox([iw.show(), temporal_plot.show(maintain_aspect=False)])
```

https://github.com/flatironinstitute/CaImAn/assets/9403332/8049c7b3-f0f9-4c3b-8822-28c879b2427c
