### ISSUE TITLE
why it took so long to run CNMF-E in Jupyter notebook

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1097]
Hello!

After I set up the parameters for CNMF-E, it took so long to run the CNMF-E algorithm. And it generated the same error all the time. 

miniconda3/envs/caiman/lib/python3.10/site-packages/scipy/signal/_spectral_py.py:2014: UserWarning: nperseg = 256 is greater than input length  = 203, using nperseg = 203
warnings.warn('nperseg = {0:d} is greater than input length '

miniconda3/envs/caiman/lib/python3.10/site-packages/scipy/sparse/_dia.py:338: RuntimeWarning: divide by zero encountered in remainder

Could you give me some suggestions that what happened? 

I have a file that barely moves but I still set up motion correction, and I am not sure about the decay_time so I didn't set up. It will impact the results?

Thank you very much!

**Comment by EricThomson** [comment]
How long is your movie? It looks like it is 203 frames long, which is typically not long enough to do good motion correction. I think you want 400+ frames. 

We need to do a better job handling this error.

See related issue #986

**Comment by zhouyi0812** [comment]
My movie is 30s and 203 frames. 
So I don't have to set up the motion correction and directly go for cnmfe parameters set up right?
Thank you!

**Comment by EricThomson** [comment]
Things will get weird if you don't do any motion correction (it needs to be memmapped).

If you save it as a memmapped file, and it has no motion, it should work. But if you want to test motion correction I would follow the suggestion by Johannes at the related issue that seemed to fix the issue there.

Or better yet run on a longer movie like 400+ frames, if you can. Otherwise, you may see some weird things. We need to better document these corner cases. I have to take the time to explore it thoroughly.

**Comment by zhouyi0812** [comment]
Thank you for your advise! I tried to adjust window number from my notebook, however I am following cnmf-e demo and there is no window parameter to adjust.....

Thank you!

**Comment by EricThomson** [comment]
@zhouyi0812 sorry I didn't realize the parameters wouldn't apply: I will probably have time next week to look at the proper parameters in cnmfe to handle this. Generally, we recommend having movies over 400 frames it is a corner case to have fewer frames. That said, we should handle the corner case better so I'll look into it more next week.

**Comment by zhouyi0812** [comment]
Hello! I have a follow up question.
I doubled my original .tif from 203 frames to 406 frames. It also took so long to run and generated the same error which is different from the last time

caiman/lib/python3.10/site-packages/scipy/sparse/_dia.py:338: RuntimeWarning: divide by zero encountered in remainder

It is something that is because of the parameter setting?

Thank you for your guidance!

**Comment by zhouyi0812** [comment]
It took me 2mins 30secs to run through the whole demo cnmf-e on jupyter notebook.
For my own data, I let it run overnight but still on it and generate the same warning.
My movie is 2 dimension; the space is 45 available of 245 GB; Memory 8GB (ram?); When I run the CNMF-E algorithm for my own data, it took almost 99% cpu. 

After I adjust n_processes=None, the cpu is taking from 80%-99%

Thank you very much!!!

**Comment by EricThomson** [comment]
Closing issue it seems resolved. Please reopen if this was a mistake.
