### ISSUE TITLE
spatial comps visualization for ipython notebook

### ISSUE THREAD

**Issue by caichangjia** [flatironinstitute/CaImAn#1099]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux):
 2. Hardware type and RAM 128GB:
 3. Python Version (3.10.10):
 4. Caiman version (1.9.13):
 5. Which demo exhibits the problem (demo_pipeline.ipynb):
 6. How you installed Caiman (memba install caiman):
 7. Details: I tried caiman on some 2p datasets. The cnm2.estimates.plot_contours_nb function output some spatial footprints, but when I use cnm2.estimates.nb_view_components function, the output spatial footprints look super tiny for all comps. 
Things look normal when I use demo_pipeline.py file on Spyder.

![Screenshot from 2023-06-02 14-32-11](https://github.com/flatironinstitute/CaImAn/assets/30387087/93efa0d1-4a9e-4a1c-b1ce-3f9c07d65fcd)
![Screenshot from 2023-06-02 14-32-20](https://github.com/flatironinstitute/CaImAn/assets/30387087/ef4218fa-64c0-432d-9981-5e01178c6845)

**Comment by EricThomson** [comment]
I'll look at this next week that is bizarre!

**Comment by EricThomson** [comment]
@caichangjia could you show the exact commands you are using in the two cases that are giving the different results, please? I'd like to try to reproduce with the sample demo datasets I have an idea what's going on, will test it probably next week.

**Comment by caichangjia** [comment]
shared with you the data and code

**Comment by EricThomson** [comment]
It seems it was params. Please reopen if is still an issue.
