### ISSUE TITLE
Unable to create file "Tolias_mesoscope_1_results"

### ISSUE THREAD

**Issue by chimmut** [flatironinstitute/CaImAn#1100]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): windows 11
 2. Hardware type (x86, ARM..) and RAM: x86
 3. Python Version (e.g. 3.9): 3.10.8
 4. Caiman version (e.g. 1.9.12): 1.9.15
 5. Which demo exhibits the problem (if applicable): demo_OnACID_mesoscope.py
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): pure conda
 7. Details: 
  Hello!
  After I ran demo_OnACID_mesoscope.py, it encountered an error. Here are the details.
  Traceback (most recent call last):
  File "C:\Users\tt\caiman_data\demos\general\demo_OnACID_mesoscope.py", line 176, in <module>
    main()
  File "C:\Users\tt\caiman_data\demos\general\demo_OnACID_mesoscope.py", line 168, in main
    cnm.save(os.path.splitext(fnames[0])[0]+'_results.hdf5')
  File "D:\Anaconda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py", line 1056, in save
    save_dict_to_hdf5(self.__dict__, caiman.paths.fn_relocated(filename))
  File "D:\Anaconda\envs\caiman\lib\site-packages\caiman\utils\utils.py", line 431, in save_dict_to_hdf5
    with h5py.File(filename, 'w') as h5file:
  File "D:\Anaconda\envs\caiman\lib\site-packages\h5py\_hl\files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "D:\Anaconda\envs\caiman\lib\site-packages\h5py\_hl\files.py", line 237, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 126, in h5py.h5f.create
OSError: [Errno 0] Unable to synchronously create file (unable to lock file, errno = 0, error message = 'No error', Win32 GetLastError() = 33)
And the file "Tolias_mesoscope_1_results"  size is 0KB.
Thank you very much for your help!!

**Comment by pgunn** [comment]
Hello,
By any chance are you out of free space on your D: drive?

**Comment by pgunn** [comment]
Can you send me the output of this command, from your activated caiman environment?
`conda list h5py`

**Comment by chimmut** [comment]
(caiman) C:\Users\tt>conda list h5py
# packages in environment at D:\Anaconda\envs\caiman:
#
# Name                    Version                   Build  Channel
h5py                      3.8.0           nompi_py310h727aef9_101    conda-forge

**Comment by pgunn** [comment]
Thanks; I haven't seen this error before; I'll hopefully be able to figure out what's going on.

**Comment by pgunn** [comment]
I just tried to reproduce on my windows test box and was not successful (the demo ran fine)

If you bring up your file browser and bring up properties of your D: drive, what file system is it using? Is it a removable drive or a HD?

**Comment by chimmut** [comment]
It's a SSD.

**Comment by pgunn** [comment]
Thanks ; what filesystem is on it? Is this an external USB SSD or desktop SSD?

**Comment by chimmut** [comment]
Sorry, I don't get it. But I use a laptop, and the D: drive is partitioned from the C: drive.



---Original---
From: "Pat ***@***.***&gt;
Date: Tue, Jun 6, 2023 11:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [flatironinstitute/CaImAn] Unable to create file"Tolias_mesoscope_1_results" (Issue #1100)




 
Thanks ; what filesystem is on it? Is this an external USB SSD or desktop SSD?

**Comment by pgunn** [comment]
Here's an example screenshot
![drive_d](https://github.com/flatironinstitute/CaImAn/assets/829791/0cfe258c-a6d1-45ee-b67a-fcaa828435a8)

**Comment by chimmut** [comment]
<img width="323" alt="image" src="https://github.com/flatironinstitute/CaImAn/assets/131773925/64610bf6-ca63-45f5-a833-56150e4ef1aa">

**Comment by chimmut** [comment]
By the way, I just ran demo_OnACID_mesoscope.py again, here are the details.
173266 [utils.py:recursively_save_dict_contents_to_group():519][10668] A is sparse ****
      173285 [utils.py:recursively_save_dict_contents_to_group():474][10668] g is an object type
      173288 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key merged_ROIs is not saved
      173288 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key coordinates is not saved
      173296 [utils.py:recursively_save_dict_contents_to_group():519][10668] Ab is sparse ****
      174178 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key groups is not saved
      174182 [utils.py:recursively_save_dict_contents_to_group():519][10668] A is sparse ****
      174187 [utils.py:recursively_save_dict_contents_to_group():474][10668] g is an object type
      174190 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key merged_ROIs is not saved
      174190 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key coordinates is not saved
      174202 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key groups is not saved
      174274 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key ind_A is not saved
      174276 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key tf_in is not saved
      174276 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key tf_out is not saved
      174277 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key loaded_model is not saved
      174279 [utils.py:recursively_save_dict_contents_to_group():484][10668] Key Ab_epoch is not saved

Process finished with exit code 0

**Comment by pgunn** [comment]
Oh, so it sounds like it succeeded. I don't understand why it failed the first time.

(what I was looking for in that screenshot was the NTFS part - that's the filesystem on the volume)

**Comment by chimmut** [comment]
Me neither. But how can I get the visualization result？I thought it could be opened through caiman_gui.py, but I can't find the .mmap in caiman_data/example_movies/mesoscope.





---Original---
From: "Pat ***@***.***&gt;
Date: Tue, Jun 6, 2023 12:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [flatironinstitute/CaImAn] Unable to create file"Tolias_mesoscope_1_results" (Issue #1100)




 
Oh, so it sounds like it succeeded. I don't understand why it failed the first time.
 
(what I was looking for in that screenshot was the NTFS part - that's the filesystem on the volume)

**Comment by pgunn** [comment]
Try altering the script to change show_movie to True, rather than false.

**Comment by chimmut** [comment]
show_movie = True 
But it caused an error. Here are the details.
Traceback (most recent call last):
  File "C:\Users\tt\caiman_data\demos\general\demo_OnACID_mesoscope.py", line 176, in <module>
    main()
  File "C:\Users\tt\caiman_data\demos\general\demo_OnACID_mesoscope.py", line 106, in main
    cnm.fit_online()
  File "D:\Anaconda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py", line 1186, in fit_online
    self.initialize_online(model_LN=model_LN)
  File "D:\Anaconda\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py", line 1040, in initialize_online
    self.bnd_AC = np.percentile(self.estimates.A.dot(self.estimates.C),
  File "<__array_function__ internals>", line 200, in percentile
  File "D:\Anaconda\envs\caiman\lib\site-packages\numpy\lib\function_base.py", line 4205, in percentile
    return _quantile_unchecked(
  File "D:\Anaconda\envs\caiman\lib\site-packages\numpy\lib\function_base.py", line 4473, in _quantile_unchecked
    return _ureduce(a,
  File "D:\Anaconda\envs\caiman\lib\site-packages\numpy\lib\function_base.py", line 3752, in _ureduce
    r = func(a, **kwargs)
  File "D:\Anaconda\envs\caiman\lib\site-packages\numpy\lib\function_base.py", line 4639, in _quantile_ureduce_func
    result = _quantile(arr,
  File "D:\Anaconda\envs\caiman\lib\site-packages\numpy\lib\function_base.py", line 4756, in _quantile
    result = _lerp(previous,
  File "D:\Anaconda\envs\caiman\lib\site-packages\numpy\lib\function_base.py", line 4575, in _lerp
    lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
  File "D:\Anaconda\envs\caiman\lib\site-packages\numpy\matrixlib\defmatrix.py", line 218, in __mul__
    return N.dot(self, asmatrix(other))
  File "<__array_function__ internals>", line 200, in dot
ValueError: shapes (2,22528000) and (2,1) not aligned: 22528000 (dim 1) != 2 (dim 0)

**Comment by pgunn** [comment]
Hello,
I've reproduced the issue on Linux; doesn't seem to be platform-specific. Looking into it. Maybe some library functions have changed since this last worked.

**Comment by EricThomson** [comment]
@chimmut the results are in `cnm.estimates`, and you can find out about how to interpret the information in that class here:
https://caiman.readthedocs.io/en/master/Getting_Started.html#result-interpretation

Each of those elements is a numpy array that you can plot using matplotlib, or you can save using standard save functions. I like `joblib` because it lets you save arbitrary dictionaries of values and load them later.  At some point we'll show how to do this in a notebook.

Let me know if you have particular questions about the estimates object etc.

**Comment by chimmut** [comment]
Thanks so much for your help!
