### ISSUE TITLE
Issue with install caimanmanager: No such file or directory after entering the full path

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1104]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): windows
 2. Hardware type (x86, ARM..) and RAM: 
 3. Python Version (e.g. 3.9): 3.10
 4. Caiman version (e.g. 1.9.12): 
 5. Which demo exhibits the problem (if applicable): unable to install caimanmanager
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): conda
 7. Details: 

Hello!

I was using windows to install the caimanmanager but tried many way still doesn't work. I tried to locate python by 'where python', however after I enter the full path:python C:\Users\Lab\anaconda3\envs\caiman\bin\caimanmanager.py install there is an error saying [Errno 2] No such file or directory

"
(caiman) C:\Users\M Lab>where python
C:\Users\M Lab\anaconda3\envs\caiman\python.exe
C:\Users\M Lab\AppData\Local\Microsoft\WindowsApps\python.exe

(caiman) C:\Users\M Lab>python C:\Users\M Lab\anaconda3\envs\caiman\caimanmanager.py install
python: can't open file 'C:\\Users\\Mourrain': [Errno 2] No such file or directory
"

Also, after I install the install the caiman via mamba/conda, I run 'pip install -e .' ---> ERROR: file:///C:/Users/M%20Lab does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found. So I tried to download a setup file and copy to the directory, but seems not working either.

I tried to reinstall the environment but still doesn't work. 

Thank you very much!!!!!!!

**Comment by pgunn** [comment]
Hello,
Having a space in your username is going to potentially create problems for you in the future. I'll try to help you make this work, but you'll have an easier time if you can make a different account on the computer with a name that's just alphanumeric. Like "MLab".

Try this:

`python "C:\Users\M Lab\anaconda3\envs\caiman\bin\caimanmanager.py" install`

**Comment by zhouyi0812** [comment]
Hello! I tried to edit the name but it is default user name. So I deleted anaconda and reinstall in a 'Public' file. However, when I open the anaconda prompt, the base environment is still M Lab. Thank you!

**Comment by GUO-neuroLAB** [comment]
Hi ,i encounter the same condition and i cannot find caimannager.py file in the script folder and cannot find caimannager in my computer. i use the manba to install the caiman. i am in China, is it the net problem?

**Comment by pgunn** [comment]
Hello @GUO-neuroLAB ,
Please do not comment on closed issues; if you're having install issues, please open a new issue and we'll try to help you.

--Pat
