### ISSUE TITLE
Download high resolution analysis figure

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1105]
Hello!!

After I run the algorithm and get the individual cell with a time series graph. I wonder if there is a way to down load the individual cell graph in high resolution.

Thank you!!

**Comment by EricThomson** [comment]
The spatial footprints are in `estimates.A`, the time series are in different parts of `estimates`, so it depends if you want time series or not, and if so which ones. But you can plot these things using matplotlib and then save them as png with `dpi` as a parameter.  For lines you can save as vectorized images.

**Comment by zhouyi0812** [comment]
I tried this code, but the image I saved is blank.

cnm.estimates.plot_contours_nb(img=cn_filter, idx=cnm.estimates.idx_components)
plt.savefig('contour.png', dpi=600)

**Comment by kushalkolar** [comment]
I'm pretty sure that `plot_contours_nb` creates a [`bokeh`](https://github.com/bokeh/bokeh) plot, whereas `plt.savefig` is from [`matplotlib`](https://github.com/matplotlib/matplotlib), you can't use matplotlib to save a bokeh plot.

I think the bokeh toolbar has a save button if that's all you want?

**Comment by zhouyi0812** [comment]
I saw the button on the left of the graph, but the resolution is quite low and I want a high resolution one.

**Comment by kushalkolar** [comment]
To create high resolution publication quality figures, the best option is really matplotlib. The various attributes of the `estimates` object are numpy arrays and you can plot them with matplotlib. Jake Vanderplas has a great matplotlib tutorial,  I think he has a youtube tutorial as well: https://jakevdp.github.io/PythonDataScienceHandbook/04.00-introduction-to-matplotlib.html

**Comment by zhouyi0812** [comment]
Thank you for your guidance, I will figure out the matplotlib myself.  I just want to double check, the parameter I should play with that represents the accepted and rejected components are: 

 cnm.estimates.C and cnm.estimates.idx_components

But I just a bit confused, how is individual cell can be separate from: cnm.estimates.
hv_view_components(img=cn_filter, idx=cnm.estimates.idx_components, denoised_color='red', cmap='gray')

Thank you very much!!!

**Comment by kushalkolar** [comment]
`estimates.C` is of shape `[n_components, n_frames]`, you can slice along the first dimension `n_components` using `estimates.idx_components`, i.e. `estimates.C[estimates.idx_components]`

For more info: https://caiman.readthedocs.io/en/master/Getting_Started.html#result-variables-for-2p-batch-analysis

if you want mor complex plots like heatmaps use seaborn which builds upon matplotlib: https://seaborn.pydata.org/generated/seaborn.heatmap.html

**Comment by zhouyi0812** [comment]
Sorry! The notebook says the estimates is not defined.
Should I import something?
Thank you for your help!!

**Comment by EricThomson** [comment]
Based on Gitter it seems you got this working. It would be helpful if you put a code snippet to show what you did, so others that find this can see what to do.

**Comment by zhouyi0812** [comment]
Sure! Here is my code based on the demo CNMF-E

1. Working code for visualizing individual cell 

plt.figure(); plt.imshow(np.reshape(cnm.estimates.A[:,cnm.estimates.idx_components[0]].toarray(), dims, order='F'))
plt.savefig('cell.png',dpi=700)
plt.figure(); plt.plot(cnm.estimates.C[cnm.estimates.idx_components[0]])
cnm.estimates.view_components()

2. The separate two graphs: all cells (FOV) and contour

import matplotlib.pyplot as plt

# Assuming P is the existing graph
# Assuming cnm.estimates.coordinates is the list of contours

# Create a new figure with subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5))

# Plot the graph P (all cells) in the first subplot
ax1.imshow(cn_filter)
ax1.set_xlabel('X')
ax1.set_ylabel('Y')
ax1.set_title('Graph P')

# Plot the contours in the second subplot
for contour_dict in cnm.estimates.coordinates:
    contour_coords = contour_dict['coordinates']
    ax2.plot(contour_coords[:, 0], contour_coords[:, 1], color='pink', linewidth=1)
ax2.set_xlabel('X')
ax2.set_ylabel('Y')
ax2.set_title('Contours of Cells')

# Adjust spacing between subplots
plt.tight_layout()

# Display the combined figure
plt.show()

3. Plot contour upon the the FOV

# Plot cell without contour
p=plt.figure(); plt.imshow(cn_filter)

# Plot contour
cnm.estimates.plot_contours_nb(img=cn_filter)
coordinates = cnm.estimates.coordinates
coordinates

coordinates = str(coordinates)
type(coordinates)


import matplotlib.pyplot as plt

# Assuming cnm is the variable representing your object
# p is the existing graph

# Plotting the shapes of the neurons on the existing graph
for contour in coordinates:
    x_coords = [coord['x'] for coord in contour]
    y_coords = [coord['y'] for coord in contour]
    p.scatter(x_coords, y_coords)

# Adding labels and title to the graph
p.set_xlabel('X')
p.set_ylabel('Y')
p.set_title('Neuronal Shapes')

# Display the graph
plt.show()

**Comment by EricThomson** [comment]
Great thanks! Closing the issue as it seems resolved (incidentally, when you feel an issue is resolved you can click `Close issue` at the bottom of the issue page).
