### ISSUE TITLE
load background `b` as a sparse matrix, not dict

### ISSUE THREAD

**Issue by loftusa** [flatironinstitute/CaImAn#1108]
The `save` function saves the background `b` as a dict under cnmf: 
https://github.com/flatironinstitute/CaImAn/blob/80e1681bbce8fb4a36b04c57d9e42ffb75a32d58/caiman/utils/utils.py#L518

However, `b` lives in the object as a `csc_matrix`.
when you call `utils.load_CNMF`, `b` should be converted back into a `csc_matrix`. It currently is loaded in as a dictionary.

**Comment by kushalkolar** [comment]
How are you saving, I can't reproduce this. `estimates.b` is a numpy array, this is using `demo_pipeline.ipynb`:

```python
cnm2.save("./test.hdf5")

from caiman.source_extraction.cnmf.cnmf import load_CNMF

cnmf_obj = load_CNMF("./test.hdf5")

print(f"loaded: {type(cnmf_obj.estimates.b)}")
print(f"orig: {type(cnmf_obj.estimates.b)}")

# output
loaded: <class 'numpy.ndarray'>
orig: <class 'numpy.ndarray'>
```

**Comment by loftusa** [comment]
> How are you saving, I can't reproduce this. `estimates.b` is a numpy array, this is using `demo_pipeline.ipynb`:
> 
> ```python
> cnm2.save("./test.hdf5")
> 
> from caiman.source_extraction.cnmf.cnmf import load_CNMF
> 
> cnmf_obj = load_CNMF("./test.hdf5")
> 
> print(f"loaded: {type(cnmf_obj.estimates.b)}")
> print(f"orig: {type(cnm2.estimates.b)}")
> 
> # output
> loaded: <class 'numpy.ndarray'>
> orig: <class 'numpy.ndarray'>
> ```
> 
> Also, `recursively_save_dict_contents_to_group` isn't saving things as a dict, it's serializing the CNMF object to an hdf5 file and parsing attributes based on their types.

I'm using `cnm.save('filename.hdf5')` with no additional parameters.

The code causing this is here, line 518 in utils/utils.py:
```
        elif 'sparse' in str(type(item)):
            logging.info(key + ' is sparse ****')
            h5file[path + key + '/data'] = item.tocsc().data
            h5file[path + key + '/indptr'] = item.tocsc().indptr
            h5file[path + key + '/indices'] = item.tocsc().indices
            h5file[path + key + '/shape'] = item.tocsc().shape
```

When you load the hdf5 file back in with `caiman.source_extraction.cnmf.cnmf.load_CNMF`, there is no functionality to sparsify this matrix again. So `estimates.b` is loaded as a dictionary.

To your question: With my parameters, `estimates.b` was saved as a scipy sparse array. Not sure where in the code it's doing that.

**Comment by kushalkolar** [comment]
`estimates.b` deserialized from the hdf5 file back into a numpy array, are you really sure `estimates.b` is a dict?

what happens if you do:

```python
cnmf_object = load_CNMF("path.hdf5")

print(type(cnmf_object.estimates.b))
```

I think you can use scipy to sparsify the matrix back to a CSC, I'm assuming hdf5 can't store sparse array types and only supports dense arrays (but I might be wrong).

**Comment by EricThomson** [comment]
@loftusa have you gotten `cnm.save()`/`load_CNMF()` worked out or do you need help with that still?
