### ISSUE TITLE
Add patch visualization for motion correction and CNMF

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#1116]
Motion correction and CNMF/E both operate on patches of images whose width/overlap is determined by user parameters (for motion correction it is set by `overlaps` and `strides`, and for CNMF by `stride` and `rf`).  I have built functionality to visualize these patches superimposed on static image templates:

![patch_plotting_example](https://github.com/flatironinstitute/CaImAn/assets/6643322/5b0e1071-6405-47d8-8bfd-b745fad8a4d1)

Especially for motion correction it would be more useful to visualize them superimposed on the actual movies so people can get a better sense of the spatial scales at which piecewise motion correction needs to be performed. 

There are a few ways this could be done (not mutually exclusive):

- I can do this in OpenCV and wrap it into the movie object (we'd feed the stride/overlap params to the play method, maybe when left as `None` patches are not drawn). 
- Fastplotlib would be a natural vehicle for this (@kushalkolar )

I'm currently just tweaking the CNMF demo, and not focusing on motion correction. Hence, I'm going to leave it as a static patch visualization tool for now (probably will do a PR for `utils.visualization.py`).

**Comment by kushalkolar** [comment]
trivial to do with fastplotlib `LinearRegionSelector` :smile: https://fastplotlib.readthedocs.io/en/feature-docs/api/selectors.html#fastplotlib.graphics.selectors.LinearRegionSelector

**Comment by EricThomson** [comment]
Quilt viewer added.
