### ISSUE TITLE
Can't load saved results in caiman GUI

### ISSUE THREAD

**Issue by chriski777** [flatironinstitute/CaImAn#1119]
Your setup:
 1. Operating System (Linux, MacOS, Windows): Linux
 2. Hardware type (x86, ARM..) and RAM:  x86
 3. Python Version (e.g. 3.9): 3.9.16
 4. Caiman version (e.g. 1.9.12): 1.9.15
 5. Which demo exhibits the problem (if applicable): `demo_pipeline.ipynb`
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): the mamba install method listed on the README.MD
 7. Details: 
 
 Hello, I'm running the following piece of code (snippets extracted from the `demo_pipeline.ipynb`). 

```
    cnm1 = cnmf.CNMF(n_processes, params=curr_ops, dview=dview)
    cnm1.fit_file(motion_correct=True)
    end = time.time()
    print('Processing this file took {} minutes'.format((end - start)/60))
    cnm1.params.set('quality', {'decay_time': decay_time,
                           'min_SNR': min_SNR,
                           'rval_thr': rval_thr,
                           'use_cnn': False, # do not use cnn for dentritic data
                           'min_cnn_thr': cnn_thr,
                           'cnn_lowest': cnn_lowest})
    cnm1.estimates.evaluate_components(images, cnm1.params, dview=dview)
    
    # Extract fluorescence values
    cnm1.estimates.detrend_df_f(quantileMin=8, frames_window=250)
    cnm1.estimates.select_components(use_object=True)
    caiman_filename = str(cropped_dir.joinpath('analysis_results.hdf5'))
    cnm1.save(caiman_filename)
    print('analysis results saved at {}'.format(caiman_filename))
```
I'm able to run the code above and wanted to load the results into the GUI. However, I keep running into this issue when I try to load the results:
```Traceback (most recent call last):
  File "/media/chris/DATA2/CaImAn/bin/caiman_gui.py", line 323, in <module>
    draw_contours()
  File "/media/chris/Data2/CaImAn/bin/caiman_gui.py", line 207, in draw_contours
    idx1 = np.where(SNRs[iidd] < 0.1)[0]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```
I've seen #839 and thought adding the part for evaluating components and detrending the Df/F values would fix it but I'm still running into this problem. 

I'd appreciate any help! Thanks!

**Comment by EricThomson** [comment]
Gui support is close to non-existent right now. Have you tried doing it after running `detrend_df_f` but not running `select_components`? select_components is a destructive operation that sets some things to `None`.  Note in #839 I don't see `select_components` suggested. 🤷

**Comment by chriski777** [comment]
Got it, will give that a try. Also, the main reason I'm trying to use the GUI is to view the components for a single session based on the .hdf5. Is there a quick way I can do this on Jupyter/Python Shell?

**Comment by EricThomson** [comment]
You can load the saved results back into a cnm object using `load_CNMF` and view them using the same component viewers etc. 

`from caiman.source_extraction.cnmf.cnmf import load_CNMF`

Next notebook iteration (coming relatively soon) we will document this better, by which I mean, it will document it.

**Comment by EricThomson** [comment]
Closing as I think we have come up with solutions:  please reopen if issues are still a problem @chriski777
