### ISSUE TITLE
Do you guys still have access to the human-labeled ground-truth data from the paper?

### ISSUE THREAD

**Issue by loftusa** [flatironinstitute/CaImAn#1124]
And is it this? https://github.com/flatironinstitute/CaImAn/tree/main/testdata

**Comment by pgunn** [comment]
Hello,
That's not paper data - that's part of an elaborate regression test mechanism that we used to run manually (and still can, when we want to).

Ages ago we built a website for the datasets that are associated with the original Caiman paper; I'll find the URL for it and put it in this issue shortly.

**Comment by pgunn** [comment]
Found it. Apologies - it's not a particularly modern website (I built it myself, and my web design skills are not particularly advanced):

https://users.flatironinstitute.org/~neuro/caiman_paper/

I hope this is what you're looking for - I think it has everything in the paper. If it's missing something, please let me know.

**Comment by EricThomson** [comment]
Closing as answered. Please let me know if this was a mistake @loftusa
