### ISSUE TITLE
OnACID fit_online initialization does not match with minibatch size

### ISSUE THREAD

**Issue by andyrdar** [flatironinstitute/CaImAn#1134]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS
 2. Hardware type (x86, ARM..) and RAM: Dual-Core Intel Core i7 and 16GB
 3. Python Version (e.g. 3.9): 3.10.11
 4. Caiman version (e.g. 1.9.12): 1.9.14
 5. Which demo exhibits the problem (if applicable):
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): conda
 7. Details: 

-  I'm trying to use OnACID to analyze personal data, I've been able to run my files through the demo notebook just fine but when I try to use the same (.tif) files for OnACID I get the following error. I'm not exactly sure how to solve it so if anyone know what is going on it'd be greatly appreciated. The current file has 90 frames but I also tried using a larger one with ~10,000 frames of 154 × 510 dimensions and I got a different error 
**- Issue with 90 frame .tif 154 × 510**
Exception                                 Traceback (most recent call last)
Cell In[19], line 2
      1 cnm = cnmf.online_cnmf.OnACID(params=opts)
----> 2 cnm.fit_online()

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:1179](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:1179), in OnACID.fit_online(self, **kwargs)
   1177     model_LN = None
   1178 epochs = self.params.get('online', 'epochs')
-> 1179 self.initialize_online(model_LN=model_LN)
   1180 self.t_init += time()
   1181 extra_files = len(fls) - 1

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:1048](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:1048), in OnACID.initialize_online(self, model_LN, T)
   1046 self.params.set('data', {'dims': dims})
   1047 T1 = np.array(Ts).sum()*self.params.get('online', 'epochs') if T is None else T
-> 1048 self._prepare_object(Yr, T1)
   1049 if opts['show_movie']:
   1050     self.bnd_AC = np.percentile(self.estimates.A.dot(self.estimates.C),
   1051                                 (0.001, 100-0.005))

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:133](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:133), in OnACID._prepare_object(self, Yr, T, new_dims, idx_components)
    130 expected_comps = self.params.get('online', 'expected_comps')
    132 if Yr.shape[-1] != self.params.get('online', 'init_batch'):
--> 133     raise Exception(
    134         'The movie size used for initialization does not match with the minibatch size')
    136 if new_dims is not None:
    138     new_Yr = np.zeros([np.prod(new_dims), init_batch])

Exception: The movie size used for initialization does not match with the minibatch size
 

---------------------------------------------------------------------------
**- Issue with ~10,000 frame .tif 154 × 510**
ValueError                                Traceback (most recent call last)
Cell In[22], line 2
      1 cnm = cnmf.online_cnmf.OnACID(params=opts)
----> 2 cnm.fit_online()

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:1179](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:1179), in OnACID.fit_online(self, **kwargs)
   1177     model_LN = None
   1178 epochs = self.params.get('online', 'epochs')
-> 1179 self.initialize_online(model_LN=model_LN)
   1180 self.t_init += time()
   1181 extra_files = len(fls) - 1

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:1050](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/caiman/source_extraction/cnmf/online_cnmf.py:1050), in OnACID.initialize_online(self, model_LN, T)
   1048 self._prepare_object(Yr, T1)
   1049 if opts['show_movie']:
-> 1050     self.bnd_AC = np.percentile(self.estimates.A.dot(self.estimates.C),
   1051                                 (0.001, 100-0.005))
   1052     #self.bnd_BG = np.percentile(self.estimates.b.dot(self.estimates.f),
   1053     #                            (0.001, 100-0.001))
   1054 return self

File <__array_function__ internals>:200, in percentile(*args, **kwargs)

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4205](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4205), in percentile(a, q, axis, out, overwrite_input, method, keepdims, interpolation)
   4203 if not _quantile_is_valid(q):
   4204     raise ValueError("Percentiles must be in the range [0, 100]")
-> 4205 return _quantile_unchecked(
   4206     a, q, axis, out, overwrite_input, method, keepdims)

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4473](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4473), in _quantile_unchecked(a, q, axis, out, overwrite_input, method, keepdims)
   4465 def _quantile_unchecked(a,
   4466                         q,
   4467                         axis=None,
   (...)
   4470                         method="linear",
   4471                         keepdims=False):
   4472     """Assumes that q is in [0, 1], and is an ndarray"""
-> 4473     return _ureduce(a,
   4474                     func=_quantile_ureduce_func,
   4475                     q=q,
   4476                     keepdims=keepdims,
   4477                     axis=axis,
   4478                     out=out,
   4479                     overwrite_input=overwrite_input,
   4480                     method=method)

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:3752](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:3752), in _ureduce(a, func, keepdims, **kwargs)
   3749             index_out = (0, ) * nd
   3750             kwargs['out'] = out[(Ellipsis, ) + index_out]
-> 3752 r = func(a, **kwargs)
   3754 if out is not None:
   3755     return out

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4639](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4639), in _quantile_ureduce_func(a, q, axis, out, overwrite_input, method)
   4637     else:
   4638         arr = a.copy()
-> 4639 result = _quantile(arr,
   4640                    quantiles=q,
   4641                    axis=axis,
   4642                    method=method,
   4643                    out=out)
   4644 return result

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4756](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4756), in _quantile(arr, quantiles, axis, method, out)
   4754     result_shape = virtual_indexes.shape + (1,) * (arr.ndim - 1)
   4755     gamma = gamma.reshape(result_shape)
-> 4756     result = _lerp(previous,
   4757                    next,
   4758                    gamma,
   4759                    out=out)
   4760 if np.any(slices_having_nans):
   4761     if result.ndim == 0 and out is None:
   4762         # can't write to a scalar

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4575](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/lib/function_base.py:4575), in _lerp(a, b, t, out)
   4573 diff_b_a = subtract(b, a)
   4574 # asanyarray is a stop-gap until gh-13105
-> 4575 lerp_interpolation = asanyarray(add(a, diff_b_a * t, out=out))
   4576 subtract(b, diff_b_a * (1 - t), out=lerp_interpolation, where=t >= 0.5)
   4577 if lerp_interpolation.ndim == 0 and out is None:

File [~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py:218](https://untitled+.vscode-resource.vscode-cdn.net/~/anaconda3/envs/mescore/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py:218), in matrix.__mul__(self, other)
    215 def __mul__(self, other):
    216     if isinstance(other, (N.ndarray, list, tuple)) :
    217         # This promotes 1-D vectors to row vectors
--> 218         return N.dot(self, asmatrix(other))
    219     if isscalar(other) or not hasattr(other, '__rmul__') :
    220         return N.dot(self, other)

File <__array_function__ internals>:200, in dot(*args, **kwargs)

ValueError: shapes (2,15708000) and (2,1) not aligned: 15708000 (dim 1) != 2 (dim 0)

**Comment by EricThomson** [comment]
This is a new one to me. Not sure when I'll be able to get to it, as I'm away at a conference right now. But definitely should try to reproduce and fix.

**Comment by EricThomson** [comment]
Sorry I didn't notice earlier that you are trying to run on a 90 frame movie. This is probably the problem. Basically, when you are in a regime under 400 (or so) frames, that is a corner case. Especially for online, which is typically meant for very long movies with a few thousand frames. Basically, I would never recommend testing out the algorithms with fewer than 400 frames. But for onacid, I would bump that up to 2000 frames.

**Comment by EricThomson** [comment]
Second one is an instance of issue #1102 which should be fixed in the next release, which should be soon.
