### ISSUE TITLE
'NoneType' object is not subscriptable when running estimates.S

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1135]
Hello! 

I tried to plot deconvolution trace by using estimates.S, I successfully use this code in the demo file, however I am confused why there is an error when I run the code on my data. Could you please give me some advice? Thank you!

Here is the code I try to visualize one deconvolution plot, when I replaced S with C for raw trace it works: 

plt.figure(); plt.plot(cnm.estimates.S[cnm.estimates.idx_components[0]])  

_TypeError                                 Traceback (most recent call last)
Cell In[66], line 1
----> 1 plt.figure(); plt.plot(cnm.estimates.S[cnm.estimates.idx_components[0]])

TypeError: 'NoneType' object is not subscriptable

<Figure size 640x480 with 0 Axes>_

And then I write a loop to visualize all the cells with deconvolution traces also encountered the same issue.

Thank you very much!

**Comment by EricThomson** [comment]
Until you run `evaluate_components()`, `idx_components` and its `bad` counterpart will be `None`.

So, either run that, or plot `S[0]`

This is my guess.

**Comment by zhouyi0812** [comment]
I think I have run evaluate_components(), here are the screenshot. Thank you!

![Screenshot 2023-07-10 195010](https://github.com/flatironinstitute/CaImAn/assets/48576330/539cd103-bc24-48f4-9283-6ed65e351b00)
![Screenshot 2023-07-10 195109](https://github.com/flatironinstitute/CaImAn/assets/48576330/8bc3eda4-c517-4dd8-9a00-b6479fa4d9d0)

**Comment by EricThomson** [comment]
Ah, then my other guess is you ran with p=0 so didn't run deconvolution (estimates.S is None). 

when you print estimates.S what do you get. Also, what are your temporal parameters?

**Comment by EricThomson** [comment]
That is weird indeed. It looks like you are doing CNMFE. 

Could you please print and show the output (text not image screenshot) of your parameters (opts)?

What happens if you run:
`cnm.estimates.deconvolve(opts)`

**Comment by zhouyi0812** [comment]
There is nothing come out when I run: cnm.estimates.deconvolve(opts), but also without error

I found another problem not sure if it is related to this. 

When I run cnmf-e model, after 3mins, and "No more components merged!", but it is still with a star sign not stop running. So I interrupt, however I still successfully evaluate the components and the later analysis,
cnm = cnmf.CNMF(n_processes=5, dview=dview, Ain=Ain, params=opts)
cnm.fit(images)

![Screenshot 2023-07-11 161339](https://github.com/flatironinstitute/CaImAn/assets/48576330/ff9698b0-9390-4d54-9a3e-cdb7093b7f06)

The parameter are:

p = 1               
K = None            
gSig = (5, 5)       
gSiz = (21, 21)     
Ain = None          
merge_thr = .7    
rf = 40             
stride_cnmf = 20    
tsub =  2           
ssub =  2          
low_rank_background = None  

gnb = 0            
nb_patch = 0       
min_corr = .8     
min_pnr = 10        
ssub_B = 1         
ring_size_factor = 1.4  
bord_px = 0

Thank you!

**Comment by zhouyi0812** [comment]
Update: Sorry, this time I wait more longer without interrupt, and I got the deconvolution traces!!!!

cnm = cnmf.CNMF(n_processes=5, dview=dview, Ain=Ain, params=opts)
cnm.fit(images)

I have a follow up question: if I want to download the deconvolution data, should I use CNMF.estimates.F_dff to get the traces in array and then save?

Thank you!!!!!!

**Comment by EricThomson** [comment]
Yes don't interrupt before it is done. :smile: 

If you want deconvolution estimates (spike counts), that is in `S`.  `F_dff` is deltaf over f.

**Comment by zhouyi0812** [comment]
Hello! 😄

May I ask you.. I tried to get delta f/f by: plt.figure(); plt.plot(cnm.estimates.F_dff[cnm.estimates.idx_components[0]])
And this is: TypeError: 'NoneType' object is not subscriptable

Also, I tried to follow: cnm2.estimates.detrend_df_f(quantileMin=8, frames_window=250)
but there is not plot out of it.

Thank you!!!

**Comment by zhouyi0812** [comment]
I figure out how to get df/f value for total components and accepted components:

cnm.estimates.detrend_df_f(quantileMin=8, frames_window=250)      Get all the df/f value
F_dff = cnm.estimates.F_dff.copy()   Save all df/f value
F_dff_accepted = cnm.estimates.F_dff[cnm.estimates.idx_components].copy()  filter to save the accepted components only

import pandas as pd
F_dff_df = pd.DataFrame(F_dff)
file_name = "F_dff_accepted.xlsx"
F_dff_df.to_excel(file_name, index=False)   save to excel file

**Comment by zhouyi0812** [comment]
However..... I am confused again. After I set bas_nonneg=True with my parameter.

I am unable to get the data from my original code with the error like this:

----> 1 f_dff_accepted = cnm.estimates.F_dff[cnm.estimates.idx_components]
TypeError: 'NoneType' object is not subscriptable

I am thinking if it is because there are 0 value in my raw trace and it won't be able to conduct the computation.

Thank you!!
