### ISSUE TITLE
Attempt to load avi throws importerror

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#1137]
In Windows 10, dev install, dev branch, `demo_online_cnmfE.ipynb`, when I hit the line `mc.motion_correct(save_movie=True)`, I get the following:
```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[5], line 2
      1 mc = MotionCorrect(fnames, dview=dview, **opts.get_group('motion'))
----> 2 mc.motion_correct(save_movie=True)

File c:\users\eric\development\dev_packages\caiman\caiman\motion_correction.py:248, in MotionCorrect.motion_correct(self, template, save_movie)
    245         self.min_mov = mi
    246     else:
    247         self.min_mov = np.array([high_pass_filter_space(m_, self.gSig_filt)
--> 248             for m_ in cm.load(self.fname[0], var_name_hdf5=self.var_name_hdf5,
    249                               subindices=slice(400))]).min()
    251 if self.pw_rigid:
    252     self.motion_correct_pwrigid(template=template, save_movie=save_movie)

File c:\users\eric\development\dev_packages\caiman\caiman\base\movies.py:1479, in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype, is3D)
   1476 def rgb2gray(rgb):
   1477     return np.dot(rgb[..., :3], [0.299, 0.587, 0.114])
-> 1479 pims_movie = pims.Video(file_name)
   1480 length = len(pims_movie)
   1481 height, width = pims_movie.frame_shape[0:2]    #shape is (h,w,channels)

File ~\miniconda3\envs\caiman_dev\lib\site-packages\pims\api.py:24, in not_available.<locals>.raiser(*args, **kwargs)
     23 def raiser(*args, **kwargs):
---> 24     raise ImportError(
     25         "This reader requires {0}.".format(requirement))

ImportError: This reader requires PyAV, MoviePy, or ImageIO.
```

I have ImageIO installed.

**Comment by EricThomson** [comment]
I reproduced this problem in an independent environment (not caiman), and can't load this or other avi files, and am getting this same error. So it seems to be a caiman-independent problem (at least on Windows 10). I'll open an issue over at the pims library.  I'm now confused why I didn't see this problem earlier when I tested this notebook on the old master branch.

**Comment by pgunn** [comment]
Actually, I can reproduce this too. Maybe somehow I didn't hit a code path that exercised this before. Wondering why.

**Comment by EricThomson** [comment]
Yes I guess that is the bigger more annoying question. 

I was able to get pims to work by installing with `av<10.0` : there seem to be some issues with pyav (relatively) new move from 9->10, even on Linux (https://github.com/soft-matter/trackpy/issues/737).

**Comment by EricThomson** [comment]
Ok for this issue I'm going to just work on what happens after fixing this problem: in my dev env, I `mamba install -c conda-forge "av<10.0"` and the errors stopped happening with pims. But this means,  we are now testing the branches in the code when open-cv fails. 

Which is I think a useful test, as other things are starting to fail. I'll go through and fix them and do a PR, and we can get back to the weird opencv fail after.

**Comment by EricThomson** [comment]
Fixing the `cv_failed` branch will take some work, as the `dims` variable is used in the `if subindices is not None` conditional for patch processing in motion correction (starting on line 1433 of `movies.py`), which throws an error when they are 0, as dims is not re-defined in the `pims` movie load branch.
https://github.com/flatironinstitute/CaImAn/blob/b3e4b72bd3d8f7926576a9624ad628ddb272ecf6/caiman/base/movies.py#L1433  

So I think we basically have two things to fix here: loading avi with opencv in windows, and fix the `cv_failed` use case. I have a few other things I'm trying to finish this week, so won't be able to sprint through these quickly.

**Comment by EricThomson** [comment]
It looks like opencv will load avi correctly in Windows in version 4.7 of opencv, which just came out recently (a little over two weeks ago). It may be a little while (e.g., release after next) before this is ready for prime time.

**Comment by pgunn** [comment]
Interesting that on conda-forge, OpenCV seems to have skipped a python 3.10 build. I wonder why things worked out that way. Their build matrix is 3.8/3.9/3.11.

**Comment by pgunn** [comment]
Actually nevermind that, I misread the binary list.

**Comment by pgunn** [comment]
The issue I filed:
https://github.com/AnacondaRecipes/tensorflow_recipes/issues/46

**Comment by pgunn** [comment]
Other options to get the next release out the door:
1) Fix the pims code path, possibly by adding more dependencies
2) Find another opensource library that can decode avis
3) Temporarily-or-not change the demo code to use some other file format, and hope users don't have avi-formatted data until this all gets sorted out

**Comment by EricThomson** [comment]
Fixed in most recent release!
