### ISSUE TITLE
Different result of pipeline and OnACID

### ISSUE THREAD

**Issue by chimmut** [flatironinstitute/CaImAn#1138]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Windows 11
 2. Hardware type (x86, ARM..) and RAM: x86
 3. Python Version (e.g. 3.9): 3.10.8
 4. Caiman version (e.g. 1.9.12): 1.9.15
 5. Which demo exhibits the problem (if applicable): demo_pipeline.ipynb and demo_OnACID_mesoscope.ipynb
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): pure conda 
 7. Details: 
     Hello!
     I tried to analyze ‘Sue_2x_3000_40_-46.tif’ using demo_OnACID_mesoscope.ipynb, which is originally analyzed in demo_pipeline.ipynb. But the neuron number was 81, which is different from the result 63 of demo_pipeline.ipynb. Would you like to tell me what I should do with ‘Sue_2x_3000_40_-46.tif’ to get consistent results, or what parameters to tune.

**Comment by pgunn** [comment]
Hello,
We expect the online and offline algorithms to produce somewhat different results; it may be possible to find parameters to get more similar results, but the algorithms differ enough that you should not expect the results to be identical.

**Comment by chimmut** [comment]
Thank you. I got it.



---Original---
From: "Pat ***@***.***&gt;
Date: Thu, Jul 20, 2023 04:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [flatironinstitute/CaImAn] Different result of pipeline andOnACID (Issue #1138)




 
Hello,
 We expect the online and offline algorithms to produce somewhat different results; it may be possible to find parameters to get more similar results, but the algorithms differ enough that you should not expect the results to be identical.
