### ISSUE TITLE
CNMF-e how to use the same mask on different sessions

### ISSUE THREAD

**Issue by annahayoon** [flatironinstitute/CaImAn#1145]
Hi, I'm just using the CNMF-e pipeline on MATLAB and python--

If I want to manually set the same masks on different sessions, how should I go about this?

Thank you!

**Comment by kushalkolar** [comment]
I think you can pass `esimates.A` from your "reference session" to `Ain`
when creating the CNMF object, so like:

```python
# do CNMF of your reference session, or load a cnmf hdf5 file
cnm.estimates.A

# start cnmf of another session
cnm_session2 = CNMF(...other args, Ain=cnm.estimates.A)
```
