### ISSUE TITLE
estimates.nb_view_components [and _3d] throws error in demo notebooks

### ISSUE THREAD

**Issue by noahpettit** [flatironinstitute/CaImAn#1149]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows):  **Windows 10**  
 2. Hardware type (x86, ARM..) and RAM: **x86**
 3. Python Version (e.g. 3.9): **3.10.8**
 4. Caiman version (e.g. 1.9.12): **1.9.15**
 5. Which demo exhibits the problem (if applicable): **demo_caiman_cnmf_3D, demo_pipeline**
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): **pure conda**
 7. Details: 
 
 
Hello,
I'm new to using caiman. I just installed it (fresh pure conda installation) and was working through the demos. Unfortunately I am getting the following error when trying to run cnm.estimates.nb_view_components_3d or cmn.estimates.nb_view_components
 
```
 ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[33], line 1
----> 1 cnm.estimates.nb_view_components_3d(image_type='mean', dims=dims, axis=2);

File [c:\Users\scanimage\miniconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\estimates.py:507](file:///C:/Users/scanimage/miniconda3/envs/caiman/lib/site-packages/caiman/source_extraction/cnmf/estimates.py:507), in Estimates.nb_view_components_3d(self, Yr, image_type, dims, max_projection, axis, denoised_color, cmap, thr)
    505 plt.ion()
    506 nr, T = self.C.shape
--> 507 if self.R is None or self.R == b'NoneType':
    508     self.R = self.YrA
    509 if self.R.shape != [nr, T]:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
---------------------------------------------------------------------------

```
 
 Specifically, these errors arise in the "view components per plane" section of demo_caiman_cnmf_3d.ipynb, and in multiple cells of the demo_pipeline.ipynb. They might be in other demos as well, I have not checked. 
 
 I was wondering if this could be related to https://github.com/flatironinstitute/CaImAn/issues/1127 but the bokeh version that is currently installed in the caiman environment (following default install intructions) is  2.4.3.

In what may be related, I am also unable to run demo_dendritic.ipynb because hv.notebook_extension('bokeh') throws an error:

```
WARNING:param.notebook_extension: Holoviews bokeh extension could not be imported, it raised the following exception: ValueError('ClassSelector parameter None value must be an instance of (function, tuple), not <function size at 0x00000202F8365D70>.')

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 30
     28 import holoviews as hv
     29 bpl.output_notebook()
---> 30 hv.notebook_extension('bokeh')

File [c:\Users\scanimage\miniconda3\envs\caiman\lib\site-packages\pyviz_comms\__init__.py:64](file:///C:/Users/scanimage/miniconda3/envs/caiman/lib/site-packages/pyviz_comms/__init__.py:64), in extension.__new__(cls, *args, **kwargs)
     62 except Exception:
     63     pass
---> 64 return param.ParameterizedFunction.__new__(cls, *args, **kwargs)

File [c:\Users\scanimage\miniconda3\envs\caiman\lib\site-packages\param\parameterized.py:3658](file:///C:/Users/scanimage/miniconda3/envs/caiman/lib/site-packages/param/parameterized.py:3658), in ParameterizedFunction.__new__(class_, *args, **params)
   3656 inst = class_.instance()
   3657 inst.param._set_name(class_.__name__)
-> 3658 return inst.__call__(*args,**params)

File [c:\Users\scanimage\miniconda3\envs\caiman\lib\site-packages\holoviews\ipython\__init__.py:116](file:///C:/Users/scanimage/miniconda3/envs/caiman/lib/site-packages/holoviews/ipython/__init__.py:116), in notebook_extension.__call__(self, *args, **params)
    114 def __call__(self, *args, **params):
    115     comms = params.pop('comms', None)
--> 116     super().__call__(*args, **params)
    117     # Abort if IPython not found
    118     try:

File [c:\Users\scanimage\miniconda3\envs\caiman\lib\site-packages\holoviews\util\__init__.py:718](file:///C:/Users/scanimage/miniconda3/envs/caiman/lib/site-packages/holoviews/util/__init__.py:718), in extension.__call__(self, *args, **params)
...
    717 if selected_backend is None:
--> 718     raise ImportError('None of the backends could be imported')
    719 Store.set_current_backend(selected_backend)

ImportError: None of the backends could be imported

```
 
 That is a truncated output, lmk if you want to see the full traceback
 
 Thanks in advance for any advice, and big thanks for all your work on this excellent toolbox!

**Comment by EricThomson** [comment]
This is an issue with how it is handling those comparisons that is newly emerging with newer `numpy`  versions (I *think*). In the next release it will be fixed by replacing 

> if self.R is None or self.R == b'NoneType':

with:

> if self.R is None or not isinstance(self.R, np.ndarray):

You can replace those lines to get it to work in the meantime.

**Comment by EricThomson** [comment]
Fixed in most recent release.
