### ISSUE TITLE
Windows installation problems

### ISSUE THREAD

**Issue by darioringach** [flatironinstitute/CaImAn#115]
Trying to install on Windows with Python 2.7

Getting:

```
    creating build\temp.win-amd64-2.7\Release\tifffile
    C:\Users\dario\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox
/MD /W3 /GS- /DNDEBUG -IC:\Users\dario\Anaconda2\envs\caiman\lib\site-packages\numpy\core\include -IC:\Users\dario\Anaco
nda2\envs\caiman\include -IC:\Users\dario\Anaconda2\envs\caiman\PC /Tctifffile/_tifffile.c /Fobuild\temp.win-amd64-2.7\R
elease\tifffile/_tifffile.obj
    _tifffile.c
    tifffile/_tifffile.c(75) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    error: command 'C:\\Users\\dario\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\
amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\dario\Anaconda2\envs\caiman\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\dario\\
appdata\\local\\temp\\pip-build-zkhuau\\tifffile\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().re
place('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\dario\appdata\local\temp\
pip-4zmsfu-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users
\dario\appdata\local\temp\pip-build-zkhuau\tifffile\

CondaValueError: pip returned an error.

```
...and trying to move on:

```
C:\Users\dario\Documents\MATLAB\CaImAn>activate caiman

(caiman) C:\Users\dario\Documents\MATLAB\CaImAn>conda install -c conda-forge tensorflow keras
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 2.7*
  - tensorflow -> python 3.5*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by epnev** [comment]
@darioringach 
We'll look into this but it appears that tensorflow on windows is not supported for Python 2.7. See e.g., [here](https://stackoverflow.com/questions/45316569/how-to-install-tensorflow-on-python-2-7-on-windows). Perhaps you can try installing a version prior to 1.2

**Comment by mingguichen** [comment]
@darioringach I am not sure whether you tried the python 3.5 for caiman and tensorflow. I worked on this combination under Windows this week. It works quite well, only with several small bugs fixed by myself. Pull request is already submitted for this bug-fixed version for Windows. Hope it helps.

**Comment by darioringach** [comment]
I have not tried yet...  Will do after SfN.

**Comment by agiovann** [comment]
@darioringach it is not strictly required to have tensorflow installed. You can run most of the pipeline without it. In general, we suggest Mac OS and linux over Windows since the support of many packages for windows is lacking. Anyways, we have users that managed to run the package on windows and we are setting up automatic tests that include Windows.

**Comment by agiovann** [comment]
Dear @darioringach we were able to provide to support on windows for Python 3 but not for Python 2. Please let us know if this works for you. If you need Python 2 we will need to discuss your specific case.

**Comment by agiovann** [comment]
NOTE TO SELF: we can try Theano backend in Python 2.
