### ISSUE TITLE
Quality assurance method for ROI detection

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1152]
Hello!

May I ask, if there is a way that we can know that I am selecting the right parameters?
Like, there is always output with parameters, and how should I know if I am choosing the best parameter that reflects the most relative situation? Or as long as I think that the parameters are able to find out the cells that exist in the experiment that will be the goal?

Thank you!

**Comment by zhouyi0812** [comment]
Hello! May I ask a question about df/f. 
I am using cnm.estimates.F_dff to get the trace for df/f, but it looks like there is not much different between raw trace and df/f.

Thank you!

![Screenshot 2023-08-16 170728](https://github.com/flatironinstitute/CaImAn/assets/48576330/2b9ab8a1-16ae-4c5c-be94-19e5923b16b2)

**Comment by EricThomson** [comment]
You are doing CNMFE? There won't be much difference, in fact dfof is actually noisier detrended calcium trace. This is a complicated topic I discuss a little bit here: https://github.com/EricThomson/yacare/blob/main/normalize_1p_traces.ipynb

**Comment by zhouyi0812** [comment]
Yes! Thank you very much I will check that code.
Also, I am just not sure if my case matches the situation since I am using wild field imaging I assume won't generate much noise compared with 1p data. 
Do you think it is still applicable? 
Thank you!

**Comment by EricThomson** [comment]
Are you cnmf or cnmfe this is the main important distinction rather than 1p or 2p.

**Comment by EricThomson** [comment]
Yes this is what I thought, then that notebook I linked to is relevant, and the dfof is only returning detrended, not normalized traces.
