### ISSUE TITLE
gSig and gSiz difference

### ISSUE THREAD

**Issue by ggmirandac** [flatironinstitute/CaImAn#1157]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows):
 2. Hardware type (x86, ARM..) and RAM:
 3. Python Version (e.g. 3.9):
 4. Caiman version (e.g. 1.9.12):
 5. Which demo exhibits the problem (if applicable):
 6. How you installed Caiman (pure conda, conda + compile, colab, ..):
 7. Details: 

Hi

I have a question about the difference of the parameters gSig and gSiz.

For example on demo_pipeline_cnmfe.py it says:

```
gSig = (3, 3)       # gaussian width of a 2D gaussian kernel, which approximates a neuron
gSiz = (13, 13)     # average diameter of a neuron, in general 4*gSig+1
```

But in params.py it says that 
```
gSiz: [int, int], default: [int(round((x * 2) + 1)) for x in gSig],
half-size of bounding box for each neuron
```

and also in demo_online_cnmfe.py

```
"gSig = (6, 6)                                  # expected half size of neurons\n",
"gSiz = (15, 15)                                # half size for neuron bounding box   \n",
```

So I'm very confused about these definitions. gSiz defines de diameter of a neuron, or it is the half size of a neuron bounding box. Also, about gSig, it has two definitions ``` gaussian width of a 2D gaussian kernel, which approximates a neuron ``` and ```expected half size of neurons```.

Can anyone clarify me these two parameters? 

Also, what are you referring with the term of bounding box?

**Comment by EricThomson** [comment]
See #1139 and #970 for a discussion of these topics.
