### ISSUE TITLE
Caiman cannot find example_movies folder

### ISSUE THREAD

**Issue by wkuthsc** [flatironinstitute/CaImAn#1160]
Please fill in the following for any issues

Your setup:
Operating System (Linux, MacOS, Windows): Windows
Hardware type (x86, ARM..) and RAM: 64bit
Python Version (e.g. 3.9): 3.11.4
Caiman version (e.g. 1.9.12): unsure
Which demo exhibits the problem (if applicable): caiman can't find example_movies folder
How you installed Caiman (pure conda, conda + compile, colab, ..): (base) PS C:\Users\wkrueger> mamba create -n caiman -c conda-forge caiman
Details: I am running the caiman script in spyder and keep getting this error message: 

File ~\AppData\Local\miniconda3\envs\caiman\lib\site-packages\caiman\utils\utils.py:119 in download_demo
    raise Exception('Cannot find the example_movies folder in your caiman_datadir - did you make one with caimanmanager.py?')

**Comment by pgunn** [comment]
Hello,
In the instructions, we mention the post-install step of running the `caimanmanager.py` utility, with the `install` argument.

If you haven't done this, please do `conda env list` and send us the result and I'll help you through the process.

**Comment by wkuthsc** [comment]
(base) PS C:\Users\wkrueger> conda env list
# conda environments:
#
base                  *  C:\Users\wkrueger\AppData\Local\miniconda3
caiman                   C:\Users\wkrueger\AppData\Local\miniconda3\envs\caiman

**Comment by pgunn** [comment]
Please do:
`conda activate caiman`

And then

`python c:\users\wkreuger\appdata\local\miniconda3\envs\caiman\bin\caimanmanager.py install`

that should go through the install process and get you the demo you need.

**Comment by wkuthsc** [comment]
(base) PS C:\Users\wkrueger> conda activate caiman
(caiman) PS C:\Users\wkrueger> python c:\users\wkreuger\appdata\local\miniconda3\envs\caiman\bin\caimanmanager.py install
C:\Users\wkrueger\AppData\Local\miniconda3\envs\caiman\python.exe: can't open file 'c:\\users\\wkreuger\\appdata\\local\\miniconda3\\envs\\caiman\\bin\\caimanmanager.py': [Errno 2] No such file or directory
(caiman) PS C:\Users\wkrueger>

**Comment by wkuthsc** [comment]
caught the error. Krueger was spelled "kreuger". Think we're good now. Doing a test run

**Comment by wkuthsc** [comment]
all good now. Thanks again Pat!
