### ISSUE TITLE
F-Dff Object Returns NoneType

### ISSUE THREAD

**Issue by CraigScullyClemmons** [flatironinstitute/CaImAn#1163]
Operating system: Windows

Python version (3.x): 3.9.12

Working environment (Python IDE/Jupyter Notebook/other): Jupyter notebook

Which of the demo scripts you're using for your analysis (if applicable): demo_caiman_cnmf_3D.ipynb

CaImAn version*: 1.8.4

CaImAn installation process (pip install ./pip install -e ./conda): conda install on mambaforge 

When running the cnmf demo, the F_dff object exists but contains no data.

cnm.estimates.F_dff.shape yields
AttributeError: 'NoneType' object has no attribute 'shape' 

The only modification made was the patch described in [problem running nwb tutorial #962 (https://github.com/flatironinstitute/CaImAn/issues/962), in which every instance of "if self.R is None or self.R == b'NoneType':" was replaced by "if self.R is None or not isinstance(self.R, np.ndarray):" in the estimates code.

**Comment by EricThomson** [comment]
Closing this as answered. Please let me know if more help needed.
