### ISSUE TITLE
A bug in play_movie function of estimates.py

### ISSUE THREAD

**Issue by wsshen** [flatironinstitute/CaImAn#1164]
Hi, in the current implementation of play_movie function, line 667, imgs[frame_range] is sliced the second time after it's done initially in the if block in line 620. This would gave error if one tries to play or save a portion of the movie. Thanks.

**Comment by EricThomson** [comment]
Thanks we'll have to take a look at this.

**Comment by EricThomson** [comment]
@wsshen good eye! fixing now.

**Comment by EricThomson** [comment]
Issue fixed thanks for bringing this up.
