### ISSUE TITLE
Adjust the CNMF-E parameters for widefield data on motion correction

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1170]
Hello!

My cell data was collected from the widefield microscope and it's not moving at all. Therefore I am a bit confused how should I adjust the parameters from the cnmf-e demo to best suit my situation. 

First, will it be possible to turn off the high pass filter setting to (0,0)?
Second, I do not fully understand what is the difference between piecewise rigid and rigid. It looks like they both use the patch but piecewise is better with non-rigid motion?

If I think there won't be any movement, can I set max_shifts = (0, 0)? 
Thank you!

**Comment by EricThomson** [comment]
set `motion_correct` to false in the cnmfe demo notebook. It sounds like you just don't need motion correction.

**Comment by zhouyi0812** [comment]
If I turn off the motion correction...how can I save it to mmap?

NameError                                 Traceback (most recent call last)
Cell In[22], line 2
      1 # load memory mappable file
----> 2 fname_new = cm.save_memmap(mc.mmap_file, base_name='memmap_2_', order='C',
      3                                border_to_0=0)  # exclude borders

NameError: name 'mc' is not defined

Thank you!!!!

**Comment by zhouyi0812** [comment]
I am wondering, how can I assess if the movie needs motion correction or not? based on eye check everything works fine but something may happen and eye can't catch. 

Thank you!

**Comment by zhouyi0812** [comment]
> If I turn off the motion correction...how can I save it to mmap?
> 
> NameError Traceback (most recent call last) Cell In[22], line 2 1 # load memory mappable file ----> 2 fname_new = cm.save_memmap(mc.mmap_file, base_name='memmap_2_', order='C', 3 border_to_0=0) # exclude borders
> 
> NameError: name 'mc' is not defined
> 
> Thank you!!!!

I just checked the demo and find out that there is already answer there

 fname_new = cm.save_memmap(fnames, base_name='memmap_',
                               order='C', border_to_0=0, dview=dview)

**Comment by zhouyi0812** [comment]
Hello! I was directly save the file without motion correction, but there is an error I am not sure how to fix it.

Exception                                 Traceback (most recent call last)
Cell In[12], line 21
     18     fname_new = cm.save_memmap(fname_mc, base_name='memmap_', order='C',
     19                                border_to_0=bord_px)
     20 else:  # if no motion correction just memory map the file
---> 21     fname_new = cm.save_memmap(fnames, base_name='memmap_',
     22                                order='C', border_to_0=0, dview=dview)

File C:\Users\Public\anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py:397, in save_memmap(filenames, base_name, resize_fact, remove_init, idx_xy, order, var_name_hdf5, xy_shifts, is_3D, add_to_movie, border_to_0, dview, n_chunks, slices)
    348 """ Efficiently write data from a list of tif files into a memory mappable file
    349 
    350 Args:
   (...)
    394 
    395 """
    396 if not isinstance(filenames, list):
--> 397     raise Exception('save_memmap: input should be a list of filenames')
    399 if slices is not None:
    400     slices = [slice(0, None) if sl is None else sl for sl in slices]

Exception: save_memmap: input should be a list of filenames

Thank you!!!!

**Comment by sun1000yao** [comment]
To solve "Exception: save_memmap: input should be a list of filenames", use bracket as [movie_path] to make it as a list.

**Comment by sun1000yao** [comment]
a bracket should also be added to demo_pipline_cnmfE

else:  # if no motion correction just memory map the file
    fname_new = cm.save_memmap(**[movie_path]**, base_name='memmap_',
                               order='C', border_to_0=0, dview=None)
