### ISSUE TITLE
Issues with detrend_df_f

### ISSUE THREAD

**Issue by JLRomero12** [flatironinstitute/CaImAn#1171]
Please fill in the following for any issues.

Your setup:
 1. Operating System (Linux, MacOS, Windows): Windows 10
 2. Hardware type (x86, ARM..) and RAM: x86 and 256GB of RAM
 3. Python Version (e.g. 3.9): Python 3.10.8
 4. Caiman version (e.g. 1.9.12): 1.9.15
 5. Which demo exhibits the problem (if applicable): Costume Code
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): I installed through mesmerize core
 7. Details:

Hello! Thank you very much for the help you have given me with my RAM issues in the past! I come back now with issues calculating the df_f on my data. For the record, this is with 1P data on rats. 

Currently, I have tried using cnm.estimates.detrend_df_f() in order to calculate the df_f as both the demos and the documentation suggests, and it works pretty well in some cells, but it shows some incredibly weird calculation in others. Let me show you:

![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/4c48a6e5-075d-4870-a0a9-6cb13248620c)
![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/1a600e28-16dd-4c7c-9f26-e59cb4363645)
In this example on blue, you can see C, and on orange, you can see the calculated df_f. The fluorescence stays pretty flat, but the calculated df_f is all over the place. If I zoom out in this example, the max the df_f it reaches would be ~3500, and the lowest value would be ~-2900. My immediate thought would be that maybe the swing is caused by something in the residuals, so I plotted the C+YrA and df_f, and this is what I see:

![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/bf89eb5f-5613-42a3-8bca-7dc15aab2fc6)

I have tried using cnm.estimates.detrend_df_f(detrend_only=True) and did not see a change, and I even used cnm.estimates.detrend_df_f(flag_auto=False) and it got even worse. 

It is also worth mentioning that this is not only a problem on one cell but multiple different cells, on multiple different sessions, and on multiple different rats. I would appreciate any sort of guidance on this issue.

**Comment by zhouyi0812** [comment]
I have encountered the same issue, and here is the notebook for how to normalize 1p data 
https://github.com/EricThomson/yacare/blob/main/normalize_1p_traces.ipynb

**Comment by JLRomero12** [comment]
Thank you, Zhouyi and Eric! I am currently going through the notebook that Zhouyi suggested.

for Eric, I tried setting the use_residuals to false in the cnm.estimates.detrend_df_f function, and it didn't change much. It is not so much the noise that is an issue it is these wild swings in the df_f where it goes to 3000+ and -3000 that are wrong and not caused by any obvious aspect of the data. 

For your suggestion of setting dff_flag to true, could you tell me what you mean in the cnm.estimates.deconvolve function? If so, could you please help me figure out what to write for the parameters of that function (it will not run without me declaring them). Looking at the documentation for the specific cnm.estimates.deconvolve it says 

`params: params object
    Parameters of the algorithm`

when I look at the documentation for CNMF.deconvolve, I see this:

 ` CNMF.deconvolve(p=None, method_deconvolution=None, bas_nonneg=None, noise_method=None, optimize_g=0,s_min=None, **kwargs)`
`Performs deconvolution on already extracted traces using constrained foopsi`

Which I am assuming are the right param values, but I figure that setting everything to None is probably not a good idea. Could you point out what I should use in these parameters?

**Comment by EricThomson** [comment]
I would use the values at issue 528 to start with.

**Comment by JLRomero12** [comment]
So, I have made progress! Using cnm.estimates.deconvolve is awesome, and it fixed many of the problems with the old df_f. The main issue I am having now is that I am still seeing increases in the df_f when there is no increase in fluorescence (both for C and C+YrA). See the following plots:
![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/0aabe0eb-c41b-4e10-9114-fe54991002bc)
![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/958ec44a-4ca9-4a2e-a1a1-c6ab5cd0b7c7)

You can see in the raw trace that when there is a drop in activity, there is a huge increase in dff. In addition, around X = 1600 (when there is a bump while the raw signal is still below baseline) the dff does not change even though there is a bump in there. Additioning it seems like the dff is "lagging behind" the activity of C, though it eventually does "catch up". See a zoomed-in example: 
![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/4cc4caf5-9890-45d4-826c-4f541a444da1)
![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/b4fecc0c-97c9-44ce-8a22-6162b0fb099a)

Could this be because, in the raw trace, the activity is "below baseline? I am not sure if this is supposed to be right. There are other examples such as this one. 

I have changed many deconvolve parameters to see if anything would change. The one thing I was not able to change was the method_deconvolution since when I tried 'cvx' I got the error "Constrained Foopsi requires cvxopt and picos packages" and when I tried 'cvxpy' I got the error: 'cvxpy solver requires installation of cvxpy. Not working in windows at the moment.' and I using windows 😞 

Would you suggest I change other parameters or use a different function?

Also, I wanted to deeply thank you for taking the time to help me out with this!

**Comment by EricThomson** [comment]
That is very strange I've never seen things misaligned like that. I use this function to plot both original and denoised versions to see which I prefer for a given experimental setup:

```
def plot_deconv(F_dff, F_dff_dec, S, S_dff):
    """
    Inspect standard and denoised version of dff and S.
    """
    fig, axs = plt.subplots(2, 1, figsize=(18, 9), sharex = True, sharey = True)
    axs = axs.ravel()
    
    # Original
    axs[0].plot(F_dff, color = 'cyan', label = "dff", linewidth = 1)
    axs[0].plot(S, color = 'r', linewidth = 1, label = "S")
    axs[0].autoscale(enable=True, axis = 'x', tight = True)
    axs[0].set_title('Original')
    # Denoised
    axs[1].plot(F_dff_dec, color = 'cyan', label = "dff", linewidth = 1)
    axs[1].plot(S_dff, color = 'r', linewidth = 1, label = "S")
    axs[1].autoscale(enable=True, axis = 'x', tight = True)
    axs[1].set_title('Denoised')
    axs[1].set_xlabel('Frame')
    
    plt.tight_layout() #so they aren't all smushed together
    return
```

Not sophisticated at all just takes in individual traces. So for instance if I've loaded my cnmf into `cnmf_loaded` I'll use as follows (say I haven't calculated dff yet):

```
#%% Extract DF/F values 
cnm_loaded.estimates.detrend_df_f(quantileMin = 8, # have not yet played with this
                           frames_window = 250,  # have not yet played with this
                           detrend_only = True);  #set to true for 1p where baseline cannot be determined

# Following should create F_dff_dec and S_dff
cnm_loaded.estimates.deconvolve(cnm_loaded.params, dff_flag = True)
```

Then to pick a trace and inspect regular/denoised:

```
# Plot the two types of estimate see which seems reasonable
good_ind = 15
to_plot = cnm_loaded.estimates.idx_components[good_ind]
F_dff = cnm_loaded.estimates.F_dff[to_plot,:]
F_dff_dec = cnm_loaded.estimates.F_dff_dec[to_plot,:]
S = cnm_loaded.estimates.S[to_plot,:]
S_dff = cnm_loaded.estimates.S_dff[to_plot,:]
plot_deconv(F_dff, F_dff_dec, S, S_dff)
```

Doing things like this I've never seen gross misalignments in time. I'm curious if you follow this code you do.

**Comment by JLRomero12** [comment]
Thank you again for your help and for that code blur for plotting specific traces. Seems very useful for quickly checking the data. This is how I am calculating the dff and dff_sec

    cnm = cm.source_extraction.cnmf.cnmf.load_CNMF(save_fold + 'CNMFE_results.hdf5', n_processes=10, dview=dview)
    p= 1
    method_deconvolution = 'oasis'
    bas_nonneg = True
    noise_method = 'logmexp'
    s_min = None
    optimize_g = 0
    noise_range = [0.25, 0.5]
    fudge_factor = 0.96
    
    # Run deconvolve to try to get the df_f
    deconvolve_dict = {'p': p,
                       'method_deconvolution': method_deconvolution,
                       'bas_nonneg': bas_nonneg,
                       'noise_method': noise_method, 
                       's_min': s_min,
                       'optimize_g': optimize_g,
                       'noise_range': noise_range,
                       'fudge_factor': fudge_factor}
    
    dec_param = cnmf.params.CNMFParams(params_dict=deconvolve_dict)
    dec_param.change_params(deconvolve_dict)
    
    cnm.estimates.deconvolve(params = dec_param, dview = dview, dff_flag = True)
    
    cnm.estimates.detrend_df_f(quantileMin = 8, # have not yet played with this
                           frames_window = 250,  # have not yet played with this
                           detrend_only = True);  #set to true for 1p where baseline cannot be determined)
    
    #I was originally using just 
    #cnm.estimates.detrend_df_f(detrend_only = True);
    #but have switched to using:
    cnm.estimates.detrend_df_f(quantileMin = 8, # have not yet played with this
                           frames_window = 250,  # have not yet played with this
                           detrend_only = True);  #set to true for 1p where baseline cannot be determined)

I plotted a different trace to the one I had shown before, and I still saw activity in the denoised that was not there in the original one. Look at these traces:
![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/e2c12910-df59-4659-9273-f39ca207a575)
Around 25500, the denoised has activity, but the original doesn't. 

Going back to the previous trace I posted in my last comment, this is what I see when plotting with your code:
![image](https://github.com/flatironinstitute/CaImAn/assets/32527055/e636fc93-ace5-4cd5-aaf2-30d1f9152c56)

If you need me to show you more of my code, I would be happy to!

**Comment by EricThomson** [comment]
How does it look when you do dff without residual -- how does that compare to the stuff in the first row above? 

Plus -- yikes it does look like the second plot is introducing artifact. I have never seen this before and am not sure what is happening.  Maybe try setting `bas_nonneg` to `True` from the get-go if you aren't?

You are definitely getting some weird traces. My guess is you have some very high amplitude high frequency noise. You might need to lower the time window for percentile calculation lower than 250 frames or something.  I'm guessing here though that is some unusual stuff.  Can you post a short compressed video so we can see what your data look like? How is the background noise around these cells where this is happening?

@j-friedrich not sure if you have seen this before it is very strange to me!

**Comment by JLRomero12** [comment]
Hello Eric, 

I have updates! So, after reading the raw code of how each function works, I realized that the order I was doing was wrong. I didn't realize that cnm.estimates.deconvolve takes the dff that was calculated by cnm.estimates.detrend_df_f. From my posted code, you can see I used detrend_df_f after deconvolve. This means that for deconvolve, I used the saved df_f that I loaded in the first line and calculated with detrend_only = False (which is the default). 

I think the original issue I was having with the df_f is because this is 1P data. As your documentation says, it is very hard to calculate the baseline activity since there is so much background, so once I detrend only, the graph looks much better, and once I use deconvolve, they look even better. Does this mean I should give up on using df_f for further analysis? Also, F_dff_dec is not normalized across all cells, right? (since it is just a detrended C+YrA). Would you suggest I use S_dff instead, since that is technically normalized (I could be super wrong in this assumption)? Or should I just Z-Score my F_dff_sec traces (which is basically what the notebook that Zhouyi posted suggested)?

**Comment by EricThomson** [comment]
Good to know you got the order of operations figured out. 

Sorry I missed your second set of questions. Before I get to that, I am currently revising demo notebook and looking into `estimates.detrend_df_f()` and I'm afraid `use_residuals` keyword actually has no effect.  :sob: This is a bug I will look into fixing soon.

In terms of what to do, I would consider either normalizing to noise as in that notebook, or using a traditional measure like `(F-F0)/F0`, where `F0` is a rolling percentile (calculated over certain number of frames). This is something I plan to open an issue about, and probably add as an option for Caiman in the future.  (Note F0 doesn't have to be a rolling percentile, it can be any measure of baseline: mean overall of the signal, some people use an early period when the animal is "not doing anything"). 

This is something we need to better document and clarify at Caiman.
