### ISSUE TITLE
cell is sliding and how can I exclude it?

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1180]
Hello! 
I encounter a problem that a few of my cells are sliding in widefield and the rest is fixed.  And the package identify the whole trajectory as a footprint. I tried to adjust the gsig and gsiz to exclude but seems doesn't work. I wonder if there is anyway improve it by which parameter?
Thank you!

![5_Original_and_Accepted_Components_098C1d16_B2_C1_1_00d00h00m](https://github.com/flatironinstitute/CaImAn/assets/48576330/087136a8-f9cc-48ac-84e9-027ae3c3452b)

**Comment by EricThomson** [comment]
This is a problem with motion correction not source extraction. If you have movement like this, it will be a problem.

**Comment by zhouyi0812** [comment]
Thank you!
I tried to limited the max_shifts for the movie, however I think it just doesn't work for that and still identify the object.
So I wonder before I decide to toss the movie, if it is possible that I just deleted the specific ROI in the result? and if this will impact the traces from other cells?
