### ISSUE TITLE
Issues with win installation. Cant install caimanmanager in env

### ISSUE THREAD

**Issue by Jorgenhoyer** [flatironinstitute/CaImAn#1187]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): windows
 2. Hardware type (x86, ARM..) and RAM: AMD ryzen 9 pro, 32GB RAM
 3. Python Version (e.g. 3.9): 3.12
 4. Caiman version (e.g. 1.9.12): -
 5. Which demo exhibits the problem (if applicable):
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): issues with install, step 4: caimanmanager install
 7. Details: 

I am trying to install mescore and I am stuck at step 4: caimanmanager.py install. I cant locate the file. I have installed Anaconda3 and mamba and followed the step guide as presented on github. Can you help out?

Kind regards
Jørgen

**Comment by pgunn** [comment]
Hello,
I think the mescore instructions are slightly out-of-date; try instead doing `caimanmanager install`

The most recent caiman release improved the release process and changed the install process slightly; the mescore instructions probably haven't been updated yet.

**Comment by Jorgenhoyer** [comment]
Hi,

It doesnt seem to work. To only files i find that seems relevant in the env
is in ..\anaconda3\envs\mescore\Scripts\ there are two files there:
caimanmanager.exe and caimanmanager-script.py. But none of them works as
install files. Am I on the right track?

Jørgen

ons. 11. okt. 2023 kl. 14:00 skrev Pat Gunn ***@***.***>:

**Comment by pgunn** [comment]
If you have activated the mescore environment, the caimanmanager.exe thing should be in your path, so `caimanmanager install` should work.

**Comment by Jorgenhoyer** [comment]
Sorry for the last reply. It works, I was just a bit inpatient.. i think Im
all set to use mescore now. thank you for fast replies!

Jørgen

ons. 11. okt. 2023 kl. 14:23 skrev Pat Gunn ***@***.***>:

**Comment by pgunn** [comment]
Glad to hear it. I hope it serves you well.
