### ISSUE TITLE
How to get cell x/y coordinates 

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1193]
Hello!

I wonder how can get the single x and y coordinates for each cell on CaIman? 

Here is my code for contour, but each cell has so many coordinates for it.
Thank you!

idx = cnm.estimates.idx_components[0]  
contour_dict = cnm.estimates.coordinates[idx]  
contour_coords = contour_dict['coordinates']  
contour_coords

**Comment by EricThomson** [comment]
What you are calling `contour_dict` is a coordinates object that includes `CoM` key which is the center of mass. 

Note these kinds of caiman usage questions are better suited for [GitHub Discussions](https://github.com/flatironinstitute/CaImAn/discussions). Issues are more for problems/bugs/feature requests.  People will be more likely to search/find answers to these types of questions there moving forward.
