### ISSUE TITLE
Ways to improve nb_correlation_pnr

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#1206]
`nb_correlation_pnr()` is pretty crucial for 1p analysis, but has a lot of ways it could be improved. It is unfortunate that it isn't nearly as intuitive to use as `correlation_pnr()`, the Matplotlib version. Potential improvements include:

- [x]   Histogram bin widths should change when you zoom, or make it easier to change number of bins on initialization.
- [x]   Make colormap a keyword arg.

EDIT Jan 2024: these are done in the CNMFE nb update PR should be in next release.

**Comment by EricThomson** [comment]
I'll check off the lower-hanging fruit as I do them for the CNMFE notebook update.

**Comment by kushalkolar** [comment]
Or build upon this as a starting point :smile: 

https://github.com/flatironinstitute/CaImAn/assets/9403332/b6930a1e-af26-4c76-b6a5-83e67a47914b

**Comment by EricThomson** [comment]
> Or build upon this as a starting point 😄
> <>

Eventually. But at least in the new cnmfe nb PR `nb_correlation_pnr()` is not completely inexplicable   😆

**Comment by EricThomson** [comment]
Main fixes are in #1207 (at least the ones I plan on making 😄 )
