### ISSUE TITLE
Volpy issue while running on HPC cluster - Tensor Flow and Qt platform plugin

### ISSUE THREAD

**Issue by carolinezphysics** [flatironinstitute/CaImAn#1209]
Please fill in the following for any issues

Your setup:
 **1. Operating System (Linux, MacOS, Windows):** 
 (caiman) -bash-4.2$ hostnamectl
   Static hostname: openmind7
         Icon name: computer
        Machine ID: ffe4afe3144f4db3a0788e94c4fc1292
           Boot ID: 9009b20a871543c5a8a2201bd1243baf
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1062.el7.x86_64
      Architecture: x86-64
 **3. Hardware type (x86, ARM..) and RAM:**
(caiman) -bash-4.2$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
Stepping:              7
CPU MHz:               1200.000
CPU max MHz:           2200.0000
CPU min MHz:           1200.0000
BogoMIPS:              4389.56
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts spec_ctrl intel_stibp flush_l1d

 4. Python Version (e.g. 3.9):
 (caiman) -bash-4.2$ python -V
Python 3.11.6
 6. Caiman version (e.g. 1.9.12):
 (caiman) -bash-4.2$ micromamba list caiman
List of packages in environment: "/home/carol410/micromamba/envs/caiman"

  Name    Version  Build            Channel    
─────────────────────────────────────────────────
  caiman  1.9.16   py311hb755f60_0  conda-forge
 8. Which demo exhibits the problem (if applicable):
 Both the demos/general/demo_pipeline_voltage_imaging.py and /demos/notebooks/demo_pipeline_voltage_imaging.ipynb
 10. How you installed Caiman (pure conda, conda + compile, colab, ..):
 conda and micromamba 
 12. Details: 
 See error attached - 1. tensor flow is complaining about CPU flags  2. qt platform is complaining, already tried x11, ssh tunneling etc. still does not fix the problem 

2023-10-23 21:49:13.706237: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU i\
nstructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler fla\
gs.
       27233 [utils.py:       download_demo():116][1385010] File demo_voltage_imaging.hdf5 already downloaded
       27234 [utils.py:       download_demo():116][1385010] File demo_voltage_imaging_ROIs.hdf5 already downloaded
       27234 [volparams.py:                 set():95][1385010] Changing key fnames in group data from None to /home/carol410/caiman_data/ex\
ample_movies/volpy/demo_voltage_imaging.hdf5
       27234 [volparams.py:                 set():95][1385010] Changing key fr in group data from None to 400
       27234 [volparams.py:                 set():95][1385010] Changing key max_shifts in group motion from (6, 6) to (5, 5)
       27234 [volparams.py:                 set():95][1385010] Changing key gSig_filt in group motion from None to (3, 3)
       27234 [volparams.py:                 set():95][1385010] Changing key strides in group motion from (96, 96) to (48, 48)
       27234 [volparams.py:                 set():95][1385010] Changing key overlaps in group motion from (32, 32) to (24, 24)
       28471 [movies.py:      extract_shifts():341][1385010] Movie average is negative. Removing 1st percentile.
       28471 [movies.py:      extract_shifts():359][1385010] Movie average is negative. Removing 1st percentile.
       28534 [movies.py:      extract_shifts():341][1385010] Movie average is negative. Removing 1st percentile.
       28534 [movies.py:      extract_shifts():359][1385010] Movie average is negative. Removing 1st percentile.
       28559 [movies.py:      extract_shifts():341][1385010] Movie average is negative. Removing 1st percentile.
       28560 [movies.py:      extract_shifts():359][1385010] Movie average is negative. Removing 1st percentile.
       28639 [motion_correction.py:motion_correction_piecewise():3176][1385010] Saving file as /home/carol410/caiman_data/example_movies/vo\
lpy/demo_voltage_imaging_rig__d1_100_d2_100_d3_1_order_F_frames_20000.mmap
       28640 [motion_correction.py:motion_correction_piecewise():3189][1385010] ** Starting parallel motion correction **
       33268 [motion_correction.py:motion_correction_piecewise():3197][1385010] ** Finished parallel motion correction **
       33333 [mmapping.py:    save_memmap_join():197][1385010] Memmap file for fname_tot: /home/carol410/caiman_data/example_movies/volpy/m\
emmap_demo_voltage_imaging_d1_100_d2_100_d3_1_order_C_frames_20000.mmap
       37094 [mmapping.py:    save_memmap_join():224][1385010] Deleting big mov
       38781 [cluster.py:         stop_server():343][1385010] stop_cluster(): done
       41213 [volparams.py:                 set():95][1385010] Changing key fnames in group data from /home/carol410/caiman_data/example_mo\
vies/volpy/demo_voltage_imaging.hdf5 to /home/carol410/caiman_data/example_movies/volpy/memmap_demo_voltage_imaging_d1_100_d2_100_d3_1_orde\
r_C_frames_20000.mmap
       41220 [volparams.py:                 set():95][1385010] Changing key ROIs in group data from None to [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
       41220 [volparams.py:                 set():95][1385010] Changing key index in group data from None to [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,\
 10, 11, 12, 13, 14]
       44033 [spikepursuit.py:     adaptive_thresh():604][1404017] Few spikes were detected. Adjusting threshold to take 10 largest spikes
       44229 [spikepursuit.py:     adaptive_thresh():607][1404040] Selecting top 100 spikes for template
       44440 [spikepursuit.py:     adaptive_thresh():604][1404039] Few spikes were detected. Adjusting threshold to take 10 largest spikes
       44470 [spikepursuit.py:     adaptive_thresh():607][1404030] Selecting top 100 spikes for template
       44492 [spikepursuit.py:     adaptive_thresh():607][1404028] Selecting top 100 spikes for template
       44688 [spikepursuit.py:     adaptive_thresh():607][1404032] Selecting top 100 spikes for template
       45187 [spikepursuit.py:     adaptive_thresh():607][1404024] Selecting top 100 spikes for template
       45495 [spikepursuit.py:     adaptive_thresh():607][1404040] Selecting top 100 spikes for template
Now processing cell number 1
Now processing cell number 4
       46034 [spikepursuit.py:     adaptive_thresh():604][1404017] Few spikes were detected. Adjusting threshold to take 10 largest spikes
       46115 [spikepursuit.py:     adaptive_thresh():607][1404040] Selecting top 100 spikes for template
       46310 [spikepursuit.py:     adaptive_thresh():607][1404030] Selecting top 100 spikes for template
       46348 [spikepursuit.py:     adaptive_thresh():607][1404029] Selecting top 100 spikes for template
       46435 [spikepursuit.py:     adaptive_thresh():607][1404028] Selecting top 100 spikes for template
Now processing cell number 14
       46672 [spikepursuit.py:     adaptive_thresh():604][1404017] Few spikes were detected. Adjusting threshold to take 10 largest spikes
Now processing cell number 0
       46906 [spikepursuit.py:     adaptive_thresh():607][1404032] Selecting top 100 spikes for template
Now processing cell number 11
Now processing cell number 2
       47115 [spikepursuit.py:     adaptive_thresh():604][1404039] Few spikes were detected. Adjusting threshold to take 10 largest spikes
       47160 [spikepursuit.py:     adaptive_thresh():607][1404030] Selecting top 100 spikes for template
       47197 [spikepursuit.py:     adaptive_thresh():607][1404029] Selecting top 100 spikes for template
       47281 [spikepursuit.py:     adaptive_thresh():607][1404028] Selecting top 100 spikes for template
Now processing cell number 6
Now processing cell number 7
Now processing cell number 13
       47622 [spikepursuit.py:     adaptive_thresh():607][1404024] Selecting top 100 spikes for template
Now processing cell number 8
       47782 [spikepursuit.py:     adaptive_thresh():607][1404032] Selecting top 100 spikes for template
Now processing cell number 10
Now processing cell number 12
       48374 [spikepursuit.py:     adaptive_thresh():607][1404024] Selecting top 100 spikes for template
Now processing cell number 9
Now processing cell number 3
Now processing cell number 5
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
/rdma/vast-rdma/vast-home/carol410/micromamba/envs/caiman/lib/python3.11/site-packages/caiman/source_extraction/volpy/utils.py:277: UserWar\
ning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
Component:0
^M  0%|          | 0/1 [00:00<?, ?it/s]^M100%|██████████| 1/1 [00:02<00:00,  2.82s/it]^M100%|██████████| 1/1 [00:02<00:00,  2.82s/it]
qt.qpa.xcb: could not connect to display localhost:11.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

/var/slurm/slurmd/job33258854/slurm_script: line 20: 1385010 Aborted                 (core dumped) python demo_pipeline_voltage_imaging.py

**Comment by pgunn** [comment]
Hello,
That CLI demo needs working X11 to display the results. It can be modified to not display the images by changing instances of display_images to False, which probably will let it run cleanly without X11, but by default it (and some other demos) assumes X11.

**Comment by carolinezphysics** [comment]
Hello,


Thanks for your message.

I did include in my comment that I tried x11 but it doesn't fix the
problem.

Additionally there is an issue with tensor flow. Please see detailed error
in the original post.

Best
Caroline

**Comment by pgunn** [comment]
Hello,
The messages from tensorflow are harmless.

I have never tried running that demo without X11; I will try doing so tomorrow when I'm in the office and will see if I can reproduce the issue.

Cheers,
Pat

**Comment by carolinezphysics** [comment]
Thank you for letting me know the tensor flow error is harmless. 

The jupyter notebook qt can be fixed when I add -x11 while already forwarding out screen with ssh tunneling...srun -t 02:00:00 --mem=10G --constraint=centos7 --x11 --pty bash

However for the demo.py file I tried a variety of ways to include x11 in my bash script while submitting jobs to the cluster, it still cannot fix the qt problem. Here is a latest version of my .sh script, do you have a version of job submission script that can make x11 works with caiman while running demo.py on cluster?
#!/bin/bash                                                                                                                                 
#SBATCH -t 08:00:00                                                                                                                         
#SBATCH -N 1                                                                                                                                
#SBATCH -n 30                                                                                                                               
#SBATCH --mem 200G                                                                                                                          
#SBATCH --gres=gpu:1                                                                                                                        
# Set the output file for Slurm job log -o /nese/mit/group/boydenlab/carol410/                                                              
#SBATCH -o ./testvol.out                                                                                                                    

source ~/.bashrc
# Activate your Conda base environment                                                                                                      
conda activate base

# Activate your CAIMAN environment within the Conda base environment                                                                        
micromamba activate caiman

export DISPLAY=:0
# Enable SSH X11 forwarding                                                                                                                 
export DISPLAY=:0
XAUTHORITY=$(mktemp)
xauth list | awk '{print "add " $0}' | xauth -f $XAUTHORITY nmerge -
# Specify the IP address for Jupyter Lab to listen on (0.0.0.0 allows all incoming connections)                                             
python demo_pipeline_voltage_imaging.py
Thank you!
<img width="1145" alt="Screenshot 2023-10-24 at 4 59 46 AM" src="https://github.com/flatironinstitute/CaImAn/assets/26918486/f86e5abc-7454-493d-b832-b92216f661de">

**Comment by carolinezphysics** [comment]
I am not sure why the script auto-format the .sh script, but here is a screenshot 

<img width="896" alt="Screenshot 2023-10-24 at 5 12 32 AM" src="https://github.com/flatironinstitute/CaImAn/assets/26918486/bc858743-08c9-49fd-a494-3756110f61a5">

**Comment by pgunn** [comment]
Hello,
I just tried running this on our system, with X11 disabled and with display_images set to False and it worked fine.

One thing to look out for - there are two instances of display_images to adjust, not just one. Can you carefully go through and make sure you've set both to false? If you do so, it should work fine without X11.

(I suggest removing the xauth and DISPLAY from your sbatch script as well)

**Comment by EricThomson** [comment]
Closing inactive: please reopen if needed.
