### ISSUE TITLE
movie save scales each frame: this introduces artifacts 

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#1222]
In `movies.py` when save is turned on, the following line is used to scale to the full dynamic range before saving (also converts to uint8):

`frame = np.minimum((frame * 255.), 255).astype('u1')`

This works great when you are viewing tons of components. But when saving a movie of a single component it introduces really bad artifacts, and ends up looking nothing like what you view in your notebook. If you want the movie to "save how it looks" when you viewed it in your notebook, you can instead just use:

`frame = frame.astype('u1')`

It works pretty well. I'm not sure if this is something we should "fix". I lean toward yes, because when people save they likely want it to save what they saw (this seems the reasonable expectation). 

Perhaps we could add it silently, or perhaps we could add a keyword toggle for scaling each frame or something for those that want to preserve the old behavior (which is reasonable in many standard contexts). There is no obvious elegant solution, I'm open to suggestions. This movie object is already a giant patchwork of toggles, but it's really useful object.

**Comment by pgunn** [comment]
Both routes seem reasonable (with some default and an override); we probably don't want to assume that everyone is using Caiman through a notebook interactively, although that's a very common usecase and your reasoning is solid.

**Comment by EricThomson** [comment]
Good point and I should have been more clear -- this will be an issue for anyone viewing the movie using opencv. Basically if you use `movie.play()` with the default  back end (`opencv`) and tweak things until you like what you see, and then save, then what you save won't match what you see.

**Comment by pgunn** [comment]
I think you can use your judgement here and nobody will object.

**Comment by EricThomson** [comment]
Fixed in #1207
