### ISSUE TITLE
scipy.sparse.csc` namespace is deprecated.

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#1235]
Hauling this over from a discussion thread. 

Something to do soon: turn off all the warnings and fix them. 

This would be a great first issue for anyone that is interested in contributing to Caiman. :smile:

### Discussed in https://github.com/flatironinstitute/CaImAn/discussions/1232

<div type='discussions-op-text'>

<sup>Originally posted by **AB0913** November 17, 2023</sup>
Hi everyone! I am attempting to run the demo script for multisession registration, but ran into this error:

DeprecationWarning: Please use `csc_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csc` namespace is deprecated.
  data = pickle.load(infile)

I am still fairly new to Python, so I wasn't sure how I should update to prevent to not rely on this deprecated function? 

Thank you!!</div>

**Comment by pgunn** [comment]
First version of scipy with this namespace change is 1.7.2 (I think) and we already require >1.10.1 so there's no need to change pins.

**Comment by pgunn** [comment]
Ah, this is unfortunate. The only instance of scipy.sparse.csc.csc_matrix in the code is in the comparison test (and this is not that - we should fix it anyway though).

I think we need to update alignment.pickle on our infrastructure to have a different class name for some of its internals so when it gets unpickled it doesn't go through the codepath that issues the deprecation warning.

**Comment by pgunn** [comment]
(removed "good first issue" because it's actually not something anyone external could fix)

**Comment by pgunn** [comment]
It looks like it's actually not fixable! I tried copying the csc_matrix to a new object and it had the same deprecated type, and I then tried making a new empty csc_matrix and it has the deprecated type.

```
>>> empty_csc = scipy.sparse.csc_matrix([0,0])
>>> type(empty_csc)
<class 'scipy.sparse._csc.csc_matrix'>
```

I'll write to them, but I suspect this is just a deprecation warning we'll have to deal with so long as we ever pickle/unpickle these things unless they change things upstream.

**Comment by pgunn** [comment]
https://github.com/scipy/scipy/issues/19566

**Comment by pgunn** [comment]
Looks like it's fixable after all. I'm uploading a fixed picklefile now.

**Comment by pgunn** [comment]
Fixed by uploading a new alignment.pickle after converting it
