### ISSUE TITLE
Tiff File Dimension Error - Volpy Demo

### ISSUE THREAD

**Issue by SRoche14** [flatironinstitute/CaImAn#1245]
Please fill in the following for any issues

Your setup:
 Operating System (Linux, MacOS, Windows): Linux, on HPC
 Python Version (e.g. 3.9): Python 2.7.5
 Caiman version (e.g. 1.9.12): Volpy demo
 Which demo exhibits the problem (if applicable): demo_pipeline_voltage_imaging_arg.py (attached, modification of volpy demo)

 Details: I am working with tiff files of shape (256, 640). I have tried passing in two files at a time into fnames, and I have also tried passing in a single tiff stack of size (5, 256, 640). However, the demo script does not appear to accept the dimensions of the tiff files. What is the right way to pass in tiff files into the volpy demo script? I have included the source demo file and the log output.

[demo_log_output.pdf](https://github.com/flatironinstitute/CaImAn/files/13783056/demo_log_output.pdf)
 
[demo_pipeline_voltage_imaging_arg.pdf](https://github.com/flatironinstitute/CaImAn/files/13782999/demo_pipeline_voltage_imaging_arg.pdf)

**Comment by EricThomson** [comment]
Thanks for the question: I'm on holiday right now, not sure if @caichangjia is too, but he might be able to answer this better than I.

**Comment by SRoche14** [comment]
Thank you! I will wait until someone is available to help. I appreciate you taking you time from your holiday to respond.

**Comment by caichangjia** [comment]
Hi Steven can you try to stitch these tiff files together to be a large tiff file (let's say 3000x256x640) and then pass into VolPy?

**Comment by SRoche14** [comment]
Yes, that worked!
