### ISSUE TITLE
Using view_quilt to define parameters

### ISSUE THREAD

**Issue by JohnStout** [flatironinstitute/CaImAn#1265]
Your setup:
 1. Operating System (Linux, **MacOS**, Windows):
 2. Hardware type (x86, **ARM**..) and RAM:
 3. Python Version (e.g. **3.11**):
 4. Caiman version (e.g. **1.9.16**):
 5. Notebook: cnmfe_pipeline demo
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): conda+mamba
 7. Details: 

Currently there is some ambiguity in terminology with stride and overlap. In the description, it is mentioned that stride should have been called overlap, but there is an `overlaps` parameter for motion correction (which I am currently defining as the strides/2). It is unclear how this overlaps variable is different from the `cnmfe_patch_stride` variable. Likewise, it is not clear on the difference between the `overlaps` parameter for mc and the `cnmfe_path_overlap`.

I've been using `rf` to define `stride` (rf/2), but I don't actually use any of the `cnmfe_patch...` parameters used by the `view_quilt` section because it remains unclear how they are related.

Could you possibly modify the tutorial to provide one place where we define `strides` and `overlaps` that draws more clearly from the the `view_quilt` function? Ideally, we could modify a single variable or two and those modifications (confirmed with visualization) would be used to define the result of our parameters (motion correction and CNMFE). It is probably also the case that I am missing something.

Thank you so much!
John

**Comment by EricThomson** [comment]
Hi John thanks for the question. It's unfortunate and confusing that the naming isn't consistent between motion correction and cnmf.  I'm a little unclear what you are asking for here. Let me back up and define things generally, and then for the two estimators. There are three possible patch parameters: patch width, patch stride, and patch overlap.  

They are related by `width = stride + overlap`. You can see in the following image. 

![patch_params](https://github.com/flatironinstitute/CaImAn/assets/6643322/158f7108-1a33-44d8-8149-64842924d5bc)

The `view_quilt()` uses stride and overlap as parameters, and superimposes the pattern on summary images (like you see above). As you know, in general you won't use the same patch params for motion correction as you will for cnmf (they have very different goals computationally).

To make things confusing, we use different terminology for motion correction and cnmf patches. For motion correction, stride and overlap are called `strides` and `overlaps` (no problem).  For cnmf, the patch width is defined indirectly by `rf` (actual patch width is `2rf+1`). `rf` stands for "receptive field" (why? who knows). overlap is defined by the `stride` parameter (which makes no sense but here we are, and the overlap is actually `stride+1`). 

I tried to clarify this stuff in the notebook, and use the quilt viewer to view the values (deriving the needed quantities from the cnmf params for the quilt function). We should probably just rename `stride` to `cnmf_overlap` or something like that.  The main reason we hold back is backward compatibility -- to avoid breaking people's code -- but `stride` is a misleading name at best and we should probably just stop this madness.

I hope that is all clear. Now, given all the above: I'm not sure what your request is exactly?

**Comment by JohnStout** [comment]
I'll backup and say that I'm trying to create a notebook that allows lab members to sort of plug and play without going into the parameter space (unless of course, they need to because this notebook doesn't work for them). So I've incorporated mesmerize-core/fastplotlib plots and your view_quilt function to interactively define some of the important parameters. I like the caiman notebooks because the parameter space is right in your face, but I like mescore because the interactive plots help to define the parameters. As such, I've been combining these things (link right below this paragraph)

https://github.com/JohnStout/decode_lab_code/blob/main/notebooks/projects/CNMFE.ipynb

This is a rather messy notebook showing what I'm doing. I'm trying to define `rf` one time and then use `strides` for both motion correction and CNMFE. So in this notebook, the user will define their `movie_path` and `fr` (frame rate), then define `rf` with view_quilt, then define `gSig`with an interactive plot, and `min_corr`/`min_pnr` with interactive plots. The result is a CNMFE.hdf5 file that can be loaded into a separate notebook for visualization of results and movies (all thanks to your incredible notebooks!!).

Essentially, I'm wondering if what I have done in this notebook is fair and was wondering if we could have something like this where we change a variable or two, see the impact of strides/overlap etc.. via view_quilt, then strides and overlaps get automatically assigned to the motion correction and CNMFE cells through variable naming (see image below).

<img width="341" alt="Screenshot 2024-02-02 at 3 13 02 PM" src="https://github.com/flatironinstitute/CaImAn/assets/46092030/6adc56a8-03a7-4c7f-aa86-e6c040ae76b6">

**Comment by JohnStout** [comment]
That makes sense! I will look that over! Thanks as always!

**Comment by EricThomson** [comment]
Closing as addressed, but feel free to reopen issue or Discussion if more help on this is needed.
