### ISSUE TITLE
Installation Step is Hanging

### ISSUE THREAD

**Issue by CorbanSwain** [flatironinstitute/CaImAn#1268]
Your setup:
 1. Operating System (Linux, MacOS, Windows): Windows
 2. Hardware type (x86, ARM..) and RAM: Intel Xeon Gold 5218 CPU, 512 GB RAM
 3. Python Version (e.g. 3.9): 3.10
 4. Caiman version (e.g. 1.9.12): 1.10.2
 5. Which demo exhibits the problem (if applicable): N/A installation
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): **conda + compile** (I think?) ... also using mambaforge ... Following instructions at: [CaImAn installation instructions](https://flatironinstitute.github.io/CaImAn/Installation.html)
 7. Details: I'm attempting to perform the install; however there seems to be an issue at the `pip install .` step.  The script is hanging at this step
```
(caiman) I:\CorbanSwain\repos\CaImAn>C:\Users\CorbanSwain\mambaforge\envs\caiman\python.exe -m pip install --verbose .
...
Running command Building wheel for caiman (pyproject.toml)
...
"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\CorbanSwain\mambaforge\envs\caiman\libs /LIBPATH:C:\Users\CorbanSwain\mambaforge\envs\caiman /LIBPATH:C:\Users\CorbanSwain\mambaforge\envs\caiman\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\um\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\um\x64" /EXPORT:PyInit_oasis build\temp.win-amd64-cpython-310\Release\caiman/source_extraction/cnmf/oasis.obj /OUT:build\lib.win-amd64-cpython-310\caiman\source_extraction\cnmf\oasis.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-310\Release\caiman/source_extraction/cnmf\oasis.cp310-win_amd64.lib
     Creating library build\temp.win-amd64-cpython-310\Release\caiman/source_extraction/cnmf\oasis.cp310-win_amd64.lib and object build\temp.win-amd64-cpython-310\Release\caiman/source_extraction/cnmf\oasis.cp310-win_amd64.exp
  Generating code
```

Is this a known issue? Any, recommendations for debugging this?

**Comment by pgunn** [comment]
Hello,

Are you sure you need to build your own caiman? It's often unnecessary and it's particularly rough on Windows; you have the alternative of not using the sources and instead installing the binary packages of caiman.

To do this, I suggest removing your caiman environment, removing your download of the sources, and then making a fresh one that uses the caiman prebuilt packages:

`mamba create -n caiman -c conda-forge caiman`

If you're really sure you need to build your own caiman we can try to help, but it's far simpler to go down this route (and you will not need to ever get the caiman sources this way).

**Comment by EricThomson** [comment]
Seconding what Pat wrote -- unless you are planning to do a developer install I would recommend just following the quickstart guide at the readme.  

Also if you *do* want do do a dev install (which is not what I would recommend for new users), that link you posted is to a really old set of instructions. The most recent updated instructions are here: https://caiman.readthedocs.io/en/latest/Installation.html

**Comment by CorbanSwain** [comment]
Thank you so much! Yes I realized that I was following the wrong instructions at some point. (After I posted this issue 🤦🏿‍♂️) Thank you.

I was able to get the baseline instructions from the main `README.md` file working with the exception of the following (let me know and I can make a new issue).

```
> mamba create -n caiman -c conda-forge -c anaconda "caiman=1.10"
```
* I had to specify anaconda as a channel because I was getting this error otherwise (for some reason it could not find tf >=2.4 on conda-forge).
  ```
  >mamba create -n caiman -c conda-forge "caiman=1.10"

  Looking for: ['caiman=1.10']

  warning  libmamba Cache file 
  "C:\\Users\\CorbanSwain\\mambaforge\\pkgs\\cache\\5afe41e9.json" was 
  modified by another program
  warning  libmamba Cache file 
  "C:\\Users\\CorbanSwain\\mambaforge\\pkgs\\cache\\09cdf8bf.json" was 
  modified by another program
  conda-forge/win-64                                  20.7MB @  14.1MB/s 1.5s
  conda-forge/noarch                                  13.5MB @   3.8MB/s 3.6s
  Could not solve for environment specs
  The following package could not be installed
  └─ caiman 1.10**  is not installable because it requires
     └─ tensorflow >=2.4.0 , which does not exist (perhaps a missing channel).
  ```
* I had to specify caiman version =1.10 otherwise it would default to an older version (1.7 maybe, this might be connected to the tf issue).

**Comment by pgunn** [comment]
Hi,
I forgot that that's necessary on Windows; you did the right thing. Glad things are working for you now.
