### ISSUE TITLE
None type output from estimates.coordinates when running CNMF-E

### ISSUE THREAD

**Issue by JohnStout** [flatironinstitute/CaImAn#1269]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, **MacOS**, Windows):
 2. Hardware type (x86, **ARM**..) and RAM: **16gb**
 3. Python Version (e.g. 3.9): **3.11.7**
 4. Caiman version (e.g. 1.9.12): **1.9.16**
 5. Which demo exhibits the problem (if applicable): **demo_pipeline_cnmfE along with my own code**
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): **instructions on the installation page**
 7. Details: 

When running the CNMFE algorithm as demonstrated in the demo_pipeline_cnmfE, the `.estimates.coordinates` is of type None (see attached image below!). This shouldn't be related to the get_contours function because I can use it to create the contours (based on the utils.visualization code):

      # import
      from caiman.utils.visualization import get_contours

      # get shape of spatial correlation output
      d1, d2 = np.shape(corr)

      # get contours
      coors = get_contours(cnmfe_model.estimates.A, (d1, d2), thr=0.99)

      # extract an example for plotting purposes
      roi = coors[0].get('coordinates')
      CoM = coors[0].get('CoM')
      
      # plot data
      plt.imshow(corr)
      plt.plot(roi.T[0,:],roi.T[1,:],c='r',linewidth=2)
      plt.text(CoM[1], CoM[0], str(0 + 1), color='w', fontsize=10)

Figure from `get_contours` function:
<img width="422" alt="Screenshot 2024-02-08 at 12 21 47 PM" src="https://github.com/flatironinstitute/CaImAn/assets/46092030/447e98e0-1c66-4d90-9005-96558d7a83dd">

Is this (`.estimates.coordinates` leading to a type None output) related to an updated caiman version, some parameter that I can set, or some combination with the Arm software? I was using .estimates.coordinates in an older version of caiman for what it is worth.

Thanks!
John

<img width="348" alt="Screenshot 2024-02-08 at 11 49 01 AM" src="https://github.com/flatironinstitute/CaImAn/assets/46092030/3f8afc82-f247-40b7-aa0e-6686ceff6439">

**Comment by EricThomson** [comment]
iirc coordinates isn't populated automatically and this is by design as it is considered more for plotting purposes: it becomes populated with functions like `plot_contours_nb()`. For instance, if you see `plot_contours_nb()` it checks to see if coordinates is `None` and if it is, it calls `get_contours()` so as to populate that field. 

Good question though, and this is related to #1088 .

**Comment by JohnStout** [comment]
Thanks Eric!
