### ISSUE TITLE
Post "evalute_components_CNN" matrix size error

### ISSUE THREAD

**Issue by catubc** [flatironinstitute/CaImAn#128]
Re: demo_OnACID.py

There is a matrix size error post-processing where I'm trying to save the **YrA** variable by subtracting original **C** matrix from **noisyC**. I think it's a simple fix to re-slice the **C** matrix to exclude the cells removed by CNN classifier.

(Note: This issue is similar to expected_comps fixed matrix size which crashes if the expected_comps is too small relative to # of neurons post-analysis).

*******************************Output***********************

Number of components:179
... using CNN classifier ...
Using TensorFlow backend.
2017-12-01 11:39:14.746002: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
Loaded model from disk
179/179 [==============================] - 0s 787us/step

...saving .npz file containing all processed data:  /media/cat/4TB/in_vivo/rafa/alejandro/G2M5/20170511/000/Registered_500frames_processed.npz
Traceback (most recent call last):
  File "/home/cat/code/CaImAn/demo_OnACID_2.py", line 129, in <module>
    np.savez(fname[:-4]+"_processed.npz", C=C, A=A, Y_=Y_,Yr=Yr, b=cnm.b, f=cnm.f, **YrA=cnm.noisyC[cnm.gnb:cnm.M] - C**, Cn=Cn)
ValueError: operands could not be broadcast together with shapes (179,500) (161,500)

**Comment by epnev** [comment]
For the OnACID algorithm `C` is only used during initialization. What is tracked during the online phase is `C_on` which should have the same dimensionality. That's poor variable selection on our side but we'll change it at some point.
