### ISSUE TITLE
`scipy` does not have a `histogram` method with this signature.

### ISSUE THREAD

**Issue by CorbanSwain** [flatironinstitute/CaImAn#1281]
My running of following pseudo code:
```python3
cnm2.estimates.detrend_df_f(quantileMin=8, 
                            frames_window=250,
                            use_residuals=False)
```

was failing with the following error:
```
AttributeError: Module 'scipy' has no attribute 'histogram'
```

https://github.com/flatironinstitute/CaImAn/blob/c873b036135a4c2f441c78449d42eb887d356b7e/caiman/utils/stats.py#L236

I believe this line should instead read: 
```python3
DataHist, bins = np.histogram(data, bins=N, range=(MIN, MAX))
```

Please let me know if I'm missing something.

**Comment by pgunn** [comment]
Hello, I think that's just old code; at some point it looks like they moved it to scipy.stats.histogram() and we didn't catch all the references in the code. We'll fix this with the next release.

**Comment by pgunn** [comment]
Ah, apparently they have since removed that replacement. Anyhow, we'll figure out the right successor to this function with the next release.

**Comment by CorbanSwain** [comment]
thanks!

**Comment by pgunn** [comment]
There will be some technical noise as I leave notes on looking into this. Sorry for the notifications you'll get.

It looks like scipy 1.11.3 has scipy.histogram(), which exposes the implementation of scipy.stats._stats_py._histogram()
scipy 1.12 does not expose this, but this may be due to a bug; it's not listed in their release notes in the breaking changes section.

I'm filing a bug against scipy; I might pin scipy if we do another release before we hear back from them. 

https://github.com/scipy/scipy/issues/20113

**Comment by CorbanSwain** [comment]
After further inspection, it seems like `caiman/utils/stats.py` is chocked full of scipy references that seems a bit off: `.pi` `.sqrt` `.sum` `.log2` ... all which are in `numpy` but not `scipy` to my knowledge.

Was a "find-replace" performed by mistake at some point?

**Comment by pgunn** [comment]
No ; scipy used to import a lot of numpy internals and re-expose them under the scipy namespace. I think they've been deprecating (and eventually removing) such things, so maybe we have a few more adjustments ahead.

**Comment by CorbanSwain** [comment]
Oh ok I see. 

I just replaced all of the `scipy` attributes in `/caiman/utils/stats.py` with `numpy` (`np`) except for `scipy.optimize.brentq` and `scipy.sparse.csc_matrix` and the code is now running through.

**Comment by pgunn** [comment]
Yup, that's what I'm doing with the diff. Once it goes green with our CI, this will be fixed in dev.

**Comment by pgunn** [comment]
This is now fixed in dev; we'll have to cut a new release soon to get this out there to avoid the new scipy release leading to broken package-based installs.
