### ISSUE TITLE
Evaluate_components cannot reshape array

### ISSUE THREAD

**Issue by warnerwarner** [flatironinstitute/CaImAn#1284]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Linux
 2. Hardware type (x86, ARM..) and RAM: x86, 64GB Ram
 3. Python Version (e.g. 3.9): 3.10.13
 4. Caiman version (e.g. 1.9.12): 1.10.2
 5. Which demo exhibits the problem (if applicable): None
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): conda + compile (developer)
 7. Details: 

Hi, I'm currently trying to apply CNMF to a small dataset, which I have not saved in the memmap format. My data is of size 100 x 100 x 100000 in its original format. I run the CNMF fitting using the following loosely the procedure in the demo_pipeline notebook. However, when I try and evaluate the components I get a ValueError. My code is as follows:

`import caiman.source_extraction.cnmf as cnmf
import caiman as cm
import numpy as np

cnmf_inst = cnmf.CNMF(10, k=5, merge_thresh=0.8, gSig=[7, 7])
cnmf_inst.fit(vid) #vid size is 100000 x 100 x100

cnmf_refit = cnmf_inst.refit(vid)

cnmf_refit.estimates.evaluate_components(vid, cnmf_refit.params)`

And my error is

`ValueError: cannot reshape array of size 805600 into shape (800,125,8)`

Thanks for any help!

**Comment by EricThomson** [comment]
Memory mapping is required: e.g., see #1272 . In the demo notebook we discuss how to memory map a file that doesn't need to be motion corrected so you can carry on with the rest of the analysis steps.
