### ISSUE TITLE
Trouble with detrend_df_f using non-CaImAn generated data.

### ISSUE THREAD

**Issue by GrowlingM1ke** [flatironinstitute/CaImAn#1285]
Hello,

Our team has been using https://github.com/denisecailab/minian/tree/master, for cell transients extraction and to my understanding shares a lot of similarity in terms of implementation with CaImAn. I'm trying to take our output and extract dff values using the detrend_df_f function but I ran into some issues. I've taken our A, C, b and f data, iterated per cell and converted to numpy before passing it into detrend_df_f, however at this line:
`
C = nA_mat * C
`
I get the following error:
`
File "c:\ProgramData\miniconda\envs\minian_updated\lib\site-packages\scipy\sparse\_base.py", line 590, in __mul__    
    return self._mul_dispatch(other)
  File "c:\ProgramData\miniconda\envs\minian_updated\lib\site-packages\scipy\sparse\_base.py", line 559, in _mul_dispatch
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
`
Which leads me to believe that there might be some discrepancy between the shape of my variables and what CaImAn uses.

For clarity here is the relevant code I've written:

```
dff_array = np.zeros(self.data['C'].shape)
# load in the necessary data
C = self.data['C'].values
A = self.data['A'].values
f = self.data['f'].values
b = self.data['b'].values
for i in range(len(C)):
    dff_array[i] = detrend_df_f(A[i], b, C[i], f)
```

and here is the corresponding shape of each of those variables being passed in:

```
A[i].shape (608, 608)
b.shape (608, 608)
C[i].shape (27000,)
f.shape (27000,)
```

Thank you in advance!

Edit 1: Looking at the notebook examples, it is possible that there may be more discrepancies than I initially realized. "A" seems to be a boolean array in CaImAn, whilst our output is a float64 type between 0.0 and 1.0. Same thing goes for the other variables we generated, they are also a float64 value but as opposed to A they are not constrained between 0 and 1 and can be larger. I'm not unfortunately too familiar enough with the implementation of detrend_df_f to know if that will be a significant issue.

**Comment by GrowlingM1ke** [comment]
Looking through the codebase I found some relevant info: https://github.com/flatironinstitute/CaImAn/blob/c873b036135a4c2f441c78449d42eb887d356b7e/caiman/source_extraction/cnmf/estimates.py#L24

```
            A:  scipy.sparse.csc_matrix (dimensions: # of pixels x # components)
                set of spatial footprints. Each footprint is represented in a column of A, flattened with order = 'F'

            C:  np.ndarray (dimensions: # of components x # of timesteps)
                set of temporal traces (each row of C corresponds to a trace)

            f:  np.ndarray (dimensions: # of background components x # of timesteps)
                set of temporal background components

            b:  np.ndarray or scipy.sparse.csc_matrix (dimensions: # of pixels x # of background components)
                set of spatial background components, flattened with order = 'F'
```

Has given me a bit of an idea, how I can change my data. I shouldn't be looping through my different values but rather I should collapse the image dimensions into a single one. I'm not quite sure how to interpret having different background components but I think in my case I could cheat and reshape b to be treated as 1 background component. I'm still a bit wary about potential compatibility so I'd happily take feedback from anyone who has more in depth knowledge of the implementation of detrend_df_f.

**Comment by GrowlingM1ke** [comment]
Thank you!

I'll take a crack today at the demo notebook and see if I can figure out how to wrangle the output of minian to fit with detrend_df_f(). Successful or not I'll post another comment here with an update for the 5-10 people in the world who still use minian.

**Comment by EricThomson** [comment]
minian is a great tool with many users: if you get this bridge between the packages working it would be useful to describe how for the communities!

**Comment by GrowlingM1ke** [comment]
Success! I've managed to convert the data and run detrend_df_f() without a hitch. I still need to check and visualize the results just to be sure I got the correct output. Thank you @EricThomson for your suggestion. I'm posting my conversion function below:

```
def minian_to_caiman(A, b, C, f, Yra) -> tuple:
        """
        Convert the minian data to caiman format

        Parameters
        ----------
        A : xr.DataArray
            Spatial footprints.
        b : xr.DataArray
            Background footprint.
        C : xr.DataArray
            Temporal Calcium Signal.
        f : xr.DataArray
            Temporal Fluorescence Signal.
        Yra : xr.DataArray
            Residuals.
        """
        # Minian data is in the format (unit_id, height, width) -> (height x width, unit_id) for caiman
        A = A.values
        A = np.reshape(A, (A.shape[0], -1), order="F").T
        A = scipy.sparse.csc_matrix(A) # Needs to be converted to csc_matrix for caiman

        C = C.values # Needs no change (unit_id, time) is the same in both

        # Minian data has one estimate of the background, whilst caiman can have several. To make it compatible, we
        # add a new axis to the background and make it the last axis, so the conversion is (height, width) -> (height x width, 1)
        b = b.values
        b = np.expand_dims(b.flatten(order="F"), axis=1)

        # With the aforementioned change, we just need to insert a new axis at the beginning
        f = f.values
        f = np.expand_dims(f, axis=0)

        Yra = Yra.values # Needs no change

        return A, b, C, f, Yra
```
I'll double check tomorrow the visualized results.

**Comment by EricThomson** [comment]
Nice that's great! 💯 

I'd double check that minian forces (our) `gnb` -- number of background components --  to be 1. Are you sure that `1` isn't just their default that can be tweaked?  Note I've never used minian in a serious way (I have used their demo notebook a couple of times just to see how their algorithm works): maybe they do limit it to 1, but I would just double check, and try setting it to 2 if you can and see how your code generalizes if possible. (If I'm wrong then ignore this 😄 )

**Comment by GrowlingM1ke** [comment]
I've double checked update_background() https://github.com/denisecailab/minian/blob/f64c456ca027200e19cf40a80f0596106918fd09/minian/cnmf.py#L1937
and this is the relevant part of the function description:

```
Returns
    -------
    b_new : xr.DataArray
        New estimation of the spatial footprint of background. Has
        dimensions ("height", "width").
    f_new : xr.DataArray
        New estimation of the temporal activity of background. Has dimension
        "frame".
    """
```
As a sidenote, I've liked everything I've seen so far from the little I've played around with CaImAn.

**Comment by EricThomson** [comment]
That’s great! 🚀 I looked through their code and think you are right: I couldn’t find a place to set number of bg components. Maybe I missed it because I’m not super familiar with their code.
