### ISSUE TITLE
Memory issue when running the cnmfe and estimates.F_dff

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1297]
Hello!

My computer C drive currently have 600G free space and 128 memory. But I have different memory error.

First, when I run cnmfe without downsampling the memory error says require 200-900 GB. But it used to work well without downsampling 
![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/188ce3c0-14f9-4678-b459-3e2a65c0f2ef)

Second, when I downsampling my tsub=2, things work fine. But when I run estimates.F_dff, it has another memory error:
![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/b2686007-b7d5-45f1-b6ad-803c9e429b00)
![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/ac4afdfa-d258-48f9-bd7c-472ab0eaf301)
![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/92e638d2-475e-4f4f-a51a-67fb82ab939c)
![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/8655a0bc-3a11-4a02-b305-c42f86b793cc)

Here are the steps I have tried from the similar question:
1) Enabling Swapping: after restart it seems doesn't work
![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/74eea6e8-ee70-45f4-a8cf-8c82683e0d35)

2) Adjust the n_process: Seems doesn't work either as I change from 10, 15 to none (24)

3) caimanmanager diagnose
![Screenshot 2024-03-12 114157](https://github.com/flatironinstitute/CaImAn/assets/48576330/e089b359-d06b-4e04-bfd2-9bcf23f5b132)

Thank you very much for your help!

**Comment by EricThomson** [comment]
Hi it looks like you are not using the most recent version of Caiman (`1.10.4`). Could you please update and try again?

**Comment by zhouyi0812** [comment]
may I ask how should I update if I am in the mescore environment?
Thank you!

**Comment by EricThomson** [comment]
Within your environment, `conda update caiman -c conda-forge`

**Comment by zhouyi0812** [comment]
Thank you!!
I updated with the code, but it still memory error
![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/ea2b3287-70eb-45bd-a906-a37dc617d34f)

**Comment by EricThomson** [comment]
Looks like you should probably downsample (as you originally tried), and if the results suffer then go to online algorithm.

**Comment by EricThomson** [comment]
I added more detailed discussion of handling memory in the demo notebook (#1300 ). It gives a bit more clear roadmap of what you should do, and I added a discussion of subsampling.
