### ISSUE TITLE
notebook demo_motion_correction.ipynb failing on mac with 'multiprocessing'

### ISSUE THREAD

**Issue by epnev** [flatironinstitute/CaImAn#130]
When using `backend = 'local'` on cell #4 on a mac, the demo hangs when attempts to correct the file. Things appear to be working fine when running the same code on a script through spyder, or with 
`backend = 'ipyparallel'`

They also appear to be working fine on linux.

**Comment by pgunn** [comment]
Appears to be an instance of:
https://github.com/numpy/numpy/issues/5752

The workaround mentioned here:
https://github.com/ContinuumIO/anaconda-issues/issues/133

works around it acceptably (VECLIB_MAXIMUM_THREADS=1)

**Comment by epnev** [comment]
Very nice, thanks!
