### ISSUE TITLE
'caimanmanerger' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1307]
Hello!

I am trying to reinstall the caiman, and when I do caimanmanager install, it shows an error like the title.

I tried to use other way to solve it from other issues. But still not working.

Thank you!

**Comment by pgunn** [comment]
Hello,
Which install process are you using?

**Comment by zhouyi0812** [comment]
I am following the steps from the Caiman page.

**Comment by pgunn** [comment]
Hello,
The caiman page describes two separate ways to install; one uses just conda, another uses the source tree and pip.

If you have time, maybe we can use gitter to resolve this more quickly?

https://app.gitter.im/#/room/#agiovann_Constrained_NMF:gitter.im

**Comment by zhouyi0812** [comment]
I am following the conda one. 
I can join gitter now, thank you!

**Comment by pgunn** [comment]
(we wrapped this up on gitter)
