### ISSUE TITLE
Can't set up caiman in Ubuntu of wsl windows11

### ISSUE THREAD

**Issue by Shuai-NY** [flatironinstitute/CaImAn#1308]
Please fill in the following for any issues

Your setup:
 1. Operating System ( Windows wsl ubuntu):
 2. Hardware type (x86, ARM..) and RAM: RAM32.0 GB
 3. Python Version (e.g. 3.9): 3.11.8
 4. Caiman version (e.g. 1.9.12): latest (mesmerize)
 5. Which demo exhibits the problem (if applicable):
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): mamba 
 7. Details: 
Traceback (most recent call last):
  File "/home/shuai/miniforge3/envs/mescore/bin/caimanmanager", line 7, in <module>
    from caiman.caimanmanager import main
  File "/home/shuai/miniforge3/envs/mescore/lib/python3.11/site-packages/caiman/__init__.py", line 4, in <module>
    from caiman.base.movies import movie, load, load_movie_chain, _load_behavior, play_movie
  File "/home/shuai/miniforge3/envs/mescore/lib/python3.11/site-packages/caiman/base/movies.py", line 9, in <module>
    import cv2
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
(mescore) shuai@Shuai:~$

**Comment by Shuai-NY** [comment]
Thank you so much for your quick reply!

**Comment by pgunn** [comment]
Can you, inside the ubuntu environment, run the following command and send me the output?

`dpkg -l | grep libegl1`

(the dpkg commnand with that argument lists all debian packages installed on the system; we're looking for libegl1, which is an OpenGL library that it looks like OpenCV needs)

**Comment by Shuai-NY** [comment]
I got nothing output

**Comment by Shuai-NY** [comment]
Thank you so much! Appreciate it.
It was fixed!
Update the package index:
# sudo apt-get update
Install libegl1-mesa-dev deb package:
# sudo apt-get install libegl1-mesa-dev
######
caimanmanager install

**Comment by pgunn** [comment]
Happy that did the job.
