### ISSUE TITLE
If it's possible to install caiman on another drive

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1309]
Hello!

I wonder if it is possible to install Caiman in another drive where has more space?

Thank you!

**Comment by pgunn** [comment]
Hello,
Caiman takes up space in two places on the drive:
1) The conda environment where the software package lives
2) The caiman_data directory where you probably are doing your work

I think you're probably talking about #2 because the first is usually smaller than the datasets you'll be working with, but if you can confirm that we can talk about your options.

Cheers,
Pat

**Comment by zhouyi0812** [comment]
Thank you!
I think I would like to change the second place where the caiman_data at.

**Comment by pgunn** [comment]
Oh, sorry, I forgot to ask, what operating system are you on?

**Comment by zhouyi0812** [comment]
I am using windows

**Comment by zhouyi0812** [comment]
Thank you!

So for the first step: change the variable path, I wonder should I just do 'D:' at conda for changing path and then reinstall the manager? If so, I encounter the error as: 'caimanmanager' is not recognized as an internal or external command,
operable program or batch file.

Or I should change the path via system?

![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/45a389b6-dac7-490d-b5e8-8a7c60614429)

**Comment by pgunn** [comment]
Hello,
I don't recognise the GUI you're showing me there; it's probably better not to change anything there.

What I suggest is launching the conda version of the terminal (under your start menu), and follow the instructions there; activate the environment, set CAIMAN_DATA in the commandline, and then rerun `caimanmanager install`.

If you'd like, you can hop on gitter again later tonight and I can try to guide you through it; I'm heading out to dinner shortly but I'll be back on in a few hours.

**Comment by zhouyi0812** [comment]
Thank you!

Am I right on following instruction?

![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/19743767-ec54-4cbc-b4e7-edb3d9d125d1)

**Comment by pgunn** [comment]
That's very close; my instructions above were actually wrong.

It's CAIMAN_DATA, not CAIMAN_HOME.

Try doing exactly what you did there, but with

`SET CAIMAN_DATA=D:\caiman_data` instead.

**Comment by zhouyi0812** [comment]
Thank you! That succussed!

So I restart the conda and put the path and jupyter.
But it seems the jupyter still open the old caiman_data directory

![image](https://github.com/flatironinstitute/CaImAn/assets/48576330/6d305a92-0e72-4d33-b81b-94301de77cf7)

**Comment by pgunn** [comment]
Before you launch jupyter, cd to D:\caiman_data
