### ISSUE TITLE
Back to older version of Caiman

### ISSUE THREAD

**Issue by zhouyi0812** [flatironinstitute/CaImAn#1324]
Hello!
I wonder if it is possible to go back to an older version of caiman?
Thank you!

**Comment by pgunn** [comment]
Hello,
Yes, it is possible to easily install conda-packaged versions of caiman using any version you see here (look at other pages for a more exhaustive list):

https://anaconda.org/conda-forge/caiman/files

You can do so by adding an equals-version and the version you want during the environment build, e.g.

`conda create -n caiman -c conda-forge caiman=1.9.16`

(or whatever version you want).

Note that older versions are more likely to have bugs and problems.
