### ISSUE TITLE
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

### ISSUE THREAD

**Issue by xuesj** [flatironinstitute/CaImAn#133]
I install pytorch on my MacOS(MacOS High Sierra) using:
conda install pytorch torchvision -c soumith
then I import torch as following:
>>>import torch
but it display error as following:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c031d3dd82fc> in <module>()
----> 1 import torch

/usr/local/anaconda3.5/lib/python3.5/site-packages/torch/__init__.py in <module>()
     51 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)
     52 
---> 53 from torch._C import *
     54 
     55 __all__ += [name for name in dir(_C)

ImportError: numpy.core.multiarray failed to import

I did update my numpy as following:
conda uodate numpy

after then , it still display error as above when I import torch.

How to fix it?

**Comment by epnev** [comment]
This is not related to our package. Please consult elsewhere.
