### ISSUE TITLE
caiman manager install fails

### ISSUE THREAD

**Issue by smbaca** [flatironinstitute/CaImAn#1369]
1. Operating System (Linux, MacOS, Windows):
Mac OS Sonoma 14.5
 2. Hardware type (x86, ARM..) and RAM:
 ARM M3 
 4. Python Version (e.g. 3.9):
 3.11
 6. Caiman version (e.g. 1.9.12):
 Latest
 10. How you installed Caiman (pure conda, conda + compile, colab, ..):
 conda 
11. Details: 
trying to install caimanmanager fails and with either x86 or arm version of conda. I get the following error:

ImportError: cannot import name 'simps' from 'scipy.integrate' (/opt/anaconda3/envs/mescore/lib/python3.11/site-packages/scipy/integrate/__init__.py)

**Comment by smbaca** [comment]
https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#backwards-incompatible-changes

Looks like they got rid of simps in the latest version...

**Comment by pgunn** [comment]
I'll file an issue with peakutils; in the meantime we may need to pin scipy in the next release.

**Comment by pgunn** [comment]
Actually, looks like there's already an issue filed - https://bitbucket.org/lucashnegri/peakutils/issues/117/not-compatible-with-scipy-114 

Looks like peakutils 1.3.5 has the fix (cut 3 days ago) but they haven't yet finished the whole release. If this isn't fixed early next week I'll cut a minor release to add max-version pins (although maybe min-version-pins are the right thing to do after the peakutils maintainers finish).

**Comment by pgunn** [comment]
peakutils 1.3.5 is out; new installs should not run into this issue. I'll add a minimum version pin and then close the issue.

**Comment by pgunn** [comment]
This is now loosely fixed (still possible someone gets an old peakutils depending on their solver, but most users should get 1.3.5 with new environment builds), and I made the changes both in-repo and on the feedstock to have a hard min-version-pin; the latter will go out with the next release.

Closing.
