### ISSUE TITLE
Using multiple tiff files as inputs

### ISSUE THREAD

**Issue by in0565** [flatironinstitute/CaImAn#138]
Hi,
I'm new with python, and I'd like to use as inputs some multiple (usually 2) tiff files because as each of them is greater than 4GBs I cannot simply concatenate and save as one tiff file.
I'm following the` demo_pipeline_cnmfE` in Jupyter as my data is one-photon data.
I found a function `load_movie_chain` to make a movie class with multiple files but with this I cannot run the `motion_correct_oneP_rigid(pars)` I can only run `Movie.motion_correction(pars)`.
Is there any way to use the function `motion_correct_oneP_rigid(pars)`  to multiple input files?
Thanks.

**Comment by agiovann** [comment]
Dear @in0565, 

yes it is possible. What I normally do is running correction on the first file and then use the template obtained to correct the second file. Also, when you create the mmap file you can pass a list of files as an input and it will generate a big file with the two original movies. 

It is not too difficult, but if you cannot find a way let me know. 

Best,

Andrea

**Comment by in0565** [comment]
Dear Andrea,

1stly, I tired to make a mmap file with my files using `files_new = cm.save_memmap(fnames, base_name='memmap_', order='C')` but as I tried `mc = motion_correct_oneP_rigid(files_new, other pars)` the `motion_correction_piecewise()` made an error about input file types...

2ndly, then I tried to run correction on the file[0] and keep that template and use it for the file[1].
Then, as you can see in the photo, 
![n2](https://user-images.githubusercontent.com/33928685/33974440-b57504ea-e0cb-11e7-886f-6de507448ff1.PNG)
there were no errors during the whole process, but the whole video seems to be duplicated from the later one (I compared with traditional ROI methods), not the sum of the 1st and 2nd one.

Here I attach my code for the 2nd question.

`fnames = ['m18_20161005_1_Substack_(1-1000)_square_crop.tif','m18_20161005_1_Substack_(1001-2000)_square_crop.tif']
fnames = [os.path.abspath(os.path.join(base_folder,fnames[0])), os.path.abspath(os.path.join(base_folder,fnames[1]))]`
`mc1 = motion_correct_oneP_rigid(fnames[0],
                                  gSig_filt = [gSig]*2,
                                  max_shifts = [5,5],
                                  dview = dview,
                                  splits_rig = 10,
                                  save_movie = True)
    bord_px_rig = np.ceil(np.max(mc1.shifts_rig)).astype(np.int)
    
    filename = fnames[1]
    gSig_filt = [gSig]*2
    max_shifts = [5,5]
    splits_rig = 10
    save_movie = True
    min_mov = np.array([cm.motion_correction.low_pass_filter_space(m_,gSig_filt) for m_ in cm.load(filename, subindices=range(400))]).min()    
    new_templ = mc1.total_template_rig    
    
    mc = MotionCorrect(filename, min_mov,
                       dview=dview, max_shifts=max_shifts, niter_rig=1, splits_rig=splits_rig,
                       num_splits_to_process_rig=None,
                       shifts_opencv=True, nonneg_movie=True, gSig_filt = gSig_filt)
    
    mc2 = mc.motion_correct_rigid(save_movie=save_movie,template = new_templ)  
    bord_px_rig = np.ceil(np.max(mc2.shifts_rig)).astype(np.int)
    
    fname_new1 = cm.save_memmap([ mc1.fname_tot_rig], base_name='memmap_', order = 'C')
    fname_new2 = cm.save_memmap([ mc2.fname_tot_rig], base_name='memmap_', order = 'C')

    fname_new = cm.save_memmap_join([fname_new1, fname_new2])`

Finally, here I'm using two short (1000 frames) videos for testing, but my actual data sometimes exceeds 2GB each, and while testing with one video (1.3GB), there was an overflow error: (the mmap file shown at the 1st line has 2.6GB)

> E:\m56_20171102\caiman_test\processedMovie-1_rig__d1_99_d2_247_d3_1_order_F_frames_27783_.mmap
loading in memory
mmap
D:\Anaconda3\envs\caiman\lib\site-packages\numpy\core\memmap.py:247: RuntimeWarning: overflow encountered in long_scalars
  bytes = long(offset + size*_dbytes)
---------------------------------------------------------------------------
> OSError                                   Traceback (most recent call last)
<ipython-input-5-8ac50c061af2> in <module>()
     20 
     21     bord_px_rig = np.ceil(np.max(mc.shifts_rig)).astype(np.int)     #borders to eliminate from movie because of motion correction
---> 22     fname_new = cm.save_memmap([ mc.fname_tot_rig], base_name='memmap_', order = 'C') # transforming memoruy mapped file in C order (efficient to perform computing)
     23 else:
     24     #% create memory mappable file

> ~\CaImAn\caiman\mmapping.py in save_memmap(filenames, base_name, resize_fact, remove_init, idx_xy, order, xy_shifts, is_3D, add_to_movie, border_to_0)
    340                 fname_tot = os.path.join(os.path.split(f)[0], fname_tot)
    341             big_mov = np.memmap(fname_tot, mode='w+', dtype=np.float32,
--> 342                                 shape=(np.prod(dims), T), order=order)
    343         else:
    344             big_mov = np.memmap(fname_tot, dtype=np.float32, mode='r+',

> D:\Anaconda3\envs\caiman\lib\site-packages\numpy\core\memmap.py in __new__(subtype, filename, dtype, mode, offset, shape, order)
    248 
    249         if mode == 'w+' or (mode == 'r+' and flen < bytes):
--> 250             fid.seek(bytes - 1, 0)
    251             fid.write(np.compat.asbytes('\0'))
    252             fid.flush()

> OSError: [Errno 22] Invalid argument

Thanks.

**Comment by agiovann** [comment]
I added some new functionality, but please use the file  demos_detailed/demo_pipeline_cnmfE.py (use spyder to execute in a matlab like environment) 
Let me know if that works

**Comment by in0565** [comment]
Hi,
I tried the demo_pipeline_cnmfE.py with spyder(caiman) and doesn't do any more after `** Startting parallel motion correction **` shown in the console.
My lab mate working with me told me that she got an error at motion correction starting as she tried couple of files as input, and also her spyder console didn't progress after ** Startting parallel motion correction **.
Thanks.

**Comment by agiovann** [comment]
would you mind sharing your 2 files with me so I can have a look?

**Comment by agiovann** [comment]
Are you by any chance using ipython notebook in MAC OS?

**Comment by bbondde** [comment]
Dear @agiovann , 
Acutally, @in0565 and I didn't try to using our data yet . We just used the file demos_detailed/demo_pipeline_cnmfE.py with example_movies/data_endoscope.tif as it is.  Spyder console didn't progress after ** Startting parallel motion correction **. We are using window7(10) with python 3.5.4.   And I have one more question. I can not find multiple files input option in your code. Is it OK if we just put in fnames = ['exmple_movies/data_endoscope1.tif', 'example_movies/data_endoscope2.tif'];  
Thanks!

**Comment by in0565** [comment]
Updates:
Success with the demos_detailed/demo_pipeline_cnmfE.py file in Spyder (I'm using Windows 10), with two files as inputs, but only when I run it cell by cell. (crtl + enter)
If I run with the run file button (f5), the process in the console stopes at  `** Startting parallel motion correction **`. The CPU gets 100% of loaded but doesn't progress during hours. (The input files are the demo's; data_esdoscope.tif, I just duplicated it to test the multi-file issue.)
Thanks for the multifile option.
