### ISSUE TITLE
Rigid motion correction - ignore frames

### ISSUE THREAD

**Issue by hluetck** [flatironinstitute/CaImAn#139]
Hello,

I am trying to run rigid motion correction on TIFF-file movies but excluding the first frame for each movie (because of shutter artifact). I tried:
```
mov = cm.load(tiff_file)
fname_tot_rig, tot_template, templates, shifts = 
motion_correct_batch_rigid(tiff_file, max_shifts, subidx=slice(1,mov.shape[0],1))
```

However, even when using `subidx=slice(1,mov.shape[0],1)` the resulting output file still has all frames. Is this expected behavior? If so, how would I go about removing specified frames from the movies?

Thanks, Henry

**Comment by epnev** [comment]
Hi @hluetck 
You are right, the ```subidx``` variable gets dropped and is not passed in the function ```motion_correction_piecewise```. We'll take a look @agiovann . In the meantime, I think if your file is relatively long, one frame at the beginning should not affect your results. To determine the template we use a median which would be relatively robust to such outliers. Can you confirm that?

**Comment by hluetck** [comment]
I agree that it probably does not matter for the motion correction. I am more concerned about the source extraction afterwards. As far as I know it is quite common to remove certain frames from the acquisition, so it might be nice to have this option. Thanks!

**Comment by epnev** [comment]
When you memory map the motion corrected file using e.g. ```save_memmap``` or ```save_memmap_each``` for multiple files, there is a parameter ```remove_init``` that will exclude the first X frames. You can use that in your pipeline (see e.g. line 132 [here](https://github.com/flatironinstitute/CaImAn/blob/master/demos_detailed/demo_pipeline.py#L132) ) to ignore the first frame after motion correction.

**Comment by epnev** [comment]
I fixed this issue in the dev branch. See the changes in the ```motion_correction.py``` file in this [commit](https://github.com/flatironinstitute/CaImAn/commit/538730686c1ad196a45df60f9e784b3d50d6fbbc). However, for stability issues I'd recommend to just ignore the first frame when memory mapping as I explained above.

**Comment by hluetck** [comment]
Hi @epnev 

I think ignoring the first frame when memory mapping is a good solution. However, when I do this, I get this error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-17-1978c6c2f764> in <module>()
----> 1 fname_new = cm.save_memmap(fname_els, base_name='memmap_', order = 'C', border_to_0 = bord_px_els, remove_init=1)

/Users/Henry/Applications/caiman/caiman/mmapping.pyc in save_memmap(filenames, base_name, resize_fact, remove_init, idx_xy, order, xy_shifts, is_3D, add_to_movie, border_to_0)
    318         if border_to_0 > 0:
    319 
--> 320             min_mov = Yr.calc_min()
    321             Yr[:, :border_to_0, :] = min_mov
    322             Yr[:, :, :border_to_0] = min_mov

AttributeError: 'numpy.ndarray' object has no attribute 'calc_min'
```

My code is:

```python
def setupMC(fname):
    mov = cm.load(fname)
    mc = MotionCorrect(fname, mov.min(), dview=dview, max_shifts=max_shifts, 
                   niter_rig=niter_rig, splits_rig=splits_rig, 
                   num_splits_to_process_rig=num_splits_to_process_rig, strides= strides, 
                   overlaps= overlaps, splits_els=splits_els, num_splits_to_process_els=num_splits_to_process_els, 
                   upsample_factor_grid=upsample_factor_grid, max_deviation_rigid=max_deviation_rigid, 
                   shifts_opencv = True, nonneg_movie = False)
    return mc

fname = tiff_files[0]
mc = setupMC(fname)
mc.motion_correct_pwrigid(save_movie=True, show_template = False)
fname_els = [mc.fname_tot_els]
bord_px_els = np.ceil(np.maximum(np.max(np.abs(mc.x_shifts_els)),
                                 np.max(np.abs(mc.y_shifts_els)))).astype(np.int) 
fname_new = cm.save_memmap(fname_els, base_name='memmap_', order = 'C', border_to_0 = bord_px_els, remove_init=1)
```
bord_px_els is 9 in my case.

Thanks, Henry

**Comment by epnev** [comment]
Thanks again for noticing this - this one is simple to fix:
https://github.com/flatironinstitute/CaImAn/commit/8e0bf1d17fbf929259c29813cd60b73d4328eeec

But alternatively, you can also remove the first frame when you load the memory mapped file.
