### ISSUE TITLE
way to executing demo notebook in bulk

### ISSUE THREAD

**Issue by kazugorira** [flatironinstitute/CaImAn#1397]
Hello

I want to exectute demo notebooks in bulk. Do you plan to add such a feature in the future?

**Comment by pgunn** [comment]
Can you help me understand what the purpose of this would be?

**Comment by kazugorira** [comment]
Sorry for the lack of words.
I want to process data from multiple trials at once.

**Comment by pgunn** [comment]
Ah, I see.

You probably should look at the commandline demos (under demos/general instead of demos/notebooks) and use those as a basis for what you need to do. You can modify them as needed to save whatever you want to save; they're pretty friendly to running in bulk as you describe.
