### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by CeeLo** [flatironinstitute/CaImAn#1399]
Hi, I've been having issues with installing Mesmerize-core. I have been following the instructions from the mesmerize-core to run the following: mamba create -n mescore -c conda-forge mesmerize-core and attempted to reinstall anaconda to see if it fixes the issue, but it did not do anything so far. 

My computer information is: 
Operating System: MacOS Sonoma 14.5
Hardware Type: M1 chip, 16 GB RAM
Python: 3.10.13

I have been getting the error message listed below. I'm not sure what the exact issue is in this case, I saw that there were issues with installing individual packages as well. What could I do to troubleshoot this? 

Error Message:
    Traceback (most recent call last):
      File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 959, in exception_converter
        raise e
      File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 952, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 898, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 767, in do_call
        exit_code = create(args, parser)
      File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 602, in create
        return install(args, parser, "create")
      File "/Users/cynthialo/anaconda3/lib/python3.10/site-packages/mamba/mamba.py", line 558, in install
        transaction.fetch_extract_packages()
    RuntimeError: Found incorrect download: libexpat. Aborting

`$ /Users/cynthialo/anaconda3/bin/mamba create -n mescore -c conda-forge mesmerize-core`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/cynthialo/anaconda3/bin/conda
             CONDA_PREFIX=/Users/cynthialo/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/cynthialo/anaconda3/bin/python
               CONDA_ROOT=/Users/cynthialo/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/Users/cynthialo/anaconda3/bin:/Users/cynthialo/anaconda3/condabin:/op
                          t/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App
                          /usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cry
                          ptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security
                          .cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.c
                          ryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Lib
                          rary/Apple/usr/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/cynthialo/anaconda3
            shell level : 1
       user config file : /Users/cynthialo/.condarc
 populated config files : /Users/cynthialo/.condarc
          conda version : 24.7.1
    conda-build version : 24.5.1
         python version : 3.10.13.final.0
                 solver : classic
       virtual packages : __archspec=1=m1
                          __conda=24.7.1=0
                          __osx=14.5=0
                          __unix=0=0
       base environment : /Users/cynthialo/anaconda3  (writable)
      conda av data dir : /Users/cynthialo/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cynthialo/anaconda3/pkgs
                          /Users/cynthialo/.conda/pkgs
       envs directories : /Users/cynthialo/anaconda3/envs
                          /Users/cynthialo/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.10.13 Darwin/23.5.0 OSX/14.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

**Comment by pgunn** [comment]
I see you also filed an issue against mezmerise-core here:
https://github.com/nel-lab/mesmerize-core/issues/313

Let's continue the conversation there.
