### ISSUE TITLE
How do I change the path to the temp folder?

### ISSUE THREAD

**Issue by ichigomikako** [flatironinstitute/CaImAn#1401]
Can I change the path to the temp folder with the command `SET CAIMAN_TEMP=D:\caiman_data\temp`?

**Comment by pgunn** [comment]
Hello,
That probably will work, but it's probably best to set the path to the CAIMAN_DATA directory instead (and run caimanmanager install after doing so). The path handling code is a little undertested in places and I'm not sure we've gotten all the code that makes temporary directories tamed yet.

**Comment by ichigomikako** [comment]
The temp folder needs to be reset each time or it goes back to the c drive
![image](https://github.com/user-attachments/assets/b184392a-e6a7-4b75-affd-8880490789f1)

**Comment by pgunn** [comment]
I may have been unclear.

If you set CAIMAN_DATA to somewhere different, you only need to do `caimanmanager install` once ever.
(you will always need to have the env var set though)
