### ISSUE TITLE
Saving motion corrected movies results in shifted image for multiple frames

### ISSUE THREAD

**Issue by smbaca** [flatironinstitute/CaImAn#1404]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows):
 Windows 11
 3. Hardware type (x86, ARM..) and RAM:
x86 32 cores and 128GB RAM 
4. Python Version (e.g. 3.9):
3.10.8
 6. Caiman version (e.g. 1.9.12):
 1.10.4
 8. Which demo exhibits the problem (if applicable):
 cnmfe pipeline demo
 10. How you installed Caiman (pure conda, conda + compile, colab, ..):
conda 
11. Details: 
I want to keep the motion corrected movie for presentation purposes. When I do so, there is almost always a large shift such that the entire image is displayed but incorrectly offset in the beginning and ending frames. Most frames are just shifted to the left and right but others are shifted up and down and left and right. 

<img width="431" alt="Screenshot 2024-09-13 at 1 21 37 PM" src="https://github.com/user-attachments/assets/8b5aef79-1413-4795-92a9-a5550d9190f9">
<img width="431" alt="Screenshot 2024-09-13 at 1 21 48 PM" src="https://github.com/user-attachments/assets/dbddbc67-7654-406b-beb0-49768d15170c">
<img width="424" alt="Screenshot 2024-09-13 at 1 22 05 PM" src="https://github.com/user-attachments/assets/a2267b44-bd4a-4eb4-b464-a537ceb1e722">
<img width="812" alt="Screenshot 2024-09-13 at 1 22 43 PM" src="https://github.com/user-attachments/assets/e09e7827-1aec-44b3-b61d-779b15cc1f5a">

**Comment by pgunn** [comment]
Hello,
Sorry for the delay in getting back to you; I'm looking at this now. 
Are you just seeing this with your data, or with the sample data as well?

**Comment by smbaca** [comment]
I have never tried to resave the sample data but I have noticed now with two different datasets of mine. These are usually ~9000-10000 frames. Happy to upload them if that will help.

-smb

**Comment by pgunn** [comment]
We'd probably only need one of them if it exhibits the issue; if you can drop it onto Google Drive and share it with pgunn@flatironinstitute.org that'd be one way to do it, although if you prefer some other route that's fine too.

**Comment by smbaca** [comment]
Well in tracking down the data to upload I did one final test. And found that the issue is not with caiman…ImageJ will produce the offset in the saved tiff stack generated from caiman. However FIJI which is the newer version of ImageJ does not have the issue.

Not sure why the older version of ImageJ—which I keep around because of some useful plug-ins—does this but it looks like this issue can be closed!

-Serapio

**Comment by pgunn** [comment]
No worries; glad I don't need to hop into a long debugging session :)

Cheers,
Pat
