### ISSUE TITLE
Image registration on longer files is slow / hangs up

### ISSUE THREAD

**Issue by catubc** [flatironinstitute/CaImAn#141]
Hi.

I have a lower-resolution (voltage imaging) 2.5GB stack (64x64 pixels, 240,000 frames) that I ran through mc.motion_correct_rigid. After almost 24 hours, it had taken up 220GB of RAM and was still not complete. Here's some of the output:

1430
1590
...
4270
4280

Are there some parameters that I need to set properly to address the lower-resolution and higher # of frames:

    # motion correction parameters
    niter_rig = 1               # number of iterations for rigid motion correction
    max_shifts = (6, 6)         # maximum allow rigid shift
    splits_rig = 56             # for parallelization split the movies in  num_splits chuncks across time
    strides = (48, 48)          # start a new patch for pw-rigid motion correction every x pixels
    overlaps = (24, 24)         # overlap between pathes (size of patch strides+overlaps)
    splits_els = 56             # for parallelization split the movies in  num_splits chuncks across time
    upsample_factor_grid = 4    # upsample factor to avoid smearing when merging patches
    max_deviation_rigid = 3     # maximum deviation allowed for patch with respect to rigid shifts
        
Thanks.
catubc

**Comment by epnev** [comment]
A couple of ideas come to mind:
1. You split the dataset in 56 chunks (split_rig) which for 240k frames means each chunk is pretty long. You might need to increase that let's say to 500. (Also parameters ```strides, overlaps, splits_els, upsample_factor_grid, max_deviation_rigid``` are not needed for rigid registration although that shouldn't affect the code)

2. We've seen cases where the multiprocessing cluster hangs when the file is executed as a script, whereas the same code runs fine if executed in a cell by cell block in spyder. Can you check that? @agiovann knows how to fix it I think

3. Make sure that there is no cluster already running when starting a new cluster. This can be done by adding:
```python
try:
    dview.terminate()
except:
    print('OK')
    
c, dview, n_processes = cm.cluster.setup_cluster(
    backend='ipyparallel', n_processes=None, single_thread=False)
```

**Comment by agiovann** [comment]
Eftychios is correct. Although I would not expect to take as much memory. Something is off. As A test I would also try to run with dview = None. What is is the input data format?


Regarding to fixing, we are testing an installation procedure using conda-forge, that seems to work fin with some minor loss in performance. Keep an eye on the master.

**Comment by catubc** [comment]
Thanks for the suggestions, but when setting chunks to 500 my computer crashed within a minute as the entire memory (256GB) was filled (the original file is 2.5GB so the chunks should be very small).

It seems to be a particular problem on long datasets as the code worked fine for 3000 frames .tifs. 

So I tracked down the precise place where the crash occurs and it appears there is an inefficient use of file loading during a multiprocessing call to _tile_and_correct_wrapper_:

`def motion_correction_piecewise(fname,...):

if dview is not None:
        print('** Startting parallel motion correction **')
        if 'multiprocessing' in str(type(dview)):
            print ("... loading map_async...")
            **res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)**
            print ("... done loading map async ...")
        else:
            res = dview.map_sync(tile_and_correct_wrapper,pars)
        print('** Finished parallel motion correction **')
    else:
        res = list(map(tile_and_correct_wrapper,pars))
    return fname_tot, res   
`
It appears that each parallelized function call is re-reading the entire file .tif over again and slicing into it. My guess is that this is filling up the memory with redundant copies of the .tif (maybe no garbage collection or otherwise explicit delete is occuring?).

`def tile_and_correct_wrapper(params):
    #todo todocument

    from skimage.external.tifffile import imread
    import numpy as np
    import cv2
    try:
        cv2.setNumThreads(1)
    except:
        1 #'Open CV is naturally single threaded'

    img_name,  out_fname,idxs, shape_mov, template, strides, overlaps, max_shifts,\
        add_to_movie,max_deviation_rigid,upsample_factor_grid, newoverlaps, newstrides, \
        shifts_opencv,nonneg_movie, gSig_filt, is_fiji = params

    import os

    name, extension = os.path.splitext(img_name)[:2]
    
    if extension == '.tif' or extension == '.tiff':  # check if tiff file
        if is_fiji:
            **imgs = imread(img_name)[idxs]**
        else:
            **imgs = imread(img_name, key=idxs)**
        mc = np.zeros(imgs.shape,dtype = np.float32)
        shift_info = []`

I fixed this by passing the chunks into the .map_async() call, i.e. there is no more memory overloading.

**Comment by agiovann** [comment]
Absolutely right

it is possible that setting is_fiji to false might work as well!

**Comment by catubc** [comment]
Hi

So everything works fine now with the memory leak corrected. I was able to use your code to register 240,000 frame stack (64 x 64 pixels). 


```
  def motion_correction_piecewise(...):
  #Cat: load image file and then send only chunks to multiprocessing code below: 
    from skimage.external.tifffile import imread
    if extension == '.tif' or extension == '.tiff':  # check if tiff file
        if is_fiji:
            imgs = imread(fname)
        else:
            imgs = imread(fname)
    
    pars = []
    for idx in idxs:
        print ("idx: ", idx)
        pars.append([fname,fname_tot,idx,shape_mov, template, strides, overlaps, max_shifts, np.array(
          add_to_movie,dtype = np.float32),max_deviation_rigid,upsample_factor_grid,
                   newoverlaps, newstrides, shifts_opencv,nonneg_movie, gSig_filt, is_fiji, imgs[idx]])

```
and here's the minor changes to the _tile_and_correct_wrapper_:
```

def tile_and_correct_wrapper(params):
    #todo todocument

    from skimage.external.tifffile import imread
    import numpy as np
    import cv2
    try:
        cv2.setNumThreads(1)
    except:
        1 #'Open CV is naturally single threaded'

    img_name, out_fname,idxs, shape_mov, template, strides, overlaps, max_shifts,\
        add_to_movie,max_deviation_rigid,upsample_factor_grid, newoverlaps, newstrides, \
        shifts_opencv,nonneg_movie, gSig_filt, is_fiji, imgs = params

    mc = np.zeros(imgs.shape,dtype = np.float32)
    shift_info = []
```

Thanks!
