### ISSUE TITLE
Propose removing old unmaintained skcuda code 

### ISSUE THREAD

**Issue by kushalkolar** [flatironinstitute/CaImAn#1416]
Should probably remove all the cuda stuff from motion correction because it just confuses people, example: #1048 . skcuda is no longer maintained, [last release was over 5 years ago](https://github.com/lebedov/scikit-cuda/tags), so it's very unlikely to work with any relatively recently CUDA version and GPU, and would be difficult to interface with any other software. Given these limitations I don't even have a way to test if this even works. If users want GPU accelerated NoRMCorre we should just redirect them to FIOLA or jnormcorre which do a great job.

https://github.com/flatironinstitute/CaImAn/blob/bb55800806f0898592d79dcc705a0b53ccd01ec3/caiman/motion_correction.py#L1629-L1636

**Comment by pgunn** [comment]
It's not entirely unmaintained; the author seems to occasionally still be accepting patches, but no release in nine years isn't great.

I think this proposal seems reasonable; the other option would be to port it to some other framework (which would at least not require people to go out-of-codebase) but I'm not keen to volunteer for such work; unless someone else shows up keen to do that soon, removing these codepaths is probably a good idea.

**Comment by pgunn** [comment]
Now in dev
