### ISSUE TITLE
trouble installing caiman

### ISSUE THREAD

**Issue by pristscats** [flatironinstitute/CaImAn#1440]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Windows
 2. Hardware type (x86, ARM..) and RAM: x64
 3. Python Version (e.g. 3.9): 3.12.8
 4. Caiman version (e.g. 1.9.12): most up-to-date version (12/14/2024)
 5. Which demo exhibits the problem (if applicable): n/a
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): conda
 7. Details: 
On step 1 of installing Caiman, I try to run: conda activate caiman  # activate virtual environment
But I run into the error: 
EnvironmentNameNotFound: Could not find conda environment: caiman
You can list all discoverable environments with `conda info --envs`.

**Comment by pgunn** [comment]
Is this after you do the `mamba create ...` step?

**Comment by pristscats** [comment]
Yes, this is after successfully running the first two lines in step 1.

**Comment by pgunn** [comment]
Two questions then:
A) Did you get any errors in the command that created the environment, and
B) What do you see when you do a `conda env list`

**Comment by pristscats** [comment]
A) No
B) 
![image](https://github.com/user-attachments/assets/abc3c8cd-6746-4da8-afe4-c7caf7aedbfc)

**Comment by pgunn** [comment]
It's a bit surprising that it made the environment where it did and without a name.

We can either try to make it more normal (removing the existing conda install and its condarc, perhaps switching to miniforge) or you can, whenever you want to activate the environment, do this instead of `conda activate caiman`:

`conda activate c:\users\kurtisl2\.local\share\mamba\envs\caiman`

Either route would work.

**Comment by pristscats** [comment]
The second option works, thank you!

**Comment by pristscats** [comment]
After trying to run caimanmanager install, the following comes up: 
![{0A6A365F-F210-4C47-9513-7CBF6653A435}](https://github.com/user-attachments/assets/b88b6b67-ca6b-4cbc-90e0-f94605a0ae9c)

**Comment by pristscats** [comment]
It's pretty long, so here's just a part of it. 

![{C7D92F38-8432-4E28-8A4C-FDE7DF0D9F74}](https://github.com/user-attachments/assets/3479e7e8-ebd5-4467-9c04-14cdadf4a772)

**Comment by pgunn** [comment]
Somehow that environment ended up with a mix of packages from conda and from pypi. Did you use pip in any stage of setting up the environment?

**Comment by pristscats** [comment]
No, I only followed the quick start steps.

**Comment by pgunn** [comment]
Hm. We'll need to start over, and before we do so, I suggest you remove the environment (that path we typed in) and then conda itself. Then go grab this and start the install process:

`https://github.com/conda-forge/miniforge/releases/download/24.11.0-1/Miniforge3-24.11.0-1-Windows-x86_64.exe`

Hopefully this time it will neither install to a path nor end up with pypi packages in the list.

**Comment by pgunn** [comment]
If you run into hiccups, we could try it with a videoconference and screen share, but it'd be good to try it on your own first to see if it might go smoothly.
