### ISSUE TITLE
TypeError: object of type 'TiffFile' has no len()

### ISSUE THREAD

**Issue by ZEKAICHEN** [flatironinstitute/CaImAn#149]
I try to run the demo_pipeline.ipynb. When come to the **piecewise rigid motion correction using the NoRMCorre algorithm**, some error occurs as following:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-8430dfe6faf7> in <module>()
      1 #%% Run piecewise-rigid motion correction using NoRMCorre
----> 2 mc.motion_correct_pwrigid(save_movie=True)
      3 m_els = cm.load(mc.fname_tot_els)
      4 bord_px_els = np.ceil(np.maximum(np.max(np.abs(mc.x_shifts_els)),
      5                                  np.max(np.abs(mc.y_shifts_els)))).astype(np.int)  

~/CaImAn/caiman/motion_correction.py in motion_correct_pwrigid(self, save_movie, template, show_template)
    266         if template is None:
    267             print('generating template by rigid motion correction')
--> 268             self = self.motion_correct_rigid()
    269             self.total_template_els = self.total_template_rig.copy()
    270 #             pl.imshow(self.total_template_els)

~/CaImAn/caiman/motion_correction.py in motion_correct_rigid(self, template, save_movie)
    216                 add_to_movie=-self.min_mov,
    217                 nonneg_movie=self.nonneg_movie,
--> 218                 gSig_filt=self.gSig_filt)
    219 
    220             self.total_template_rig = _total_template_rig

~/CaImAn/caiman/motion_correction.py in motion_correct_batch_rigid(fname, max_shifts, dview, splits, num_splits_to_process, num_iter, template, shifts_opencv, save_movie_rigid, add_to_movie, nonneg_movie, gSig_filt, subidx)
   2390                                                              dview=dview, save_movie=save_movie, base_name=os.path.split(
   2391                                                                  fname)[-1][:-4] + '_rig_', subidx = subidx,
-> 2392                                                              num_splits=num_splits_to_process, shifts_opencv=shifts_opencv, nonneg_movie=nonneg_movie, gSig_filt=gSig_filt)
   2393 
   2394         new_templ = np.nanmedian(np.dstack([r[-1] for r in res_rig]), -1)

~/CaImAn/caiman/motion_correction.py in motion_correction_piecewise(fname, splits, strides, overlaps, add_to_movie, template, max_shifts, max_deviation_rigid, newoverlaps, newstrides, upsample_factor_grid, order, dview, save_movie, base_name, subidx, num_splits, shifts_opencv, nonneg_movie, gSig_filt)
   2597     if extension == '.tif' or extension == '.tiff':  # check if tiff file
   2598         with tifffile.TiffFile(fname) as tf:
-> 2599             if len(tf) == 1:  # Fiji-generated TIF
   2600                 is_fiji = True
   2601                 T, d1, d2 = tf[0].shape

TypeError: object of type 'TiffFile' has no len()

Can you help me explain where is wrong? Thanks so much!

**Comment by epnev** [comment]
Can you check the version of your tifffile package? The API changed between v 0.12 and v 0.13 and the package is not compatible with the latest version.

**Comment by ZEKAICHEN** [comment]
Yeah it's v 0.13.4

**Comment by pgunn** [comment]
Hi ZEKAICHEN,
As the author of that module changed the interface (and might do so again in the future), for now we're pinning version 0.12 of tifffile (we just landed a change to do this in our dev branch). You can fix this with your current checkout by doing `conda install tifffile=0.12.1` from inside your conda environment for caiman.

**Comment by ZEKAICHEN** [comment]
Thanks for your reply! Appreciate. I just tried `conda install tifffile=0.12.1` under the caiman env, but something saying:

PackageNotFoundError: Packages missing in current channels:
            
  - tifffile 0.12.1*

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
            
I don't know what's going on

**Comment by pgunn** [comment]
Ah, sorry, there are different conda repositories we use between our dev and main branches, and on the main branch pip is used to install tifffile. Instead, could you do
`pip install tifffile==0.12.1`
?

**Comment by ZEKAICHEN** [comment]
Ah yeah I just noticed that. Alright, I successfully install the v 0.12.1 Now let me rerun the coding

**Comment by pgunn** [comment]
Happy to help!

**Comment by pgunn** [comment]
Should be fixed on master by https://github.com/flatironinstitute/CaImAn/commit/3264e51d2c6e5f6605616267f0b9da1de8c8c1e6
