### ISSUE TITLE
Exception: Input must be an ndarray, use load instead!

### ISSUE THREAD

**Issue by ZEKAICHEN** [flatironinstitute/CaImAn#150]
Hi there,

I just met another issue when I was running the `Memory mapping` module with `demoMovieJ.tif` and under `backend = ipyparallel`. It has error as following:

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-17-bbf324e398f2> in <module>()
      4 border_to_0 = bord_px_els     # number of pixels to exclude
      5 fname_new = cm.save_memmap(fnames, base_name='memmap_', order = 'A',
----> 6                            border_to_0 = bord_px_els) # exclude borders
      7 
      8 # now load the file

~/CaImAn/caiman/mmapping.py in save_memmap(filenames, base_name, resize_fact, remove_init, idx_xy, order, xy_shifts, is_3D, add_to_movie, border_to_0, dview, n_chunks, async)
    331 
    332             else:
--> 333                 Yr = cm.load(f, fr=1, in_memory=True) if isinstance(f, basestring) else cm.movie(f)
    334 
    335                 if xy_shifts is not None:

~/CaImAn/caiman/base/movies.py in __new__(cls, input_arr, **kwargs)
     98             return super(movie, cls).__new__(cls, input_arr, **kwargs)
     99         else:
--> 100             raise Exception('Input must be an ndarray, use load instead!')
    101 
    102     def motion_correction_online(self, max_shift_w=25, max_shift_h=25, init_frames_template=100,

Exception: Input must be an ndarray, use load instead!

Can you give me any idea what's wrong here?

**Comment by ZEKAICHEN** [comment]
The code is exactly consistent with the sample one as 
`
#%% MEMORY MAPPING
# memory map the file in order 'C'
fnames = [mc.fname_tot_els]   # name of the pw-rigidly corrected file.
border_to_0 = bord_px_els     # number of pixels to exclude
# fname_new = cm.save_memmap(fnames, base_name='memmap_', order = 'C', 
#                            border_to_0 = bord_px_els) # exclude borders
fname_new = cm.load_memmap(fnames, base_name='memmap_', order = 'C', 
                           border_to_0 = bord_px_els) # exclude borders

# now load the file
Yr, dims, T = cm.load_memmap(fname_new)
d1, d2 = dims
images = np.reshape(Yr.T, [T] + list(dims), order='F') 
    #load frames in python format (T x X x Y)
`

**Comment by epnev** [comment]
Which demo are you trying to run?

**Comment by ZEKAICHEN** [comment]
demo_pipeline.ipynb

**Comment by ZEKAICHEN** [comment]
I run the original file, step by step, nothing changed

**Comment by epnev** [comment]
can you try changing the line:
`fnames = [mc.fname_tot_els]   # name of the pw-rigidly corrected file.`
to
`fnames = mc.fname_tot_els   # name of the pw-rigidly corrected file.`
and let me know if it works?

**Comment by ZEKAICHEN** [comment]
Yes! That works! Many thanks!
