### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by ZEKAICHEN** [flatironinstitute/CaImAn#151]
When I was running `demo_pipeline.ipynb`, error occurred in the *plot contours of identified components against correlation image* module such as,

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-7b300887f7aa> in <module>()
      2 Cn = cm.local_correlations(images.transpose(1,2,0))
      3 Cn[np.isnan(Cn)] = 0
----> 4 plt.figure(); crd = plot_contours(cnm.A, Cn, thr=0.9)
      5 plt.title('Contour plots of found components')

~/CaImAn/caiman/utils/visualization.py in plot_contours(A, Cn, thr, thr_method, maxthr, nrgthr, display_numbers, max_number, cmap, swap_dim, colors, vmin, vmax, **kwargs)
    930 
    931     d1, d2 = np.shape(Cn)
--> 932     d, nr = np.shape(A)
    933     if max_number is None:
    934         max_number = nr

ValueError: not enough values to unpack (expected 2, got 0)

Hope to get your help!

**Comment by ZEKAICHEN** [comment]
All the backend is `ipyparallel` instead of `local`

**Comment by epnev** [comment]
What do you get if you type `np.shape(cnm.A)`?

**Comment by epnev** [comment]
Are you on a mac and python 3? Can you check whether the shell above produced any errors?

**Comment by ZEKAICHEN** [comment]
The result is `( )` when I do `np.shape(cnm.A)`, and I print `cnm.A` which comes out `None`. I use mac and Python 3

**Comment by ZEKAICHEN** [comment]
Oh I just found that the last line `cnm = cnm.fit(images)` was commented out and I fix it. But now the error has become into 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-2b61ff959181> in <module>()
      9                 method_init=init_method, alpha_snmf=alpha_snmf,
     10                 only_init_patch = False, gnb = gnb, border_pix = bord_px_els) 
---> 11 cnm = cnm.fit(images)

~/CaImAn/caiman/source_extraction/cnmf/cnmf.py in fit(self, images)
    533                                                                      gnb=self.gnb, border_pix=self.border_pix,
    534                                                                      low_rank_background=self.low_rank_background,
--> 535                                                                      del_duplicates=self.del_duplicates)
    536 
    537             # options = CNMFSetParms(Y, self.n_processes, p=self.p, gSig=self.gSig, K=A.shape[

~/CaImAn/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, options, rf, stride, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates)
    372         (b_tot, idx_tot_B, idx_ptr_B), shape=(d, count_bgr))
    373 
--> 374     idx_tot_A = np.concatenate(idx_tot_A)
    375     a_tot = np.concatenate(a_tot)
    376     idx_ptr_A = np.cumsum(np.array(idx_ptr_A))

ValueError: need at least one array to concatenate

**Comment by ZEKAICHEN** [comment]
Let me run the .py file to see if it works

**Comment by ZEKAICHEN** [comment]
Can I change backend from `local` into `ipyparallel` in the demo_pipeline.py file?

**Comment by epnev** [comment]
I recommend local although the problem seems to be independent of that.

**Comment by ZEKAICHEN** [comment]
I used the backend as `ipyparallel` and still the same error with the demo_pipeline.py file. Perhaps I should try to use `local` instead.

**Comment by ZEKAICHEN** [comment]
Yes! I successfully run the demo_pipeline.py file with `backend = local`. So it seems the problem is from the `ipyparallel`

**Comment by epnev** [comment]
Good! It's unclear that `ipyparallel` is the problem since I get the same error when using the `local` backend through the notebook. I suggest to not use jupyter notbeooks until we figure this out. Thanks for bringing this into our attention. It used to work fine about a month ago..

**Comment by ZEKAICHEN** [comment]
Oh I see. Okay. Anyway, thanks for your kind reply and I greatly appreciate!
