### ISSUE TITLE
Custom javascript for bokeh visualizations needs updating.

### ISSUE THREAD

**Issue by nerduno** [flatironinstitute/CaImAn#155]
The bokeh visualizations are crashing with the latest version of bokeh: 0.12.13.

To fix the issue I had to replace the use of 'get':
`var data = source.get('data');`
with the simpler:
`var data = source.data;`
See this bokeh issue: https://github.com/bokeh/bokeh/issues/7301

I also had to update the change signalling:
`source.trigger('change')`
with:
`source.change.emit();`

**Comment by j-friedrich** [comment]
Thanks for pointing out the issue and even providing the code snippets to fix it.
