### ISSUE TITLE
Clean install: demo_pipeline.ipynb is not producing a results_analysis.npz file

### ISSUE THREAD

**Issue by alyosha-f** [flatironinstitute/CaImAn#161]
I have made a fresh install from most recent git using anaconda python 3. I have a version on Ubuntu and Win and behaviour is so far identical.

I am interested in demo_pipeline.ipynb as a starting point. It runs smoothly out of the box, but is a problem:

The <something>_results_analysis.npz does not seem to be found anywhere. I run Jupyter from CaImAn root directory and demo_pipeline.ipynb runs smoothly. It seems to be instructed to write the .npz file towards the end of the program, but it is neither in the root directory nor in the example_movies directory. Where could it be?

**Comment by epnev** [comment]
Have you check whether a file named 
`memmap__d1_170_d2_170_d3_1_order_C_frames_3000_.results_analysis.npz`
appears in your example_movies folder?

**Comment by alyosha-f** [comment]
Contents of my example_movies folder is as follows: 

data_endoscope.tif
demoMovie3D.tif
demoMovie_els__d1_60_d2_80_d3_1_order_F_frames_2000_.mmap
demoMovieJ.tif
demoMovie.tif
memmap__d1_170_d2_170_d3_1_order_C_frames_3000_.mmap
memmap__d1_60_d2_80_d3_1_order_C_frames_2000_.mmap
Mesoscope
Sue_2x_3000_40_-46_els__d1_170_d2_170_d3_1_order_F_frames_3000_.mmap
Sue_2x_3000_40_-46.tif
Yr_d1_30_d2_40_d3_50_order_F_frames_256_.mmap


I suppose the file is not there

**Comment by epnev** [comment]
I just ran it on a linux machine. The file was saved but I found a bug when saving the variables which is now fixed. You can try again. Make sure you change the `save_results` flag to `True`

**Comment by alyosha-f** [comment]
Thanks :)

A naive question: is it enough to do a "git pull" in the folder and then recompile the project, or do I have to delete the whole CaImAn and clone it again?

**Comment by epnev** [comment]
If you cloned it (as opposed to downloading a zip file) a git pull will update it

**Comment by epnev** [comment]
No recompiling will be necessary

**Comment by alyosha-f** [comment]
The file is now saved correctly. I totally missed the save flag. I am very sorry

**Comment by epnev** [comment]
great, thanks!
