### ISSUE TITLE
demo_pipeline.ipynb - replacing "Sue_2x_3000_40_-46.tif" with "demoMovie.tif" causes weird behaviour

### ISSUE THREAD

**Issue by alyosha-f** [flatironinstitute/CaImAn#162]
demo_pipeline.ipynb runs smoothly using original settings. If one tries to use the smaller movie by writing "fname =['demoMovie.tif']" and adjusting the path accordingly, the CNMF algorithm appears to work smoothly and finds the regions. However, when it displays the motion corrected movie, it shows only the borders. The inside of the movie is white. Also, it produces 18 accepted components, but when it tries to produce rejected components, it crashes with "list index out of range" at "CaImAn/caiman/utils/visualization.py" line 181.

**Comment by epnev** [comment]
Can you reduce the `gain` when you display the motion corrected data?

**Comment by alyosha-f** [comment]
Just tried setting gain=5 or gain=10 for the code

cm.concatenate([m_orig.resize(1, 1, downsample_ratio)+offset_mov,
                m_els.resize(1, 1, downsample_ratio)], 
               axis=2).play(fr=60, gain=15, magnification=2, offset=0)  # press q to exit

The result is still the same - the movie on the right is still a white box with moving border of a few pixels

**Comment by epnev** [comment]
Are you using 'demoMovie.tif' or 'demoMovieJ.tif'?

**Comment by alyosha-f** [comment]
demoMovie.tif

**Comment by epnev** [comment]
I checked the demoMovieJ and it worked fine. The reason  "list index out of range" error was produced because there were actually no rejected components so there was nothing to plot. I'll put an if command to make sure to test for that.

**Comment by alyosha-f** [comment]
I confirm, demoMovieJ.tif works fine, and demoMovie.tif does not

**Comment by epnev** [comment]
The issue is with the data type of demoMovie. Will fix it

**Comment by epnev** [comment]
In the motion correction block change
`min_mov = cm.load(fname[0], subindices=range(200)).min()`
to
`min_mov = min(cm.load(fname[0], subindices=range(200)).min(),0)`
It should work (but you'll need to adjust the gain parameter e.g. to 5 for more visible results).
Let me know

**Comment by alyosha-f** [comment]
I confirm, with the proposed edit demoMovie.tif works as expected in terms of visualisation

**Comment by epnev** [comment]
cool, thanks.
