### ISSUE TITLE
Undefined function or variable 'Cn'

### ISSUE THREAD

**Issue by sstaszko** [flatironinstitute/CaImAn#164]
When running the demo data through demo_pipeline.mlx, I consistently get the error at "rejected vs selected components" that reads Undefined function or variable 'Cn' with a blank plot. 

```throw = ~keep;
figure;
    ax1 = subplot(121); plot_contours(A(:,keep),Cn,options,0,[],Coor,1,find(keep)); title('Selected components','fontweight','bold','fontsize',14);
    ax2 = subplot(122); plot_contours(A(:,throw),Cn,options,0,[],Coor,1,find(throw));title('Rejected components','fontweight','bold','fontsize',14);
    linkaxes([ax1,ax2],'xy')
```

**Comment by epnev** [comment]
This is the python repo. Please post on [MATLAB's repo](https://github.com/flatironinstitute/CaImAn-MATLAB)
