### ISSUE TITLE
Cannot play movie in Jupyter notebook on Ubuntu

### ISSUE THREAD

**Issue by hluetck** [flatironinstitute/CaImAn#173]
Hello,

I am trying to run the demo_pipeline.ipynb notebook on a Ubuntu virtual machine (remote access). Loading the data (Sue_2x_3000_40_-46.tif) works fine, but when I try to play the movie, the kernel dies:
`m_orig.play(gain=10, offset=offset_mov, fr=30, magnification=2)` --> kernel dies

I also tried the `backend='notebook'` option:
`m_orig.play(gain=10, offset=offset_mov, fr=30, magnification=2, backend='notebook')`

This produces an error:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-5-91e15940e9ac> in <module>()
> ----> 1 m_orig.play(gain=10, offset=offset_mov, fr=30, magnification=2, backend='notebook')
> 
> ~/caiman/caiman/base/movies.py in play(self, gain, fr, magnification, offset, interpolation, backend, do_loop, bord_px)
>    1062 
>    1063             # call our new function to display the animation
> -> 1064             return visualization.display_animation(anim, fps=fr)
>    1065 
>    1066         if fr is None:
> 
> ~/caiman/caiman/utils/visualization.py in display_animation(anim, fps)
>     758 def display_animation(anim, fps=20):
>     759     pl.close(anim._fig)
> --> 760     return HTML(anim_to_html(anim, fps=fps))
>     761 #%%
>     762 
> 
> ~/caiman/caiman/utils/visualization.py in anim_to_html(anim, fps)
>     749             anim.save(f.name, fps=fps, extra_args=['-vcodec', 'libx264'])
>     750             video = open(f.name, "rb").read()
> --> 751         anim._encoded_video = video.encode("base64")
>     752 
>     753     return VIDEO_TAG.format(anim._encoded_video)
> 
> AttributeError: 'bytes' object has no attribute 'encode'
> 

Thanks for the help!

Regards, Henry

**Comment by epnev** [comment]
@hluetck is this specific to notebook? Can you run the demo_pipeline.py on the same virtual machine?

**Comment by epnev** [comment]
Also, what version of python are you using?

**Comment by pgunn** [comment]
Hi,
As far as I can tell this is a Python2 versus Python3 compatibility issue. I'm making a patch to address the issue, but in the meantime if you want to patch your

~/caiman/caiman/utils/visualization.py

and make the following change, it should get you going:
1) Add an "import base64" to the top of the file
2) On line 751 (which you might make into a different line number by adding the above import), change the right side of the assignment from:

video.encode("base64")
to
base64.b64encode(video)

If you don't want to do this, note that I expect to land the patch today and if you pull tomorrow you'll be good.

**Comment by pgunn** [comment]
Pull requests that fix this issue:
https://github.com/flatironinstitute/CaImAn/pull/175
https://github.com/flatironinstitute/CaImAn/pull/176

**Comment by hluetck** [comment]
Hello,

I tested it and found that the fix works, but only if I also change the next line to:
`return VIDEO_TAG.format(anim._encoded_video.decode('ascii'))`

If I don't add `.decode('ascii')` there is only an empty video player in the output cell.

Thanks for your help.

Best, Henry

**Comment by pgunn** [comment]
2 more PRs
#181 
#182
