### ISSUE TITLE
matplotlib._cntr deprecated

### ISSUE THREAD

**Issue by neurodroid** [flatironinstitute/CaImAn#174]
The `matplotlib._cntr` module (used for example [here](https://ccarocean.github.io/python-contours/) in CaImAn) [has been removed from matplotlib](https://github.com/matplotlib/matplotlib/commit/e95572c6) and will be unavailable from version 2.2.0 onwards.
There's an alternative [standalone contours module](https://ccarocean.github.io/python-contours/) that provides similar functionality at the cost of adding a dependency.
[Here's an example](https://github.com/neurodroid/haussmeister/commit/0a51304e) of how to replace `matplotlib._cntr` with the `contours` module.

**Comment by j-friedrich** [comment]
We already have skimage as dependency, hence replaced with skimage.measure.find_contours in dev and master.
