### ISSUE TITLE
No async argument in save_memap_join

### ISSUE THREAD

**Issue by vaiana** [flatironinstitute/CaImAn#177]
Line 311 of mmapping.py reads

`fname_new = cm.save_memmap_join(fname_new, base_name=base_name, dview=dview, n_chunks=n_chunks,  async=async)`

But the definition of save_memmap_join does not include an async argument
`def save_memmap_join(mmap_fnames, base_name=None, n_chunks=20, dview=None):
`

This is an easy fix but it was giving me errors when trying to save a large sequence of individual tiff files into a single memory mapped array.

**Comment by agiovann** [comment]
Hello Michael, 
thank you so much for pointing that out. I am curious, why would you get an error for many files? Do you have the log saved somewhere?

Thank you!

**Comment by vaiana** [comment]
Hi Andrea,

Sorry for the confusion, the point wasn't that there are a large number of files, the point was that calling `save_memmap` directly was branching into  `save_memmap_join` causing the error I mentioned.  

I do have a related question/bug that I will open as another issue.
