### ISSUE TITLE
Can not save individual .tiff files into memory map

### ISSUE THREAD

**Issue by vaiana** [flatironinstitute/CaImAn#178]
Calling `save_memmap` on a list of images which consist of single frames (i.e. 2 dimensional images) causes an index error 'IndexError: tuple index out of range'  in the line `1 if len(dims) == 2 else dims[2]) + '_order_' + str(order)` in `mmapping.py`

My collaborator images in such a way that the data from a recording session is stored as single individual `.tiff` files.  We may have 100k such files in a directory and even dealing with a subset of them can be difficult due to the size of the data.  I am hoping to use the CaImAn code base to save chunks into memory mapped files to be able to work with them.  

I think this is also a fairly easy fix, just putting in a check to make sure that the loaded file has 3 nontrivial dimensions.  For example,
```
            if len(np.squeeze(Yr).shape) ==2:
                # loading single tiff images at a time
                dims = Yr.shape
                T = 1
            else:
                T, dims = Yr.shape[0], Yr.shape[1:]
                Yr = np.transpose(Yr, list(range(1, len(dims) + 1)) + [0])
            Yr = np.reshape(Yr, (np.prod(dims), T), order='F')
```
Not sure if this has consequences I'm not thinking through.  It would be great to be able to map a sequence of individual tiffs into a single memory mapped file and then continue the pipeline.

**Comment by agiovann** [comment]
In practice it will have consequences. In order to make everything work, especially motion correction, each single file should have at least 500 frames (the more the frames the more you can parallelize motion correction). The solution is easy, just having a preprocessing file that groups your frames into files (I would suggest 3000 frames). Or is that impossible?

**Comment by vaiana** [comment]
We have long periods we are interesting in looking at.  Supposed I wanted to look at 21k frames,  can I group into 7 groups of 3k as you suggest and then motion correct and run the CaImAn pipeline on the full 21k?

This is unrelated, and I can open another issue or we can chat outside of the GitHub interface if you have time, but I'm wondering if its possible to us CaImAn with my own ROIs?

**Comment by agiovann** [comment]
Absolutely, that is the idea. You can use the demo_pipeline file (use the dev branch please), and you can pass a list to cm.save_memmap. Let me know if this works for you.
