### ISSUE TITLE
A question about online calcium image analysis OnACID algorithm 

### ISSUE THREAD

**Issue by marchzhe** [flatironinstitute/CaImAn#187]
Hi

I am interested in the OnACID algorithm for real time calcium image analysis. It seems that this real-time algorithm is verified on 2p data set. I wonder if it works equally well for the 1-photon calcium image?

Thanks,
marchzhe

**Comment by agiovann** [comment]
Dear @marchzhe,

at the moment it does not work. We are planning to look into it once we finalize the 2 photon work. I will leave the issue open as an improvement request. Thank you!

**Comment by epnev** [comment]
This is now possible with caiman 1.7 or higher.
