### ISSUE TITLE
trouble loading video under Ubuntu 16.04

### ISSUE THREAD

**Issue by ckemere** [flatironinstitute/CaImAn#190]
Hey folks,

Has anyone run up against an OpenCV issue where video files can't be loaded in Ubuntu? I've seen a lot of traffic about FFMPEG, but I'm not sure if this has been solved for CaImAn or not.

thanks!
caleb

**Comment by pgunn** [comment]
Hi,
Can you give us the output you get when video fails to load? This could be one of a few causes.

**Comment by agiovann** [comment]
Hi Pat, 

It might the newer version of opencv. If it is, we should fix the version at the most recent working.

**Comment by ckemere** [comment]
The errors arise in the memory mapped file creation because the dimensions of the frames are 0. I traced that down to the VideoCapture call, which fails silently to open the file. The interwebs suggest this happens because of some sort of ffmpeg/opencv misconfiguration. Why are you using opencv rather than just the raw ffmpeg calls?

**Comment by agiovann** [comment]
Dear @ckemere, the avi load function is not used often and in general when I cannot load the file I go through ImageJ to transform the file into tiff. However it is just a hack. Is it easy (both in terms of installation and coding) to directly call ffmpeg?  We could think about doing it if it is portable and robust. Please let me know your opinion! Thank you for the feedback

**Comment by ckemere** [comment]
It appears that sk-video might be preferable. However, when I actually probe using ffmpeg, I find that the avi file has some issue in my installation, so there may be more challenging things to figure out.

**Comment by ckemere** [comment]
OK, I need to apologize. It turns out that when I uploaded my test file to my Ubuntu box, it was corrupted. For future readers who might face issues with Ubuntu 16.04, it appears that the default ffmpeg is old, and can be upgraded, but OpenCV should otherwise work!
