### ISSUE TITLE
Incorrect call to save_memmap_join

### ISSUE THREAD

**Issue by jonnew** [flatironinstitute/CaImAn#193]
Line 311 of memapping.py makes the following call
```
fname_new = cm.save_memmap_join(fname_new, base_name=base_name, dview=dview, n_chunks=n_chunks,  async=async) 
```
However the function `save_memmap_join` does not seem to take an `async` argument.
 
```
def save_memmap_join(mmap_fnames, base_name=None, n_chunks=20, dview=None)
```

**Comment by pgunn** [comment]
Thanks for letting us know! I'll have a patch to fix this later today.
