### ISSUE TITLE
Stripped down pipeline without motion correction?

### ISSUE THREAD

**Issue by Cumol** [flatironinstitute/CaImAn#195]
I am trying to use CNMF for a rather simpel data set with cultured neurons where no motion correction is needed.

What would be the best approach using your package? I am rather new to python and was not able to make the basic.py script run as it requires ipython even though it is a python script...

Am I on the right track or is there an easier option?

**Comment by epnev** [comment]
You can use the [demo_caiman_basic.py](https://github.com/flatironinstitute/CaImAn/blob/master/demos_detailed/demo_caiman_basic.py) demo which does not perform any motion correction. However, please follow the installation instructions to install all the required packages before running caiman. If you prefer to use matlab see [here.](https://github.com/flatironinstitute/CaImAn-MATLAB)
