### ISSUE TITLE
On caiman saving in memmap fails for larger files

### ISSUE THREAD

**Issue by agiovann** [flatironinstitute/CaImAn#198]
Input is a 1.5 GB file

Error is:

example_movies/025_003_000_5_green_02_rig__d1_412_d2_696_d3_1_order_F_frames_2646_.mmap
loading in memory
mmap
SAVING WITH f.write()
Traceback (most recent call last):

  File "<ipython-input-32-7afc5a3e65e3>", line 3, in <module>
    border_to_0=bord_px_els.astype(np.int))  # exclude borders

  File "/Users/agiovann/SOFTWARE/CaImAn/caiman/mmapping.py", line 435, in save_memmap
    f.write(Yr)

OSError: [Errno 22] Invalid argument

**Comment by pgunn** [comment]
Is there any chance your conda environment ended up with a 32-bit python? I'd expect a 32-bit python to not be able to map a file that big.

Could you run this and let me know the results?

If you're on Python2:
python -c "import platform; import sys ; print platform.architecture();print sys.maxsize > 2**32"

Or if you're on Python3:
python -c "import platform; import sys ; print(platform.architecture());print(sys.maxsize > 2**32)"
('64bit', '')

**Comment by pgunn** [comment]
(do this in the environment that you saw the problem in)

**Comment by agiovann** [comment]
see #205
