### ISSUE TITLE
cnm.fit(movie) throws Attribute Error: 'movie' object has no attribute 'filename'

### ISSUE THREAD

**Issue by gcskoenig** [flatironinstitute/CaImAn#199]
When fitting the deconvolution to a movie object as shown in the demo_caiman_basic.py file, I get an error stating that the movie attribute 'filename' was not found.

Indeed, the movie object does not have a 'filename' attribute, but one called 'file_name'. The movie object was created using the caiman.load() function.

How can I solve this?

``` python
import caiman as cm
from caiman.source_extraction.cnmf import cnmf as cnmf
import os
import numpy as np
import math
import matplotlib.pyplot as plt

# some code

movie = cm.load(files[1])

# some code

cnm = cnmf.CNMF(n_processes, method_init='greedy_roi', k=K, gSig=gSig,
                merge_thresh=merge_thresh, p=p, dview=dview, gnb=gnb,
                rf=rf, stride=stride, rolling_sum=False)
cnm = cnm.fit(movie)
```

**Comment by pgunn** [comment]
Hi,
Can you give us the text of the error you're getting?

Thanks,
Pat

**Comment by gcskoenig** [comment]
Sure!

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-e6686947adb8> in <module>()
      3                 merge_thresh=merge_thresh, p=p, dview=dview, gnb=gnb,
      4                 rf=rf, stride=stride, rolling_sum=False)
----> 5 cnm = cnm.fit(movie)
      6 
      7 

/Volumes/HDD/university/M.Sc. Data Science/18/thesis/CaImAn/caiman/source_extraction/cnmf/cnmf.py in fit(self, images)
    528                 options['init_params']['alpha_snmf'] = self.alpha_snmf
    529 
--> 530             A, C, YrA, b, f, sn, optional_outputs = run_CNMF_patches(images.filename, dims + (T,),
    531                                                                      options, rf=self.rf, stride=self.stride,
    532                                                                      dview=self.dview, memory_fact=self.memory_fact,

AttributeError: 'movie' object has no attribute 'filename'
```

**Comment by pgunn** [comment]
Hi,
As far as I can tell, you're not passing the right parameter to the fit function; the demos are doing a load_memmap() and then reshaping the Yr; that's built from a numpy.memmap (which will have the filename attribute as per https://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html )

So if you can do that, I think the problem will be solved. (if this isn't clear, let me know and we can go more into the details).

Cheers,
Pat

**Comment by epnev** [comment]
@gcskoenig I'm closing the issue but feel free to reopen if your problems persist.

**Comment by gcskoenig** [comment]
That solved it, thank you!
