### ISSUE TITLE
CNN threshold

### ISSUE THREAD

**Issue by somsol** [flatironinstitute/CaImAn#225]
Hi. Can anyone explain to me what's the difference between "thresh_CNN_noisy" and "rm_thr" ? What's a good number to use for these?

Thanks.

**Comment by agiovann** [comment]
@somsol the former is a threshold to decide the probability of accepting shapes that look like neurons. The latter is a threshold for removing neurons that might have low quality. If the flag remove_flag is set to False it will not have any effect. We have run all our experiments without using it (remove_flag=False) and we obtained very good results.

**Comment by epnev** [comment]
@somsol Just to add, `thresh_CNN_noisy` and its corresponding CNN is used *during* the online processing to detect *new* neurons. `rm_thr` and its corresponding CNN is used *after* the online processing has finished to detect and remove false positive components. 

Feel free to re-open the issue if you have any further questions.
