### ISSUE TITLE
CaImAn source extraction - same analysis, different results

### ISSUE THREAD

**Issue by hluetck** [flatironinstitute/CaImAn#232]
Hello,

we are running the CaImAn source extraction on dendritic data. When the same analysis is run with same parameters on the same dataset, the identified components are usually NOT the same. I.e. we are seeing that the number of identified components changes as well as the components that are classified as good / bad. Usually the discrepancy is about 1 - 2 components (5-10%). Is there a random number generation involved somewhere and if so, would it be possible to provide a fixed seed?

Thanks for your help.

Best regards, Henry

**Comment by agiovann** [comment]
dear @hluetck 

it should be fixed, can you  give it a try?

Cheers

**Comment by hluetck** [comment]
Thanks a lot for the quick reply. I tried to test but have the following error:
`YrA = cnmf_out.YrA`
AttributeError: 'CNMF' object has no attribute 'YrA'

Is the residual not computed automatically anymore?

Thanks!

**Comment by hluetck** [comment]
Hello @agiovann @epnev 

I just noticed yesterday evening that CaImAn's installation is now different. So, I re-installed with pip according to the new instructions and it seems to work fine. Thanks for your help.

Best, Henry
