### ISSUE TITLE
Motion correction in notebook demo fails

### ISSUE THREAD

**Issue by pavolbauer** [flatironinstitute/CaImAn#237]
Hi,

On a fresh installation of CaImAn on Windows 10 and an up-do-date Anaconda distribution, I get the following error when running demo_pipeline.

`%%capture
#%% Run piecewise-rigid motion correction using NoRMCorre
mc.motion_correct_pwrigid(save_movie=True)
m_els = cm.load(mc.fname_tot_els)
bord_px_els = np.ceil(np.maximum(np.max(np.abs(mc.x_shifts_els)),
                                 np.max(np.abs(mc.y_shifts_els)))).astype(np.int)  
    # maximum shift to be used for trimming against NaNs`

produces the error 
``
--------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\bauerp\AppData\Local\Continuum\anaconda2\envs\caiman\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\bauerp\AppData\Local\Continuum\anaconda2\envs\caiman\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\bauerp\AppData\Local\Continuum\anaconda2\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 2344, in tile_and_correct_wrapper
    imgs = imread(img_name, key=idxs)
  File "C:\Users\bauerp\AppData\Local\Continuum\anaconda2\envs\caiman\lib\site-packages\skimage\external\tifffile\tifffile.py", line 1234, in imread
    return tif.asarray(**kwargs)
  File "C:\Users\bauerp\AppData\Local\Continuum\anaconda2\envs\caiman\lib\site-packages\skimage\external\tifffile\tifffile.py", line 1487, in asarray
    pages = [pages[k] for k in key]
  File "C:\Users\bauerp\AppData\Local\Continuum\anaconda2\envs\caiman\lib\site-packages\skimage\external\tifffile\tifffile.py", line 1487, in <listcomp>
    pages = [pages[k] for k in key]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-7-8430dfe6faf7> in <module>()
      1 #%% Run piecewise-rigid motion correction using NoRMCorre
----> 2 mc.motion_correct_pwrigid(save_movie=True)
      3 m_els = cm.load(mc.fname_tot_els)
      4 bord_px_els = np.ceil(np.maximum(np.max(np.abs(mc.x_shifts_els)),
      5                                  np.max(np.abs(mc.y_shifts_els)))).astype(np.int)  

~\AppData\Local\Continuum\anaconda2\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_pwrigid(self, save_movie, template, show_template)
    291         if template is None:
    292             print('generating template by rigid motion correction')
--> 293             self = self.motion_correct_rigid()
    294             self.total_template_els = self.total_template_rig.copy()
    295         else:

~\AppData\Local\Continuum\anaconda2\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_rigid(self, template, save_movie)
    241                 nonneg_movie=self.nonneg_movie,
    242                 gSig_filt=self.gSig_filt,
--> 243                 use_cuda=self.use_cuda)
    244             if template is None:
    245                 self.total_template_rig = _total_template_rig

~\AppData\Local\Continuum\anaconda2\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_batch_rigid(fname, max_shifts, dview, splits, num_splits_to_process, num_iter, template, shifts_opencv, save_movie_rigid, add_to_movie, nonneg_movie, gSig_filt, subidx, use_cuda)
   2183                                                                  fname)[-1][:-4] + '_rig_', subidx = subidx,
   2184                                                              num_splits=num_splits_to_process, shifts_opencv=shifts_opencv, nonneg_movie=nonneg_movie, gSig_filt=gSig_filt,
-> 2185                                                              use_cuda=use_cuda)
   2186 
   2187         new_templ = np.nanmedian(np.dstack([r[-1] for r in res_rig]), -1)

~\AppData\Local\Continuum\anaconda2\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correction_piecewise(fname, splits, strides, overlaps, add_to_movie, template, max_shifts, max_deviation_rigid, newoverlaps, newstrides, upsample_factor_grid, order, dview, save_movie, base_name, subidx, num_splits, shifts_opencv, nonneg_movie, gSig_filt, use_cuda)
   2474             dview.map(close_cuda_process, range(len(pars)))
   2475         elif 'multiprocessing' in str(type(dview)):
-> 2476             res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)
   2477         else:
   2478             res = dview.map_sync(tile_and_correct_wrapper, pars)

~\AppData\Local\Continuum\anaconda2\envs\caiman\lib\multiprocessing\pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

IndexError: list index out of range
``

Did I miss some settings or did I do something wrong during the installation?
Thanks, cheers
Pavol

**Comment by epnev** [comment]
@pavolbauer What is your version of tifffile? Due to some changes in the package's API we have pinned its version to 0.12.x 

Please also bear in mind that we do not support python2 on windows.

**Comment by agiovann** [comment]
@pavolbauer you can try to run with the option dview=None to get a more meaningful error

**Comment by epnev** [comment]
The issue should be fixed now (without the need of resorting to .hdf5 files, which are great btw)

**Comment by epnev** [comment]
I'm closing this issue but feel free to reopen if you still have problems.

**Comment by pavolbauer** [comment]
Thank you @epnev. For the record, also using the newest version from the trunk the error appeared, but after converting my tiff to hdf5 as suggested in #242 the motion correction ran through.

**Comment by agiovann** [comment]
@pavolbauer can you share with us us the file?

Thank you

**Comment by epnev** [comment]
@pavolbauer If you used the `pip install .` process to install caiman (and not the `pip install -e .` then a simple git pull might not get you the latest version. See [these instructions](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn) on how to upgrade.

**Comment by pavolbauer** [comment]
@agiovann the file is quite large in order to be shared, but it's a 6000 frame tiff sequence created from single frames using ImageJ (Fiji).
@epnev I've created a new conda environment for the updated version, but did not remove the old one before that. If that might be the issue, I will try to re-install later.

**Comment by pgunn** [comment]
It is never necessary to remove old conda environments (unless you want to save disk space); they're independent from each other (and from the underlying OS).
