### ISSUE TITLE
Add demo fish

### ISSUE THREAD

**Issue by agiovann** [flatironinstitute/CaImAn#248]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

- **Tell us about your operating system (Linux/macOS/Windows) and Python version (2.7/3.x)**

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
an example appears with #402
