### ISSUE TITLE
'>=' not supported between instances of 'list' and 'float'

### ISSUE THREAD

**Issue by xhonial** [flatironinstitute/CaImAn#252]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

- **Tell us about your operating system (Linux/macOS/Windows) and Python version (2.7/3.x)**

Windows 10, 64 bit

- **Describe the issue that you are experiencing**

Once I run demo_pipline_cnmfE.py with my data, I receive an error at component valuation portion of the code. 
![untitled](https://user-images.githubusercontent.com/28151273/40201623-88e7ca5c-59ed-11e8-9531-030d174cdbba.png)

- **Copy error log below**
![untitled](https://user-images.githubusercontent.com/28151273/40201653-ac98c046-59ed-11e8-96f6-a97b955685ef.png)

- **If you're not reporting an error, type your message below**

**Comment by xhonial** [comment]
Hi,
Thank you for your quick response. How can I change the code in the module and have the change executed in the demo files? I've changed the code as you suggested in components_evaluation.py, but the change doesn't affect the demo code even after shutting down the kernel.

Best,
Xhoni

**Comment by pgunn** [comment]
If you were to change this yourself you'd need to do a "pip uninstall caiman" and then redo the "pip install ." for it to take effect.

(my comment was meant to start a conversation internally on how to fix it for the longer term, but if this solves your issue immediately, that's great)

**Comment by xhonial** [comment]
Okay thank you very much. I did what you said and I got another error now. 
![untitled](https://user-images.githubusercontent.com/28151273/40206487-44144ff2-59fe-11e8-8d43-5b69e350d2c6.png)

Best,
Xhoni

**Comment by epnev** [comment]
This is probably the same error. But it's strange. These errors should not be happening in the first place.

**Comment by epnev** [comment]
I believe that the error appears because you actually have no components to evaluate. This is easy to fix but you will need to check in your script why it's happening.

**Comment by xhonial** [comment]
That could be possible. If that's the case, what changes should I do to the code to make it work?

**Comment by epnev** [comment]
I'd refer you to the previous issue you opened https://github.com/flatironinstitute/CaImAn/issues/244 
In the meantime I'll make changes in the code to make sure there is no error message there.

**Comment by xhonial** [comment]
Okay thank you very much. Also this is a little unrelated, but when I ran the same script on the data_endoscope file, it detected 3 neurons. When I ran it last week, it detected 43 neurons. Was that a purposeful change?

**Comment by pgunn** [comment]
@epnev Can we figure out a way to provide a more helpful error message in this case?

**Comment by xhonial** [comment]
I reinstalled caiman, and it still gave me 3 accepted components and no rejected components on data_endoscope. Perhaps I'm missing something?

**Comment by epnev** [comment]
@pgunn yup, just pushed it on dev.

**Comment by epnev** [comment]
@xhonial I don't know what might be wrong. We tested on multiple machines here.

**Comment by xhonial** [comment]
Thank you both for the amount of help here. As I reinstalled the repository on my pc, I tried to run the code on my files, and I received an error on the following portion. 
![untitled](https://user-images.githubusercontent.com/28151273/40245128-b346ac50-5a92-11e8-8810-429c85a5e099.png)

I changed dview=None and this is the error I received:
![untitled1](https://user-images.githubusercontent.com/28151273/40245150-c6048ace-5a92-11e8-8c3e-15fb73fa5203.png)

Thank you again for the help, and sorry for bugging you guys. 

Best,
Xhoni

**Comment by xhonial** [comment]
Hi, 
I uninstalled and reinstalled anaconda and the repository on two computers that are windows 10, 64-bit and this is how the contour plot of the accepted and rejected components look like for the demo data:

![untitled](https://user-images.githubusercontent.com/28151273/40254215-9660c03a-5ab0-11e8-81f6-782d14fad164.png)

Best,
Xhoni

**Comment by pgunn** [comment]
I will attempt to reproduce the issue locally to see if I can get the results you're getting.

**Comment by xhonial** [comment]
This might be rather silly,but perhaps it might be the way I installed caimanmanager.py. I have tested the program on two different computers using windows 10, 64-bit. After doing pip install . , I referred to another issue #217, and installed it using python C:\\Users\user\Anaconda3\envs\caiman\bins\caimanmanager.py install. Maybe this isn't the correct way of installing it?

Best,
Xhoni

**Comment by pgunn** [comment]
Hi,
That is indeed a workable way to do the data install on Windows. If you do a lot of extra integration work with conda on windows, this would not be necessary, but the extra work is not documented and not fun. We're working on reproducing the issues you're having locally.

**Comment by epnev** [comment]
@xhonial Just to make sure: Are you running `demo_pipeline` or `demo_pipeline_cnmfE`?

**Comment by xhonial** [comment]
demo_pipeline_cnmfE

**Comment by pgunn** [comment]
I just realised you're probably talking about the Jupyter notebooks, not the demos/general/demo_pipeline_cnmfE, right?

**Comment by xhonial** [comment]
Yes

**Comment by pgunn** [comment]
We have reproduced the issue locally; thank you for your bug report. We're looking into it.

**Comment by pgunn** [comment]
#260

**Comment by pgunn** [comment]
xhonial: The above pull request fixes the issue in our dev branch, and I expect it will be pulled forward into master soon. If you'd like to grab the new version of the notebook, you can grab it from there.

Cheers,
Pat

**Comment by xhonial** [comment]
Alright thank you guys very much. You've been extremely helpful!
