### ISSUE TITLE
Windows/Python3/Spyder - Issue with demo_pipeline_cnmfE.py

### ISSUE THREAD

**Issue by pgunn** [flatironinstitute/CaImAn#256]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

- **Tell us about your operating system (Linux/macOS/Windows) and Python version (2.7/3.x)**
Windows 10, Python 3.x (Spyder)

- **Describe the issue that you are experiencing**
When stepping through demo_pipeline_cnmfE under Spyder, the motion correction cell runs, but it throws an exception in the asynchronous save_place_holder code.

- **Copy error log below**
0
saving mmap of D:\Users\pgunn\caiman_data\example_movies\data_endoscope.tif
**** MOVIE NOT SAVED BECAUSE num_splits is not None ****
** Startting parallel motion correction **
** Finished parallel motion correction **
Adding to movie 2.65565
0
saving mmap of D:\Users\pgunn\caiman_data\example_movies\data_endoscope.tif
** Startting parallel motion correction **
** Finished parallel motion correction **
Traceback (most recent call last):

  File "<ipython-input-11-738f4e5f4235>", line 74, in <module>
    dview=dview)

  File "D:\Users\pgunn\AppData\Local\Continuum\miniconda3\envs\caiman\lib\site-packages\caiman\mmapping.py", line 136, in save_memmap_each
    fnames_new = dview.map_async(save_place_holder, pars).get(4294967)

  File "D:\Users\pgunn\AppData\Local\Continuum\miniconda3\envs\caiman\lib\multiprocessing\pool.py", line 644, in get
    raise self._value

AttributeError: 'NoneType' object has no attribute 'flush'

- **If you're not reporting an error, type your message below**

![screenshot 2018-05-21 at 16 28 18](https://user-images.githubusercontent.com/829791/40328601-ed2b98e8-5d14-11e8-98af-6c52d5eb7649.png)

**Comment by epnev** [comment]
@pgunn is this resolved?

**Comment by pgunn** [comment]
The issue does not occur with dview=None.
