### ISSUE TITLE
Does non-rigid motion correction in this demo script use results from rigid or original files?

### ISSUE THREAD

**Issue by akls** [flatironinstitute/CaImAn#258]
https://github.com/flatironinstitute/CaImAn/blob/f76d8b6e6d19efb9f10c57817a6f167d3d19db11/demos/general/demo_pipeline_cnmfE.py#L80

In the demo script for "motion_correct_oneP_nonrigid(...)", it does use fnames as inputs. But I think it should use the files generated by the previous rigid motion correction (which are stored in filename_reorder = mc.fname_tot_rig).

**Comment by epnev** [comment]
You can do it directly on the original file. It will still perform rigid motion correction to determine the template the range of allowed shifts. I have not seen big differences by doing explicitly rigid motion correction first.

**Comment by akls** [comment]
Ok, but shouldn't "motion_correct_oneP_rigid" then only be executed if "do_motion_correction_nonrigid = False"? Otherwise it appears to run rigid motion correction twice. In the explicit call of "motion_correct_oneP_rigid" and then again for nonrigid.

**Comment by epnev** [comment]
Yes, I guess we were being extra cautious with this one. I'll let @agiovann comment on it

**Comment by agiovann** [comment]
Dear @akls ,

the situation is a little more subtle. What is very important for motion correction is to have **a good template**. Starting from a rigidly motion corrected file is actually worst for non-rigid for some technical reasons (you can read the paper https://www.sciencedirect.com/science/article/pii/S0165027017302753 for more details). So the important factor here is whether you pass as input a template or not. @epnev I think we should be more detailed about this in the caiman paper.  So, the answer is no to your question, the input must be the raw files but you need to pass as input the template computed with the rigid. Let me know if this makes sense

**Comment by akls** [comment]
Thanks for the clarification @agiovann ! That makes a lot of sense.
