### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by xhonial** [flatironinstitute/CaImAn#261]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

- **Tell us about your operating system (Linux/macOS/Windows) and Python version (2.7/3.x)**
Win 10, 64-bit. Python 3.6

- **Describe the issue that you are experiencing**
I was running demo_pipeline_cnmfE with my data and I received an error on the following portion of the code:
![untitled](https://user-images.githubusercontent.com/28151273/40452398-b0f38a92-5eaf-11e8-8326-6a0bf8408378.png)

The error was: 
![untitled1](https://user-images.githubusercontent.com/28151273/40452411-b76f1a4e-5eaf-11e8-8680-4f4f0cd4a827.png)

Also, this is from the demo file under the demo/general folder

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by agiovann** [comment]
which demo file? Can you give the exact name? Can you also check what the fname_new variable value is? Thx

**Comment by xhonial** [comment]
Oh sorry, this was my data. I meant to say demo_pipeline_cnmfE is under the demo/general folder. Sorry for the misunderstanding!

**Comment by xhonial** [comment]
Hi, I printed the fname_new variable and the answer that I received is ['C:\\Users\\AllenLi\\caiman_data\\example_movies\\memmap_0000_d1_480_d2_752_d3_1_order_C_frames_2000_.mmap'] .
I don't know if this is what you were looking for.

**Comment by pgunn** [comment]
Hi,
Can you do the following in a python interactive mode in your python environment and paste the results into your reply?

```
import os
import sys
os.environ['PROCESSOR_ARCHITECTURE']
sys.maxsize > 2**32
```

**Comment by xhonial** [comment]
Hi,
After typing os.environ['PROCESSOR_ARCHITECTURE'], I got AMD64 as a result. After typing sys.maxsize > 2**32 I got True as a result.

**Comment by pgunn** [comment]
Hi,
After looking at some details of the functionality of the mmap() facility on Windows, I believe there may be a limit on how much memory can be mapped at a time on that platform based on the Windows swap settings. In the system settings for your version of Windows there should be a pagefile size option:

http://www.tomshardware.com/faq/id-2864547/manage-virtual-memory-pagefile-windows.html

If you can increase the maximum size for paging to 32 gigabytes (or more), it might resolve the issue; please try it and let us know how it goes (if it solves the problem we will want to add it to the documentation).

If that does not help, if you can share your data (just enough to reproduce the problem) and your scripts with us, we would like to arrange to reproduce the issue locally. It'd probably be easiest if you were to hop on https://gitter.im/agiovann/Constrained_NMF to chat with us and make the arrangements in private.

If that's not possible we could think about another way to debug this.

Please try the pagefile adjustment and let us know.

**Comment by xhonial** [comment]
Hey,
I just ran the code with a virtual ram of 64 gigabytes (my ram already was 32 gigabytes), and it keeps giving the same problem. How can I share my data and scripts with you guys in order to reproduce the problem? I can also start a private channel with whomever to make the arrangements. Thank you guys so much for helping me out.

**Comment by pgunn** [comment]
If you can hop onto gitter (the chat link I mentioned above), we'll talk through setting up such a share. However, we're going to all be occupied until Tuesday with a company event; we'll likely have to pick things up then (although I'm going to experiment with mmap() on Windows starting now to see how large a file I can mmap).

**Comment by xhonial** [comment]
Alright will do!

**Comment by agiovann** [comment]
@xhonial just to make sure, you set dview=None, right? 
In the meanwhile can you add a debug message soon before line 187 in mmapping,py?
print([fname_tot, d, tot_frames])
after restarting the kernel retry

THank you for the valuable feedback

**Comment by xhonial** [comment]
Hi, 
I was working yesterday with @pgunn and I did the same thing. fname_tot is C:\Users\AllenLi\caiman_data\example_movies\memmap__d1_480_d2_752_d3_1_order_C_frames_2000_.mmap. d is 360960 and tot_frames is 2000.

**Comment by agiovann** [comment]
ok, thank you. Let's try to reproduce locally.

**Comment by agiovann** [comment]
Dear @xhonial @j-friedrich we had a deeper look at your file. It is a pretty exceptional situation you have there: the movie you collected is different from what we are used to. It seems that there is strong non-rigid movement in x and y but also unfortunately along the z axis. Moreover some stains on the cover glass that are not moving along with the brain confuse the algorithm. In order to be able to use CaImAn we would need to customize it. My suggestion is, if your experiment allows it, to stabilize the preparation at surgery time. Otherwise, I cannot see CaImAn working on it on the short term. Thank you for your feedback, based on it we will in any case change some parameters in the demo (for instance some parameters like max_shift were not clearly exposed). Sorry for not being able to further help you.

**Comment by xhonial** [comment]
Thank you @agiovann for the later issue, but in regards to the original issue I posted in this thread, I never received a possible solution. Even with other data sets, that are much clearer and have less movement, the OSError: [Errno 22] Invalid argument, still is present.

**Comment by agiovann** [comment]
@xhonial  we would need the dataset that causes that error, can you share that one with @pgunn? The file you passed does not seem to have that problem

**Comment by xhonial** [comment]
Hi the error only occurred with my data. I also ran it with demo_pipeline_cnmfE.py in the demos/general folder rather than demos/notebooks

**Comment by pgunn** [comment]
PR 272 addresses the memmap (overflow) issue.

**Comment by pgunn** [comment]
I'm closing this issue - xhonial, let's chat on gitter on any remaining issues you have (I believe you hit another problem after this was solved, but you should check again with a fresh checkout)
