### ISSUE TITLE
Joining C-format mmap movie chunks into a a single large memmap file

### ISSUE THREAD

**Issue by Rylan-L** [flatironinstitute/CaImAn#262]
- **Tell us about your operating system (Linux/macOS/Windows) and Python version (2.7/3.x)**
OS= Windows 10; Python 3.6

- **Describe the issue that you are experiencing**
Using the demo_pipeline notebook as a guide, I'm encountering an error with the mmap-ing to C format step that occurs just prior to segmentation using my data. 

Right now the code works to generate mmaps (in C format) for each movie portion/chunk following motion correction of as a movie chain. I can see that these individual mmap files are saved on the hard drive for each movie chunk. However, when the code attempts to join them into a single, large mmap file, there is an error that seems to arise at the numpy.mmap step (below). 

The command that generates this is:
fnames = mc.fname_tot_els   # name of the pw-rigidly corrected file.
border_to_0 = bord_px_els     # number of pixels to exclude
fname_new = cm.save_memmap(fnames, base_name='memmap_', order = 'C',
                           border_to_0 = bord_px_els,n_chunks=500) # exclude borders

- **Copy error log below**
![caiman_mmaperror](https://user-images.githubusercontent.com/38474907/40455668-e460df5e-5ea2-11e8-8529-1d4a9a25457d.jpg)

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
Seems pretty similar to #261 that was just opened. We'll take a look. @agiovann @pgunn

**Comment by Rylan-L** [comment]
@pgunn Yes, looks very similar to #261 . Just in case it's helpful, when I type the instructed commands into python, I get the following: 
os.environ['PROCESSOR_ARCHITECTURE']
**'AMD64'**
sys.maxsize > 2**32
**True**

**Comment by agiovann** [comment]
@Rylan-L  just to make sure, you set dview=None, right? 
In the meanwhile can you add a debug message soon before line 187 in mmapping,py?
print([fname_tot, d, tot_frames])
after restarting the kernel retry

THank you for the valuable feedback

**Comment by epnev** [comment]
@Rylan-L We believe that this is addressed now. Please update the code and re-install (see instructions [here](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn) ) and let us know if the issue persists.
