### ISSUE TITLE
Template contains NaNs

### ISSUE THREAD

**Issue by Cumol** [flatironinstitute/CaImAn#277]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**
Python 3.6 on Ubuntu running Python from command line `python demo_pipeline.py`

- **Describe the issue that you are experiencing**
Pipeline gets stuck in/after motion correction even though it ran with another dataset from the same experiment.

- **Copy error log below**
```
penCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvDestroyAllWindows, file /feedstock_root/build_artefacts/opencv_1490907195496/work/opencv-3.2.0/modules/highgui/src/window.cpp, line 577
/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/motion_correction.py:2397: RuntimeWarning: Mean of empty slice
  return shift_info, idxs, np.nanmean(mc, 0)
** Finished parallel motion correction **
/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/lib/function_base.py:3858: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
Traceback (most recent call last):
  File "demo_pipeline.py", line 135, in <module>
    mc.motion_correct_pwrigid(save_movie=True)
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/motion_correction.py", line 318, in motion_correct_pwrigid
    'Template contains NaNs, something went wrong. Reconsider the parameters')
Exception: Template contains NaNs, something went wrong. Reconsider the parameters
```

**Comment by epnev** [comment]
@Cumol Do you have the same problem if you do rigid motion correction?

**Comment by Cumol** [comment]
@epnev do you mean rigid but not piecewise?

**Comment by epnev** [comment]
@Cumol Yes.`mc.motion_correct_rigid`

**Comment by Cumol** [comment]
The rigid motion correction seems to work, it just stops at the `mc.fname_tot_els`because it probably doesnt have that value.

```
** Finished parallel motion correction **
0.193359
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/demo_pipeline.py in <module>()
    134 #%% Run piecewise-rigid motion correction using NoRMCorre
    135 mc.motion_correct_rigid(save_movie=True)
--> 136 m_els = cm.load(mc.fname_tot_els[0])
    137 bord_px_els = np.ceil(np.maximum(np.max(np.abs(mc.x_shifts_els)),
    138                                  np.max(np.abs(mc.y_shifts_els)))).astype(np.int)

AttributeError: 'MotionCorrect' object has no attribute 'fname_tot_els'
```

**Comment by epnev** [comment]
@Cumol Yes. You can replace that with `mc.fname_tot_rig` and it will go through. In general I suggest you should build some familiarity with the code before running it from the command line. This is a black box approach so if you change a thing you'd need to see your changes propagate through and the results are reasonable. 

I'll take a look at your error see how I can prevent it. If your data looks fine after rigid motion correction you should stick to that. If not, you can try using piecewise rigid motion correction with increased values for the parameters `strides` and `overlaps`. This will use greater patch size and will add more robustness.

**Comment by epnev** [comment]
@Cumol This is fixed now. The nans appear when motion correcting because there is no signal to be inferred at the boundaries. For rigid motion correction this is not a problem because the boundaries are being removed in the subsequent steps of the pipeline. However for non-rigid this can appear in some interior part of the FOV if your patch size/motion ratio is too low and there is not enough overlap from neighboring patches. Increasing the size of the patch should fix this problem as I explained in my previous message.

However, you can now also set `border_nan = 'copy'` or `border_nan = 'min'` when creating the motion correction object and it will prevent this behavior.
