### ISSUE TITLE
Running CNMF on portion of the file

### ISSUE THREAD

**Issue by Cumol** [flatironinstitute/CaImAn#282]
I need to run CNMF on a part of the video to get components and then run it on the whole file to get traces etc.

In my situation I have a stimulus which activates 95% of the neurons, leading to a worse identification of neurons that are close to each other. I already verified that this is the case by running CNMF only on the part of the video that does not contain the stimulus.

The current options are only resaving the portion as hdf5, running CNMF and then running it again on the whole file. But it might be easier to have the option to pick the frames used for CNMF in the function itself.

**Comment by agiovann** [comment]
@Cumol you can try to pull the new code, we have added an argument called slices to save_memmap. It works exactly as the slice command (https://www.programiz.com/python-programming/methods/built-in/slice). For instance, to only save the first one thousand frames in save_memmap use the parameter slices = slice(0,1000). Let me know if this solves your issue.

**Comment by agiovann** [comment]
@Cumol please close the issue is the PR solves your problem please

**Comment by Cumol** [comment]
@agiovann Just tested this and it works. Thank you!
