### ISSUE TITLE
Avi files won't go through pre-processing

### ISSUE THREAD

**Issue by jordanfarrell** [flatironinstitute/CaImAn#291]
MacOS (Yosemite), Python 3.6, Jupyter Notebook.

**I'm having difficulties getting through the pre-processing phase with avi files. If I convert to hdf5 or tiff, I have no problem getting through the entire pipeline , but this increases the file sizes significantly and slows the process. The avi files I'm using are generated using the UCLA miniscope. Do I have to convert to a different format or is it possible to use avi's?** 

-Here is the error message:
 ---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-4-2a8c0888ee53> in <module>()
      3     Y = cm.load(fls[0], subindices = slice(0,initbatch,None)).astype(np.float32).resize(1. / ds_factor, 1. / ds_factor)
      4 else:
----> 5     Y =  cm.load(fls[0], subindices = slice(0,initbatch,None)).astype(np.float32)
      6 
      7 if mot_corr:                                        # perform motion correction on the first initbatch frames

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/base/movies.py in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype)
   1234         elif extension == '.avi':  # load avi file
   1235             if subindices is not None:
-> 1236                 raise Exception('Subindices not implemented')
   1237             cap = cv2.VideoCapture(file_name)
   1238             try:

Exception: Subindices not implemented

Thanks!

**Comment by jordanfarrell** [comment]
Hi Andrea, thanks for the quick response. Having the option to run .avi's through the pipeline would be greatly appreciated. Looking forward to that update! Thanks.

**Comment by epnev** [comment]
@jordanfarrell You are referring to the online pipeline, right?

**Comment by jordanfarrell** [comment]
Yes, that error message was from the online pipeline, however, I get the same message ("Subindicies not implemented") using both the online and full pipeline - only when using .avi's.

**Comment by epnev** [comment]
Can you specify where the error occurs when using the full pipeline?

**Comment by jordanfarrell** [comment]
It occurs at the first step in motion correction - when the movie is loaded and "subindices=" is specified. This is the error for the full pipeline:

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-5-55b1dad95e0e> in <module>()
      1 # first we create a motion correction object with the parameters specified
----> 2 min_mov = min(cm.load(fname[0], subindices=range(200)).min(),0)
      3         # this will be subtracted from the movie to make it non-negative
      4 
      5 mc = MotionCorrect(fname[0], min_mov,

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/base/movies.py in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype)
   1234         elif extension == '.avi':  # load avi file
   1235             if subindices is not None:
-> 1236                 raise Exception('Subindices not implemented')
   1237             cap = cv2.VideoCapture(file_name)
   1238             try:

Exception: Subindices not implemented

Thanks!

**Comment by epnev** [comment]
I see, thanks. I'm looking into it.

**Comment by jordanfarrell** [comment]
Much appreciated!

**Comment by epnev** [comment]
@jordanfarrell We made the required changes and believe processing of .avi files should be feasible without the need to convert to a different file type. Let us know if you still have issues.

**Comment by epnev** [comment]
You're welcome!

**Comment by akim5651** [comment]
I have been encountering this error trying to run .avi files (Spyder, OSX, git up-to-date)
This is after loading an avi file labeled: 'msCam1.avi' in the example_movies folder.

INPUT:
```
fnames = ['msCam1.avi']  # filename to be processed
fnames = [download_demo(fnames[0])]  # download file if not already present
filename_reorder = fnames
fr = 10                          # movie frame rate
decay_time = 0.4                 # length of a typical transient in seconds

# motion correction parameters
motion_correct = True            # flag for motion correction
pw_rigid = False                 # flag for pw-rigid motion correction

gSig_filt = (3, 3)   # size of filter, in general gSig (see below),
#                      change this one if algorithm does not work
max_shifts = (5, 5)  # maximum allowed rigid shift
strides = (48, 48)   # start a new patch for pw-rigid motion correction every x pixels
overlaps = (24, 24)  # overlap between pathes (size of patch strides+overlaps)
# maximum deviation allowed for patch with respect to rigid shifts
max_deviation_rigid = 3
border_nan = 'copy'

mc_dict = {
    'fnames': fnames,
    'fr': fr,
    'decay_time': decay_time,
    'pw_rigid': pw_rigid,
    'max_shifts': max_shifts,
    'gSig_filt': gSig_filt,
    'strides': strides,
    'overlaps': overlaps,
    'max_deviation_rigid': max_deviation_rigid,
    'border_nan': border_nan
}
```
OUTPUT:
```
opts = params.CNMFParams(params_dict=mc_dict)
     2662495 [utils.py:       download_demo():93][23506] File msCam1.avi already downloaded
     2662497 [params.py:                 set():780][23506] Changing key fnames in group data from None to ['/Users/andrew/caiman_data/example_movies/msCam1.avi']
     2662498 [params.py:                 set():780][23506] Changing key fr in group data from 30 to 10
     2662499 [params.py:                 set():780][23506] Changing key max_shifts in group motion from (6, 6) to (5, 5)
     2662500 [params.py:                 set():780][23506] Changing key gSig_filt in group motion from None to (3, 3)
     2662500 [params.py:                 set():780][23506] Changing key strides in group motion from (96, 96) to (48, 48)
     2662501 [params.py:                 set():780][23506] Changing key overlaps in group motion from (32, 32) to (24, 24)
Traceback (most recent call last):

  File "<ipython-input-34-0c91f945f8ec>", line 33, in <module>
    opts = params.CNMFParams(params_dict=mc_dict)

  File "/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/params.py", line 723, in __init__
    self.data['dims'] = get_file_size(self.data['fnames'])[0]

  File "/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py", line 945, in get_file_size
    dims, T = get_file_size(file_name[0], var_name_hdf5=var_name_hdf5)

  File "/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py", line 917, in get_file_size
    dims[0] = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))

TypeError: 'tuple' object does not support item assignment
```
How may I bypass this?

**Comment by agiovann** [comment]
Hello,

if you try 

cm.load(avi_file_name).shape

what do you get?

Cheers

Andrea

**Comment by agiovann** [comment]
try set 

dims = np.array(dims)

It seems tuples are not accepted

**Comment by akim5651** [comment]
I got this message:
```
dims = np.array(dims)
Out: Traceback (most recent call last):

  File "<ipython-input-10-f2aec2a0b2c3>", line 1, in <module>
    dims = np.array(dims)

NameError: name 'dims' is not defined
```

Could you confirm if I am using the pipeline correctly - in that, I have .avi files, labeled 'msCam1.avi', 'msCam2.avi', etc. (UCLA miniscope recordings). I place these avi files into the 'example_movies' folder in caiman_data folder. And then down the pipeline (using demo_pipeline_cnmfE.py), for starters I would swap in the filename I want to analyze:
`  fnames = ['msCam1.avi']  # filename to be processed`

Am I correct thus far? Appreciate your patience, as I am not well-versed in Python yet. The tuple error was not reconciled, and so I'm wondering how folks above got their .avi files to work. Thanks for your help thus far.

**Comment by agiovann** [comment]
@akim5651 I apologize for not specifying: you should add it just before

File "/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py", line 917, in get_file_size
    dims[0] = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))

it is a hack but it would allow me to see if the issue is simply tuple assignment

Best,

**Comment by akim5651** [comment]
Thank you for the detailed instructions. Putting that before line 917, as described, fixed the issue and the code runs without error. 
Quick question - How would I be able to analyze multiple videos (e.g. 'msCam1.avi', 'msCam2.avi', and 'msCam3.avi')? For this example, would I place those 3 video files into the caiman_data directory and list those file names in fnames[ ]? Or should I concatenate them and them run them as one file? Thanks again @agiovann .

**Comment by agiovann** [comment]
No troubles. In principle you should just be able to do so by adding the paths of the files into the fnames list, you do not even need to move them.

**Comment by agiovann** [comment]
Could you please open a Pull Request for the change you just added?

thank you
