### ISSUE TITLE
CNMF hangs without finishing.

### ISSUE THREAD

**Issue by lyprince** [flatironinstitute/CaImAn#301]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**

Using Ubuntu 16.04, python version 3.6.3, running code in jupyter notebook

- **Describe the issue that you are experiencing**

When running CNMF with method_init = 'corr_pnr', it reaches a point where it hangs without finishing.  I've left it running overnight a few times and it hasn't finished, and I've altered parameters so that no neurons are found and it does finish then.

The data in question is size : (4714, 472, 463), and I use these parameters:

p                   = 1     # Order of autoregressive system
K                   = None  # upper bound on number of components per patch (in general None)
gSig                = 7     # width of 2D Gaussian kernel, which approximates a neuron
gSiz                = 22    # average diameter of a neuron, generally gSig*3 + 1
merge_thresh        = 0.7   # merging threshold, max correlation allowed
rf                  = 80    # half-size of the patches in pixels. e.g., if rf=40, patches are 80x80
stride_cnmf         = 40    # Overlap between patches. Keep it at least as large as gSiz
tsub                = 2     # Temporal downsampling factor
ssub                = 2     # Spatial downsampling factor
Ain                 = None  # Initialised components. Can pass as boolean vector if wanted
low_rank_background = None  # None leaves background of each patch intact, True performs low rank approximation
gnb                 = -1    # Number of background components if > 0, elif -2: return BG as b and W, elif -1 return full rank BG as B, elif 0, don't return BG
nb_patch            = -1    # Number of background components per patch
min_corr            = 0.8   # minimum peak value from correlation image
min_pnr             = 10    # minimum peak to noise ratio from PNR image
ssub_B              = 2     # additional spatial downsampling for background
ring_size_factor    = 1.4   # radius of ring is gSiz*ring_size_factor

- **Copy error log below**

After interrupting the kernel this is the output:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-15-b442f06a74c2> in <module>()
----> 1 cnm.fit(Y)

~/anaconda2/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images)
    569                                                                      gnb=self.gnb, border_pix=self.border_pix,
    570                                                                      low_rank_background=self.low_rank_background,
--> 571                                                                      del_duplicates=self.del_duplicates)
    572 
    573             # options = CNMFSetParms(Y, self.n_processes, p=self.p, gSig=self.gSig, K=A.shape[

~/anaconda2/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, options, rf, stride, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates)
    264     if dview is not None:
    265         if 'multiprocessing' in str(type(dview)):
--> 266             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    267         else:
    268             try:

~/anaconda2/envs/caiman/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    636 
    637     def get(self, timeout=None):
--> 638         self.wait(timeout)
    639         if not self.ready():
    640             raise TimeoutError

~/anaconda2/envs/caiman/lib/python3.6/multiprocessing/pool.py in wait(self, timeout)
    633 
    634     def wait(self, timeout=None):
--> 635         self._event.wait(timeout)
    636 
    637     def get(self, timeout=None):

~/anaconda2/envs/caiman/lib/python3.6/threading.py in wait(self, timeout)
    549             signaled = self._flag
    550             if not signaled:
--> 551                 signaled = self._cond.wait(timeout)
    552             return signaled
    553 

~/anaconda2/envs/caiman/lib/python3.6/threading.py in wait(self, timeout)
    297             else:
    298                 if timeout > 0:
--> 299                     gotit = waiter.acquire(True, timeout)
    300                 else:
    301                     gotit = waiter.acquire(False)

KeyboardInterrupt:

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@lyprince You seem to be using a python 3 environment from a python 2 anaconda distribution. This might be causing problems with parallel processing. 

Try setting `backend="ipyparallel"` when setting up the cluster (see [here](https://github.com/flatironinstitute/CaImAn/blob/master/demos/general/demo_pipeline_cnmfE.py#L101)) to see if the error persists, or reduce the number of processes you're using.

**Comment by lyprince** [comment]
Thanks, it no longer hangs.

**Comment by epnev** [comment]
glad to hear. Just curious, which option made it work for you?

**Comment by lyprince** [comment]
backend='ipyparallel' worked for me,

What are the differences between the options, and why is there a problem with python 3 parallel processing in a  python 2 anaconda distribution?

**Comment by lyprince** [comment]
@pgunn thanks!
