### ISSUE TITLE
After running CNMF: "ValueError: indices and data should have the same size"

### ISSUE THREAD

**Issue by lyprince** [flatironinstitute/CaImAn#302]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**

Using Ubuntu 16.04, python version 3.6.3, running code in jupyter notebook

- **Describe the issue that you are experiencing**

After running CNMF with method_init = 'corr_pnr', it does not complete transforming patches into a full matrix due to a problem with indexing error. I'm not sure if this is just because no neurons have been found, but based on the correlation and pnr images it looks as if it should have done. The error is the same with dview = None

The data in question is size : (4714, 472, 463), and I use these parameters:

p = 1 # Order of autoregressive system
K = None # upper bound on number of components per patch (in general None)
gSig = 7 # width of 2D Gaussian kernel, which approximates a neuron
gSiz = 22 # average diameter of a neuron, generally gSig3 + 1
merge_thresh = 0.7 # merging threshold, max correlation allowed
rf = 80 # half-size of the patches in pixels. e.g., if rf=40, patches are 80x80
stride_cnmf = 40 # Overlap between patches. Keep it at least as large as gSiz
tsub = 2 # Temporal downsampling factor
ssub = 2 # Spatial downsampling factor
Ain = None # Initialised components. Can pass as boolean vector if wanted
low_rank_background = None # None leaves background of each patch intact, True performs low rank approximation
gnb = -1 # Number of background components if > 0, elif -2: return BG as b and W, elif -1 return full rank BG as B, elif 0, don't return BG
nb_patch = -1 # Number of background components per patch
min_corr = 0.8 # minimum peak value from correlation image
min_pnr = 10 # minimum peak to noise ratio from PNR image
ssub_B = 2 # additional spatial downsampling for background
ring_size_factor = 1.4 # radius of ring is gSizring_size_factor

- **Copy error log below**

(4714, 472, 463)
using 8 processes
using 4000 pixels per process
using 5000 block_size
(160, 160)
You may think that it went well but reality is harsh
3036.4020771980286
Transforming patches into full matrix
Skipped %d Empty Patch 0
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-b442f06a74c2> in <module>()
----> 1 cnm.fit(Y)

~/anaconda2/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images)
    569                                                                      gnb=self.gnb, border_pix=self.border_pix,
    570                                                                      low_rank_background=self.low_rank_background,
--> 571                                                                      del_duplicates=self.del_duplicates)
    572 
    573             # options = CNMFSetParms(Y, self.n_processes, p=self.p, gSig=self.gSig, K=A.shape[

~/anaconda2/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, options, rf, stride, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates)
    390         idx_ptr_B = np.cumsum(np.array(idx_ptr_B))
    391         B_tot = scipy.sparse.csc_matrix(
--> 392             (b_tot, idx_tot_B, idx_ptr_B), shape=(d, count_bgr))
    393     else:
    394         B_tot = scipy.sparse.csc_matrix((d, count_bgr), dtype=np.float32)

~/anaconda2/envs/caiman/lib/python3.6/site-packages/scipy/sparse/compressed.py in __init__(self, arg1, shape, dtype, copy)
     96             self.data = np.asarray(self.data, dtype=dtype)
     97 
---> 98         self.check_format(full_check=False)
     99 
    100     def getnnz(self, axis=None):

~/anaconda2/envs/caiman/lib/python3.6/site-packages/scipy/sparse/compressed.py in check_format(self, full_check)
    165         # check index and data arrays
    166         if (len(self.indices) != len(self.data)):
--> 167             raise ValueError("indices and data should have the same size")
    168         if (self.indptr[-1] > len(self.indices)):
    169             raise ValueError("Last value of index pointer should be less than "

ValueError: indices and data should have the same size

- **If you're not reporting an error, type your message below**

**Comment by agiovann** [comment]
@j-friedrich I seem to remember you looked into the emtpy patch problem. Is that correct?  Was it solved? Can you look into this one?

**Comment by j-friedrich** [comment]
@lyprince excuse the delay. I finally managed to reproduce the error. Some downsampling issue. You can set `ssub=1` for now and I'll keep you posted once the issue has been solved.

**Comment by j-friedrich** [comment]
Ok, resolved the issue. Fixed it in master and dev. At least my reproduced error is gone. Reopen in the unlikely event that the issue still persists for your data.
