### ISSUE TITLE
Errors in Motion Correction when running .avi files in pipeline

### ISSUE THREAD

**Issue by jtalley24** [flatironinstitute/CaImAn#316]
- Windows 10, Python 3, Jupyter Notebook

- I am trying to run this pipeline with Miniscope data.  Miniscope saves videos in the .avi format, and I receive the following error in the Motion Correction section when trying to run the pipeline:

- ---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-8-7a08fdda7601> in <module>()
      6                                    dview=dview,
      7                                    splits_rig=splits_rig,
----> 8                                    save_movie=not(do_motion_correction_nonrigid)
      9                                    )
     10 

~\Anaconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_oneP_rigid(filename, gSig_filt, max_shifts, dview, splits_rig, save_movie)
    473     '''
    474     min_mov = np.array([cm.motion_correction.high_pass_filter_space(
--> 475         m_, gSig_filt) for m_ in cm.load(filename[0], subindices=range(400))]).min()
    476     new_templ = None
    477 

~\Anaconda3\envs\caiman\lib\site-packages\caiman\base\movies.py in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype)
   1234         elif extension == '.avi':  # load avi file
   1235             if subindices is not None:
-> 1236                 raise Exception('Subindices not implemented')
   1237             cap = cv2.VideoCapture(file_name)
   1238             try:

Exception: Subindices not implemented

- Any help is greatly appreciated

**Comment by epnev** [comment]
@jtalley24 Support for .avi files was implemented as a response to issue https://github.com/flatironinstitute/CaImAn/issues/291
You should update to the latest version (see instructions on how to do this)

**Comment by jtalley24** [comment]
Could you provide a link to the relevant instructions?

**Comment by epnev** [comment]
It appears when you click to open a new issue but you deleted it. check the wiki
