### ISSUE TITLE
Error running caimanmanager.py install

### ISSUE THREAD

**Issue by hluetck** [flatironinstitute/CaImAn#317]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**
macOS 10.13.5, Python 3.6

- **Describe the issue that you are experiencing**
I did a fresh install of CaImAn using the pip installer. After activating the environment and running `caimanmanager.py install` in my home directory, I get the error below.

- **Copy error log below**

Traceback (most recent call last):
  File "/Users/Henry/miniconda3/envs/caiman/bin/caimanmanager.py", line 13, in <module>
    from caiman.paths import caiman_datadir
  File "/Users/Henry/miniconda3/envs/caiman/lib/python3.6/site-packages/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "/Users/Henry/miniconda3/envs/caiman/lib/python3.6/site-packages/caiman/base/movies.py", line 28, in <module>
    import cv2
ImportError: dlopen(/Users/Henry/miniconda3/envs/caiman/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libx264.138.dylib
  Referenced from: /Users/Henry/miniconda3/envs/caiman/lib/libavcodec.57.dylib
  Reason: image not found

- **If you're not reporting an error, type your message below**

**Comment by hluetck** [comment]
This seems to be a problem with the installation of opencv:

In [1]: import cv2
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c8ec22b3e787> in <module>()
----> 1 import cv2

ImportError: dlopen(/Users/Henry/miniconda3/envs/caiman/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libx264.138.dylib
  Referenced from: /Users/Henry/miniconda3/envs/caiman/lib/libavcodec.57.dylib
  Reason: image not found

**Comment by pgunn** [comment]
Sorry about this; last Friday conda-forge had an issue where someone released a new version of libx264, which broke ffmpeg which breaks opencv. You can most concisely reproduce this by, in your conda environment, doing the following:

```
$ python
> import cv2
```

You likely will see the same failure.

Fixing this in a cross-platform way is not really doable, but if you do the following:
conda install x264=20131218

it will likely fix it for your environment. The conda-forge developers are aware of this issue and are working on it (although I think they said they'd fix it up over the weekend and that clearly hasn't happened)

**Comment by hluetck** [comment]
`conda install -c conda-forge x264=20131218` indeed fixed the problem for me.

Thanks for your help!
