### ISSUE TITLE
Slow motion correction on big tif files

### ISSUE THREAD

**Issue by cortadita** [flatironinstitute/CaImAn#318]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**

Windows, Python 3.6, Spyder

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

I have an issue similar to #141 trying to run motion correction on big tif files (a few thousand frames of 512x512, 30 Hz acquisition, ~2 GB size). The registration works on shorter video of 500 frames but not on the long ones. Was this issue previously resolved in the software? 

I have tried using parameters as in demo_pipeline and also varying them to increase number of splits, patch size and overlap but to no avail. Both piecewise and full rigid registration take ~hour(s) or hang up altogether, even though the movies I use are a few minutes long.  Sometimes memory is also filled to full capacity (my PC is 16GB RAM). I am wondering if I am missing something here or this is an existing issue?

**Comment by epnev** [comment]
@cortadita We didn't follow the suggestion of the user in #141 but we modified the code to do something similar. Does your `load` function in `base/movies.py` look like [this](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/base/movies.py#L1234) when you work with .tif files?

**Comment by cortadita** [comment]
Thanks for quick reply @epnev. Yes, my `load` function is the same as on the master and I didn't have problems when loading .tif files previously.

**Comment by epnev** [comment]
Can you tell me the result when you type the following (where `fname` is the path to your tiff file)?
```
import tifffile
M = tifffile.TiffFile(fname)
print(M.is_imagej)
```

**Comment by epnev** [comment]
With some tiff files chunks of the data cannot be loaded without loading the entire dataset first. I believe that we had fixed this issue but it might still be there. I'm suspecting that this might be the case with your files where multiple process will load the entire file at once causing memory issues. If you have access to a machine with more RAM it would be helpful to try there see where the situation improves. 

If you are using the parameters as displayed in the demos, here are some suggestions that could help with respect to speed/memory:

- Increase `strides` by a factor of 2 or more.
- Increase `splits_rig` and `splits_els`. 

@agiovann

**Comment by agiovann** [comment]
Do you have the environment variables set as this? 

export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

**Comment by cortadita** [comment]
@epnev, thanks, I already increased these parameters. I may try to run it again on a better PC to see their effect.

@agiovann I didn't have these variables set, thank you! Setting them enabled me to run motion correction but Spyder still crashes afterwards - the mmap files saved are twice the size of the original file (>5GB). I am using demo_pipeline as the template and it looks that it first saves the motion corrected file as mmap in order F, loads it, then saves it again as order C, and then loads the whole memmaped C file into memory again. I am not familiar with handling memmap files but this seems to be a lot worse than directly loading the original file. Is there a better way of approaching this?

**Comment by agiovann** [comment]
excellent @cortadita it is normal to double the size. It is a bit complex to deal with memory map but is is absolutely necessary. You can try yourself to blow up your machine passing as input the numpy array  and setting dview=None and rf=None and strides=None. The memory map is necessary to deal with the memory and scalability.

**Comment by epnev** [comment]
@cortadita Just to add in case it's not clear, loading a memory mapped file does not add to the memory consumption which is the main reason we're doing this. You can find more details in our preprint.

**Comment by cortadita** [comment]
Thanks both for explanation - it looks like the demo runs for my files now, converting to different .mmap files is just slow. Can I also ask what is the reason for converting the C order memmaped file into order F again before feeding it into the cnmf function?

Running the second, refined CNMF raises the following error - tracking the function seems to show interpolating NaN values was just not implemented properly yet?

```
  File "<ipython-input-27-1e267550313b>", line 8, in <module>
    cnm2 = cnm2.fit(images)

  File "C:\Users\intrinsic\caiman\caiman\source_extraction\cnmf\cnmf.py", line 448, in fit
    Yr, dview=self.dview, **options['preprocess_params'])

  File "C:\Users\intrinsic\caiman\caiman\source_extraction\cnmf\pre_processing.py", line 604, in preprocess_data
    Y, coor = interpolate_missing_data(Y)

  File "C:\Users\intrinsic\caiman\caiman\source_extraction\cnmf\pre_processing.py", line 68, in interpolate_missing_data
    Y[idx, nans] = np.interp(nans, n_nans, row[n_nans])

ValueError: assignment destination is read-only
```

**Comment by epnev** [comment]
@cortadita For more info on memory mapping check the relevant section in page 23 of our [preprint](https://www.biorxiv.org/content/early/2018/06/05/339564).

For the error without NaN's, do you use the option `border_nan='copy'` when doing motion correction?

**Comment by agiovann** [comment]
@cortadita what happens is usually transforming from F order to C order, and not the other way around. When is this happening?

**Comment by cortadita** [comment]
@epnev I had it as a default (`True`) - setting it to `'copy'` helped, thank you.

@agiovann I meant that in the demo images fit into cnmf are re-ordered into F (`images = np.reshape(Yr.T, [T] + list(dims), order='F')`), but I am assuming it has to do with format the fit function expects and getting the same format directly from F-ordered memmap is impossible.

The pipeline generally works for me now but not always. Occasionally it still hangs - this happens when running a whole (large) script and usually is not the case when I run the script cell by cell. Not sure what may be causing this but restarting the kernel and running again in smaller chunks helps.
Many thanks for all your help!

**Comment by epnev** [comment]
@cortadita good to hear, we have changed the default to `'copy'` in the next release we're preparing. 

About the memory mapping, you are correct. The two orders refer to something different. The 'C' order is how files are saved and accessed efficiently from the hard drive. The 'F' order during reshaping is how we initialize chose to transform a 2d image (a single frame) into a 1d vector to be processed by the fit function. This was because the code was first implemented in matlab and then ported into python. It's a less pythonic choice but does not interact with the save/load memory mapping in any way.

Windows have some issues when running large scripts which is why we introduced these main() functions in the demos, for example [here](https://github.com/flatironinstitute/CaImAn/blob/master/demos/general/demo_pipeline.py#L54). If this continues to be a problem, please open a different issue. Thanks!
