### ISSUE TITLE
'Memory Error' Running CNMF on Patches

### ISSUE THREAD

**Issue by MarkCBenz** [flatironinstitute/CaImAn#321]
Using Windows 10 and Python 3.3, I continue to encounter issues using demo_pipeline.ipynb

I'm currently attempting to analyze some of my own 1p video of calcium transients in demo_pipeline.ipynb. Everything goes smoothly until the first run of CNMF. I encounter the following error:

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-30-d1c5f4dc51bf> in <module>()
      9                 method_init=init_method, alpha_snmf=alpha_snmf,
     10                 only_init_patch = False, gnb = gnb, border_pix = bord_px_els) 
---> 11 cnm = cnm.fit(images)

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images)
    647 
    648         self.A, self.C, self.YrA, self.b, self.f, self.neurons_sn = normalize_AC(
--> 649             self.A, self.C, self.YrA, self.b, self.f, self.neurons_sn)
    650 
    651         return self

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\utilities.py in normalize_AC(A, C, YrA, b, f, neurons_sn)
   1029 
   1030     if A is not None:
-> 1031         A /= nA
   1032 
   1033     if C is not None:

~\Anaconda3\envs\caiman\lib\site-packages\scipy\sparse\base.py in __truediv__(self, other)
    613 
    614     def __truediv__(self, other):
--> 615         return self._divide(other, true_divide=True)
    616 
    617     def __div__(self, other):

~\Anaconda3\envs\caiman\lib\site-packages\scipy\sparse\base.py in _divide(self, other, true_divide, rdivide)
    592             if not rdivide:
    593                 if true_divide:
--> 594                     return np.true_divide(self.todense(), other)
    595                 else:
    596                     return np.divide(self.todense(), other)

MemoryError: 

```

Are there some parameters I might try tinkering with to improve my system's performance. I'm working with 16GB of RAM.

best,
Mark

**Comment by epnev** [comment]
Can you run with setting `dview=None`? In general you might want to reduce the number of processes `n_processes` when starting a cluster since 16GB can be very little.

**Comment by pgunn** [comment]
One other thing to try is to increase the size of your pagefile; the README has instructions and a link to help you through this process. It's not obvious, but this setting also impacts the maximum size of a memmap on Windows.

**Comment by epnev** [comment]
@MarkCBenz Let us know if your issue still persists. Otherwise, we'll close it.

**Comment by j-friedrich** [comment]
If the normalization of sparse A is the only memory issue, we could use the division implementation that avoids conversion to dense as we do at other places.

**Comment by epnev** [comment]
@j-friedrich Agree, I didn't realize that A is dense here. The normalize_components method should fix this.
