### ISSUE TITLE
Problems Installing CaImAn

### ISSUE THREAD

**Issue by ja-94** [flatironinstitute/CaImAn#324]
-Ubuntu 18.04, Python 3.6, I usually work with Jupyter Notebooks

- Following the Readme, I do this:
`
git clone https://github.com/flatironinstitute/CaImAn
cd CaImAn/
conda env create -f environment.yml -n caiman
source activate caiman
pip install .
`

and I get this error:

`~/anaconda3/CaImAn$ conda env create -f environment.yml -n caiman`

Solving environment: done
Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for scikit-image located at /home/jaime/anaconda3/pkgs/scikit-image-0.14.0-py36hfc679d8_1
appears to be corrupted. The path 'lib/python3.6/site-packages/skimage/data/astronaut_GRAY_hog_L1.npy'
specified in the package manifest cannot be found.

CondaVerificationError: The package for scikit-image located at /home/jaime/anaconda3/pkgs/scikit-image-0.14.0-py36hfc679d8_1
appears to be corrupted. The path 'lib/python3.6/site-packages/skimage/data/astronaut_GRAY_hog_L2-Hys.npy'
specified in the package manifest cannot be found.

CondaVerificationError: The package for scikit-image located at /home/jaime/anaconda3/pkgs/scikit-image-0.14.0-py36hfc679d8_1
appears to be corrupted. The path 'lib/python3.6/site-packages/skimage/data/mssim_matlab_output.npz'
specified in the package manifest cannot be found.

CondaVerificationError: The package for scikit-image located at /home/jaime/anaconda3/pkgs/scikit-image-0.14.0-py36hfc679d8_1
appears to be corrupted. The path 'lib/python3.6/site-packages/skimage/feature/_haar.cpython-36m-x86_64-linux-gnu.so'
specified in the package manifest cannot be found.

CondaVerificationError: The package for scikit-image located at /home/jaime/anaconda3/pkgs/scikit-image-0.14.0-py36hfc679d8_1
appears to be corrupted. The path 'lib/python3.6/site-packages/skimage/filters/rank/generic_cy.cpython-36m-x86_64-linux-gnu.so'
specified in the package manifest cannot be found.

CondaVerificationError: The package for scikit-image located at /home/jaime/anaconda3/pkgs/scikit-image-0.14.0-py36hfc679d8_1
appears to be corrupted. The path 'lib/python3.6/site-packages/skimage/filters/rank/percentile_cy.cpython-36m-x86_64-linux-gnu.so'
specified in the package manifest cannot be found.

CondaVerificationError: The package for scikit-image located at /home/jaime/anaconda3/pkgs/scikit-image-0.14.0-py36hfc679d8_1
appears to be corrupted. The path 'lib/python3.6/site-packages/skimage/graph/_mcp.cpython-36m-x86_64-linux-gnu.so'
specified in the package manifest cannot be found.

CondaVerificationError: The package for scikit-image located at /home/jaime/anaconda3/pkgs/scikit-image-0.14.0-py36hfc679d8_1
appears to be corrupted. The path 'lib/python3.6/site-packages/skimage/restoration/tests/camera_unsup.npy'
specified in the package manifest cannot be found.

SafetyError: The package for scikit-image located at /home/jaime/anaconda3/pkgs/scikit-image-0.14.0-py36hfc679d8_1
appears to be corrupted. The path 'lib/python3.6/site-packages/skimage/restoration/tests/camera_unsup2.npy'
has a sha256 mismatch.
  reported sha256: 30e81718f3cac0fc00d84518ca75a3c0fb9b246bb7748a9e20ec0b44da33734d
  actual sha256: 92d5bf136f236d2fb93298ea0900655c4e2f87e082b7025fb652e4b9e97bbdb9

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::gettext-0.19.8.1-0, defaults::libgcc-ng-7.2.0-hdf63c60_3, conda-forge::readline-6.2-0
  path: 'share/info/dir'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::jupyter_core-4.4.0-py_0, conda-forge::jupyter-1.0.0-py_1
  path: 'lib/python3.6/site-packages/jupyter.py'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::jupyter_core-4.4.0-py_0, conda-forge::jupyter-1.0.0-py_1
  path: 'lib/python3.6/site-packages/__pycache__/jupyter.cpython-36.pyc'

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::tensorboard-0.4.0rc3-py36_2, conda-forge::tensorflow-1.4.0-py36_0
  path: 'bin/tensorboard'

I have tried changing directories and the error persists.

I can activate the environment and do `pip install .`, which seems to work properly. Then, when running `caimanmanager.py install`, I get an error because of line `from caiman.paths import caiman_datadir` saying that caiman.path doesn't exist. I have tried changing that line with the actual caiman_datadir function, but it still doesn't work (it says other modules don't exist).

`Traceback (most recent call last):
  File "/home/jaime/anaconda3/CaImAn/caimanmanager.py", line 13, in <module>
    from caiman.paths import caiman_datadir
  File "/home/jaime/anaconda3/CaImAn/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "/home/jaime/anaconda3/CaImAn/caiman/base/movies.py", line 25, in <module>
    from builtins import str
ImportError: No module named builtins`

**Comment by ja-94** [comment]
Following the instructions in the issue below I get this
https://github.com/flatironinstitute/CaImAn/issues/217
with caiman env activated, while in home directory:
`echo $PYTHONPATH`  -> no output
`~/anaconda3/CaImAn/caimanmanager.py install` same error as before:
Traceback (most recent call last):
  File "/home/jaime/anaconda3/CaImAn/caimanmanager.py", line 13, in <module>
    from caiman.paths import caiman_datadir
  File "/home/jaime/anaconda3/CaImAn/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "/home/jaime/anaconda3/CaImAn/caiman/base/movies.py", line 25, in <module>
    from builtins import str
ImportError: No module named builtins

with caiman env activated, while in ~/anaconda3/CaImAn directory:
`echo $PYTHONPATH`-> no output
`~/anaconda3/CaImAn/caimanmanager.py install`->same error as before:
Traceback (most recent call last):
  File "/home/jaime/anaconda3/CaImAn/caimanmanager.py", line 13, in <module>
    from caiman.paths import caiman_datadir
  File "/home/jaime/anaconda3/CaImAn/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "/home/jaime/anaconda3/CaImAn/caiman/base/movies.py", line 25, in <module>
    from builtins import str
ImportError: No module named builtins
`echo $PATH`
/home/jaime/anaconda3/envs/caiman/bin:/usr/bin:/bin:/usr/local/cuda-9.0/bin:/home/jaime/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
`which python`
/usr/bin/python
`/usr/bin/env python`
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
`python caymanmanager.py install`
python: can't open file 'caymanmanager.py': [Errno 2] No such file or directory

**Comment by ja-94** [comment]
I started again from scratch and installed the packages in the .yml file by hand. The environment is created fine now, and when I run `caimanmanager.py install` instead of giving me the error I got before, I get:

Traceback (most recent call last):
  File "/home/jaime/anaconda3/envs/caiman/bin/caimanmanager.py", line 13, in <module>
    from caiman.paths import caiman_datadir
  File "/home/jaime/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "/home/jaime/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/base/movies.py", line 28, in <module>
    import cv2
ImportError: libjasper.so.1: cannot open shared object file: No such file or directory

I have tried doing `conda install x264=20131218`  as suggested in https://github.com/flatironinstitute/CaImAn/issues/317 but I keep getting the same error

**Comment by ja-94** [comment]
I did `conda install opencv` instead of `opencv=3.2` as suggested by the .yml file, and now caimanmanager.py installed correctly

**Comment by ja-94** [comment]
I realized the error with `import cv2` was due to the fact that I was using jupyter lab, which I didn't install in my caiman env, so I installed it, removed opencv, and reinstalled opencv=3.2, and now I don't get that error anymore. I can open the demo notebooks, and import all the modules, however as soon as I get to a call to imshow I get this error:+

error: /feedstock_root/build_artefacts/opencv_1490907195496/work/opencv-3.2.0/modules/highgui/src/window.cpp:583: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage


I have tried doing `conda install --channel loopbio --channel conda-forge --channel pkgw-forge gtk2 ffmpeg ffmpeg-feature gtk2-feature opencv` as suggested in https://github.com/Microsoft/ELL/issues/53, but it doesn't get rid of the error

**Comment by epnev** [comment]
@ja-94 Sorry for the late response. Our offices are closed these days and some people are traveling. Is your problem resolved if you don't use jupyter lab?

@pgunn Can you take a look?

**Comment by ja-94** [comment]
Don't worry, thanks for the response. 

I get the same error when using jupyter notebooks instead of jupyter-lab. This happens to me in the 4th cell in the pipeline demo notebook. After `m_orig.resize(1, 1, downsample_ratio).play(
gain=10, offset=offset_mov, fr=30, magnification=2)`, I get this:

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-4-c7f78d8d3a8b> in <module>()
      3 offset_mov = -np.min(m_orig[:100])  # make the dataset mostly non-negative
      4 m_orig.resize(1, 1, downsample_ratio).play(
----> 5 gain=10, offset=offset_mov, fr=30, magnification=2)

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/base/movies.py in play(self, gain, fr, magnification, offset, interpolation, backend, do_loop, bord_px, q_max, q_min, plot_text)
   1121                                     frame.shape[0] - (text_height + 5)), fontFace=5, fontScale=0.8, color=(255, 255, 255), thickness=1)
   1122 
-> 1123                     cv2.imshow('frame', frame)
   1124 
   1125                     if cv2.waitKey(int(1. / fr * 1000)) & 0xFF == ord('q'):

error: /feedstock_root/build_artefacts/opencv_1490907195496/work/opencv-3.2.0/modules/highgui/src/window.cpp:583: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage


If I change to one of my .tif files, I get a Memory Error instead.

**Comment by ja-94** [comment]
I just did this:

conda remove opencv
conda update conda
conda install --channel menpo opencv

and it solved the error I was getting, now everything seems to work fine.

**Comment by pgunn** [comment]
Some of the errors above make it look like your local conda cache may have gotten some corrupted packages in it ; two possible causes are if the disk filled up recently some packages may have been left half-written, or alternatively if you saw some disk corruption. I'm glad you solved the issue, and we'll keep an eye out for problems like this  in the future in case it's something else.

In a more ideal world you would not have needed to use the menpo channel packagings of opencv.

**Comment by ja-94** [comment]
I just did this:

conda remove opencv
conda update conda
conda install --channel menpo opencv

and it solved the error I was getting, now everything seems to work fine.

**Comment by ja-94** [comment]
I don't think my disk has ever been completely full yet, nor have I seen any corruption issues with it, but I'm not a computer scientist, and I set up a dual boot system in which I've spent hundreds of hours installing stuff and changing settings I don't fully understand, so I've gotten plenty of opportunities to mess things up, very likely a problem with my system.
