### ISSUE TITLE
'future' module not installed when installing CaImAn package

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#330]
Reported by @sfailor in the gitter chat. I actually ran into the same problem with conda / py3.6 / RHEL 6 and just installed it manually and forgot about it.

>This is the error message: Traceback (most recent call last):
File "C:\Users\Samuel\caimanmanager.py", line 13, in <module>
from caiman.paths import caiman_datadir
File "C:\Users\Samuel\CaImAn\caiman__init__.py", line 3, in <module>
from .base.movies import movie, load, load_movie_chain
File "C:\Users\Samuel\CaImAn\caiman\base\movies.py", line 27, in <module>
from past.utils import old_div
ModuleNotFoundError: No module named 'past'

**Comment by epnev** [comment]
That's weird. `future` is included in the [environment.yml](https://github.com/flatironinstitute/CaImAn/blob/master/environment.yml) file.

**Comment by zbarry** [comment]
Oh, you know what, when I installed it, I just blindly pip install'd caiman and then took care of the missing packages that weren't in my environment already myself... Forgot about that.
