### ISSUE TITLE
Strange "artifact" in correlation maps

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#331]
This is more of a results than a software problem, but I thought I'd see if anyone has encountered this before:

https://gist.github.com/zbarry/8392882436e9ab658f20e4982ed02d0f/raw/833b3b262a5d1e7c65dadfd9ae7b1a913d66e5b1/caiman_correlation_image.png

In the middle of the image, you can see that there is a low correlation / high correlation dual band horizontal line. I thought this may be from a scratch on the lens or something (and maybe it is), but strangely, this artifact only appears in some movies, even from the same sample across sessions. In one case, the artifact was not present in session 1, present in sessions 2 and 3, and not present in the final session... no idea what's going on here.

Any ideas?

**Comment by epnev** [comment]
It looks like some sort of artifact but I cannot tell what it might be. You might want to do some high pass spatial filtering and look at the data to see if anything like that is present
