### ISSUE TITLE
detrend_df_f() fails with dimensionality issue when automatic quantile determination is used

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#332]
conda / 3.6 / RHEL 6

Commit: 9e816b53e1bdc3dbcb69725dab0fb2659b9dd511 (pulled today)

`detrend_df_f()` in `caiman.source_extraction.cnmf.utilities` fails with dimensionality error when `flag_auto=True`. This error occurs specifically on line 572:

`F_df = (F - Fd) / (Df + Fd)`

Variable values/dimensions:

`frames_window = 60`

`A.shape`: `(388800, 173)`
`b.shape`: `(388800, 48)`
`C.shape`: `(173, 400)`
`f.shape`: `(48, 400)`
`YrA.shape`: `(173, 400)`

`B.shape`: `(173, 400)`

`F.shape`: `(173, 400)`
`Fd.shape`: `(60, 400)`
`Df.shape`: `(60, 400)`

The problem appears to be with:

`data_prct, val = df_percentile(F[:frames_window], axis=1)`

`data_prct` and `val` are of shape `(60,)`, which causes `Fd` and `Df` to be shortened because the `zip()`s are receiving only 60 elements from `data_prct` (and the full 400 from `B`):

```
            else:  # line 565
                Fd = np.stack([scipy.ndimage.percentile_filter(
                    f, prctileMin, (frames_window)) for f, prctileMin in
                    zip(F, data_prct)])
                Df = np.stack([scipy.ndimage.percentile_filter(
                    f, prctileMin, (frames_window)) for f, prctileMin in
                    zip(B, data_prct)])
            F_df = (F - Fd) / (Df + Fd)
```

I think this is because the slicing on `F` is done on the wrong axis. Seems like it should be something like:

`data_prct, val = df_percentile(F[:, :frames_window], axis=1)`

instead?

**Comment by epnev** [comment]
Yup, another great catch. Thanks!

**Comment by epnev** [comment]
Updated it. I usually use a much larger frames_window parameter that includes all the parameters so this hadn't appeared before. You may find `frames_window=60` to be small depending on the frame rate of your data. Empirically, after talking with experimentalists `frames_window` should cover a period of about 10s, perhaps even more.

**Comment by zbarry** [comment]
No problem. Thanks for the advice. In this case, we're binning the time a ton (to 5 Hz), so that would be a 12 second window. Having looked at my traces though, I'm thinking I need to increase it more anyway. Still tweaking parameters at the moment, but results are looking very promising (and so much better than PCA-ICA used previously, haha)
