### ISSUE TITLE
Problems Updating CaImAn

### ISSUE THREAD

**Issue by MarkCBenz** [flatironinstitute/CaImAn#340]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**
Windows 10, Python 3, Anaconda Prompt

- **Describe the issue that you are experiencing**
I'm attempting to  python install caimanmanager.py, however, I can't seem to make this work. From my Anaconda prompt. I use:

```
cd CaImAn
python caimanmanager.py install

```

- **Copy error log below**
To which I find:
```
Traceback (most recent call last):
  File "caimanmanager.py", line 197, in <module>
    main()
  File "caimanmanager.py", line 163, in main
    cfg = handle_args()
  File "caimanmanager.py", line 192, in handle_args
    cfg.userdir = caiman_datadir()
NameError: name 'caiman_datadir' is not defined
```

**Comment by pgunn** [comment]
This is odd. Does your caimanmanager.py not have a line like this near the top?

```from caiman.paths import caiman_datadir```

**Comment by MarkCBenz** [comment]
Yes,

everything looks normal there:
```
#!/usr/bin/env python

from __future__ import print_function
import argparse
import distutils.dir_util
import filecmp
import os
import shutil
import string
import subprocess
import sys # for sys.prefix

from caiman.paths import caiman_datadir
```

**Comment by MarkCBenz** [comment]
Now, when I activate the caiman enviroment, us CaImAn folder as my current directory, I get:
```
ModuleNotFoundError: No module named 'caiman.source_extraction.cnmf.oasis'
```

**Comment by pgunn** [comment]
Ah, so on Windows, assuming you installed Caiman with "pip install .", you'll want to:

1) Copy caimanmanager.py to the parent of your checkout directory
2) Run it there

This is because the compiled parts of caiman land in python library directories rather than in the source tree with the new install mechanism.

**Comment by MarkCBenz** [comment]
So, when I run it from the folder CaImAn, I get the same error. This is the same for that I establish as the current directory with cd CaImAn. Now, sitting inside this folder is caiman? Im new to this, so I'm a bit puzzled what a checkout directory is.

**Comment by pgunn** [comment]
Sorry, what I mean is to copy it outside the CaImAn folder and run it from out there.

**Comment by MarkCBenz** [comment]
I see, I got it to work! Thanks
