### ISSUE TITLE
Interest in a pull request for memory mapping motion correction shift application

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#343]
I noticed that `apply_shifts_movie` in the `MotionCorrect` class does not use memory mapping. Would you guys be interested in a pull request to address this? If so, are the any considerations in particular outside of the guidelines provided in the contributions .md file that I should consider to make integration into the existing codebase as efficient as possible?

**Comment by epnev** [comment]
@zbarry You can create a PR although it'll take a while until we get to it. We'll need to think about where the memory mapped filenames will be stored and these decisions can take a while. This function will not affect nosetests or any other tests at all. Thanks!

**Comment by zbarry** [comment]
Ok, makes sense. It's something that's necessary to me anyway, but it's easier to just tailor it to my needs in my own codebase than adapt it into a larger, existing framework, so just want to make sure that in the end, it is desired and valuable. 

Given that it would be interesting in the long term (regardless of it probably being a slow process to integrate), which branch should I work on, though?

**Comment by epnev** [comment]
I'd say master to make sure you have a stable codebase for your application.
