### ISSUE TITLE
Installation fails: many packages are missing and I can't run any CaImAn code

### ISSUE THREAD

**Issue by corenlahav** [flatironinstitute/CaImAn#347]
I have never used python\anaconda before and am not familiar with the environment.
I use Windows 10. I installed python and anaconda according to the installation instructions in https://github.com/flatironinstitute/CaImAn.
When I run python from command line the version reported is:
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32

The first steps of the installation went smoothly as far as I am aware (Downloaded and installed Anaconda (Python 3.6), Used Conda to install git, Installed Microsoft Build Tools for Visual Studio 2017)

During installation instructions I am asked to run start>programs>anaconda3>anaconda prompt
and execute the following lines:

> ```bash
> git clone  https://github.com/flatironinstitute/CaImAn
> cd CaImAn
> conda env create -f environment.yml -n caiman
> activate caiman
> pip install . (OR pip install -e . if you want to develop code)
> copy caimanmanager.py ..
> conda install numba
> cd ..
> ```

When running this script I get the following errors:
Error 1:

> '```bash' is not recognized as an internal or external command, operable program or batch file.

Error 2:

> Invalid requirement: '(OR'
> Traceback (most recent call last):
>   File "C:\Users\Coren\Anaconda3\envs\caiman\lib\site-packages\pip\_vendor\packaging\requirements.py", line 93, in __init__

So I ran each line manually excluding the lines marked here with #

> #```bash
> git clone  https://github.com/flatironinstitute/CaImAn
> cd CaImAn
> conda env create -f environment.yml -n caiman
> activate caiman
> pip install . # (OR pip install -e . if you want to develop code)
> copy caimanmanager.py ..
> conda install numba
> cd ..
> #```

and got the following error

> Directory '.' is not installable. File 'setup.py' not found.

I am guessing that this is where the installation failed.

Later, trying to run the first piece of code from demo_motion_correction in Jupiter Notebooks fails with error

> ModuleNotFoundError: No module named 'past'

When I install it using the command "pip install future" I get another error

> ModuleNotFoundError: No module named 'caiman'

and so on...

It's obviously a stupid mistake but I am not sure what I've done wrong and will be glad for any help

Thanks

**Comment by pgunn** [comment]
Hi,
For the lines to execute up top, it's expected that you'd copy/paste them out and run them individually. The version in the repo has some formatting things that are meant to make the README display nicely on Github; the "bash" bit was not meant for you to type. Also, the (OR pip install -e ) part was a note for humans rather than something to cut/paste in. We might be able to make that more clear.

For the second error you saw, I think if you ignore the lines with the triple-backtics, and don't paste in the part in parantheses, and run it as you see it on the github page, it should work. If not, put in here the first command that gave an error (and do not go on from that); we can debug it from there.

**Comment by corenlahav** [comment]
Open the file CaImAn\demos\notebooks\**demo_motion_correction.ipynb** using Jupyter Notebook and run the first piece of code using the Run button.
At the first run I got the following error at line 11:
ModuleNotFoundError: No module named 'past'

I installed future (using the following command in Anconda prompt: pip install future) and tried to run the code again. Now I got the following error:

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-38562c56f03e> in <module>()
>      24     pass
>      25 
> ---> 26 **import caiman as cm**
>      27 import numpy as np
>      28 import os
> 
> **ModuleNotFoundError: No module named 'caiman'**

**I ran the command caimanmanager.py install from cmd but it does not install anything, it only opens the Visual Studio Code editor.**

**Comment by pgunn** [comment]
Try this instead (after starting the anaconda command prompt and doing "activate caiman"):

`python caimanmanager.py install`

**Comment by corenlahav** [comment]
I solved the problems by working with the Matlab toolbox. Everything works
well there.

You can close this one.
Thanks for the help :)
Coren
