### ISSUE TITLE
TiffWriter error when saving a .tif file from .mmap

### ISSUE THREAD

**Issue by Cumol** [flatironinstitute/CaImAn#351]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**

Ubuntu 17.10 with Python 3.6 straight from a .py file

- **Describe the issue that you are experiencing**
Saving a .tif file from a motion corrected .mmap outputs an error.

- **Copy error log below**

```
TypeError                                 Traceback (most recent call last)
~/caiman-motioncorrection.py in <module>()
     88 
     89 ##save rigid corrected movie as .tif
---> 90 m_rig.save(os.path.join(os.path.dirname(fname[0]),'motion_corrected.tif'))
     91 
     92 #%% plot rigid shifts

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/base/timeseries.py in save(self, file_name, to32, order, imagej, bigtiff, software, compress)
    172 
    173 
--> 174             with tifffile.TiffWriter(file_name, bigtiff=bigtiff, imagej=imagej, software=software) as tif:
    175 
    176 

TypeError: __init__() got an unexpected keyword argument 'software'

```

**Comment by epnev** [comment]
Can you try again now?
Essentially I removed the reference to the software entry as it appears to not be supported by all versions of tifffile.
https://github.com/flatironinstitute/CaImAn/commit/c014d2633d1d7d1188c29624b8c8ebbb5a16adb1 
You'll probably need to do a soft upgrade as the [instructions](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn) say.

**Comment by epnev** [comment]
```
pip uninstall caiman
git pull
pip install .
```
should be enough assuming you didn't use the `-e` options when you first installed. If you did then a `git pull` is all you need.

**Comment by Cumol** [comment]
Works fine now. thanks!

**Comment by epnev** [comment]
@Cumol cool. Can you also check if your previous problem with the subindices is still an issue? 
https://github.com/flatironinstitute/CaImAn/issues/242#issuecomment-398812180
