### ISSUE TITLE
LassoLars alpha too aggressive

### ISSUE THREAD

**Issue by mschachter** [flatironinstitute/CaImAn#352]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**
Operating System: CENTOS 7
Python Version: Anaconda 3.6
CaImAn Branch: dev
Environment: Typical caiman environment installed with conda env 
Dataset: Available here (~50MB):
https://drive.google.com/file/d/1cRBTuawSqiMFZoHLMmYXkZLhcmkX2DKo/view?usp=sharing

- **Describe the issue that you are experiencing**
With one-photon data, update_spatial is calling LassoLars with an alpha set with the following code (line 390 of spatial.py):

```python
lambda_lasso = 0 if np.size(cct_) == 0 else \
                    .5 * noise_sn[px] * np.sqrt(np.max(cct_)) / T
```
The value of lambda_lasso on the data, around 1e-4, is too high, and zeroes out the spatial footprints. When I hardcode lambda_lasso to be 1e-8, everything works ok.

I think a solution to this problem could be to add a parameter to CNMFParams called "lasso_alpha_gain" that is multiplied by lambda_lasso to determine the final alpha parameter for LassoLars.

- Here is the code to reproduce the issue, after downloading the file linked above:
```python
import os
from caiman import load_memmap
from caiman.source_extraction.cnmf import CNMF
from caiman.components_evaluation import estimate_components_quality_auto
from caiman.source_extraction.cnmf.params import CNMFParams

# set the params
frame_rate = 10.0
decay_time = 0.400
min_SNR = 3

cnmfe_params = CNMFParams(k=20, gSiz=(9, 9), decay_time=decay_time, min_pnr=2,
                                                    min_SNR=min_SNR, p=1,
                                                    merge_thresh=0.8, ssub=1, tsub=1, p_ssub=1, p_tsub=1,
                                                    method_init='corr_pnr', min_corr=0.80, ssub_B=2, 
                                                    ring_size_factor=1.5,
                                                    low_rank_background=None, nb_patch=-1, gnb=-1)

# load the file
root_dir = '/path/to/downloaded/file'
mov_file = os.path.join(root_dir, 'recording_20160517_172653-cropped_d1_116_d2_135_d3_1_order_C_frames_4298_.mmap')
Yr, dims, T = load_memmap(mov_file)
Y = Yr.T.reshape((T,) + dims, order='F')

# fit the data
num_procs = 1
cnmfe = CNMF(num_procs, dview=None, params=cnmfe_params)
cnmfe.fit(Y)

print('A.shape=',cnmfe.estimates.A.shape)
print('C.shape=',cnmfe.estimates.C.shape)
```

**Comment by epnev** [comment]
@mschachter Good catch. What's probably happening here is that the noise is calculated without removing the background, which in 1p data might lead to over-estimation. I'm fine with this idea. 
@j-friedrich @agiovann thoughts?

**Comment by mschachter** [comment]
Also @epnev I want to note that these movies are already spatial bandpass filtered and mean-subtracted, so their average intensity should be constant over time.

**Comment by epnev** [comment]
@mschachter I see. I'll take a look at the dataset see if I can get any insights. Thanks

**Comment by j-friedrich** [comment]
If `normalize_yyt_one is True`(is it always True?) `C` and `A_in` get renormalized in lines 184+, whereas the noise `sn` is not rescaled, so this issue should actually affect 2p data as well.

**Comment by epnev** [comment]
@j-friedrich Not sure, because `sn` depends on the data `Y` which seems to be unchanged regardless of the unintuitive parameter name. However I have concerns about the formula
```
lambda_lasso = 0 if np.size(cct_) == 0 else \
                    .5 * noise_sn[px] * np.sqrt(np.max(cct_)) / T
```
If you reduce the value of `C` then the `lambda_lasso` factor would be reduced where in practice you actually want to do the opposite since `A` has been increased and you need a stronger penalty to achieve the same level of shrinkage.

**Comment by j-friedrich** [comment]
You're right, it's noise per pixel. It does however not get rescaled if `normalize_init=True`, a setting I never used for 1p, not sure whether one would want to.
The formula seems indeed wrong, looks as if `alpha` should be independent of the scale of `c`. If I keep the same `alpha` and `y` in LassoLars, but scale `c` by some factor `f` the result is scaled by `1/f` as it should.

**Comment by epnev** [comment]
@j-friedrich Does the script run for you with the current state of dev? I'm getting stuck in the deconvolution

**Comment by j-friedrich** [comment]
`LassoLars` also has a setting `normalize` that actually defaults to `True`. If we set it to `False` the current formula should be fine, i.e. scaling `c` by some factor `f` the result `a` is scaled by `1/f`.

Tested on some random simulated data:

`In [5]: f = 20` 
`In [6]: np.allclose(f*LassoLars(alpha=.01*f, normalize=False).fit(f*c.T, y).coef_ , LassoLars(alpha=.01, normalize=False).fit(c.T, y).coef_)`
`Out[6]: True`
`In [7]: np.allclose(f*LassoLars(alpha=.01, normalize=True).fit(f*c.T, y).coef_ , LassoLars(alpha=.01, normalize=True).fit(X.T, y).coef_)`
`Out[7]: True`

**Comment by mschachter** [comment]
@epnev Setting normalize == True does not fix the problem:
```python
# does not work
clf = linear_model.LassoLars(alpha=lambda_lasso, positive=True, normalize=False)
```
Also setting fit_intercept == False does not fix the problem:
```python
# does not work
clf = linear_model.LassoLars(alpha=lambda_lasso, positive=True, fit_intercept=False)
```

Setting them both to False also does not work:
```python
# does not work
clf = linear_model.LassoLars(alpha=lambda_lasso, positive=True, normalize=False, fit_intercept=False)
```

**Comment by j-friedrich** [comment]
Do you use `only_init_patch=True` and `normalize_init=False`?
I get 19 components on your cropped example data, even without fixing lambda_lasso, though we should.

**Comment by mschachter** [comment]
Thanks @j-friedrich. If I set normalize_init == False in the CNMFParams constructure, then *no modification of the LassoLars constructor is necessary.* These are the parameters I'm using:

```python
cnmfe_params = CNMFParams(k=25, gSiz=(13, 13), decay_time=0.400, min_pnr=2, 
                                                    min_SNR=3, p=1,
                                                    merge_thresh=0.8, ssub=1, tsub=1, p_ssub=1, p_tsub=1,
                                                    method_init='corr_pnr', min_corr=0.80,
                                                    ssub_B=2, ring_size_factor=1.5,
                                                    only_init_patch=True, center_psf=True,
                                                    low_rank_background=None, nb_patch=-1, gnb=-1, 
                                                    normalize_init=False)
```

**Comment by mschachter** [comment]
@epnev Yes, setting normalize_init=False solves the problem of zero-ing without the need of modifications, and the cells look reasonable and not too sparse.

**Comment by epnev** [comment]
@mschachter ah, that makes sense. For 1p data all the processing takes place in the initialization module and the LassoLars routine will be affected by this initialization. That shouldn't be the case for 2p data where the initialization does not call `update_spatial` etc. I still think however think that we should set `fit_intercept=False` although the effect should not be strong.

**Comment by mschachter** [comment]
@epnev setting ```fit_intercept=False``` doesn't have any negative effects on this dataset.

**Comment by j-friedrich** [comment]
Giving it a 2nd thought, I agree that `fit_intercept=False` is what we want. In this case `normalize` is actually ignored in `LassoLars`, which is fine because we normalize anyway before. The lambda_lasso formula should be ok too.
Should we further set `normalize_init=False` automatically if the ringmodel is used (`if method_init=='corr_pnr' and ring_size_factor is not None`)? Currently we set it correctly in `demo_pipeline_cnmfE.py` and merely tell the user to "just leave as is".

**Comment by epnev** [comment]
@j-friedrich Yes, that's a good idea. Can you implement these changes on dev and close the issue?

**Comment by j-friedrich** [comment]
Implemented, hence closing
