### ISSUE TITLE
Corr/PNR summary image downstream of apply_shifts_movie with border_nan=True broken

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#354]
I am taking a crop of my full field of view to first extract motion correction shifts out of. I then apply these shifts to the full movie using `apply_shifts_movie` from the returned motion correction object. By default, `border_nan` is set to `True` in this function. Attempting to then run `cm.summary_images.correlation_pnr` on this data results in this interesting result (PNR image is shown):

![corr_pnr_with_nans](https://user-images.githubusercontent.com/4762711/44371958-93c20c00-a4af-11e8-89a6-81b7b346bfb5.png)

Note that all that black is of value `NaN`.

Setting `border_nan` to `False` solves this issue, and I believe that must be done behind the scenes when you run the pipeline as usual without this sort of cropping. This is unusual, though, because `border_nan` is set to `True` in `motion_correct_oneP_rigid`. Any idea what might be going on? Is that parameter actually getting ignored accidentally, or maybe I'm just missing something else? `border_nan=False` appears to be fine for my purposes, though the behavior struck me as potentially worth mentioning.

Note that I think this might imply that the CNMF fitting routine itself will fail during corr_pnr initialization with the same exact issue.

Skeleton implementation:

```python
    c, dview, n_processes = cm.cluster.setup_cluster(
        backend='local',
        n_processes=num_processes,
    )

    mc = motion_correct_oneP_rigid(
        [input_filename_crop],
        gSig_filt=gsig_filt,
        max_shifts=max_shifts,
        dview=dview,
        splits_rig=splits_rig,
        save_movie=False
    )

    mc_full = mc.apply_shifts_movie(input_filename_full, border_nan=True)
    mc_full.save(output_filename_prefix + '.mmap')
```

~~~ Later on down the pipeline ~~~

```python
    yr, dims, t = cm.load_memmap(mmap_filename)
    y = yr.T.reshape((t,) + dims, order='F')
    im_corr, im_pnr = cm.summary_images.correlation_pnr(y, gSig=g_sigma_cnmf, swap_dim=False)
```

**Comment by epnev** [comment]
@zbarry Hard to say. In general a nan value can propagate all the way to the summary statistics and appear in them. It's best to avoid them by using either 'False' or 'copy', which will be the default method. Does 'copy' solve the problem?

**Comment by agiovann** [comment]
@zbarry is this solved?

**Comment by zbarry** [comment]
Yeah, should be good to go.
