### ISSUE TITLE
OverflowError: cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#356]
Encountered this error during the CNMF-E analysis of my data. Memory maps from the motion correction that I'm passing in are 4.3 GB. Anyone seen this before?

Documentation of error message:

```
~~~ snip ~~~
/home/barryza1/hpc_resources/CaImAn/caiman/source_extraction/cnmf/deconvolution.py:1025: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  g = np.linalg.lstsq(A, xc[lags + 1:])[0]
/home/barryza1/anaconda3/envs/inscopix/lib/python3.6/site-packages/scipy/sparse/compressed.py:746: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)
/home/barryza1/anaconda3/envs/inscopix/lib/python3.6/site-packages/scipy/sparse/dia.py:300: RuntimeWarning: divide by zero encountered in remainder
  c = np.arange(num_rows, dtype=np.intc) - (offsets % max_dim)[:, None]
Traceback (most recent call last):
  File "/home/barryza1/anaconda3/envs/inscopix/bin/caiman", line 11, in <module>
    load_entry_point('Inscopix-Analysis', 'console_scripts', 'caiman')()
  File "/home/barryza1/hpc_resources/mibs-inscopix/src/inscopix/run_caiman.py", line 420, in main
    args.func(args)
  File "/home/barryza1/hpc_resources/mibs-inscopix/src/inscopix/run_caiman.py", line 90, in stage_cnmf
    num_processes=args.numprocs
  File "/home/barryza1/hpc_resources/mibs-inscopix/src/inscopix/caiman/cnmf.py", line 163, in run_cnmf
    use_cnn=False
  File "/home/barryza1/hpc_resources/CaImAn/caiman/components_evaluation.py", line 538, in estimate_components_quality_auto
    fitness_delta_min=thresh_fitness_delta, return_all=True, dview=dview, num_traces_per_group=50, N=N_samples)
  File "/home/barryza1/hpc_resources/CaImAn/caiman/components_evaluation.py", line 696, in estimate_components_quality
    evaluate_components_placeholder, params).get(4294967)
  File "/home/barryza1/anaconda3/envs/inscopix/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/barryza1/anaconda3/envs/inscopix/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/home/barryza1/anaconda3/envs/inscopix/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/barryza1/anaconda3/envs/inscopix/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
OverflowError: cannot serialize a bytes object larger than 4 GiB
```

Note that `inscopix/caiman/cnmf.py` is my pipeline's wrapper for this step of analysis, not a part of caiman proper.

Apparently this is expected, actually, as people have noted this before: https://bugs.python.org/issue23979 . Unfortunately, the poster apparently solved the problem somehow and then ignored the request to post his solution (great...). It appears to be a limitation with Pickle and the fact that multiprocessing uses it instead of shared memmaps or another solution.

Also: https://bugs.python.org/issue17560

I'm guessing there is not a straightforward workaround for CaImAn to be able to handle movies whose sizes are on the order of what I'm dealing with (10-30 minutes @ 20 Hz which I've downsampled to 5 Hz at the moment. File sizes would then double of course when I test 10 Hz... The 10 minute time-crops are what come to 4.3 GB memory maps). Unless you guys know a quick solution, I guess I'm going to have to dive into the code, and if I find a workaround, I'll initiate a PR.

**Comment by pgunn** [comment]
We ran into this in the latter stages of dealing with #322 - it doesn't have a great solution, but it's what we have for now.  We're looking into other options.

There's a chance that later versions of Python may use later versions of the pickle format which would solve it for us for free. It might be interesting to try Python 3.7 to see if the needed plumbing changes made it in there.

**Comment by j-friedrich** [comment]
Are you returning the full rank back ground (`nb_patch=-1`)? Can imagine that could yield objects larger than 4 GiB. Using a low rank approximation instead (`nb_patch=20` or `100` or so) would yield a smaller object, but might deteriorate results.
In the dev branch we added the option to return the background as `b` and `W`, compact while keeping it exact. You could try the dev branch with `gnb=0`. Actually, even returning the full rank background is more efficiently implemented in the dev branch, so `gnb=-1` might work too.

**Comment by zbarry** [comment]
Hmm interesting. Thanks for suggestions... will play around and let you know if there's just something trivial to go with in the future.

> Are you returning the full rank back ground (`nb_patch=-1`)?

Yup. Deterioration of the results is kind of why I'm trying `nb_patch=-1` right now. Some of the traces look pretty weird at the moment after deconvolution & I think some non-accounted for background is getting sucked into the AR model as spike events. For now, I'm just going to try to shorten my movies to 5 min and see if that indeed fixes my background problems. If not, maybe just going back to the low rank is good enough.

Going to hit up the dev branch. That sounds promising. Thanks!

**Comment by zbarry** [comment]
Quick Q - looks like there is a new `Estimates` object. is `my_cnmf_object.estimates.A` (`my_cnmf_object` of class `CNMF`) after `my_cnmf_object.fit(y)` equivalent to the old `my_cnmf_object.A`?

**Comment by zbarry** [comment]
Also, since I'm trying `gnb=0`, should I also then do `nb_patch=0`?

**Comment by j-friedrich** [comment]
Yes, `my_cnmf_object.estimates.A ` is equivalent to the old `my_cnmf_object.A`.
If you set `gnb=0`, `nb_patch` will automatically be set to `0`, even if you provide a value for it.

**Comment by zbarry** [comment]
Gotcha. Thanks. Will get back if I find some magic solution that solves all our problems.

**Comment by zbarry** [comment]
Actually, do you have a rough estimate of how much memory that `gnb=0` change saved? I wonder if `gnb=-1` used a metric ton of memory and now I have a lot more room to work in (to analyze longer movies). Also, would reducing the patch size help significantly? I'm working with 140x140 patches right now because memory (I thought wasn't) isn't a problem, and I believed this would cut down on potential edge artifacts even with the compensation for this during the patch integration stage.

**Comment by j-friedrich** [comment]
I finally did some memory profiling on some long 128z128x40000 data generated by simply concatenating the demodata 40 times. Though one wouldn't do that in praxis, I used a large single patch that was nevertheless processed in parallel mode in order to reproduce the errors.

Get the same `OverflowError: cannot serialize a bytes object larger than 4 GiB` as you do with master and `gnb=-1`, another (seemingly related) error `'i' format requires -2147483648 <= number <= 2147483647` with dev and `gnb=-1`, whereas dev with `gnb=0` runs through. 

The major difference is the amount of data that is shipped from the workers to the master process, which is much less (~factor 100) for `gnb=0`, whereas the total amount of required memory is about the same (28GB for dev with either `gnb=0` or `-1`, but 44GB for master `-1`).

**Comment by pgunn** [comment]
@zbarry This is not necessarily a great long-term solution, but there's a variant on multiprocessing that uses a different data transfer scheme; if you'd like to try it and don't mind using something that we might not be able to support (just found it today), you can try this:

`conda install pathos`
and then modify caiman/cluster.py so where it says `import multiprocessing`, have it instead say `import pathos.multiprocessing as multiprocessing`

I have no idea if this will work, and it may be something you'll need to remove later, but it's a possible route forward if you're feeling adventurous. If you do it, please let us know the results.

**Comment by zbarry** [comment]
@j-friedrich 

> Get the same OverflowError: cannot serialize a bytes object larger than 4 GiB as you do with master and gnb=-1, another (seemingly related) error 'i' format requires -2147483648 <= number <= 2147483647 with dev and gnb=-1, whereas dev with gnb=0 runs through.

Oh, that's great that it runs through with `gnb=0`. Our movies are max 36000 frames @ 20 Hz which are then downsampled anyway prior to the cnmf stage. I feel since I could always change my patch size down from my ridiculously big 140x140 patches too, I have a ton of wiggle room here re: running into memory issues. 

@pgunn - thanks for the link. That looks like a really cool library (and I might integrate it into my own processing pipelines in the future, haha.) I'm thinking based on the above, though, that I should be good to go for now!

Guess the takeaway from this now is that with `gnb=0` in the dev branch, this problem is hopefully no longer an issue for anyone unless they need huge patches for some reason or have incredibly long movies.

Thanks for looking into it, guyes!
