### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by UCLAmini-user** [flatironinstitute/CaImAn#360]
Hi, I'm using Jupyter notebook (Python 3.6) on mac OS X.

I didn't do any recording, so I ran the demo_pipeline on the given demo movie.
I ran into an error while running input [11]:

%%capture
#%% RUN CNMF ON PATCHES

#% First extract spatial and temporal components on patches and combine them
#% for this step deconvolution is turned off (p=0)
t1 = time.time()

cnm = cnmf.CNMF(n_processes=1, k=K, gSig=gSig, merge_thresh= merge_thresh, 
                p = 0,  dview=dview, rf=rf, stride=stride_cnmf, memory_fact=1,
                method_init=init_method, alpha_snmf=alpha_snmf, 
                only_init_patch = False, gnb = gnb, border_pix = bord_px_els) 
cnm = cnm.fit(images)

And this is the error log I got:

---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, options, rf, stride, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates)
    451             try:
--> 452                 f = np.linalg.inv(b.T.dot(b)).dot((Bm.T.dot(b)).T.dot(F_tot))
    453             except np.linalg.LinAlgError:  # singular matrix

~/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py in inv(a)
    527     extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 528     ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
    529     return wrap(ainv.astype(result_t, copy=False))

~/anaconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py in _raise_linalgerror_singular(err, flag)
     88 def _raise_linalgerror_singular(err, flag):
---> 89     raise LinAlgError("Singular matrix")
     90 

LinAlgError: Singular matrix

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-11-2b61ff959181> in <module>()
      9                 method_init=init_method, alpha_snmf=alpha_snmf,
     10                 only_init_patch = False, gnb = gnb, border_pix = bord_px_els) 
---> 11 cnm = cnm.fit(images)

~/anaconda3/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images)
    569                                                                      gnb=self.gnb, border_pix=self.border_pix,
    570                                                                      low_rank_background=self.low_rank_background,
--> 571                                                                      del_duplicates=self.del_duplicates)
    572 
    573             # options = CNMFSetParms(Y, self.n_processes, p=self.p, gSig=self.gSig, K=A.shape[

~/anaconda3/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, options, rf, stride, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates)
    452                 f = np.linalg.inv(b.T.dot(b)).dot((Bm.T.dot(b)).T.dot(F_tot))
    453             except np.linalg.LinAlgError:  # singular matrix
--> 454                 f = scipy.linalg.lstsq(b, Bm.toarray())[0].dot(F_tot)
    455 
    456         nB = np.ravel(np.sqrt((b**2).sum(0)))

~/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py in lstsq(a, b, cond, overwrite_a, overwrite_b, check_finite, lapack_driver)
   1153     """
   1154     a1 = _asarray_validated(a, check_finite=check_finite)
-> 1155     b1 = _asarray_validated(b, check_finite=check_finite)
   1156     if len(a1.shape) != 2:
   1157         raise ValueError('expected matrix')

~/anaconda3/lib/python3.6/site-packages/scipy/_lib/_util.py in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    236             raise ValueError('masked arrays are not supported')
    237     toarray = np.asarray_chkfinite if check_finite else np.asarray
--> 238     a = toarray(a)
    239     if not objects_ok:
    240         if a.dtype is np.dtype('O'):

~/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py in asarray_chkfinite(a, dtype, order)
   1231     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
   1232         raise ValueError(
-> 1233             "array must not contain infs or NaNs")
   1234     return a
   1235 

ValueError: array must not contain infs or NaNs

I also get errors while running demo_pipeline_cnmfE with the demo movie. May I be doing something wrong?
Thank you in advance!

**Comment by davegrays** [comment]
@UCLAmini-user how did you resolve the issue? I am running into similar errors
