### ISSUE TITLE
Current multiprocessing configuration might not be appropriate for an HPC environment

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#361]
I'm running CaImAn on a cluster with a GridEngine scheduler using a little wrapper application I wrote. I was actually notified by one of the cluster admins that the way the job is using threads is suboptimal to the stability of all jobs on a node (and possibly computational efficiency). Apparently the cluster activity monitor flagged my jobs as overloading the nodes they were running on...

When I launch a job to run the CNMF stage, I create a `Client` with:

`setup_cluster(backend='local', n_processes=10, single_thread=False)`

inside the running job. This creates the 10 `multiprocessing` subprocesses as expected.

The issue, however, is that each of these subprocesses are then spawning 10 of their own threads which each utilize 10% of their respective CPU. I'm pretty sure this is because of the `cv2.setNumThreads(0)` preamble command in the `caiman.source_extraction.cnmf.cnmf` module. I'm wondering... is there any point in using multithreaded OpenCV processing in this case, when you've already divided up all the CPUs for individual subprocesses? If each of those threads could have used 100% of the CPU all by itself (an assumption), then creating the 10 would slow things down a bit due to the context switching between all the threads competing for time. It appears that performance degradation is indeed happening: after the "fix" below was applied, the jobs seemed to finish significantly faster (though I'm not sure the admin would appreciate me going back and quantifying how much faster...)

Our solution for now was to just add `export OMP_NUM_THREADS=1` to my submission scripts to keep OpenCV's calls to OpenMP from spawning more than one thread to work with. It works, but it might be worth considering setting `cv2.setNumThreads(N)` w.r.t. the `Client` configuration chosen.

**Comment by pgunn** [comment]
Hi,
According to the OpenCV docs:
https://docs.opencv.org/3.3.1/db/de0/group__core__utils.html#gae78625c3c2aa9e0b83ed31b73c6549c0

calling opencv.setNumThreads(0) will disable threading. If our code is somehow leading to more threads, it should not relate to the setNumTreads call.

**Comment by zbarry** [comment]
Hmm, ok. Sorry, should have checked the docs! I was on my way out. I'll keep any eye out for it in the future.

**Comment by pgunn** [comment]
No worries - if some builds of OpenCV are calling into OpenMP, and OpenMP has this behaviour, we may want to add your env var to the documentation as a good thing to set. So far I don't recall anyone else running into this ; do you mind doing a conda list and showing us what version of OpenCV you have? It'd be helpful in knowing whether others are likely to hit this issue.

**Comment by zbarry** [comment]
Sure. Will do when I get back in.

**Comment by zbarry** [comment]
You know what... For some reason, when I created my conda environment on the cluster, I installed the PyPI version of OpenCV:

`opencv-python             3.4.1.15                  <pip>`

I'm guessing this version has the issue you're referring to here in `CLUSTER.md`:

> OpenCV is not easy to use safely with multithreaded or multi-process software. We take steps to disable multithreading in OpenCV, but **some builds of it may not allow this**. If you run into these issues let us know; we may ask you to switch the OpenCV version you use (Conda makes this easy).

Whoops... (my bad, x2)

Think that was it?

**Comment by pgunn** [comment]
It's a jungle of confusion to wade through; no worries. Still, what you describe above sounds more like the root cause is that your OpenCV calls into OpenMP, rather than OpenCV itself doing anything objectionable. If you do a "conda install opencv" (you might need the "reinstall" flag instead, but try install first), it might get you a version without the OpenMP bindings.

**Comment by zbarry** [comment]
Sorry for the delay in getting back to you!

> OpenCV calls into OpenMP, rather than OpenCV itself doing anything objectionable

Yeah, I think this is exactly it. Thanks for the suggestion! Pretty sure we can close this, and I'll let you know if anything weird crops up in the future with even the Anaconda version of OpenCV.
