### ISSUE TITLE
spike matrix S not returned for 1P data in patch mode

### ISSUE THREAD

**Issue by mschachter** [flatironinstitute/CaImAn#363]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**
Operating System: CENTOS 7
Python Version: Anaconda 3.6
CaImAn Branch: dev
Environment: Typical caiman environment installed with conda env
Dataset: Available here (~50MB):
https://drive.google.com/file/d/1cRBTuawSqiMFZoHLMmYXkZLhcmkX2DKo/view?usp=sharing

- **Describe the issue that you are experiencing**
The matrix cnmfe.estimates.S == None when running in 1P mode using patches. This occurs both in the example data supplied above, without using IPython cluster (dview == None), and also for the full movie with IPython cluster (dview != None).

- **Code to reproduce**
This runs in 5-10 minutes on the sample data provided above:
```python
import os
from caiman import load_memmap
from caiman.source_extraction.cnmf import CNMF
from caiman.components_evaluation import estimate_components_quality_auto
from caiman.source_extraction.cnmf.params import CNMFParams

# set the params
frame_rate = 10.0
decay_time = 0.400
min_SNR = 3

cnmfe_params = CNMFParams(k=25, gSiz=(13, 13), decay_time=decay_time, min_pnr=2, min_SNR=min_SNR, p=1,
                          merge_thresh=0.8, ssub=1, tsub=2, p_ssub=1, p_tsub=1, method_init='corr_pnr',
                          min_corr=0.80, ssub_B=2, ring_size_factor=1.5, only_init_patch=True,
                          center_psf=True,
                          rf=(16, 16), stride=(6, 6),
                          low_rank_background=None, nb_patch=-1, gnb=-1)

# load the file
root_dir = '/path/to/downloaded/file'
mov_file = os.path.join(root_dir, 'recording_20160517_172653-cropped_d1_116_d2_135_d3_1_order_C_frames_4298_.mmap')
Yr, dims, T = load_memmap(mov_file)
Y = Yr.T.reshape((T,) + dims, order='F')

# fit the data
num_procs = 1
cnmfe = CNMF(num_procs, dview=None, params=cnmfe_params)
cnmfe.fit(Y)

assert cnmfe.estimates.S is not None, "spike matrix S is None"
```

**Comment by j-friedrich** [comment]
added in dev
