### ISSUE TITLE
shape error in Estimates.normalize in 1P mode

### ISSUE THREAD

**Issue by mschachter** [flatironinstitute/CaImAn#366]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**
Operating System: CENTOS 7
Python Version: Anaconda 3.6
CaImAn Branch: dev
Environment: Typical caiman environment installed with conda env 
Dataset: Available here (~50MB):
https://drive.google.com/file/d/1cRBTuawSqiMFZoHLMmYXkZLhcmkX2DKo/view?usp=sharing

- **Describe the issue that you are experiencing**
*Note that this problem does not occur when tsub=2*. When I set tsub=1, as in the code below, there is a shape error that occurs after the 1P cell extraction is run, in the Estimates.normalize() function. I should also note that tsub=1, but ssub_B=2. When I set ssub_B=1, there is no longer an error. Not sure why spatial downsampling of the background is interacting with temporal downsampling of movie?

- Here is the code to reproduce the issue, after downloading the file linked above:
```python
import os
from caiman import load_memmap
from caiman.source_extraction.cnmf import CNMF
from caiman.components_evaluation import estimate_components_quality_auto
from caiman.source_extraction.cnmf.params import CNMFParams

cnmfe_params = CNMFParams(k=25, gSiz=(13, 13), decay_time=400e-3,
                                                   min_pnr=2, min_SNR=3, p=1,
                                                   merge_thresh=0.8, ssub=1, tsub=1,
                                                   p_ssub=1, p_tsub=1, method_init='corr_pnr',
                                                   min_corr=0.80, ssub_B=2, ring_size_factor=1.5,
                                                   only_init_patch=True, center_psf=True,
                                                   low_rank_background=None, nb_patch=-1, gnb=-1)

# load the file
root_dir = '/path/to/downloaded/file'
mov_file = os.path.join(root_dir, 'recording_20160517_172653-cropped_d1_116_d2_135_d3_1_order_C_frames_4298_.mmap')
Yr, dims, T = load_memmap(mov_file)
Y = Yr.T.reshape((T,) + dims, order='F')

# fit the data
num_procs = 1
cnmfe = CNMF(num_procs, dview=None, params=cnmfe_params)
cnmfe.fit(Y)
```

- Here is the error reported:
```
Traceback (most recent call last):
  File "/home/mschachter/code/isx-cnmfe/scripts/zero_cells_bug.py", line 30, in <module>
    cnmfe.fit(Y)
  File "/home/mschachter/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 476, in fit
    self.estimates.normalize_components()
  File "/home/mschachter/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/estimates.py", line 604, in normalize_components
    self.f = nB_mat * self.f
  File "/home/mschachter/anaconda3/envs/caiman/lib/python3.6/site-packages/scipy/sparse/base.py", line 405, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
```
- Here is some debugging information:
This is the code block that is failing (starting on line 593 of estimates.py):
```python
        if self.f is not None:  # 1p with exact ring-model
            nB = np.sqrt(np.ravel((self.b.power(2) if scipy.sparse.issparse(self.b)
                         else self.b**2).sum(axis=0)))
            nB_mat = scipy.sparse.spdiags(nB, 0, nB.shape[0], nB.shape[0])
            nB_inv_mat = scipy.sparse.spdiags(1. / nB, 0, nB.shape[0], nB.shape[0])
            self.b = self.b * nB_inv_mat
```

The difference between tsub=1 and tsub=2 is in the size of self.b, the background term:
* For tsub=1, self.b.shape = (15560, 1)
* For tsub=2, self.b.shape = (15560, 15560)

So in all likelihood there is something going on with initialization, probably in the greedyROI_corr function of initialize.py.

**Comment by epnev** [comment]
I added an if command to avoid the error but I have no idea why the `b` has different shapes depending on tsub. @j-friedrich take a look.

**Comment by mschachter** [comment]
I can confirm that the latest dev branch fixes the issue, when ssub == 1, tsub == 1, and ssub_B == 2. Thanks!!

**Comment by j-friedrich** [comment]
Fixed, so that `b` has the proper shape in both cases for `tsub`.
