### ISSUE TITLE
Segmentation fault (core dumped) on `caimanmanager.py` install

### ISSUE THREAD

**Issue by ronnyb29** [flatironinstitute/CaImAn#367]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**
Linux Ubuntu 16.04, Python 3.6.6. Clean EC2 instance created solely to install caiman.

- **Describe the issue that you are experiencing**
I want to use caiman manager but am unable to install. Get a classic seg fault on the install script.

- **Copy error log below**
```
python caimanmanager.py install
Segmentation fault (core dumped)
```

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
Are you using python from conda, or some other python? If you do "strace python caimanmanager.py install", you'll get a full (and very noisy) trace of what went on, and somewhere in the last few lines hopefully there'd be a hint as to the problem.

**Comment by pgunn** [comment]
To give a little more context, that import will import a fair amount of the rest of the codebase, including some of the things caiman depends on. My intuition is that one of those libraries, maybe Keras or one of the maths libraries, is segfaulting during initialisation. We'll want to figure out why.

**Comment by ronnyb29** [comment]
Apologies for the delay - I'm using python from conda

**Comment by pgunn** [comment]
That could be helpful, yes. Running your conda env's python under gdb might be a little more involved, but it also might be a way to get more of a hint where the problem is happening.

**Comment by pgunn** [comment]
@ronnyb29 Hi, any news on this? It'd be great not to leave issues open for too long without movement on them.

**Comment by pgunn** [comment]
Closing this issue to inactivity; please reopen if you're still having issues.
