### ISSUE TITLE
Setting Parameters

### ISSUE THREAD

**Issue by MarkCBenz** [flatironinstitute/CaImAn#370]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**

Windows/ Python 2.7/ Jupyter Notebook 

- **If you're not reporting an error, type your message below**

I would like to use the demo_pipline.ipynb to extract some traces from some 2p video. At the moment, the found components are much smaller than the neurons that are apparent in the video. Which parameters should I consider adjusting in order for the program to 'look for' larger areas to identify components? Any help is greatly appreciated.

best,
Mark

**Comment by epnev** [comment]
@MarkCBenz You should try increasing the value of `gSig` which corresponds to the radius (in pixels) of a neurons on average. You can also increase the `rf` value. 

Please also note that we do not support Python 2.7 in windows and you should consider switching to Python 3.

**Comment by MarkCBenz** [comment]
@epnev thanks!
