### ISSUE TITLE
Cannot find the example_movies

### ISSUE THREAD

**Issue by HunterTom94** [flatironinstitute/CaImAn#372]
Hi, I am using Win10, python 3.6 in Jupyter Notebook.

In the third section of demo_pipeline.ipynb, I got the following error.

Exception                                 Traceback (most recent call last)
<ipython-input-3-2af042ebf6cf> in <module>()
      1 if fname[0] in ['Sue_2x_3000_40_-46.tif','demoMovie.tif']:
----> 2     fname = [download_demo(fname[0])]

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\utils.py in download_demo(name, save_folder)
     97             print("File already downloaded")
     98     else:
---> 99         raise Exception('Cannot find the example_movies folder in your caiman_datadir - did you make one with caimanmanager.py?')
    100     return path_movie
    101 

Exception: Cannot find the example_movies folder in your caiman_datadir - did you make one with caimanmanager.py?

However, under the CaImAn folder, I can find a folder named 'example_movies' and there are three files in it. 

In the Anaconda Prompt, I also tried 'python caimanmanager.py'. However, it requires more argument and I do not know which one of the three argument prompted to use.

Thanks for the help!

**Comment by pgunn** [comment]
Hi,
From the anaconda prompt, do "python caimanmanager.py install"
This will make for you a datadir, independent of the sources, that you will be working from.

**Comment by HunterTom94** [comment]
Thank
