### ISSUE TITLE
Failure on running CNMF

### ISSUE THREAD

**Issue by HunterTom94** [flatironinstitute/CaImAn#373]
Hi, I am using Win10, python 3.6 in Jupyter Notebook.

I am modifying demo_pipeline.ipynb to run my own 1 photon imaging video.

The original demo_pipeline.ipynb can be executed without any problem.

When I was running the first section under CNMF, I had the following issue.

MemoryError                               Traceback (most recent call last)
<ipython-input-12-2b61ff959181> in <module>()
      9                 method_init=init_method, alpha_snmf=alpha_snmf,
     10                 only_init_patch = False, gnb = gnb, border_pix = bord_px_els) 
---> 11 cnm = cnm.fit(images)

F:\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images)
    651 
    652         self.A, self.C, self.YrA, self.b, self.f, self.neurons_sn = normalize_AC(
--> 653             self.A, self.C, self.YrA, self.b, self.f, self.neurons_sn)
    654 
    655         return self

F:\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\utilities.py in normalize_AC(A, C, YrA, b, f, neurons_sn)
   1113 
   1114     if A is not None:
-> 1115         A /= nA
   1116 
   1117     if C is not None:

F:\Anaconda3\envs\caiman\lib\site-packages\scipy\sparse\base.py in __truediv__(self, other)
    613 
    614     def __truediv__(self, other):
--> 615         return self._divide(other, true_divide=True)
    616 
    617     def __div__(self, other):

F:\Anaconda3\envs\caiman\lib\site-packages\scipy\sparse\base.py in _divide(self, other, true_divide, rdivide)
    592             if not rdivide:
    593                 if true_divide:
--> 594                     return np.true_divide(self.todense(), other)
    595                 else:
    596                     return np.divide(self.todense(), other)

MemoryError: 

I did change the virtual memory to 64GB according to the instruction. I do not know why this memory issue occurs.

Thank you very much!

**Comment by epnev** [comment]
@HunterTom94 How big is your file?

**Comment by HunterTom94** [comment]
481MB

**Comment by epnev** [comment]
@HunterTom94 That shouldn't be an issue. How much memory do you have?

**Comment by HunterTom94** [comment]
@epnev Sorry for the late reply, I have 16GB RAM. I checked the usage right before I run the section in Jupyter Notebook, 40% of the RAM was in use.

**Comment by HunterTom94** [comment]
@epnev I just changed the tif file from 16 bit to 8 bit and the file sized is half of the original (241 MB for 8 bit). There is still the same error. The mmap file that is loaded in the memory mapping step right before CNMF is 960MB.

**Comment by epnev** [comment]
@HunterTom94 That shouldn't matter because everything will be converted to single precision at the end. Have you tried spatial downsampling, e.g., setting `ssub=2`?

**Comment by HunterTom94** [comment]
@epnev I tried to set ssub = 2 when I called the CNMF constructor, same error

**Comment by epnev** [comment]
@HunterTom94 Does this happen to all your files or just this one?

**Comment by HunterTom94** [comment]
@epnev For now I only tested with 2 videos. The other video does not have this error. (Although the output of extracted source does not make any sense, because the accepted areas are all over the FOV.) 

The other video's shape is (79, 128 ,128). It is 1 MB big.
