### ISSUE TITLE
Source extraction on video imaging dendrites 

### ISSUE THREAD

**Issue by HunterTom94** [flatironinstitute/CaImAn#375]
Hi, I am using Win10, python 3.6 in Jupyter Notebook.

In many demos files, I found a parameter called 'is_dendrites' and is set to False by default. Since I want to perform source extraction on a video that includes both cell body and dendrites, I want to set is_dendrites to True, but nothing happened. I then searched for this variable in the code but it is not used anywhere else, at least in the demos code. I also looked up in the documentation and cannot find more information.

I am a bit confused about how to use this variable.

**Comment by epnev** [comment]
@HunterTom94 You can safely ignore this.
