### ISSUE TITLE
Index out of range during motion correct

### ISSUE THREAD

**Issue by kareemcheese96** [flatironinstitute/CaImAn#377]
- Windows 10, numpy, python 3.7

- The current file I am now working with has more than 200 frames (9000) and it gives the following error at the motion correct line min_mov = min(cm.load(fname[0], subindices=range(200)).min(),0): 

line 2992, in _seek
raise IndexError('list index out of range')

IndexError: list index out of range

 When I remove the subindices argument or replace range with slice, I get the following error at the mc.motion_correct_pwrigid(save_movie=True) line:

line 180, in motion_correct
10e7, (self.shape[1] * self.shape[2]))

IndexError: tuple index out of range

**Comment by epnev** [comment]
@kareemcheese96 What is the output of
```
cm.load(fname[0]).shape
```

**Comment by kareemcheese96** [comment]
> @kareemcheese96 What is the output of
> 
> ```
> cm.load(fname[0]).shape
> ```

That gives an error of 
  line 222, in motion_correct_rigid
    print(-self.min_mov)

TypeError: bad operand type for unary -: 'tuple'

at the mc.motion_correct_pwrigid(save_movie=True)  line

**Comment by epnev** [comment]
@kareemcheese96 Just type this command without calling any motion correction methods.

**Comment by kareemcheese96** [comment]
> @kareemcheese96 Just type this command without calling any motion correction methods.

Oh sorry. The output of it is (9000, 800, 800)

**Comment by epnev** [comment]
@kareemcheese96 
Ok, I'm trying to understand where things break down. 
How about this one?
```
cm.load(fname[0], subindices=range(200))
```

**Comment by kareemcheese96** [comment]
@epnev Okay sounds good. That one gives an error

raise IndexError('list index out of range')

IndexError: list index out of range

**Comment by epnev** [comment]
@kareemcheese96 That's weird. What's the extension of the file?

**Comment by kareemcheese96** [comment]
@epnev it's .tif

**Comment by epnev** [comment]
@kareemcheese96 Most likely, your tiff file is read as a single block instead of a sequence of pages. This happens sometimes especially with files saved through fiji/imagej. Is this the case for you?

**Comment by kareemcheese96** [comment]
@epnev Oh yes, I did save using fiji/imagej. How can I fix this so that the tiff file is read as a sequence of pages?

**Comment by epnev** [comment]
@kareemcheese96 Not sure. What is the version of your tifffile package?
You can type the following from your anaconda enabled command prompt
```
conda list tifffile
```

**Comment by kareemcheese96** [comment]
@epnev The version is 0.15.1

**Comment by kareemcheese96** [comment]
@epnev I just ran a 4600 frame file and it went through the pipeline without any issues, even though it was also a .tif that was saved through fiji/imagej

**Comment by epnev** [comment]
@kareemcheese96 It doesn't happen all the time which makes this more confusing. You can load and save your file and then re-process it if necessary.
```
movie = cm.load(fnames[0])
movie.save('new_filename.tif')
```
This by default will save the file with 32bit (single) precision. If you want to save it in the original format (e.g., uint16 or uint8) to save on file size you can do instead e.g.
```movie.astype(‘uint16’).save(`new_filename.tif`, to32=False)```

**Comment by cgohlke** [comment]
> It doesn't happen all the time which makes this more confusing

ImageJ only saves one TIFF page/IFD if the file is larger than 4 GB.

**Comment by kareemcheese96** [comment]
@epnev yes it did resolve the issue. Thank you for all of your help!
