### ISSUE TITLE
Value Error for Some Files

### ISSUE THREAD

**Issue by kareemcheese96** [flatironinstitute/CaImAn#384]
For better support, please use the template below to submit your issue.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- Windows 10, numpy, python 3.7

- Most videos that I have run are getting through the pipeline without any issue. However, some of them are giving a value error.

- At the cnm = cnm.fit(images) line, the following error pops up: 

 line 1215, in asarray_chkfinite
    "array must not contain infs or NaNs")

ValueError: array must not contain infs or NaNs

Does this mean that the file itself is corrupted in some way, or is there a way around this error?

Thank you again for all of your help!

**Comment by agiovann** [comment]
@kareemcheese96 Does the movie contain NaNs or infinite values? Or does the movie contain pixels whose standard deviation is 0 (constant value in time)?

**Comment by kareemcheese96** [comment]
@agiovann I do not believe it contains any NaNs or infinite values, it should contain pixels with SD of 0. I apologize for the simplicity of this question, but is there a way for me to confirm that it contains pixels with SD as 0?

**Comment by agiovann** [comment]
if this list is non empty then you have such values np.where(np.std(images,0)==0)

**Comment by kareemcheese96** [comment]
@agiovann Sorry for the delayed response. The output that it gives is 
Out[7]: (array([], dtype=int64), array([], dtype=int64))

**Comment by epnev** [comment]
@kareemcheese96 Can you provide a more complete message. I'd like to understand where this error occurs exactly. Also make sure you run with `dview=None`.

**Comment by kareemcheese96** [comment]
@epnev Yes, this is the complete error message.

Traceback (most recent call last):

  File "<ipython-input-6-3eae6d4a0fef>", line 71, in <module>
    cnm = cnm.fit(images)

  File "C:\Users\SvendsenLab\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 571, in fit
    del_duplicates=self.del_duplicates)

  File "C:\Users\SvendsenLab\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\map_reduce.py", line 454, in run_CNMF_patches
    f = scipy.linalg.lstsq(b, Bm.toarray())[0].dot(F_tot)

  File "C:\Users\SvendsenLab\Anaconda3\envs\caiman\lib\site-packages\scipy\linalg\basic.py", line 1155, in lstsq
    b1 = _asarray_validated(b, check_finite=check_finite)

  File "C:\Users\SvendsenLab\Anaconda3\envs\caiman\lib\site-packages\scipy\_lib\_util.py", line 238, in _asarray_validated
    a = toarray(a)

  File "C:\Users\SvendsenLab\Anaconda3\envs\caiman\lib\site-packages\numpy\lib\function_base.py", line 1215, in asarray_chkfinite
    "array must not contain infs or NaNs")

ValueError: array must not contain infs or NaNs

**Comment by kareemcheese96** [comment]
@epnev In the pipeline dview is set as dview=dview at multiple points. Should I change that to dview=None only at the following line, or at all instances?

cnm = cnmf.CNMF(n_processes=1, k=K, gSig=gSig, merge_thresh=merge_thresh,
                        p=0, dview=dview, rf=rf, stride=stride_cnmf, memory_fact=1,
                        method_init=init_method, alpha_snmf=alpha_snmf,
                        only_init_patch=False, gnb=gnb, border_pix=bord_px_els)
        cnm = cnm.fit(images)

**Comment by kareemcheese96** [comment]
@agiovann @epnev Thank you for your help! That got them through the pipeline without any issue.

**Comment by epnev** [comment]
@kareemcheese96 Glad this is fixed, but it is weird that you get an error if you set `dview=dview` but you don't if you set `dview=None`. Have you set the environment variables `MKL_NUM_THREADS=1` and `OPENBLAS_NUM_THREADS=1`?

**Comment by kareemcheese96** [comment]
@epnev So one of the videos got through the pipeline, but the rest still give the same error after I set dview=None. I have not set the environment variables as such, would that fix the error? If so, do I set those in the command prompt?

**Comment by epnev** [comment]
Yes, you do that in the command prompt.
@pgunn Can you give instructions, also update the installation instructions for environment variable setting in windows?

**Comment by pgunn** [comment]
Hi,
So on Windows, you would issue the following commands after every time you enter your conda environment:
```
SET MKL_NUM_THREADS=1
SET OPENBLAS_NUM_THREADS=1
```
I hope this helps.

**Comment by kareemcheese96** [comment]
Sorry, we have been trying to figure out if the error can be attributed to the file conversion that we do after acquisition. The file is acquired as a CXD, and we convert it to a tif through fiji/imagej. Just trying to confirm whether this is the issue or not before sending over the example, to be sure

**Comment by epnev** [comment]
@kareemcheese96 Bear in mind that if you create a tif file through fiji/imagej that is larger than 4GB, it will be saved as a single page tif file. This can create various performance problems in the pipeline since the whole file will be loaded in memory every time you call it, even tough you would only need to load a few frames from it.
