### ISSUE TITLE
Status of dF/F calculation?

### ISSUE THREAD

**Issue by HagaiHargil** [flatironinstitute/CaImAn#389]
Hi, I was wondering what the current status of dF/F calculation is. I've reported on several issues with the resulting numbers from the `detrend_df_f` function in `source_extraction.cnmf.utilities` a while back (in the gitter), and @epnev kindly inspected my data and wrote `detrend_df_f_auto`, which significantly improved the correlation between the automatic dF/F calculation and manual calculation. 

Our lab has been using `detrend_df_f_auto` ever since, but with all of the recent updates and refactoring done I was wondering what the current status of these functions is. For example, the `estimates` object still links by default to the "old" `detrend_df_f`, and can I also see the `extract_DF_F` function which seems to be "deprecated". 

I'm looking for these clarifications since the dF/F metric is perhaps the most important metric users take from the entire pipeline, and I'd be happy to be aware of any improvements made to it.

Thanks.

**Comment by epnev** [comment]
@HagaiHargil The `detrend_df_f` function now essentially replicates the `detrend_df_f_auto` if the variable `flag_auto` is set to `True` which is also its default value. So essentially, the `estimates` will by default call the old `detrend_df_f_auto`. I want to also include a more manual method that computes DF/F using the traditional annulus approach since it appears that in some cases you kind of have to do this.

**Comment by HagaiHargil** [comment]
That's great to hear! 

I see that one of the older bugs of `detrend_df_f_auto` found its way to the new `detrend_df_f` - [This line](https://github.com/flatironinstitute/CaImAn/blob/7df61047f3bbb3dda40e9e2666667b4f5e290527/caiman/source_extraction/cnmf/utilities.py#L332) should be identical to [this one](https://github.com/flatironinstitute/CaImAn/blob/7df61047f3bbb3dda40e9e2666667b4f5e290527/caiman/source_extraction/cnmf/utilities.py#L476), I believe.

**Comment by epnev** [comment]
@HagaiHargil You're right. I update it, thanks!

**Comment by HagaiHargil** [comment]
@epnev Thank you for the quick fix. 

Another bug I discovered is that when CaImAn detected zero active components, the function will crash. You're checking for this edge case [here](https://github.com/flatironinstitute/CaImAn/blob/0b24d059ae8a59ec7933e347f20e48e0172c22af/caiman/source_extraction/cnmf/estimates.py#L548), by checking `if self.C is None`, but (at least on our datasets) when there are no components the shape of `self.C` is `(0, NUM_OF_FRAMES)`, and not `None`. That is, `self.C` exists, so this check fails to identify this case. Instead, you have to check whether `if self.C.shape[0] == 0`.

**Comment by epnev** [comment]
@HagaiHargil Thanks, again. I modified to also check for this condition. In the future, feel free to submit pull requests for other bugs you encounter.

**Comment by cyberfag** [comment]
@epnev Hi. Could you please explain how exactly caiman.source_extraction.cnmf.utilities.detrend_df_f calculates df/f? I didn't find detailed explanation in the docs, and reading the code didn't make it completely clear to me. As far as I understand, in general, df/f = (f-f0)/f0, so, basically, it's a matter of defining f0. In detrend_df_f, f0 is the average signal of coordinates that do not fall into selected components areas or what? And what's the role of percentile? Thanks in advance.

**Comment by qweasdf1354** [comment]
> @epnev Hi. Could you please explain how exactly caiman.source_extraction.cnmf.utilities.detrend_df_f calculates df/f? I didn't find detailed explanation in the docs, and reading the code didn't make it completely clear to me. As far as I understand, in general, df/f = (f-f0)/f0, so, basically, it's a matter of defining f0. In detrend_df_f, f0 is the average signal of coordinates that do not fall into selected components areas or what? And what's the role of percentile? Thanks in advance.

Yes i also want to know how to calculates df/f and what is the F0
