### ISSUE TITLE
Idea to use demo_OnACID_mesoscope

### ISSUE THREAD

**Issue by bingcao2** [flatironinstitute/CaImAn#394]
Hi All,

I am testing the demo of OnACID on our microscope data recorded in different days. To compare the demo data from Dr. Tolias, which background brightness are quite similar, the brightness of our data fluctuated very much. These unstable conditions induce huge changes at boundaries among data, that make further analysis becomes impossible. 
So I am trying to use pipeline_cnmfE to save a .mmap file without backgroup (such as play_movie(include_bck=False)). However, the recent saved file is the motion-corrected one, which still has the background. So could you teach me some helpful script to save a non-background that I can add in the current pipeline file? Or you can tell me where I could find the manual to learn the caiman functions.
Many thanks!

Best,
Bing

**Comment by epnev** [comment]
@bingcao2 
If I understand your question correctly you can use something like this:
```
denoised = cm.movie((cnm.estimates.A.dot(cnm.estimates.C)).reshape(dims + (-1,), order='F').transpose([2, 0, 1]))
denoised.save('processed_movie.tif')
```
Does this work? To understand how this works, check this [wiki entry](https://github.com/flatironinstitute/CaImAn/wiki/Interpreting-Results) on how each variable works.

Also, do your problems with spyder/pycharm in #391 still persist?

**Comment by bingcao2** [comment]
> @bingcao2
> If I understand your question correctly you can use something like this:
> 
> ```
> denoised = cm.movie((cnm.estimates.A.dot(cnm.estimates.C)).reshape(dims + (-1,), order='F').transpose([2, 0, 1]))
> denoised.save('processed_movie.tif')
> ```
> Does this work? To understand how this works, check this [wiki entry](https://github.com/flatironinstitute/CaImAn/wiki/Interpreting-Results) on how each variable works.
> 
> Also, do your problems with spyder/pycharm in #391 still persist?

Thank you epenv. The code works very well!
For the issue #391, I haven't find the correct way to copy the ∆F/F.
Since the code to plot each curve is already in the demo, is it possible to copy all of them into clipboard for further analysis? Many thanks for your help!
```
cnm.estimates.nb_view_components(img=cn_filter, idx=cnm.estimates.idx_components,
                                denoised_color='red', cmap='gray')
```
