### ISSUE TITLE
error when importing cnmf

### ISSUE THREAD

**Issue by yufu1981** [flatironinstitute/CaImAn#395]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
MacOS 10.13.6
Python 3.6.2
Spyder

- **Describe the issue that you are experiencing**
I'm very new to Caiman and just started to play with it
I'm simply typing in the Spyder console:
from caiman.source_extraction import cnmf
and got error message

- **Copy error log below**
Traceback (most recent call last):

  File "<ipython-input-11-ddfcfa11033b>", line 1, in <module>
    from caiman.source_extraction import cnmf

  File "/Users/fuyu/CaImAn/caiman/source_extraction/cnmf/__init__.py", line 12, in <module>
    from . import oasis

ImportError: cannot import name 'oasis'

- **If you're not reporting an error, type your message below**
n.a.

thanks you

**Comment by j-friedrich** [comment]
Please try to recompile oasis (reinstall caiman with pip install .)

**Comment by yufu1981** [comment]
I remove the caiman folder under anaconda3/envs and reinstalled Caiman using:
cd CaImAn/
conda env create -f environment.yml -n caiman
source activate caiman
pip install .

still get this error message.

it's ok to do import caiman as cm, but always get same error message when doing anything related with cnmf

**Comment by pgunn** [comment]
Hi,
when you do this, please make sure you then use caimanmanager to make a data folder (which has code samples and demos) and that you run the demos from there; you should not work from inside the source tree.

**Comment by yufu1981** [comment]
thanks. everything works now.
