### ISSUE TITLE
Future of visualizing live outputs of OnACID?

### ISSUE THREAD

**Issue by tom1193** [flatironinstitute/CaImAn#408]
Are there any plans to support a feature that visualizes the outputs of a running OnACID program in live time? As referenced in the OnACID paper, this would allow for closed-loop experiments in which the experimentor change the stimulus or other experimental conditions based on the recorded neural activity.

I have been [working on a server](https://github.com/tom1193/servaiman) that can pipe the outputs of an OnACID algorithm into a visualization application. Before I think about building this visulization feature, I'm wondering if the CaImAn team has plans to support this in the near future. If so, I would be interested in contributing.

**Comment by epnev** [comment]
@tom1193 We definitely have plans to use OnACID for closed loop experiments and are thinking about the best way to do this. Right now you have the option to generate a movie of the processed results while analyzing the data by setting `show_movie=True` in the `params` object. We can talk more to understand what you have in mind. @agiovann

**Comment by agiovann** [comment]
dear @tom1193 can you tell us more about the application? What visual framework are you using? We definitively would like to extend this with that capability in the near future.

**Comment by epnev** [comment]
@tom1193 
> One challenge is that the output matrices can be large and every iteration of the algorithm changes the entries in the matrix rather than simply appending to past data, which means the entire plot has to re-render at every frame.

There are two different cases there depending on whether you update all shapes at once every N frames (default) or whether you update a *few* shapes at every frame. This is governed by the boolean parameter `params.online.dist_shape_update`. In any case these updates mostly change the shape and not the position so after a few frames the position of the components is more or less stabilized. At any case you can grab only a few columns of the matrix and update the contours only there. What would be more important is to display new neurons that are being detected as the algorithm proceeds.

**Comment by jmxpearson** [comment]
I think the current approach @hawkwings has been working on is Python-based and so a little easier to modify. But we’ve done very little along visualization lines. 

Likely the priority should first be to just figure out the incremental computation bit, after which one can think about moving visualization to GPU libraries.
