### ISSUE TITLE
problems with pyqt and spyder or mac

### ISSUE THREAD

**Issue by epnev** [flatironinstitute/CaImAn#409]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

macOS, Python 3.6, Spyder

- **Describe the issue that you are experiencing**

I'm having a problem similar to #391 on my mac. Wile creating a new environment the following version `pyqt` was installed from conda-forge:
```
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
```
This causes spyder crash before loading giving the error copied below.

Note that:
1. The problem does not appear on linux with exactly the same version of pyqt
2. With my older version of pyqt (still 5.6.0)
```
pyqt                      5.6.0                    py36_5    conda-forge
```
things work fine on the mac.

- **Copy error log below**

```
Traceback (most recent call last):
  File "/Users/epnevmatikakis/anaconda3/envs/caiman-gui/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/epnevmatikakis/anaconda3/envs/caiman-gui/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/epnevmatikakis/anaconda3/envs/caiman-gui/lib/python3.6/site-packages/spyder/app/start.py", line 189, in main
    from spyder.app import mainwindow
  File "/Users/epnevmatikakis/anaconda3/envs/caiman-gui/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/epnevmatikakis/anaconda3/envs/caiman-gui/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```

**Comment by pgunn** [comment]
I've reproduced the issue on my mac laptop and think I know what's going on - the issue is that the versions of pyqt (5.6.0) and qt (5.6.2) are not compatible. If you do `conda install qt=5.6.0` (assuming you have conda-forge enabled for your environment, if not you may need to tweak the above slightly), it will install a version of qt compatible with pyqt 5.6.0 and everything will be fine.

**Comment by epnev** [comment]
@pgunn That didn't work for me. I get the following error when trying to install `qt`:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - ffmpeg
  - fontconfig
  - qt 5.6.0*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by bingcao2** [comment]
Hi,
I have used `conda install qt=5.6.0` to reinstall qt, and the spyder could be opened now.
However, when I tried to import caiman I encountered the error as follows. Would you do me a favor to help me fix this error. Many thanks!
Bing

```
import caiman
Traceback (most recent call last):

  File "<ipython-input-1-5074b0ea2ec9>", line 1, in <module>
    import caiman

  File "/Users/Bing/CaImAn/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain

  File "/Users/Bing/CaImAn/caiman/base/movies.py", line 25, in <module>
    import cv2

ModuleNotFoundError: No module named 'cv2'
```

**Comment by pgunn** [comment]
Hi, are you sure you are in the conda environment when you're doing this? If so, can you do this and send me the output?

`conda list | grep opencv`

**Comment by bingcao2** [comment]
Hi, 
The default version of opencv is 3.1. Is it ok to install this version? Because the opencv=3.2 will update qt to 5.6.2. Please find the information as follows. Thank you very much!
Bing

```
(caiman) bash-3.2$ conda install opencv
Solving environment: done

## Package Plan ##

  environment location: /anaconda3/envs/caiman

  added / updated specs: 
    - opencv


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    opencv-3.1.0               |      np112py36_1        36.4 MB  conda-forge

The following NEW packages will be INSTALLED:

    opencv:       3.1.0-np112py36_1  conda-forge

The following packages will be UPDATED:

    matplotlib:   2.0.2-np113py36_0              --> 2.0.2-np112py36_0             
    scikit-learn: 0.19.0-np113py36_0             --> 0.19.0-np112py36_0            
    scipy:        0.19.1-np113py36_0             --> 0.19.1-np112py36_0            

The following packages will be DOWNGRADED:

    h5py:         2.7.1-py36_1       conda-forge --> 2.7.0-np112py36_0  conda-forge
    hdf5:         1.8.18-3           conda-forge --> 1.8.17-11          conda-forge
    numpy:        1.13.1-py36_0                  --> 1.12.1-py36_0   
```              

```
(caiman) bash-3.2$ conda install opencv=3.2
Solving environment: done

## Package Plan ##

  environment location: /anaconda3/envs/caiman

  added / updated specs: 
    - opencv=3.2


The following NEW packages will be INSTALLED:

    opencv:       3.2.0-np112py36_0  conda-forge

The following packages will be UPDATED:

    fontconfig:   2.12.1-3                       --> 2.12.1-4           conda-forge
    freetype:     2.5.5-2                        --> 2.7-1              conda-forge
    harfbuzz:     0.9.39-2                       --> 1.3.4-2            conda-forge
    icu:          54.1-0                         --> 58.2-hfc679d8_0    conda-forge
    matplotlib:   2.0.2-np113py36_0              --> 2.0.2-py36_2       conda-forge
    pillow:       4.2.1-py36_0                   --> 4.3.0-py36_1       conda-forge
    qt:           5.6.0-0                        --> 5.6.2-h4e759b2_10  conda-forge
    scikit-learn: 0.19.0-np113py36_0             --> 0.19.0-np112py36_0            
    scipy:        0.19.1-np113py36_0             --> 0.19.1-np112py36_0            

The following packages will be DOWNGRADED:

    cairo:        1.14.8-0                       --> 1.14.6-4           conda-forge
    h5py:         2.7.1-py36_1       conda-forge --> 2.7.0-np112py36_0  conda-forge
    hdf5:         1.8.18-3           conda-forge --> 1.8.17-11          conda-forge
    numpy:        1.13.1-py36_0                  --> 1.12.1-py36_0 
```

**Comment by pgunn** [comment]
Ah. That's really unfortunate. What happens if you try this?
`conda install opencv=3.2 qt=5.6.0`

**Comment by bingcao2** [comment]
Hi,
Please find the error information as follows. Thanks.

```
(caiman) bash-3.2$ conda install opencv=3.2 qt=5.6.0
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - opencv=3.2 -> harfbuzz=1.3 -> icu=58
  - qt=5.6.0
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by pgunn** [comment]
This worked locally; we're looking at other ways to solve this and will have an answer soon. Apologies.

**Comment by agiovann** [comment]
still working on it

**Comment by bingcao2** [comment]
Hi,
 Since I could only use jupyter to run the code in notebook without spyder, could you tell me how to get  ∆F/F in jupyter? Here is some hints previously, but I still don't know how to write the code. I do appreciate if you could write the code to extract all the ∆F/F and could paste it into excel for further plotting. Many thanks!

Quoted from epnev
> The DF/F traces are included in cnm.estimates.F_dff. If you want to store them separately you can use some numpy command, e.g., np.savez
>

**Comment by omidm7** [comment]
> Hi,
> Since I could only use jupyter to run the code in notebook without spyder, could you tell me how to get ∆F/F in jupyter? Here is some hints previously, but I still don't know how to write the code. I do appreciate if you could write the code to extract all the ∆F/F and could paste it into excel for further plotting. Many thanks!
> 
> Quoted from epnev
> 
> > The DF/F traces are included in cnm.estimates.F_dff. If you want to store them separately you can use some numpy command, e.g., np.savez

Yes I would also love to be able to extract delta F/F in Jupyter. Is there a quick line for this?

**Comment by pgunn** [comment]
@bingcao2 @omidm7 Is there any way one of you could open a different issue for that question? Would be helpful in dependency tracking and assignment.

**Comment by pgunn** [comment]
FYI, this is the Github issue we're waiting on for the Spyder issue.

https://github.com/conda-forge/qt-feedstock/pull/82

**Comment by pgunn** [comment]
Some of the upstream issues have been fixed; I think right now the only blocker is that pyqt needs a rebuild. I'm trying to poke the maintainers to do that.

**Comment by pgunn** [comment]
This has been fixed upstream with a rebuild of the qt and pyqt packages. I have just successfully made a new environment and it has a working spyder. Thanks to @ccordoba12
