### ISSUE TITLE
initialize_components, doc string and methods 

### ISSUE THREAD

**Issue by MaximilianHoffmann** [flatironinstitute/CaImAn#414]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

https://github.com/flatironinstitute/CaImAn/blob/f894473f123f4dd2d7a2952e599f6432aa98847e/caiman/source_extraction/cnmf/initialization.py#L135

The doc string specifies an argument named method, but there is only method_init , it is later copied, but would be better to have the right name

And a question: 
https://github.com/flatironinstitute/CaImAn/blob/f894473f123f4dd2d7a2952e599f6432aa98847e/caiman/source_extraction/cnmf/initialization.py#L282

As an if statement for `method == 'corr_pnr'` (it says it is for 1p data, which is relevant for me), but the doc string only lists the possible method_init values  `Initialization method 'greedy_roi' or 'sparse_nmf'`

Other values that are in the function include `'local_nmf':` and ` 'pca_ica'`, is this unsupported and from the publication for method comparison? Or can it be used.

Thank you.

**Comment by MaximilianHoffmann** [comment]
I just saw, that the only difference is the opencv flag
https://github.com/flatironinstitute/CaImAn/blob/f894473f123f4dd2d7a2952e599f6432aa98847e/caiman/source_extraction/cnmf/initialization.py#L282

**Comment by agiovann** [comment]
Dear @MaximilianHoffmann, no the difference is not only the opencv flag but the way the whole initialization process is carried out. I corrected the docstring and commented when to use each of them. I will push soon to master.

**Comment by agiovann** [comment]
@MaximilianHoffmann at the moment local_nmf is unsupported and pca_ica  experimental

**Comment by MaximilianHoffmann** [comment]
Thanks for addressing this!

Cheers
Max
