### ISSUE TITLE
What is implemented for 3D, and what only for 2D data

### ISSUE THREAD

**Issue by MaximilianHoffmann** [flatironinstitute/CaImAn#415]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

I would be very interested to know, what method are implemented for 3d and which only for 2d data,
e.g.  `init_neurons_corr_pnr` , only works for 2d data.  

Is there a reason, if so, maybe this could be handled by a dedicated exception?

Thank You

**Comment by agiovann** [comment]
@MaximilianHoffmann thank you for the heads up. The reason is that init_neurons_corr_pnr is mostly used for 1-photon data, for 3D we use greedy_roi. At the moment that we did not process any 1photon 3D data, but of course his could be extended to the 3D case. What is your use case? I marked this is as an enhacement and  as a bug. Cheers.

**Comment by agiovann** [comment]
@marianotepper I am modifying  the documentation to alert the user about the possible conflict

**Comment by MaximilianHoffmann** [comment]
Hi, 
thanks for addressing my issues. My data is from a yet unpublished microscope, which delivers 3d data. It makes some compromises in z-sectioning to image larger volumes though, so there is partially some bleed through from layers below, similar to what you would expect from the endoscope data. Of course it has a well defined PSF, so in principle something like 3D greedy roi should probably work. But I thought I could benefit from a initialization similar to the 1p endoscope data in cases where there is correlated activity from many neurons in one plane, which will be out of focus diffuse BG in upper/lower planes. I still have to fully read the code though, and then I might try to adapt it for 3D.

**Comment by agiovann** [comment]
@MaximilianHoffmann Thank you, that sounds interesting! If you want to work with us on that we would be happy to collaborate.

**Comment by MaximilianHoffmann** [comment]
Is segmentation in patches fully implemented for 3d data?

**Comment by epnev** [comment]
@MaximilianHoffmann Processing in patches is implemented in 3d. For component evaluation the CNN classifier has been trained only on 2d data and will not work on 3d data (you could try a max projection along z of each 3d spatial component and then feed that into your classifier but no guarantees that will be useful). The other two tests will run with 3d data but adjustment of the thresholds might be necessary.

**Comment by epnev** [comment]
3D motion correction is now part of CaImAn.
