### ISSUE TITLE
Value error: dimension mismatch with sparse_nmf initialization

### ISSUE THREAD

**Issue by hluetck** [flatironinstitute/CaImAn#416]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
macOS, Python 3.6.6, Jupyter

- **Describe the issue that you are experiencing**
I am experiencing an unexpected error when running CNMF with the `sparse_nmf` initialisation method. The error occurs when calling `cnm = cnm.fit(images)` during / after the removing Baseline step. Everything runs fine when the `greedy_roi` initialisation method is used (other parameters unchanged). I attach a file with my parameters from `opts.to_dict()`.

- **Copy error log below**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-1afb06bafa6b> in <module>
      3 opts.set('temporal', {'p': 0})
      4 cnm = cnmf.CNMF(n_processes, params=opts, dview=dview)
----> 5 cnm = cnm.fit(images)

~/miniconda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indeces)
    542                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    543                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 544                     indeces=indeces)
    545 
    546             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~/miniconda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indeces)
    252 
    253     else:
--> 254         file_res = list(map(cnmf_patches, args_in))
    255 
    256     print((time.time() - st))

~/miniconda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py in cnmf_patches(args_in)
    131         cnm = cnmf.CNMF(n_processes=1, params=opts)
    132 
--> 133         cnm = cnm.fit(images)
    134         return [idx_, shapes, scipy.sparse.coo_matrix(cnm.estimates.A),
    135                 cnm.estimates.b, cnm.estimates.C, cnm.estimates.f, cnm.estimates.S, cnm.estimates.bl, cnm.estimates.c1,

~/miniconda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indeces)
    470                     self.estimates.YrA = self.estimates.YrA[idx_components]
    471 
--> 472                 self.estimates.normalize_components()
    473 
    474                 return self

~/miniconda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/estimates.py in normalize_components(self)
    594             nB_inv_mat = scipy.sparse.spdiags(1. / nB, 0, nB.shape[0], nB.shape[0])
    595             self.b = self.b * nB_inv_mat
--> 596             self.f = nB_mat * self.f
    597         return self
    598 

~/miniconda/envs/caiman/lib/python3.6/site-packages/scipy/sparse/base.py in __mul__(self, other)
    385             # dense row or column vector
    386             if other.shape != (N,) and other.shape != (N, 1):
--> 387                 raise ValueError('dimension mismatch')
    388 
    389             result = self._mul_vector(np.ravel(other))

ValueError: dimension mismatch

-----------------------------------------
Thanks for the help!

[opts.txt](https://github.com/flatironinstitute/CaImAn/files/2614690/opts.txt)

**Comment by agiovann** [comment]
Thank you for the feedback,

I suspect it has to do with the fact that you find less than expected
components. Could you please add a breakpoint  at

594 nB_inv_mat = scipy.sparse.spdiags(1. / nB, 0, nB.shape[0], nB.shape[0])
595 self.b = self.b * nB_inv_mat
--> 596 self.f = nB_mat * self.f

And let me know which dimensions are mismatched?

Thank you!

**Comment by hluetck** [comment]
Hello,

thanks for your reply.

the variables are:

nB_mat:
  (0, 0)	9643.70735351
(1, 1)
<class 'scipy.sparse.dia.dia_matrix'>

self.f:
(732,)
<class 'numpy.ndarray'>

**Comment by j-friedrich** [comment]
Hi Henry, i managed to reproduce the error using your opts.
Can you please remove the `.squeeze()` from `f_in = model.components_.squeeze()` in line 541 of `initialization.py` and confirm that this resolves the issue?

**Comment by hluetck** [comment]
Hi Johannes, I can confirm that this change resolves the issue. Thanks a lot!

**Comment by j-friedrich** [comment]
Thanks. I just updated master and dev accordingly.
