### ISSUE TITLE
Problems with demo_motion_correction

### ISSUE THREAD

**Issue by tbenst** [flatironinstitute/CaImAn#421]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
Ubuntu 18.04, anaconda w/ python 3.6, installed via environment.yml file. Working in jupyter.

- **Describe the issue that you are experiencing**
1. 'download_demo' fails with `HTML 400 - bad request`.
2. If I try to run with my own tiff files, the `play` method crashes the kernel with `qt.qpa.screen: QXcbConnection: Could not connect to display`. This is a server so there is no display. 

Does another backend support headless?

**Comment by pgunn** [comment]
Hi,
1) It looks like the storage for this file on Dropbox is no longer working; I'm going to need to correct the sources to address this issue. I'll try to get this addressed on Friday.
2) Right now while you can run the main body of the code without graphical support (we in fact do this in CI), you're going to be missing out on some visualisation; there's not a good way around that. If you can start a Xvnc session on your server, that's probably a good way of letting you do graphics there (VNC clients are readily available on all platforms).

Happy to chat on the second point further.

**Comment by agiovann** [comment]
@tbenst we apologize for problem 1. One of our Dropbox account was closed. For problem 2, just comment the lines that play the movies and inactivate the show_movie or save_movie parameters. 

Let us know

PS: teamviewer is another valid alternative!

**Comment by pgunn** [comment]
@tbenst I have adjusted the hosting of those files to a more stable placement; the first problem is solved if you do a fresh pull/install of the sources.

**Comment by pgunn** [comment]
@tbenst Hi, I hope this has answered your question/resolved the issues; if you'd like advice on things like VNC, please hop onto our gitter channel:

https://gitter.im/agiovann/Constrained_NMF
