### ISSUE TITLE
CaImAn roadmap?

### ISSUE THREAD

**Issue by HagaiHargil** [flatironinstitute/CaImAn#423]
Hi,

As you might remember me and my lab have been following, using, publishing with, and (just a tiny bit) contributing to CaImAn for quite a while now, and we're very happy to be a part of the vibrant community around this package.

Many popular open source projects also advertise a roadmap that deals with future plans for the package. The roadmap is sometimes limited to the next stable release, but sometimes might include some long-term plans as well.

For example, I recently learned "by accident" that @agiovann is developing a GUI for component evaluation. This news is very important for labs like us, which might be wanting to contribute to this effort, or simply be aware that it exists. I'm sure you have many other plans in the pipes that could be advertised as such (new features, docs upgrade, etc.).

Anyways, please take this as an honest recommendation. If you don't have the bandwidth currently to write and maintain such a roadmap it's completely understandable. Keep up the good work!

**Comment by HagaiHargil** [comment]
@epnev Thanks for your thoughtful response. I agree that the model you described is a good alternative. 

As for specific requests, our main interests are as follows:

- We've  been using a couple of post-processing scripts for quite some time now to serialize CaImAn's output, since in most notebooks\scripts I believe that CaImAn doesn't save anything to disk, but merely displays the results and keeps it in memory. A more standardized serialization format could perhaps benefit the great ecosystem around this framework, and allow others to write "extensions" that are guaranteed to process the same standardized format.
- A result-inspection GUI is always a high priority. It is indeed a large endeavor, one which we also do not have the bandwidth to undertake.
- 3D segmentation: We've used CaImAn on our 3D data with mixed results. When we kept the parameters close to the values set in the 3D notebook it completed its run but wasn't able to detect too many cells since the parameters were kinda off. Once we tried modifying them to better fit our data the pipeline would crash every time. We consider this a high priority as well, which means that if you (or some other maintainer) could devote some time to it, we'll be happy to provide the data, error logs and generally work hand-in-hand in an iterative manner until the problem is solved.

Thanks again!

**Comment by epnev** [comment]
A couple of updates before closing this issue:
- We have added a `cnmf.save` and a `cnmf.load` method for saving/loading analysis results in the form of hdf5 files.
- There is now a small GUI that can load a results file (saved with the method explained above) and can be used for inspecting the results and modifying them (e.g. by removing some component). 
- A very notable effort for interactive analysis comes with [mesmerize](http://www.mesmerizelab.org/#) that  provides an interface to CaImAn and also several methods for downstream analysis.
- We have not done any further work for 3D segmentation but we now also have methods for 3D motion correction.
