### ISSUE TITLE
Latest update, crash on activating caiman env

### ISSUE THREAD

**Issue by PhilippBartel** [flatironinstitute/CaImAn#433]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
Windows10, Python 3.6, Anaconda, Jupyter Notebook / Lab

- **Describe the issue that you are experiencing**
Updated to the latest caiman following the instructions; since then any attempt to activate the caiman environment results in a crash from the anaconda prompt on trying to import keras.
Haven't had this problem before.

I'm sure the problem is somewhere on my end; what would you recommend to resolve this issue?

**Comment by pgunn** [comment]
Hi,
Could you cut'n'paste the precise crash text?

**Comment by PhilippBartel** [comment]
Hi, thank you for your quick response.
Trying to reinstall again, will let you know.

**Comment by PhilippBartel** [comment]
I am not logging the anaconda prompt; don't know of a good way to do that. On crash I cannot copy the text since it closes the prompt.
I know Im not making it easier, what do you suggest?

**Comment by pgunn** [comment]
One thing you might try: In the conda install dir, look for and delete this file:

vs2015_compiler_vars.bat

If it is what I think it is (admittedly just a guess based on past experience), that will solve the issue.

**Comment by PhilippBartel** [comment]
I traced the problem back to messed up Microsoft Visual Studio. Everything worked after VS was modified.
Thank you for your help!

**Comment by peltonen** [comment]
On a new installation, I am also finding that the shell crashes when attempting to activate the caiman environment. Here's the piped output:


C:\Users\Ginty>python C:\Users\Ginty\.conda\envs\caiman\etc\keras\load_config.py  1>temp.txt 

C:\Users\Ginty>set /p KERAS_BACKEND= 0<temp.txt 

C:\Users\Ginty>del temp.txt 

C:\Users\Ginty>python -c "import keras"  1>nul 2>&1 

C:\Users\Ginty>if errorlevel 1 (
ver  1>nul  
 set "KERAS_BACKEND=theano"  
 python -c "import keras"  1>nul 2>&1 
) 

C:\Users\Ginty>SET DISTUTILS_USE_SDK=1 

C:\Users\Ginty>SET MSSdk=1 

C:\Users\Ginty>SET platform= 

C:\Users\Ginty>IF /I [AMD64] == [amd64] set "platform=true" 

C:\Users\Ginty>IF /I [] == [amd64] set "platform=true" 

C:\Users\Ginty>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" ) 

C:\Users\Ginty>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B" 

C:\Users\Ginty>if "" == "" (set "VSINSTALLDIR=" ) 

C:\Users\Ginty>if "" == "" (
ECHO "Did not find VS in registry or in VS140COMNTOOLS env var - exiting"  
 exit 1 
) 
"Did not find VS in registry or in VS140COMNTOOLS env var - exiting"


Am I right to suspect an imperfect VS install, and any tips for troublshooting?

**Comment by pgunn** [comment]
Hi,
This is an issue with the glue between Conda and Visual Studio not functioning correctly. Do a search under your conda dir for a file named vs2015_compiler_vars.bat
if you find it, try deleting it (or move it elsewhere).

**Comment by pgunn** [comment]
@peltonen Actually given the messages I see there, you might have a slightly differently named file specific to VisualStudio 14 that still follows the same pattern; maybe it'd be vs2014_compiler_vars.bat ? It might be safer to just search for _compiler_vars.bat and see what turns up.

**Comment by peltonen** [comment]
Deleting the .vars file mentioned above solved the issue, thanks for the fix.
