### ISSUE TITLE
Cannot import name 'oasis'

### ISSUE THREAD

**Issue by omidm7** [flatironinstitute/CaImAn#435]
Operating system: macOS, 
Python version (3.6),
 and working environment (Spyder)

Hello, after upgrading Caiman and running caimanmanager.py install in the terminal, I see a file directory 'Caiman' with the file caimanmanager.py in it and another directory called "Caiman data" as described in the installation instructions. However, I get the following error upon trying to import caiman:

- **Copy error log below**
Traceback (most recent call last):

  File "<ipython-input-1-fdf105e43b1e>", line 30, in <module>
    import caiman as cm

  File "/Users/Bing/CaImAn/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain

  File "/Users/Bing/CaImAn/caiman/base/movies.py", line 67, in <module>
    from ..utils import visualization

  File "/Users/Bing/CaImAn/caiman/utils/visualization.py", line 34, in <module>
    from ..summary_images import local_correlations

  File "/Users/Bing/CaImAn/caiman/summary_images.py", line 31, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft

  File "/Users/Bing/CaImAn/caiman/source_extraction/cnmf/__init__.py", line 12, in <module>
    from . import oasis

ImportError: cannot import name 'oasis'

___
In a previous topic I saw the suggestion to remove caimanmanager.py from the Caiman folder and try running it  there. I tried this and still receive the error. 

Thanks for your help!

**Comment by epnev** [comment]
@omidm7  Did you run the pip install command during the installation?

**Comment by omidm7** [comment]
@epnev Yes!

**Comment by omidm7** [comment]
Hey. I'm running demo_pipeline_cnmfE.py on Spyder (Python 3.6).

**Comment by pgunn** [comment]
Sounds good; what's the path to that script when you're running it, and from what directory are you launching Spyder?

**Comment by omidm7** [comment]
The script is in the path: /Users/omid/CaImAn/demos/general.
And I am launching Spyder from the anaconda caiman environment I created.
I got the whole thing to work on my laptop, but can't get it to run on the desktop. Both are iOS, python 3.6.

**Comment by j-friedrich** [comment]
Maybe oasis didn't properly compile. Can you check whether there is a file oasis.cpython-36m-darwin.so (or a similarly named *.so file) in directory caiman/source_extraction/cnmf/?

**Comment by omidm7** [comment]
Hi, I don't see any .so files in that directory. 
![image](https://user-images.githubusercontent.com/44180252/51636085-36723100-1f0d-11e9-8c90-57ab954694ab.png)

**Comment by pgunn** [comment]
Hi,
So after you install caiman with pip, you will want to use the caimanmanager.py script to make a working directory, and then use that working directory rather than working in the sources.

**Comment by j-friedrich** [comment]
You can create the oasis.so file by running `python setup.py build_ext -i` within the CaImAn directory.

**Comment by omidm7** [comment]
@pgunn , even when I run the caimanmanager.py script by itself, I get the oasis error.
![image](https://user-images.githubusercontent.com/44180252/51637826-9ec31180-1f11-11e9-968e-3ea5f607786d.png)

**Comment by omidm7** [comment]
@j-friedrich , that line gives me the following error:
![image](https://user-images.githubusercontent.com/44180252/51637943-ed70ab80-1f11-11e9-8c44-09d376c7cf9c.png)

**Comment by omidm7** [comment]
@pgunn , No matter where I copy and paste that caimanmanager.py file, and whichever directory I use to open it, I still get the oasis error.

**Comment by omidm7** [comment]
@j-friedrich , That seems to have fixed it.

Thank you both very much for your time, it is much appreciated! 
Omid

**Comment by SensibleLife333** [comment]
Hi everyone,
I'm getting the same cannot import oasis error. Even though I have imported it. 
from . import oasis
ImportError: cannot import name 'oasis' from partially initialized module 'caiman.source_extraction.cnmf' (most likely due to a circular import) (C:\Users\Shreyasta\PycharmProjects\CaImAn\caiman\source_extraction\cnmf\__init__.py)

What should I do?

**Comment by pgunn** [comment]
@SensibleLife333
Hello, how did you install caiman?

(note that we can have this conversation much faster if you can pop on Gitter:
https://gitter.im/agiovann/Constrained_NMF )

**Comment by SensibleLife333** [comment]
Hi Pat,

I installed CaImAn from https://linuxtut.com/en/be62cbf84161279e33af/

Regards,
Shreyasta Samal

**Comment by raymondwjang** [comment]
Hi, I'm having the same issue as @SensibleLife333 , but cannot find the relevant thread on the [gitter link](https://gitter.im/agiovann/Constrained_NMF). Could somebody help me out?

**System:**
Apple M1, OS X Sequoia

**Error Reproduction:**
```sh
git clone https://github.com/flatironinstitute/CaImAn.git
conda install -n base -c conda-forge mamba -y  # install mamba in base environment
mamba create -n caiman -c conda-forge caiman -y # install caiman
conda activate caiman  # activate virtual environment
caimanmanager install
```
Run the first cell in `demo_online_cnmfE.ipynb`

**Error Trace:**
```sh
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 9
      6 import numpy as np
      7 from time import time
----> 9 import caiman as cm
     10 from caiman.source_extraction import cnmf as cnmf
     11 from caiman.motion_correction import MotionCorrect

File ~/CaImAn/caiman/__init__.py:4
      1 #!/usr/bin/env python
      3 import pkg_resources
----> 4 from caiman.base.movies import movie, load, load_movie_chain, _load_behavior, play_movie
      5 from caiman.base.timeseries import concatenate
      6 from caiman.cluster import start_server, stop_server

File ~/CaImAn/caiman/base/movies.py:36
     34 import caiman.base.traces
     35 import caiman.mmapping
---> 36 import caiman.summary_images
     37 import caiman.utils.sbx_utils
     38 import caiman.utils.visualization

File ~/CaImAn/caiman/summary_images.py:18
     16 import caiman
     17 import caiman.base.movies
---> 18 from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
     20 def max_correlation_image(Y, bin_size: int = 1000, eight_neighbours: bool = True, swap_dim: bool = True) -> np.ndarray:
     21     """Computes the max-correlation image for the input dataset Y with bin_size
     22 
     23     Args:
   (...)
     40             max correlation image
     41     """

File ~/CaImAn/caiman/source_extraction/cnmf/__init__.py:12
     10 from . import spatial
     11 from . import temporal
---> 12 from . import oasis
     13 from . import params
     14 from . import online_cnmf

ImportError: cannot import name 'oasis' from partially initialized module 'caiman.source_extraction.cnmf' (most likely due to a circular import) (~/CaImAn/caiman/source_extraction/cnmf/__init__.py)
```

**Comment by pgunn** [comment]
Hello,
The instructions you're following mix two different install methods; it's important you just pick one and stick with it.

I suggest removing your checkout of caiman (do not check it out) and just use the rest of the instructions you have.
See if it changes the results. If you still encounter issues, please open a new issue so we don't notify everyone else on this issue.

Cheers,
Pat
