### ISSUE TITLE
macOS Mojave 10.14.2 installation issue

### ISSUE THREAD

**Issue by rem7101** [flatironinstitute/CaImAn#439]
- **Describe the issue that you are experiencing**
Hello, I am new to Python and am trying to install CaImAn on a MacOS Mojave 10.14.2 system. I received an error similar to issue #412, but trying the fix suggested in that string did not fix my problem. Please find the error string below and thank you for the help.

- **Copy error log below**
macbook-pro:CaImAn ninja7101$ source activate caiman
(caiman) macbook-pro:CaImAn ninja7101$ pip install .
Processing /Users/ninja7101/CaImAn
Building wheels for collected packages: caiman
  Building wheel for caiman (setup.py) ... error
  Complete output from command /Users/ninja7101/anaconda3/envs/caiman/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wh/r3d_f4zj6gl3p_9qbq43s21m0000gn/T/pip-req-build-a20da9z7/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/wh/r3d_f4zj6gl3p_9qbq43s21m0000gn/T/pip-wheel-msnd9316 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/paths.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/components_evaluation.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/summary_images.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/motion_correction.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/mmapping.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/cluster.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
  copying caiman/behavior/behavior.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
  copying caiman/behavior/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_pre_processing.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_temporal.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_spatial.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_deconvolution.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_import.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/comparison_humans.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_general.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_toydata.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_demo.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/comparison_humans_online.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/labelling.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/visualization.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/utils.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/stats.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/image_preprocessing_keras.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/gui
  copying caiman/gui/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
  copying caiman/gui/caiman_gui.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
  copying caiman/gui/gui.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
  copying caiman/gui/gui_pyqtgraph.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/external
  copying caiman/external/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external
  copying caiman/external/cell_magic_wand.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction
  copying caiman/source_extraction/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/rois.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/movies.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/traces.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/timeseries.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/regen_main_gt.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/comparison.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/create_gt.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/demo_VST.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/regions.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/plotting.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/estimation.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/measures.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/stats.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/gat.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/params.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/temporal.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/estimates.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/deconvolution.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/spatial.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/cnmf.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/initialization.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/cnmf_optional_outputs.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/map_reduce.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/utilities.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/pre_processing.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/merging.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/online_cnmf.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  running build_ext
  building 'caiman.source_extraction.cnmf.oasis' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/caiman
  creating build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction
  creating build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ninja7101/anaconda3/envs/caiman/include -arch x86_64 -I/Users/ninja7101/anaconda3/envs/caiman/include -arch x86_64 -I/Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include -I/Users/ninja7101/anaconda3/envs/caiman/include/python3.6m -c caiman/source_extraction/cnmf/oasis.cpp -o build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf/oasis.o
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from caiman/source_extraction/cnmf/oasis.cpp:647:
  In file included from /Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
  In file included from /Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
  /Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it with " \
   ^
  caiman/source_extraction/cnmf/oasis.cpp:651:10: fatal error: 'ios' file not found
  #include "ios"
           ^~~~~
  2 warnings and 1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for caiman
  Running setup.py clean for caiman
Failed to build caiman
Installing collected packages: caiman
  Running setup.py install for caiman ... error
    Complete output from command /Users/ninja7101/anaconda3/envs/caiman/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wh/r3d_f4zj6gl3p_9qbq43s21m0000gn/T/pip-req-build-a20da9z7/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wh/r3d_f4zj6gl3p_9qbq43s21m0000gn/T/pip-record-yv0w5o_m/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/paths.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/components_evaluation.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/summary_images.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/motion_correction.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/mmapping.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/cluster.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
    copying caiman/behavior/behavior.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
    copying caiman/behavior/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_pre_processing.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_temporal.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_spatial.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_deconvolution.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_import.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/comparison_humans.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_general.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_toydata.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_demo.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/comparison_humans_online.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/labelling.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/visualization.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/utils.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/stats.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/image_preprocessing_keras.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/gui
    copying caiman/gui/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
    copying caiman/gui/caiman_gui.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
    copying caiman/gui/gui.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
    copying caiman/gui/gui_pyqtgraph.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/external
    copying caiman/external/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external
    copying caiman/external/cell_magic_wand.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction
    copying caiman/source_extraction/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/rois.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/movies.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/traces.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/timeseries.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/regen_main_gt.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/comparison.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/create_gt.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/demo_VST.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/regions.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/plotting.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/estimation.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/measures.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/stats.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/gat.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/params.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/temporal.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/estimates.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/deconvolution.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/spatial.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/cnmf.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/initialization.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/cnmf_optional_outputs.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/map_reduce.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/utilities.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/pre_processing.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/merging.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/online_cnmf.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    running build_ext
    building 'caiman.source_extraction.cnmf.oasis' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/caiman
    creating build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction
    creating build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ninja7101/anaconda3/envs/caiman/include -arch x86_64 -I/Users/ninja7101/anaconda3/envs/caiman/include -arch x86_64 -I/Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include -I/Users/ninja7101/anaconda3/envs/caiman/include/python3.6m -c caiman/source_extraction/cnmf/oasis.cpp -o build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf/oasis.o
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from caiman/source_extraction/cnmf/oasis.cpp:647:
    In file included from /Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:
    /Users/ninja7101/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    caiman/source_extraction/cnmf/oasis.cpp:651:10: fatal error: 'ios' file not found
    #include "ios"
             ^~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/ninja7101/anaconda3/envs/caiman/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wh/r3d_f4zj6gl3p_9qbq43s21m0000gn/T/pip-req-build-a20da9z7/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wh/r3d_f4zj6gl3p_9qbq43s21m0000gn/T/pip-record-yv0w5o_m/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/wh/r3d_f4zj6gl3p_9qbq43s21m0000gn/T/pip-req-build-a20da9z7/

**Comment by pgunn** [comment]
Hi,
As far as I can tell this relates to the version of the XCode command line tools you have installed; could you try upgrading that component and giving it another go?

(I think you can do this through the GUI or by issuing the `xcode-select --install` command from the terminal)

**Comment by pgunn** [comment]
I've been reading up on this - apparently Mojave broke compile toolchains for a lot of packages.

This thread:
https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave

goes deep into the issue. It suggests this might be a solution:

```open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg```

Give that a go and let us know the results of a pip install afterwards.

**Comment by rem7101** [comment]
Thanks, 
In case it is helpful, here is the XCode page where it explains the issue:
[https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes]
Here they suggest ' To make sure that you're using the intended version of the command line tools, run xcode-select -s <path to Xcode> or xcode select -s /Library/Developer/CommandLineTools after installing.' after installing the package. I did not do this since I am not sure which option and path to use exactly.

I tried executing 'open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg' while in the caiman environment, but I got the same error as before. I also tried making a new environment called caiman2, then executed the open /.../...macOS_10.14.pkg command again before trying the pip install, but I also got the same error.

Thanks

**Comment by pgunn** [comment]
Hm. Did the open command itself give you an error or did it do nothing?

**Comment by rem7101** [comment]
The open command worked - it brought up a standard gui installer window - all the steps seemed to complete ok.

**Comment by pgunn** [comment]
We're going to locally upgrade one of our systems to the new OS version to figure this out; it may take us a bit. Hopefully it won't be too long before we can get back to you.

**Comment by rem7101** [comment]
Ok - thank you for the help.

**Comment by epnev** [comment]
@rem7101 Running `CFLAGS='-libstd=libc++' pip install .` (or `pip install -e .` depending on your preference) seems to fix the issue. Can you confirm? We're also testing this and will update the installer file accordingly.

**Comment by rem7101** [comment]
Hi - thanks - just to make sure I understand before running in terminal:
Should I run `CFLAGS='-libstd=libc++' pip install .` within my caiman environment on conda?

**Comment by pgunn** [comment]
@rem7101 
Yes. Give that a go.

**Comment by rem7101** [comment]
Ok - it did not seem to work for me:

MacBook-Pro:~ ninja7101$ source activate caiman
(caiman) MacBook-Pro:~ ninja7101$ CFLAGS='-libstd=libc++' pip install .
Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

**Comment by pgunn** [comment]
You're going to want to do this in your caiman source directory (pip looks in the current directory for a setup.py)

**Comment by pgunn** [comment]
Testing #441 to make sure it doesn't break other platforms

**Comment by j-friedrich** [comment]
Can you please try `CFLAGS='-stdlib=libc++' pip install .`
i.e. stdlib instead libstd

**Comment by rem7101** [comment]
I think it worked that time - just as an fyi, this was the same environment where I ran the `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` yesterday. I will try running the demo file later today. Thanks!
Please find the terminal read-out below:

MacBook-Pro:~ ninja7101$ cd CaImAn/
MacBook-Pro:CaImAn ninja7101$ source activate caiman
(caiman) MacBook-Pro:CaImAn ninja7101$ CFLAGS='-stdlib=libc++' pip install .
Processing /Users/ninja7101/CaImAn
Building wheels for collected packages: caiman
  Building wheel for caiman (setup.py) ... done
  Stored in directory: /private/var/folders/wh/r3d_f4zj6gl3p_9qbq43s21m0000gn/T/pip-ephem-wheel-cache-to8p9203/wheels/72/88/92/c81ff69de5f1770bbc4063afbb1f59821ce0e82a05f8b159e6
Successfully built caiman
Installing collected packages: caiman
Successfully installed caiman-1.0

**Comment by pgunn** [comment]
Fixed in dev with 441.

**Comment by epnev** [comment]
@pgunn I'll do some testing and merge with master tomorrow.
