### ISSUE TITLE
issue of motion correction in demo_pipeline

### ISSUE THREAD

**Issue by yuhany1024** [flatironinstitute/CaImAn#440]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
linux(Ubuntu 16), python3.6, jupyter notebook

- **Describe the issue that you are experiencing**
I'm trying to run demo_pipeline.ipynb, and I get an error when running "motion correction" part. It shows:       140174 [motion_correction.py:motion_correction_piecewise():2544] [13287] **** MOVIE NOT SAVED BECAUSE num_splits is not None ***
Is it normal? How can I save the movie?

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@yuhany1024 This is not an error, is just a logging message. The file is actually saved as a memory mapped file in the location specified by `mc.fname_tot_els`. Using the notebook notation you can simply type the following to save your movie in a different format:
```
m_els = cm.load(mc.fname_tot_els)
m_els.save('path_to_file.tif')
```
This will save the movie as a TIFF file with the name you're giving it.
