### ISSUE TITLE
tiling artifacts in cell map

### ISSUE THREAD

**Issue by mschachter** [flatironinstitute/CaImAn#442]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
OS: Linux CENTOS 7
Python Version: 3.6

- **Describe the issue that you are experiencing**
Cell images contain artifacts from patch mode. When the cell images are normalized by their maximum, and a cell map is constructed by adding all of the normalized cell images together, we observe artifacts where the patches overlap:

https://drive.google.com/file/d/1dS42ewCA-M1FgtPordRgARN03XwXHTCb/view?usp=sharing

Is there some way to fix this?

**Comment by epnev** [comment]
@mschachter Does the tiling match the breaking up in patches?

**Comment by mschachter** [comment]
Yes, sorry for not being more specific. The patch size is 50 pixels by 50 pixels, with a stride of 6 pixels.

**Comment by epnev** [comment]
What is the value of `cnm.skip_refinement`? If it's to `True` then this might happen because the algorithm will skip updating the components after the patch processing is done (although I'm not sure this is the issue).

@j-friedrich @agiovann Any ideas?

**Comment by mschachter** [comment]
I'll check it out, thanks! It's probably set to True.

**Comment by epnev** [comment]
@mschachter Did you have a chance to check this?

**Comment by mschachter** [comment]
Sorry @epnev , I got back to checking this out today. So far, with the latest master branch, with default parameters, the artifacts still remain. By default, it appears that ```skip_refinement=False``` in the CNMF constructor. However, I did not see the word "refinement" appear in the output logs, although I would have expected it to appear because of this code in cnmf.py (line 489):

``
            if not self.skip_refinement:
                logging.info('refinement...')
                if self.params.get('merging', 'do_merge'):
                    logging.debug('merging components ...')
                    logging.debug(self.estimates.A.shape)
                    logging.debug(self.estimates.C.shape)
                    self.merge_comps(Yr, mx=50, fast_merge=True)

                logging.debug(self.estimates.A.shape)
                logging.debug(self.estimates.C.shape)
                logging.info('Updating spatial ...')

                self.update_spatial(Yr, use_init=False)
                # set it back to original value to perform full deconvolution
                self.params.set('temporal', {'p': self.params.get('preprocess', 'p')})
                logging.info('update temporal ...')
                self.update_temporal(Yr, use_init=False)
``

I'm now testing by setting ```skip_refinement=False``` explicitly in the CNMF constructor, I'll let you know how it goes.

**Comment by mschachter** [comment]
@epnev I should have paid more attention to the code...

So first of all, we're running in patch mode, so skip_refinement is never used. Instead, presumably, the code from lines 551 on are applied from caiman/source_extraction/cnmf.py. We provide customers with a wrapper that executes CNMFe, which can be found here:

https://github.com/inscopix/isx-cnmfe-wrapper/blob/master/isx_cnmfe_wrapper/runner.py

I still get these artifacts whether skip_refinement is set to False explicitly or not, but after looking back into the code, it makes sense that it wouldn't change anything.
