### ISSUE TITLE
register_ROIs shape broadcasting error

### ISSUE THREAD

**Issue by mowe91** [flatironinstitute/CaImAn#447]
I tried and failed to use the register_ROIs function in base/rois.py. It gave me a shape broadcasting error. I noticed that reversing the dimensions (dims) argument, I could get it to work, but the output registered ROIs looked scrambled/transposed.

Long story short, I could get the function to work by changing:

~~~~
x_grid, y_grid = np.meshgrid(np.arange(0., dims[0]).astype(np.float32),
                                              np.arange(0., dims[1]).astype(np.float32))
~~~~

to

~~~~
x_grid, y_grid = np.meshgrid(np.arange(0., dims[1]).astype(np.float32),
                                              np.arange(0., dims[0]).astype(np.float32))
~~~~

I reasoned the x dimension of the image is axis 1 in the matrix, and conversely, axis 0 is y.

**Comment by epnev** [comment]
@mowe91 I just tried out the `register_ROIs` function on a non-square FOV and it worked without any problems. I'm wondering whether when you call it you pass the matrices of spatial components in a different form. Do these come from `estimates` objects?

**Comment by mowe91** [comment]
@epnev Well... I saved estimates.A to an hdf5 file, also casting it into a dense array, like so:
~~~~
 hdf['A'] = cnm.estimates.A[:, cnm.estimates.idx_components].todense()
~~~~
Since my FOVs were differently cropped, I reshaped, padded, and "re-reshaped" the padded As, and finally ran the registration:
~~~~
A = [csc_matrix(A1/A1.sum(0)) for A1 in A]

dims = [ci.shape for ci in CI]
dims_comb = tuple(np.array(dims).max(axis=0))

masks = [np.reshape(A_.toarray(), dims_ + (-1,), order='F').transpose(2, 0, 1)
             for A_, dims_ in zip(A, dims)]
masks = [np.pad(m, list(zip([0]*3,[0, *(np.array(dims_comb) - m.shape[1:])])),
                'constant', constant_values=0) for m in masks]
CI = [np.pad(ci, list(zip([0]*2, (np.array(dims_comb) - ci.shape))),
             'constant', constant_values=0) for ci in CI]

A = [csc_matrix(m.transpose(1,2,0).reshape((-1, m.shape[0]), order='F')) for m in masks]

max_thr = 0.1
A_reg, assign, match = register_multisession(A, dims_comb, CI, max_thr=max_thr)
~~~~
(Some of this is lifted from one of the eLife Figure scripts in the repository.)

After making the change I described above, this worked (and the results look sensible). I checked that the reshaping doesn't mess with A (skipping the padding, but performing the reshaping and comparing that to the normalized A). I haven't really checked if this could be due to saving A as dense matrix in to a hdf file?

**Comment by epnev** [comment]
@mowe91 Yes, the order with which you save the `A` matrices is important. I'll look into whether saving causes any problems. Thanks!

**Comment by epnev** [comment]
@mowe91 After looking at this a bit more I don't think it's the saving that causes the problem but the cropping/reshaping/padding. You'll need to make sure that this is done in order `F` as also shown in the snippet above. However, the save function works fine with sparse arrays so you don't need to go through this to save space.
