### ISSUE TITLE
Error at save_memmap

### ISSUE THREAD

**Issue by wmau** [flatironinstitute/CaImAn#448]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
Hi, I am using Windows 10, Python 3.6.6 in Spyder. 

- **Describe the issue that you are experiencing**
After running motion correction on a list of tifs, I'm getting an error from save_memmap, which I've copied below. Please let me know how I can fix this issue. Thanks in advance!

- **Copy error log below**
L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py:275: RuntimeWarning: overflow encountered in long_scalars
  if f.tell() != idx_end * Yr_tot.dtype.itemsize * tot_frames:
L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py:277: RuntimeWarning: overflow encountered in long_scalars
  logging.debug(idx_end * Yr_tot.dtype.itemsize * tot_frames)
Traceback (most recent call last):

  File "<ipython-input-5-b344aabfb7e7>", line 26, in <module>
    border_to_0=bord_px)

  File "L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py", line 391, in save_memmap
    fname_new = cm.save_memmap_join(fname_new, base_name=base_name, dview=dview, n_chunks=n_chunks)

  File "L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py", line 201, in save_memmap_join
    list(map(save_portion, pars))

  File "L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py", line 279, in save_portion
    raise Exception('Writing at the wrong location!')

**Comment by epnev** [comment]
@pgunn could this be related to the int32/int64 issues we were saying with memory mapping in windows?

**Comment by pgunn** [comment]
@wmau Can you give us more of the log? There are some things not included in this error log that would help us figure out what's going on.

@epnev Possibly - either way, I'd like to rework some of the logging here to make it more obvious what's failing in that conditional block. The overflow reported when multiplying out

idx_end * Yr_tot.dtype.itemsize * tot_frames

is the problem ; it's possible the write was successful but one of these types is too small to hold the result and python isn't promoting the type during the multiplication.

**Comment by wmau** [comment]
Hi @pgunn, sorry I copied everything I thought was relevant. Here's the complete message that appears when the cell I run fails: 
L:\Python\envs\caiman\lib\site-packages\caiman\base\movies.py:258: UserWarning: ** Pixel averages are too negative. Removing 1 percentile. **
  '** Pixel averages are too negative. Removing 1 percentile. **')
L:\Python\envs\caiman\lib\site-packages\caiman\base\movies.py:277: UserWarning: Pixel averages are too negative for template. Removing 1 percentile.
  'Pixel averages are too negative for template. Removing 1 percentile.')
L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py:275: RuntimeWarning: overflow encountered in long_scalars
  if f.tell() != idx_end * Yr_tot.dtype.itemsize * tot_frames:
L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py:277: RuntimeWarning: overflow encountered in long_scalars
  logging.debug(idx_end * Yr_tot.dtype.itemsize * tot_frames)
Traceback (most recent call last):

  File "<ipython-input-6-b344aabfb7e7>", line 26, in <module>
    border_to_0=bord_px)

  File "L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py", line 391, in save_memmap
    fname_new = cm.save_memmap_join(fname_new, base_name=base_name, dview=dview, n_chunks=n_chunks)

  File "L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py", line 201, in save_memmap_join
    list(map(save_portion, pars))

  File "L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py", line 279, in save_portion
    raise Exception('Writing at the wrong location!')

Exception: Writing at the wrong location!

Here is also the app log if helpful:
[caiman.log](https://github.com/flatironinstitute/CaImAn/files/2852000/caiman.log)

**Comment by pgunn** [comment]
@wmau Hi, If you're up for a bit of adventure, the PR I made above has a revised version of mmapping.py that may solve the issue; you'd download this over your existing mmapping in your source tree and then redo a pip install of caiman.

At very least it'd make the errors you're getting a little more clear.

**Comment by wmau** [comment]
@pgunn Now I am getting a type error. Looks like the seek() method doesn't like uint64s?

L:\Python\envs\caiman\lib\site-packages\caiman\base\movies.py:258: UserWarning: ** Pixel averages are too negative. Removing 1 percentile. **
  '** Pixel averages are too negative. Removing 1 percentile. **')
L:\Python\envs\caiman\lib\site-packages\caiman\base\movies.py:277: UserWarning: Pixel averages are too negative for template. Removing 1 percentile.
  'Pixel averages are too negative for template. Removing 1 percentile.')
Traceback (most recent call last):

  File "<ipython-input-5-b344aabfb7e7>", line 26, in <module>
    border_to_0=bord_px)

  File "L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py", line 353, in save_memmap
    fname_new = cm.save_memmap_join(fname_new, base_name=base_name, dview=dview, n_chunks=n_chunks)

  File "L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py", line 176, in save_memmap_join
    list(map(save_portion, pars))

  File "L:\Python\envs\caiman\lib\site-packages\caiman\mmapping.py", line 248, in save_portion
    f.seek(idx_start * np.uint64(Yr_tot.dtype.itemsize) * tot_frames)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by wmau** [comment]
@pgunn I replaced np.uint64(Yr_tot.dtype.itemsize) with int(Yr_tot.dtype.itemsize) and this appears to have resolved the issue.

**Comment by pgunn** [comment]
That's surprising; I'll adjust my fix, but there's a chance this is a deeper bug in numpy.

**Comment by wmau** [comment]
Thanks for helping me get to the bottom of this! Running CNMF-E now!

**Comment by pgunn** [comment]
Fix is merged into dev (will eventually make its way into master)

**Comment by tvajtay** [comment]
Ubuntu 16.04, Python 3.6, Jupyter notebook
I believe this same issue has cropped up again for me. In `demo_pipeline.ipynb`, when trying to run `cm.save_memmap`. However, I only receive this error when I try to run multiple tiffs, if I only do one movie I don't get the error.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-ca43d3c83b71> in <module>
      2 # memory map the file in order 'C'
      3 fname_new = cm.save_memmap(mc.mmap_file, base_name='memmap_', order='C',
----> 4                            border_to_0=border_to_0) # exclude borders
      5 
      6 # now load the file

~/CaImAn/caiman/mmapping.py in save_memmap(filenames, base_name, resize_fact, remove_init, idx_xy, order, xy_shifts, is_3D, add_to_movie, border_to_0, dview, n_chunks, slices)
    396 
    397 
--> 398         fname_new = cm.save_memmap_join(fname_new, base_name=base_name, dview=dview, n_chunks=n_chunks)
    399 
    400     else:

~/CaImAn/caiman/mmapping.py in save_memmap_join(mmap_fnames, base_name, n_chunks, dview, add_to_mov)
    204 
    205     else:
--> 206         list(map(save_portion, pars))
    207 
    208     np.savez(base_name + '.npz', mmap_fnames=mmap_fnames, fname_tot=fname_tot)

~/CaImAn/caiman/mmapping.py in save_portion(pars)
    276     else:
    277         with open(big_mov, 'r+b') as f:
--> 278             f.seek(idx_start * np.uint64(Yr_tot.dtype.itemsize) * tot_frames)
    279             f.write(Yr_tot)
    280             computed_position = idx_end * np.uint64(Yr_tot.dtype.itemsize) * tot_frames

TypeError: 'numpy.float64' object cannot be interpreted as an integer

```
