### ISSUE TITLE
Feature Request: Unit test for mmapping

### ISSUE THREAD

**Issue by pgunn** [flatironinstitute/CaImAn#452]
This is a low-priority feature request (that I might do myself at some later time):

Write nosetests that exercise the mmapping functionality thoroughly, looking particularly for boundary conditions, overflows, and the like.

**Comment by wmau** [comment]
Windows 10, Python 3.6, Spyder

I think a recent change is introducing an overflow error at this line: https://github.com/flatironinstitute/CaImAn/blob/0c4f1a1ef9f769f54c88745e97f34084b27941ec/caiman/mmapping.py#L280

Here's the full error message: 

> C:\Anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py:275: RuntimeWarning: overflow encountered in long_scalars
>   computed_position = idx_end * int(Yr_tot.dtype.itemsize) * tot_frames
> CRITICAL:root:Error in mmap portion write: at position 6197374800
> CRITICAL:root:But should be at position 72900 * 4 * 21253 = 1902407504
> Traceback (most recent call last):
> 
>   File "<ipython-input-6-4da6b186bd3a>", line 1, in <module>
>     session.run_phase1()
> 
>   File "L:\CaImAn Wrapper\caiman_wrapper.py", line 135, in run_phase1
>     self.motion_correct()
> 
>   File "L:\CaImAn Wrapper\caiman_wrapper.py", line 379, in motion_correct
>     border_to_0=self.bord_px)
> 
>   File "C:\Anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py", line 392, in save_memmap
>     fname_new = cm.save_memmap_join(fname_new, base_name=base_name, dview=dview, n_chunks=n_chunks)
> 
>   File "C:\Anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py", line 201, in save_memmap_join
>     list(map(save_portion, pars))
> 
>   File "C:\Anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py", line 280, in save_portion
>     raise Exception('Internal error in mmapping: Actual position does not match computed position')
> 
> Exception: Internal error in mmapping: Actual position does not match computed position

**Comment by wmau** [comment]
Changing computed_position = idx_end * int(Yr_tot.dtype.itemsize) * tot_frames to idx_end * np.int64(Yr_tot.dtype.itemsize) * tot_frames resolves this issue. 

From what I can tell, the original line gives the wrong multiplication result due to memory overflow.

**Comment by pgunn** [comment]
Ah, fascinating. I assumed that np.int was a 64-bit int on all modern platforms. Will fix.

**Comment by pgunn** [comment]
https://github.com/flatironinstitute/CaImAn/pull/472

**Comment by pgunn** [comment]
@wmau Fix is in dev now, will likely go into master soon. Leaving this FR open as I still haven't written a unit test to catch this yet.
