### ISSUE TITLE
Issue with OpenCV import on OSX (conda-forge)

### ISSUE THREAD

**Issue by pgunn** [flatironinstitute/CaImAn#459]
In CI and also with users, OpenCV broke recently on OSX, failing in import with messages like this:

```
09:41:42 Traceback (most recent call last):
09:41:42   File "/Users/jenkins/workspace/CaImAn_PR-458/test/osx-python3/bin/caimanmanager.py", line 12, in <module>
09:41:42     from caiman.paths import caiman_datadir
09:41:42   File "/Users/jenkins/workspace/CaImAn_PR-458/test/osx-python3/lib/python3.6/site-packages/caiman/__init__.py", line 3, in <module>
09:41:42     from .base.movies import movie, load, load_movie_chain
09:41:42   File "/Users/jenkins/workspace/CaImAn_PR-458/test/osx-python3/lib/python3.6/site-packages/caiman/base/movies.py", line 25, in <module>
09:41:42     import cv2
09:41:42 ImportError: dlopen(/Users/jenkins/workspace/CaImAn_PR-458/test/osx-python3/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libjasper.1.dylib
09:41:42   Referenced from: /Users/jenkins/workspace/CaImAn_PR-458/test/osx-python3/lib/libopencv_imgcodecs.3.4.dylib
09:41:42   Reason: image not found
```

**Comment by pgunn** [comment]
Will confirm that downgrading jasper to 1.900.1 (from 1.900.31, which was uploaded this weekend) fixes the issue, poking conda-forge people on gitter. If/when confirmed, will ask them to mark 1.900.31 as a bad build)

**Comment by pgunn** [comment]
Have confirmed that `conda install jasper=1.900.1` fixes the problem. Hoping I can get them to mark 1.900.31 as a bad build; if that's not done today we can pin it in our environment.yml file until the problem is solved.

**Comment by pgunn** [comment]
We can't pin jasper in a cross-platform way - OpenCV is not built against jasper on Windows

**Comment by pgunn** [comment]
Added note to our install instructions (tried pinning Jasper but that didn't work on Windows).

Reported here:
https://github.com/conda-forge/opencv-feedstock/issues/147

Please do not close this issue until it's fixed upstream and we've taken those install instructions back out.

**Comment by epnev** [comment]
This has been fixed by the conda-forge team.

**Comment by swagner-astro** [comment]
Hi, not sure if this is the right place to put it but I am having the same problems. The installation underneath worked fine but when I try to use it I get the error:
ImportError: dlopen(/Users/Sarah/miniconda3/lib/python3.8/site-packages/cv2.cpython-38-darwin.so, 2): Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: /Users/Sarah/miniconda3/lib/libopencv_imgcodecs.4.4.0.dylib
  Reason: Incompatible library version: libopencv_imgcodecs.4.4.dylib requires version 14.0.0 or later, but libjpeg.9.dylib provides version 12.0.0


INSTALLATION:
The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/osx-64::bzip2-1.0.8-h1de35cc_0
  cairo              pkgs/main/osx-64::cairo-1.16.0-h8023c5d_1
  ffmpeg             conda-forge/osx-64::ffmpeg-4.3-hd0c0d6a_0
  fontconfig         pkgs/main/osx-64::fontconfig-2.13.1-ha9ee91d_0
  gettext            pkgs/main/osx-64::gettext-0.21.0-h7535e17_0
  glib               pkgs/main/osx-64::glib-2.68.2-hdf23fa2_0
  gmp                pkgs/main/osx-64::gmp-6.2.1-h23ab428_2
  gnutls             pkgs/main/osx-64::gnutls-3.6.15-hed9c0bf_0
  graphite2          pkgs/main/osx-64::graphite2-1.3.14-h38d11af_0
  harfbuzz           pkgs/main/osx-64::harfbuzz-2.8.1-ha8c618c_0
  hdf5               pkgs/main/osx-64::hdf5-1.10.6-hdbbcd12_0
  icu                pkgs/main/osx-64::icu-58.2-h0a44026_3
  jasper             pkgs/main/osx-64::jasper-1.900.1-h1f36771_4
  lame               pkgs/main/osx-64::lame-3.100-h1de35cc_0
  libblas            conda-forge/osx-64::libblas-3.8.0-14_mkl
  libcblas           conda-forge/osx-64::libcblas-3.8.0-14_mkl
  libiconv           pkgs/main/osx-64::libiconv-1.16-h1de35cc_0
  libidn2            pkgs/main/osx-64::libidn2-2.3.1-h9ed2024_0
  liblapack          conda-forge/osx-64::liblapack-3.8.0-14_mkl
  liblapacke         conda-forge/osx-64::liblapacke-3.8.0-14_mkl
  libopencv          conda-forge/osx-64::libopencv-4.4.0-py38_2
  libtasn1           pkgs/main/osx-64::libtasn1-4.16.0-h9ed2024_0
  libunistring       pkgs/main/osx-64::libunistring-0.9.10-h9ed2024_0
  libwebp-base       pkgs/main/osx-64::libwebp-base-1.2.0-h9ed2024_0
  libxml2            pkgs/main/osx-64::libxml2-2.9.12-hcdb78fc_0
  llvm-openmp        pkgs/main/osx-64::llvm-openmp-10.0.0-h28b9765_0
  nettle             pkgs/main/osx-64::nettle-3.7.3-h230ac6f_1
  opencv             conda-forge/osx-64::opencv-4.4.0-py38_2
  openh264           conda-forge/osx-64::openh264-2.1.1-hd174df1_0
  pcre               pkgs/main/osx-64::pcre-8.45-h23ab428_0
  pixman             pkgs/main/osx-64::pixman-0.40.0-haf1e3a3_0
  py-opencv          conda-forge/osx-64::py-opencv-4.4.0-py38h23f93f0_2
  x264               pkgs/main/osx-64::x264-1!152.20180806-h1de35cc_0

The following packages will be UPDATED:

  ca-certificates                      2021.1.19-hecd8cb5_1 --> 2021.5.25-hecd8cb5_1
  certifi                          2020.12.5-py38hecd8cb5_0 --> 2021.5.30-py38hecd8cb5_0
  conda                                4.9.2-py38hecd8cb5_0 --> 4.10.3-py38hecd8cb5_0
  jpeg                        pkgs/main::jpeg-9b-he5867d9_2 --> conda-forge::jpeg-9d-hbcb3906_0

**Comment by pgunn** [comment]
I'm going to move this to a new issue and see if I can replicate the issue.
