### ISSUE TITLE
merge_thr not being properly assigned in CNMF-E notebook demo

### ISSUE THREAD

**Issue by wmau** [flatironinstitute/CaImAn#460]
- **If you're not reporting an error, type your message below**
In the change_params method call, 'merge_thresh' should be 'merge_thr'. Consider a small function in set() or change_params() that will flag unconventional dict keys.

**Comment by epnev** [comment]
@wmau Thanks for noticing. This has now been fixed with 9aea1feb2fb25c78e171e2f49c6e97e0ecfe5911 and I also introduced the feature you suggested.
