### ISSUE TITLE
Suggested feature

### ISSUE THREAD

**Issue by 123miles** [flatironinstitute/CaImAn#465]
For making it easier to compare parameters, plots could be automatically given a title "idx_components_bad" and have a legend "min_SNR=2, rval_thr = 0.8"

**Comment by epnev** [comment]
@123miles I added the feature you suggested with 6749faf179896fc5379b1dc8a5f2445c23f01c3f Currently on the dev branch, it should appear on the master branch with our next release. You will need to pass the `params` object when calling the plot contour functions so the threshold parameters can be read from there.

**Comment by 123miles** [comment]
Wow, that was fast. Thank you so much
