### ISSUE TITLE
Better docs on "best practices"

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#467]
Hi all - from lurking a bit in the gitter channel, I've seen time and time again questions about "what should I set this parameter to" or "what does this parameter even do" (which are totally legitimate). I was thinking it would be a good idea to well-document how to ballpark params w.r.t. the type of imaging being done, conditions, whatever, as well as how to sanity check results based on params they've set so that the results generated by the users of the package will robust and well-comparable to other users working in the same biological system. Seems like it would be pretty important for scientific reproducibility. Might be able to help a bit with this.

What do you think?

**Comment by epnev** [comment]
@zbarry I agree with that. Right now we have some tips on the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/CaImAn-Tips) which seems like a reasonable place to add such information but we can/should add more. If you have any ideas I'll be happy to talk more.

**Comment by zbarry** [comment]
Hmm. Since there's already a skeleton Sphinx API documentation framework set up, it could make sense to build that out more so the big picture + the low level functionality are all in one place. Could be formulated like (just as a first pass off the top of my head):

1. What is CaImAn
    - What it is trying to accomplish as a package
    - What were the previous solutions to calcium trace extraction and analysis, and how does CaImAn (CNMF, CNMF-E, motion correction, etc) improve on those solutions (i.e., why should \<user\> bother to move their analysis pipeline over to it and go through that effort)
2. Installation
3. Brief explanation of the steps in the CNMF(-E) pipelines (pointing to the manuscripts) 
    - "See demo notebooks for full implementations of the CaImAn pipeline"
    - Parameters they require with a decent enough explanation of what they mean 
    - How parameter changes can affect the results of the analysis
    - How you would begin to think about picking ballparks for parameter values given your data / setup
    - How you then know that your results are meaningful / reliable, maybe based on the correlation maps, what the traces look like, contours, etc.
4. FAQ / common roadblocks
5. API section

If you put together the readmes + the gitter + wiki + notebooks, most of this is already there (but I think the parameter choices / understanding is probably the least present), though it is currently pretty scattered and therefore hard to take in.

**Comment by zbarry** [comment]
Any thoughts on this / things I missed / better ideas on how to organize / secret helpful docs lying around to scrape content from?

**Comment by epnev** [comment]
@zbarry This is thoughtful and helpful. I'm not very experienced with documentation generation. Do you have any preference e.g. github pages vs readthedocs?

**Comment by zbarry** [comment]
Hmm. One of my colleagues has a whole setup for generating RTDs-style documentation, so I can probably rip off his (and get his help). I'm seeing more and more projects' documentation on readthedocs, so I think that might be the way to go.

**Comment by epnev** [comment]
@zbarry I have started adding some bits and pieces in the documentation (based on gh-pages for now although we can switch to the readthedocs at any time). I used pandoc to convert the MD files into RSTs although the conversion is not always flawless.

If you want to contribute you can submit PRs in the `dev_docs` branch. The source files are inside `docs/source`. The whole instructions for turning these into html files with sphinx and placing them in the gh-pages branch is detailed [here](https://github.com/flatironinstitute/CaImAn/wiki/Updating-Github-pages-docs) but don't worry about that. 

This will be a long process but I'm willing to keep adding stuff every once in a while and learn the whole docs generation better.

**Comment by epnev** [comment]
Tips page is part of the [RTD now](https://caiman.readthedocs.io/en/dev/CaImAn-Tips.html) and hopefully will be filled with all the wisdom. PRs are welcome :)
