### ISSUE TITLE
Walk through on 2p mesoscope data

### ISSUE THREAD

**Issue by windgrazer** [flatironinstitute/CaImAn#474]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

Windows 10, Python 3.6, Spyder

- **Describe the issue that you are experiencing**

Batch processing of mesoscope data does not seem to trace neurons well both spatially and temporally.

- **Copy error log below**

None

- **If you're not reporting an error, type your message below**

I am a pretty new user to Python, the mesoscope, and CaImAn and recently have been trying to analyse some of the tiff files I obtained from the mesoscope for a behaviour task. Having successfully installed CaImAn and ran the demo (demo_pipeline.py), I tried to use the default settings on my tiff file, while only changing the frame rate value. However, the result I obtained does not seem to represent the data well as shown in the screenshots below:

![sample image 1](https://user-images.githubusercontent.com/26172299/53312578-95520e00-38f0-11e9-9487-846f3a2d01df.PNG)
![sample image 2](https://user-images.githubusercontent.com/26172299/53312579-95520e00-38f0-11e9-876d-fb335b860e60.PNG)

I have also tried to play around with the other user-defined variables (dxy, rf, K, gSig) to better fit my data but I would get memory errors and/or similar results. 

Right now, I am only trying this with 1 tiff file but ultimately I would be looking to use the program to look at multiple tiff files in one session, as well as across days to look at neuronal changes over a learning task (which to my knowledge would make use of the demo_pipeline_mulitday.py code, which I have tried and failed to run the demo).

Would appreciate a simple user guide to walk me through this process.

Thank you!

**Comment by epnev** [comment]
@windgrazer It's hard to say what's going wrong since the images have poor resolution. You can try setting `display_numbers=False` when plotting the contours to reduce the clutter. If you feel that the number of components is too high you should try reducing `K` and/or increasing `rf`. The `dxy` parameter refers to the spatial resolution in pixels/um so you should set it to whatever value you get from your experiment.

**Comment by windgrazer** [comment]
@epnev 

I have tried setting display_numbers = False and changing the K and rf values. These seem to help reduce the components picked up to make it look more reasonable. I would like to further check on the **dxy** I should input - currently set to (1., 0.4).
![dxy 1 0 4](https://user-images.githubusercontent.com/26172299/53385046-07d9f100-39b8-11e9-89f4-7d1bb38b18cf.PNG)



Our original tiff file looks something like this:

![5c74af085a599039406814](https://user-images.githubusercontent.com/26172299/53385071-23dd9280-39b8-11e9-8afe-05b6582b468c.gif)
with a 500 x 2500 resolution, imaged at pixel ratio 1, 0.4. 



However, the components picked up still looks very much like noise:
![new screenshot component](https://user-images.githubusercontent.com/26172299/53385142-60a98980-39b8-11e9-939c-b72a1da20fdf.PNG)


Running on Spyder, I am only currently able to see 2 of the components identified with the spatial and temporal information displayed. How should I obtain these information for the other components identified?

**Comment by epnev** [comment]
@windgrazer That figure has a slider you can use to view all the components. Since there is substantial motion you should make sure that the motion correction part corrects for it. You can also try out the online algorithm, check the `demo_OnACID_mesoscope` demo.
