### ISSUE TITLE
Dimension mixup when doing register_multisession with templates

### ISSUE THREAD

**Issue by wmau** [flatironinstitute/CaImAn#475]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

Windows 10, Python 3.6, Spyder/PyCharm

- **Describe the issue that you are experiencing**

Running register_multisession() with a list of templates gives me the error copied below.

(210, 250) is the actual dimension of the templates but it looks like the meshgrid() call in line 391 may be swapping the dimensions. Was there possibly a mix-up between i,j versus x,y indexing here? Changing that line to: 

>     x_grid, y_grid = np.meshgrid(np.arange(0., dims[1]).astype(
>                 np.float32), np.arange(0., dims[0]).astype(np.float32))

eliminates the error and gives me sensible results. 

- **Copy error log below**
> Traceback (most recent call last):
>   File "C:\Anaconda3\envs\caiman\lib\site-packages\IPython\core\interactiveshell.py", line 3291, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-2-851acab5077a>", line 4, in <module>
>     r = Registration([s1,s2])
>   File "L:\CaImAn Wrapper\caiman_wrapper.py", line 546, in __init__
>     self.A_union, self.assignments, self.matchings = self.register_sessions()
>   File "L:\CaImAn Wrapper\caiman_wrapper.py", line 553, in register_sessions
>     A_union, assignments, matchings = register_multisession(self.A, self.dims, templates=self.templates)
>   File "C:\Anaconda3\envs\caiman\lib\site-packages\caiman\base\rois.py", line 599, in register_multisession
>     enclosed_thr = enclosed_thr)
>   File "C:\Anaconda3\envs\caiman\lib\site-packages\caiman\base\rois.py", line 406, in register_ROIs
>     x_remap = (flow[:,:,0] + x_grid).astype(np.float32)
> ValueError: operands could not be broadcast together with shapes (210,250) (250,210)

**Comment by epnev** [comment]
@wmau it could be, although I looked into something similar in the past and there were no errors #447.

Can you try out the following? Use the code without the changes you introduced, but swap `flow[:,;,0]` and `flow[:,:,1]` in [lines 406-407](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/base/rois.py#L406). 
Does this solve the problem? (sorry, can't try this at the moment myself).

**Comment by epnev** [comment]
@wmau Nevermind the above, won't solve the problem. Will take a look

**Comment by epnev** [comment]
@wmau Thanks, you were absolutely right. Fixed on dev with 97d1fee6f2943a460b379e197dada15461841dbc
