### ISSUE TITLE
Affine translations from registration alignments?

### ISSUE THREAD

**Issue by wmau** [flatironinstitute/CaImAn#476]
- **If you're not reporting an error, type your message below**
I am trying to plot cell contours over multiple days, but they are slightly misaligned each day. I assume there is some kind of alignment algorithm happening before cells are matched. Is there any way I can extract the affine translation values so I can align my cell contours post-hoc? Or are aligned cell contours included in the outputs somewhere?

**Comment by epnev** [comment]
@wmau You can do that relatively easily when you align a pair. The alignment happens at this [spot](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/base/rois.py#L403) or at line 410 if the other alignment method is used. While the inferred transformation is not included outputs, the last output, denoted as `A2`, stores the ROIs of session 2 aligned to the template of session 1. For multiday alignment you will need to modify the code to store and output the different FOV alignments.
