### ISSUE TITLE
Change python version pinning in environment.yml?

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#479]
i.e., change `python=3.6` to `python>=3.6`, unless there's some sort of package that breaks with 3.7 (?)

**Comment by pgunn** [comment]
Right now it's easier for us to support one version of Python, particularly because users are making an environment specifically for CaImAn. Is there a use-case you have in mind for loosening this pin?

**Comment by zbarry** [comment]
Hmm. I guess my situation is that when I use caiman when processing all my movies in batch (or any of my analysis pipelines), I use an environment specifically for that one pipeline. On the other hand, since I have a lot of projects that I'm working on simultaneously, I just have a single Jupyter lab instance running that has the packages to support all of them (I don't feel too bad about this since I'm mostly using it for prototyping and visualization of results rather than the critical computation portion). 

Don't think it's really a necessity & if it actually adds more technical effort supporting multiple versions of Python 3, I guess I could see not moving in that direction. Not sure of many (any? really don't know) packages that would break given a 3.6->3.7->3.x transition, but I guess that uncertainty is argument enough for just pinning if you want to make sure you have stability for the average user (and people like me can deal with the consequences of making messy custom environments).

**Comment by epnev** [comment]
Last time we checked there were some issues with opencv and python 3.7. If these are gone then we can consider lifting this pinning. In general, it's good to play it safe and be a late adopter.
