### ISSUE TITLE
Something to maybe keep on the radar: Python 3.8 multiprocessing module shared memory

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#481]
Looks like there's this really cool way in 3.8 to share memory between multiprocessing-spawned Python processes: https://docs.python.org/3.8/library/multiprocessing.shared_memory.html

Their numpy example looks pretty straightforward to implement (in a vacuum). Not sure how much of the performance cost right now is data serialization-based, but even if it's not too much of a bottleneck, maybe future caiman feature enhancements could take advantage of it (with a version check to toggle between shared memory vs. serialization-based multiprocessing modes (?) ).

Just thought I'd point it out since I saw it in a discussion for another multiprocessing-oriented package.

**Comment by pgunn** [comment]
This looks very interesting; we're still not ready to move to 3.7 yet, and 3.8 isn't quite released yet (looks like there are some alphas floating about), but when we're ready to push users to this version we'll probably experiment with this.

**Comment by zbarry** [comment]
Yeah, figured this would be a distant-future kind of thing considering how (rightly) careful you guys are with the reliability of the software for a growing userbase.

**Comment by epnev** [comment]
@zbarry  Thanks for the info; we're still a long way. CaImAn will still not work with python 3.7 although I believe this will be lifted soon. #483
