### ISSUE TITLE
Transforming S to spike numbers.

### ISSUE THREAD

**Issue by naranji** [flatironinstitute/CaImAn#499]
Inferred spike vector is float. I was wondering about the best way of comparing the S vector for two different neurons. Is there any standard way to transform S to some firing rate like variable?

**Comment by epnev** [comment]
@naranji 
In general, it is wise to interpret the output `S` as a signal that is roughly proportional to the firing rate at that moment. If you want to translate it into direct spike counts you can do either:

1. Quantize the neural activity `S` outputs to get spike counts. That's the easiest but least accurate/formal. The idea is you set an amplitude on the ` S` output that corresponds to one spike and then transform your output signal into spikes. It's best to do that on when operating on the DF/F traces `F_dff` that have scale invariance.

2. Use a different deconvolution algorithm that produces directly spike counts. We have an old Matlab based [MCMC algorithm](https://github.com/epnev/continuous_time_ca_sampler) which does that and works well but it's slow.

**Comment by naranji** [comment]
@epnev 
As far as I understood S lies in [0,1) range. Is that invariant among all neurons with different S/N? In other words, ca I directly compare two different neurons and say if S_1=0.03 and S_2=0.06 then neuron two is twice as active as neuron one in that particular moment?

**Comment by epnev** [comment]
@naranji I realized I left this unanswered. 

When using the constrained_foopsi method for deconvolution the spiking variable S does not immediately correspond to number of spikes or the spiking probability in each timebin. It merely represents a measure of "deconvolved neural activity" that is loosely proportional to the firing rate of the neuron at each time. To convert into actual spike counts some reference point is needed to threshold and quantize this signal. For example, if you deconvolve DF/F traces and have knowledge of what change in DF/F units a spike is inducing, you can use this information to approximate the number of spikes (under certain linearity assumptions). 

As such it is hard to compare the S values from two neurons directly, unless the traces have been converted into some DF/F units prior to the deconvolution.
