### ISSUE TITLE
Extract 1P data 

### ISSUE THREAD

**Issue by lun11** [flatironinstitute/CaImAn#500]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)** Windows 10, Anaconda3

- **Describe the issue that you are experiencing**
I am trying to extract data from the following traces: 
![bokeh_plot (3)](https://user-images.githubusercontent.com/41491620/55354304-5dac2800-5493-11e9-85c0-fe58848bed9e.png)
![bokeh_plot (4)](https://user-images.githubusercontent.com/41491620/55354305-600e8200-5493-11e9-8ae6-6fefe44a2045.png)

I tried using "cnmf.estimates.estimates.A", but the following error showed up.  I would really appreciate it if you could give us some hints on how to extract the data.  Thanks.

- **Copy error log below**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-90-1fea071e0255> in <module>
----> 1 cnmf.estimates.estimates.A

AttributeError: module 'caiman.source_extraction.cnmf.estimates' has no attribute 'estimates'

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@lun11 There should be only one `estimates` field. How about if you try `cnmf.estimates.A`?

**Comment by lun11** [comment]
@epnev Thank you for the prompt response.  I tried `cnmf.estimates.A`, but I received the following error message.   Just to clarify, I am trying extract the tracing, so I could make the plots either with python or other software.  Thank you.


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-91-b41ca2975c50> in <module>
----> 1 cnmf.estimates.A

AttributeError: module 'caiman.source_extraction.cnmf.estimates' has no attribute 'A'

**Comment by epnev** [comment]
@lun11 This seems resolved so I'm closing the issue but feel free to follow up/reopen it.

**Comment by lun11** [comment]
@j-friedrich @epnev Thank you for the input. I will reopen if I have more questions.
