### ISSUE TITLE
PointSelection __getitem__ only works with bool arrays

### ISSUE THREAD

**Issue by alex-attinger** [flatironinstitute/CaImAn#501]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
OS: Windows 10

- **Describe the issue that you are experiencing**
I am trying to run the demo_motion_correction.ipynp with my own file. The provided example works fine. However, when I try to run it with my own data (hdf5 file, uint16, data in '/mov'), I get the following error when running mc.motion_correct(). The movie is displayed correctly with load_movie_chain. Would be grateful for any hints. My original data is in Neurolabware's sbx format.

- **Copy error log below**
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\giocomolab\Miniconda3\envs\caiman\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\giocomolab\Miniconda3\envs\caiman\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\giocomolab\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 2436, in tile_and_correct_wrapper
    imgs = cm.load(img_name, subindices=idxs)
  File "C:\Users\giocomolab\Miniconda3\envs\caiman\lib\site-packages\caiman\base\movies.py", line 1315, in load
    f[var_name_hdf5][subindices]).squeeze()
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\giocomolab\Miniconda3\envs\caiman\lib\site-packages\h5py\_hl\dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "C:\Users\giocomolab\Miniconda3\envs\caiman\lib\site-packages\h5py\_hl\selections.py", line 72, in select
    sel[arg]
  File "C:\Users\giocomolab\Miniconda3\envs\caiman\lib\site-packages\h5py\_hl\selections.py", line 212, in __getitem__
    raise TypeError("PointSelection __getitem__ only works with bool arrays")
TypeError: PointSelection __getitem__ only works with bool arrays
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-14-2994c8f1b989> in <module>
      1 # correct for rigid motion correction and save the file (in memory mapped form)
----> 2 mc.motion_correct(save_movie=False)

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct(self, template, save_movie)
    237                                     np.max(np.abs(self.y_shifts_els))))
    238         else:
--> 239             self.motion_correct_rigid(template=template, save_movie=save_movie)
    240             b0 = np.ceil(np.max(np.abs(self.shifts_rig)))
    241         self.border_to_0 = b0.astype(np.int)

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_rigid(self, template, save_movie)
    289                 use_cuda=self.use_cuda,
    290                 border_nan=self.border_nan,
--> 291                 var_name_hdf5=self.var_name_hdf5)
    292             if template is None:
    293                 self.total_template_rig = _total_template_rig

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_batch_rigid(fname, max_shifts, dview, splits, num_splits_to_process, num_iter, template, shifts_opencv, save_movie_rigid, add_to_movie, nonneg_movie, gSig_filt, subidx, use_cuda, border_nan, var_name_hdf5)
   2257                                                                  fname)[-1][:-4] + '_rig_', subidx = subidx,
   2258                                                              num_splits=num_splits_to_process, shifts_opencv=shifts_opencv, nonneg_movie=nonneg_movie, gSig_filt=gSig_filt,
-> 2259                                                              use_cuda=use_cuda, border_nan=border_nan, var_name_hdf5=var_name_hdf5)
   2260 
   2261         new_templ = np.nanmedian(np.dstack([r[-1] for r in res_rig]), -1)

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correction_piecewise(fname, splits, strides, overlaps, add_to_movie, template, max_shifts, max_deviation_rigid, newoverlaps, newstrides, upsample_factor_grid, order, dview, save_movie, base_name, subidx, num_splits, shifts_opencv, nonneg_movie, gSig_filt, use_cuda, border_nan, var_name_hdf5)
   2594             dview.map(close_cuda_process, range(len(pars)))
   2595         elif 'multiprocessing' in str(type(dview)):
-> 2596             res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)
   2597         else:
   2598             res = dview.map_sync(tile_and_correct_wrapper, pars)

~\Miniconda3\envs\caiman\lib\multiprocessing\pool.py in get(self, timeout)
    668             return self._value
    669         else:
--> 670             raise self._value
    671 
    672     def _set(self, i, obj):

TypeError: PointSelection __getitem__ only works with bool arrays

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@alex-attinger Can you run again but setting `dview=None` when creating the MotionCorrect object? Post the error message that you get in that case.

**Comment by alex-attinger** [comment]
Thanks for your reply. I did:
mc = MotionCorrect(fnames, dview=None, **opts.get_group('motion'))

But the error does not seem to change:
TypeError                                 Traceback (most recent call last)
<ipython-input-21-4d1e407438e4> in <module>
      1 #%% Run piecewise-rigid motion correction using NoRMCorre
----> 2 mc.motion_correct(save_movie=True)
      3 m_els = cm.load(mc.fname_tot_els)
      4 border_to_0 = 0 if mc.border_nan is 'copy' else mc.border_to_0
      5     # maximum shift to be used for trimming against NaNs

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct(self, template, save_movie)
    233 
    234         if self.pw_rigid:
--> 235             self.motion_correct_pwrigid(template=template, save_movie=save_movie)
    236             b0 = np.ceil(np.maximum(np.max(np.abs(self.x_shifts_els)),
    237                                     np.max(np.abs(self.y_shifts_els))))

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_pwrigid(self, save_movie, template, show_template)
    335         if template is None:
    336             logging.info('Generating template by rigid motion correction')
--> 337             self = self.motion_correct_rigid()
    338             self.total_template_els = self.total_template_rig.copy()
    339         else:

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_rigid(self, template, save_movie)
    289                 use_cuda=self.use_cuda,
    290                 border_nan=self.border_nan,
--> 291                 var_name_hdf5=self.var_name_hdf5)
    292             if template is None:
    293                 self.total_template_rig = _total_template_rig

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_batch_rigid(fname, max_shifts, dview, splits, num_splits_to_process, num_iter, template, shifts_opencv, save_movie_rigid, add_to_movie, nonneg_movie, gSig_filt, subidx, use_cuda, border_nan, var_name_hdf5)
   2257                                                                  fname)[-1][:-4] + '_rig_', subidx = subidx,
   2258                                                              num_splits=num_splits_to_process, shifts_opencv=shifts_opencv, nonneg_movie=nonneg_movie, gSig_filt=gSig_filt,
-> 2259                                                              use_cuda=use_cuda, border_nan=border_nan, var_name_hdf5=var_name_hdf5)
   2260 
   2261         new_templ = np.nanmedian(np.dstack([r[-1] for r in res_rig]), -1)

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correction_piecewise(fname, splits, strides, overlaps, add_to_movie, template, max_shifts, max_deviation_rigid, newoverlaps, newstrides, upsample_factor_grid, order, dview, save_movie, base_name, subidx, num_splits, shifts_opencv, nonneg_movie, gSig_filt, use_cuda, border_nan, var_name_hdf5)
   2599         logging.info('** Finished parallel motion correction **')
   2600     else:
-> 2601         res = list(map(tile_and_correct_wrapper, pars))
   2602 
   2603     return fname_tot, res

~\Miniconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in tile_and_correct_wrapper(params)
   2434 #        imgs = cm.load(img_name, subindices=np.array(idxs))
   2435 
-> 2436     imgs = cm.load(img_name, subindices=idxs)
   2437     mc = np.zeros(imgs.shape, dtype=np.float32)
   2438     for count, img in enumerate(imgs):

~\Miniconda3\envs\caiman\lib\site-packages\caiman\base\movies.py in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype)
   1313                         else:
   1314                             images = np.array(
-> 1315                                 f[var_name_hdf5][subindices]).squeeze()
   1316                             #if images.ndim > 3:
   1317                             #    images = images[:, 0]

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

~\Miniconda3\envs\caiman\lib\site-packages\h5py\_hl\dataset.py in __getitem__(self, args)
    551 
    552         # Perform the dataspace selection.
--> 553         selection = sel.select(self.shape, args, dsid=self.id)
    554 
    555         if selection.nselect == 0:

~\Miniconda3\envs\caiman\lib\site-packages\h5py\_hl\selections.py in select(shape, args, dsid)
     70         elif isinstance(arg, np.ndarray):
     71             sel = PointSelection(shape)
---> 72             sel[arg]
     73             return sel
     74 

~\Miniconda3\envs\caiman\lib\site-packages\h5py\_hl\selections.py in __getitem__(self, arg)
    210         """ Perform point-wise selection from a NumPy boolean array """
    211         if not (isinstance(arg, np.ndarray) and arg.dtype.kind == 'b'):
--> 212             raise TypeError("PointSelection __getitem__ only works with bool arrays")
    213         if not arg.shape == self.shape:
    214             raise TypeError("Boolean indexing array has incompatible shape")

TypeError: PointSelection __getitem__ only works with bool arrays

**Comment by epnev** [comment]
@alex-attinger I believe this addition should fix the issue when running with `dview=None`
https://github.com/flatironinstitute/CaImAn/commit/df7d6bd92cb13f9a2e3a66d2e018ef1920f20678
Can you confirm?

When running with `dview=dview`, i.e., there seems to be another error that I'll need to look into.

**Comment by epnev** [comment]
@alex-attinger actually I think it should work with `dview=dview` as well. Let me know if you still get errors

**Comment by alex-attinger** [comment]
It works! Thank you! Unrelated question: Is there a recommended way of processing data from multiple separate z layers other than putting it into separate files?

**Comment by epnev** [comment]
@alex-attinger You're welcome; thanks for spotting this. 

Separate files is the way to go. In principle the code can be modified to e.g. read every N frames but that will require non-trivial amount of work. Are your z planes spaced far apart from each other to capture disjoint sets of neurons?
