### ISSUE TITLE
`inf` SNR from component quality estimation

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#503]
```python
# ~~~

yr, dims, t = cm.load_memmap(mc_filename)
y = yr.T.reshape((t,) + dims, order='F')

(idcs_components_good, idcs_components_bad, comp_snr, r_values, _
     ) = estimate_components_quality_auto(
        y,
        cnmf_estimates.A,
        cnmf_estimates.C,
        cnmf_estimates.b,
        cnmf_estimates.f,
        cnmf_estimates.YrA,
        framerate,  # 5
        decay_time,  # 0.4
        cnmf_params.init['gSig'],
        dims,
        dview=dview,  # None
        min_SNR=min_snr,  # 3
        r_values_min=r_values_min,  # 0.85
        min_SNR_reject=min_snr_reject,  # 0.5
        use_cnn=False
    )
```

One component had a `comp_snr` value of `inf` and an `r_value` of 0.9. I then went the different route of using `cnmf.deconvolution.GetSn` for noise estimation, which did give a proper value (see below). Here's what it looks like:

```python
%%opts Curve [width=750, height=400, fontsize=fontsize]

traces = cnmf_estimates.C + cnmf_estimates.YrA

trace_idx = 437

trace = traces[trace_idx, ...]
c_trace = cnmf_estimates.C[trace_idx, ...]

snr = comp_snr[trace_idx]
r_val = r_values[trace_idx]

noise_getsn = cnmf.deconvolution.GetSn(trace, range_ff=[0.25, 0.5], method='mean')
pnr_getsn = trace.max() / noise_getsn

dimopts = dict(kdims='time [frame]', vdims='intensity [AU]')

(
    hv.Curve(trace, **dimopts)
    .options(title_format=f'SNR: {snr} | r_value: {r_val:.2f} || noise[GetSn]: {noise_getsn:.2f} | PNR[GetSn]: {pnr_getsn:.2f}')
    +
    hv.Curve(c_trace, **dimopts)
    +
    component_overlay(im_corr, [contours[trace_idx]])
).cols(2)
```

![image](https://user-images.githubusercontent.com/4762711/55434134-e050e800-5564-11e9-9493-ed7e7ec98190.png)

Any idea why this might be happening? (Note: it was marked as a "good" component)

**Comment by epnev** [comment]
@zbarry If you put a breakpoint at around [this point](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/components_evaluation.py#L153) what values do you get for `sd_r` and `erf`? Is `sd_r` zero or `erf` infinite?

Also, is the computation based on the trace shown on the left or on the right panel?

**Comment by epnev** [comment]
@zbarry any updates on this or should I just close it?

**Comment by zbarry** [comment]
Sorry, meant to close. I should be good to go. I'll reopen if I see it happening again and do some debugging.
