### ISSUE TITLE
Problems installing CaImAn (basic issues)

### ISSUE THREAD

**Issue by KyeongMinMOON** [flatironinstitute/CaImAn#505]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
Windows 10, python version 3.6, Spyder

- **Describe the issue that you are experiencing**
Hi,

Firstly, thank you for providing this wonderful program.

I just follow your installing guide (in windows 10) that you mentioned, I found some error messages and i stocked in pip install . step now.

Three messages that i have got from following steps.
First message is from conda env create -f environment.yml -n caiman.
- Actually some warning message came out during this process, but it worked well (I guess) But i think it may can affect my error, so i mentioned it.

second message is from conda install -n caiman vs2017_win-64
- This step seems working well, but some error message came out before done this process. (I attach screen shot)

last error is from pip install . step.
- I am totally stocked in this step, and message said , that it can unable to create process using ..... (I also attach screen shot) 

Check the screen shots below. 

*I checked conda list after installing caiman vs2017,  however i couldn't find out caiman on it. 

Please give me some advice for that.

Thanks

- **Copy error log below**

![first question](https://user-images.githubusercontent.com/40463208/55600115-a9ade400-5795-11e9-885b-38ffee974c29.PNG)
![second question](https://user-images.githubusercontent.com/40463208/55600120-ac103e00-5795-11e9-87bb-770ca725b2a1.png)
![third question](https://user-images.githubusercontent.com/40463208/55600126-ae729800-5795-11e9-907e-c6cc3fb1b0c6.PNG)

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
The conda.compat thing is a little weird but harmless
The second part failed, so anything after is not likely to work. If you can try running this manually it may help us figure out what went wrong:

`C:\Users\MK\Anaconda\envs\caiman\Scripts\.qt-post-link.bat -v`

(I'm hoping this script wasn't removed as part of the rollback, but it may have been)

**Comment by KyeongMinMOON** [comment]
Hi,

Unfortunately, qt-post-link.bat -v file is not existed in Scripts folder.
However, i can find this file in two different folders C:\Users\MKM\Anaconda\Scripts\qt-post-link.bat -v and C:\Users\MKM\Anaconda3\pkgs\qt-5.6.2-h2639256_8\Scripts.

Thanks

**Comment by pgunn** [comment]
Ah. Unfortunately this doesn't leave me with a great path forward to debugging this - in an ideal world it'd stop where the install fails and let us poke at or repair the install process so it can go forward, but if it undoes its work when it encounters a problem it's going to be hard to diagnose and fix it.

Are you using conda for anything else? If not, we might want to try removing and reinstalling it and see if that helps.

**Comment by KyeongMinMOON** [comment]
Actually, i reinstalled conda three times before writing this issue. I will try to reinstall once again. But i am not sure it can help or not. 

I will tell you the results

Thanks,

**Comment by KyeongMinMOON** [comment]
Hi,

I reinstalled anaconda3, but same issue still occurred.

**Comment by pgunn** [comment]
Hi,
When installing Anaconda, what options did you use? The installer should have asked if you wanted to install for "just me" or for the whole system - the former works much better. Also, what directory did you install anaconda to?

**Comment by KyeongMinMOON** [comment]
Hi, 
I installed anaconda for ''just me''.
And anaconda directory is this.
(base) C:\Users\MKM>where anaconda 
(results)C:\Users\MKM\Anaconda3\Scripts\anaconda.exe
I am not sure this answer is the right.

**Comment by pgunn** [comment]
That all looks fine - I had seen some error reports similar to yours where people installed anaconda (or made environment names) with spaces or Unicode characters in them, leading to problems.

https://github.com/ContinuumIO/anaconda-issues/issues/1491

One thing you might try - delete the environment (conda env remove -n caiman)
And when you create it again (the `conda env create ...` command), add the `-v` flag. That will make it noisier and may cause it to show more useful debugging info.

**Comment by KyeongMinMOON** [comment]
I delete the environment and re-create env condition with adding -v flag, however i still have same problems. 
I attached results, 

I don't know what is wrong. 
I will re-install anaconda again. If you find some answers please tell me.

![Fourth Question](https://user-images.githubusercontent.com/40463208/55744527-1d8b0d80-5a70-11e9-8372-feefb9f15319.png)
![Fifth q](https://user-images.githubusercontent.com/40463208/55744532-1f54d100-5a70-11e9-8eb7-6094a977aca4.PNG)

**Comment by pgunn** [comment]
Hi,
That was actually quite helpful - it's complaining that it did not find the Visual Studio compiler. Are you sure you installed all the needed components of that?

**Comment by KyeongMinMOON** [comment]
Hi,
I installed Visual Studio 2017 using the link, that install guide mentioned. 
And i checked that i added C/C++ CLI Tools when i installed Visual studio.
But still same problem occurred. 
Is there any other needed components that i have to install including C/C++ CLI Tools?.

Thanks,

**Comment by KyeongMinMOON** [comment]
Hi,
Still some small errors occurred, but your solution `SET VS140COMNTOOLS=%VS100COMNTOOLS%` seems work! 
Because, remaining steps were done, and finally i can use pip install . without any problems.

After that, i run the caimanmanager.py to test demo files, but when i start debugging, 'No module named 'caiman'' message came out.
If i did something wrong with it, please knowing me

Thanks,

**Comment by pgunn** [comment]
Sounds like we're almost there. Because of how you may have configured python file associations on your computer, you may need to run scripts in caiman by saying `python scriptname` rather than just saying the script name. Try doing `python caimanmanager.py install` (you may need to provide the full path to caimanmanager). If this works you'll need to do the same for the demos if you want to run them.

**Comment by KyeongMinMOON** [comment]
Hi,

when i was trying `python scriptname`  after activating caiman, then this message came out 'python: can't open file 'scriptname': [Errno 2] No such file or directory'

I think i missed something, So i will check the install guide and demo_pipeline

If you have any solution about this please knowing me 

Thank you always,

**Comment by pgunn** [comment]
Hi,
Sorry, when you do it this way you will need to enter the full path to the script.

An alternative is to remove the .py file association, letting conda handle that.

**Comment by KyeongMinMOON** [comment]
Hi,

Finally, basic demos is working! 

Thanks,
