### ISSUE TITLE
uint64 type error in save_memmap

### ISSUE THREAD

**Issue by tvajtay** [flatironinstitute/CaImAn#506]
Ubuntu 16.04, Python 3.6, Jupyter notebook
I believe this same issue #448 has cropped up again for me. In `demo_pipeline.ipynb`, when trying to run `cm.save_memmap`. However, I only receive this error when I try to run multiple tiffs, if I only do one movie I don't get the error.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-ca43d3c83b71> in <module>
      2 # memory map the file in order 'C'
      3 fname_new = cm.save_memmap(mc.mmap_file, base_name='memmap_', order='C',
----> 4                            border_to_0=border_to_0) # exclude borders
      5 
      6 # now load the file

~/CaImAn/caiman/mmapping.py in save_memmap(filenames, base_name, resize_fact, remove_init, idx_xy, order, xy_shifts, is_3D, add_to_movie, border_to_0, dview, n_chunks, slices)
    396 
    397 
--> 398         fname_new = cm.save_memmap_join(fname_new, base_name=base_name, dview=dview, n_chunks=n_chunks)
    399 
    400     else:

~/CaImAn/caiman/mmapping.py in save_memmap_join(mmap_fnames, base_name, n_chunks, dview, add_to_mov)
    204 
    205     else:
--> 206         list(map(save_portion, pars))
    207 
    208     np.savez(base_name + '.npz', mmap_fnames=mmap_fnames, fname_tot=fname_tot)

~/CaImAn/caiman/mmapping.py in save_portion(pars)
    276     else:
    277         with open(big_mov, 'r+b') as f:
--> 278             f.seek(idx_start * np.uint64(Yr_tot.dtype.itemsize) * tot_frames)
    279             f.write(Yr_tot)
    280             computed_position = idx_end * np.uint64(Yr_tot.dtype.itemsize) * tot_frames

TypeError: 'numpy.float64' object cannot be interpreted as an integer

```

**Comment by pgunn** [comment]
The surprise here is that somehow it's becoming floating-type. Would you mind, right before that f.seek, inserting this like and letting me know what you see right before the excception triggers?

(tab it in to the same level as f.seek)
```
print(f"idx_start:{idx_start} tot_frames:{tot_frames}")
```

I'm guessing that somehow idx_start or tot_frames is floating-point rather than integer, although I don't know how that would happen.

**Comment by tvajtay** [comment]
Ok, will do that

**Comment by epnev** [comment]
@tvajtay I believe the change here https://github.com/flatironinstitute/CaImAn/commit/8342d9ac2de32522a762811ab97ec3df7edd8068 should fix the error. Can you confirm?

**Comment by tvajtay** [comment]
I think that fixed it, I was able to run multiple movies simultaneously through the pipeline.
Does CaImAn just concatenate multiple movies or does it analyze each one separately?

**Comment by epnev** [comment]
@tvajtay good to hear. If you pass a list of files CaImAn will process them as one big concatenated file.
