### ISSUE TITLE
Representative video image in jupyter notebook for trace plot has scale issue

### ISSUE THREAD

**Issue by tvajtay** [flatironinstitute/CaImAn#507]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
Ubuntu 16.04, Python 3.6, Jupyter notebook

- **Describe the issue that you are experiencing**
When running `cnm2.estimates.nb_view_components` the still image of the source movie starts small and then increases in size as the neuron slider is moved.

- **Copy error log below**

- **If you're not reporting an error, type your message below**
![Screenshot from 2019-04-05 11-59-11](https://user-images.githubusercontent.com/17116111/55641036-e7f9d200-579a-11e9-8bc8-e6ba97492541.png)
![Screenshot from 2019-04-05 11-59-48](https://user-images.githubusercontent.com/17116111/55641037-e7f9d200-579a-11e9-8225-b878c932d3fa.png)

**Comment by epnev** [comment]
@tvajtay Can you make the change introduced with https://github.com/flatironinstitute/CaImAn/commit/05778123f6d41339ca75e7d0c25666ce5ca3a2d8 and try again?

**Comment by tvajtay** [comment]
@epnev  Ok

**Comment by tvajtay** [comment]
@epnev The change worked, now aspect ratio is conserved and image does not change with slider

**Comment by epnev** [comment]
@tvajtay cool, thanks for checking.
