### ISSUE TITLE
Error when trying python caimanmanager.py install

### ISSUE THREAD

**Issue by lechen0802** [flatironinstitute/CaImAn#511]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
macOS, Python 3.6.7, Jupyter Notebook

- **Describe the issue that you are experiencing**
when I tried $ caimanmanager.py install, it gives me:
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/caimanmanager.py", line 43
    def do_install_to(targdir:str, inplace:bool=False, force:bool=False) -> None:
                             ^
SyntaxError: invalid syntax

Then I tried $ alias python = python3 $python caimanmanager.py install, I got 👍 Traceback (most recent call last):
  File "caimanmanager.py", line 14, in <module>
    from caiman.paths import caiman_datadir
  File "/Users/lechenqian/CaImAn/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "/Users/lechenqian/CaImAn/caiman/base/movies.py", line 68, in <module>
    from ..utils import visualization
  File "/Users/lechenqian/CaImAn/caiman/utils/visualization.py", line 35, in <module>
    from ..summary_images import local_correlations
  File "/Users/lechenqian/CaImAn/caiman/summary_images.py", line 31, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
  File "/Users/lechenqian/CaImAn/caiman/source_extraction/cnmf/__init__.py", line 12, in <module>
    from . import oasis
ImportError: cannot import name 'oasis'

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
The supported way to run caiman is in a conda environment built through our install instructions. Could you give that a try and let us know how it goes?

**Comment by lechen0802** [comment]
I installed Anaconda long ago and yesterday I tried to install the caiman by following the instructions on Installation on Mac step by step, except the first step 'Download and install Anaconda or Miniconda'. Am I supposed to reinstall the anaconda? And also another issue is I have python2.7, python 3.6.7 installed before Anaconda. I'm not familiar with how to handle these problems. I really appreciate your help.

**Comment by epnev** [comment]
@lechen0802 You have an old anaconda distribution that is based on python 2 and you're trying to install caiman which uses python 3. This can cause all sorts of problems. If you don't have an application that depends on Python 2.7 then I suggest you remove it and install Anaconda3. If you do, then you can install Anaconda3 and change your python path to point to this version when you install caiman.

**Comment by lechen0802** [comment]
Great! It works for me now. 

After reinstalling the Anaconda, I still encountered problem with $ pip install .
It turns out that I need to run these two lines(in known issue) first.
$ xcode-select --install
$ open /Library/Developer/CommandLineTools/Packages/

But because this known issue comes after the line saying ' If any of these steps gives you errors do not proceed to the following step without resolving it', I was stuck for a long time. 

After all, thank you for helping me out.

**Comment by epnev** [comment]
@lechen0802 glad it worked, and thanks for the feedback.
