### ISSUE TITLE
Error during source extraction (operands could not be broadcast together...)

### ISSUE THREAD

**Issue by AlexDenman** [flatironinstitute/CaImAn#512]
This error occurs when running Caiman on my institution's HPC cluster (Linux), using Python 3.6, CaImAn v1.0, which is installed within a Conda environment, as described in the installation instructions.  I am running Caiman via bash script.

On some files, source extraction fails with an error message like the following:
```Traceback (most recent call last): File "/data/denmanaj/scripts/AD_caiman_pipeline.py", line 400, in <module> main() File "/data/denmanaj/scripts/AD_caiman_pipeline.py", line 341, in main cnm.fit(images) File "/data/denmanaj/conda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 581, in fit self.deconvolve() File "/data/denmanaj/conda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 677, in deconvolve F = self.estimates.C + self.estimates.YrA ValueError: operands could not be broadcast together with shapes (786,66300) (787,66300)```

This error typically occurs on files with a large number of frames (>60k frames), although there is no set threshold (i.e. some files with >60k frames finish successfully, some with <60k frames produce the error). The same files always produce an error (i.e. there are no files that produce an error *sometimes*). All of my files have 400x400 pixels. The error does not occur when I process the same files on my workstation (Windows 10, similar Caiman install, run in Spyder).

The following folder contains log files from both successful (e.g. _4) and unsuccessful runs (e.g. _1, _8, _10, _11, etc.)
[AD_log_files.zip](https://github.com/flatironinstitute/CaImAn/files/3090766/AD_log_files.zip)

**Comment by epnev** [comment]
@AlexDenman Can you try the following:

1. When you configure the [`logging`](https://github.com/flatironinstitute/CaImAn/blob/master/demos/general/demo_pipeline_cnmfE.py#L42) in the demo file pass a filename variable so the output is saved, e.g. `filename='caiman.log'`
2. Add the line `logging.info("Shapes {0}, {1}".format(self.estimates.C.shape[0], self.estimates.YrA.shape[0]))` above line [567](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/source_extraction/cnmf/cnmf.py#L567) and below line 572 (but within that if command) on the file `cnmf.py`.
3. Run the code.
4. Look into the log file `caiman.log` for all the lines that look something like this: 
    `223764 [cnmf.py:fit():567][48336] Shapes 1204, 1204`. 
5. Paste these lines here. These lines print the dimensions of `C` and `YrA` and might give some insight on where the discrepancy occurs.

**Comment by AlexDenman** [comment]
@epnev 

I made the changes you described above. I've attached a log file.

The error output I received from SLURM (not recorded in Caiman log file) reads:
`ValueError: operands could not be broadcast together with shapes (104,36807) (105,36807)`

[caiman.log](https://github.com/flatironinstitute/CaImAn/files/3098472/caiman.log)

**Comment by AlexDenman** [comment]
@epnev 

I made the changes you described above. I've attached a log file.

The error output I received from SLURM (not recorded in Caiman log file) reads:
`ValueError: operands could not be broadcast together with shapes (104,36807) (105,36807)`

[caiman.log](https://github.com/flatironinstitute/CaImAn/files/3098472/caiman.log)

**Comment by epnev** [comment]
@AlexDenman Thanks, this is useful. I believe the error is due to the merging procedure. Can you run again with setting `merge_thr = 1` which effectively turn off merging?

If no error occurs for this file then I'll be confident that the error is due to that.

**Comment by epnev** [comment]
@AlexDenman Also, either delete or change the name of the log file because if you use the same name, any run will append to that file and makes reading them harder.

**Comment by AlexDenman** [comment]
@epnev I set `merge_thr = 1`, and the file was successfully processed. I've attached the log files
[here](https://github.com/flatironinstitute/CaImAn/files/3103716/caiman_logs_2.zip).

**Comment by epnev** [comment]
@AlexDenman Thanks, I'll look into what causes the error there. In the meantime you can run with this setting.

**Comment by epnev** [comment]
@AlexDenman I created a new branch named `issue_512` that I believe fixes the issue. If you want switch over there and try again to see if the problem is fixed. 

The changes are minor, you can see them here: https://github.com/flatironinstitute/CaImAn/commit/37bfb92025d9a02dd0da272ba931c6f36686bee7

**Comment by AlexDenman** [comment]
That fixed the problem, thanks! Closing.

**Comment by epnev** [comment]
@AlexDenman Thanks for your help with testing!

**Comment by epnev** [comment]
fixed with #514
