### ISSUE TITLE
ValueError: Cannot save <class 'tuple'> type.

### ISSUE THREAD

**Issue by naranji** [flatironinstitute/CaImAn#515]
When I try to save my results I get this error. Does anyone know why this is happenning?

----> 1 cnm.save('analysis_results.hdf5')

/mnt/sdb2/caiman_software/CaImAn-master/caiman/source_extraction/cnmf/cnmf.py in save(self, filename)
    603 
    604         if '.hdf5' in filename:
--> 605             save_dict_to_hdf5(self.__dict__, filename)
    606         else:
    607             raise Exception("Filename not supported")

/mnt/sdb2/caiman_software/CaImAn-master/caiman/utils/utils.py in save_dict_to_hdf5(dic, filename)
    357 
    358     with h5py.File(filename, 'w') as h5file:
--> 359         recursively_save_dict_contents_to_group(h5file, '/', dic)
    360 
    361 def load_dict_from_hdf5(filename):

/mnt/sdb2/caiman_software/CaImAn-master/caiman/utils/utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    441             h5file[path + key] = np.array(item)
    442         elif type(item).__name__ in ['CNMFParams', 'Estimates']: # parameter object
--> 443             recursively_save_dict_contents_to_group(h5file, path + key + '/', item.__dict__)
    444         else:
    445             raise ValueError('Cannot save %s type.' % type(item))

/mnt/sdb2/caiman_software/CaImAn-master/caiman/utils/utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    427         # save dictionaries
    428         elif isinstance(item, dict):
--> 429             recursively_save_dict_contents_to_group(h5file, path + key + '/', item)
    430         elif 'sparse' in str(type(item)):
    431             logging.info(key + ' is sparse ****')

/mnt/sdb2/caiman_software/CaImAn-master/caiman/utils/utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    443             recursively_save_dict_contents_to_group(h5file, path + key + '/', item.__dict__)
    444         else:
--> 445             raise ValueError('Cannot save %s type.' % type(item))
    446 
    447 

ValueError: Cannot save <class 'tuple'> type.

**Comment by epnev** [comment]
@naranji Is your code updated to include the changes shown in this commit? https://github.com/flatironinstitute/CaImAn/commit/f52d41c7aa2431195ef1c2df9519d9c5063763eb#diff-43e774193fefad197378efe92780532e
If not, you may want to incorporate these changes.
