### ISSUE TITLE
Register ROIs returning out-of-bounds indices

### ISSUE THREAD

**Issue by dwwest** [flatironinstitute/CaImAn#524]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**
Linux, Python 3.6

- **Describe the issue that you are experiencing**
I'm trying to register ROI's across multiple sessions using register_mulitsession() in rois.  I am trying to get the data back from assignments (`ndarray int of size # of total distinct components x # sessions element [i,j] = k if component k from session j is mapped to component i in the A_union matrix. If there is no much the value is NaN`).  I am looping over all of the elements in A_union to get component time-course data from all of my sessions.  However, I will end up getting and index, k, from this that is much greater than the length of the array of components from that session.  I.e. the index from assignments will be j=2606 for session 4 when there are only 206 components in that session.  Looking at the whole assignments array, it appears that the number of out-of-bounds assignments increases over the sessions in the order in which these sessions were input into register_multisession().

- **Copy error log below**
```
Traceback (most recent call last):
  File "show_processed_data.py", line 125, in <module>
    neurons = reconcile_neurons(all_neurons, experiments, processing_lengths, A_union, assignments)
  File "/kemeny_data01/dwest/TwoPhotonPipeline/label_neurons.py", line 26, in reconcile_neurons
    multi_registered_neurons['delta_f_f'].append(neurons[session]['delta_f_f'][int(multi_component[session])])
IndexError: index 1616 is out of bounds for axis 0 with size 208
```

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@dwwest Your error log has some customized variables `multi_registered_neurons, multi_component, neurons` which is not clear what they mean in your context. Can you describe what you want to do with the variable names given in the code?

**Comment by dwwest** [comment]
The function `reconcile_neurons(...)` consists of a nested for loop--iterating over the rows of assignments, and from there over each element of each row.  `multi_registered_neurons` is a dictionary initialized before the nested for loops, and is intended to be a dictionary of all the overlapping neurons (their label-numbers, coordinates, and time-traces for the entirety of an experiment).  `multi_component` is the variable from the first for loop, and corresponds to a row of assignments.  `neurons` is a list of dictionaries of all the neurons found in all chunks of data (where each index of the list is a chunk of processed data and each dictionary contains the label-numbers, coordinates, and time-traces for each neuron).  The idea is to reconcile all time traces for the entire length of the experiment with data on which neurons correspond to neurons later in the experiment and collect all the information in a single dictionary.  So for instance `multi_registered_neurons['delta_f_f'].append(neurons[session]['delta_f_f'][int(multi_component[session])])` means append the delta_f_f data from a given experimental session to our master-dictionary, `multi_registered_neurons` by indexing into assignments to get the label-number of the neuron in that session (because `multi_component` is a row of `assignments` and `session` will give the correct element.  There are about 200-300 components found for each chunk of data, and so I wouldn't expect there to be an elements of assignments to be greater than ~300, however after a certain point in the array, the elements get larger and larger until the array contains odd values in the thousands, as seen here.  Once I iterate over assignments and get to this point, my code, of course breaks and gives me an out of bounds error.  I'm concerned there may be an error somewhere in roi registration, but I'm not entirely sure.  I hope this is clear, and thank you for your help!  Code is below for the nested for loops.

```
def reconcile_neurons(neurons, experiments, processing_lengths, A_union, assignments):
    multi_registered_neurons = {'experiment_ind':experiments, 'overlap_ind':range(np.shape(assignments)[0]), \
        'coords':A_union, 'delta_f_f':[], 'deconvolved':[]}
    for multi_component in assignments:
        print(multi_component)
        # this gives the session number (indexing at zero) i.e. not the experiment index
        # but the chunk number (because experiments were processed in multiple chunks
        for session in range(len(multi_component)):
            if not np.isnan(multi_component[session]):
                multi_registered_neurons['delta_f_f'].append(neurons[session]['delta_f_f'][int(multi_component[session])])
                multi_registered_neurons['deconvolved'].append(neurons[session]['deconvolved'][int(multi_component[session])])
            else:
                multi_registered_neurons['delta_f_f'].append(np.zeros(processing_lengths[session]))
                multi_registered_neurons['deconvolved'].append(np.zeros(processing_lengths[session]))
```

**Comment by epnev** [comment]
@dwwest The script looks fine to me although it's hard to interpret so I might have missed something. There might be an error in the way you construct your `neurons` list. As a test I just ran the [script](https://github.com/flatironinstitute/CaImAn/blob/master/use_cases/eLife_scripts/figure_9/Figure_9_alignment.py) that generates Figure 9 in our caiman paper (just the forward assignment) and then typed:

```
np.nanmax(assign_forw, axis=0)
Out[15]: array([452., 392., 374., 377., 375., 372.])

[a.shape[-1] for a in A]
Out[16]: [453, 393, 375, 378, 376, 373]
```

This indicates that there is no shape mismatch between the `assignments` variable and the number of neurons in each session. You can try something similar for your case and see whether there is a mismatch. If not, the error must be somewhere else.

**Comment by dwwest** [comment]
I just ran the lines you requested with my own variables and obtained the following: `[1575, 1624, 1623, 1628, 1605, 1565, 1605, 1619, 1635, 1630, 1633, 1624, 1556, 1562]
[1574. 1623. 1622. 1627. 1604. 1564. 1604. 1618. 1634. 1629. 1632. 1623.
 1555. 1561.]`  Could there be some other issue with my setup?  I'll mention I didn't provide a template for `register_multisession()`, is that important?  Thank you!

**Comment by epnev** [comment]
@dwwest  The dimensions match (the difference of 1 is due to the python indexing) which suggests that there is no error during the assignment. In other words if 
`assignments[multi_component][session]` is not `NaN` then there exists a neuron whose shape is given by `A[session][:, int(assignments[multi_component][session])]`. So my guess is there is a mistake with how you construct your neuron class. I'm closing the issue because it doesn't appear to be a problem with the code base but feel free to ask any further questions.
