### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_oasis)

### ISSUE THREAD

**Issue by naranji** [flatironinstitute/CaImAn#525]
Why do I get this?
----> 1 from caiman.source_extraction import cnmf

/mnt/sdb2/caiman_software/CaImAn/caiman/source_extraction/cnmf/__init__.py in <module>
     10 from . import spatial
     11 from . import temporal
---> 12 from . import oasis
     13 from . import params
     14 from . import online_cnmf

ImportError: dynamic module does not define module export function (PyInit_oasis)

**Comment by epnev** [comment]
@naranji Did you try to update caiman in any way? It would be good to have the information that is requested from the issues template.

**Comment by naranji** [comment]
I simply removed the old caiman env, created a new caiman env pulled the repository and installed it fresh using pip install -e .

**Comment by epnev** [comment]
was your previous installation with `pip install .`?

**Comment by naranji** [comment]
I don't remember but probably yes.

**Comment by epnev** [comment]
Something went wrong with your installation. You can try using `pip install .` again in case there is a conflict there. @pgunn should be able to help you more.

**Comment by epnev** [comment]
@naranji Did you try using the `pip install .` option?

**Comment by pgunn** [comment]
Also, what are you running that evokes this error?

**Comment by naranji** [comment]
> @naranji Did you try using the `pip install .` option?

Yes, it did not do the job. 


> Also, what are you running that evokes this error?

I get it on initialization of cnmf object.

**Comment by naranji** [comment]
> Also, what are you running that evokes this error?

at the very begining when I try to import caiman.

**Comment by pgunn** [comment]
Sorry, what I meant by "What are you running" is what script are you running, and what is the path to it on your system?
