### ISSUE TITLE
Recalculating baseline post-CNMF-E when running OASIS giving "better" results than original estimates

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#528]
Would be nice to have some thoughts on this phenomenon. What I'm doing here is rerunning traces through OASIS after the CNMF-E analysis and having it calculate a fresh estimate of the baseline (instead of passing in `cnm.estimates.bl`). What I find is that, actually, the spike events trace `s` looks quite a bit sparser & more resilient to my drifting traces that I get with my long movies. (Note that if I indeed pass in the `bl` as in the commented out block below, I nearly perfectly recover the original denoised trace, though not exactly, for whatever reason.)

Was wondering what it means that the post-hoc estimated baseline is different from the one returned in the estimates object. Seems like the denoised traces & spike events that pop out are more reasonable and robust to noise using the re-estimation. If it is true that these traces are "better" (for some definition of better), it might even make sense to add this as the final step in the CNMF-E analysis(?)

```python
%%opts Curve [width=1250, height=175, active_tools=['wheel_zoom']]

A = cnmf_estimates.A
YrA = cnmf_estimates.YrA
C = cnmf_estimates.C
S = cnmf_estimates.S
movie_bl = cnmf_estimates.bl

noise_method = 'mean'
lags = 5
fudge_factor = 0.96
s_min = None
# s_min = -100
bas_nonneg=True
noise_range=[.25, .5]
optimize_g = 0

p = 1
g = None
sn = None

penalty = 1 if s_min is None else 0

###########

trace_idx = 50

# frame_range = np.s_[8000:]
frame_range = np.s_[:]

trace_yra = YrA[trace_idx, frame_range]
trace_c = C[trace_idx, frame_range]
trace_s = S[trace_idx, frame_range]
trace_bl = movie_bl[trace_idx]

trace = trace_yra + trace_c

###########

g, sn = estimate_parameters(trace, p=p, sn=sn, g=g, range_ff=noise_range,
    method=noise_method, lags=lags, fudge_factor=fudge_factor)

c, s, bl, g_updated, lam = constrained_oasisAR1(
    trace.astype(np.float32), g[0], sn, optimize_b=True, b_nonneg=bas_nonneg,
    optimize_g=optimize_g, penalty=penalty, s_min=0 if s_min is None else s_min)

# c, s, _, g, lam = constrained_oasisAR1(
#     (trace - trace_bl).astype(np.float32), g[0], sn, optimize_b=False, penalty=penalty)

residuals = trace - c

(
    hv.Curve(trace).options(title_format='Raw trace')
    + hv.Curve(trace_c).options(title_format='Denoised trace (previous)')
    + hv.Curve(c).options(title_format='Denoised trace (new)')
    + hv.Curve(trace_s, vdims='s').options(title_format='Spike events (previous)')
    + hv.Curve(s, vdims='s').options(title_format='Spike events (new)')
    + hv.Curve(trace_yra, vdims='y_res').options(title_format='Residuals (previous)')
    + hv.Curve(residuals, vdims='y_res').options(title_format='Residuals (new)')
).cols(1)
```

Trace 1:

![Screenshot from 2019-04-28 14-48-30](https://user-images.githubusercontent.com/4762711/56868880-5f9bd500-69c6-11e9-9902-f37045a0684e.png)

Trace 2:

![Screenshot from 2019-04-28 14-51-26](https://user-images.githubusercontent.com/4762711/56868882-632f5c00-69c6-11e9-9031-6cdbd1c24584.png)

Trace 3:

![Screenshot from 2019-04-28 14-56-24](https://user-images.githubusercontent.com/4762711/56868883-6591b600-69c6-11e9-80c5-5b9f844d31ef.png)

**Comment by epnev** [comment]
We can add this as an additional (optional) step.

**Comment by epnev** [comment]
I created a new method for the estimates object that just deconvolves the traces plus the option to deconvolve the detrended (plus normalized) traces. It's in the [`deconv`](https://github.com/flatironinstitute/CaImAn/tree/deconv) branch. I'll do some testing to see whether to include it as a last step in the `fit` method or just put it as an additional post-processing step in the various demos.
