### ISSUE TITLE
get_contours from HDF file

### ISSUE THREAD

**Issue by naranji** [flatironinstitute/CaImAn#545]
How do you plot the Neuron ROIs back from saved CNMFE analysis results?

**Comment by naranji** [comment]
I figured it out myself.
 
`f = h5py.File(h5File,'r')`
`est = f['estimates']`
`Ahd5 = est['A']`
`A = scipy.sparse.csc_matrix((Ahd5['data'],Ahd5['indices'],Ahd5['indptr']),shape=Ahd5['shape'])`
`coordinates = cm.utils.visualization.plot_contours(A,dims=dims)`
Thanks.

**Comment by epnev** [comment]
@naranji Yup.
There are two outstanding issues you opened a while ago #515 and #525 
Can we close those?
