### ISSUE TITLE
df_percentile can return invalid percentiles

### ISSUE THREAD

**Issue by haesemeyer** [flatironinstitute/CaImAn#551]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

Python 3.6 on Ubuntu Linux, running CaImAn from Jupyter QtConsole.

- **Describe the issue that you are experiencing**

The following is in reference or to reopen #398 . I encounter an invalid percentile error on some datasets. As the debug walk below shows this is caused by df_percentile returning the offending percentiles. data_prct returned by this function should probably be clipped between 0 and 100, in case kde returned invalid values. This would fix the error and should not have any unintended side effects

- **Debug output
debug walk shows that data_prct (used in line 390 of caiman/source_extraction/cnmf/utilities.py) contains the offending percentile of 100.02477. This variable is created by df_percentile in caiman/utils/stats.py.

> /home/martinh/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py(391)<listcomp>()
    389             else:
    390                 Fd = np.stack([scipy.ndimage.percentile_filter(
--> 391                     f, prctileMin, (frames_window)) for f, prctileMin in
    392                     zip(F, data_prct)])
    393                 Df = np.stack([scipy.ndimage.percentile_filter(

ipdb> prctileMin
100.02477130770946

> /home/martinh/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py(392)detrend_df_f()
    390                 Fd = np.stack([scipy.ndimage.percentile_filter(
    391                     f, prctileMin, (frames_window)) for f, prctileMin in
--> 392                     zip(F, data_prct)])
    393                 Df = np.stack([scipy.ndimage.percentile_filter(
    394                     f, prctileMin, (frames_window)) for f, prctileMin in

ipdb> data_prct.max()
100.02477130770946

- **Copy error log below**

RuntimeError                              Traceback (most recent call last)
~/PythonCode/imaging_pipeline/cai_test.py in <module>
    197     all_c = []
    198     for i, fn in enumerate(fnames):
--> 199         fit_cnm2 = main2(eparser.scanner_data[i]["fov"], frame_duration, fn)
    200         all_c.append(fit_cnm2.estimates.C)
    201     all_c = [a for b in all_c for a in b]

~/PythonCode/imaging_pipeline/cai_test.py in main2(fov, t_per_frame, filename)
    183     cai = CaImAn(4.0, fov, t_per_frame)
    184     im = cai.motion_correct(filename)[0]
--> 185     return cai.extract_components(im, filename)[1]
    186 
    187 

~/PythonCode/imaging_pipeline/cai_wrapper.py in extract_components(self, images, fname)
    200             cnm2.estimates.select_components(use_object=True)
    201             # extract DF/F values
--> 202             cnm2.estimates.detrend_df_f(**self.detrend_dff_params)
    203         finally:
    204             cm.stop_server(dview=dview)

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/estimates.py in detrend_df_f(self, quantileMin, frames_window, flag_auto, use_fast, use_residuals, detrend_only)
    633                                   frames_window=frames_window,
    634                                   flag_auto=flag_auto, use_fast=use_fast,
--> 635                                   detrend_only=detrend_only)
    636         return self
    637 

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py in detrend_df_f(A, b, C, f, YrA, quantileMin, frames_window, flag_auto, use_fast, detrend_only)
    390                 Fd = np.stack([scipy.ndimage.percentile_filter(
    391                     f, prctileMin, (frames_window)) for f, prctileMin in
--> 392                     zip(F, data_prct)])
    393                 Df = np.stack([scipy.ndimage.percentile_filter(
    394                     f, prctileMin, (frames_window)) for f, prctileMin in

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py in <listcomp>(.0)
    389             else:
    390                 Fd = np.stack([scipy.ndimage.percentile_filter(
--> 391                     f, prctileMin, (frames_window)) for f, prctileMin in
    392                     zip(F, data_prct)])
    393                 Df = np.stack([scipy.ndimage.percentile_filter(

~/anaconda3/envs/caiman/lib/python3.6/site-packages/scipy/ndimage/filters.py in percentile_filter(input, percentile, size, footprint, output, mode, cval, origin)
   1279     """
   1280     return _rank_filter(input, percentile, size, footprint, output, mode,
-> 1281                         cval, origin, 'percentile')
   1282 
   1283 

~/anaconda3/envs/caiman/lib/python3.6/site-packages/scipy/ndimage/filters.py in _rank_filter(input, rank, size, footprint, output, mode, cval, origin, operation)
   1140             percentile += 100.0
   1141         if percentile < 0 or percentile > 100:
-> 1142             raise RuntimeError('invalid percentile')
   1143         if percentile == 100.0:
   1144             rank = filter_size - 1

RuntimeError: invalid percentile

**Comment by epnev** [comment]
@haesemeyer Possibly also related to #429
Can you share the trace that gives this invalid percentile?

**Comment by haesemeyer** [comment]
@epnev Hi the attached file contains a trace for which df_percentile will return (100.024, 22.318). Hope this helps.
Thanks,
Martin


[trace_percentile_fail.npy.zip](https://github.com/flatironinstitute/CaImAn/files/3248537/trace_percentile_fail.npy.zip)

**Comment by epnev** [comment]
@haesemeyer Thanks. Similar to #429 the kernel density estimator fails on traces that are very short. If you replicate the array a couple of time then you start getting values that make more sense. See for examples what I get for the trace you sent me:

```
df_percentile(np.array(a.tolist()*1))
Out[50]: (100.02477130770946, 22.318409025690563)

df_percentile(np.array(a.tolist()*2))
Out[51]: (79.17029716572137, 18.122918143176648)

df_percentile(np.array(a.tolist()*3))
Out[52]: (80.42609814782074, 18.25344452618819)

df_percentile(np.array(a.tolist()*100))
Out[53]: (87.67350467848593, 18.86256764690873)

df_percentile(np.array(a.tolist()*300))
Out[54]: (87.69398972337818, 18.86256764690873)
```

I will include a fix to at least check for these wrong percentiles, but performing a DF/F extraction on such long traces will be very sensitive to small variations and the baseline estimate can be very inaccurate.

**Comment by epnev** [comment]
Introduced a workaround with 64307fa
If a percentile is outside the [0, 100] range the sequence is duplicated, and the process is repeated.

**Comment by haesemeyer** [comment]
@epnev Thanks for the fix and more importantly thanks for pointing me to the problem of the trace length. I simply set frames_window way too short (the actual data trace is considerably longer).

Thanks,
Martin

**Comment by epnev** [comment]
Good point; I didn't think this could also arise with very short window sizes.
