### ISSUE TITLE
CNM.fit in demo

### ISSUE THREAD

**Issue by eltabbal** [flatironinstitute/CaImAn#561]
I am using MacOS Mojave, Python 3.6, Spyder, demo_pipeline used for analysis

- **Describe the issue that you are experiencing**

I keep getting the same error message when running the demo-pipeline script on my data, everything works fine till trying to extract sources. My data size is not that big around 1.5Gb

- **Copy error log below**

  File "<ipython-input-21-17b4547af67b>", line 3, in <module>
    cnm = cnm.fit(images)

  File "/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 544, in fit
    indeces=indeces)

  File "/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 242, in run_CNMF_patches
    file_res = dview.map_async(cnmf_patches, args_in).get(4294967)

  File "/anaconda3/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value

BrokenPipeError: [Errno 32] Broken pipe

**Comment by pgunn** [comment]
Before we dive into this, can you tell me if the demo runs fine on the sample data?

**Comment by eltabbal** [comment]
Yeah, it works fine with the demo data, i can share the data file with you if this will help

**Comment by pgunn** [comment]
That'd be great

**Comment by eltabbal** [comment]
https://www.dropbox.com/s/hioouh6gw7ufhh4/Spontaneous_short.tif?dl=0

give it 5 mins, it will be uploaded. I decreased the bit size to 8 bit, it is still not working

**Comment by pgunn** [comment]
Did you just swap the filenames around when modifying the demo to run this, or did you need to make more substantial changes?

**Comment by eltabbal** [comment]
Just swapping the file names should be ok

**Comment by pgunn** [comment]
Apologies - I didn't get the time to do this today, but I will get to it tomorrow.

**Comment by epnev** [comment]
It run without problems for me (on MacOS Mojave) even without changing any parameters (which should be changed for this dataset, e.g., double the value of `rf` and `gSig`).

I haven't seen this error message before but a simple search reveals it arises somewhat often within the multiprocessing package.

**Comment by eltabbal** [comment]
I guess it is something in multiprocessing package as you said, any advice on how to fix that

**Comment by epnev** [comment]
@pgunn might have some ideas.

**Comment by pgunn** [comment]
Hi,
As far as I understand, this error usually happens because of problems with the size of data shared during IPC during multiprocessing. I suspect:
1) Were you to run in singlethreaded mode you would not see the issue (although performance would be markedly worse)
2) Were you to vary the amount of parallelism when you setup the cluster, you probably could find settings that would make the issue go away. You might also try ipyparallel rather than multiprocessing.

I'm puzzled that it works locally and fails for you, but first let's see if testing 1 shows that to be correct and if varying things as per 2 helps.

**Comment by eltabbal** [comment]
Yeah, it is working when running in single-threaded mode, however, it is requiring a bit more time. i will test also using the ipyparaellel, for now, I guess my issue is solved. thanks a lot for the support

**Comment by epnev** [comment]
@eltabbal You can also try reducing the number of `n_processes` as was suggested.

**Comment by eltabbal** [comment]
@epnev  yeah got the main idea from your suggestions and will play around with this
