### ISSUE TITLE
Issues with OnAcid

### ISSUE THREAD

**Issue by skasavica** [flatironinstitute/CaImAn#563]
Hello,

I have a few questions and issues about OnAcid software.

1. Can you tell me in which variable I can find the raw fluorescence trace?
2. Matrix S(deconvolved trace) after the fix that you implemented I get twice the number of frames than in C if the epochs=2, three times more if epochs=3 etc..... Do you have suggestions how to fix this?
3. Variables Yra,f,b are not in the correct format as documentation says, rather there are in format 2x number of frames, pixels, depending on the variable.
4. What should I use as a template input variable for multisession regist function to track cells across multiple days?
5.When I apply detrend_fdff function I get the following error: Its not possible to convert NaN to float, Which means I have Not a Number elements of my data. How can I overcome  this?

Thanks in advance

BR

Sergej

**Comment by epnev** [comment]
>  Can you tell me in which variable I can find the raw fluorescence trace?

It's in general given by the sum of `C` and `YrA`. Corresponds to non-deconvolved fluorescence (up to a scaling constant).

>  Matrix S(deconvolved trace) after the fix that you implemented I get twice the number of frames than in C if the epochs=2, three times more if epochs=3 etc..... Do you have suggestions how to fix this?

Yes, the matrix `S` will store the estimates from all the epochs. If you want to get the estimates from only the last epoch you would need to to get the last frames, e.g.
`cnm.estimates.S[:, -cnm.estimates.C.shape[-1]:]`
I'll introduce a fix for this.

>  Variables Yra,f,b are not in the correct format as documentation says, rather there are in format 2x number of frames, pixels, depending on the variable.

I just checked and `YrA` and `f` are in the correct format. Not sure what you're referring to. `b` and `A` can have a smaller number of pixels if you used downsampling. 

>   What should I use as a template input variable for multisession regist function to track cells across multiple days?

The correlation image is typically a good choice. There is a caveat in the sense if your dataset has large amounts of motion then the correlation image on the raw data might be somewhat inaccurate, and motion correction will be needed first. 

> When I apply detrend_fdff function I get the following error: Its not possible to convert NaN to float, Which means I have Not a Number elements of my data. How can I overcome this?

This probably relates to the previous issue you raised and my response there #556 
You should confirm that there are NaNs in your estimates variables `C` prior to applying the DF/F method.

**Comment by epnev** [comment]
`demo_OnACID_mesoscope.py` has been updated to show how to apply the shifts and obtain the registered file.
