### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by oregonGCAMP** [flatironinstitute/CaImAn#565]
- I'm running Windows 7, python version , Anaconda 1.9.7, python 3.6.7

- 
![image](https://user-images.githubusercontent.com/40069618/59791432-ef535680-9286-11e9-845b-86633e025976.png)

After running >python caimanmanager.py install --inplace
I get the error FileNotFoundError: [WinError 3] The system cannot find the paht specified: 'demos'
When I run >caimanmanager.py check 
I get the error The term 'caimanmanager.py' is not recognized ...

I'm not sure how to copy the Powershell Prompt text.

Also, if I try running the demo_pipeline notebook in Jupyter, I get the following error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-317b0bf1ba69> in <module>
     31     pass
     32 
---> 33 import caiman as cm
     34 from caiman.utils.utils import download_demo
     35 from caiman.utils.visualization import plot_contours, nb_view_patches, nb_plot_contour

ModuleNotFoundError: No module named 'caiman'

I assume that it is because I have not installed CaImAn correctly.

Thanks,

Andrei

**Comment by pgunn** [comment]
Hi,
When you used pip to install the library parts, what options did you provide? Did it complete successfully?

**Comment by oregonGCAMP** [comment]
I used 
**pip install -e .**
I didn't get errors during that part. Should I re-run it?

**Comment by pgunn** [comment]
You're sure you're in the caiman environment you did the install into?

If you do a `conda list | findstr caiman` what do you get?

**Comment by oregonGCAMP** [comment]
![image](https://user-images.githubusercontent.com/40069618/59877662-3874da80-935b-11e9-9064-077b67a3e81d.png)

**Comment by pgunn** [comment]
Ah, you're in the base environment right now. That's why it's not working. For any shell where you want to work with caiman, you need to do a `conda activate caiman` first.

**Comment by oregonGCAMP** [comment]
![image](https://user-images.githubusercontent.com/40069618/59877837-ade0ab00-935b-11e9-8d10-dc925fb992c0.png)

**Comment by pgunn** [comment]
That's looking much better. Give caimanmanager another go.

**Comment by oregonGCAMP** [comment]
![image](https://user-images.githubusercontent.com/40069618/59878116-542cb080-935c-11e9-9609-a1d668c00b6b.png)

**Comment by pgunn** [comment]
Unfortunately, there are a lot of ways that paths can work on Windows. As you did an install with the -e flag, go into the source tree and do `python caimanmanager.py install` instead.

**Comment by oregonGCAMP** [comment]
You'd like me to be in the CaImAn directory?

**Comment by pgunn** [comment]
Ordinarily I'd say no, but since you did an in-place install, that's fine. Yes.

**Comment by oregonGCAMP** [comment]
![image](https://user-images.githubusercontent.com/40069618/59878951-732c4200-935e-11e9-9130-c499153160ae.png)

**Comment by pgunn** [comment]
Apologies. Add the --inplace command to that above.

**Comment by oregonGCAMP** [comment]
![image](https://user-images.githubusercontent.com/40069618/59879379-69570e80-935f-11e9-9897-9f0977f2f395.png)

**Comment by pgunn** [comment]
Great. That's what we wanted to see. Now you can go into that data dir and run demos and otherwise work with the code - the install is now successful.

**Comment by oregonGCAMP** [comment]
Weird, I get the same error..
![image](https://user-images.githubusercontent.com/40069618/59879672-1762b880-9360-11e9-9585-04649589e0ea.png)

**Comment by pgunn** [comment]
What command are you running that gives you this error?

**Comment by oregonGCAMP** [comment]
I was just running the demo_pipeline notebook in Jupyter.

**Comment by pgunn** [comment]
Ah. For this to work, you'll need to make sure you launch jupyter from inside the  conda environment - ideally install it from conda.

**Comment by pgunn** [comment]
(alternatively, if you know how to define custom kernels, you can make on that lives in the caiman environment and use Jupyter as you always do, although setting this up takes some work and is not something I can do for you over a github issue)

**Comment by oregonGCAMP** [comment]
I'm not too familiar with that, so it will have to wait.

Thanks for your help!

**Comment by epnev** [comment]
@oregonGCAMP

**Comment by epnev** [comment]
@oregonGCAMP I don't understand. 
Are you trying to run the file `demo_pipeline.py` or `demo_pipeline.ipynb` through jupyter?

**Comment by epnev** [comment]
You should be able to open an jupyter notebook from within your caiman environment and run the `demo_pipeline.ipynb` file. Is this something that fails?

**Comment by oregonGCAMP** [comment]
I don't have a demo_pipeline.py, only demo_pipeline.ipynb.
Running it from the caiman environment works.

**Comment by epnev** [comment]
ok good to know (for reference the `demos/general` folder contains non-notebook versions of the demos)
