### ISSUE TITLE
demo_pipeline download

### ISSUE THREAD

**Issue by oregonGCAMP** [flatironinstitute/CaImAn#566]
When running the demo_pipeline in jupyter (windows 7, python 3.7.3), I get the following error in the download the dataset if not already present cell (sorry it's a little verbose):

downloading Sue_2x_3000_40_-46.tifwith urllib
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-3-2af042ebf6cf> in <module>
      1 if fname[0] in ['Sue_2x_3000_40_-46.tif','demoMovie.tif']:
----> 2     fname = [download_demo(fname[0])]

c:\users\sdrulla\caiman\caiman\utils\utils.py in download_demo(name, save_folder)
     90             url = file_dict[name]
     91             print("downloading " + name + "with urllib")
---> 92             f = urlopen(url)
     93             data = f.read()
     94             with open(path_movie, "wb") as code:

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221     else:
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 
    225 def install_opener(opener):

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in open(self, fullurl, data, timeout)
    530         for processor in self.process_response.get(protocol, []):
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 
    534         return response

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in http_response(self, request, response)
    640         if not (200 <= code < 300):
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 
    644         return response

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in error(self, proto, *args)
    562             http_err = 0
    563         args = (dict, proto, meth_name) + args
--> 564         result = self._call_chain(*args)
    565         if result:
    566             return result

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in http_error_302(self, req, fp, code, msg, headers)
    754         fp.close()
    755 
--> 756         return self.parent.open(new, timeout=req.timeout)
    757 
    758     http_error_301 = http_error_303 = http_error_307 = http_error_302

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in open(self, fullurl, data, timeout)
    530         for processor in self.process_response.get(protocol, []):
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 
    534         return response

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in http_response(self, request, response)
    640         if not (200 <= code < 300):
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 
    644         return response

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in error(self, proto, *args)
    568         if http_err:
    569             args = (dict, 'default', 'http_error_default') + orig_args
--> 570             return self._call_chain(*args)
    571 
    572 # XXX probably also want an abstract factory that knows when it makes

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 400: Bad Request

**Comment by pgunn** [comment]
Hi,
Could you include a little bit more log? Right above this it should give you the http request it's making.

**Comment by oregonGCAMP** [comment]
Hi, 
Here's the screenshot:
![image](https://user-images.githubusercontent.com/40069618/59944701-4dfd0980-941a-11e9-8b34-163f1b8b8269.png)

**Comment by pgunn** [comment]
Out of curiosity, if you visit this URL in a browser, what do you get?

https://caiman.flatironinstitute.org/~neuro/caiman_downloadables/Sue_2x_3000_40_-46.tif

**Comment by oregonGCAMP** [comment]
I downloaded the movie, placed in the folder and was able to proceed through the notebook. 

Thanks.
