### ISSUE TITLE
3D Motion Correction

### ISSUE THREAD

**Issue by epnev** [flatironinstitute/CaImAn#570]
@bendichter Here are the basic steps needed to extend the motion correction algorithm to volumetric (3D) data. The main step is to write down a function that given a volume of data and a template, aligns the volume to the template.

To do that we need the following pieces:

- [ ] Break the volume and template into a sequence of overlapping sub-volumes and sub-templates. We have a function for this in [2D](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/motion_correction.py#L1718) but should be easy to extend in 3D.
- [ ] Align each sub-volume to its corresponding sub-template. The [`register_translation_3d`](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/motion_correction.py#L1220) method should be able to do this, although some testing is needed to ensure that it works accurately for sub-pixel registration.
- [ ] Align the inferred shifts from each sub-volume into a 3D grid. Upsample this grid to the original resolution of the 3D volume. Some care will be needed to there to ensure this is done correctly. For example, you can place each shift at the center of each subvolume and then interpolate/extrapolate between them. At the output, you should three volumes (one for each of the x-, y-, z-directions) that would locate how much in each direction has each pixel moved. In 2D we use the `cv2.resize` method which is not applicable to 3D. However, scikit-image has a method for [this](https://scikit-image.org/docs/dev/api/skimage.transform.html#resize).
- [ ] Apply the shifts to register the volume. Again in 2D we use the `cv2.remap` method which is not applicable to 3D, but scikit-image has the [`warp` method](https://scikit-image.org/docs/dev/api/skimage.transform.html#warp) that can do this job.

Let's start with this. Once this is done, we'll wrap around it the other methods we have for estimating template, correcting sequences of volumes, memory mapping etc.

**Comment by as31** [comment]
@epnev @bendichter 
Hi guys, I'm going to start working on this issue now

**Comment by epnev** [comment]
Cool, let me know if you have any questions.

**Comment by as31** [comment]
Is there a sample 3D dataset that I can use to test scripts on? I can generate one but if one existed already that would be ideal

**Comment by epnev** [comment]
Nothing with any sort of ground truth. Since at this point we just want to register two volumes against each other I'd suggest you generate one. Let me know if you need help with that.

**Comment by as31** [comment]
Ok - i'm generating a sample dataset using NAOMi and a flat average zstack. Is there a dropbox I could use to upload these files?

**Comment by epnev** [comment]
I can host it and make it available from here if you share it from me.

**Comment by bendichter** [comment]
Thanks for the support @epnev I can also host the data if needed

**Comment by as31** [comment]
Question about typing: the 2d code was written with float64 in mind while the 3d code that is already established seems to work primary in float32. Should I keep this convention? (I'm guessing it saves a bunch on ram?)

**Comment by as31** [comment]
I have the data currently on a google drive folder:
https://drive.google.com/open?id=1sxMpZ5_j24HlMQRoKG03_H--NnuFYm6D
The relevant files for these analyses are: 
baseim.h5 (/mov has the 3d volume image to correct against)
sampled3dMovie.h5 (/mov has a 4d array for a movie with motion, set at planes 20+(1:24)*5 of the baseim movie)
motion.h5 (/motion has a 4d array corresponding to the x,y,z motion for each line of each plane of each frame)
This corresponds to a sample 3d movie without activity with planes taken at 1um xy sampling and 5um z sampling for 24 axial planes scanned sequentially at 5Hz per plane (120Hz overall).

**Comment by epnev** [comment]
float32 is fine, thanks.

**Comment by bendichter** [comment]
@epnev, @as31 is working on this. Can you assign him this issue?

**Comment by as31** [comment]
[https://github.com/flatironinstitute/CaImAn/pull/586](url)  rigid correction is mostly functional (through motion_correction.py, version in movies.py is incomplete). piecewise motion correction still needs to be debugged. i'm not sure how to directly link the draft pull request to this issue

**Comment by as31** [comment]
#586

**Comment by tvajtay** [comment]
I would also be open to helping on this issue.

**Comment by epnev** [comment]
Implemented with #611 Still in beta form.
Thanks to @as31
