### ISSUE TITLE
Basic questions of the noise and the baseline.

### ISSUE THREAD

**Issue by Ruyi-Yang** [flatironinstitute/CaImAn#571]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**
Hi, when I analysis data from two-photon imaging, I met a question, I don't know how to get the standard deviation of the noise, could I get the signal of noise? And how to define the baseline? If  I have 20 trails. 
Waiting for help. Thank you！

**Comment by epnev** [comment]
@Ruyi-Yang Do you want the noise level and the baseline for each trace or for the whole dataset?

If you want for the traces the noise level for each trace is stored in `cnm.estimates.neurons_sn` and the baseline levels at `cnm.estimates.bl`.

If you want for the whole dataset the noise level for each pixel is stored in `cnm.estimates.sn` and the baseline is part of the background stored in the pairs `cnm.estimates.b` and `cnm.estimates.f`.
