### ISSUE TITLE
Module Import Error

### ISSUE THREAD

**Issue by maxseppo** [flatironinstitute/CaImAn#573]
Any help with the following error is greatly appreciated:

I am running Python 3.7 in a Jupyter Notebook on Windows 10. I am attempting to run demo_motion_correction.ipynb, I get the following error following the first (import) section: 

![Screenshot (2)](https://user-images.githubusercontent.com/47156254/60600044-77ecef00-9d7d-11e9-8481-f66216090176.png)

**Comment by epnev** [comment]
@maxseppo are you inside your caiman environment?

**Comment by pgunn** [comment]
FYI, it usually helps if you use conda to install and run Jupyter rather than use an external install of Jupyter.

**Comment by maxseppo** [comment]
I believe I am inside the caiman environment and that I used conda to install Jupyter (I launched the notebook via the anaconda prompt).

**Comment by epnev** [comment]
Try once more by launching jupyter from inside your environment to be sure. If you have followed the instructions you should be using python 3.6 and not 3.7

**Comment by maxseppo** [comment]
Indeed, I am using Python 3.6, although I thought I downloaded Anaconda 3.7 as directed to following the links under Installation on Windows. Anyway, I get the same error posted above when I launch jupyter with: 
![Screenshot (9)](https://user-images.githubusercontent.com/47156254/60622406-4b050000-9dae-11e9-988d-46513f24815f.png)

**Comment by pgunn** [comment]
Let's try another test. Activate the caiman environment (no need to enter the caiman directory), but instead of launching jupyter, just launch python. From the python shell, type `import caiman`. Does that work?

**Comment by maxseppo** [comment]
Here is what I got: 
![Screenshot (11)](https://user-images.githubusercontent.com/47156254/60671875-1c386980-9e42-11e9-8016-bf27ece6fd92.png)

**Comment by pgunn** [comment]
That's very surprising - line 65 of caiman\motion_correction.py should not read (quite) like that. You didn't modifiy the caiman sources during installation, did you?

If you take a look at that last file, it should read `from .mmapping import prepare_shape` (note the dot before mmapping). Does it?

**Comment by maxseppo** [comment]
Strange - I must have accidentally deleted the dot while looking through the script. Working now. Apologies for the silly issue!
