### ISSUE TITLE
mc.coord_shifts_els is list of None values after pw_rigid motion correction

### ISSUE THREAD

**Issue by dominic-Evans** [flatironinstitute/CaImAn#576]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

MacOS High Sierra, python 3.6.8 Anaconda, Jupyter Notebooks, demo scripts (demo_pipeline_cnmfE and demo_motion correction, also using own data)

- **Describe the issue that you are experiencing**

I'm not sure if this is an error but I would appreciate help in understanding why **mc.coords_shifts_els** is populated with None values after running pw motion correction successfully, but x_shifts_els and y_shifts_els are populated with numbers. I've found this to be independent of the file that was motion corrected. I'm trying to use mc.apply_shifts_movie, but without mc.coords_shifts_els, I can only apply the rigid shifts. 

Thanks a lot, 
Dominic

- **Copy error log below**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-7941cb9b1559> in <module>
----> 1 G = mc.apply_shifts_movie(fname_raw, border_nan='copy',rigid_shifts=False)

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/motion_correction.py in apply_shifts_movie(self, fname, rigid_shifts, border_nan)
    402         else:
    403             dims_grid = tuple(np.max(np.stack(self.coord_shifts_els[0], axis=1), axis=1) - np.min(
--> 404                 np.stack(self.coord_shifts_els[0], axis=1), axis=1) + 1)
    405             shifts_x = np.stack([np.reshape(_sh_, dims_grid, order='C').astype(
    406                 np.float32) for _sh_ in self.x_shifts_els], axis=0)

~/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/shape_base.py in stack(arrays, axis, out)
    408     """
    409     _warn_for_nonsequence(arrays)
--> 410     arrays = [asanyarray(arr) for arr in arrays]
    411     if not arrays:
    412         raise ValueError('need at least one array to stack')

TypeError: 'NoneType' object is not iterable

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@dominic-Evans This is a bug I had encountered and fixed earlier in June 10 2a5b160f5c02362e5fa8568a624b538768763580 
If you downloaded CaImAn before that you probably don't have these changes and you'll need to update it. 

Unfortunately, we have introduced a couple of new dependencies with our latest release so you will need to create a new environment. You can find instructions [here](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

Let me know if this fixes your problem.

**Comment by dominic-Evans** [comment]
@epnev Thanks for your swift reply. I didn't remake the environment last time I updated so perhaps that's why I didn't have it. 

I think lines 430-441 are indented one level too far, as now **rigid shifts = True** does not return the movie. Regards, Dominic

**Comment by epnev** [comment]
thanks for noticing this. should be fixed now.
