### ISSUE TITLE
DISPLAY variable problem with matplotlib

### ISSUE THREAD

**Issue by tvajtay** [flatironinstitute/CaImAn#581]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**
CentOS 7 ,Python 3.6.6, SLURM/CLI, a variation of `demo_pipeline.py` that I edited to take CLI arguments, save a contour plot image with numbers, and save a denoised avi.

- **Describe the issue that you are experiencing**
I have updated to the current version of CaImAn and I am encountering this issue where when I try to plot the contours of selected components I receive an error message.

- **Copy error log below**
```
Traceback (most recent call last):
  File "/home/tjv55/slurm_pipeline.py", line 249, in <module>
    main()
  File "/home/tjv55/slurm_pipeline.py", line 222, in main
    cnm2.estimates.plot_contours(img=Cn, idx=cnm2.estimates.idx_components)
  File "/home/tjv55/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/estimates.py", line 187, in plot_contours
    plt.figure()   
  File "/home/tjv55/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/home/tjv55/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/tjv55/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 167, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/home/tjv55/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 24, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/home/tjv55/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 234, in __init__
    _create_qApp()
  File "/home/tjv55/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 125, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
```

**Comment by pgunn** [comment]
Hi,
Usually this happens because you've ssh'd to a system to do work but you didn't specify options to ssh to create a graphical session. You can usually check this by running xlogo or xterm after sshing and seeing if they come up. If they also complain that display is not set, change how you're sshing (e.g. add the `-X` flag).

If you're not using ssh (running locally, or perhaps using a job queueing system like slurm) let me know and we'll figure out an alternate route.

**Comment by tvajtay** [comment]
I was using slurm in this case

**Comment by pgunn** [comment]
Ah. If you're getting a shell on the system using slurm, you'll want to check the docs for your local cluster - there are plug-ins to slurm that let you allocate a node in shell mode that set up X11 plumbing correctly. Alternatively, if you allocate it with one command and then can ssh into your allocated node (from another terminal) to do the work you can add `-X` to that ssh. Slurm complicates things for anything that needs X11 forwarding.

**Comment by tvajtay** [comment]
Would running an interactive node via srun be preferable in this case?

**Comment by pgunn** [comment]
I don't think interactive mode sets up X11 forwarding (you can test with something less elaborate than Caiman). So either your local SLURM has those X11 extensions installed or you should just use slurm to allocate the node and separately ssh to it to get the graphics plumbing worked out.

(there is a chance, if you can't ssh to slurm nodes with your local setup and your cluster also doesn't have the X11 extension installed, that you may not be able to do this at all)

**Comment by tvajtay** [comment]
We have interactive GUI's via OnDemand that I believe use X11, so I guess if you need to save plots on a cluster do it with a GUI? I had this working before with ssh on the cluster, so I'm going to try and see if running pipeline with a GUI fixes everything and then go from there.

**Comment by pgunn** [comment]
FYI, if you're running code that happens to bring up a GUI but doesn't need input of any kind to proceed, I've had luck using xvfb-run (part of the Xvfb suite that starts up a mock X server) to fake that stuff out. This may not be what you need though.

**Comment by tvajtay** [comment]
So just leaving out `cnm2.estimates.plot_contours` prevented the error. I was doing that so I could have the activity heat map and numbered ROI's on the same plot. Preferably it would be nice to have a jupyter notebook that would do the Bokeh plots from just the hdf5 output file but that's a separate issue/feature request, and doesn't fix this issue.

**Comment by pgunn** [comment]
You should be able to cut'n'paste code from the demos into a Jupyter notebook if that'd be helpful.

(to get xvfb-run you may need to install the Xvfb Xserver unless it's already installed in your OS Image)
