### ISSUE TITLE
Install Issues on Windows 10 Pro 1903

### ISSUE THREAD

**Issue by RossRucho** [flatironinstitute/CaImAn#582]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

OS: Windows 10 Pro 1903
In (base) environment: Python 3.7.3
In (caiman) environment: Python 3.6.7

- **Describe the issue that you are experiencing**
During installation everything appears to go smoothly up to the command "pip install -e .". During execution of this command multiple errors are thrown and the pip install won't complete. Below, I'm copying the entire command prompt output from the execution of the pip install mentioned above (additionally, the text beginning with the first ERROR line is in red). 

- **Copy error log below**

Obtaining file:///C:/Windows/System32/CaImAn
Installing collected packages: caiman
  Running setup.py develop for caiman
    ERROR: Complete output from command 'C:\Users\nel\Anaconda3\envs\caiman\python.exe' -c 'import setuptools, tokenize;__file__='"'"'C:\\Windows\\System32\\CaImAn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps:
    ERROR: running develop
    running egg_info
    writing caiman.egg-info\PKG-INFO
    writing dependency_links to caiman.egg-info\dependency_links.txt
    writing top-level names to caiman.egg-info\top_level.txt
    reading manifest file 'caiman.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.py' under directory 'SPGL1_python_port'
    writing manifest file 'caiman.egg-info\SOURCES.txt'
    running build_ext
    building 'caiman.source_extraction.cnmf.oasis' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\nel\Anaconda3\envs\caiman\lib\site-packages\numpy\core\include -IC:\Users\nel\Anaconda3\envs\caiman\include -IC:\Users\nel\Anaconda3\envs\caiman\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpcaiman/source_extraction/cnmf/oasis.cpp /Fobuild\temp.win-amd64-3.6\Release\caiman/source_extraction/cnmf/oasis.obj
    oasis.cpp
    c1xx: fatal error C1083: Cannot open source file: 'caiman/source_extraction/cnmf/oasis.cpp': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command "'C:\Users\nel\Anaconda3\envs\caiman\python.exe' -c 'import setuptools, tokenize;__file__='"'"'C:\\Windows\\System32\\CaImAn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in C:\Windows\System32\CaImAn\

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
on your system, does the following file exist?

C:\Windows\System32\CaImAn\caiman\source_extraction\cnmf\oasis.cpp

**Comment by pgunn** [comment]
Oh, wait, hang on. Did you clone the caiman sources under C:\Windows\System32\CaImAn ? That's a weird and not good place to put things. Please remove that directory and do the checkout again under your home directory.

**Comment by RossRucho** [comment]
Yes, the file does exist, and I thought it was a weird location too but that was the default folder that a new command prompt opened into. I'll move it and try again--will update soon.

**Comment by donglabimaging** [comment]
Hi we are having similar issue with `pip install .`.  It shows similar error messages ERROR: Complete output from command 'C:\Users\allenli\Anaconda3\envs\caiman\python.exe' etc, but we don't have CaImAn in System32.

**Comment by RossRucho** [comment]
I was able to solve my problem by moving the CaImAn folder out of System32. I'm new to Windows and I think when I ran the anaconda prompt originally I ran it as an administrator, so it dropped me into the wrong folder. Someone else seems to be having a problem, do you still want me to close this issue?

**Comment by donglabimaging** [comment]
I believe that it is related to m Visual Studio Installation.  You can go ahead and close this issue.  Thank you.
