### ISSUE TITLE
Reading .sbx (scanbox) files

### ISSUE THREAD

**Issue by bdudok** [flatironinstitute/CaImAn#587]
-  Windows, python 3.6, running from PyCharm (console disabled). I'm running a copy of the demo script demo_pipeline.py saved in a new folder under caiman_data, and edited to read my .sbx file.

- The demo script ran without error on the included sample data.  When the input file is changed to a .sbx source, running the script throws the following error:

C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\python.exe C:/Users/bdudok/caiman_data/Barna_Batch/demo_pipeline_sbx.py
        5203 [params.py:                 set():797][1208] Changing key fnames in group data from None to ['test_155_261.sbx']
        5203 [params.py:                 set():797][1208] Changing key fr in group data from 30 to 15.6
        5203 [params.py:                 set():797][1208] Changing key pw_rigid in group motion from False to True
        5203 [params.py:                 set():797][1208] Changing key max_shifts in group motion from (6, 6) to [20, 20]
        5203 [params.py:                 set():797][1208] Changing key strides in group motion from (96, 96) to (100, 100)
        5203 [params.py:                 set():797][1208] Changing key overlaps in group motion from (32, 32) to (24, 24)
fatal: Not a git repository (or any of the parent directories): .git
Reading Iteration:0
C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\base\movies.py:1654: RuntimeWarning: overflow encountered in long_scalars
  fo.seek(k * nSamples, 0)
Traceback (most recent call last):
  File "C:/Users/bdudok/caiman_data/Barna_Batch/demo_pipeline_sbx.py", line 270, in <module>
    main()
  File "C:/Users/bdudok/caiman_data/Barna_Batch/demo_pipeline_sbx.py", line 128, in main
    mc.motion_correct(save_movie=True)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 234, in motion_correct
    self.motion_correct_pwrigid(template=template, save_movie=save_movie)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 336, in motion_correct_pwrigid
    self = self.motion_correct_rigid()
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 290, in motion_correct_rigid
    var_name_hdf5=self.var_name_hdf5)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 2272, in motion_correct_batch_rigid
    m = cm.load(fname, var_name_hdf5=var_name_hdf5, subindices=corrected_slicer)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\base\movies.py", line 1402, in load
    return movie(sbxreadskip(file_name[:-4], subindices), fr=fr).astype(outtype)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\base\movies.py", line 1654, in sbxreadskip
    fo.seek(k * nSamples, 0)
ValueError: negative seek position -2143092736

Process finished with exit code 1*

#---------------------
This is the case when trying to read a single channel file. Reading a dual channel file produces a different error, I should get into that once this is solved.

**Comment by epnev** [comment]
@agiovann @mheybpoosh You might have experience with this.

**Comment by epnev** [comment]
@bdudok How big is the file you're trying to read? I'm wondering whether it's worth sharing it

**Comment by bdudok** [comment]
> @bdudok How big is the file you're trying to read? I'm wondering whether it's worth sharing it

Typically they're 5-30 GB. I can crop one for sharing (<1GB). What would be the best way to share it?

**Comment by epnev** [comment]
Ideally the smallest file that reproduces the error. Looking at the error log
```
fo.seek(k * nSamples, 0)
ValueError: negative seek position -2143092736
```
I suspect the error might be due to some numerical overflow trying to index a very large file. 
Are small files read without any issues?

**Comment by bdudok** [comment]
Yes, this might be the case. a File of 999 frames did not reproduce the
error.

**Comment by epnev** [comment]
The file you sent appears to be 999 long and I can open it with no issues. Can you share one that has the problem?

**Comment by epnev** [comment]
actually 1000. I realized that our current reader drops one frame.

**Comment by epnev** [comment]
BTW I found an older 15GB large .sbx file and was able to read it without any issues.

**Comment by bdudok** [comment]
Mine was only 8 GB. It may be something about the .mat file too, the format might have changed since your old file was recorded. Anyways, If this is hard to reproduce I suggest we close the issue. Because of the  need for cropping, and probably splitting channels too, I think conversion will be necessary anyways. What format is the most recommended?

**Comment by epnev** [comment]
I don't mind trying it out if you can share it. If your file is not corrupted for any reason, I'd like to make sure that the reader can handle it. I think the reader also supports multiple channels although not sure how well this is tested.

For other formats I would suggest hdf5 files which are the fastest to load in caiman and splitting the multiple channels into separate files.

**Comment by bdudok** [comment]
OK, thanks. I'm uploading a 8 GB single and 16 GB dual channel file. The log I included in the post is from loading the single channel file. Below is the error when reading the dual channel file:

Traceback (most recent call last):
  File "C:/Users/bdudok/caiman_data/Barna_Batch/demo_pipeline_sbx.py", line 271, in <module>
    main()
  File "C:/Users/bdudok/caiman_data/Barna_Batch/demo_pipeline_sbx.py", line 129, in main
    mc.motion_correct(save_movie=True)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 234, in motion_correct
    self.motion_correct_pwrigid(template=template, save_movie=save_movie)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 336, in motion_correct_pwrigid
    self = self.motion_correct_rigid()
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 290, in motion_correct_rigid
    var_name_hdf5=self.var_name_hdf5)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\motion_correction.py", line 2272, in motion_correct_batch_rigid
    m = cm.load(fname, var_name_hdf5=var_name_hdf5, subindices=corrected_slicer)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\base\movies.py", line 1402, in load
    return movie(sbxreadskip(file_name[:-4], subindices), fr=fr).astype(outtype)
  File "C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman\lib\site-packages\caiman\base\movies.py", line 1663, in sbxreadskip
    x[:,:,:,0] = tmp
ValueError: could not broadcast input array from shape (2,796,512,1) into shape (796,512,2)

**Comment by epnev** [comment]
That error looks like a dimension misalignment. Shouldn't be too hard to fix.

**Comment by epnev** [comment]
are you by any chance on a 32bit machine or using a 32bit conda kernel? It's unlikely but thought I should ask

**Comment by bdudok** [comment]
I don't think so:
active environment : caiman
    active env location : C:\Users\bdudok\AppData\Local\conda\conda\envs\caiman
            shell level : 2
       user config file : C:\Users\bdudok\.condarc
 populated config files :
          conda version : 4.6.14
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\bdudok\.conda\pkgs
                          C:\Users\bdudok\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\bdudok\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\bdudok\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

**Comment by epnev** [comment]
I'm not sure what's going on...

For the single channel file I was able to read it and run the motion correction script without any issues.

For the dual channel I modified the code https://github.com/flatironinstitute/CaImAn/commit/c718a01013a29484474f0205797874e61df240f8 to deal with this error you reported that I was able to reproduce. After that, reading/motion correction ran without any issues. 

As a caveat, our sbx reader only keeps the first channel (presumably the functional) when reading multichannel files and drops the rest. This happens when specifying https://github.com/flatironinstitute/CaImAn/commit/c718a01013a29484474f0205797874e61df240f8#diff-c6ff97f7696c0eb1a249ee0ae8abfcaaR1667
```
x = x[0, :, :, :]
```
This presumably happens to bring the files in a uniform format for caiman to process, regardless of the filetype. If you just want to read the file, the code can modified easily to return all channels by commenting out this line. However for processing within the caiman pipeline we need to stick to that single channel format (it'll take a lot of work to do otherwise).

The modified reader is on the dev branch if you want to try it out.

**Comment by epnev** [comment]
The changes in the file are highlighted in these two commits: 
https://github.com/flatironinstitute/CaImAn/commit/22ec90cea646406b8ae8cffa736138e28e36d111 
https://github.com/flatironinstitute/CaImAn/commit/c718a01013a29484474f0205797874e61df240f8

**Comment by epnev** [comment]
the changes have now been pushed to the master branch.
