### ISSUE TITLE
Oasis not being installed during environment setup

### ISSUE THREAD

**Issue by tvajtay** [flatironinstitute/CaImAn#591]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**
Linux, 3.6.6, CLI, environment.yml

- **Describe the issue that you are experiencing**
Oasis does not seem to be installed after `conda env create -f environment.yml -n caiman`
which creates errors when trying to run `caimanmanager.py`

- **Copy error log below**
https://pastebin.com/QF3j0ZH1

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
After you install caiman, don't work out of the checkout dir anymore and you should be fine.

**Comment by epnev** [comment]
@tvajtay You also need to pip install after you create the environment (it's not clear whether you did that already). oasis is not a conda package that will appear in `conda list`.

**Comment by tvajtay** [comment]
I think this one is a PEBCAK, what I probably did was try to run `caimanmanager.py` without doing `pip install .` first.
