### ISSUE TITLE
Plotting Contours

### ISSUE THREAD

**Issue by maxseppo** [flatironinstitute/CaImAn#594]
I am running Python 3.6 in a Jupyter notebook, analyzing 2p data with a modified version of demo_pipeline.ipynb. I am struggling a bit with how to view spatial components after they have been saved. Based on previous issues and the Interpreting Results page, it should be something like:

f = h5py.File('location of the hdf5 files','r')
estimates = f['estimates']
estA = estimates['A']
np.reshape(estA.toarray(), dims, order='F'))
estA.plot_contours_nb(Cn= ?)

This is obviously incorrect - any help greatly appreciated!

**Comment by epnev** [comment]
@maxseppo 
The preferred method to load the cnmf object is by using the [`load_CNMF`](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/source_extraction/cnmf/cnmf.py#L953) function. 

```
cnm = load_CNMF(filename)
cnm.estimates.plot_contours_nb(img=Cn)
```

With what you have `estimates.plot_contours_nb(img=Cn)` might also work. The thing to note here is that `plot_contours_nb` is a method of the `estimates` object.

**Comment by maxseppo** [comment]
Thanks - That seems more straightforward. Leaving out the img=Cn arguments gives an image without background, which is useful, but is there a way to use the estimates.b as an argument for img? ie How do I avoid recalculating the correlation image?

**Comment by epnev** [comment]
@maxseppo 
You should be able to use
```
np.reshape(estimates.b.sum(1), dims, order='F')
```
as your background, but it might not contain the neurons (given that it is the background) and/or it might contain silent neurons. You can save the correlation image in the `cnmf` object prior to saving it and then use it when you reload the object.
