### ISSUE TITLE
Multi-channel video analysis and ROI identification/merging

### ISSUE THREAD

**Issue by tvajtay** [flatironinstitute/CaImAn#607]
- **If you're not reporting an error, type your message below**
Currently in our set up we are recording 2P data on a green channel, and have used a red channel for cell type identification. It would be useful to analyze both channels simultaneously to cross identify the ROI's in our case where the other channel is used for ID, or to use two different reporters.

I know there is the cross day merging script which could serve as the basis for this feature.

**Comment by epnev** [comment]
@tvajtay What type of simultaneous analysis would you like? We currently have a script that does the following:
- Uses the "red" channel for motion correction and applies the inferred shifts to the "green" channel.
- Segments the red channel and uses the ROIs to seed the CNMF algorithm. The script is [here](https://github.com/flatironinstitute/CaImAn/blob/master/use_cases/collaborations/ToliasLab/demo_seeding_nuclear.py) and we'll be turning it into a notebook with more comments and a shareable dataset.
Is that sufficient or do you have something else in mind?

**Comment by tvajtay** [comment]
@epnev this is more than sufficient for my current needs!

**Comment by antonykiran10** [comment]
> [@tvajtay](https://github.com/tvajtay) What type of simultaneous analysis would you like? We currently have a script that does the following:
> 
> * Uses the "red" channel for motion correction and applies the inferred shifts to the "green" channel.
> * Segments the red channel and uses the ROIs to seed the CNMF algorithm. The script is [here](https://github.com/flatironinstitute/CaImAn/blob/master/use_cases/collaborations/ToliasLab/demo_seeding_nuclear.py) and we'll be turning it into a notebook with more comments and a shareable dataset.
>   Is that sufficient or do you have something else in mind?

Can you share that script again? The previous link appears to be broken.
