### ISSUE TITLE
Distorted Image Outputs

### ISSUE THREAD

**Issue by donglabimaging** [flatironinstitute/CaImAn#609]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

Windows 10, Python 3.6.7, Jupyter Notebook/Anaconda environment, demo_pipeline_cnmfE

- **Describe the issue that you are experiencing**

We noticed that the image output from "cnm.estimates.plot_contours" did not look okay, and after running "cnm.estimates.nb_view_components" for the accepted components, we also saw that the figures on the left side representing the cell components were distorted, even though everything was working fine up to that point with no errors and the graphs on the right side look normal.

![10M_Day1_1_Fig 2](https://user-images.githubusercontent.com/50585879/62475071-40a1a180-b772-11e9-86d4-2e9109c26dd7.png)

![DistortedFigure](https://user-images.githubusercontent.com/50585879/62474878-e30d5500-b771-11e9-8ac3-6a625fd65ff5.PNG)

We suspect it may have something to do with file types, as the demo worked perfectly to the end with ".ome.tif" files, but we began seeing this issue after switching to avi video files.

If someone could help us solve this problem, we would greatly appreciate it. Thank you.

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
Looks like some dimension got flipped somewhere. I can take a look if you can share the file and the script that produces this error (in case you modified the notebook in any non-trivial way).

**Comment by donglabimaging** [comment]
Here is the avi video file that we tried:
https://we.tl/t-OSLd1M5XH5

We did not modify the notebook, but here is the script:
https://we.tl/t-4zDBjmWG8n

Thank you!

**Comment by epnev** [comment]
I think there is a dimensionality issue.
Can you try replacing: 
```images = Yr.T.reshape((T,) + dims, order='F')```
with
```images = Yr.T.reshape((T,) + dims[::-1], order='F')```
when loading the memory mapped file?
It seems to resolve some issues that appear there. 
It's confusing why this is happening. Does it happen in all your avi files?

**Comment by donglabimaging** [comment]
We followed your directions by replacing the line with your code, but we got a distorted image output after running `inspect_correlation_pnr(cn_filter, pnr)`:

![Distorted 1](https://user-images.githubusercontent.com/50585879/62550058-968c4d00-b837-11e9-9a68-0ad021e87515.png)

Also, we encountered an error while trying to run the CNMF-E algorithm:

![ValueError](https://user-images.githubusercontent.com/50585879/62550114-aefc6780-b837-11e9-8c30-d3773ee0ed7f.PNG)

Sadly, the issue happened with all the avi files that we have tried so far.

Thank you so much for helping us.

**Comment by epnev** [comment]
@donglabimaging 
I think the change highlighted here https://github.com/flatironinstitute/CaImAn/commit/7207d412cfde03bb5f2034f8c9f366546d4242f6
fixes the problem. I confirmed it on the notebook you sent me (without the changes I suggested earlier). Let us know if you have problems incorporating the changes. @pgunn 

btw, when computing the correlation and pnr images, you can always compute it on a subset of the data (e.g. `images[::5]` would compute it on a subset taken on every fifth frame as opposed to the whole dataset) to gain speed.

**Comment by donglabimaging** [comment]
Thank you for the tips on image[::5] it ran a lot faster.  The correlation and PNR figure looks great.  
![Caiman stuff 1](https://user-images.githubusercontent.com/50585879/62575526-e9322d00-b868-11e9-81bc-b1185386d7f9.png)

I will have to change the parameters to get the right accepted and rejected components.  The lower half of the image is cropped.
![Caiman stuff _2](https://user-images.githubusercontent.com/50585879/62575610-17177180-b869-11e9-9ef6-3004c281c6ff.png)

Unfortunately, the last image is still distorted.
![bokeh_plot (3)](https://user-images.githubusercontent.com/50585879/62575746-72496400-b869-11e9-8707-16d6dc67c38f.png)

**Comment by epnev** [comment]
what is the value of `opts.data['dims']`?

**Comment by donglabimaging** [comment]
It is [752, 480]

**Comment by epnev** [comment]
@donglabimaging this means that the change I mentioned above has not been incorporated to your distribution of caiman and you will need to update it. It should show [480, 752].

**Comment by donglabimaging** [comment]
Thank you for pointing that out.  I am not sure how to make sure that it is incorporated.  I have made the changes according to your suggestions in the utilities.py file.  
![dis](https://user-images.githubusercontent.com/50585879/62584175-62d61500-b881-11e9-9c6c-efcb965c0035.PNG)

I closed the notebook and ran it again, but it is showing the same results.  Any suggestions would be great appreciated.  Thank you!

**Comment by epnev** [comment]
Open a terminal/command prompt, enter the CaImAn directory and activate the caiman environment.
Then type
```
pip uninstall caiman
pip install .
```
Then launch jupyter again. It should work.

**Comment by donglabimaging** [comment]
It worked! Thank you so much.

However, when I run `# rejected components
cnm.estimates.nb_view_components(img=cn_filter, idx=cnm.estimates.idx_components_bad,
                                denoised_color='red', cmap='gray')`

I get the error  ValueError: Slider 'start' and 'end' cannot be equal. 
![components](https://user-images.githubusercontent.com/50585879/62656056-60cb8f00-b931-11e9-8b70-3ca4bf70e58d.png)

Accepted components
![bokeh_plot (4)](https://user-images.githubusercontent.com/50585879/62656059-62955280-b931-11e9-97f7-fad22238d10b.png)

**Comment by epnev** [comment]
cool, glad it worked. The error you get is most likely because there is only one component to be shown so the slider breaks down because there is nothing to slide over. 

In general, the reason the correlation and PNR images are shown is to inspect them, see what value you get at the positions where neurons are and set the thresholds accordingly. The default values seem very high for your case so I would lower them to get more components.

**Comment by donglabimaging** [comment]
I will change the corr and pnr values accordingly.  Thanks again for all the help.  I really appreciate it.
