### ISSUE TITLE
'mmapping: Actual position does not match computed position' for multiple tiff files

### ISSUE THREAD

**Issue by njone97** [flatironinstitute/CaImAn#616]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

Windows 10, python 3.7, anaconda prompt
demo_pipeline.py 

- **Describe the issue that you are experiencing**

I'm trying to run the demo pipeline, and I feed a list of my tiffs as the variable 'fnames'. Ideally, I would be able to provide the entire list of tiffs from 30 mins straight 2p recording from relatively unchanging FOV. Normally, I have 69 tiffs each about 400MB, but this gives me a memory error when I feed all tiffs, so I tried feeding only one of my tiff files and it worked! So next, I tried feeding 5 tiffs, and it didn't work, and gave the error below. I reduced to feeding a list of even just 2 tiffs, and still got the below error. I even tried to concatenate the files beforehand and feed as an individual large tiff, but it didn't recognise the file type. I'm quite new to python, so I may have concatenated improperly but I'm not sure. 

If it makes a difference, I did change the initialisation methods to 'sparse_nmf' and the only other things I've altered are the parameters, to match 'demo_caiman_basic_dendrites.py', as I'm trying to analyse dendrite activity. 

- **Copy error log below**
C:\Users\njone079\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py:283: RuntimeWarning: overflow encountered in long_scalars
  computed_position = np.uint64(idx_end * Yr_tot.dtype.itemsize * tot_frames)
      990869 [mmapping.py:        save_portion():285][14904] Error in mmap portion write: at position 5872025600
      990870 [mmapping.py:        save_portion():286][14904] But should be at position 262144 * 4 * 5600 = 1577058304
Traceback (most recent call last):
  File "\Users\njone079\caiman\demos\general\demo_pipeline.py", line 275, in <module>
    main()
  File "\Users\njone079\caiman\demos\general\demo_pipeline.py", line 152, in main
    border_to_0=border_to_0)  # exclude borders
  File "C:\Users\njone079\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py", line 400, in save_memmap
    fname_new = cm.save_memmap_join(fname_parts, base_name=base_name, dview=dview, n_chunks=n_chunks)
  File "C:\Users\njone079\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py", line 209, in save_memmap_join
    list(map(save_portion, pars))
  File "C:\Users\njone079\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py", line 288, in save_portion
    raise Exception('Internal error in mmapping: Actual position does not match computed position')
Exception: Internal error in mmapping: Actual position does not match computed position

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@njone97 

Can you run your script again using either an editor or a jupyter notebook? I would like to see exactly where the error occurred. Also make sure that all your tiff files that are listed in the `fnames` variable must have exactly the same dimensions in terms of FOV (number of frames can be different). Using 2 files is good for a start.

Also bear in mind that we now have a specific notebook for dendritic data (demo_dendritic.ipynb) that you can try out once you resolve this issue (for your case you should use patches). But keep in mind that loading your data in memory and displaying it can cause memory problems, the actual processing is memory efficient.

**Comment by njone97** [comment]
Ok! I'll make sure to check it out. Below is the error log from when I run in jupyter notebook. 

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-61d5d3a9f4ed> in <module>
    273 # versus from the CLI
    274 if __name__ == "__main__":
--> 275     main()
    276 

<ipython-input-1-61d5d3a9f4ed> in main()
    150     # memory map the file in order 'C'
    151     fname_new = cm.save_memmap(mc.mmap_file, base_name='memmap_', order='C',
--> 152                                border_to_0=border_to_0)  # exclude borders
    153 
    154     # now load the file

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py in save_memmap(filenames, base_name, resize_fact, remove_init, idx_xy, order, xy_shifts, is_3D, add_to_movie, border_to_0, dview, n_chunks, slices)
    398 
    399 
--> 400         fname_new = cm.save_memmap_join(fname_parts, base_name=base_name, dview=dview, n_chunks=n_chunks)
    401 
    402     else:

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py in save_memmap_join(mmap_fnames, base_name, n_chunks, dview, add_to_mov)
    207 
    208     else:
--> 209         list(map(save_portion, pars))
    210 
    211     np.savez(base_name + '.npz', mmap_fnames=mmap_fnames, fname_tot=fname_tot)

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py in save_portion(pars)
    286                     logging.critical(f"But should be at position {idx_end} * {Yr_tot.dtype.itemsize} * {tot_frames} = {computed_position}")
    287                     f.close()
--> 288                     raise Exception('Internal error in mmapping: Actual position does not match computed position')
    289 
    290     del Yr_tot

Exception: Internal error in mmapping: Actual position does not match computed position

**Comment by pgunn** [comment]
Hi,
When you run this you should see a version of that logging.critical() message with the numbers still in (or you may need to adjust your logging settings if you don't). Can you paste that info in here?

**Comment by njone97** [comment]
Right above the initial 'Exception Traceback' line it says: 

computed_position = np.uint64(idx_end * Yr_tot.dtype.itemsize * tot_frames)
      398641 [mmapping.py:        save_portion():285][17684] Error in mmap portion write: at position 2516582400
      398642 [mmapping.py:        save_portion():286][17684] But should be at position 262144 * 4 * 2400 = 18446744071931166720

Is this what you're referring to? If not, could you point me to where/how I should adjust the logging settings?

**Comment by pgunn** [comment]
This is exactly what I wanted. I'm looking further into this now.

**Comment by pgunn** [comment]
Do you mind bringing up an interactive python terminal and running the following code?:

```
import numpy as np
np.uint64(262144 * 4 * 2400)
````

**Comment by pgunn** [comment]
We think we know how this happened and how to fix it. We'll update this ticket shortly - no need for further action from you.

**Comment by epnev** [comment]
@njone97 It should be fixed with the changes shown here: https://github.com/flatironinstitute/CaImAn/commit/892eec955cc375742afafe3731a46eca313951b5
You will need to update caiman for the changes to take effect. We have some instructions [here](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

**Comment by epnev** [comment]
@njone97 let us know if the issue was resolved.

**Comment by njone97** [comment]
Hi guys, sorry for the delay. I had some issues with updating. It's taken care of now, and I've tried feeding up to 5 tiffs at a time and the code seems to work for me. Thanks!

**Comment by epnev** [comment]
great, thanks for the update.
