### ISSUE TITLE
Question about min_SNR

### ISSUE THREAD

**Issue by donglabimaging** [flatironinstitute/CaImAn#620]
We are trying to figure out how to improve component evaluation by changing min_SNR. We would like to know how SNR is calculated for each component to evaluate whether to place it in the accepted group or the rejected group using the threshold we provide. We observed that lowering the value of the parameter will shift some components from the rejected group to the accepted group, but we felt that sometimes some obviously bad ones become included while better ones stay in the rejected group.

Thank you.

**Comment by epnev** [comment]
@donglabimaging The details are in our paper but the test looks for traces that are above a SNR threshold for the duration of a typical transient. What components get accepted depends also on the other tests and not just the threshold. 

In general a component is accepted if `(r_val > rval_thr OR SNR > min_SNR) AND r_val > rval_lowest AND SNR > SNR_lowest`. Similar if you also include the CNN criterion

**Comment by donglabimaging** [comment]
Thank you!
