### ISSUE TITLE
Use standard "install_requires" to list core dependencies

### ISSUE THREAD

**Issue by yarikoptic** [flatironinstitute/CaImAn#623]
ATM `install_requires` in setup.py is just an empty list.  That complicates installation without going the "conda" way using `environment.yml`.  
Originally there was a list of requirements specified but it was trimmed in b8a41dfb04fe3915900b71c00d4228bc979cd60d in attempt to fix "autoinstallation".
IMHO `install_requires` should be the one to specify minimal versions of external dependencies. setup.py could even parse and compile those from `environment.yml` to centralize specification.

**Comment by epnev** [comment]
@pgunn ^^^^

**Comment by pgunn** [comment]
Hello,
We don't support installing CaImAn except into an environment set up with conda. Those files are remaining bits from an earlier way we used to do installs, and probably should be cleaned out to avoid confusion.

**Comment by yarikoptic** [comment]
I would advise to reconsider lock-in to conda since some users/deployments might not have conda, and rather use standard python deployment/distribution (pip, virtualenv, venv, etc) and/or package for other GNU/Linux distributions (e.g. see freshly filed http://bugs.debian.org/934621 in Debian).  But of cause -- it is up to you how friendly you decide to be to the users/contributors.  It was just a recommendation.
Cheers

**Comment by epnev** [comment]
@yarikoptic Thanks for the suggestion. We have a lot of users with minimal experience to programming, let alone python. We believe conda to be the most accessible way to distribute the software and we'll stick to that for the time being. We might add pip in the future as the code reaches a more stable and mature state. I know users who have done this already with caiman, see e.g. #510
