### ISSUE TITLE
MacOS High Sierra installation Issue 10.13.1

### ISSUE THREAD

**Issue by alimoges42** [flatironinstitute/CaImAn#625]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

MacOS High Sierra 10.13.1

- **Describe the issue that you are experiencing**

Hi all, hope all is well. I'm trying to do a fresh install on a desktop, but getting an error during the `pip install .` command. I saw that there are related issues for Mojave and tried those fixes, but they haven't worked on my machine, i.e. the suggestion to run the `xcode-select --install` doesn't work for me, so not sure if my install problem is related to that xcode problem or if it's a different issue altogether. Any help is appreciated. Thanks!

- **Copy error log below**

Building wheels for collected packages: caiman
  Building wheel for caiman (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/chris/anaconda/envs/caiman/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-req-build-va1ulvr2/setup.py'"'"'; __file__='"'"'/private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-req-build-va1ulvr2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-wheel-g_7lntp8 --python-tag cp36
       cwd: /private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-req-build-va1ulvr2/
  Complete output (91 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/paths.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/components_evaluation.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/summary_images.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/motion_correction.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/mmapping.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  copying caiman/cluster.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
  copying caiman/behavior/behavior.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
  copying caiman/behavior/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_pre_processing.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_onacid.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_temporal.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_spatial.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_deconvolution.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_import.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_tensorflow.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/comparison_humans.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/comparison_general.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_toydata.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/test_demo.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  copying caiman/tests/comparison_humans_online.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/labelling.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/visualization.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/utils.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/stats.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/image_preprocessing_keras.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  copying caiman/utils/unused.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/gui
  copying caiman/gui/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
  copying caiman/gui/gui_pyqtgraph_layout.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
  copying caiman/gui/caiman_gui.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/external
  copying caiman/external/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external
  copying caiman/external/cell_magic_wand.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction
  copying caiman/source_extraction/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/rois.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/movies.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/traces.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  copying caiman/base/timeseries.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/regen_main_gt.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/comparison.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/create_gt.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/demo_VST.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/regions.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/plotting.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/estimation.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/measures.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/stats.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/gat.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
  creating build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/params.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/temporal.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/estimates.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/deconvolution.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/spatial.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/cnmf.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/initialization.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/cnmf_optional_outputs.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/map_reduce.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/utilities.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/pre_processing.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/merging.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/online_cnmf.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  running build_ext
  building 'caiman.source_extraction.cnmf.oasis' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/caiman
  creating build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction
  creating build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/chris/anaconda/envs/caiman/include -arch x86_64 -I/Users/chris/anaconda/envs/caiman/include -arch x86_64 -I/Users/chris/anaconda/envs/caiman/lib/python3.6/site-packages/numpy/core/include -I/Users/chris/anaconda/envs/caiman/include/python3.6m -c caiman/source_extraction/cnmf/oasis.cpp -o build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf/oasis.o -stdlib=libc++
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ERROR: Failed building wheel for caiman
  Running setup.py clean for caiman
Failed to build caiman
Installing collected packages: caiman
  Running setup.py install for caiman ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/chris/anaconda/envs/caiman/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-req-build-va1ulvr2/setup.py'"'"'; __file__='"'"'/private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-req-build-va1ulvr2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-record-3wsrkeuj/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-req-build-va1ulvr2/
    Complete output (91 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/paths.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/components_evaluation.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/summary_images.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/motion_correction.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/mmapping.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    copying caiman/cluster.py -> build/lib.macosx-10.7-x86_64-3.6/caiman
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
    copying caiman/behavior/behavior.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
    copying caiman/behavior/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/behavior
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_pre_processing.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_onacid.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_temporal.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_spatial.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_deconvolution.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_import.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_tensorflow.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/comparison_humans.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/comparison_general.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_toydata.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/test_demo.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    copying caiman/tests/comparison_humans_online.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/labelling.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/visualization.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/utils.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/stats.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/image_preprocessing_keras.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    copying caiman/utils/unused.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/utils
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/gui
    copying caiman/gui/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
    copying caiman/gui/gui_pyqtgraph_layout.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
    copying caiman/gui/caiman_gui.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/gui
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/external
    copying caiman/external/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external
    copying caiman/external/cell_magic_wand.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction
    copying caiman/source_extraction/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/rois.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/movies.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/traces.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    copying caiman/base/timeseries.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/base
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/regen_main_gt.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/comparison.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/create_gt.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/tests/comparison
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/demo_VST.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/regions.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/plotting.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/estimation.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/measures.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/stats.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/gat.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/external/houghvst
    creating build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/params.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/temporal.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/estimates.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/deconvolution.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/spatial.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/cnmf.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/initialization.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/cnmf_optional_outputs.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/map_reduce.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/utilities.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/pre_processing.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/merging.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/online_cnmf.py -> build/lib.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    running build_ext
    building 'caiman.source_extraction.cnmf.oasis' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/caiman
    creating build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction
    creating build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/chris/anaconda/envs/caiman/include -arch x86_64 -I/Users/chris/anaconda/envs/caiman/include -arch x86_64 -I/Users/chris/anaconda/envs/caiman/lib/python3.6/site-packages/numpy/core/include -I/Users/chris/anaconda/envs/caiman/include/python3.6m -c caiman/source_extraction/cnmf/oasis.cpp -o build/temp.macosx-10.7-x86_64-3.6/caiman/source_extraction/cnmf/oasis.o -stdlib=libc++
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/chris/anaconda/envs/caiman/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-req-build-va1ulvr2/setup.py'"'"'; __file__='"'"'/private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-req-build-va1ulvr2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/9b/m5ykcqk154l5x6pybp7yzmg40000gn/T/pip-record-3wsrkeuj/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by pgunn** [comment]
Hello,
This can happen if the xcode installation is incomplete or becomes inconsistent with the OS version. You should be able to fix this by doing `xcode-select --install`

Cheers,
Pat

**Comment by alimoges42** [comment]
Hi Pat, 

I had tried that suggestion but get am having a problem trying to install through the pop up window after typing the command. I am guessing it may be an inconsistency with the OS version, because the App Store says "Xcode can’t be installed because macOS version 10.14.3 or later is required". Any ideas for this? 

Thanks,
Aaron

**Comment by pgunn** [comment]
Can you give the instructions here a go?

https://www.ics.uci.edu/~pattis/common/handouts/macmingweclipse/allexperimental/macxcodecommandlinetools.html

**Comment by alimoges42** [comment]
It turned out to be an incompatibility with the current OS version - I updated overnight and was able to complete the caiman install. Thanks for the help though!

Best,
Aaron
