### ISSUE TITLE
Failure to load cnn_model_online.h5.pb file in cnn_model_online

### ISSUE THREAD

**Issue by Rylan-L** [flatironinstitute/CaImAn#629]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

Windows, Python version 3.6. I have tested this in both Juypter notebook and Spyder as a standalone .py script.

- **Describe the issue that you are experiencing**
I've been testing the conda forge distribution of caiman recently (which may be unrelated to this issue), but I'm encountering an issue  when running cnmf_online (which is also new to me). 

In particular, in running the code I get "NewRandomAccessFile failed to Create/Open: C:\Users\rylanl\caiman_data\model\cnn_model_online.h5.pb : The system cannot find the path specified." .  This appears related to loading a tensorflow model.

Two issues seem to potentially causing this. 

First, in windows, Caiman seems to be installing cnn_model_online.h5 in the path "C:\Users\rylanl\CaImAn\model\", **_not_** "C:\Users\rylanl\caiman_data\". Therefore the default path specified for the 'path_to_model' may not be correct on some Windows systems. I have no caiman_data folder.

Secondly, I have tried replacing the default path parameter for this model (the path_to_model key in params) with the correct path: C:\Users\rylanl\CaImAn\model\cnn_model_online.h5. However, I still get an error because Caiman seems to be appending a ".pb" to that path where no .pb file exists. 

Should I have the .pb file? or should the `model_path = '.'.join(path + ['h5', 'pb'])` line in online_cnmf.py be changed?

- **Copy error log below**

NotFoundError                             Traceback (most recent call last)
<ipython-input-6-e6482fec5709> in <module>
----> 1 segs.caiman_segment(save_fname='caiman_segmentation_results.hdf5')

<ipython-input-3-cc1ea57de79a> in caiman_segment(self, save_fname)
    127 
    128         cnm = cnmf.online_cnmf.OnACID(params=opts)
--> 129         cnm.fit_online()
    130 
    131         roi_num = cnm.estimates.A.shape[1]

C:\Anaconda2\envs\axon_seg\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in fit_online(self, **kwargs)
    717         init_batch = self.params.get('online', 'init_batch')
    718         epochs = self.params.get('online', 'epochs')
--> 719         self.initialize_online()
    720         extra_files = len(fls) - 1
    721         init_files = 1

C:\Anaconda2\envs\axon_seg\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in initialize_online(self)
    663         self.params.set('data', {'dims': dims})
    664         T1 = np.array(Ts).sum()*self.params.get('online', 'epochs')
--> 665         self._prepare_object(Yr, T1)
    666         if opts['show_movie']:
    667             self.bnd_AC = np.percentile(self.estimates.A.dot(self.estimates.C),

C:\Anaconda2\envs\axon_seg\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in _prepare_object(self, Yr, T, new_dims, idx_components)
    247                 path = self.params.get('online', 'path_to_model').split(".")[:-1]
    248                 model_path = '.'.join(path + ['h5', 'pb'])
--> 249                 loaded_model = load_graph(model_path)
    250                 self.tf_in = loaded_model.get_tensor_by_name('prefix/conv2d_1_input:0')
    251                 self.tf_out = loaded_model.get_tensor_by_name('prefix/output_node0:0')

C:\Anaconda2\envs\axon_seg\lib\site-packages\caiman\utils\utils.py in load_graph(frozen_graph_filename)
    506     with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
    507         graph_def = tf.GraphDef()
--> 508         graph_def.ParseFromString(f.read())
    509 
    510     # Then, we can use again a convenient built-in function to import a

C:\Anaconda2\envs\axon_seg\lib\site-packages\tensorflow\python\lib\io\file_io.py in read(self, n)
    116       string if in string (regular) mode.
    117     """
--> 118     self._preread_check()
    119     with errors.raise_exception_on_not_ok_status() as status:
    120       if n == -1:

C:\Anaconda2\envs\axon_seg\lib\site-packages\tensorflow\python\lib\io\file_io.py in _preread_check(self)
     76       with errors.raise_exception_on_not_ok_status() as status:
     77         self._read_buf = pywrap_tensorflow.CreateBufferedInputStream(
---> 78             compat.as_bytes(self.__name), 1024 * 512, status)
     79 
     80   def _prewrite_check(self):

C:\Anaconda2\envs\axon_seg\lib\contextlib.py in __exit__(self, type, value, traceback)
     86         if type is None:
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:
     90                 return False

C:\Anaconda2\envs\axon_seg\lib\site-packages\tensorflow\python\framework\errors_impl.py in raise_exception_on_not_ok_status()
    464           None, None,
    465           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 466           pywrap_tensorflow.TF_GetCode(status))
    467   finally:
    468     pywrap_tensorflow.TF_DeleteStatus(status)

NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\rylanl\CaImAn\model\cnn_model_online.h5.pb : The system cannot find the file specified.

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@Rylan-L Is this with the conda installer?

**Comment by Rylan-L** [comment]
@epnev Yes, this is after installing Caiman with: 
conda create -n myenvname -c conda-forge python=3.6 caiman

**Comment by pgunn** [comment]
Hi,
If you're using the conda-based installer, you should be able to either remove your checkout of the sources, or move them somewhere else. I recommend doing so, so python will know to load the caiman library from the pythonpath rather than from some local directory.

**Comment by epnev** [comment]
It appears that you have a git repo from an earlier version and the installer. This can lead to path conflicts if a) you're on windows and b) you install caiman right in your user directory which both seem to be the case. I'd say move the CaImAn folder somewhere else, rename you caiman_data folder to back it up and then try to install the caimanmanager again

**Comment by Rylan-L** [comment]
@pgunn @epnev Just to clarify the solution here, the answer is to move my C:\Users\rylanl\CaImAn\ folder to another location and then run `python caimanmanager.py install --inplace `?

**Comment by epnev** [comment]
without the `--inplace``.

**Comment by pgunn** [comment]
Almost but not quite. Move that folder elsewhere, and then run that second command, but without the --inplace flag.

**Comment by Rylan-L** [comment]
Following those instructions and moving the directory produces a different error upon running caimanmanager.py install

`(axon_seg) D:\Code\CaImAn>python caimanmanager.py install
Traceback (most recent call last):
  File "caimanmanager.py", line 13, in <module>
    from caiman.paths import caiman_datadir
  File "D:\Code\CaImAn\caiman\__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "D:\Code\CaImAn\caiman\base\movies.py", line 68, in <module>
    from ..utils import visualization
  File "D:\Code\CaImAn\caiman\utils\visualization.py", line 45, in <module>
    from ..summary_images import local_correlations
  File "D:\Code\CaImAn\caiman\summary_images.py", line 27, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
  File "D:\Code\CaImAn\caiman\source_extraction\cnmf\__init__.py", line 4, in <module>
    from . import cnmf
  File "D:\Code\CaImAn\caiman\source_extraction\cnmf\cnmf.py", line 40, in <module>
    from .oasis import OASIS
ModuleNotFoundError: No module named 'caiman.source_extraction.cnmf.oasis'`

**Comment by epnev** [comment]
Hmm, it seems it still reads caiman from the old distribution. Just rename that CaImAn directory and try again. If even that doesn't work, try removing it.

**Comment by pgunn** [comment]
Hello,
Please move caimanmanager to D:\Code
And then rename D:\Code\CaImAn to something else. After that, the install should work.

**Comment by Rylan-L** [comment]
Appears to be resolved after doing that. Thanks for your help! Closing issue
