### ISSUE TITLE
Loading movies from mmap.

### ISSUE THREAD

**Issue by scottcanoe** [flatironinstitute/CaImAn#631]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by scottcanoe** [comment]
Can you point me toward/create/document a function to load movies from mmap'ed files as if they're in their original form (let's say axes are 't', 'y', 'x'). I'm not positive how to reshape the data after it's been stored flat.

**Comment by epnev** [comment]
@scottcanoe The memory mapped file stores a 2D matrix with dimensions # pixels X # frames. The different spatial dimensions (x, y, and z if present) are unfolded in `F` format. So to get a 3D movie in (t, x, y) format, you first load the data, transpose it and then reshape it by keeping the `F` order. Also, the names of the memory mapped files caiman produces contain information about the dimension so they can be extracted from there. 

demo_pipeline.py shows an example of loading and reshaping the data:
```
    Yr, dims, T = cm.load_memmap(fname_new)
    images = np.reshape(Yr.T, [T] + list(dims), order='F')
```
Let me know if that answers your question.

**Comment by scottcanoe** [comment]
@epnev Great, thanks! Somehow missed it in demo_pipeline.
