### ISSUE TITLE
NMF Produces Error when using Sparse NMF in cnmf.CNMF fit

### ISSUE THREAD

**Issue by Rylan-L** [flatironinstitute/CaImAn#633]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

Windows, Python 3.6. Currently experiencing in Juypter notebook

- **Describe the issue that you are experiencing**
Using setting similar to what I've used before and which worked for Caiman version 1.0, I now receive an error from originating from Skilearn initialization of NMF using the 'nndsvdar'. This is for sparse_nmf (dendrite/process segmentation).

'nndsvdar' can only be used when n_components <= min(n_samples, n_features)

The params I'm attempting to use are:
    p = 2                       # order of the autoregressive system
    gnb = 2                     # number of global background components
    merge_thr = 0.6            # merging threshold, max correlation allowed
    rf =  256                  # half-size of the patches in pixels. e.g., if rf=25, patches are 50x50
    stride_cnmf = 20          # amount of overlap between the patches in pixels
    K = 100                   # number of components per patch
    method_init = 'sparse_nmf'   # initialization method 
    ssub = 1                 # spatial subsampling during initialization
    tsub = 1                   # temporal subsampling during intialization
    alpha_snmf=10e1
    gSig = [5, 5]
    border_pix=20
    do_merge=True
    SNR_lowest = 0.10
    n_processes=3
    method_deconvolution='oasis'

Do I need to change my parameters somehow?

- **Copy error log below**

<ipython-input-2-ae69c69e2c5e> in caiman_CNMF_segment(self, load_if_exists)
    159 
    160         cnm = cnmf.CNMF(4,params=opts)
--> 161         cnm=cnm.fit(images)
    162 
    163         roi_num = cnm.estimates.A.shape[1]

C:\Anaconda2\envs\axon_seg\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
    564                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    565                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 566                     indices=indices)
    567 
    568             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

C:\Anaconda2\envs\axon_seg\lib\site-packages\caiman\source_extraction\cnmf\map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    432         nan_components = np.any(np.isnan(F_tot), axis=1)
    433         F_tot = F_tot[~nan_components, :]
--> 434         _ = mdl.fit_transform(F_tot).T
    435         Bm = Bm[:, ~nan_components]
    436         f = mdl.components_.squeeze()

C:\Anaconda2\envs\axon_seg\lib\site-packages\sklearn\decomposition\nmf.py in fit_transform(self, X, y, W, H)
   1270             l1_ratio=self.l1_ratio, regularization='both',
   1271             random_state=self.random_state, verbose=self.verbose,
-> 1272             shuffle=self.shuffle)
   1273 
   1274         self.reconstruction_err_ = _beta_divergence(X, W, H, self.beta_loss,

C:\Anaconda2\envs\axon_seg\lib\site-packages\sklearn\decomposition\nmf.py in non_negative_factorization(X, W, H, n_components, init, update_H, solver, beta_loss, tol, max_iter, alpha, l1_ratio, regularization, random_state, verbose, shuffle)
   1043     else:
   1044         W, H = _initialize_nmf(X, n_components, init=init,
-> 1045                                random_state=random_state)
   1046 
   1047     l1_reg_W, l1_reg_H, l2_reg_W, l2_reg_H = _compute_regularization(

C:\Anaconda2\envs\axon_seg\lib\site-packages\sklearn\decomposition\nmf.py in _initialize_nmf(X, n_components, init, eps, random_state)
    310         raise ValueError("init = '{}' can only be used when "
    311                          "n_components <= min(n_samples, n_features)"
--> 312                          .format(init))
    313 
    314     if init is None:

ValueError: init = 'nndsvdar' can only be used when n_components <= min(n_samples, n_features)

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@Rylan-L What are the dimensions of the dataset you're analyzing?

**Comment by Rylan-L** [comment]
@epnev (7012, 512, 451). I have also tried adding black pixels to one of the dimensions to make it (7012, 512, 512), but I still get the same error.

**Comment by epnev** [comment]
@Rylan-L The error occurs if the number of components that you're searching `K` is larger than one of the dimensions of your matrix. See [here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/decomposition/nmf.py#L307) for example.

In your case you set `rf = 256` for a FOV which is `512 x 451`.  If you want to run without any patches then you should just set `rf = None` and repeat. What you're doing might result in some weird behavior and the creation of a small patch. 

As a side note, I wouldn't recommend running such a big dataset without patches just for memory issues, but if that works for you, then it's fine.

**Comment by Rylan-L** [comment]
I see, so the number of total components = K * rf, and I need to keep that below my frame number (7012 in this case)? I would prefer to run this with patches, so I'm inclined to reduce rf and the number of components per patch and re-run.

**Comment by epnev** [comment]
As written in the code you pasted the dimension of each patch is `2*rf`. So 2*256 = 512 which is equal to your whole FOV, so it does not make sense to use this value. If you want to use patch try something like `rf=100`. 

K is the number of components per patch. You may want to decrease that a bit as well, since it will search for K components in each patch (not overall).

**Comment by Rylan-L** [comment]
Setting rf=100 fixed my issues and it ran fine. I'm not sure how often users will experience this type of error, but raising a descriptive error message might help future users troubleshoot (just a thought though!). Thanks
