### ISSUE TITLE
Combining Multiple Analyses Performed on Different Parts of the Same Data

### ISSUE THREAD

**Issue by donglabimaging** [flatironinstitute/CaImAn#637]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 
 2. Python version (3.x): 
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

We originally had our data stored as single video files (one for each trial). However, the analysis on CaImAn took way too long was inefficient because of the large file size, so we decided to divide each video file into two parts and perform analysis on each independently. This saved us time, but now we are facing the issue of merging the two independently-conducted analyses together; as you may be able to imagine, the outcome, especially the detected/accepted components, can differ between the two analyses even though they are technically part of the same trial. So we were wondering if there was a way to somehow merge the analyses together, or if there are things we can do to increase the efficiency of the CaImAn analysis so that we do not have to split the video files.

Thank you!

**Comment by epnev** [comment]
You can try using the [`register_ROIs`](https://caiman.readthedocs.io/en/master/core_functions.html?highlight=register_ROIs#caiman.base.rois.register_ROIs) method for matching the components across different days. I would keep the components that are accepted in at least one of the sessions and discard only those that are rejected for both.

However, I would first recommend using spatial/temporal downsampling. From what I remember you work with a large FOV and the neurons are also large (in terms of pixels). Doing the analysis using e.g. `ssub=2` or `ssub=4` will give you substantial gains in terms of speed or memory and most likely will not affect the results. If you're doing one photon analysis then you might also want to set `ssub_B=2`.

Let me know if that helps.

**Comment by donglabimaging** [comment]
Thank you for the suggestions.  We have been trying to get the `register_ROIs` to work with some success.  

We are indeed doing one photon analysis and would like to use ssub_B=2, but we got a Memory Error at the motion correct step.   Therefore, we tried to downsample the videos before the analysis with the suggested code `movies_chained.resize(1, 1, .5)`, but we are not sure what `resize(1, 1, 0.5)` does.  We noticed that the frame number of the downsampled videos are not exactly half of the original ones, so we are having a hard time matching the timestamps to the corresponding frames.  Could you give us some insight into what resize(1, 1, 0.5) does?  Thank you.

**Comment by epnev** [comment]
@donglabimaging `resize(1, 1, 0.5)` will downsample the movie across time by a factor of 2. What do you mean when you say "We noticed that the frame number of the downsampled videos are not exactly half of the original ones"?

Also note, that to run the motion correction (and the entire pipeline) you do not need to load all the files in memory. By just passing a list of all the files you want to correct, the algorithm will correct them one by one and if each file is not too large, there will not be any memory issues.

**Comment by donglabimaging** [comment]
@epnev We first concatenate the files into one single file that contains for example 20000 frames (collected at 30fps).  The output of the `resize(1, 1, 0.5)` was 10030 instead of exactly 100000.  Since each of the 20000 frames has a timestamp associated with it, it made it difficult to match the extra 30 frames to the timestamp. 

I will definitely try to load all the files in memory prior to downsample the videos at the CNMF step with the suggested `ssub_B=2` .  I hope this solves the issue.  Thank you!

**Comment by epnev** [comment]
@donglabimaging I find this hard to believe. For example if you type:
``` 
import caiman as cm
from caiman.paths import caiman_datadir
import os

fnames = [os.path.join(caiman_datadir(), 'example_movies', 'demoMovie.tif')]
m = cm.load(fnames*10)

print(m.shape)
(20000, 60, 80)

print(m.resize(1, 1, 0.5).shape)
(10000, 60, 80)
```
you see that the 20000 frames original movie, has 10000 frames after resizing.

**Comment by epnev** [comment]
@donglabimaging I'm closing the issue but feel free to reopen it if you're encountering more issues.

**Comment by donglabimaging** [comment]
Hi @epnev,

Thank you for always giving us feedback and advice on how to run CaImAn and for being patient with us. We really appreciate all the help you have been giving us so far.

Unfortunately, we are still dealing with the resizing issue. We have tried it with multiple videos, and the resulting frame number is always slightly off. Here is an example:

![image](https://user-images.githubusercontent.com/50585879/66675592-9b082400-ec33-11e9-8ff2-a6534b5dd159.png)

Also, we were wondering if you'd be able to provide us with some insight into the method of analysis we should employ. You mentioned about passing multiple input files as a list in your comment ([https://github.com/flatironinstitute/CaImAn/issues/637#issuecomment-534116683](url)), so we tried passing 27 avi video segments of our 2-hr trial video to the algorithm to see if this method may be able to save us from having to concatenate video segments into one whole video for every trial. The entire process ran smoothly, however, the result was subpar in the sense that the number of total components was 1 and it was rejected. This could be due to some other issues, like parameter settings, but we're starting to question if this is the method best suited for our purposes. What exactly is happening when we pass multiple video files---is the algorithm analyzing each one separately, and if so, how is it making them come together at the end? We have noted that others have used this method to analyze videos from different trials at once, but our inputs are all part of the same trial, and we were wondering if the algorithm is able to recognize that they have a temporal order. And finally, how is this method different from ROIs?

We apologize for our inexperience and lack of knowledge and thank you, again, for all your help!

**Comment by epnev** [comment]
I think I know what's happening with respect to the resizing. The discrepancy during the resizing happens because your movie has more than `2^31` entries (it has 752*480*26984). It's an old opencv bug that appears to have been fixed but we have not updated our codes to reflect that. For your case I believe that you lose one frame every 5949 frames during the resizing. The number 5949 comes from the division `2**31/(752*480)`. The file is being truncated in chunks of 5949 frames and because 5949 is odd everytime you resize in time by a factor of 2 you lose a frame.You could argue that the frames lost are roughly 5949, 5949*2, 5949*3 and 5949*4. I'll fix the code to better handle this case.

As for your other question, are you saying that concatenating the data into a single movie and passing that work well, whereas passing all the smaller files at once does not?

In general, I would try to optimize the results for a single file or two, before proceeding to put all the files at once. The files will be processed in alphanumerical order, and if they all correspond to the same FOV, then it should be the same as concatenating everything into a big file.

**Comment by donglabimaging** [comment]
We understand the issue with the frame number now, and thank you so much for looking into ways to fix it! It would definitely be wonderful if we can start using the function to resize our videos. As for the other issue regarding file input, we will follow your advice and try to optimize the results using two files as an input first, and then see if we can maintain the quality of the output as we increase the number of input files. Thank you so much for your guidance!

**Comment by donglabimaging** [comment]
Hi @epnev ,

May I ask if you had the time to fix the opencv bug?  Thanks.

Best,

Allen

**Comment by epnev** [comment]
@donglabimaging it's fixed now.
