### ISSUE TITLE
GUI loads in video data rotated 90 degrees

### ISSUE THREAD

**Issue by tvajtay** [flatironinstitute/CaImAn#638]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux
 2. Python version (3.x): 
 3.6
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Caiman GUI from command line
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 1.6.2
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

When I open the data in the CaImAn GUI the video data appears to be loaded in sideways relative to the original video.

![Screenshot from 2019-08-30 13-41-48](https://user-images.githubusercontent.com/17116111/64046994-823c2700-cb3b-11e9-9549-ff24e34482c8.png)

**Comment by epnev** [comment]
@tvajtay you're right.

@caichangjia Can you take a look? If you run `demo_caiman_basic` and then load the results on GUI, the image does appear rotated.

**Comment by caichangjia** [comment]
@epnev Sure.

**Comment by epnev** [comment]
@caichangjia I'm pretty sure the reason of this behavior is that opencv is being used for plotting and computing contours etc. OpenCV flips the axes compared to matplotlib/skimage in the rest of caiman. The best fix here would be to replace the `cv2.drawContours` function with our function [`get_contours`](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/utils/visualization.py#L323). 
@agiovann what do you think?

**Comment by pgunn** [comment]
(another option would be to flip it back)

**Comment by epnev** [comment]
@tvajtay This is fixed with #653 (currently on dev, will be included in the next release).
