### ISSUE TITLE
Is there a way to rerun "estimates.detrend_df_f" after manually merging components? 

### ISSUE THREAD

**Issue by SamBenezra** [flatironinstitute/CaImAn#641]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux
 2. Python version (3.x): 
 3.6
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Spyder
 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_dendritic
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
After merging a few components using 'estimates.manual_merge', the resulting estimates.C appears to reflect the merged components (judging by the number of rows), however the resulting estimates.F_dff does not reflect the merged components. 

I get a dimension mismatch error when trying to rerun detrend_df_f on the merged estimates. Is there a correct way to approach this issue?

- **Copy error log below**
estimates.detrend_df_f(quantileMin=8, frames_window=250)
Traceback (most recent call last):

  File "<ipython-input-33-35e917b72027>", line 1, in <module>
    estimates.detrend_df_f(quantileMin=8, frames_window=250)

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/estimates.py", line 659, in detrend_df_f
    detrend_only=detrend_only)

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py", line 365, in detrend_df_f
    YrA = nA_mat * YrA

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/scipy/sparse/base.py", line 517, in __mul__
    raise ValueError('dimension mismatch')

ValueError: dimension mismatch

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@SamBenezra I believe that was not possible in the past but it is now. What's the version of caiman you're using?

**Comment by SamBenezra** [comment]
My apologies, I was running an older version I installed in July. I just updated and it works. Thanks!

**Comment by epnev** [comment]
Great!
