### ISSUE TITLE
CaImAn installation in Windows

### ISSUE THREAD

**Issue by mischiatim** [flatironinstitute/CaImAn#642]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Windows 

 2. Python version (3.x): 
 3.6.7

 3. Working environment (Python IDE/Jupyter Notebook/other):
Spyder 

 4. Which of the demo scripts you're using for your analysis (if applicable):

 5. CaImAn version*: 
current conda-forge package 

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
unable to install

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I am a new Caiman user attempting to install the package on a Windows machine.
I followed the steps for the package-based installation and completed the following steps without errors ('conda create -n caiman', 'conda install caiman -c conda-forge').
However, I could not complete the subsequent steps as 'caimanmanager' does not seem to be recognized (both 'caimanmanager.py install' and 'python caimanmanager.py install' commands failed, see logs below).

Note that I could not complete the developer-based installation either, because Microsoft Build Tools for Visual Studio 2017 is not available anymore (unless one has some paid Microsoft developer account) as it has been replaced with Microsoft Build Tools for Visual Studio 2019, which however caused some compilation error when attempting to complete the developer-based installation of caiman.     

- **Copy error log below**
After attempting 'caimanmanager.py install', the error message was:
'caimanmanager.py' is not recognized as an internal or external command, operable program or batch file.

After attempting 'python caimanmanager.py install' from home folder, the error message was:
python: can't open file 'caimanmanager.py': [Errno 21] No such file or directory.

As a hack, I tried to copy on my home folder the folder of demos and examples that appears to be created as part of the installation process (under anaconda\envs\caiman\share) but the demo notebooks failed to execute correctly (missing packages, etc.)

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
One of the challenging parts of using python packages on Windows is that the PATH variable (where the shell looks for commands) can have a variety of settings.

Let's clear the slate and start again. Please do the following commands:

```
conda env remove -n caiman
conda create -n caiman -c conda-forge caiman
conda activate caiman
caimanmanager.py install
```

Let me know that goes.

**Comment by mischiatim** [comment]
Thanks for the quick reply.
Unfortunately I got the same error ('caimanmanager.py' is not recognized...) after following your suggestion.

(
As a sidenote, I got the following warnings while removing the previous caiman environment:

INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}',
prefix: 'C:\Users\labadmin\Anaconda3\envs\caiman', env_name: 'caiman', mode: 'No
ne', used_mode: 'user'
'"C:\Users\labadmin\Anaconda3\envs\caiman\Scripts\jupyter-nbextension.exe"' is not recognized as an internal or external command, operable program or batch file.

WARNING conda.core.link:run_script(519): pre-unlink script failed for package conda-forge::widgetsnbextension-3.5.1-py36_0
consider notifying the package maintainer
)

**Comment by pgunn** [comment]
Ok. So instead of that last command, let's do this:

`python C:\Users\labadmin\Anaconda3\envs\caiman\bin\caimanmanager.py install`

(be sure you're still in the caiman environment).

**Comment by mischiatim** [comment]
It doesn't give an error, but nothing seems to happen either.

**Comment by pgunn** [comment]
There's a good chance that it succeeded then; do you now have a caiman_data directory in C:\Users\labadmin  ?

**Comment by mischiatim** [comment]
No, and there isn't a 'caiman_data' folder anywhere in the system.

**Comment by pgunn** [comment]
You got literally no output from that install command above? That's very surprising. It didn't pop things up in an editor, did it?

**Comment by mischiatim** [comment]
No, I can see it's trying to do something (shows a spinning wheel for about 5secs) but then nothing happens.

(I can double click on caimanmanager.py, however, and it opens the file up in an Enthought Canopy editor page)

**Comment by pgunn** [comment]
If you do `python C:\Users\labadmin\Anaconda3\envs\caiman\bin\caimanmanager.py --help`, do you get any output?

**Comment by mischiatim** [comment]
Nope. Usual spinning wheel for 5 secs, then nothing.

**Comment by pgunn** [comment]
What happens if you just type "python" from the prompt?

**Comment by mischiatim** [comment]
It enters into Python (3.6.7) command line mode.

**Comment by pgunn** [comment]
What happens if you type this from the commandline?

```C:\Users\labadmin\Anaconda3\envs\caiman\bin\caimanmanager.py --help```

**Comment by pgunn** [comment]
I am really puzzled as to what's going on on your system. It's surprising that you get nothing when we ran python against the script with --help.

Can you send me the output of this?

```dir C:\Users\labadmin\Anaconda3\envs\caiman\bin\caimanmanager.py```

**Comment by mischiatim** [comment]
It shows that the file (caimanmanager.py) is about 10kb, but the interesting thing is that it shows as having been modified on 8/27/2019 at 8:49am. Shouldn't it show today's date?

**Comment by pgunn** [comment]
In this case no ; that's probably the date the build you have was packaged.

When you start the python interactive shell, it probably doesn't immediately say `>` (the prompt); there's some text beforehand. Can you paste that text in here?

Also, can you send me the output of `caiman env list` ?

**Comment by mischiatim** [comment]
# conda environments:
caiman                *  C:\Users\labadmin\Anaconda3\envs\caiman
phy                      C:\Users\labadmin\Anaconda3\envs\phy
root                     C:\Users\labadmin\Anaconda3

**Comment by pgunn** [comment]
Can you do a `where python`?

**Comment by mischiatim** [comment]
C:\Users\labadmin\Anaconda3\envs\caiman\python.exe
 C:\Users\labadmin\Miniconda3\python.exe

**Comment by pgunn** [comment]
I'm surprised you got python 3.6. Can you do a `conda list | findstr python`  ?

**Comment by mischiatim** [comment]
ipython                   7.8.0            py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
python                    3.6.7             he025d50_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge

**Comment by pgunn** [comment]
Something odd is happening with your PATH, as your caiman environment has 3.6.7 but when you run python manually you get 3.6.1. Also, ideally installing caiman would get you an environment with python 3.7.x.

Two things.

First, please let me know what you get from the following command:

```echo %PATH%```

Second, let's give this a try (to bypass PATH):
```C:\Users\labadmin\Anaconda3\envs\caiman\python.exe C:\Users\labadmin\Anaconda3\envs\caiman\bin\caimanmanager.py --install```

**Comment by mischiatim** [comment]
1) output of 'echo %PATH%': 
C:\Users\labadmin\Anaconda3\envs\caiman;C:\Users\labadmin\Anaconda3\envs\caiman\
Library\mingw-w64\bin;C:\Users\labadmin\Anaconda3\envs\caiman\Library\usr\bin;C:
\Users\labadmin\Anaconda3\envs\caiman\Library\bin;C:\Users\labadmin\Anaconda3\en
vs\caiman\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Pr
ogram Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA G
PU Computing Toolkit\CUDA\v9.0\libnvvp;c:\program files\nvidia gpu computing too
lkit\cuda\v8.0\bin;c:\program files\nvidia gpu computing toolkit\cuda\v8.0\libnv
vp;c:\program files\nvidia gpu computing toolkit\cuda\v7.0\bin;c:\program files\
nvidia gpu computing toolkit\cuda\v7.0\libnvvp;c:\programdata\oracle\java\javapa
th;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\
;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\win
dowspowershell\v1.0\;c:\program files\intel\intel(r) management engine component
s\dal;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\
program files\intel\intel(r) management engine components\ipt;c:\program files (
x86)\intel\intel(r) management engine components\ipt;c:\program files (x86)\quic
ktime\qtsystem\;C:\Program Files\MATLAB\R2018a\bin;c:\program files\matlab\r2017
a\bin;c:\program files\matlab\r2015b\bin;c:\program files (x86)\windows kits\8.1
\windows performance toolkit\;c:\program files\microsoft sql server\110\tools\bi
nn\;c:\program files (x86)\microsoft sdks\typescript\1.0\;c:\program files\micro
soft sql server\120\tools\binn\;c:\program files\git\cmd;c:\program files (x86)\
putty\;c:\users\labadmin\documents\nvidia_cuda_dnn_library\cuda\bin;C:\Program F
iles (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Users\lab
admin\Anaconda3\envs\caiman;C:\Users\labadmin\Anaconda3\envs\caiman\Library\ming
w-w64\bin;C:\Users\labadmin\Anaconda3\envs\caiman\Library\usr\bin;C:\Users\labad
min\Anaconda3\envs\caiman\Library\bin;C:\Users\labadmin\Anaconda3\envs\caiman\Sc
ripts;C:\Users\labadmin\Miniconda3;C:\Users\labadmin\Miniconda3\Library\mingw-w6
4\bin;C:\Users\labadmin\Miniconda3\Library\usr\bin;C:\Users\labadmin\Miniconda3\
Library\bin;C:\Users\labadmin\Miniconda3\Scripts;C:\Program Files (x86)\Microsof
t VS Code\bin

2) I tried the command you suggested but got the same outcome as before (spinning wheel 5secs then nothing)

**Comment by pgunn** [comment]
Ok. This next one is a bit weird, but let's give it a go.

```conda install -c conda-forge python=3.7```
After that, let's retry first
```python``` (and let's see what version of python it says you're on then)
and then
```python C:\Users\labadmin\Anaconda3\envs\caiman\bin\caimanmanager.py --install```

**Comment by pgunn** [comment]
One more thing I noticed ; it appears you've installed both Miniconda and Anaconda on your system. This is not a good thing, and may be responsible for things being messed up. It may be a good idea to entirely remove both of them and reinstall just one (this will work best if you're not using Anaconda/Miniconda for something already). Alternatively, if you have a fresh computer around that you haven't installed either on, it's likely going to be faster to get that to a working state.

**Comment by mischiatim** [comment]
Ok, I found a new workstation where I could start clean with a new installation of Anaconda (Python 3.7). Now executing 'caimanmanager.py --install' (after 'conda create -n caiman -c conda-forge caiman' and activating the caiman environment) opens up an editor window (Spyder), but no 'caiman_data' folder is created anywhere. What should I do next?

**Comment by pgunn** [comment]
Ok, we're getting closer. While in the conda environment, try again with this:

```python caimanmanager.py --install```

**Comment by mischiatim** [comment]
Great, it finally worked after doing the following:
1) Executing 'conda install -c conda-forge python=3.7' as you suggested earlier, to update the version of Python within the caiman environment (which by default was still 3.6.7)
2) Executing 'python C:\Users\labadmin\Anaconda3\envs\caiman\bin\caimanmanager.py install' (with the complete path and without the dashes -- before 'install')
Thanks a lot for your help.

**Comment by pgunn** [comment]
I'm happy it worked out.
