### ISSUE TITLE
Trying to run notebook interface but no 'nb_interface' folder?

### ISSUE THREAD

**Issue by cudmore** [flatironinstitute/CaImAn#646]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 macOS Sierra, 10.12.6

 2. Python version (3.x): 
 3.7

 3. Working environment (Python IDE/Jupyter Notebook/other):
Command line, custom python scripts, JUpyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 nb_interface folder

 5. CaImAn version*: 
1.0 ?
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
git clone https://github.com/flatironinstitute/CaImAn
cd CaImAn/
conda env create -f environment.yml -n caiman
source activate caiman
pip install -e .

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I am trying to run your notebook interface in the 'nb_interface' folder. I followed the installation of the development version instruction but do not have a 'nb_interface' folder to get started? Looking at the github for CaImAn, I don't see a 'nb_interface' in the online repo?

**Comment by epnev** [comment]
@cudmore I'm not sure where you found about the notebook interface. It has not been released (yet) and exists in a different branch of our repo (`nb_interface2.0`). You can try it out if you want, but it's not synced to the current state of the code and we cannot provide any support whatsoever.
