### ISSUE TITLE
cnmf.fit fails due to a pickling error

### ISSUE THREAD

**Issue by ckemere** [flatironinstitute/CaImAn#648]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 

Linux (Ubuntu 19.04)
 
 2. Python version (3.x): 
 
Python 3.7 (fresh Anaconda)

 3. Working environment (Python IDE/Jupyter Notebook/other):

Both Jupyter notebook and VisualStudio Code
 
 4. Which of the demo scripts you're using for your analysis (if applicable):

demos/general/demo_pipeline_cnmfE.py

modified with larger gSig (15,15) and gSiz (61, 61) to match my data 

 5. CaImAn version*: 
 
Newest (pulled from github this week)

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

`pip install -e`

- **Describe the issue that you are experiencing**

In `cnmf.fit(images)`, things run along for a while, and then a pickling failure appears. I suspect this is symptomatic of something else, but I'm not sure where to start looking.

- **Copy error log below**

```
---------------------------------------------------------------------------
MaybeEncodingError                        Traceback (most recent call last)
 in 
      1 cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, Ain=Ain, params=opts)
----> 2 cnm.fit(images)

~/Code/CaImAn/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    603                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    604                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 605                     indices=indices)
    606 
    607             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, Noneõ
~/Code/CaImAn/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    603                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    604                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 605                     indices=indices)
    606 
    607             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~/Code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    245     if dview is not None:
    246         if 'multiprocessing' in str(type(dview)):
--> 247             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    248         else:
    249             try:

~/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    681             return self._value
    682         else:
--> 683             raise self._value
    684 
    685     def _set(self, i, obj):

MaybeEncodingError: Error sending result: ''. Reason: 'PicklingError("Can't pickle : import of module '_flapack' failed")'

```

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
The most likely theory for what's happening is that the size of your data, combined with the level of parallelism chosen, is causing the datasets to exceed the maximum size that the pickle format can handle (later versions lift this limit).

Before we go with diagnosing that (most likely, either downsampling your data or changing the level of parallelism), could you try running the normal demos to see if the issue turns up with our bundled datasets? I expect it won't, but it'd be good to make sure before we go down the other route.

**Comment by epnev** [comment]
@ckemere I agree that this looks like a memory issue. `gSig=15` is a large value which shows that you can benefit from significant spatial downsampling by a factor of 2-3 or more.

**Comment by ckemere** [comment]
Hey all, much appreciated for the speedy response. Yes, it's very large (it's a new miniscope sensor that's 1920x1080, and I was working with 6000 frames), and yes, the demo runs with the default downloaded data. 

@epnev I didn't dig into the code yet to answer this question, but maybe you can answer quickly - if I set the `ssub` parameter, does that do the downsampling for me? Or do I need to do it manually prior to calling `fit`?

**Comment by epnev** [comment]
@ckemere `ssub` will do it for you and then the algorithm will upsample the results back to the original resolution. You can also do it manually prior to any preprocessing if you want to reduce your data load.

**Comment by ckemere** [comment]
Awesome (and thanks again for the speedy reply!). Should I change gSig to take account of the scaling, or is that automatically done?

**Comment by epnev** [comment]
it'll be done automatically. Let me know if that works so we can close the issue.

**Comment by ckemere** [comment]
I tried with `ssub` set to 5 and still got the pickling error. (I also set `tsub` to 4.) Trying again with 8.

**Comment by epnev** [comment]
how big is your dataset?

**Comment by ckemere** [comment]
6000 (frames) x 1920 x 1080. Also, it's 30 fps, so I changed that parameter.

**Comment by ckemere** [comment]
(Is there a convenient way of uploading it somewhere?)

**Comment by ckemere** [comment]
Same error; now testing `ssub = 10` and `ssub_B = 5`.

**Comment by epnev** [comment]
This is fairly large (I guess the resolution changed with the new miniscope). At single precision this would amount to ~50GB which will be tough for the current algorithm (we'll have some news on that soon). If that resolution is not strictly necessary you could try downsampling prior to any processing.

@pgunn Would reducing the degree of parallelism (`n_processes` ) help here?

**Comment by pgunn** [comment]
Hi,
As an experiment, would you mind modifying the top of the following file:

~/Code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py

adding the line `from scipy.linalg import _flapack` to the import section?

**Comment by ckemere** [comment]
In response to the too-much-data idea, I tried downsampling my data after motion correction.

```
images2 = images[:,::3,::3]
dims2 = images2.shape[1:3]
```

and I set the `dims` parameter in the options structure to `dims2`. Correlation/PNR calculation seems to work ok, but then I now get the following error in `cnmf.fit()`:
```
2173890 [params.py:                 set():858][37421] Changing key n_processes in group patch from 1 to 16
     2173891 [params.py:                 set():858][37421] Changing key init_batch in group online from 200 to 6358
     2175394 [params.py:                 set():858][37421] Changing key medw in group spatial from None to (3, 3)
     2175396 [params.py:                 set():858][37421] Changing key n_pixels_per_process in group preprocess from None to 13880
     2175396 [params.py:                 set():858][37421] Changing key n_pixels_per_process in group spatial from None to 13880
     2175398 [params.py:                 set():858][37421] Changing key n_pixels_per_process in group preprocess from 13880 to 1600
     2175398 [params.py:                 set():858][37421] Changing key n_pixels_per_process in group spatial from 13880 to 1600
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ckemere/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ckemere/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ckemere/Code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 137, in cnmf_patches
    cnm = cnm.fit(images)
  File "/home/ckemere/Code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 505, in fit
    self.initialize(Y)
  File "/home/ckemere/Code/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 964, in initialize
    **self.params.get_group('init'))
  File "/home/ckemere/Code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 331, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)
  File "/home/ckemere/Code/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1093, in greedyROI_corr
    dview=None, dims=(d1, d2), **options['spatial_params'])
  File "/home/ckemere/Code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 240, in update_spatial_components
    parallel_result = list(map(regression_ipyparallel, pixel_groups))
  File "/home/ckemere/Code/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 393, in regression_ipyparallel
    c = C[idxs_C[idx_px_from_0], :]
IndexError: index 395 is out of bounds for axis 0 with size 394
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
 in 
      1 cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, Ain=Ain, params=opts)
----> 2 cnm.fit(images2)

~/Code/CaImAn/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    603                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    604                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 605                     indices=indices)
    606 
    607             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~/Code/CaImAn/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    245     if dview is not None:
    246         if 'multiprocessing' in str(type(dview)):
--> 247             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    248         else:
    249             try:

~/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    681             return self._value
    682         else:
--> 683             raise self._value
    684 
    685     def _set(self, i, obj):

IndexError: index 395 is out of bounds for axis 0 with size 394
```

**Comment by epnev** [comment]
If `images` is the loaded memory mapped file this approach won't work. You would need to read/load an already downsampled file.

If you can upload your file somewhere I can try and take a look.

**Comment by ckemere** [comment]
Update - I finally had the chance to dig a bit, and I discovered something - the "gSig" and "gSiz" parameters appear to drive whether or not I get the `MaybeEncodingError: Error sending result: ''. Reason: 'PicklingError("Can't pickle : import of module '_flapack' failed")'` error. Specifically, with my data, `gSig=9` and `gSiz=37` works, but `gSig=10` and `gSiz=41` causes an error. Any thoughts about how I could track this down?

**Comment by pgunn** [comment]
For the _flapack error, if you get the chance you could try the change I mentioned above. It may not be exactly what we're trying to debug, but it may fix the error that comes up when that parameter is used.

**Comment by ckemere** [comment]
Yes, sorry - I had already done that, and verified that I was running the functions from the new `map_reduce.py` (my error is on line 249).

**Comment by ckemere** [comment]
I just verified that making that parameter change (`gSig` and `gSiz`) using the downloaded data from the CNMF-E example code also causes it to fail with the same error:

**Comment by epnev** [comment]
@ckemere Thanks, that's a useful observation. Is `rf` at the default value 40? If so, make sure that you set it to a value greater than `gSiz`. In general `rf` should be significantly greater than `gSiz` by a factor of 2-3 at least. For your setting, I would actually set `gSiz` at a smaller value (it does not have to be `4*gSig` but it has to be odd and `>2*gSig` and also increase `rf` significantly.

**Comment by ckemere** [comment]
Awesome. I changed the `rf` factor and also reduced the `gSiz` to `2*gSig + 1`, and did not get the error with the test data. Now trying with my own data. I'll update this comment and close if it works!

**Comment by ckemere** [comment]
I think I can close this issue now. For the particular error that I reported, making sure `rf` has a reasonable value appears to be the solution. Thanks much for help!
