### ISSUE TITLE
About Tif format: how to map my own grayscale image to CaImAn Tif file?

### ISSUE THREAD

**Issue by KaiWangCanada** [flatironinstitute/CaImAn#652]
I use tifffile read CaImAn sample tif:
`img_grays = tifffile.imread('/home/kai/caiman_data/example_movies/Sue_2x_3000_40_-46.tif')`
Then check the image type:
`type(img_grays[0][0][0])`
I got:
`numpy.float32`
Looks like CaImAn tif is float32 format.

I plot hist of an image:
`_, _, _ = plt.hist(img_grays[0].ravel(), 100)`
Looks like CaImAn image pixel value ranges from -296.0 to 603.0.

The question is:
1. what does the range mean?
2. how to map a pixel value ranges (0, 65535) to CaImAn's float32?

Thanks!

**Comment by epnev** [comment]
@KaiWangCanada 
1. The range can be negative if during the acquisition the microscope software introduces an offset
2. CaImAn can process files that are not in the float32 format. It will convert them automatically during motion correction/memory mapping.

**Comment by KaiWangCanada** [comment]
@epnev 
Thanks for the clarify. Now I know what to do :)

CaImAn is a wonderful projects. Thank you so much for create it. 

Best regards,
