### ISSUE TITLE
Data value change after motion correction

### ISSUE THREAD

**Issue by x8808099** [flatironinstitute/CaImAn#655]
The data value distribution of motion corrected mmap files is different from the original files. I was wondering what happened during motion correction that changes the data distribution. In non-rigid case, such change seems to affect the quality of extracted signals.

The original tiff value distribution (range: 0-2**14, zero: ~96%, saturation: ~2%):
<img width="1896" alt="screenshot" src="https://user-images.githubusercontent.com/21134731/67160944-52b1da00-f388-11e9-819f-8cbb5db95f66.png">

Rigid motion corrected (maintains the range):
<img width="1894" alt="screenshot" src="https://user-images.githubusercontent.com/21134731/67160966-8ab91d00-f388-11e9-827f-e8e42e4f48aa.png">

Non-rigid motion corrected (range is wider with negative values):
<img width="1893" alt="screenshot" src="https://user-images.githubusercontent.com/21134731/67160988-d075e580-f388-11e9-8d43-acc05828aed6.png">

**Comment by epnev** [comment]
@x8808099 Try setting `nonneg_movie=False` in the motion correction object. Does this keep the range?

**Comment by x8808099** [comment]
I've made min_mov=0, the result is the same. Is this equivalent to set nonneg_movie=False?

**Comment by epnev** [comment]
@x8808099 I took a look at the code. I'm reasonably confident that the changes in the dynamic range are introduced from the application of sub-pixel shifts with an interpolation method that is something more thoughtful than just a nearest neighbor interpolation. 

You can set `nonneg_movie=False` or `min_mov=0` which essentially is a flag for subtracting the minimum value of the movie (and in the movie has negative values, make it non-negative) but that itself does not affect the range. The range gets affected by the intercubic interpolation used when `shifts_opencv=True` or the Fourier interpolation when `shifts_opencv=False`. Setting a nearest interpolation (you can do that by modifying the sources) can preserve the range, but the results will be poorer in my opinion. In you data you have both truncation at zero and saturation at 2**14, so these are smoothed out during the interpolation. If you want to preserve the range, you can clip each corrected frame to have the same min/max values as the original data.

**Comment by epnev** [comment]
I should add that, as you observed, this effect would be stronger for pw-rigid motion correction, where the shifts are non-uniform across the FOV.

**Comment by x8808099** [comment]
I want to clip the negative values but I didn't see a parameter in motion correction that can do this. Or this might not be an issue? How does the cnmf handle negative values when temporal components are non-negative?

**Comment by epnev** [comment]
There is no parameter that controls the clipping at the moment. You will need to either modify the sources, or write a slightly modified memory mapping function. But I don't think it's necessary. CNMF can produce negative values if needed. These can be either in the temporal background components `estimates.f` or in the baseline activity of each trace `estimates.bl`. The latter is controlled by the parameter `params.temporal_params['bas_nonneg']`.

**Comment by vncntprvst** [comment]
Tracking down [another issue](https://github.com/kushalkolar/mesmerize-viz/issues/38) I was also puzzled by the negative values coming out of motion correction. 
Just to confirm, when replacing `cv2.INTER_CUBIC` by `cv2.INTER_LINEAR` at the [`tile_and_correct` step](https://github.com/flatironinstitute/CaImAn/blob/9b0b79ca61f20ce93259b9833e1fe18e26d4e086/caiman/motion_correction.py#L2237C60-L2237C60), there are no out-of-range values anymore. 
```
m_reg = cv2.remap(img, cv2.resize(shift_img_y.astype(np.float32), dims[::-1]) + x_grid,
                              cv2.resize(shift_img_x.astype(np.float32), dims[::-1]) + y_grid,
                              cv2.INTER_CUBIC, borderMode=cv2.BORDER_REPLICATE)
np.min(m_reg)
-7128.232741199434
np.max(m_reg)
73333.82225518674
```
```
m_reg = cv2.remap(img, cv2.resize(shift_img_y.astype(np.float32), dims[::-1]) + x_grid,
                              cv2.resize(shift_img_x.astype(np.float32), dims[::-1]) + y_grid,
                              cv2.INTER_LINEAR, borderMode=cv2.BORDER_REPLICATE)
np.min(m_reg)
0.0
np.max(m_reg)
65520.0
```
These out-of-range values can be clipped if needed.

**Comment by EricThomson** [comment]
That's a really good find @vncntprvst ! Definitely worth looking into this more deeply!

**Comment by vncntprvst** [comment]
This is useful to know, especially when using calcium indicators with low SNR, because the re-scaled range artificially reduces the SNR. And just for visualization purposes, the new range makes the background more gray (less contrast).
To clip the values to the 0-65535 range, for example if saving the motion corrected movie `mcorr_movie`, one can do this: `mcorr_movie_16bit = np.clip(mcorr_movie, 0, 2**16-1)` (casting to uint16 data type with `mcorr_movie.astype(np.uint16)` doesn't work well.)
