### ISSUE TITLE
tile_and_correct() seems to skip half the algorithm

### ISSUE THREAD

**Issue by bsugerman** [flatironinstitute/CaImAn#657]
Unless I'm missing something, I think the tile_and_correct() function is skipping about half of its code if you set `shifts_opencv=True`. 

In the current `motion_correction.py file, on line 2120 you open an `if` statement with
`if shifts_opencv:` which applies the` translation mapping with `cv2.remap`. Then you return the registered image 
```
            return m_reg - add_to_movie, total_shifts, None, None
```
The function continues for 110 more lines, and originally I assumed that this was in case one chose to use `apply_shifts_dft` instead of opencv. However on line 2173 you have another option to use `shifts_opencv` to call `apply_shifts_iteration`. It seems like the only way to get past line 2135  is to use `shifts_opencv=False`, so you would never use `apply_shifts_iteration` on line 2179. And if you do set `shifts_opencv=True` then you will never reach the tests for too much shear. Did you mean for this to happen, or is there a mistake somewhere, like the return statement on line 2133?

**Comment by epnev** [comment]
@bsugerman Thanks for the question, and taking the effort to go through this. If you use `shifts_opencv=True`, then the motion field will be upsampled to the original resolution (lines 2125-2126) and then will be applied to the original frame. You don't need to separately test for too much shearing, as this upsampling procedure already assumes that it exists. Does this answer your question?

**Comment by bsugerman** [comment]
Yes, it certainly does answer it. However, it might be good to remove that
second if/then option with `shifts_opencv=True` on lines 2173-2182 since
you can never use it. As long as I'm writing, I think you have a small
type-o on line 1643, in the `register_translation` function. You call
opencv's `fftn` here, but then numpy's `fftn` the line before.

-ben

**Comment by epnev** [comment]
Thanks, I incorporated your suggestions in an upstream branch.
