### ISSUE TITLE
Qt and Pillow import errors after new installation of CaImAn

### ISSUE THREAD

**Issue by SuperSonicHedgehog** [flatironinstitute/CaImAn#659]
Hi,

I'm having problems with CaImAn installation through conda-forge, although the same procedure worked perfectly well last month on another computer. See the details below :
 
 1. Operating system (Linux/macOS/Windows): **Windows 10**

 2. Python version (3.x): **python 3.7.3**
 
 3. Working environment (Python IDE/Jupyter Notebook/other): **Spyder**
 
 4. Which of the demo scripts you're using for your analysis (if applicable): **demo_pipeline.py**
 
 5. CaImAn version: **caiman 1.6.3**
 
 6. CaImAn installation process: `conda create -n caiman -c conda-forge caiman`

After having installed caiman in a new environment, I tried to open Spyder within that environment and to run a modified version of the demo pipeline. When doing so, I get this message in the conda terminal: 
`Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.`
Besides, at the startup in Spyder, an import error that seems related to the pillow library (6.2.1) appears in the ipython console : 
![Untitled](https://user-images.githubusercontent.com/16664777/68530545-2e06ad80-0309-11ea-83a2-787cdb805d87.png)

I tried to uninstall pillow from the caiman environment with pip and install an earlier version (6.1.0, I think). It didn't remove the message in the conda terminal, but it removed the import error at Spyder startup. When I try to launch my script, which starts with an OpenCV import, I get an error saying that the module is not found, and indeed, I can't find it in the environment list of packages. After installing OpenCV with pip (`pip install opencv-contrib-python`), I can run the script (a modified version of the demo pipeline that is working fine on my other installation of CaImAn in another computer), but I think it stays stuck at the source extraction step (I am not running any motion correction).

Do you know anything about this problem ?

Thank you in advance.

**Comment by pgunn** [comment]
Hi,
At this time I would strongly recommend not using Spyder (with CaImAn, and in general) as it's no longer under active development and you're much more likely to hit issues like this moving forward. PyCharm might treat you better.

Opencv should be installed using the conda package called opencv; I don't know much about the alternate version you installed, but opencv is installed through our environment file, and if it was not present you should delete the environment you made, remake it, and verify that the environment matches the environment.yml

Happy to help you debug further once you've done that.

**Comment by SuperSonicHedgehog** [comment]
Hi,
I've just installed PyCharm and tried running the same script in it but I get the same error : 
![001](https://user-images.githubusercontent.com/16664777/68581293-6d9fd780-0478-11ea-93ef-011fad006205.png)
![002](https://user-images.githubusercontent.com/16664777/68581299-71335e80-0478-11ea-834c-44d80dc9c3bd.png)

**Comment by pgunn** [comment]
Hi, so I think we may need to untangle a few things to get you a working install.

First, I'm concerned by that "on win32" up there; did you install a 32-bit or 64-bit conda? 
Second, can you activate your caiman environment and do ```conda list | findstr opencv``` ?
And third, from inside your conda environment, if you can start the python interactive shell (just type python) and do ```import matplotlib```, I'd like to know if that suceeds (little or no output) or fails. (you can type control-Z on a blank line to exit interactive python)

Thanks.

**Comment by SuperSonicHedgehog** [comment]
I installed Anaconda 3 64-bit. 
This is what I get when I look for opencv : 
![opencv](https://user-images.githubusercontent.com/16664777/68607972-220a1f80-04b2-11ea-8399-e8823915d27a.png)
(One of them might be one that I installed to fix the failing "import cv2" ? (I don't remember exactly what I did)
And importing matplotlib in the python interactive shell seems to work.

**Comment by pgunn** [comment]
It's probably a good idea to do a `conda remove opencv-python`; the opencv you got from conda-forge should give you a cv2 and if it is not we'll want to debug that.

You'll want to make sure you're managing conda environments correctly in pycharm:

https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html

**Comment by SuperSonicHedgehog** [comment]
I couldn't remove opencv-python : 
![remove-opencv](https://user-images.githubusercontent.com/16664777/68609352-53d0b580-04b5-11ea-9fd5-3719db2dc1d2.png)

I have entirely removed the environment and re-installed it. Opencv-python is gone : 
![findopencv](https://user-images.githubusercontent.com/16664777/68609498-b45ff280-04b5-11ea-8dce-935f61af6ebd.png)

This is how I have setup the environment in pycharm:
![envsetuppycharm](https://user-images.githubusercontent.com/16664777/68609956-ecb40080-04b6-11ea-94bd-d6d169814668.png)

Now, when I import opencv I get : 
![importcv2](https://user-images.githubusercontent.com/16664777/68610346-d8bcce80-04b7-11ea-9b19-f8228ba5efe3.png)

**Comment by pgunn** [comment]
Can you verify that in this new environment, you can still use the interactive python shell to import cv2?

**Comment by SuperSonicHedgehog** [comment]
I can't import cv2 in the interactive python shell either, I get `ImportError: DLL load failed: The specified module could not be found.`

**Comment by pgunn** [comment]
I just spotted this in another issue that's otherwise unrelated but also on Windows; I need to investigate this further.

**Comment by SuperSonicHedgehog** [comment]
Ok, I look forward to hearing more about this ! Thanks a lot for your help.

**Comment by pgunn** [comment]
Hi, from within your caiman environment, can you do an `echo %PATH%` and paste the results in here?

**Comment by SuperSonicHedgehog** [comment]
There : 
`(caiman) C:\Users\PerrierLab>echo %PATH%
C:\Users\PerrierLab\Anaconda3\envs\caiman;C:\Users\PerrierLab\Anaconda3\envs\caiman\Library\mingw-w64\bin;C:\Users\PerrierLab\Anaconda3\envs\caiman\Library\usr\bin;C:\Users\PerrierLab\Anaconda3\envs\caiman\Library\bin;C:\Users\PerrierLab\Anaconda3\envs\caiman\Scripts;C:\Users\PerrierLab\Anaconda3\envs\caiman\bin;C:\Users\PerrierLab\Anaconda3\condabin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\MATLAB\R2017a\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\PerrierLab\Anaconda3;C:\Users\PerrierLab\Anaconda3\Library\mingw-w64\bin;C:\Users\PerrierLab\Anaconda3\Library\usr\bin;C:\Users\PerrierLab\Anaconda3\Library\bin;C:\Users\PerrierLab\Anaconda3\Scripts;C:\Users\PerrierLab\AppData\Local\Microsoft\WindowsApps`

**Comment by pgunn** [comment]
Hm. I think the OpenCV libraries are likely in C:\Users\PerrierLab\Anaconda3\envs\caiman\Library\bin and that's on your path. So this is puzzling. If you try "import cv2" from a python launched from the commandline in your environment, do you get the same thing?

**Comment by SuperSonicHedgehog** [comment]
I open the conda terminal, activate the caiman environment, launch either python or ipython, try to import cv2 and in all cases I get the import error. Is this what you asked?

**Comment by pgunn** [comment]
Yup. So this is not specific to your IDE; it's the environment. I'll need to poke around some more. It's surprising, as locally I made a new environment on a windows test box and it worked fine.

**Comment by SuperSonicHedgehog** [comment]
Hi,
Everything seems to be working fine now... I can import cv2, import caiman and analysis in the ipython or python shell, in Pycharm and in Spyder. To make it work in Spyder I had to do a `conda install spyder-kernels=0.*` from within the caiman environment. I'm not quite sure what is going on to be honest. In the meantime, I have installed for other purposes a GPU driver, CUDA and Visual Studio. I remember installing Visual Studio last time I had to install caiman, but it looks like doing that is not anymore in the package-based installation process. Could that explain the problems I have been running into?

**Comment by SuperSonicHedgehog** [comment]
After trying a bit more I think it's not working in Spyder, I can do the imports correctly and the memory-mapping but I think it stays stuck at the source extraction step. Anyway, I'll just use PyCharm from now on.

**Comment by pgunn** [comment]
I don't know how you got it working, but I'm glad you got your way to a working config. The package-based install does not need a compiler as the package includes the platform-specific compiled elements.

If the source extraction seems stuck, as a first debugging step you should try a run in non-clustered mode, but if you could open another ticket for that that'd be great.
