### ISSUE TITLE
Question: Overlay accepted components on mean image.

### ISSUE THREAD

**Issue by donglabimaging** [flatironinstitute/CaImAn#661]
Hi @epnev ,

I am trying to make a figure similar to Figure 7 in the CaImAn paper (The one shows the correlation image with accepted components masked on top).  The default color of the correlation image is blue and red.  How do I change the color of the correlation image to match those in Figure 7?  

To get around this issue, I have tried to overlay the accepted components on the first image of the video with the code below.  However, the color is distorted.  May I ask if there is a way to get the image to grey scale and the accepted components to a different color (e.g. white)?  Thank you.

`cnm.estimates.plot_contours_nb(img = images[0], idx=cnm.estimates.idx_components)`

![Overlay](https://user-images.githubusercontent.com/50585879/68712708-4b868200-056a-11ea-90d1-c4e02715d47a.PNG)

Best,

Allen

**Comment by epnev** [comment]
I don't think you can do that through the `estimates.plot_contours_nb` function. However you can use the [`plot_contours`](https://github.com/flatironinstitute/CaImAn/blob/6b027d10dd136833c288e2987cbf9a87aef2a625/caiman/utils/visualization.py#L962) of the [`nb_plot_contour`](https://github.com/flatironinstitute/CaImAn/blob/6b027d10dd136833c288e2987cbf9a87aef2a625/caiman/utils/visualization.py#L739) function in the visualization module that accepts both a colormap argument and a colors argument.

**Comment by donglabimaging** [comment]
That's exactly what I ended up doing.  I found the `plot_contours` in visualization.py file and got something close to what we wanted.  Thank you for your help as always!
