### ISSUE TITLE
Solving Environment Issue

### ISSUE THREAD

**Issue by AlisaOmel** [flatironinstitute/CaImAn#662]
1. Operating system (Linux/macOS/Windows): 
 MacOS High Sierra Vestion 10.13.6

 2. Python version (3.x): 
 Python 3.6.8 :: Anaconda, Inc.

 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda create -n caiman -c conda-forge caiman

I installed all the dependencies, but when I put in the conda create command the environment never gets solved:

Collecting package metadata (repodata.json): done
Solving environment: | 

Is there a reason it is hanging? 

Thanks!
Alisa

**Comment by pgunn** [comment]
How much RAM does the system you're doing this have? Have you used conda for other things too? How long did you let it try?

**Comment by AlisaOmel** [comment]
After I submitted this, I left it running and it took a little bit over an hour but finally went through. I just didn't expect it to work for over an hour and quit it after 45 minutes last time. 

Sorry for the hassle and thank you for the quick reply!

**Comment by pgunn** [comment]
One thing you might try to speed things up is to do a ```conda clean --all```

If you've used conda for a long time, a lot of cruft can accumulate that can slow things down.
