### ISSUE TITLE
error importing caiman

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [flatironinstitute/CaImAn#663]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): macOS
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other):Spyder
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline.ipynb
 
 5. CaImAn version*: 1.6.3
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

I couldn't import caiman. I have already installed and when I try to import it I have an error. I will appreciate your help a lot. 

- **Copy error log below**

  File "/usr/local/anaconda3/lib/python3.7/site-packages/scipy/_lib/_numpy_compat.py", line 16, in <module>
    _assert_warns = np.testing.assert_warns

AttributeError: module 'numpy' has no attribute 'testing'

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Interesting; this looks like an upstream error. If you can enter your caiman environment and issue the following two commands and let me know the output for each, that'll help me dig further:
```
conda list | grep numpy
conda list | grep scipy
```

Thanks

**Comment by sofiapuvogelvittini** [comment]
Dear pgunn. Thank you for you quick response. I just uninstall caiman and downloaded it again, following the instructions from: https://buildmedia.readthedocs.org/media/pdf/caiman/dev/caiman.pdf, and managed to solve the problem. I probably made a mistake during the installation before.
Thanks!
