### ISSUE TITLE
load a file issue

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [flatironinstitute/CaImAn#668]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): macOS
 
 2. Python version (3.x): 3.6
 
 3. Working environment (Python IDE/Jupyter Notebook/other):spyder
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 1.6.3
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

Hi! I am new with Caiman and I am trying to analyze a file. It is saved as a tiff stack (.tiff). I have been following a tutorial but I cant even start it:

import bokeh.plotting as bpl
import caiman as cm
from caiman.motion_correction import MotionCorrect
from caiman.source_extraction.cnmf import cnmf as cnmf
from caiman.source_extraction.cnmf import params as params
from caiman.utils.visualization import plot_contours, nb_view_patches, nb_plot_contour
bpl.output_notebook()

single_movie = cm.load('slice.tif')

# dataset dependent parameters
fr = 10             # imaging rate in frames per second
decay_time = 0.4    # length of a typical transient in seconds
dxy = (2., 2.)      # spatial resolution in x and y in (um per pixel)
# note the lower than usual spatial resolution here
max_shift_um = (12., 12.)       # maximum shift in um
patch_motion_um = (100., 100.)  # patch size for non-rigid correction in um

# motion correction parameters
pw_rigid = True       # flag to select rigid vs pw_rigid motion correction
# maximum allowed rigid shift in pixels
max_shifts = [int(a/b) for a, b in zip(max_shift_um, dxy)]
# start a new patch for pw-rigid motion correction every x pixels
strides = tuple([int(a/b) for a, b in zip(patch_motion_um, dxy)])
# overlap between pathes (size of patch in pixels: strides+overlaps)
overlaps = (24, 24)

# maximum deviation allowed for patch with respect to rigid shifts
max_deviation_rigid = 3
mc_dict = {
        'fnames': single_movie,
        'fr': fr,
        'decay_time': decay_time,
        'dxy': dxy,
        'pw_rigid': pw_rigid,
        'max_shifts': max_shifts,
        'strides': strides,
        'overlaps': overlaps,
        'max_deviation_rigid': max_deviation_rigid,
        'border_nan': 'copy'
    }
opts = params.CNMFParams(params_dict=mc_dict)

when I run "opts = params.CNMFParams(params_dict=mc_dict) " I have this answers : 

WARNING:root:Changing key dxy in group data from (1, 1) to (2.0, 2.0)
WARNING:root:Changing key pw_rigid in group motion from False to True
WARNING:root:Changing key max_shifts in group motion from (6, 6) to [6, 6]
WARNING:root:Changing key strides in group motion from (96, 96) to (50, 50)
WARNING:root:Changing key overlaps in group motion from (32, 32) to (24, 24)
An finally this error: raise Exception('Unknown input type')

Exception: Unknown input type

I will appreciate your help a lot!

- **Copy error log below**

raise Exception('Unknown input type')

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@sofiapuvogelvittini 
The error occurs because you are doing:
```
single_movie = cm.load('slice.tif')
mc_dict = {
'fnames': single_movie,
...}
```
which loads the file into memory and then passes it in the options dictionary. 
You should instead pass the path to the file(s) in the dictionary:
```
mc_dict = {
'fnames': ['slice.tif'],
...}
```

**Comment by sofiapuvogelvittini** [comment]
Thank you very much!
