### ISSUE TITLE
Motion correction template contains all NaNs for short videos

### ISSUE THREAD

**Issue by neuroczy** [flatironinstitute/CaImAn#669]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 macOS and Windows 10
 2. Python version (3.x): 
 Python 3.7.3
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Anaconda Prompt
 4. Which of the demo scripts you're using for your analysis (if applicable):
 Modified version of demo_pipeline.py to load my own TIFFs
 5. CaImAn version*: 
 1.6.3
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Performing motion correction on short videos (512x512 px, <91 frames) leads to an incorrect template containing all NaNs, and incorrect shifts from opencv.matchTemplate.

- **Copy error log below**

- **If you're not reporting an error, type your message below**
The issue appears to be mitigated if sufficient slices are loaded in MotionCorrection.motion_correct_batch_rigid().

On line 2668-2678 of motion_correction.py:
```
corrected_slicer = slice(subidx.start, subidx.stop, subidx.step * 10)
m = cm.load(fname, var_name_hdf5=var_name_hdf5, subindices=corrected_slicer)
    
if m.shape[0] < 300:
     m = cm.load(fname, var_name_hdf5=var_name_hdf5, subindices=corrected_slicer)
elif m.shape[0] < 500:
     corrected_slicer = slice(subidx.start, subidx.stop, subidx.step * 5)
     m = cm.load(fname, var_name_hdf5=var_name_hdf5, subindices=corrected_slicer)
else:
     corrected_slicer = slice(subidx.start, subidx.stop, subidx.step * 30)
     m = cm.load(fname, var_name_hdf5=var_name_hdf5, subindices=corrected_slicer)
```
The initial corrected_slicer specifies 10 frame increments, and is used to load a movie object.  The conditional statement on line 2671 specifies 300 frames in the loaded movie, corresponding to 3000 frames in the original video.  The movie is then reloaded with the same slicer.  Conversely, if there are less than 500 frames, the movie is reloaded with a smaller slicer (5 frame increments). And yet when there are greater than 500 frames, the movie is re-sliced at 30 frame increments.

I don't know if this loading scheme is by design, but if line 2668 is modified to:
`corrected_slicer = slice(subidx.start, subidx.stop, subidx.step)
`
The template will then be calculated correctly.  I did not investigate further into the source of NaNs when the sliced number of frames are low.  Would this work-around/fix be a valid long-term solution?

I look forward to your reply, thanks!

**Comment by epnev** [comment]
@neuroczy Thanks for this observation. Can you tell me how short your file was that gave you the NaN template?

The idea here is that we want to just *initialize* the template using only a small subset of the frames so we don't load the entire file in memory just for speed reasons. But I agree that the procedure can be improved if for example we read a fixed number of frames regardless of the file size.

**Comment by neuroczy** [comment]
@epnev Thank you for your response!  

> Can you tell me how short your file was that gave you the NaN template?

It would appear that tiff files with <= 90 frames lead to the NaN template.

> The idea here is that we want to just initialize the template using only a small subset of the frames so we don't load the entire file in memory just for speed reasons.

That makes sense.  So perhaps line 2668 should remain as it is with 10-frame increments, but in the `if m.shape[0] < 300:` clause, corrected_slicer should be redefined with a smaller slice step?  

As the code is currently, `m.shape < 300` is sliced with `subidx.step * 10`, `m.shape < 500` is `subidx.step * 5`, `m.shape >= 500` is `subidx.step * 30`.  One would expect the slicing step to monotonically increase with the number of frames.

**Comment by epnev** [comment]
> As the code is currently, `m.shape < 300` is sliced with `subidx.step * 10`, `m.shape < 500` is `subidx.step * 5`, `m.shape >= 500` is `subidx.step * 30`. One would expect the slicing step to monotonically increase with the number of frames.

You're right. Will introduce a fix soon.

**Comment by neuroczy** [comment]
That's great, thank you!

**Comment by epnev** [comment]
I'll leave it open until it's fixed (also as a reminder). Thanks again.

**Comment by epnev** [comment]
This commit 661a6bed505ee96bf045a99d254254b1d7254b1d should take care of the issue. Currently on the dev branch but will be merged into master in the following release.
