### ISSUE TITLE
Errors during motion correction

### ISSUE THREAD

**Issue by HoniSanders** [flatironinstitute/CaImAn#672]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Linux
 
 2. Python version (3.x): Python 3.6.6
 
 3. Working environment (Python IDE/Jupyter Notebook/other): command line
 
 4. Which of the demo scripts you're using for your analysis (if applicable): a modified version of demo_pipeline_cnmfE.py
 
 5. CaImAn version*: 1.7
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Failure during motion correction

- **Copy error log below**
```
Traceback (most recent call last):
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 755, in array_split
    Nsections = len(indices_or_sections) + 1
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/honi/caiman-analysis//full_cnmfE.py", line 319, in <module>
    main()
  File "/home/honi/caiman-analysis//full_cnmfE.py", line 142, in main
    mc.motion_correct(save_movie=True)
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/caiman/motion_correction.py", line 254, in motion_correct
    self.motion_correct_rigid(template=template, save_movie=save_movie)
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/caiman/motion_correction.py", line 305, in motion_correct_rigid
    indices=self.indices)
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/caiman/motion_correction.py", line 2716, in motion_correct_batch_rigid
    indices=indices)
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/caiman/motion_correction.py", line 2969, in motion_correction_piecewise
    idxs = np.array_split(list(rng), splits)
  File "<__array_function__ internals>", line 6, in array_split
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 761, in array_split
    raise ValueError('number sections must be larger than 0.')
ValueError: number sections must be larger than 0.
```

**Comment by epnev** [comment]
@HoniSanders Can you paste `params.motion` and the dimensions of the file(s) you're trying to analyze?

**Comment by HoniSanders** [comment]
`AttributeError: module 'caiman.source_extraction.cnmf.params' has no attribute 'motion'`

**Comment by epnev** [comment]
@HoniSanders I meant `opts.motion`, `params` is the name of the module but we assign it to `opts`. Anyway, I think that's sufficient provided everything else is left at the default value.

**Comment by HoniSanders** [comment]
Would you like me to share the files with you?  The error occurs with some videos but not others, and I'm not sure why.

**Comment by pgunn** [comment]
If you can find the smallest file you have that exhibits the problem, that'd be a great thing to share with us.

**Comment by HoniSanders** [comment]
https://www.dropbox.com/s/g5z1pd495h5sz3u/HM25_12.5x_MiniPOS_2019-11-19T10_06_16.avi?dl=0

**Comment by epnev** [comment]
@HoniSanders This file has only 14 frames and not 1000. I can reproduce the error but the reason is that the parameter `opts.motion['num_frames_split']` is set to the default value of `80` which is higher than `14`. If you set it to 14 or lower, then the code runs with no problems.

Please confirm that this works for you and that you're not facing this error with the files that have  1000 frames.

**Comment by epnev** [comment]
This commit cd93c77 should deal with the problem. However, to me, the problem only occurs when the first file in the list of files is shorter than the value of `opts.motion['num_frames_split']`. I'm not making a new release for this but you can incorporate it in your code if you want.

**Comment by HoniSanders** [comment]
I see, thank you very much for your help.
