### ISSUE TITLE
cnm.save() issue

### ISSUE THREAD

**Issue by donglabimaging** [flatironinstitute/CaImAn#673]
Windows 10 Jupyter Notebook

- **Describe the issue that you are experiencing**
We modify the demo_pipeline_cnmfE to run our analysis.  We are experiencing similar issue as #427.   It does not happen all the time.  It only happens for certain imaging files.

- **Copy error log below**
ValueError                                Traceback (most recent call last)
<ipython-input-48-e0418046cd1e> in <module>
----> 1 cnm.save('28M_Day7_ImageJ_DS.hdf5')

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in save(self, filename)
    663 
    664         if '.hdf5' in filename:
--> 665             save_dict_to_hdf5(self.__dict__, filename)
    666         else:
    667             raise Exception("Filename not supported")

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\utils.py in save_dict_to_hdf5(dic, filename, subdir)
    371 
    372     with h5py.File(filename, 'w') as h5file:
--> 373         recursively_save_dict_contents_to_group(h5file, subdir, dic)
    374 
    375 def load_dict_from_hdf5(filename:str) -> Dict:

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    458             h5file[path + key] = np.array(item)
    459         elif type(item).__name__ in ['CNMFParams', 'Estimates']: #  parameter object
--> 460             recursively_save_dict_contents_to_group(h5file, path + key + '/', item.__dict__)
    461         else:
    462             raise ValueError("Cannot save %s type for key '%s'." % (type(item), key))

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    440                 h5file[path + key] = item
    441             if not np.array_equal(h5file[path + key].value, item):
--> 442                 raise ValueError('The data representation in the HDF5 file does not match the original dict.')
    443         # save dictionaries
    444         elif isinstance(item, dict):

ValueError: The data representation in the HDF5 file does not match the original dict.

**Comment by epnev** [comment]
@donglabimaging What's your version of CaImAn?

**Comment by epnev** [comment]
@donglabimaging 
Please follow the procedure below so I can understand better where the saving fails:
1. Go to '~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\utils.py' and change line 442 from
`raise ValueError('The data representation in the HDF5 file does not match the original dict.')`
to 
`raise ValueError('Error while saving {}'.format(key))`
2. Relaunch python and reproduce the error
3. Paste the error log

**Comment by donglabimaging** [comment]
@epnev Thank you for the suggestion.  I will reproduce the error and post the error log tomorrow.

**Comment by donglabimaging** [comment]
@epnev Here is the error log. 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-43066b76a4d4> in <module>
----> 1 cnm.save(name + '_fr5.hdf5')

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in save(self, filename)
    663 
    664         if '.hdf5' in filename:
--> 665             save_dict_to_hdf5(self.__dict__, filename)
    666         else:
    667             raise Exception("Filename not supported")

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\utils.py in save_dict_to_hdf5(dic, filename, subdir)
    371 
    372     with h5py.File(filename, 'w') as h5file:
--> 373         recursively_save_dict_contents_to_group(h5file, subdir, dic)
    374 
    375 def load_dict_from_hdf5(filename:str) -> Dict:

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    458             h5file[path + key] = np.array(item)
    459         elif type(item).__name__ in ['CNMFParams', 'Estimates']: #  parameter object
--> 460             recursively_save_dict_contents_to_group(h5file, path + key + '/', item.__dict__)
    461         else:
    462             raise ValueError("Cannot save %s type for key '%s'." % (type(item), key))

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    440                 h5file[path + key] = item
    441             if not np.array_equal(h5file[path + key].value, item):
--> 442                 raise ValueError('Error while saving {}'.format(key))
    443         # save dictionaries
    444         elif isinstance(item, dict):

ValueError: Error while saving r_values

**Comment by epnev** [comment]
@donglabimaging Thanks, can you tell me what the value of `cnm.estimates.r_values` is?

**Comment by epnev** [comment]
@donglabimaging No, this is helpful thanks. I'm wondering whether the existence of the NaN value causes the problems. Can you run the following command:
```
cnm.estimates.r_values = np.where(np.isnan(cnm.estimates.r_values), -1, cnm.estimates.r_values)
```
and then try to save the object again. Does that work?

**Comment by donglabimaging** [comment]
It worked!  Thank you!

Mind if I ask why is there a NaN instead of 0?

**Comment by epnev** [comment]
Great! It's a good question why this happened; I don't have an immediate answer. 
I'll need to look into this a bit and will provide a fix. Thanks for reporting

**Comment by donglabimaging** [comment]
Sounds good.  Thanks again for the prompt response!  I really appreciate your help!!
