### ISSUE TITLE
Unable launch jupyter notebook

### ISSUE THREAD

**Issue by mtugsbayar** [flatironinstitute/CaImAn#674]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux 
 2. Python version (3.x): 
 3.7.1
 3. Working environment (Python IDE/Jupyter Notebook/other):
 AWS EC2 instance, connecting through PuTTY
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 1.7
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e .
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Unable to launch Jupyter notebook instance to run demos.

- **Copy error log below**
[C 22:34:50.623 NotebookApp] Bad config encountered during initialization:
[C 22:34:50.623 NotebookApp] The 'kernel_spec_manager_class' trait of <notebook.notebookapp.NotebookApp object at 0x7f5541ca1978> instance must be a type, but 'environment_kernels.EnvironmentKernelSpecManager' could not be imported

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@mtugsbayar It's not clear whether this is a caiman related issue. Can you launch jupyter notebooks in AWS in different Python environments?

**Comment by mtugsbayar** [comment]
I can. That particular error only shows up in the caiman environment.

**Comment by pgunn** [comment]
Hi,
I've googled this a bit; here are a few commands I'd like you to run (separately) from within your caiman environment and let me know the result of each:

- which jupyter
- conda list | grep jupyter
- conda list | grep ipykern

**Comment by mtugsbayar** [comment]
Hello, sorry for the delay!

- which jupyter: /home/ubuntu/anaconda3/envs/caiman/bin/jupyter

- conda list | grep jupyter
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge

-conda list | grep ipykern

ipykernel                 4.10.0                   py37_0

-jupyter --paths

config:
    /home/ubuntu/.jupyter
    /home/ubuntu/anaconda3/envs/caiman/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/ubuntu/.local/share/jupyter
    /home/ubuntu/anaconda3/envs/caiman/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/ubuntu/.local/share/jupyter/runtime

**Comment by pgunn** [comment]
This may affect a number of other things, but in that environment let's try upgrading ipykernel.

Enter the environment, and do:
```
conda install -c conda-forge ipykernel=5.1.3
```

**Comment by mtugsbayar** [comment]
I upgraded ipykernel. It still throws the same error.

**Comment by pgunn** [comment]
The big difference I see between our environments is the version of jupyter_core.
Let's see if downgrading helps you at all.

```
conda install -c conda-forge jupyter_core=4.5.0
```

**Comment by mtugsbayar** [comment]
Same as before. Here's what the environment looks like now:
           
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge

I'm kind of confused about the third column. Is the build string supposed to look like this?

**Comment by pgunn** [comment]
Conda has a lot of variety in build strings, but those match my local environment (which works) exactly.

Could you give this a try?
https://github.com/Cadair/jupyter_environment_kernels/issues/33#issuecomment-463805975

**Comment by mtugsbayar** [comment]
Ah, I see. I think that specific fix is for an old version, but I think I'm having more of a problem with jupyter than how the caiman environment was set up. I'll look into this from the jupyter side. Thank you!
