### ISSUE TITLE
What exactly does the object estimates.S?

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [flatironinstitute/CaImAn#676]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): macOS
 
 2. Python version (3.x): 3.6
 
 3. Working environment (Python IDE/Jupyter Notebook/other):Spyder
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

With the object estimates.S I get returned a numpy array with the dimensions [accepted components, time steps] but I don't understand what is the exactly meaning of the values within the array, considering that there are also negative values. In the webpage https://caiman.readthedocs.io/en/master/Getting_Started.html#component-evaluation I found estimates.S= Deconvolved neural activity (spikes) for each component.... Is really the number of spikes? or it is just a way of expressing the mean fluorescence of each component within each time frame?
Thank you very much for your help!

**Comment by epnev** [comment]
@sofiapuvogelvittini `S` is an estimate that is roughly proportional to the actual spiking activity of each neuron. Exact number of spikes is very hard to get without having a measure of what increase in fluorescence each spike induces. 

The best you can do is extract DF/F values (through `estimates.detrend_df_f`) and then deconvolve this, using [`estimates.deconvolve`](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/source_extraction/cnmf/estimates.py#L1084) and setting `dff_flag=True`. This will give you deconvolved activity with respect to relative fluorescence which you might be able to relate to firing rates.

**Comment by sofiapuvogelvittini** [comment]
Thank you for your help!
But I have another issue, when I create the DF/F values it returns a
"nontype objects of builtins module"... I can't view it.
Kind regards,
Sofía

**Comment by epnev** [comment]
As I wrote above, you have to first compute the DF/F values using `estimates.detrend_df_f`. Consult some demos.
