### ISSUE TITLE
I need help with a video with 4x4 binning.

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [flatironinstitute/CaImAn#685]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): mac=S
 
 2. Python version (3.x): 3.6
 
 3. Working environment (Python IDE/Jupyter Notebook/other):Spyder
 
 4. Which of the demo scripts you're using for your analysis (if applicable): caiman tutorail for 1 photon data.
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda):  conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**
I have been analyzing mi videos (tiff stacks) which  I have recorded with 2x2 binning  and I got very good results keeping the parameters suggested by the tutorial. But then I wanted to obtain videos that last longer so I did records with 4x4 binning and I don't know if I can maintain the parameters with this modification (like the gSig and gSiz )
Could you help me with this?
Kind regards!
Sofía

**Comment by epnev** [comment]
@sofiapuvogelvittini I'm not sure I understand what you mean by binning. If you mean spatial downsampling, then you would have to adjust the parameters accordingly. `gSig` should be roughly equal to the radius of a neuron *after* downsampling, and `gSiz` should be roughly an odd number roughly double than that.

**Comment by sofiapuvogelvittini** [comment]
Thank you very much for your reply. Yes, I meant spatial downsampling.
Is there any correction that i should do to motion correction algorithm
too? like to the gSig_filt = (3, 3)?
Kind regards, thank you!
Sofía

**Comment by sofiapuvogelvittini** [comment]
Thank you very much for your help!
