### ISSUE TITLE
Photo bleaching

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [flatironinstitute/CaImAn#688]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): macOS
 
 2. Python version (3.x): 3.6
 
 3. Working environment (Python IDE/Jupyter Notebook/other):Spyder
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**
I am working with long duration videos of one photon data, therefore I see the effect of bleaching in my photos. Is there any function within the program that can help me with this problem?
Greetings and thank you very much for your help.

**Comment by epnev** [comment]
@sofiapuvogelvittini The `estimates` object has the [`detrend_df_f`](https://caiman.readthedocs.io/en/master/core_functions.html#caiman.source_extraction.cnmf.estimates.Estimates.detrend_df_f) method that removes the drift from each trace as a postprocessing step. For an example on how you call it see [here](https://github.com/flatironinstitute/CaImAn/blob/master/demos/general/demo_pipeline.py#L251). If you want to just remove the drift (and not normalize) you can set the flag `detrend_only` flag to `True` when calling it.

**Comment by sofiapuvogelvittini** [comment]
Thank you very much!
