### ISSUE TITLE
Cannot install caimanmanager.py

### ISSUE THREAD

**Issue by hoseon-an** [flatironinstitute/CaImAn#691]
I use windows, python version is 3.7
I tried to install caimanmanager for 2 days. But I could not succeess.
I tried to install and uninstall both of caiman and anaconda.
![1](https://user-images.githubusercontent.com/59821084/72409848-4502c980-37aa-11ea-85df-d3e3b706a563.jpg)
![2](https://user-images.githubusercontent.com/59821084/72409850-4502c980-37aa-11ea-9e05-570c835dbcb5.jpg)
![3](https://user-images.githubusercontent.com/59821084/72409911-6a8fd300-37aa-11ea-8502-f3c3dff77e95.jpg)

Here are my working environment and error messages

And these are error logs:
(caiman) C:\Users\USER\CaImAn>caimanmanager.py check
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.decomposition.incremental_pca module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "C:\Users\USER\CaImAn\caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
  File "C:\Users\USER\CaImAn\caiman\__init__.py", line 4, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "C:\Users\USER\CaImAn\caiman\base\movies.py", line 62, in <module>
    from ..utils import visualization
  File "C:\Users\USER\CaImAn\caiman\utils\visualization.py", line 37, in <module>
    from ..summary_images import local_correlations
  File "C:\Users\USER\CaImAn\caiman\summary_images.py", line 23, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
  File "C:\Users\USER\CaImAn\caiman\source_extraction\cnmf\__init__.py", line 12, in <module>
    from . import oasis
ImportError: cannot import name 'oasis'

**Comment by epnev** [comment]
@hoseon-an Did you install using the caiman conda-forge package?
If the answer is no, then did you run `pip install .` prior to installing caimanmanager?

**Comment by hoseon-an** [comment]
> @hoseon-an Did you install using the caiman conda-forge package?
> If the answer is no, then did you run `pip install .` prior to installing caimanmanager?

Thank you. I solved it. But I have another problem.
