### ISSUE TITLE
Trouble using fit_next 

### ISSUE THREAD

**Issue by morganemoss** [flatironinstitute/CaImAn#692]
We are trying to use the OnACID function fit_next in a jupyter notebook. Caiman version is 1.7.1

We are first doing onAcid to a 1000-frame tif stack. the dimensions are 512 x 512 and we dont do any spatial subsampling.

```
fnames = [os.path.join(fpath, dirlist[i]) for i in range(len(dirlist)) if dirlist[i].endswith(".tif")]
fr = 30                                                             # frame rate (Hz)
decay_time = 0.4                                                    # approximate length of transient event in seconds
gSig = (14, 14)                                                        # expected half size of neurons
p = 1                                                               # order of AR indicator dynamics
min_SNR = 2.5                                                         # minimum SNR for accepting new components
rval_thr = 0.4                                                     # correlation threshold for new component inclusion
ds_factor = 1                                                       # spatial downsampling factor (increases speed but may lose some fine structure)
gnb = 2                                                             # number of background components
gSig = tuple(np.ceil(np.array(gSig)/ds_factor).astype('int'))       # recompute gSig if downsampling is involved
mot_corr = True                                                     # flag for online motion correction 
pw_rigid = True #False                                                    # flag for pw-rigid motion correction (slower but potentially more accurate)
max_shifts_online = np.ceil(10./ds_factor).astype('int')            # maximum allowed shift during motion correction
sniper_mode = True                                                  # flag using a CNN to detect new neurons (o/w space correlation is used)
init_batch = 200                                                    # number of frames for initialization (presumably from the first file)
expected_comps = 500                                                # maximum number of expected components used for memory pre-allocation (exaggerate here)
dist_shape_update = True                                            # flag for updating shapes in a distributed way
min_num_trial = 10                                                  # number of candidate components per frame     
K = 6                                                               # initial number of components
epochs = 1                                                          # number of passes over the data
show_movie = False                                                  # show the movie with the results as the data gets processed
rf = 45
ssub = 1 #2
tsub = 3 #2
thresh_cnn_noisy = 0.8
stride = 28
merge_thr = 0.9                                                     # merge components if correlation is more than this
SNR_lowest = 2.5
rval_thr = 0.7
rval_lowest = 0.7
min_cnn_thr = 0.99
cnn_lowest = 0.4

# to match SNR, cnn, r masks from cnmf, copy them to _lowest vars 

params_dict = {'fnames': fnames,
               'fr': fr,
               'decay_time': decay_time,
               'gSig': gSig,
               'p': p,
               'stride': stride,
               'min_SNR': min_SNR,
               'rval_thr': rval_thr,
               'ds_factor': ds_factor,
               'nb': gnb,
               'motion_correct': mot_corr,
               'init_batch': init_batch,
               'thresh_CNN_noisy': thresh_cnn_noisy,
               'init_method': 'bare',
               'normalize': True,
               'expected_comps': expected_comps,
               'sniper_mode': sniper_mode,
               'dist_shape_update' : dist_shape_update,
               'min_num_trial': min_num_trial,
               'K': K,
               'rf': rf,
               'merge_thr': merge_thr,
               'ds_factor': ssub,
               'tsub': tsub,
               'epochs': epochs,
               'max_shifts_online': max_shifts_online,
               'pw_rigid': pw_rigid,
               'min_SNR': min_SNR,
               'SNR_lowest': SNR_lowest,
               'rval_lowest': rval_lowest,
               'rval_thr': rval_thr,
               'min_cnn_thr': min_cnn_thr,
               'cnn_lowest': cnn_lowest,
               'show_movie': show_movie
                }

opts = cnmf.params.CNMFParams(params_dict=params_dict)
 
cnm = cnmf.online_cnmf.OnACID(params=opts)
timestart = time()
cnm.fit_online()
timetaken = time() - timestart
print(timetaken)
```

No errors so far, as far as we can tell cnm now exists and contains all the estimates etc. Next we load a new frame, this is a single tif file. When we reshape the frame with this code: 

```
frame = plt.imread(r'D:\path\frame_1001.tif')
cnm.fit_next(1, frame.reshape(-1, order='F'))
```

We get this error:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-18-92a5aca8462f> in <module>
>       3 # frame = plt.imread(r'D:\path\frame_1001.tif')
>       4 # frame_reshape = np.reshape(frame, (262144,))
> ----> 5 cnm.fit_next(1, frame.reshape(-1, order='F'))
> 
> C:\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in fit_next(self, t, frame_in, num_iters_hals)
>     431                     o.fit_next(self.estimates.noisyC[nb_ + i, t])
>     432                     self.estimates.C_on[nb_ + i, t - o.get_l_of_last_pool() +
> --> 433                               1: t + 1] = o.get_c_of_last_pool()
>     434 
>     435         else:
> 
> ValueError: could not broadcast input array from shape (123) into shape (0)

When we don't reshape, we get this error: 

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-7-6dae67a54aa9> in <module>
>       3 frame = plt.imread(r'D:\Morgane\test_videos\190925\NVI16\D0\im\baseline\baseline_190925T204017-021\baseline_190925T204017-021_Cycle00001_Ch2_000299.ome.tif')
>       4 #frame_reshape = np.reshape(frame, (262144))
> ----> 5 cnm.fit_next(1, frame)
> 
> C:\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in fit_next(self, t, frame_in, num_iters_hals)
>     410         frame = frame_in.astype(np.float32)
>     411 #       print(np.max(1/scipy.sparse.linalg.norm(self.estimates.Ab,axis = 0)))
> --> 412         self.estimates.Yr_buf.append(frame)
>     413         if len(self.estimates.ind_new) > 0:
>     414             self.estimates.mean_buff = self.estimates.Yres_buf.mean(0)
> 
> C:\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in append(self, x)
>    1900 
>    1901     def append(self, x):
> -> 1902         self[self.cur] = x
>    1903         self.cur = (self.cur + 1) % self.max_
>    1904 
> 
> ValueError: could not broadcast input array from shape (512,512) into shape (262144)

Weirdly, when we re-run the command with reshaping, shape (123) increases to (124), (127) and so forth each time. 
We aren't sure where we are going wrong, so we appreciate any insight.

**Comment by epnev** [comment]
@morganemoss You're running things in a non-standard way so I don't know whether I'll be able to help. There could various things going on here. For example, the algorithm reads the specified list of files to be processed and pre-allocates some matrices based on the total length of these files. Adding an additional file after that might lead to issues.

I'd recommend not using single frame files, but if you want/have to, try to pass them as inputs in the params object when you specify the various parameters ('fnames') and run the `fit_online` method as intended. Let me know if that helps.
