### ISSUE TITLE
Anaconda doesn't support the scikit-learn (version > 0.22)

### ISSUE THREAD

**Issue by hoseon-an** [flatironinstitute/CaImAn#693]
- **Tell us a bit about your setup**: 

 Windows / python 3.8 / Anaconda jupyer notebook
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 The lastest version.

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e.

- **Describe the issue that you are experiencing**
Anaconda support just scikit-learn 0.22 version.
I installed the sklearn 0.23 version, but conda doesn't support this.
So, 0.22 version deprecated caiman.
How can I solve this problem??

- **Copy error log below**

C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.decomposition.incremental_pca module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\USER\Anaconda3\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

**Comment by epnev** [comment]
Anaconda will support version 0.23 in the future so you'll be able to use it. Also in our environment file we specify python 3.7 so we cannot support any installations with python 3.8 at this point.
Please stick to the versions supported by anaconda and specified by the caiman environment.
