### ISSUE TITLE
Problem installing Caiman on Windows with package-based process

### ISSUE THREAD

**Issue by vickerse1** [flatironinstitute/CaImAn#694]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows 7
 
 2. Python version (3.x): 3.6.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Anaconda prompt, Windows
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

I followed the instructions at: https://caiman.readthedocs.io/en/master/Installation.html. When I get to this step:

"Once CaImAn is installed, you may want to get a working directory with code samples and datasets; pip installed a caimanmanager.py command that manages this. If you have not installed Caiman before, you can do

caimanmanager.py install if you used the conda-forge package"

....it says Windows doesn't know which program to use. If I type "python caimanmanager.py install", I get an error message.

Do I need to be in a particular directory to run the caimanmanager.py install command? Which one? I am in the caiman environment already......?

Perhaps there is a step missing in the instructions?

Thanks,

Evan

the error message looks something like this:

C:\ProgramData\Anaconda3\envs\caiman\lib\site-packa
.py:144: FutureWarning: The sklearn.decomposition.i
recated in version 0.22 and will be removed in vers
lasses / functions should instead be imported from
ng that cannot be imported from sklearn.decompositi
 API.
  warnings.warn(message, FutureWarning)
Traceback (most recent call last):
  File "caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\si
y", line 4, in <module>
    from .base.movies import movie, load, load_movi
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\si
s.py", line 45, in <module>
    from . import timeseries
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\si
eries.py", line 22, in <module>
    from pynwb import NWBHDF5IO, NWBFile
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\si
", line 244, in <module>
    from . import legacy  # noqa: F401,E402
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\si
it__.py", line 3, in <module>
    from .map import ObjectMapperLegacy as ObjectMa
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\si
py", line 2, in <module>
    from hdmf.build.map import ObjectMapper, TypeMa
ImportError: cannot import name 'ObjectMapper'

- **Copy error log below**

Once CaImAn is installed, you may want to get a working directory with code samples and datasets; pip installed a caimanmanager.py command that manages this. If you have not installed Caiman before, you can do

caimanmanager.py install if you used the conda-forge package

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@vickerse1 
I think caiman was installed fine but your installation includes a bad build of the `hdmf` package. See here: https://github.com/NeurodataWithoutBorders/pynwb/issues/1134
I believe typing in the anaconda prompt (from your caiman environment)
``` conda install hdmf=1.3.3 -c conda-forge``` 
should fix the issue.
