### ISSUE TITLE
Error when using new tiff stack file in motion correction demo

### ISSUE THREAD

**Issue by jjkowalewski** [flatironinstitute/CaImAn#695]
- **Set up**
 1. Operating system Windows 10 
 
 2. Python version (3.7.3)
 
 3. Working environment: Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): The motion_correction Jupyter notebook
 
 5. CaImAn version*: 1.7.1
 
 6. CaImAn installation process: conda forge

- **Describe the issue that you are experiencing**
The demo file (Sue_2x_3000_40_-46.tif) works fine in the motion correction Jupyter notebook for me; however, loading a new tiff stack file results in an index error.

This motion correction will start and then an error arises shortly after the following output: motion_correction.py:motion_correction_piecewise():3004] [16692] ** Starting parallel motion correction **

The new .tiff file is roughly half the size of the sample (in mb) and is only 20 frames. It is 16-bit vs 32 bit. So something in the parameters may need altering. I just can't determine what the expected input should be or to modify the file appropriately.

- **Copy error log below**
The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-36-34dd55e270b5> in <module>
      1 # correct for rigid motion correction and save the file (in memory mapped form)
----> 2 mc.motion_correct(save_movie=True)

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct(self, template, save_movie)
    252                                     np.max(np.abs(self.y_shifts_els))))
    253         else:
--> 254             self.motion_correct_rigid(template=template, save_movie=save_movie)
    255             b0 = np.ceil(np.max(np.abs(self.shifts_rig)))
    256         self.border_to_0 = b0.astype(np.int)

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_rigid(self, template, save_movie)
    303                 var_name_hdf5=self.var_name_hdf5,
    304                 is3D=self.is3D,
--> 305                 indices=self.indices)
    306             if template is None:
    307                 self.total_template_rig = _total_template_rig

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correct_batch_rigid(fname, max_shifts, dview, splits, num_splits_to_process, num_iter, template, shifts_opencv, save_movie_rigid, add_to_movie, nonneg_movie, gSig_filt, subidx, use_cuda, border_nan, var_name_hdf5, is3D, indices)
   2713                                                              num_splits=num_splits_to_process, shifts_opencv=shifts_opencv, nonneg_movie=nonneg_movie, gSig_filt=gSig_filt,
   2714                                                              use_cuda=use_cuda, border_nan=border_nan, var_name_hdf5=var_name_hdf5, is3D=is3D,
-> 2715                                                              indices=indices)
   2716         if is3D:
   2717             new_templ = np.nanmedian(np.stack([r[-1] for r in res_rig]), 0)

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\motion_correction.py in motion_correction_piecewise(fname, splits, strides, overlaps, add_to_movie, template, max_shifts, max_deviation_rigid, newoverlaps, newstrides, upsample_factor_grid, order, dview, save_movie, base_name, subidx, num_splits, shifts_opencv, nonneg_movie, gSig_filt, use_cuda, border_nan, var_name_hdf5, is3D, indices)
   3007             dview.map(close_cuda_process, range(len(pars)))
   3008         elif 'multiprocessing' in str(type(dview)):
-> 3009             res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)
   3010         else:
   3011             res = dview.map_sync(tile_and_correct_wrapper, pars)

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\multiprocessing\pool.py in get(self, timeout)
    668             return self._value
    669         else:
--> 670             raise self._value
    671 
    672     def _set(self, i, obj):

IndexError: too many indices for array

**Comment by epnev** [comment]
@jjkowalewski This could be because your stack is too short and related to #672
What is the value of `opts.motion`?

**Comment by jjkowalewski** [comment]
These are the parameters that were set, below. Everything would be the default settings in params.py.  I went ahead and changed the number of frames per split, which seemed to be the likely cause, however I still got the same error.  I tried again with the other demos, all of which worked. So it must be specific to the file. 

max_shifts = (6, 6)  # maximum allowed rigid shift in pixels (view the movie to get a sense of motion)
strides =  (48, 48)  # create a new patch every x pixels for pw-rigid correction
overlaps = (24, 24)  # overlap between pathes (size of patch strides+overlaps)
**num_frames_split = 5**  # lowered to less than the total number of frames. This was 100
max_deviation_rigid = 3   # maximum deviation allowed for patch with respect to rigid shifts
pw_rigid = False  # flag for performing rigid or piecewise rigid motion correction
shifts_opencv = True  # flag for correcting motion using bicubic interpolation (otherwise FFT interpolation is used)
border_nan = 'copy'  

I've included the file. I significantly decreased the size here from the original (~1000 x 1000 pixels) but the size doesn't affect the error. 

[Sample.tif.gz](https://github.com/flatironinstitute/CaImAn/files/4081266/Sample.tif.gz)

**Comment by epnev** [comment]
@jjkowalewski Thanks, I figured out what's happening. Basically it's the same bug as before. The reason that it appeared now is that you run the motion_correction notebook which uses the old way to pass the parameters inside the motion correction object. As a result the `num_frames_split` argument does not affect the parameters. 

To fix the problem you will need to pass the additional parameter `splits_rig` (and `split_els` for piecewise rigid motion correction) when you construct the object and set to a value equal to 10 or lower (i.e., at most half the number of frames - the default value is 14). 

When you run the `demo_pipeline` notebook, then the parameter setting is happening through the `CNMFParams` object which takes care of this condition automatically.

**Comment by jjkowalewski** [comment]
Thank you. I was able to successfully run the demo with a new file. But the motion correction demo does not provide an example for simply exporting the motion correction files at the end. Would this be the same as in the pipeline notebook or is this different as well? Appreciate your help.

**Comment by epnev** [comment]
@jjkowalewski As long as you called the motion correct with the flag `save_movie` set to `True`
```python
mc.motion_correct(save_movie=True)
```
the movie will be exported in the location specified by `mc.mmap_file`. This will be in memory mapped format, but you can load it and re-save it in a different format, if that's what you're after.
