### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by SophiePinder** [flatironinstitute/CaImAn#698]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux): 
 
 2. Python version (3.x): 
 
 3. Working environment (Python IDE/Jupyter Notebook/other): iPython
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_pipeline_cnmfE
 5. CaImAn version*: 
 latest
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
i'm trying to go through the demo, when i run the below code i get the following error
fnames = ['data_endoscope.tif']  # filename to be processed
fnames = [download_demo(fnames[0])]

- **Copy error log below**
xception                                 Traceback (most recent call last)
<ipython-input-3-71594e46ba8e> in <module>
      1 fnames = ['data_endoscope.tif']  # filename to be processed
----> 2 fnames = [download_demo(fnames[0])]

~/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/utils/utils.py in download_demo(name, save_folder)
    114             logging.info("File " + str(name) + " already downloaded")
    115     else:
--> 116         raise Exception('Cannot find the example_movies folder in your caiman_datadir - did you make one with caimanmanager.py?')
    117     return path_movie
    118 

Exception: Cannot find the example_movies folder in your caiman_datadir - did you make one with caimanmanager.py?

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@SophiePinder You most likely did not set up `caimanmanager` so the installation is incomplete. See the [instructions](https://caiman.readthedocs.io/en/master/Installation.html#setting-up-caimanmanager) on how to do it.

**Comment by epnev** [comment]
@SophiePinder I assume your issue is fixed, but please let us know if otherwise.
