### ISSUE TITLE
Bokeh interactive plot not displaying in notebook

### ISSUE THREAD

**Issue by alimoges42** [flatironinstitute/CaImAn#699]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Windows 

 2. Python version (3.x): 
 Python 3.7.3

 3. Working environment (Python IDE/Jupyter Notebook/other):
Jupyter notebook in caiman environment 

 4. Which of the demo scripts you're using for your analysis (if applicable):
N/A

 5. CaImAn version*: 
1.6.3 

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda forge

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I'm analyzing endoscopic videos and am not getting the Bokeh interactive plot to appear in my notebook after running `cnm.estimates.plot_contours_nb(img=cn_filter, idx=cnm.estimates.idx_components)`. Instead, I get a statement that "Bokeh could not be loaded. Either it is not installed or you are not running within a notebook. Using non-interactive plot as fallback." Following this message, I get the logging output followed by a non-interactive plot of the accepted and rejected components. However, if I run a Bokeh demo script (i.e. one from the Bokeh doc site, not a caiman demo) I can get a Bokeh interactive plot to display in a notebook from the caiman environment, so I'm confused as to what is triggering that print statement. 

- **Copy error log below**
Bokeh could not be loaded. Either it is not installed or you are not running within a notebook
Using non-interactive plot as fallback

* I get a long logging printout, but it appears to all be related to Font Manager stuff and not related to the Bokeh plot. I can paste the printout if it's helpful, but at face value it doesn't look relevant or important to me.

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@alimoges42 Does the following work?
```python
from caiman.utils.visualization import nb_plot_contour
dims = cnm.estimates.dims
nb_plot_contour(cn_filter, cnm.estimates.A, dims[0], dims[1], coordinates=cnm.estimates.coordinates)
```

**Comment by alimoges42** [comment]
@epnev It throws a type error saying "None Type object is not subscriptable" because `cnm.estimates.dims` is None. But if I set `dims = cn_filter.shape` then it shows a figure, but there's no slider bar or anything (not sure if there's supposed to be a slider bar produced by this function though).

**Comment by epnev** [comment]
Are there any contours plotted?

**Comment by alimoges42** [comment]
Yes, contours get plotted but they are not numbered, so no way of knowing which is which

**Comment by epnev** [comment]
The reason it fails might be that `cnm.estimates.dims = None` (which is weird on its own). Try setting `cnm.estimates.dims = dims` and then repeat the original command:
```python
cnm.estimates.plot_contours_nb(img=cn_filter, idx=cnm.estimates.idx_components)
```
Does that work?

**Comment by alimoges42** [comment]
Ah that worked! And so do the holoviews sliderbar plots, which is great. I agree that it's weird that `cnm.estimates.dims` doesn't initialize with the appropriate values. Manually setting it isn't too much of a hassle though. 

If you want more info or have any idea why that could be happening on my machine let me know (not sure if it's been an issue for other users). Otherwise feel free to close the issue, as the current workaround seems easy enough.

Thanks again for the quick help!

**Comment by epnev** [comment]
Thanks. A fix will be available at the next release (basically the dimensions will be read from the background image if for some reason are not present) but I'll look to see why this is happening.
