### ISSUE TITLE
cannot load GUI

### ISSUE THREAD

**Issue by vickerse1** [flatironinstitute/CaImAn#700]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows 7
 
 2. Python version (3.x): 3.6.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Anaconda prompt
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_OnACID_mesoscope.py
 
 5. CaImAn version*: 1.7.1
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): package based

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Hello,
I successfully installed Caiman on Windows 7 with the package-based process, and was able to run the onACID mesoscope demo from a jupyter notebook. (it produced the output: MC_d1_440_d2_256_d3_1_order_F_frames_3000_.mmap)

However, when I attempt to load the GUI with the following command from your instructions:

ipython caiman/gui/gui_pyqtgraph_layout.py

I get this error:

ipython caiman/gui/gui_pyqtgraph_layout.py

I am in my caiman environment.

I have tried this from both the caiman directory:

ipython caiman/gui/gui_pyqtgraph_layout.py

and the caiman data directory:

C:\Users\scanimage\caiman_data

.....but I get the same error in both cases.

Am I in the wrong folder? Is there supposed to be a folder called "gui"? Do I need to update my version of Caiman to 1.8? Is 1.8 not available with package installation?

Thanks,

Evan

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@vickerse1 Can you put the actual error log? Right now you just copied the command.

@pgunn Can you take a look at this? It possible that the conda installation changes the location of the GUI

**Comment by pgunn** [comment]
Hi,
Right now the GUI is experimental and the package version of CaImAn does not include an easy way to run it. Future versions of the conda package may make this easier.

--Pat

**Comment by pgunn** [comment]
For right now, this is how you can launch the GUI:
1. Open a shell and activate your caiman environment
2. Find the path to your miniconda3 install (probably in your homedir).
3. Find, under that path, where the GUI is by doing the following command:
```dir /s C:\PATH\TO\MINICONDA\gui_pyqtgraph_layout.py```
(replacing PATH\TO\MINICONDA with the actual path
You will probably get two results; look at the one that has \envs\caiman\ as part of it
4. Launch that GUI by issuing the following command:
```python PATH\TO\gui_pyqtgraph_layout.py```

Let me know if you have any questions.

We have a plan to make this easier for future releases of the package.

**Comment by vickerse1** [comment]
Hi Pat,

It works! Thanks.

-Evan
________________________________

**Comment by epnev** [comment]
Great! 
@pgunn let me know when you fix this; we can make a new release - will leave this open until then.

**Comment by pgunn** [comment]
I'm working on the diff as we speak. Should have it ready today for review.

**Comment by epnev** [comment]
Fixed with v1.8.1 GUI is now located in the `caiman_data/bin folder` and has been renamed to `caiman_gui`.
