### ISSUE TITLE
90 degree rotation during "movie mode" in caiman_gui.py

### ISSUE THREAD

**Issue by bnstet** [flatironinstitute/CaImAn#706]
1. Operating system (Linux/macOS/Windows): 
 Linux
 2. Python version (3.x): 
 3.6.7
 3. Working environment (Python IDE/Jupyter Notebook/other):
 ipython
 4. Which of the demo scripts you're using for your analysis (if applicable):
 bin/caiman_gui.py
 5. CaImAn version*: 
 v1.8.1
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install .

- **Describe the issue that you are experiencing**
While running bin/caiman_gui.py via ipython, if you click on a neuron then you get a time series plot in the lower-center of the screen. If you drag the colored bar on this plot, the reconstructed movie plays above in the top-center, along with the source activity movie in the top-right. The reconstructed movie is however rotated 90 degrees counter-clockwise with respect to both the source activity movie and the static image shown when you launch the GUI or press "Show Neurons".

**Comment by j-friedrich** [comment]
Now fixed in dev and master branches.
