### ISSUE TITLE
register_multisession() taking lot of time

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#707]
1. Operating system (Linux/macOS/Windows): Windows 10
 
 2. Python version (3.x): Python 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Anaconda Jupyter
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_multisession_registration.ipynb
 
 5. CaImAn version*: 1.7.1
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
Using conda after installing Microsoft Build tools

- issue faced:
I am not sure if this is typical but i am using the demo_multisession_registration.ipynb to register 2 .avi files (each with dimensions (480,752,1000) -> (FOV_x,FOV_y, frames)) but even with only 2 files, it is taking a very long time to finish. Each .avi is around 340MB.

**Comment by j-friedrich** [comment]
register_multisession() is used to align the spatial footprints derived from the CNMF analysis of the same FOV over multiple sessions, not raw movies. 

Do you want to perform motion correction of the 2 files? Then please refer to demo_motion_correction.ipynb

**Comment by akatav** [comment]
@j-friedrich thank you. I have many .avi files, one for each session. MotionCorrect() returns an images array whose dims are (T,dims_x,dims_y) where T is the total number of frames of all .avi files. For the register_multi_sessions(), i take A=list(cnm.estimates.A), templates=list(cn_filter),dims=cn_filter.shape, where cn_filter is the correlation image. I do not think that the above parameter passing is correct. I also think that 'A' (spatial footprint) matrix contains components derived from all thr .avi files. It is not clear how to pass the components from many video recordings onto the register_multiple_sessions() method. Can you please help?
Can you please give an example of usi

**Comment by epnev** [comment]
@akatav It is not clear what you want to do. If you need to analyze a set some data that is temporally contiguous but split into multiple files, then you do not need to use any multi session registration. 

Multisession registration is used when you need to register the components you found from the analysis over two or more different sessions (for example days). In that case you can analyze each session separately (and each session can contain multiple files), and then take the spatial footprints from each session and pass them into the register multi session function. If you pass a list of files for motion correction, then it is implied that all these files contain recordings from the same session with the same FOV.
