### ISSUE TITLE
caimanmanager.py install windows simple issue.

### ISSUE THREAD

**Issue by DanePatey** [flatironinstitute/CaImAn#708]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows 10
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 1.8
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda):  conda install

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Simple issue, when using the caimanmanager.py install command, windows wants me to select how to open the file. None of the options seem like they will open the file.

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
Are you sure you're in the right conda environment when you're doing this? If so and it's still not working, you should be able to find the path to caimanmanager.py and say "python caimanmanager.py install" (although I expected Conda to handle all this for you).

**Comment by DanePatey** [comment]
Hi,
Thanks for the response, sorry for the late reply.  I'm fairly new to some
of these things.  I followed the instructions exactly as written.
I've tried to follow along with other debugging posts and made sure after
running "conda env list" the output was with an astrix next to the caiman
environment.  Then when trying the command "cainmanmanager.py install",
windows immediately pops up a window saying "How do you want to open this
program"
Thanks for you help.

**Comment by pgunn** [comment]
Can you send me the output of `conda info`?

**Comment by DanePatey** [comment]
active environment : caiman
    active env location : C:\Users\LiLab\.conda\envs\caiman
            shell level : 2
       user config file : C:\Users\LiLab\.condarc
 populated config files :
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\LiLab\.conda\pkgs
                          C:\Users\LiLab\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\LiLab\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\LiLab\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4
Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

**Comment by pgunn** [comment]
Try:

```python C:\Users\LiLab\.conda\envs\caiman\bin\caimanmanager.py install```

**Comment by DanePatey** [comment]
C:\Users\LiLab\.conda\envs\caiman\lib\site-packages\sklearn\utils\deprecation.py:144:
FutureWarning: The sklearn.decomposition.incremental_pca module is
 deprecated in version 0.22 and will be removed in version 0.24. The
corresponding classes / functions should instead be imported from
sklearn.decomposition. Anything that cannot be imported from
sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\LiLab\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:526:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\LiLab\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:527:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\LiLab\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:528:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\LiLab\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:529:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\LiLab\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:530:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\LiLab\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\dtypes.py:535:
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
deprecated; in a future version of numpy, it will be understood as (type,
(1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Installed C:\Users\LiLab\caiman_data

Was the output, so the last line looks like it was installed sucessfully,
but I am unsure of all the preceding lines.  Should I worry?
Thank you so much!

**Comment by pgunn** [comment]
No - those are all warnings to code maintainers and are harmless to users.

Have fun with Caiman.
