### ISSUE TITLE
Question about the accuracy of detecting cells

### ISSUE THREAD

**Issue by Ruyi-Yang** [flatironinstitute/CaImAn#710]
Hi, I have a question about the accuracy of detecting cells. I used CaImAn to detect cell automatically, and draw the picture with the boundary of neuron, I found that maybe it's not good sometimes. The file is a example.
So I want to know what's the  criterion of detecting cells, and what can I do to make it perform better, is there some parameters that I can adjust?
I'm not major in mathematics and can't understand the algorithm well, though the question maybe not    express clearly. I'm sorry for that.
![detect neuron](https://user-images.githubusercontent.com/50794031/74095955-428a5a00-4b33-11ea-8d72-aa08affeb1ec.png)

**Comment by agiovann** [comment]
Dear Ruyi, 

there are many parameters which could affect your detection. Chiefly, you want to consider the values in this section of the demo (https://github.com/flatironinstitute/CaImAn/blob/8427d974550db2c8218b1db5d51bd0f7a1eb1194/demos/general/demo_pipeline.py#L226) and you should also read the CaImAn paper in eLife (2019).  Let us know if you have further questions.

**Comment by Ruyi-Yang** [comment]
Ok, thank you very much for your reply. Also ask one more question, can give a few suggestions, such as whether I need to improve the criteria of minSNR, etc.

**Comment by epnev** [comment]
@Ruyi-Yang Yes, `minSNR` and all the parameters that pertain to the quality as shown there are relevant and can be tuned accordingly depending on your dataset.

**Comment by Ruyi-Yang** [comment]
Thank you for your reply. I have few questions, is that min_SNR determines the signal level of cell detected? And I wonder what rval_thr, cnn_thr, cnn_lowest mainly determine, is that will change  neuron's shape or something?
I‘m sorry the question is not professionally enough.
Best wishes!

**Comment by epnev** [comment]
The parameters will not change the shape of the neurons. They will only affect which components are accepted and which are not. See [here](https://caiman.readthedocs.io/en/master/Getting_Started.html#component-evaluation) for more details.
