### ISSUE TITLE
add psutil as a dependency

### ISSUE THREAD

**Issue by ajkswamy** [flatironinstitute/CaImAn#713]
1. Operating system (Linux/macOS/Windows): **Linux**

 2. Python version (3.x): **3.7.6**

 3. Working environment (Python IDE/Jupyter Notebook/other): **Pipenv/commandline**
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: **1.8.1**
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

`pip install -r requirements.txt;pip install -e ./`

- **Describe the issue that you are experiencing**
After installation as above, importing caiman/starting GUI complains:

> ModuleNotFoundError: No module named 'psutil'

- **Copy error log below**

- **If you're not reporting an error, type your message below**
Please add `psutil` to `requirements.txt`. Adding it to `environment.yml` may also be beneficial, in case miniconda does not come with `psutil` (not sure).

**Comment by pgunn** [comment]
Hello,
We may do this, but in the meantime please use the conda-based install.

**Comment by ajkswamy** [comment]
Hello pgunn

Thanks for the reply. I am a bit confused as I was able to install successfully caiman_data using `python caimanmanager.py install --inplace`, and `python caimanmanager.py test` said that all tests passed. Just to understand better, which components of caiman are not expected to work properly with a pure pip install?

**Comment by pgunn** [comment]
It's not that we believe tests will fail, but rather that using conda to manage dependencies (and optionally the install itself) is the install path that we provide support for. Users can be adventurous and install in other ways, but they might bump into surprises (as versions of dependent packages change in ways we might not notice) and if they hit issues we'll likely point them back in the direction of conda rather than debug with them.

**Comment by pgunn** [comment]
Adjusted in https://github.com/flatironinstitute/CaImAn/commit/efa65eb9625f06c3cc72e001c5c6c1cbba0c3b0a
(on the dev branch), will eventually make its way to the master branch.

**Comment by epnev** [comment]
@ajkswamy Thanks
@pgunn Miniconda does not come with `psutil` so it makes sense to add it to `environment.yml` as well.
