### ISSUE TITLE
mc.apply_shifts_movie: 'MotionCorrect' object has no attribute 'x_shifts_els'

### ISSUE THREAD

**Issue by obarnstedt** [flatironinstitute/CaImAn#714]
1. Operating system: Ubuntu 18.04.3 LTS
 2. Python version: 3.7
 3. Working environment: Bash / PyCharm
 5. CaImAn version: 1.6.2 / 1.8.1
 6. CaImAn installation process: pip / conda-forge

- **Describe the issue that you are experiencing**
After motion correcting a structural channel using
```
mc = MotionCorrect('Results_Imaging_Red_ds.h5', dview=dview, **opts.get_group('motion'))
border_to_0 = 0 if mc.border_nan is 'copy' else mc.border_to_0
mc.motion_correct(save_movie=True)
```
successfully resulting in a motion corrected file 'OB_161_red_d_rig__d1_680_d2_680_d3_1_order_F_frames_18000_.mmap',
I want to apply this motion correction to the GCaMP channel using
```
mc.apply_shifts_movie('Results_Imaging_Green_ds.h5',
                              save_memmap=True, order='C', rigid_shifts=not opts_dict['pw_rigid'],
                              save_base_name='_green_memmap'))
```
- **Copy error log below**
```
WARNING:root:The rigid_shifts flag is deprecated and it is being ignored. The value is read directly from mc.pw_rigid and is current set to the opposite of 0.0
Traceback (most recent call last):
  File "init_caiman.py", line 307, in <module>
    save_base_name='_green_memmap'))
  File "/home/oliver/anaconda3/envs/caiman2/lib/python3.7/site-packages/caiman/motion_correction.py", line 444, in apply_shifts_movie
    np.float32) for _sh_ in self.x_shifts_els], axis=0)
AttributeError: 'MotionCorrect' object has no attribute 'x_shifts_els'
```
I experienced this problem with 1.6.1 and 1.8.2, tried with and without rigid_shifts parameter. This is working fine with pw_rigid registered files, but keeps resulting in the error message above with rigid motion correction.
Any help is appreciated!
Thanks,
Oliver

**Comment by pgunn** [comment]
I'm digging into this a little bit - this should have been gated on self.pw_rigid, but looking at the errors above, this is suspicious:

```WARNING:root:The rigid_shifts flag is deprecated and it is being ignored. The value is read directly from mc.pw_rigid and is current set to the opposite of 0.0```

0.0 is a surprising value for self.pw_rigid as that's supposed to be a boolean; I suspect that's leading this gating inside MotionCorrect.apply_shifts_movie():

```if self.pw_rigid is False:```
to go down the wrong code path. A la:

```
>>> foo = 0.0
>>> if foo is False:
...     print("Heya")
... else:
...     print("Nope")
... 
Nope
```

It's not clear to me where self.pw_rigid is set to float(0.0); poking around the code doesn't provide an immediate culprit. I wonder if this is from a serialisation/desearlisation of the MotionCorrect object, as a number of serialisers don't have good bool types.

**Comment by pgunn** [comment]
@obarnstedt Would you be comfortable making a small change to your installed CaImAn to see if it fixes the issue? If so, please edit:

/home/oliver/anaconda3/envs/caiman2/lib/python3.7/site-packages/caiman/motion_correction.py
and go to the __init__ function, changing this line:
```
self.pw_rigid = pw_rigid
```

to the following:
```
self.pw_rigid = bool(pw_rigid)
```

(please preserve the indentation and so on).

This *may* fix the problem. If it does, please let us know.

**Comment by epnev** [comment]
@obarnstedt What is the value of `mc.pw_rigid` when you're trying to apply rigid shifts? It should be `False` otherwise it would try to read piecewise rigid shifts that apparently are not there.

**Comment by obarnstedt** [comment]
Hi and thanks for the quick reply!
As @pgunn pointed out, the value was indeed `0.0`, weirdly parsed with Pandas from an Excel cell that contained `FALSE`, and then passed on to the opts_dict. So changing this to `False` indeed solved the problem. I guess `self.pw_rigid = bool(pw_rigid)` might be more fool-proof in a future release.
Thanks!

**Comment by pgunn** [comment]
Let's leave this open until we've fixed it in at least the dev branch.

**Comment by pgunn** [comment]
Looks like this kind of thing is not unknown when people are using Pandas/excel glue - apparently there are a lot of things people need to pay attention to to avoid danger.

https://stackoverflow.com/questions/51661980/pandas-read-excel-sometimes-incorrectly-reads-boolean-values-as-1s-0s

**Comment by pgunn** [comment]
The above commit should hopefully address the immediate issue. It'd be nice if Python were more strongly typed.
