### ISSUE TITLE
Question of SNR

### ISSUE THREAD

**Issue by Ruyi-Yang** [flatironinstitute/CaImAn#715]
Hi, I wonder what the relationship between min_SNR and container.estimates.SNR_comp. 
I adjusted the parameter of min_SNR to 2.0 when evaluating the components, but for some components, I got the SNR below 2.0, some even below 0.8, from container.estimates.SNR_comp. So I also want to know what can I do to rejected these components when evaluating components.
Thank you !

**Comment by epnev** [comment]
Once you change the parameter you would need to run the `estimates.evaluate_components` method (or the [`estimates.filter_components`](https://caiman.readthedocs.io/en/master/core_functions.html#caiman.source_extraction.cnmf.estimates.Estimates.filter_components) method to just update the allocation instead of computing it from scratch) again so it can take effect.

**Comment by Ruyi-Yang** [comment]
Thanks for your reply. 
I update the parameter, after that, I also find few components. Their SNR also below the min_SNR. 
I want to know if there is a way to see the specific parameters used by the results.







At 2020-02-24 00:49:47, "eftychios pnevmatikakis" <notifications@github.com> wrote:

Once you change the parameter you would need to run the estimates.evaluate_components method (or the estimates.filter_components method to just update the allocation instead of computing it from scratch) again so it can take effect.

**Comment by Ruyi-Yang** [comment]
Thanks for your reply. 
I update the parameter, after that, I also find few components. Their SNR also below the min_SNR. 
I want to know if there is a way to see the specific parameters used by the results.

**Comment by epnev** [comment]
If you want to reject all the components that are below a certain SNR then you need to adjust the `SNR_lowest` parameter. See [here](https://caiman.readthedocs.io/en/master/Getting_Started.html#component-evaluation) on how the components gets accepted/rejected.
