### ISSUE TITLE
get_contours() + session registration edge case

### ISSUE THREAD

**Issue by zbarry** [flatironinstitute/CaImAn#716]
I get the following error when running `get_contours()` on a small percentage of registration-remapped cnm.A matrices:

```
/scratch/miniconda3/envs/calcium/lib/python3.7/site-packages/caiman/utils/visualization.py in get_contours(A, dims, thr, thr_method, swap_dim)
    369             cumEn = np.cumsum(patch_data[indx]**2)
    370             # we work with normalized values
--> 371             cumEn /= cumEn[-1]
    372             Bvec = np.ones(d)
    373             # we put it in a similar matrix

IndexError: index -1 is out of bounds for axis 0 with size 0
```

I *think* this might happen when a component's footprint gets pushed out of the field of view after the call to `cv2.remap`. The frames that I get this error on certainly suggest it - the remapped frame's component has disappeared.

My janky solution was just to fill in that coordinate entry with null data and continue on. There's probably a better, more sophisticated solution.

```python
            if len(cumEn) == 0:

                pars = dict(
                    coordinates=np.array([]),
                    CoM=np.array([np.NaN, np.NaN]),
                    neuron_id=i + 1,
                )

                coordinates.append(pars)

                continue
            else:
                # we work with normalized values
                cumEn /= cumEn[-1]

                Bvec = np.ones(d)
                # we put it in a similar matrix
                Bvec[A.indices[A.indptr[i]:A.indptr[i + 1]][indx]] = cumEn
```

**Comment by epnev** [comment]
@zbarry There are several places in the code where we check for empty components and remove them so your hypothesis sounds very plausible. Since this appears only when plotting, I'd just create a PR on dev with this. Removing it might create indexing problems with the way registration works. Thanks!

**Comment by epnev** [comment]
@pgunn Maybe you want to incorporate this and close the issue.

**Comment by pgunn** [comment]
I'll turn this into a PR on monday.
