### ISSUE TITLE
Video Concatenation Issue

### ISSUE THREAD

**Issue by connorjohnson1** [flatironinstitute/CaImAn#718]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows):  Windows
 
 2. Python version (3.x):  3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter
 
 4. Which of the demo scripts you're using for your analysis (if applicable): Demo_CNMFE
 
 5. CaImAn version*: 1.8.1
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda):  conda forge

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I am unable to concatenate videos using the function provided in the documentation. Perhaps I am loading them wrong? Maybe some clarification on the proper use of the function would help. Thanks in advance!

- **Copy error log below**

UnboundLocalError                         Traceback (most recent call last)
D:\Desktop\Anaconda3\envs\caiman\lib\site-packages\caiman\base\timeseries.py in concatenate(*args, **kwargs)
    349     try:
--> 350         return obj.__class__(np.concatenate(*args, **kwargs), **obj.__dict__)
    351     except:

UnboundLocalError: local variable 'obj' referenced before assignment

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-3-d9f5bc945627> in <module>
      2 movies_chained = cm.load_movie_chain(fnames)
      3 #fnames = [download_demo(fnames[0])]
----> 4 movies_chained = cm.concatenate(fnames , axis=0)

D:\Desktop\Anaconda3\envs\caiman\lib\site-packages\caiman\base\timeseries.py in concatenate(*args, **kwargs)
    351     except:
    352         logging.debug('no meta information passed')
--> 353         return obj.__class__(np.concatenate(*args, **kwargs))

UnboundLocalError: local variable 'obj' referenced before assignment

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment]
If you have a list of filenames of the movies you want to concatenate use `caiman.load_movie_chain(fnames)` where `fnames` is the (ordered) list of your filenames, e.g. `['mov1.tif', 'mov2.tif']`.

If you have a list of movie objects use `caiman.concatenate(movies)` where `movies` is your list of movie objects, e.g. `[m1, m2]` where `type(m1)` is `caiman.base.movies.movie`.
(You can cast arrays to movie objects using `caiman.movie(array)`)

**Comment by connorjohnson1** [comment]
How can I use the cm.load_movie_chain with the demo_pipeline_CNMFE? It doesn't seem to be accepted as when I use the download_demo to import a single video.

**Comment by j-friedrich** [comment]
`cm.load_movie_chain` can handle multiple as well as single files, e.g.
`m=cm.load_movie_chain([cm.paths.caiman_datadir() + '/example_movies/demoMovie.tif'])`
For single files you can also just use `cm.load`
