### ISSUE TITLE
Error during Memory Map (unexpected keyword argument 'var_name_hdf5')

### ISSUE THREAD

**Issue by connorjohnson1** [flatironinstitute/CaImAn#720]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter
 
 4. Which of the demo scripts you're using for your analysis (if applicable): Demo_pipeline_CNMFE
 
 5. CaImAn version*: 1.8.1
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): Conda

- **Describe the issue that you are experiencing**

Unable to perform memory mapping of files after motion correction, I get an error saying that there was an "unexpected keyword argument 'var_name_hdf5'".

- **Copy error log below**

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-3be661c455b1> in <module>
     17     bord_px = 0 if border_nan is 'copy' else bord_px
     18     fname_new = cm.save_memmap(fname_mc, base_name='memmap_', order='C',
---> 19                                border_to_0=bord_px)
     20 else:  # if no motion correction just memory map the file
     21     fname_new = cm.save_memmap(fnames, base_name='memmap_',

D:\Desktop\Anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py in save_memmap(filenames, base_name, resize_fact, remove_init, idx_xy, order, var_name_hdf5, xy_shifts, is_3D, add_to_movie, border_to_0, dview, n_chunks, slices)
    438         fname_new = cm.save_memmap_join(fname_parts, base_name=base_name,
    439                                         var_name_hdf5=var_name_hdf5,
--> 440                                         dview=dview, n_chunks=n_chunks)
    441 
    442     else:

TypeError: save_memmap_join() got an unexpected keyword argument 'var_name_hdf5'

**Comment by j-friedrich** [comment]
Can you please remove or comment out line 439 `var_name_hdf5=var_name_hdf5,` in D:\Desktop\Anaconda3\envs\caiman\lib\site-packages\caiman\mmapping.py 
That should fix the issue. Please let me know whether it does.

**Comment by connorjohnson1** [comment]
Yes, that solved the issue. Thank you very much!

**Comment by HoniSanders** [comment]
a similar issue occurs on line 330 of the same file.

**Comment by przemyslawj** [comment]
I have the same issue when the call is made from line 439

https://github.com/flatironinstitute/CaImAn/blob/e695785daa76e412516c39c371f96ae5438fb253/caiman/mmapping.py#L439

**Comment by j-friedrich** [comment]
@HoniSanders line 330 should be ok, cause `save_memmap` has indeed an argument `var_name_hdf5`, whereas `save_memmap_join` does not (because it expects a list of mmap files not hdf5)
