### ISSUE TITLE
Motion Correction: Apply_shifts_movie with 3D. 

### ISSUE THREAD

**Issue by caviri** [flatironinstitute/CaImAn#721]
Hello, 

Thanks for the tool and the extensive documentation. I'm trying to apply shifts generated using pw_rigid motion correction to another channel but  it seems is not compatible with 3D. Is this right?  

```
----> 5 mc.apply_shifts_movie(fname_ch2)

/home/jhub/jupyter_server/tutorials/tools/caiman_dev/CaImAn/caiman_dev/motion_correction.py in apply_shifts_movie(self, fname, rigid_shifts, save_memmap, save_base_name, order, remove_min)
    424         """
    425 
--> 426         Y = cm.load(fname).astype(np.float32)
    427         if remove_min:
    428             ymin = Y.min()

/home/jhub/jupyter_server/tutorials/tools/caiman_dev/CaImAn/caiman_dev/base/movies.py in load(file_name, fr, start_time, meta_data, subindices, shape, var_name_hdf5, in_memory, is_behavior, bottom, top, left, right, channel, outtype, is3D)
   1490                                 outtype=outtype,
   1491                                 var_name_hdf5=var_name_hdf5,
-> 1492                                 is3D=is3D)
   1493 
   1494     elif isinstance(file_name,tuple):

/home/jhub/jupyter_server/tutorials/tools/caiman_dev/CaImAn/caiman_dev/base/movies.py in load_movie_chain(file_list, fr, start_time, meta_data, subindices, var_name_hdf5, bottom, top, left, right, z_top, z_bottom, is3D, channel, outtype)
   1801                 m = m[np.newaxis, :, :]
   1802 
-> 1803             _, h, w = np.shape(m)
   1804             m = m[:, top:h - bottom, left:w - right]
   1805         else:

ValueError: too many values to unpack (expected 3)
```

**Comment by j-friedrich** [comment]
`apply_shifts_movie` is indeed only implemented for 2D data. Sadly, implementing it for pw_rigid will take some time. For rigid motion correction one can use:

`m_reg = cm.movie(np.array([cm.motion_correction.apply_shifts_dft(
    img, (sh[0], sh[1], sh[2]), 0, is_freq=False, border_nan=mc.border_nan) for img, sh in
    zip(cm.load(fname_ch2), -np.array(mc.shifts_rig))]))`

Not sure why the sign of the shifts needs to be flipped, but when above is applied to the original movie the resulting `m_reg` looks indeed identical to `m_rig` obtained via `mc.motion_correct(save_movie=True); m_rig = cm.load(mc.fname_tot_rig, is3D=True)`

Sorry, don't have a more positive answer at the moment.

**Comment by epnev** [comment]
@caviri @j-friedrich 
You can reuse the code snippet [here](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/motion_correction.py#L2373-L2384) to extend `apply_shifts` to the 3D pw-rigid motion correction. Do you want to try it?

**Comment by caviri** [comment]
@j-friedrich thanks so much for your quick response. I'm going to try to reuse the snipped @epnev shared!

**Comment by j-friedrich** [comment]
`apply_shifts_movie` is now compatible with 3D data (dev branch).
