### ISSUE TITLE
Pop Up Error - "Notebook Validation Failed"

### ISSUE THREAD

**Issue by connorjohnson1** [flatironinstitute/CaImAn#722]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows):  Windows
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): Demo_pipeline_CNMFE
 
 5. CaImAn version*: 1.8.1
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda):  conda forge

- **Describe the issue that you are experiencing**

Frequently when running CaImAn on Jupyter Notebook I get an error screen that pops up saying "notebook validation failed", however it doesn't typically impact CaImAn's output - I just close it and move on. However sometimes it will pop up multiple times and become frozen on my screen blocking me from doing anything without restarting. I see this error on two different computers I've installed CaImAn on, is it a common error? I haven't seen any other posts about it.

- **Copy error log below**
The save operation succeeded, but the notebook does not appear to be valid. The validation error was:

Notebook validation failed: 'application/vnd.bokehjs_load.v0+json' does not match any of the regexes: '^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$':
{
 "application/javascript": "\n(function(root) {\n  function now() {\n    return new Date();\n  }\n\n  var force = true;\n\n  if (typeof root._bokeh_onload_callbacks === \"undefined\" || force === true) {\n    root._bokeh_onload_callbacks = [];\n    root._bokeh_is_loading = undefined;\n  }\n\n  var JS_MIME_TYPE = 'application/javascript';\n  var HTML_MIME_TYPE = 'text/html';\n  var EXEC_MIME_TYPE = 'application/vnd.bokehjs_exec.v0+json';\n  var CLASS_NAME = 'output_bokeh rendered_html';\n\n  /**\n   * Render data to the DOM node\n   */\n  function render(props, node) {\n    var script = document.createElement(\"script\");\n    node.appendChild(script);\n  }\n\n  /**\n   * Handle when an output is cleared or removed\n   */\n  function handleClearOutput(event, handle) {\n    var cell = handle.cell;\n\n    var id = cell.output_area._bokeh_element_id;\n    var server_id = cell.output_area._bokeh_server_id;\n    // Clean up Bokeh references\n    if (id != null && id in Bokeh.index) {\n      Bokeh.index[id].model.document.clear();\n .................

The error is very long so I cut it off. I will also include a photo of the error. 

![bokeherror](https://user-images.githubusercontent.com/60056509/76011818-35b71700-5ee3-11ea-9840-665819958428.PNG)

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment]
That seems to be an issue with nbformat. Which version do you have? I can replicate the error with 5.0.4, but it disappears if I downgrade using `conda install -c conda-forge nbformat=4.4`

Maybe @pgunn has a comment on that?

**Comment by pgunn** [comment]
This looks like https://github.com/jupyter/nbformat/issues/161 - if I read this right, we have 2 choices (should confirm with experiments):

1. We open all our existing notebooks and re-save them with a current version of jupyter/nbformat, which might lock out older versions of jupyter, or
2. We pin nbformat for awhile to keep a window of compatibility, and then eventually do 1.

Right now, I think we manage jupyter as a part of our conda environment, so I don't think doing 1 would be too antisocial (just like any other dependency) but it would require anyone with an existing checkout to regenerate their environment if they're doing things in Jupyter. Doing 2 would be fine, but anyone who made an environment recently may already have the current nbformat and we'd be asking them to downgrade (which is its own kind of hassle).

If all the above is correct, I favour doing the first reasonably soon, and not doing the second at all.

**Comment by epnev** [comment]
Agree with @pgunn 
@connorjohnson1 What is your version of `nbformat`? You can find it by doing `conda list nbformat` from your caiman environment. If it's version 5 does the problem go away if you open a notebook, save it, and then reload it?

**Comment by connorjohnson1** [comment]
@epnev @pgunn I have nbformat version 5.0.4, I tried to save my notebook and reload it but I got the same popup error.

**Comment by pgunn** [comment]
I'm going to spend some time today replicating the issue. It's likely, if a load/save cycle doesn't fix it, that making a new notebook and then cut'n'pasting the cells from the old one would do the job.

**Comment by connorjohnson1** [comment]
@pgunn I see... in that case I will make sure to give that a try and report back.

**Comment by pgunn** [comment]
@connorjohnson1 Hello, if you're comfortable working with source releases of CaImAn, or with grabbing notebooks out of this branch, this might fix the issue. At least so far the testing is looking good for me, but we could use more testers.

https://github.com/flatironinstitute/CaImAn/pull/725

**Comment by pgunn** [comment]
@connorjohnson1 All of our testing of 725 suggests that that adjustment fixed the issue. I just merged it into dev, and we'll be making a new release to master (and a new conda package) this week.
