### ISSUE TITLE
CaImAn and named-pipes (for IPC)

### ISSUE THREAD

**Issue by thethea** [flatironinstitute/CaImAn#727]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows 10 Professional

 2. Python version (3.x): 
 Python 3.7

 3. Working environment (Python IDE/Jupyter Notebook/other):
 PyCharm IDE

 4. Which of the demo scripts you're using for your analysis (if applicable):
 online OnACID (or VolPy - if it can provide online analysis (see my question below))

 5. CaImAn version*: 
 CaImAn 1.8.1

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
via Miniconda3

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

x

- **Copy error log below**

x

- **If you're not reporting an error, type your message below**

Dear CaImAn developers/community,

rather than having an issue, I would like to ask for an advice on setting up one of CaImAn's online algorithms in a direct inter-process communication (IPC) via named-pipe with another open-source software. CaImAn's documentation page recommends using tiff/hdf5/h5 types of files as input, my question is - should a named-pipe follow the same rule or is another data format suitable to be used?

In addition, I can not find the information whether Volpy can perform online analysis of streaming data?

Any help/advice is kindly appreciated.

Best, Tea

**Comment by agiovann** [comment]
Dear Tea, I am working on something very similar. I think it should come out in a few months. We are connecting to scanimage.

**Comment by epnev** [comment]
@thethea The short answer is that the CaImAn codebase cannot do this out of box, but can be modified to do it (although that's not a trivial amount of work). Also VolPy cannot work in an online mode at the moment.
