### ISSUE TITLE
cnm.estimates.F_dff = Nonetype object

### ISSUE THREAD

**Issue by connorjohnson1** [flatironinstitute/CaImAn#729]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline_CNMFE
 
 5. CaImAn version*: 1.81
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda forge

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

Trying to save the raw df/f traces from CaImAn demo_pipeline_cnmfe but the variable cnm.estimates.F_dff seems to have no value, as if nothing is being saved there. Can anyone help me try to resolve why this might be happening?

- **Copy error log below**

`print(cnm.estimates.F_dff)`
None

`type(cnm.estimates.F_dff)`
NoneType

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment]
`cnm.estimates.F_dff` is populated once you run `cnm.estimates.detrend_df_f()`
