### ISSUE TITLE
Recommendation for less cell double labeling?

### ISSUE THREAD

**Issue by connorjohnson1** [flatironinstitute/CaImAn#730]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline_cnmfe
 
 5. CaImAn version*: 1.8.1
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda forge

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **If you're not reporting an error, type your message below**
![celloverlap1](https://user-images.githubusercontent.com/60056509/77079157-f5b95f00-69cd-11ea-8361-7e4c7d45612c.PNG)
![celloverlap2](https://user-images.githubusercontent.com/60056509/77079160-f651f580-69cd-11ea-967c-18d413f7ab7e.PNG)
In the examples above I have noticed several overlapping contours on what appear to be single cells. Now I know that these could be multiple cells but this is absolutely overkill. The df/f traces of a lot of these cells are very noisy, and I am not convinced they are real cells. I set my thresholds pretty high, and my merging threshold low but I still see most of my traces come out like this. 

I want to know ~ is this common for other people to see? What do you do to overcome this issue? When I try to decrease the merging threshold I get overly large cells and merging of clearly distant cells. I will post my parameters below:

gSig = (5, 5)       # gaussian width of a 2D gaussian kernel, which approximates a neuron
gSiz = (21, 21)     # average diameter of a neuron, in general 4*gSig+1
merge_thr = .4
min_corr = .9       
min_pnr = 5.25

Component Evaluation:
min_SNR = 3           
r_values_min = 0.9

I am hoping other CaImAn users can contribute here and we can open a discussion about enhancing the accuracy of cell detection. All of our work is based on the idea that the traces we are analyzing are true transients from cells, and not artifacts or split up signals.

**Comment by epnev** [comment]
@connorjohnson1 can you post a couple of examples with traces of components that should have been merged?

**Comment by connorjohnson1** [comment]
![Capture6](https://user-images.githubusercontent.com/60056509/77339011-8ca15680-6d01-11ea-9750-956c9f891785.PNG)
![Capture2](https://user-images.githubusercontent.com/60056509/77339026-92973780-6d01-11ea-9b65-35444ba92b56.PNG)
![Capture3](https://user-images.githubusercontent.com/60056509/77339027-932fce00-6d01-11ea-9445-c60e4d9fe510.PNG)
![Capture4](https://user-images.githubusercontent.com/60056509/77339028-932fce00-6d01-11ea-97e5-92ef3ce2ffed.PNG)
![Capture5](https://user-images.githubusercontent.com/60056509/77339030-932fce00-6d01-11ea-8375-a1ce6bb3b795.PNG)
![Capture](https://user-images.githubusercontent.com/60056509/77339031-932fce00-6d01-11ea-963c-53dea03bfe86.PNG)

**Comment by connorjohnson1** [comment]
Are there more spatial thresholds I can set on my data? I truly feel like these are too small and inaccurate.

**Comment by epnev** [comment]
@connorjohnson1 Are these the accepted components or all the components?

In general, I think there are two things to notice here:
- Unit 17 (last one) picks up a strong component that seems to be shared between the two neurons.
- Units 19 & 20 seems to belong to the same cell but have very distinct traces. Same goes for 21 & 22. 

I would suggest looking at the data to get a sense of what's failing here.

In terms of parameters I'd try increasing min_pnr to reduce the number of components, perhaps also reducing gSiz to ensure components don't get too large.

**Comment by connorjohnson1** [comment]
@epnev Ok, thank you! I will continue changing parameters and post back here if I have made any progress. I am going to look at my raw data too.

I have another question, however -- in the traces is the Y axis df/f? If so, is 1 = 1%? I found that these traces are getting up to like 150-200% which is very high. Perhaps my interpretation of the axis is wrong.

**Comment by connorjohnson1** [comment]
@epnev I thought you might be interested to know that this was actually an issue with the motion correction step, and not with the CNMF-E algorithm. It seemed there was some noise in our videos that did not shift with tissue we were recording. By applying a low-pass filter to our data we were able to get much better motion correction and better labeling. 



![dirint418contours](https://user-images.githubusercontent.com/60056509/78277666-d862b580-74e2-11ea-9f97-5a9dc7098fd1.PNG)

**Comment by epnev** [comment]
Ah good to know. That would explain it.

**Comment by FedeClaudi** [comment]
hi @connorjohnson1 , I'm having similar issues in my 1p recordings where I have several overlapping components. 
I'd like to try your solution but I'm not sure what you mean by low-pass filter: is it a spatial or temporal filter, are you filtering before motion correction or after and so on. 

If you could give us more details about how you went about fixing this issue that'd be awesome :)
