### ISSUE TITLE
Issue At estimates.nb_view_components() in Demo Pipeline

### ISSUE THREAD

**Issue by NUtaHei** [flatironinstitute/CaImAn#732]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
machine 1: macOS Mojave 10.14.6
machine 2: macOS Mojave 10.14.4

 2. Python version (3.x): 
 both machine: Python 3.7.1

 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook

 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_pipeline
 5. CaImAn version*: 
 1.8.2
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
machine 1: conda
machine 2:pip install -e .

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I have 2 machines and tried to install CaIman in different ways but got exactly same errors in Demo pipeline with both machines. I got errors at View traces of accepted and rejected components and Display final results. All showed AttributeError: unexpected attribute 'callback' to Slider, similar attributes are js_event_callbacks.

- **Copy error log below**

# accepted components
cnm2.estimates.nb_view_components(img=Cn, idx=cnm2.estimates.idx_components)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-002fdca18e59> in <module>
      1 # accepted components
----> 2 cnm2.estimates.nb_view_components(img=Cn, idx=cnm2.estimates.idx_components)

/Applications/CaImAn-master/caiman/source_extraction/cnmf/estimates.py in nb_view_components(self, Yr, img, idx, denoised_color, cmap, thr)
    397                                                         self.C[idx], self.b, self.f,
    398                                                         self.dims[0], self.dims[1], YrA=self.R[idx], image_neurons=img,
--> 399                                                         thr=thr, denoised_color=denoised_color, cmap=cmap)
    400         return self
    401 

/Applications/CaImAn-master/caiman/utils/visualization.py in nb_view_patches(Yr, A, C, b, f, d1, d2, YrA, image_neurons, thr, denoised_color, cmap)
    231 
    232     slider = bokeh.models.Slider(start=1, end=Y_r.shape[0], value=1, step=1,
--> 233                                  title="Neuron Number", callback=callback)
    234     xr = Range1d(start=0, end=image_neurons.shape[1])
    235     yr = Range1d(start=image_neurons.shape[0], end=0)

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/models/widgets/sliders.py in __init__(self, **kwargs)
     68                 raise ValueError("Slider 'start' and 'end' cannot be equal.")
     69 
---> 70         super().__init__(**kwargs)
     71 
     72     title = String(default="", help="""

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/model.py in __init__(self, **kwargs)
    232         kwargs.pop("id", None)
    233 
--> 234         super().__init__(**kwargs)
    235         default_theme.apply_to_model(self)
    236 

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/core/has_props.py in __init__(self, **properties)
    244 
    245         for name, value in properties.items():
--> 246             setattr(self, name, value)
    247 
    248     def __setattr__(self, name, value):

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/core/has_props.py in __setattr__(self, name, value)
    279 
    280             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
--> 281                 (name, self.__class__.__name__, text, nice_join(matches)))
    282 
    283     def __str__(self):

AttributeError: unexpected attribute 'callback' to Slider, similar attributes are js_event_callbacks

# rejected components
if len(cnm2.estimates.idx_components_bad) > 0:
    cnm2.estimates.nb_view_components(img=Cn, idx=cnm2.estimates.idx_components_bad)
else:
    print("No components were rejected.")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-e7029f559bfa> in <module>
      1 # rejected components
      2 if len(cnm2.estimates.idx_components_bad) > 0:
----> 3     cnm2.estimates.nb_view_components(img=Cn, idx=cnm2.estimates.idx_components_bad)
      4 else:
      5     print("No components were rejected.")

/Applications/CaImAn-master/caiman/source_extraction/cnmf/estimates.py in nb_view_components(self, Yr, img, idx, denoised_color, cmap, thr)
    397                                                         self.C[idx], self.b, self.f,
    398                                                         self.dims[0], self.dims[1], YrA=self.R[idx], image_neurons=img,
--> 399                                                         thr=thr, denoised_color=denoised_color, cmap=cmap)
    400         return self
    401 

/Applications/CaImAn-master/caiman/utils/visualization.py in nb_view_patches(Yr, A, C, b, f, d1, d2, YrA, image_neurons, thr, denoised_color, cmap)
    231 
    232     slider = bokeh.models.Slider(start=1, end=Y_r.shape[0], value=1, step=1,
--> 233                                  title="Neuron Number", callback=callback)
    234     xr = Range1d(start=0, end=image_neurons.shape[1])
    235     yr = Range1d(start=image_neurons.shape[0], end=0)

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/models/widgets/sliders.py in __init__(self, **kwargs)
     68                 raise ValueError("Slider 'start' and 'end' cannot be equal.")
     69 
---> 70         super().__init__(**kwargs)
     71 
     72     title = String(default="", help="""

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/model.py in __init__(self, **kwargs)
    232         kwargs.pop("id", None)
    233 
--> 234         super().__init__(**kwargs)
    235         default_theme.apply_to_model(self)
    236 

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/core/has_props.py in __init__(self, **properties)
    244 
    245         for name, value in properties.items():
--> 246             setattr(self, name, value)
    247 
    248     def __setattr__(self, name, value):

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/core/has_props.py in __setattr__(self, name, value)
    279 
    280             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
--> 281                 (name, self.__class__.__name__, text, nice_join(matches)))
    282 
    283     def __str__(self):

AttributeError: unexpected attribute 'callback' to Slider, similar attributes are js_event_callbacks

#Display final results
cnm2.estimates.nb_view_components(img=Cn, denoised_color='red')
print('you may need to change the data rate to generate this one: use jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10 before opening jupyter notebook')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-74bf6f499cff> in <module>
----> 1 cnm2.estimates.nb_view_components(img=Cn, denoised_color='red')
      2 print('you may need to change the data rate to generate this one: use jupyter notebook --NotebookApp.iopub_data_rate_limit=1.0e10 before opening jupyter notebook')

/Applications/CaImAn-master/caiman/source_extraction/cnmf/estimates.py in nb_view_components(self, Yr, img, idx, denoised_color, cmap, thr)
    392             caiman.utils.visualization.nb_view_patches(Yr, self.A, self.C,
    393                     self.b, self.f, self.dims[0], self.dims[1], YrA=self.R, image_neurons=img,
--> 394                     thr=thr, denoised_color=denoised_color, cmap=cmap)
    395         else:
    396             caiman.utils.visualization.nb_view_patches(Yr, self.A.tocsc()[:,idx],

/Applications/CaImAn-master/caiman/utils/visualization.py in nb_view_patches(Yr, A, C, b, f, d1, d2, YrA, image_neurons, thr, denoised_color, cmap)
    231 
    232     slider = bokeh.models.Slider(start=1, end=Y_r.shape[0], value=1, step=1,
--> 233                                  title="Neuron Number", callback=callback)
    234     xr = Range1d(start=0, end=image_neurons.shape[1])
    235     yr = Range1d(start=image_neurons.shape[0], end=0)

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/models/widgets/sliders.py in __init__(self, **kwargs)
     68                 raise ValueError("Slider 'start' and 'end' cannot be equal.")
     69 
---> 70         super().__init__(**kwargs)
     71 
     72     title = String(default="", help="""

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/model.py in __init__(self, **kwargs)
    232         kwargs.pop("id", None)
    233 
--> 234         super().__init__(**kwargs)
    235         default_theme.apply_to_model(self)
    236 

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/core/has_props.py in __init__(self, **properties)
    244 
    245         for name, value in properties.items():
--> 246             setattr(self, name, value)
    247 
    248     def __setattr__(self, name, value):

/anaconda3/envs/caiman/lib/python3.7/site-packages/bokeh/core/has_props.py in __setattr__(self, name, value)
    279 
    280             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
--> 281                 (name, self.__class__.__name__, text, nice_join(matches)))
    282 
    283     def __str__(self):

AttributeError: unexpected attribute 'callback' to Slider, similar attributes are js_event_callbacks

- **If you're not reporting an error, type your message below**

**Comment by kachiO** [comment]
Getting this same error message as well, with the same operating system and notebook.

**Comment by j-friedrich** [comment]
This issue has already been addressed in the dev branch. For the time being, until the new release, the easiest would be for @kachiO and @NUtaHei to downgrade bokeh from version 2.0 to 1.4.

@pgunn I am just doing some final testing of the dev branch. Then you could merge dev into master and release 1.8.3 which supports bokeh 2 and tensorflow 2. Also, holoviews 1.13 supports bokeh 2 as well, thus now the notebooks using holoviews run smoothly too.

**Comment by NUtaHei** [comment]
> This issue has already been addressed in the dev branch. For the time being, until the new release, the easiest would be for @kachiO and @NUtaHei to downgrade bokeh from version 2.0 to 1.4.

Downgrade bokeh worked for the machine 2 (pip install). Thank you so much.
