### ISSUE TITLE
ValueError: To many value to unpack

### ISSUE THREAD

**Issue by Xuuu11** [flatironinstitute/CaImAn#733]
1. Operating system (Linux/macOS/Windows): 
 Windows

 2. Python version (3.x): 
 Python 3.7.6

 3. Working environment (Python IDE/Jupyter Notebook/other):
 Spyder

 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_pipeline.py

 5. CaImAn version*: 
 1.8.2

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda-forge

- **Describe the issue that you are experiencing**
There is no problem with demo_movie, but show up an error when we want to upload our own data movie, while our data is also a TIF file and in the acceptable size range. The parameter like size and density of neurons is similar to demo script, so I think it should work with original settings.

- **Copy error log below**

  File "C:\Users\Administrator\anaconda3\envs\caiman\lib\site-packages\caiman\base\movies.py", line 321, in bin_median
    T, d1, d2 = np.shape(self)

ValueError: too many values to unpack (expected 3)

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@Xuuu11 What is the command you're trying to execute when getting this error?

**Comment by Xuuu11** [comment]
Sorry, I just fix this! I uploaded an RGB movie... I change it to 32 bit and it works now. Thanks for your quick response!

**Comment by amitakoren** [comment]
Hello, we're having the same issue with .tif files that worked in the past. 
Did you manage to run .tif files in the end?
