### ISSUE TITLE
cnm.refit(images) throws error: ValueError: shapes (1,) and (228,2809) not aligned: 1 (dim 0) != 228 (dim 0)

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#734]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows 10
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other):Jupyter
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline
 
 5. CaImAn version*: latest
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): pip

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I am just running the demo_pipeline() code with a few .avi files from the same session.  The following is the error. 

![Capture_LI](https://user-images.githubusercontent.com/721570/77896589-7bcd8380-72b3-11ea-9915-6b29eb82396c.jpg)

Strangely, when i reran this code with only 1 of the .avi files, the code ran however, no cells are found (the cnm.estimates.A array is empty). These are my parameters.Can someone please comment on the values (whether they must be decreased or not) ?

    p = 2               # order of the autoregressive system
    K = None            # upper bound on number of components per patch, in general None for 1p data
    gSig = (3, 3)       # gaussian width of a 2D gaussian kernel, which approximates a neuron
    gSiz = (13, 13)     # average diameter of a neuron, in general 4*gSig+1
    Ain = None          # possibility to seed with predetermined binary masks
    merge_thr = .7      # merging threshold, max correlation allowed
    rf = 26             # half-size of the patches in pixels. e.g., if rf=40, patches are 80x80
    stride_cnmf = 12    # amount of overlap between the patches in pixels
    #                     (keep it at least large as gSiz, i.e 4 times the neuron size gSig)
    tsub = 2            # downsampling factor in time for initialization,
    #                     increase if you have memory problems
    ssub = 1            # downsampling factor in space for initialization,
    #                     increase if you have memory problems
    #                     you can pass them here as boolean vectors
    low_rank_background = None  # None leaves background of each patch intact,
    #                     True performs global low-rank approximation if gnb>0
    gnb = 0             # number of background components (rank) if positive,
    #                     else exact ring model with following settings
    #                         gnb= 0: Return background as b and W
    #                         gnb=-1: Return full rank background B
    #                         gnb<-1: Don't return background
    nb_patch = 0        # number of background components (rank) per patch if gnb>0,
    #                     else it is set automatically
    min_corr = .8       # min peak value from correlation image
    min_pnr = 10        # min peak to noise ration from PNR image
    ssub_B = 2          # additional downsampling factor in space for background
    ring_size_factor = 1.4  # radius of ring is gSiz*ring_size_factor

min_SNR = 2.5           # adaptive way to set threshold on the transient size
    r_values_min = 0.85    # threshold on space consistency (if you lower more components
    #                        will be accepted, potentially with worst quality)

**Comment by epnev** [comment]
What’s the error?

**Comment by epnev** [comment]
@akatav What is the value of `images.shape`?

**Comment by akatav** [comment]
The .avi files are 1000 frames with each frame being (480,752) in resolution.So, images.shape is (360960,1000) in the case where only 1 .avi file is provided to the motion correction.

**Comment by epnev** [comment]
This shouldn't be the case. The code is as follows:
```
Yr, dims, T = cm.load_memmap(fname_new)
images = Yr.T.reshape((T,) + dims, order='F')
```
`Yr` should have the dimensions you report but `images` should be `1000 x 480 x 752`. 
What is `Yr.shape`?

**Comment by akatav** [comment]
ah, ok.i'll change and try.thank you.
