### ISSUE TITLE
Example of slurm script to schedule demo_pipeline.py in parallel for a number of sessions

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#735]
Hi,
I am quite new to slurm setup, so i'll appreciate any help with setting up caiman demo_pipeline code for the 2 photon case to do motion correction and cell detection.I have a few sessions running into TBs where each session contains many .avi files.Each  .avi file on caiman pipeline takes upto 3 hours to finish cell detection.
I'd like to setup a slurm job to run all the sessions in parallel. Is there an example for doing this with slurm and caiman?

**Comment by epnev** [comment]
Once you set up a CNMF object you can run pretty much the entire pipeline using the [`cnmf.fit_file`](https://caiman.readthedocs.io/en/master/core_functions.html#caiman.source_extraction.cnmf.cnmf.CNMF.fit_file) method. Then you can save the output using the `cnmf.cnm.save`. You can package this as a script that you can submit using SLURM (cannot help there, but your cluster administrator should be able to).

Alternatively (or in addition) you can speed up processing by downsampling your data. Setting `ssub` and `tsub` to integer values greater than 1 can increase speed significantly, and won't harm performance as long as you don't downsample too. You should try out to see what works best for you but as a rule of thumb setting such that `gSig/ssub >= 4`  and `frame rate/tsub >=10` should not affect performance.
