### ISSUE TITLE
Embedded timestamp (UCLA Miniscope Question)

### ISSUE THREAD

**Issue by donglabimaging** [flatironinstitute/CaImAn#736]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Windows 10, Anacoda environment
 
- **If you're not reporting an error, type your message below**
We are using CaImAn to analysis data recorded by the UCLA miniscope (*.avi).  Each frame is timestamped and the timestamp is embedded within each frame.  The timestamp can be extracted by generating a 32bit integer from the last 8th, 7th, 6th, and 5th pixels in each frame.   

They have posted a sample Matlab code (listed below), but I am not sure how to do that in the CaImAn environment.
footer = (frame(end,(end-7):end)); timestamp = footer(1) + bitshift(footer(2),8) + bitshift(footer(3),16) + bitshift(footer(4),24);

I have tried cv.imread / cv.videocapture and try to gain access the pixels of each frame without any success.  I would really appreciate it, if I could get some help here.  Many thanks!

**Comment by epnev** [comment]
@donglabimaging 

1.  You can load the file `fname`  as usual (but save it as a 32 bit integer).
``` m = cm.load(fname).astype(np.uint32))```

2. Then it is not clear whether the last  8th, 7th, 6th, and 5th pixels occur in the last row or the last column of each frame. You'll have to find that out yourself, but depending on where they are you can extract them by
```pixel_values = m[:, -1, -8:-4]```
or
```pixel_values = m[:, -8:-4, -1]```.
This will give you an array where each row has the values of the pixels you're interested in.

3. You will have to find a python equivalent to MATLAB's `bitshift` function or implement it yourself. We cannot help with this but maybe the Miniscope team can.
