### ISSUE TITLE
Multisession image appears shifted to the left

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#737]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows 10
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter
 
 4. Which of the demo scripts you're using for your analysis (if applicable): Figure_9_alignment
 
 5. CaImAn version*: most recent
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): pip

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
My image resolution is (480,752).I am trying to register multiple sessions. I obtained the correlation for each session using the cm.summary_images.correlation_pnr() 

The cells detected across sessions are plotted fine, however, the underlying cell structure is not shown. The figures look like below: 

![download (1)](https://user-images.githubusercontent.com/721570/78450646-14e90980-76bb-11ea-819f-11502d92b6e5.png)

In another instance, the plot appreared as if the cells were shifted to the left like below:
 
![download](https://user-images.githubusercontent.com/721570/78450849-7f4e7980-76bc-11ea-8f92-275b0dfc5588.png)

How to plot so that the underlying cell borders are also shown? 

Code:

`
get mmap file for each session like this:
Yr, dims, T = cm.load_memmap('mmap file for each session'')
images_0 = Yr.T.reshape((T,) + dims, order='F')

A=spatial # spatial is the array of cnm.estimates.A for each session
c1_0=cm.summary_images.correlation_pnr(images_0, swap_dim=False) 
c2_0=cm.summary_images.correlation_pnr(images_1, swap_dim=False)

CI=[c1_0[0],c2_0[0]]
max_thr=0.1
A_forw, assign_forw, match_forw = register_multisession(spatial, dims, CI, max_thr=0.1)  
A_back, assign_back, match_back = register_multisession(A[::-1], dims, CI[::-1], max_thr=max_thr)
`

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@akatav What is the plotting command you're doing?
Also bear in mind that you have two sessions here. Forward and backward registration is identical so it doesn't make sense to do both.

**Comment by akatav** [comment]
`
plt.figure(figsize=(15,10))
plt.rcParams['pdf.fonttype'] = 42
font = {'family': 'Myriad Pro',
        'weight': 'regular',
        'size': 10}
plt.rc('font', **font)
cl = ['r', 'b']
ax1 = plt.subplot2grid((3, 3), (0, 0), colspan=2, rowspan=2)
lp, hp = np.nanpercentile(CI[0], [5, 98])
plt.imshow(CI[0], vmin=lp, vmax=hp, cmap='gray')
for i in range(N):
    [plt.contour(norm_nrg(mm), levels=[0.95], colors=cl[i], linewidths=2)
     for mm in masks[i][comb_forw[i]]]
plt.title('Components tracked across all days (forward)')
plt.xlim((3, dims[0]-7))
plt.axis('off')
`
The code is same as Figure9 script.

**Comment by epnev** [comment]
@akatav That may be a bit too much for just two sessions. Can you use the [`register_ROIs`](https://caiman.readthedocs.io/en/master/core_functions.html#caiman.base.rois.register_ROIs) method and set the `plot_results` flag to `True`?

**Comment by epnev** [comment]
@akatav Any updates on this?

**Comment by akatav** [comment]
@epnev yes, thank you. Setting plot_results=True worked for with just 2 sessions. Although,I have to check with multiple sessions. Is there such a plot flag with register_multisessions() ?

**Comment by epnev** [comment]
No there is not, you can follow the other script that you initially used. If you go through it you'll understand what's happening and how to create your own plots if necessary.
