### ISSUE TITLE
Question about estimates.S for 1P data 

### ISSUE THREAD

**Issue by danachang** [flatironinstitute/CaImAn#739]
Hi, I know there has been similar questions on how to estimate spike count from `estimates.S`, but I have specific questions around this for 1P data. From previous posts, it is suggested that `estimates.S` should not be directly used as a proxy for spike rate or number of spikes, but should deconvolve using `dF_F`. However, from CNMFe, it suggests that `C` is a scaled version of `dF`, and can be used as a proxy for `dF/F`, and `S(i)` is thought as an estimate of number of spikes in i-th frame, if I understand it correctly. 

Therefore, I'm not sure how to best get spike count estimate (or spiking activity) with 1P data using CalmAn package. For 1P data, what would be appropriate way to estimate spike counts per timeframe (given that it does not make sense to calculate df/F for 1P data)? Thanks!!

**Comment by epnev** [comment]
There is no direct way to get spike counts. If you have a reference point, e.g. expected firing rate, you could try to relate that to the signal you're observing, but other than that there is no way to know what a spike corresponds to with respect to observed fluorescence.

**Comment by danachang** [comment]
Got it. Thanks a lot!
