### ISSUE TITLE
CaImAn GUI

### ISSUE THREAD

**Issue by zknauss** [flatironinstitute/CaImAn#741]
1. Operating system (Linux/macOS/Windows): 
 **Windows**
 2. Python version (3.x): 
 **Python 3.7**
 3. Working environment (Python IDE/Jupyter Notebook/other):
 **Jupyter Notebook**
 4. Which of the demo scripts you're using for your analysis (if applicable):
 Post analysis of 1p data using cmnf-E offline + CNN --> **CaImAn GUI**
 5. CaImAn version*: 
 **1.8.2**
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
**Package based**
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

**I'm relatively new to coding in python and am having trouble with launching the caiman_gui and keep getting the below AttributeError. I'm looking at 1p calcium imaging data that is taken from an avi file --> motion corrected --> extraction/deconvolution with CNMF-E --> detrended --> evaluated via CNN and saved as a hdf5 file for sorting in the CaImAn GUI.
 
AttributeError                            Traceback (most recent call last)
~\caiman_data\caiman_gui.py in <module>
    109 estimates.Cn = rotate90(estimates.Cn, right=True, vector=False)
    110 estimates.A = rotate90(estimates.A, right=True, vector=True, sparse=True)
--> 111 estimates.b = rotate90(estimates.b, right=True, vector=True)
    112 estimates.dims = (estimates.dims[1], estimates.dims[0])
    113 estimates.rotation = True               # rotation flag becomes true after rotation

~\caiman_data\caiman_gui.py in rotate90(img, right, vector, sparse)
     94     elif vector == True:
     95         if sparse == False:
---> 96             img = img.reshape((dims[1-a], dims[a], img.shape[1]), order='F')
     97             img = img.transpose([1,0,2])
     98             img = np.flip(img, axis=a)

AttributeError: 'NoneType' object has no attribute 'reshape'

- Copy error log below
**Not sure where to find the error log but I'll try to locate it and upload it here** 

Attached is the complete code I'm running
Thanks,
- Zknauss
[code.txt](https://github.com/flatironinstitute/CaImAn/files/4481760/code.txt)

**Comment by j-friedrich** [comment]
The GUI does not support 1p data, which uses a different background model. 

If you are not interested in inspecting the background as a simple workaround you can modify caiman_gui.py by simply adding the following lines after line 75 
<pre>
if estimates.b is None:
    estimates.b = np.zeros((np.prod(dims), 0))
    estimates.f = np.zeros((0, estimates.C.shape[1]))
</pre>

It gets more complicated if you want to display the background.
As one workaround (with big memory requirements) that displays the background for each frame you could set `b` to the full background and `f` to the identity matrix, i.e. modify caiman_gui.py by adding the following lines after line 75
<pre>
if estimates.b is None:
    m = cm.load(F.getOpenFileName(caption='Load Movie')[0])
    estimates.b = estimates.compute_background(m.reshape(len(m), -1).T)
    estimates.f = np.eye(len(m), dtype='int8')
</pre>
Alternatively you could approximate the full background using NMF.
Note that `compute_background` has only been recently added to the dev branch [here](https://github.com/flatironinstitute/CaImAn/blob/1eb4c49717088723f33b07861e1c271d364018ee/caiman/source_extraction/cnmf/estimates.py#L705)

**Comment by j-friedrich** [comment]
Actually, there's an as simple workaround that displays the constant background, but ignores the fluctuating background
<pre>
if estimates.b is None:
    estimates.b = estimates.b0[:, None]
    estimates.f = np.ones((1, estimates.C.shape[1]))
</pre>

**Comment by zknauss** [comment]
I tryed running the GUI after adding those after line 75 and got the following error  
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\caiman_data\caiman_gui.py in <module>
    293 
    294 
--> 295 draw_contours()
    296 
    297 hist.setLevels(estimates.background_image.min(), estimates.background_image.max())

~\caiman_data\caiman_gui.py in draw_contours()
    177         iidd = np.array(estimates.idx_components)
    178 
--> 179         idx1 = np.where(SNRs[iidd] < 0.1)[0]
    180         idx2 = np.where((SNRs[iidd] >= 0.1) &
    181                         (SNRs[iidd] < 0.25))[0]

IndexError: too many indices for array

**Comment by j-friedrich** [comment]
Please check whether`cnm.estimates.r_values` is `None`.
If it's `None` you need to run the component evaluation as done in the [demo_pipeline_cnmfE](https://github.com/flatironinstitute/CaImAn/blob/e2533f5a4350f7916a14f6fd61b3a1bcb5dede79/demos/general/demo_pipeline_cnmfE.py#L214)

**Comment by zknauss** [comment]
That did it thank you so much! I have a few more questions that maybe you can help me with...

1. In the GUI I'm assuming it's possible to alter the axis labels, titles and trace color but I can't seem to find it in the GUI or a specific line in the code for this. I was able to change the color of the background during export but the trace remained a faded gray. It might just take some more exploration of the GUI code but is there a simple way to do this?

2. Is there currently a way to calculate trace statistics ( average amplitude, frequency, rise and fall tau etc.) for each ROI and display them alongside the trace in the GUI or export them together downstream?

Thanks for all the help 
-Zknauss

**Comment by j-friedrich** [comment]
@zknauss excuse the delayed response.
That is currently not implemented in the GUI. The GUI is mostly useful for inspection and manual acceptation/rejection of detected components.

To interact more with the data I'd suggest using the jupyter notebook. Nice functions to display the results are `estimates.plot_contours_nb` and `estimates.hv_view_components` or `estimates.nb_view_components` (which allow specifying colors).

The denoised traces are `esimates.C`, the undenoised 'raw traces' can be obtained as `esimates.C+esimates.R`. The time constants are implicitly given by `estimates.g`.
For `p=1`
<img width="841" alt="Screen Shot 2020-04-24 at 10 41 53 AM" src="https://user-images.githubusercontent.com/11875432/80224961-71837880-8618-11ea-9177-345b146ee89e.png">
For `p=2`
<img width="756" alt="Screen Shot 2020-04-24 at 10 41 29 AM" src="https://user-images.githubusercontent.com/11875432/80224906-5dd81200-8618-11ea-898e-aa9da0d9d97f.png">

**Comment by tvajtay** [comment]
Hello, I have 2p data that ran through the pipeline and was able to load into an older version of caiman_gui.py, however when I recently updated my install I recieved the following error.

```
(caiman) [tjv55@slepner033 tjv55]$ ipython ./gui/caiman_gui.py
ValueError                                Traceback (most recent call last)
/scratch/tjv55/gui/caiman_gui.py in <module>
    291 
    292 
--> 293 draw_contours()
    294 
    295 hist.setLevels(estimates.background_image.min(), estimates.background_image.max())

/scratch/tjv55/gui/caiman_gui.py in draw_contours()
    186         idx6 = np.where(SNRs[iidd] >= 0.9)[0]
    187 
--> 188         cv2.drawContours(bkgr_contours, sum([contours[jj] for jj in idx1], []), -1, (255, 0, 0), 1)
    189         cv2.drawContours(bkgr_contours, sum([contours[jj] for jj in idx2], []), -1, (0, 255, 0), 1)
    190         cv2.drawContours(bkgr_contours, sum([contours[jj] for jj in idx3], []), -1, (0, 0, 255), 1)

ValueError: operands could not be broadcast together with shapes (0,) (327,256) 
```
 I looked at `cnm.estimates.r_values` and it is not none.

**Comment by j-friedrich** [comment]
Hi @tvajtay,
the gui actually hasn't changed in months.
It seems you are using a too old version of opencv. In old versions `cv2.findContours` used to return 3 values, in the newer ones (>=3.2) only 2. Please check your version of opencv and try upgrading.

**Comment by tvajtay** [comment]
Updating my environment seems to have worked, thanks!

**Comment by j-friedrich** [comment]
Ok, great! Thanks for leting me know.
