### ISSUE TITLE
Problem with Multisession registration with CaImAn

### ISSUE THREAD

**Issue by DariaGiunta** [flatironinstitute/CaImAn#743]
Hi there,

I'm currently using the CaImAn pipeline to analyze my microendoscopic (1p) Calcium Imaging data. The CNMF-E algorithm works perfectly and I get good results. Now I need to move on and perform multi-day registration with my videos recorded during multiple sessions. I tried to follow the instructions from the multisession registration demo from GitHub: [https://github.com/flatironinstitute/CaImAn/blob/5af22564d8771342212b0e67e97df800f5a85537/demos/notebooks/demo_multisession_registration.ipynb](https://github.com/flatironinstitute/CaImAn/blob/5af22564d8771342212b0e67e97df800f5a85537/demos/notebooks/demo_multisession_registration.ipynb).

Unfortunately, I can’t manage to reproduce the notebook script with my own data and hope to find some help here.

In order to run the multisession registration, I constructed as required a list of spatial footprints (derived from the CNMF analysis of the videos) and a template (correlation image) for each session. To create a list of spatial footprints I extracted the ‘data of estimates A’ and constructed a `csc_matrix` for each session using this code:

```python
with h5py.File(data.hdf5, 'r') as hdf:
  ls = list(hdf.keys())
  all_estimates = hdf.get('estimates')
  estimates = np.array(all_estimates)
  est_a = hdf.get('/estimates/A')
  est_a_items = list(est_a.items())
  est_a_data = est_a.get('data')
  csc_mat_a = csc_matrix(est_a_data)
```

To create a list of templates (correlation images) for each session I extracted the `cn_filter` data, computed during the summary images computation step of the caiman pipeline:

```python
corr_image = np.array(cn_filter)
np.save('path.npy', corr_image, allow_pickle=True)
```

At the end I put both into a list and pickle the data. Unpickling works well and I get a final list that looks similar to the one from the demo data, with csc-matrices for the footprints and numpy arrays (float 32) for the templates.

However, when I am trying to run the following command:

```python
spatial_union, assignments, matchings = register_multisession(A=spatial, dims=dims, templates=templates)
```

with videos from 3 different sessions, I get the following error:

```
error: (OpenCV(4.1.0) ../modules/video/src/optflowgf.cpp:1114: error: (-215:Assertion failed) prev0.size() == next0.size() && prev0.channels() == next0.channels() && prev0.channels() == 1 && pyrScale_ < 1 in function 'calc').
```

I thought the problem might be due to some differences in the number of extracted components by the cnmf-e in the three different videos. To exclude this option, I tried to reproduce the demo notebook again with the data of the same video repeated three times in a row. Here I got following error: 

```
ValueError: cannot reshape array of size 29041 into shape (188,188,newaxis).
```

As I really can’t explain these errors to myself I kindly ask for some help!

Many many Thanks,
Daria

**Comment by j-friedrich** [comment]
Hi Daria,
you don't properly load the sparse matrix `A`. The easiest way is to use CaImAn's built in function:
`cnm=caiman.source_extraction.cnmf.cnmf.load_CNMF('data.hdf5')`
The spatial footprints are then `cnm.estimates.A`.
Alternatively, specify not only the data, but the indices and indptr:
<pre>
with h5py.File('data.hdf5', 'r') as hdf:
    est_a = hdf.get('/estimates/A')
    csc_mat_a = csc_matrix((est_a.get('data'), est_a.get('indices'), est_a.get('indptr')))
</pre>
Note the double brackets, cf. `csc_matrix` reference guide.

Cheers,
Johannes

**Comment by DariaGiunta** [comment]
Hello Johannes,
Many thanks for the super fast reply. Indeed the CaImAn's built in function is the easiest way to extract the correct data. Thank you very much for your help it worked now for me! 
Best, Daria

**Comment by DariaGiunta** [comment]
Hello together,

after correcting my way of extracting Estimates A, I still get the following error message:

```
error: (OpenCV(4.1.0) ../modules/video/src/optflowgf.cpp:1114: error: (-215:Assertion failed) prev0.size() == next0.size() && prev0.channels() == next0.channels() && prev0.channels() == 1 && pyrScale_ < 1 in function 'calc').
```

This only happens when I analyze three different videos, of the same mouse just three distinct timepoints. I tested the registration with the same video three times in a row and then it worked.

What might be the problem with the three different videos? 

Many thanks for your help! 
Best, Daria

**Comment by epnev** [comment]
@DariaGiunta One possibility is that the FOV in the three videos have different dimensions so make sure that this is not the case. Also, the error might occur if one of the `A` matrices is empty.

**Comment by DariaGiunta** [comment]
Hello together,

First many thanks for your previous help, and I am very sorry that I again ran into trouble and need your help.

The multisession registration works very well, and I am also able to collect the traces of all neurons that were registered in all of my sessions.
However, the number of registered neurons after running the multisession registration does not reflect the "real neurons" that I extracted with CNMF-E after removing the bad components.

I already tried to, instead of loading all identified components into sparse matrix A, to load only the accepted components that are saved in ```idx_components``` :

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_a_accepted= cnm.estimates.A[:,idx_components] ```
to extract the accepted spatial components and

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_c_accepted= cnm.estimates.C[idx_components] ```
to extract the accepted temporal components, but I get the following error message:

```NameError: name 'idx_components' is not defined.```

I tried to play around with many settings and read the ‘caiman.readthedocs.io’ (https://caiman.readthedocs.io/en/latest/Getting_Started.html#variables-for-1p-processing-cnmf-e) to find out what might be the mistake, but I couldn't find out the reason for this error message.

In general, I am also not sure if what I have done so far is the right way to perform multisession registration on ONLY the accepted components derived after running the cnmf-e. 

I kindly ask for some help!

Many Thanks,
Daria

**Comment by DariaGiunta** [comment]
Hello together,

First many thanks for your previous help, and I am very sorry that I again ran into trouble and need your help.

The multisession registration works very well, and I am also able to collect the traces of all neurons that were registered in all of my sessions.
However, the number of registered neurons after running the multisession registration does not reflect the "real neurons" that I extracted with CNMF-E after removing the bad components.

I already tried to, instead of loading all identified components into sparse matrix A, to load only the accepted components that are saved in idx_components:

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_a_accepted= cnm.estimates.A[:,idx_components]```

to extract the accepted spatial components and

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_c_accepted= cnm.estimates.C[idx_components]```

to extract the accepted temporal components, but I get the following error message:

```NameError: name 'idx_components' is not defined.```

I tried to play around with many settings and read the ‘caiman.readthedocs.io’ (https://caiman.readthedocs.io/en/latest/Getting_Started.html#variables-for-1p-processing-cnmf-e) to find out what might be the mistake, but I couldn't find out the reason for this error message.

In general, I am also not sure if what I have done so far is the right way to perform multisession registration on ONLY the accepted components derived after running the cnmf-e. 

I kindly ask for some help!

Many Thanks,
Daria

**Comment by DariaGiunta** [comment]
Hello together,

First many thanks for your previous help, and I am very sorry that I again ran into trouble and need your help.

The multisession registration works very well, and I am also able to collect the traces of all neurons that were registered in all of my sessions.
However, the number of registered neurons after running the multisession registration does not reflect the "real neurons" that I extracted with CNMF-E after removing the bad components.

I already tried to, instead of loading all identified components into sparse matrix A, to load only the accepted components that are saved in idx_components:

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_a_accepted= cnm.estimates.A[:,idx_components]
```
to extract the accepted spatial components and

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_c_accepted= cnm.estimates.C[idx_components]
```
to extract the accepted temporal components, but I get the following error message:

```NameError: name 'idx_components' is not defined.
```

I tried to play around with many settings and read the ‘caiman.readthedocs.io’ (https://caiman.readthedocs.io/en/latest/Getting_Started.html#variables-for-1p-processing-cnmf-e) to find out what might be the mistake, but I couldn't find out the reason for this error message.

In general, I am also not sure if what I have done so far is the right way to perform multisession registration on ONLY the accepted components derived after running the cnmf-e. 

I kindly ask for some help!

Many Thanks,
Daria

**Comment by DariaGiunta** [comment]
Hello together,

First many thanks for your previous help, and I am very sorry that I again ran into trouble and need your help.

The multisession registration works very well, and I am also able to collect the traces of all neurons that were registered in all of my sessions.
However, the number of registered neurons after running the multisession registration does not reflect the "real neurons" that I extracted with CNMF-E after removing the bad components.

I already tried to, instead of loading all identified components into sparse matrix A, to load only the accepted components that are saved in ```idx_components``` :

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_a_accepted= cnm.estimates.A[:,idx_components] ```
to extract the accepted spatial components and

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_c_accepted= cnm.estimates.C[idx_components] ```
to extract the accepted temporal components, but I get the following error message:

```NameError: name 'idx_components' is not defined.
```

I tried to play around with many settings and read the ‘caiman.readthedocs.io’ (https://caiman.readthedocs.io/en/latest/Getting_Started.html#variables-for-1p-processing-cnmf-e) to find out what might be the mistake, but I couldn't find out the reason for this error message.

In general, I am also not sure if what I have done so far is the right way to perform multisession registration on ONLY the accepted components derived after running the cnmf-e. 

I kindly ask for some help!

Many Thanks,
Daria

**Comment by DariaGiunta** [comment]
Hello together,

First many thanks for your previous help, and I am very sorry that I again ran into trouble and need your help.

The multisession registration works very well, and I am also able to collect the traces of all neurons that were registered in all of my sessions.
However, the number of registered neurons after running the multisession registration does not reflect the "real neurons" that I extracted with CNMF-E after removing the bad components.

I already tried to, instead of loading all identified components into sparse matrix A, to load only the accepted components that are saved in idx_components:

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_a_accepted= cnm.estimates.A[:,idx_components]
```

to extract the accepted spatial components and

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_c_accepted= cnm.estimates.C[idx_components]
```

to extract the accepted temporal components, but I get the following error message:

```NameError: name 'idx_components' is not defined.
```

I tried to play around with many settings and read the ‘caiman.readthedocs.io’ (https://caiman.readthedocs.io/en/latest/Getting_Started.html#variables-for-1p-processing-cnmf-e) to find out what might be the mistake, but I couldn't find out the reason for this error message.

In general, I am also not sure if what I have done so far is the right way to perform multisession registration on ONLY the accepted components derived after running the cnmf-e. 

I kindly ask for some help!

Many Thanks,
Daria

**Comment by DariaGiunta** [comment]
Hello together,

First many thanks for your previous help, and I am very sorry that I again ran into trouble and need your help.

The multisession registration works very well, and I am also able to collect the traces of all neurons that were registered in all of my sessions.
However, the number of registered neurons after running the multisession registration does not reflect the "real neurons" that I extracted with CNMF-E after removing the bad components.

I already tried to, instead of loading all identified components into sparse matrix A, to load only the accepted components that are saved in [idx_components]:

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_a_accepted= cnm.estimates.A[:,idx_components]
```
to extract the accepted spatial components and

```cnm=cm.source_extraction.cnmf.cnmf.load_CNMF('myvideos')
est_c_accepted= cnm.estimates.C[idx_components]```

to extract the accepted temporal components, but I get the following error message:

```NameError: name 'idx_components' is not defined.
```

I tried to play around with many settings and read the ‘caiman.readthedocs.io’ (https://caiman.readthedocs.io/en/latest/Getting_Started.html#variables-for-1p-processing-cnmf-e) to find out what might be the mistake, but I couldn't find out the reason for this error message.

In general, I am also not sure if what I have done so far is the right way to perform multisession registration on ONLY the accepted components derived after running the cnmf-e. 

I kindly ask for some help!

Many Thanks,
Daria

**Comment by j-friedrich** [comment]
The accepted components are saved in `cnm.estimates.idx_components` not `idx_components`, thus `est_a_accepted= cnm.estimates.A[:,cnm.estimates.idx_components]`

**Comment by DariaGiunta** [comment]
It worked. Thank you so much @j-friedrich!

**Comment by DariaGiunta** [comment]
Hello together, 

I am sorry, it's me again. 

Sadly I have an error message occuring when I try to run the following command:

```
traces = np.zeros(assignments_filtered.shape, dtype=np.ndarray)
for i in range(traces.shape[0]):
    for j in range(traces.shape[1]):
        traces[i,j] = temporal_ms36[j][int(assignments_filtered[i,j])]
```

I get the following error message: 

```
  File "<ipython-input-64-e4fcafeeb9e8>", line 4, in <module>
    traces[i,j] = temporal_ms36[j][int(assignments_filtered[i,j])]
IndexError: index 29 is out of bounds for axis 0 with size 29
```

No matter which videos I try to register, even if I register the same video multiple times, this error message always occurs. 
As I really can’t explain these errors to myself I kindly ask for some help!

Thank you very much and wish you all the best,
Daria

**Comment by j-friedrich** [comment]
What's `temporal_ms36`? Please check the shapes `assignments_filtered.shape` and `temporal_ms36.shape` (or `np.shape(temporal_ms36)` it it's a list of lists) to see where the indexing does not match up.

**Comment by DariaGiunta** [comment]
Thank you for the fast reply @j-friedrich!

temporal_ms36 is a list (type: float64) containing numpy arrays with the temporal traces of the accepted components (cnm.estimates.C[cnm.estimates.idx_components]) from the registered videos. This, I created in order to combinine the data dereived from the multidays registration with the temporal traces of my accepted components over the multiple sessions. 

According to the instructions of the multisession registration demo from GitHub: https://github.com/flatironinstitute/CaImAn/blob/5af22564d8771342212b0e67e97df800f5a85537/demos/notebooks/demo_multisession_registration.ipynb, I created a pickle file containing a list of spatial and temporal footprints of the accepted components and template images of each session.

I constructed the list as following: 
1. a list of spatial footprints of the accepted components for all sessions by doing:
```
cnm=cm.source_extraction.cnmf.cnmf.load_CNMF(mydata)
est_a=cnm.estimates.A[:,cnm.estimates.idx_components]
```
2. a list of templates (correlation images) for each session. Therefore I extracted the cn_filter data, computed during the summary images computation step of the caiman pipeline by doing:
```
corr_image = np.array(cn_filter)
np.save('path.npy', corr_image, allow_pickle=True)
```
3. a list of temporal traces of the accepted components for all sessions by doing: 
```
cnm=cm.source_extraction.cnmf.cnmf.load_CNMF(mydata)
est_c=cnm.estimates.C[cnm.estimates.idx_components]
```

This list I then used to run the multidays registration. 

When I checked the shape of "assignments_filtered" I get a list (type int64, numpy array) with 53 rows and 2 columns, according to my in this case 2 registered videos with 53 accepted components that I used for testing.  
However, when I check the shape of temporal_ms36 by using "np.shape(temporal_ms36)" I get the following shape: (2, 29, 20401).

I guess this might be the reason for my trouble, but I don't really understand what went wrong creating my lists for the multisession registration, as for both the temporal and spatial traces, I picked the data from only the accepted components. 

Maybe you can see what my mistake was. Thank you very much for all the help!

All the best, 
Daria

**Comment by epnev** [comment]
I think what happens is that 29 neurons were found present in both  sessions so your `temporal_ms36` matrix contains the trace of each of these neurons in each session, and there is nothing that went wrong with that. That's my sense based on the information you provide. I'm closing this issue because you did not report any errors.

**Comment by paulklemm** [comment]
Hi there. Maybe I can help clarify this. The error occurs when running the following code from https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_multisession_registration.ipynb:

```python
traces = np.zeros(assignments_filtered.shape, dtype=np.ndarray)
for i in range(traces.shape[0]):
    for j in range(traces.shape[1]):
        traces[i,j] = cnm_list[j].estimates.C[int(assignments_filtered[i,j])]

# Error:
#     traces[i,j] = temporal[j][int(assignments_filtered[i,j])]
# IndexError: index 29 is out of bounds for axis 0 with size 29
```

It can very well be that only 29 matching neurons are found in the session, but why is `traces = np.zeros(assignments_filtered.shape, dtype=np.ndarray)` then creating a matrix with wrong dimensions?

**Comment by paulklemm** [comment]
Sorry to bother you, do we need to reopen a new issue for this one?

**Comment by pgunn** [comment]
@j-friedrich ^^

**Comment by epnev** [comment]
@paulklemm 

> Hi there. Maybe I can help clarify this. The error occurs when running the following code from https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_multisession_registration.ipynb:
> 
> ```python
> traces = np.zeros(assignments_filtered.shape, dtype=np.ndarray)
> for i in range(traces.shape[0]):
>     for j in range(traces.shape[1]):
>         traces[i,j] = cnm_list[j].estimates.C[int(assignments_filtered[i,j])]
> 
> # Error:
> #     traces[i,j] = temporal[j][int(assignments_filtered[i,j])]
> # IndexError: index 29 is out of bounds for axis 0 with size 29
> ```
> 
> It can very well be that only 29 matching neurons are found in the session, but why is `traces = np.zeros(assignments_filtered.shape, dtype=np.ndarray)` then creating a matrix with wrong dimensions?

Because it may very well be that `assignments_filtered` has only the components that are found in both sessions. In the demo notebook it is defined as the components that are found in all six sessions.

**Comment by paulklemm** [comment]
> Because it may very well be that `assignments_filtered` has only the components that are found in both sessions. In the demo notebook it is defined as the components that are found in all six sessions.

Makes sense to me. In the example, you required the components to be found in all 6 sessions.
```python
n_reg = 6  # minimal number of sessions that each component has to be registered in
```

In our case we have three sessions and set `n_reg = 3`. It's odd that the shape of `assignments_filtered` is larger than 29 when only 29 components are found in all three sessions. I just want to make sure we do not accidentally pull the traces of the wrong components.

**Comment by epnev** [comment]
@paulklemm @DariaGiunta I verified that the script in the demo runs without any issues. I do not know what the problem in your case is but there is not much we can do with the information you provided. I recommend you spend a little bit of time to understand the logic behind the output variables `assignments` and `matchings` of the registration function. Once you have done that you should be able to extract the information you need (either using the scripts in the demo or by writing your own).

**Comment by paulklemm** [comment]
@epnev Thanks a lot for all the info. We were able to fix the problem we're having. We were retrieving the components wrong. Now everything runs fine.

Thank you all so much for your help.
