### ISSUE TITLE
No neuron cells detected from 1d photon data

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#744]
Hi,
Using Caiman 1 photon demo - demo_pipeline_cnmfE.ipynb (with gSig=[5,5] and smaller values, fr=20), no neurons are detected. At max, 2 spatial components are detected but that is about it. 
We expect >=70 neurons. We get that the video quality maybe poor. We tried using Min1Pipe and got 142 cells but we'd like to adopt Caiman. Can you pls advice. 

Here is a sample gif of  one of the sessions. 
![test1](https://user-images.githubusercontent.com/721570/80096848-37c55a00-85a5-11ea-8015-5cb5828b978b.gif)

Must i upsample/downsample this video to detect more cells ?

**Comment by epnev** [comment]
@akatav When you run the `inspect_correlation_pnr` you should adjust the parameters `min_corr` and `min_pnr` such that neurons become visible and then set them to these values.

**Comment by akatav** [comment]
@epnev thanks.i am running on a server, so not really able to see the figure and adjust the values accordingly.Is there a way to save the figures (alongwith the Sliders) ? I tried pickling the 'fig' in inspect_correlation_pnr() but it only saves as static png. How to save the figure alongwith the sliders dynamically?

**Comment by j-friedrich** [comment]
@akatav you could just save the output arrays of `caiman.summary_images.correlation_pnr()` and run `inspect_correlation_pnr()` locally.

What I often do to display graphics while running on a cluster node is to run jupyter notebook with the --no-browser option. If you start it on the remote server via
`jupyter notebook --ip=$(hostname -i) --no-browser`
it will tell you an URL to open up locally in your browser.
(If that doesn't work you probably would need to do some ssh port forwarding)

**Comment by epnev** [comment]
@akatav I'd also suggest to analyze one of your datasets locally in an interactive manner to set the required parameters.

**Comment by akatav** [comment]
@epnev @j-friedrich silly question perhaps, i am using jupyter notebook and using inspect_correlation_pnr(), but the slider does not seem to work ? 
I used nb_inspect_correlation_pnr() and it gives the following o/p:
:Layout
   .AdjointLayout.Correlation :AdjointLayout
      :Image   [x,y]   (corr)
      :DynamicMap   []
   .AdjointLayout.Pnr         :AdjointLayout
      :Image   [x,y]   (pnr)
      :DynamicMap   []

**Comment by j-friedrich** [comment]
Did you execute the line `hv.notebook_extension('bokeh')`?
W/o it I get your output as well. You might have to update holoviews to version 1.13.

Another option that does not rely on holoviews is to use function  `caiman.utils.visualization.inspect_correlation_pnr`

**Comment by akatav** [comment]
@j-friedrich thank you,yes, that helped. actually, the broader issue we're having is that, in our original .avi files of mice brain (sample for which has been attached as gif in this thread), despite varying the min_corr and min_pnr thresholds, no cells seem to become visible. Like below:
![image](https://user-images.githubusercontent.com/721570/81246301-2888e680-9052-11ea-8218-e5bd7b564840.png)
does this mean that there are no cells at all in this session or that imaging quality is poor? I use gSig size of (3,3). These are my other params:
fr = 20                          # movie frame rate
decay_time = 0.4                 # length of a typical transient in seconds
motion_correct = True            # flag for motion correction
pw_rigid = False                 # flag for pw-rigid motion correction
gSig_filt = (3,3)   # size of filter, in general gSig (see below),
max_shifts = (5, 5)  # maximum allowed rigid shift
strides = (48,48)   # start a new patch for pw-rigid motion correction every x pixels
overlaps = (24, 24)  # overlap between pathes (size of patch strides+overlaps)
# maximum deviation allowed for patch with respect to rigid shifts
max_deviation_rigid = 3
border_nan = 'copy'
p = 2               # order of the autoregressive system
K = None            # upper bound on number of components per patch, in general None for 1p data
gSig = (3,3)       # gaussian width of a 2D gaussian kernel, which approximates a neuron
gSiz = (13,13)     # average diameter of a neuron, in general 4*gSig+1
Ain = None          # possibility to seed with predetermined binary masks
merge_thr = .7      # merging threshold, max correlation allowed
rf = 26             # half-size of the patches in pixels. e.g., if rf=40, patches are 80x80
stride_cnmf = 4    # amount of overlap between the patches in pixels
#                     (keep it at least large as gSiz, i.e 4 times the neuron size gSig)
tsub = 2            # downsampling factor in time for initialization,
#                     increase if you have memory problems
ssub = 2            # downsampling factor in space for initialization,
#                     increase if you have memory problems
#                     you can pass them here as boolean vectors
low_rank_background = None  # None leaves background of each patch intact,
#                     True performs global low-rank approximation if gnb>0
gnb = 0             # number of background components (rank) if positive,
#                     else exact ring model with following settings
#                         gnb= 0: Return background as b and W
#                      bord_px = 0 if border_nan is 'copy' else bord_px
#      gnb=-1: Return full rank background B
#                         gnb<-1: Don't return background
nb_patch = 0        # number of background components (rank) per patch if gnb>0,
#                     else it is set automatically
#min_corr = .1       # min peak value from correlation image
#min_pnr = 3        # min peak to noise ration from PNR image
ssub_B = 2          # additional downsampling factor in space for background
ring_size_factor = 1.4  # radius of ring is gSiz*ring_size_factor
dims=(480,752)

**Comment by j-friedrich** [comment]
vmin has to be smaller than vmax, these are the lower and upper saturation values for plotting respectively.
make sure that `center_psf=True`
Are you at least able to see the cells in the correlation and pnr image before adjusting the vmin-vmax range?

**Comment by akatav** [comment]
@j-friedrich  yes, center_psf is set to True as we are doing 1-p imaging. 
Actually, we do not see the cells as-is (ie, before adjusting the vmin-vmax range), unfortunately.

**Comment by pgunn** [comment]
I will look into modifying the GUI to prevent vmin and vmax from being set incorrectly.
