### ISSUE TITLE
Artefacts in display of original data and issues with parameters tuning

### ISSUE THREAD

**Issue by PaulinaWysmolek** [flatironinstitute/CaImAn#746]
Operating system (Linux/macOS/Windows):
macOS High Sierra (10.13.6)

Python version (3.x):
3.6.10

Working environment (Python IDE/Jupyter Notebook/other):
Jupyter Notebook (opened via Anaconda Navigator)

Which of the demo scripts you're using for your analysis (if applicable):
demo_pipeline_cnmfE 

CaImAn version*:
1.8.3 

CaImAn installation process (pip install ./pip install -e ./conda):
For installation I used

```
git clone https://github.com/flatironinstitute/CaImAn
cd CaImAn/
conda env create -f environment.yml -n caiman
source activate caiman
pip install -e

```
Hello,
I would kindly like to ask for your help with two issues - in both cases I am referring to the analysis done with the demo_pipeline_cnmfE. I apologize in advanced as the problems I will mention are probably resulting from my lack of understanding of some basic things...

I was trying to analyse two data sets- both xyt stacks (256x256, 16-bit) - I will refer to them as  a) and b):
a) had 100 planes 
b) second 20 planes
Also, they were both obtained as MIP of xyzt stacks.

Upon inspection in programs such as ImageJ they seem similar, however a) has overall more signal and saturated pixels.

![hist](https://user-images.githubusercontent.com/64419168/80594559-85b5e400-8a23-11ea-852d-a3d90aadecab.png)

Issue 1.
 I was not able to get any component identified for the b) dataset. I did try to be less restrictive and play with the `min_corr` and `min_pnr` values in the parameters, as well as to lower the `min_SNR`  and   `r_values_min `,  turned `use_cnn` to `False`  but nothing seems to have worked... The corr and pnr images look (I think) good... Just to give an idea I am showing below results for for both datasets with following parameters ( the thresholds already lowered compared to default ones... ):

![params](https://user-images.githubusercontent.com/64419168/80594894-20aebe00-8a24-11ea-9b4e-f09dd6d168b0.png)

-dataset a) that got analysed (upper left image is just a screen shot of one plane as viewed in image J)

![analized](https://user-images.githubusercontent.com/64419168/80593306-41c1df80-8a21-11ea-8c11-4512fdcc8269.png)
- dataset b) that was not analysed
![not_analized](https://user-images.githubusercontent.com/64419168/80593370-6453f880-8a21-11ea-91f4-223d6a583a36.png)
 and here is the error message : 
![error_message](https://user-images.githubusercontent.com/64419168/80593550-b8f77380-8a21-11ea-8914-583e195bf213.png)

From what I understand the error results from the fact that no components get identified and so somewhere we get a _zero_ that further causes problems...?
I would be very grateful for any suggestions!

Issue 2. 
For dataset a) that gets analysed I noticed some artefacts (something like a grid or small squares...) in the "original data" displayed in the left panel of 
```
# without background
cnm.estimates.play_movie(images, q_max=99.9, magnification=2,
                                 include_bck=False, gain_res=4, bpx=bord_px)
```
here is a simple comparison picture:

![satutrated pixels](https://user-images.githubusercontent.com/64419168/80591556-33be8f80-8a1e-11ea-9e2b-be9ab48330c7.png)

I suspect the reason for this is for this is that the original data contains saturated pixels however I am not sure about that...Would you have any suggestions regarding that and also any tips to prevent this from happening/ how to improve on these output images ?

In any case thank you very much for your time reading this!
I would be very grateful for your help.

Many thanks and best regards,
Paulina

**Comment by j-friedrich** [comment]
Hi Paulina,
your pnr values are quite low. Have you tried even lower values for `min_pnr` to detect more components?
You can also use `caiman.utils.visualization.inspect_correlation_pnr` and adjust vmin of the pnr image to see which components are actually above the threshold.

I am unsure which artifacts you refer to.
If you see grid-like artifacts of the size of the patches, you could try to process without splitting the FOV in patches by setting `rf=None`, which will however take longer to run.
If you see small patches of the size of a neuron, the provided estimate for the size of a neuron might be to small and you could try a larger value for `gSiz`, though your value of 17 seems very reasonable.
It seems that some neurons have been absorbed in the background. Hopefully adjusting the `min_corr` and `min_pnr` thresholds alleviates that. 

Hope that's somewhat helpful,
Johannes

**Comment by PaulinaWysmolek** [comment]
Hi Johannes,

Thank you very much for your answer! Yes, I tried lowering  of `min_corr` and `min_pnr`  also before but after your suggestion I did it pretty radically and it somehow solved the problem for this dataset (some neurons still did not get identified). 

The "grid" appears in the original data & residuals "without the background"- so I assume it's the result of the background subtraction that causes this effect?  I increased the neuron size (`gSiz` ) but it did not help.

here is an example of the original data without background when  `gSiz = 30` :
![grid_rf_30](https://user-images.githubusercontent.com/64419168/81336584-e4293500-90a9-11ea-921e-25a6534abea0.jpg)

(just for sake of consistency, I am also showing how it more or less looks like with `rf = None`)
![grid_rf_None](https://user-images.githubusercontent.com/64419168/81336782-3a967380-90aa-11ea-8c08-cf45f3afa8b4.jpg)

I am sorry for the bother - I just would like to know if I have to modify something to improve this or if this is "normal" for low resolution, small datasets.

Thanks again for your time and help*
All the best,
Paulina

 
* Also with the issue #745 :)

**Comment by j-friedrich** [comment]
Hi Paulina,
while I wouldn't be too concerned about the background, one other thing you could try is to vary the ring_size_factor. Good values seem to be typically in the range 1.4 to 2.
Some neurons might not have been detected and been absorbed in the background, yielding some artifacts. To help with neurons that still do not get identified, I have some preliminary code to add them manually. I'll let you know once that is added to caiman.

**Comment by PaulinaWysmolek** [comment]
Dear Johannes,

thank you very much for your answer and help. Yes I would be very happy to get this information :)
The truth is I still have a lot of questions and I thought I would open another case to make it clearer - it's case [#771](https://github.com/flatironinstitute/CaImAn/issues/771)... :)

I am really grateful for all your help!
All the best,
Paulina

**Comment by j-friedrich** [comment]
Hi Paulina,
excuse the very long delay. I just pushed some of my recent changes to the dev branch for now. There is a new parameter `seed_method` that is `auto` by default. For only manual ROI detection set it to `manual`. I used a mix of both, setting it to `semi` and setting `init_iter` to `2`. With these setting one (`n_iter-1`) round of automatic ROI detection is performed, and in a second round you can manually add ROIs by clicking in the figure that pops up and displays the correlation and PNR images as well as their product. The time series of the pixel you clicked on will be displayed. If it doesn't look like a neural trace to you, you can click again to remove the ROI. 
I've only tested this running python in the terminal, it might not work in jupyter notebook or only with certain matplotlib backends.

I'll take a look at the other issue you opened.

**Comment by j-friedrich** [comment]
The option to manually add components during initialization has been added in the recent 1.8.5 release.
