### ISSUE TITLE
error from isolated call of  tile_and_correct_3d

### ISSUE THREAD

**Issue by MaximilianHoffmann** [flatironinstitute/CaImAn#753]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting dview=None.

If you need to upgrade CaImAn follow the instructions given in the documentation.

Tell us a bit about your setup:

 Operating system (Linux/macOS/Windows):
   Linux

   Python version (3.x):
   3.7

   Working environment (Python IDE/Jupyter Notebook/other):
   jupyter notebook
   Which of the demo scripts you're using for your analysis (if applicable):

   CaImAn version*:
    just pulled from master.

   CaImAn installation process (pip install ./pip install -e ./conda):
   pip install -e . 
   I installed the environment-minimal.yml

   Describe the issue that you are experiencing

I wanted to test the motion correction without employing the whole pipeline.
(I copied all the used functions into an isolated normcorre.py file)

When calling

```
from caiman.motion_correction import tile_and_correct_3d

import numpy as np                                                      
a=np.random.rand(100,100,100)                                           
b=np.random.rand(100,100,100)                                           
tile_and_correct_3d(a,b,[20,20,20],[5,5,5],[2,2,2])  
```
yields
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-59f40a3b606d> in <module>
      3 a=np.random.rand(100,100,100)
      4 b=np.random.rand(100,100,100)
----> 5 tile_and_correct_3d(a,b,[20,20,20],[5,5,5],[2,2,2]
      6 
      7 

/fast/work/users/hoffmmax_c/repos/CaImAn/caiman/motion_correction.py in tile_and_correct_3d(img, template, strides, overlaps, max_shifts, newoverlaps, newstrides, upsample_factor_grid, upsample_factor_fft, show_movie, max_deviation_rigid, add_to_movie, shifts_opencv, gSig_filt, use_cuda, border_nan)
   2457             half_overlap_z = np.int(newoverlaps[2] / 2)
   2458 
-> 2459             for (x, y, z), (idx_0, idx_1, idx_2), im, (_, _, _), weight_mat in zip(start_step, xyz_grid, imgs, total_shifts, weight_matrix):
   2460 
   2461                 if idx_0 == 0:

/fast/work/users/hoffmmax_c/repos/CaImAn/caiman/motion_correction.py in create_weight_matrix_for_blending(img, overlaps, strides)
   1976         if grid_1 < max_grid_1:
   1977             weight_mat[-overlaps[0]:,
-> 1978                        :] = np.linspace(1, 0, overlaps[0])[:, None]
   1979         if grid_2 > 0:
   1980             weight_mat[:, :overlaps[1]] = weight_mat[:, :overlaps[1]

ValueError: could not broadcast input array from shape (5,1) into shape (5,10,10)
```

**Comment by epnev** [comment]
@MaximilianHoffmann Try setting `shifts_opencv = True`. It's the only type of shifts that is supported for 3d.

**Comment by MaximilianHoffmann** [comment]
thanks, that works. And thanks for the great package. It would be cool if there would be a list of things, that do not work in 3d or an exception, that is caught. ( #415 ) .

**Comment by epnev** [comment]
I know.. we haven't spent much time on 3D so issues like that arise. However if you use the code from the standard API the flag would have been set automatically to its correct value.

**Comment by epnev** [comment]
@pgunn Can you modify `caiman.motion_correction.tile_and_correct_3d` to have as default `shifts_opencv = True`? Thanks

**Comment by pgunn** [comment]
@epnev Will do.

**Comment by MaximilianHoffmann** [comment]
[This](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/motion_correction.py#L2369) seem like the switch is not actually necessary right now, also it doesn't use cv, but scikit image instead. Maybe it would be better to just drop it there?
