### ISSUE TITLE
Components detected after multisession registration not visible in fov

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#758]
Hi,
Below is the output of register_multisession (6 sessions) plotted using plot_contours(). 
![register_op](https://user-images.githubusercontent.com/721570/82968871-3c988600-a009-11ea-9bcc-66462c7bd885.png)

As can be seen, the cells registered seem to be away from the center of the field of view and very few in number. An example plot of each session's components (idx_components) is already given in this post - #757 
Is there anyway to 
1.detect more components
2. shift the registered components more towards the center of the image ?

Values of important parameters are:
gSig=3
min_corr = .25
min_pnr = 3

Sample correlation image from one of the sessions is as below:
![image](https://user-images.githubusercontent.com/721570/82968911-4de19280-a009-11ea-8cd0-c72958e3bd8b.png)

**Comment by epnev** [comment]
@akatav I can't be sure what is happening here but here are some thoughs:
- It might be the case that having the same neurons active across all six sessions is not common.
- The images look fairly noisy so it is possible that the FOV alignment between days is failing and needs to be adjusted.
- Similar to above, the parameters of the registration script might need to be adjusted
- The image on top seems square whereas the images on the bottom are not. Just making sure that you're plotting things correctly.

**Comment by akatav** [comment]
@epnev thank you. i apologize, i think i uploaded the wrong images. I think that the images now look better than before?
