### ISSUE TITLE
Error AttributeError: 'tuple' object has no attribute 'step'

### ISSUE THREAD

**Issue by donglabimaging** [flatironinstitute/CaImAn#762]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows 10
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Anaconda 

 4. Which of the demo scripts you're using for your analysis (if applicable):
This error is occurring when we run the "Pipeline for microendoscopic data processing in CaImAn using the CNMF-E algorithm".
 
 6. CaImAn installation process:
 `conda install -c conda-forge caiman`

- **Describe the issue that you are experiencing**
We previously posted about a problem we encountered with the updating CaImAn (5/22/2020) Now, we have encountered a new problem. We are able to run the pipeline until the "Do some plotting" for the accepted components. The error we encountered occurs when running the following line. 
```
# accepted components
cnm.estimates.nb_view_components(img=cn_filter, idx=cnm.estimates.idx_components,
                                denoised_color='red', cmap='gray')
```
Please see below for the error we are experiencing. Any feedback will be appreciated!

- **Copy error log below**
TypeError                                 Traceback (most recent call last)
~\Anaconda3\envs\caiman\lib\site-packages\numpy\lib\index_tricks.py in __getitem__(self, key)
    163                     size.append(
--> 164                         int(math.ceil((key[k].stop - start)/(step*1.0))))
    165                 if (isinstance(step, float) or

TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-17-b1f26a955500> in <module>
      1 # accepted components
      2 cnm.estimates.nb_view_components(img=cn_filter, idx=cnm.estimates.idx_components,
----> 3                                 denoised_color='red', cmap='gray')

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\estimates.py in nb_view_components(self, Yr, img, idx, denoised_color, cmap, thr)
    397                                                         self.C[idx], self.b, self.f,
    398                                                         self.dims[0], self.dims[1], YrA=self.R[idx], image_neurons=img,
--> 399                                                         thr=thr, denoised_color=denoised_color, cmap=cmap)
    400         return self
    401 

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\visualization.py in nb_view_patches(Yr, A, C, b, f, d1, d2, YrA, image_neurons, thr, denoised_color, cmap)
    183         image_neurons = A.mean(1).reshape((d1, d2), order='F')
    184 
--> 185     coors = get_contours(A, (d1, d2), thr)
    186     cc1 = [cor['coordinates'][:, 0] for cor in coors]
    187     cc2 = [cor['coordinates'][:, 1] for cor in coors]

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\visualization.py in get_contours(A, dims, thr, thr_method, swap_dim)
    354     else:
    355         d1, d2 = dims
--> 356         x, y = np.mgrid[0:d1:1, 0:d2:1]
    357 
    358     coordinates = []

~\Anaconda3\envs\caiman\lib\site-packages\numpy\lib\index_tricks.py in __getitem__(self, key)
    192             return nn
    193         except (IndexError, TypeError):
--> 194             step = key.step
    195             stop = key.stop
    196             start = key.start

AttributeError: 'tuple' object has no attribute 'step'

**Comment by pgunn** [comment]
Hi,
Do you mind editing the following file: Anaconda3\envs\caiman\lib\site-packages\caiman\utils\visualization.py

adding a new line after line 355, which is `d1, d2 = dims`
a line saying the following (with the same indentation as the lines before):

```print(f"Computing grid with dims {d1} and {d2}")```

Then rerun the computation and tell me what the output is right before the crash. Thanks

**Comment by donglabimaging** [comment]
We added the line of code to that file, but the same error occurred.  It looks like the additional line of code did not get integrated.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\Anaconda3\envs\caiman\lib\site-packages\numpy\lib\index_tricks.py in __getitem__(self, key)
    163                     size.append(
--> 164                         int(math.ceil((key[k].stop - start)/(step*1.0))))
    165                 if (isinstance(step, float) or

TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-16-b1f26a955500> in <module>
      1 # accepted components
      2 cnm.estimates.nb_view_components(img=cn_filter, idx=cnm.estimates.idx_components,
----> 3                                 denoised_color='red', cmap='gray')

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\estimates.py in nb_view_components(self, Yr, img, idx, denoised_color, cmap, thr)
    397                                                         self.C[idx], self.b, self.f,
    398                                                         self.dims[0], self.dims[1], YrA=self.R[idx], image_neurons=img,
--> 399                                                         thr=thr, denoised_color=denoised_color, cmap=cmap)
    400         return self
    401 

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\visualization.py in nb_view_patches(Yr, A, C, b, f, d1, d2, YrA, image_neurons, thr, denoised_color, cmap)
    183         image_neurons = A.mean(1).reshape((d1, d2), order='F')
    184 
--> 185     coors = get_contours(A, (d1, d2), thr)
    186     cc1 = [cor['coordinates'][:, 0] for cor in coors]
    187     cc2 = [cor['coordinates'][:, 1] for cor in coors]

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\visualization.py in get_contours(A, dims, thr, thr_method, swap_dim)
    354     else:
    355         d1, d2 = dims
--> 356         x, y = np.mgrid[0:d1:1, 0:d2:1]
    357 
    358     coordinates = []

~\Anaconda3\envs\caiman\lib\site-packages\numpy\lib\index_tricks.py in __getitem__(self, key)
    192             return nn
    193         except (IndexError, TypeError):
--> 194             step = key.step
    195             stop = key.stop
    196             start = key.start

AttributeError: 'tuple' object has no attribute 'step'

**Comment by pgunn** [comment]
It should've been output before the error display started.

**Comment by donglabimaging** [comment]
That's what I was expecting, but it did not.
![Capture](https://user-images.githubusercontent.com/50585879/83303703-8761fb80-a1cb-11ea-81b2-45ecc769f693.PNG)

**Comment by pgunn** [comment]
It's possible the output landed in the terminal that you used to launch jupyter.

**Comment by donglabimaging** [comment]
The additional line was not saved in the visualization.py file.  

Here is the output:
Computing grid with dims (320, 320) and (320, 320)

**Comment by pgunn** [comment]
That's surprising - somehow the dimensions ended up really being tuples rather than single values. Let me see if I can figure out how that might have happened. Have you modified the notebook much? Do any of your modifications add dimensions parameters?

**Comment by donglabimaging** [comment]
@pgunn 
Other than changing the parameters frame rate, decay time, gSig, gSiz, we did not modify the notebook at all.

**Comment by donglabimaging** [comment]
@pgunn 
The code ran fine if we select only one file.
`fnames = [r'D:\layer1\layer2\layer3\layer4\msCam1.avi']`

If i run the following line, the error shows up.
`fnames = [r'D:\layer1\layer2\layer3\layer4\msCam1.avi', r'D:\layer1\layer2\layer3\layer4\msCam2.avi']`

May I ask how I can select multiple files?

**Comment by pgunn** [comment]
I'm looking into it. On first glance what you're doing looks correct.

**Comment by donglabimaging** [comment]
I thought I did not made the list correctly.  Thank you for looking into it.  I appreciate your help as always.

**Comment by epnev** [comment]
@donglabimaging What is the value of `cnm.estimates.idx_components`?

**Comment by donglabimaging** [comment]
@epnev 
`print(cnm.estimates.idx_components)`
gives [1 2]

**Comment by epnev** [comment]
@donglabimaging Can you go at [this file](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/source_extraction/cnmf/utilities.py#L1052) below line 1052 and add
```
dims = dims[0]
```
I believe this should fix it. Please confirm. 

@pgunn this is very confusing.

**Comment by pgunn** [comment]
@epnev I'm wondering if there might be something odd in the particular data sets that leads the attempt to concatenate them to not do it properly; maybe if the data comes back wrapped like [data] it might not flatten correctly. I've treated our general code and at least with normal files we have lying around it doesn't seem to do this.

@donglabimaging are there movies that exhibit the problem that are small enough that you might be able to share them with us?

**Comment by donglabimaging** [comment]
I made the suggested addition to the file mentioned above by @epnev and received the same error:

Computing grid with dims (320, 320) and (320, 320)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\Anaconda3\envs\caiman\lib\site-packages\numpy\lib\index_tricks.py in __getitem__(self, key)
    163                     size.append(
--> 164                         int(math.ceil((key[k].stop - start)/(step*1.0))))
    165                 if (isinstance(step, float) or

TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-17-b1f26a955500> in <module>
      1 # accepted components
      2 cnm.estimates.nb_view_components(img=cn_filter, idx=cnm.estimates.idx_components,
----> 3                                 denoised_color='red', cmap='gray')

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\estimates.py in nb_view_components(self, Yr, img, idx, denoised_color, cmap, thr)
    397                                                         self.C[idx], self.b, self.f,
    398                                                         self.dims[0], self.dims[1], YrA=self.R[idx], image_neurons=img,
--> 399                                                         thr=thr, denoised_color=denoised_color, cmap=cmap)
    400         return self
    401 

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\visualization.py in nb_view_patches(Yr, A, C, b, f, d1, d2, YrA, image_neurons, thr, denoised_color, cmap)
    183         image_neurons = A.mean(1).reshape((d1, d2), order='F')
    184 
--> 185     coors = get_contours(A, (d1, d2), thr)
    186     cc1 = [cor['coordinates'][:, 0] for cor in coors]
    187     cc2 = [cor['coordinates'][:, 1] for cor in coors]

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\visualization.py in get_contours(A, dims, thr, thr_method, swap_dim)
    355         d1, d2 = dims
    356         print(f"Computing grid with dims {d1} and {d2}")
--> 357         x, y = np.mgrid[0:d1:1, 0:d2:1]
    358 
    359     coordinates = []

~\Anaconda3\envs\caiman\lib\site-packages\numpy\lib\index_tricks.py in __getitem__(self, key)
    192             return nn
    193         except (IndexError, TypeError):
--> 194             step = key.step
    195             stop = key.stop
    196             start = key.start

AttributeError: 'tuple' object has no attribute 'step' 



Here is a little more detail about our problem. We recently started using a newer version of the miniscope from UCLA, but the output .Avis seem to be different than what we have gotten previously. We previously used ImageJ to concatenate the individual msCam files, but are unable to do this with the newer miniscope files. Thus, we are attempting to call the individual files as a list in CaImAn.

[Here](https://drive.google.com/drive/folders/1uujPxuMzrQZIYZIzlt1y15CJaUHZ-1Zd?usp=sharing) are two movies to work with. Please let me know if you have trouble accessing them.

**Comment by pgunn** [comment]
Thanks - that ImageJ can't handle the new files makes me feel that the theory I was developing is more likely to be correct. I will grab one of the movies and give it a look; if I'm right, there may be a simple bit of processing you can apply to the movies before using them with ImageJ or CaImAn.

**Comment by pgunn** [comment]
@epnev I tracked it down. It's not related to his dataset, and appears to be a general bug in the code for handling file lists rather than individual files. While the parameters are being set up for CNMF, specifically in params.check_consistency(), the code calls get_file_size() which (only) in the case of a file list returns a tuple of sizes, one for every file passed in. This makes its way into the parameters, which goes through the rest of the program until it eventually chokes here. I think we haven't done enough testing with multiple files.

There are a few ways we could deal with this. I'd like to hear your thoughts.

**Comment by epnev** [comment]
> @epnev I tracked it down. It's not related to his dataset, and appears to be a general bug in the code for handling file lists rather than individual files. While the parameters are being set up for CNMF, specifically in params.check_consistency(), the code calls get_file_size() which (only) in the case of a file list returns a tuple of sizes, one for every file passed in. This makes its way into the parameters, which goes through the rest of the program until it eventually chokes here. I think we haven't done enough testing with multiple files.
> 
> There are a few ways we could deal with this. I'd like to hear your thoughts.

@pgunn The change I suggested was addressing exactly that. What confuses me is that we've been routinely processing lists of files for years with no issues. Almost feels like the code changed abruptly although git history doesn't suggest so.

**Comment by donglabimaging** [comment]
Hello @pgunn and @epnev, just reaching out to see how this is going. 

Do you have any suggestions on how to pre-process the videos before entering them into CaImAn? For instance, do you have thoughts on how to concatenate the individual videos instead of calling them as a list? We could do the concatenation as a temporary fix.

**Comment by epnev** [comment]
@donglabimaging  The error you have is just a plotting and not a processing error..
Try manually setting `cnm.estimates.dims = (320, 320)` and `cnm.dims = (320, 320)` right before your plotting function and see whether that fixes the problem.

**Comment by donglabimaging** [comment]
Hello all, we concatenated the videos in Image J and saved them as one .tif file prior to running in them through CaImAn, but now we have encountered a new error after running this line: 
```
# compute some summary images (correlation and peak to noise)
cn_filter, pnr = cm.summary_images.correlation_pnr(images[::5], gSig=gSig[0], swap_dim=False) # change swap dim if output looks weird, it is a problem with tiffile
# inspect the summary images and set the parameters
inspect_correlation_pnr(cn_filter, pnr)
```

Below is the error:
---------------------------------------------------------------------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-17949c1703f7> in <module>
      2 cn_filter, pnr = cm.summary_images.correlation_pnr(images[::5], gSig=gSig[0], swap_dim=False) # change swap dim if output looks weird, it is a problem with tiffile
      3 # inspect the summary images and set the parameters
----> 4 inspect_correlation_pnr(cn_filter, pnr)
      5 
      6 # Takes about 10 min #

~\Anaconda3\envs\caiman\lib\site-packages\caiman\utils\visualization.py in inspect_correlation_pnr(correlation_image_pnr, pnr_image)
   1136 
   1137     s_cn_max = Slider(pl.axes([0.05, 0.01, 0.35, 0.03]), 'vmax',
-> 1138                       correlation_image_pnr.min(), correlation_image_pnr.max(), valinit=correlation_image_pnr.max())
   1139     s_cn_min = Slider(pl.axes([0.05, 0.07, 0.35, 0.03]), 'vmin',
   1140                       correlation_image_pnr.min(), correlation_image_pnr.max(), valinit=correlation_image_pnr.min())

~\Anaconda3\envs\caiman\lib\site-packages\matplotlib\widgets.py in __init__(self, ax, label, valmin, valmax, valinit, valfmt, closedmin, closedmax, slidermin, slidermax, dragging, valstep, orientation, **kwargs)
    352             ax.set_ylim((valmin, valmax))
    353         else:
--> 354             ax.set_xlim((valmin, valmax))
    355         ax.set_xticks([])
    356         ax.set_navigate(False)

~\Anaconda3\envs\caiman\lib\site-packages\matplotlib\axes\_base.py in set_xlim(self, left, right, emit, auto, xmin, xmax)
   3182 
   3183         self._process_unit_info(xdata=(left, right))
-> 3184         left = self._validate_converted_limits(left, self.convert_xunits)
   3185         right = self._validate_converted_limits(right, self.convert_xunits)
   3186 

~\Anaconda3\envs\caiman\lib\site-packages\matplotlib\axes\_base.py in _validate_converted_limits(self, limit, convert)
   3099             if (isinstance(converted_limit, Real)
   3100                     and not np.isfinite(converted_limit)):
-> 3101                 raise ValueError("Axis limits cannot be NaN or Inf")
   3102             return converted_limit
   3103 

ValueError: Axis limits cannot be NaN or Inf

[Here](https://drive.google.com/file/d/1M4HqpqtuHmDw10IUQD2oEYH5sfQaIxSG/view?usp=sharing) is a link to an example .tif file we use when the error occurs.

**Comment by j-friedrich** [comment]
There are presumably NaNs in `cn_filter` or `pnr` (which can happen if some pixel values don't vary in time). Can you please try `cn_filter, pnr = np.nan_to_num(cm.summary_images.correlation_pnr(images[::5], gSig=gSig[0], swap_dim=False))`

**Comment by j-friedrich** [comment]
Closing. Seems my last suggestion addressed the issue.
