### ISSUE TITLE
Seeding Online caiman (OnACID) algorithm problem

### ISSUE THREAD

**Issue by moraogando** [flatironinstitute/CaImAn#763]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows
 2. Python version (3.x): 
 3.7.4
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Noteboo
 4. Which of the demo scripts you're using for your analysis (if applicable):
 a mix between the seeded demo and the online cnmf demo
 5. CaImAn version*: 
 I cloned it about a month ago, should be very recent, yet when i followed instructions params.data['caiman_version']) I get that the field doesn't exist, but I'm not really sure if I'm doing it correctly (very new to python).
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda
- **Describe the issue that you are experiencing**
I'm trying to run seeded OnACID algorithm and I get an error during the "seeded_initialization" step. I'm very new to python so I might be entering wrong parameters, but it seems that I define a variable "model" in line 1532 but I never do the fitting to any matrix. Am I supposed to fit Ain here? 

- **Copy error log below**

AttributeError                            Traceback (most recent call last)
<ipython-input-51-e70e5697f099> in <module>
      8 cnm_on = cm.source_extraction.cnmf.online_cnmf.OnACID(params=opts)
      9 cnm_on.estimates.A = Ain
---> 10 cnm_on.fit_online()
     11 
     12 

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in fit_online(self, **kwargs)
   1135             model_LN = None
   1136         epochs = self.params.get('online', 'epochs')
-> 1137         self.initialize_online(model_LN=model_LN)
   1138         self.t_init += time()
   1139         extra_files = len(fls) - 1

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in initialize_online(self, model_LN)
   1030             self.estimates.A, self.estimates.b, self.estimates.C, self.estimates.f, self.estimates.YrA = seeded_initialization(
   1031                     Y.transpose(1, 2, 0), self.estimates.A, gnb=self.params.get('init', 'nb'), k=self.params.get('init', 'K'),
-> 1032                     gSig=self.params.get('init', 'gSig'), return_object=False)
   1033             self.estimates.S = np.zeros_like(self.estimates.C)
   1034             nr = self.estimates.C.shape[0]

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in seeded_initialization(Y, Ain, dims, init_batch, order_init, gnb, p, return_object, **kwargs)
   1531     Yr = np.reshape(Y, (Ain.shape[0], Y.shape[-1]), order='F')
   1532     model = NMF(n_components=gnb, init='nndsvdar', max_iter=10)
-> 1533     f_in = model.components_.squeeze()
   1534     f_in = np.atleast_2d(f_in)
   1535     Y_resf = np.dot(Yr, f_in.T)

AttributeError: 'NMF' object has no attribute 'components_'

Thanks a lot in advance!

**Comment by epnev** [comment]
@moraogando You're right, thanks for catching that! As you can imagine this is not a method that is being used often (and it's not fully worked out) and I wouldn't recommend using it as is.

@pgunn Can you add the line 
```_ = model.fit_transform(np.maximum(Yr[not_px], 0))``` 
between the lines 1531 and 1532 [here](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/source_extraction/cnmf/online_cnmf.py#L1531-L1532)?

**Comment by pgunn** [comment]
@epnev Are you sure you typed that correctly? There isn't a variable called _ there, so this assingment would not do anything.

**Comment by epnev** [comment]
That variable is not needed but the `model` object will be populated.

**Comment by pgunn** [comment]
Oh! Got it.

**Comment by moraogando** [comment]
Thanks so much for the very fast reply! Indeed, there's still something strange with the seeding, as I'm getting some components that are present in Ain but absent in the estimates, and many new components appear, even when I set the parameter "max_num_added = 0 ". 
I was hoping to use this seeded approach for an online analysis pipeline that reads each file as it's being created (and the segmentation of the structural channel works nicely for my datasets).
But in my hands, the "offline" CNMF is way faster. So with this advice I'll then focus on the offline algorithm.Thanks again, it's a great set of tools!

**Comment by j-friedrich** [comment]
You had to set `update_num_comps` to `False`.
With the recent commit 540cc11b14991a4f4710a9d6360d728c783897a6 it is set automatically to `False` if `max_num_added` or `min_num_trial` is `0`.

One can now also provide the masks `Ain` when creating the OnACID object, akin to the behavior of the offline CNMF object.
`cnm = online_cnmf.OnACID(params=opts, Ain=Ain)`
