### ISSUE TITLE
Plot Contours without Background?

### ISSUE THREAD

**Issue by connorjohnson1** [flatironinstitute/CaImAn#765]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x):  3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda):  pip install -e

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

I want to plot my extracted contours without a background using either the plot_contours function or the plot_contours_nb function. I can't seem to get it to work. I would like to plot all accepted components with no background. Could someone please help me achieve this? Thank you very much in advance. 

 - **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@connorjohnson1 You can try setting the background to an all zeros array with the dimensions of the FOV but it would still be a uniform background. 

Check this part of the [code](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/utils/visualization.py#L1033-L1046). You'll either have to modify the source to exclude the background image plotting or get the code below that plots the coordinates.
