### ISSUE TITLE
openh264 savemovie

### ISSUE THREAD

**Issue by CheKuangLiu** [flatironinstitute/CaImAn#766]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows 10
 2. Python version (3.x): 
 3.6.10
 3. Working environment (Python IDE/Jupyter Notebook/other):
 jupyter notebook
 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_pipeline
 5. CaImAn version*: 
 1.8.3
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
  conda
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Getting error when enabling save_movie argument when playing result movie.
cnm2.estimates.play_movie(images, q_max=99.9, gain_res=2,
                                  magnification=2,
                                  bpx=border_to_0,
                                  save_movie=True,
                                  movie_name='results_movie.avi', 
                                  display=True, 
                                  opencv_codec='H264', 
                                  use_color=False,
                                  include_bck=False)

- **Copy error log below**
[libopenh264 @ 000001bd49626780] [OpenH264] this = 0x000001BE2476BA90, Error:ParamValidationExt(), width > 0, height > 0, width * height <= 9437184, invalid 7680 x 1440 in dependency layer settings! 
[libopenh264 @ 000001bd49626780] [OpenH264] this = 0x000001BE2476BA90, Error:WelsInitEncoderExt(), ParamValidationExt failed return 2. 
[libopenh264 @ 000001bd49626780] [OpenH264] this = 0x000001BE2476BA90, Error:CWelsH264SVCEncoder::Initialize(), WelsInitEncoderExt failed. 
[libopenh264 @ 000001bd49626780] Initialize failed Could not open codec 'libopenh264': Unspecified error [ERROR:0] global ..\modules\videoio\src\cap.cpp (415) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception: OpenCV(4.2.0) ..\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): results_movie.avi in function 'cv::icvExtractPattern'

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
Could you see if this resolves the issue? Activate your environment, and then:

`conda install openh264`

**Comment by epnev** [comment]
@CheKuangLiu I would also recommend the following:
1. ```Error:ParamValidationExt(), width > 0, height > 0, width * height <= 9437184, invalid 7680 x 1440 in dependency layer settings!``` This part of the error makes me wonder whether the video is just too large. Try saving with `magnification=1` (or even lower) so the resolution is not doubled.
2. If that fails, try saving with a different codec. Unfortunately whether this works or not is system dependent but MP4V, MPEG, XVID, X264 are popular choices.
3. If all of these fail you can specify an output argument `M = cnm2.estimates.play_movie(...)` and have the output movie loaded in memory and then either use `M.save(..)` or just save it as numpy array.

**Comment by CheKuangLiu** [comment]
@epnev 
Hi, thank you for your response. Lowering the magnification worked.
