### ISSUE TITLE
Memory Error when runing  demo_behavior 

### ISSUE THREAD

**Issue by yfj33** [flatironinstitute/CaImAn#774]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows 10
 2. Python version (3.x): 
 3.7.6
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook
 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_behavior.py
 5. CaImAn version*: 
 1.8.4
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda activate caiman
pip install -e .  # OR `pip install .` if you don't want to develop code
copy caimanmanager.py ..
cd ..
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Hello, I was trying to use the demo_behavior file to analyze my video and I tried to run the demo provided first. However, the program shows the following error:

"MemoryError: Unable to allocate 1.51 GiB for an array with shape (5277, 240, 320) and data type float32"

I am new to python so appreciate if you could give some tips on this issue. Thanks so much!

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
I'm not familiar with the behavior analysis demo. @agiovann might have some thoughts.

**Comment by agiovann** [comment]
Dear @yfj33, unfortunately the spams package (http://spams-devel.gforge.inria.fr/doc-python/html/doc_spams003.html) which the demo depends on, cannot be installed on windows. Then, we fall back on the scikit-learn package, which unfortunately is less efficient and does not scale, and therefore you  need a large amount of memory. How much is the RAM memory on your computer?

**Comment by yfj33** [comment]
Dear @agiovann, it is great to hear back from you. I had the issues of the memory and SPAMS so I switched to Linux and use a computer with RAM 64 GB and this helped me solve the problem. However, on Linux, I still have toruble running the demo_behavior.py file: after selecting the region of interest, the script didn't generate any plot. The message was:
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
30.662570238113403
demo_behavior.py:115: RuntimeWarning: invalid value encountered in less
  mask[mask < np.nanpercentile(spfl, 70)] = np.nan
demo_behavior.py:115: RuntimeWarning: invalid value encountered in less
  mask[mask < np.nanpercentile(spfl, 70)] = np.nan
demo_behavior.py:115: RuntimeWarning: invalid value encountered in less
  mask[mask < np.nanpercentile(spfl, 70)] = np.nan
demo_behavior.py:115: RuntimeWarning: invalid value encountered in less
  mask[mask < np.nanpercentile(spfl, 70)] = np.nan

Then, I used the script on my own video (10min,3GB) and was able to genrate magnitude, direction and spatial filter. However, I have sone trouble understanding the variable dataset spatial filter. does it have something to do with the heat map of mice movement as show in the automated gesture tracking paper? In addition, selecting large region of interest could also lead to the failure of the program. Therefore, it is true that I should select small region of interest and do one component at a time instead of large region with several component once? Appreciate if you could help these two problems!

**Comment by pgunn** [comment]
@yfj33 Hello,
Did you run with the environment variable OMP_NUM_THREADS set to 1? If not, could you give that a try?

**Comment by agiovann** [comment]
Closed due to inactivity
