### ISSUE TITLE
Display evaluation metrics in Estimates view_components methods?

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#775]
This is not a problem but a feature request: when viewing components, it would be really cool if we could display the individual components' evaluation metric values (spatial corr, SNR, and the confidence from the CNN, if the latter is applicable). This would apply to `view_components()`, `nb_view_components()`, and `hv_view_components()`. Frankly I don't know bokeh or holoviews well enough to pull this off right now, but I just wanted to bring this up as it is helpful seeing the parameters when viewing contours.

**Comment by epnev** [comment]
@EricThomson At this point, I can add the enhancement label in case someone wants to think about it. I agree that it can be a useful feature.

**Comment by j-friedrich** [comment]
Finally got around to add this useful feature. If the evaluation metrics have been computed they are now automatically displayed for all 3, matplotlib, bokeh and holoviews.

**Comment by EricThomson** [comment]
Thanks can't wait to check this out!
