### ISSUE TITLE
Package based installation problem on Linux

### ISSUE THREAD

**Issue by yfj33** [flatironinstitute/CaImAn#777]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Linux
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): 
 
 4. Which of the demo scripts you're using for your analysis (if applicable): behavior demo.py
 
 5. CaImAn version*: 1.8.4
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda install caiman -c conda-forge

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Hello! I was trying to install the package on Ubuntu. After I created an enviroment and tried to activate it, the error that "the shell has not been properly configured to use conda activate to initialize your shell" occurs, which didn't happen when I did it on windows. I updated the Conda but didn't help. Appreciate if you could give some advice.

- **Copy error log below**
ommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
After you got this message, did you do `conda init bash` ? If so, you should then close your current shell, open a new one, and conda should work for you.

**Comment by yfj33** [comment]
Thank you! It worked by following the link below
https://askubuntu.com/questions/849470/how-do-i-activate-a-conda-environment-in-my-bashrc
