### ISSUE TITLE
compressed video lead to different results.

### ISSUE THREAD

**Issue by SabriQ** [flatironinstitute/CaImAn#778]
- **Describe the issue that you are experiencing**
I compress the data video by ffmpeg, then its size was strikingly shrunk, with the signal almost as clear as the raw video. I analyzed the raw video and the compressed video with the same scripts. however, the total number of the neurons increased but the number of the accepted neurons hugely decrease.  the *mmap files almost have the same size.
I'm wondering caiman must ask for rawvideo or not. and how about the pix_fmt of the video?

**Comment by epnev** [comment]
That might happen if the compression scheme alters the video. caiman's behavior depends on what the video values are, and not whether it's compressed or not. I would suggest you see the movie of the difference between the original and compressed video to get a sense of how much activity was altered during compression. 

I'm closing this, but follow up if you have a specific question.
