### ISSUE TITLE
problem in caiman running in SLURM

### ISSUE THREAD

**Issue by SabriQ** [flatironinstitute/CaImAn#779]
hi, I am running caiman script in SLURM
I noticed that it was quite slow as if it was stuck somewhere when there were more than 2 task in one node.
I found a folder named "SLURM" in your Code while it has not been update for 2 years
`import ca_source_extraction as cse` is the first sentence in your `demo_slurm.py`. I tried it in ipython, however it put `ModuleNotFoundError: No module named 'ca_source_extraction'`
so, is it a problem in SLURM?

**Comment by pgunn** [comment]
Hi,
Some parts of Caiman are slurm-aware and slightly change behaviour when the slurm environment variables are found. There have been various other ways to work with slurm in the past, some of which stuck around in the codebase and probably should be removed. In general provided you set environment variables sensibly, caiman should run well under any environment, including slurm - no need to poke around in the codebase. I think our readmes cover some relevant envirionment variables you could look at relating to performance; happy to talk with you about those.

**Comment by SabriQ** [comment]
Thanks for your reply.
