### ISSUE TITLE
Crash while doing the motion correction

### ISSUE THREAD

**Issue by maxrioux100** [flatironinstitute/CaImAn#780]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 windows 10
 2. Python version (3.x): 
 3.7.6
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook
 4. Which of the demo scripts you're using for your analysis (if applicable):
 Custom one, with part from some of the demo (1p)
 5. CaImAn version*: 
 1.8.4 dev_0
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
I followed your guide for the github dev version

- **Describe the issue that you are experiencing**
I have a batch of 12 .tif files, captured in 2 days. They have all been captured with the exact same methodology. On the 12, 7 pass this step with no problem, the others 5 are crashing. I tried to find the difference by comparing 2 tif (1 faulty and 1 correct) but I can't see the difference. 

- **Copy error log below**
[Link](https://drive.google.com/drive/folders/1cXt65sWAjZo_oNpRVeo-G-5Sxj8d_1RX?usp=sharing) to the log and everything to recreate it.

Thanks a lot for you help again !

**Comment by pgunn** [comment]
Are the files things you might share with us? How big are they?

**Comment by maxrioux100** [comment]
I can share, they are between 2 and 4 gb.

**Comment by maxrioux100** [comment]
@pgunn Just shared the 2 files from the above logs with you. Just ask if you need anything

**Comment by maxrioux100** [comment]
oops, I kinda made a little mistake when trying to recreate the bug to show you.
I had set 
`mc.motion_correct(save_movie=True)` 
to
`mc.motion_correct(save_movie=False)`

I corrected the log in the first post and added everything to recreate it.

The motion correction is completing but isn't saving in the memmap(3 mb files), so the crash is happening a little bit later.

Im sorry if I lost anybody time. It wasn't my intention at all

**Comment by pgunn** [comment]
Could you also share one of the files you're having success with?

**Comment by maxrioux100** [comment]
[Working example](https://drive.google.com/drive/folders/1PLD2qyWt-HmkoFyDfDu3dTbGA-K0dxym?usp=sharing)

**Comment by epnev** [comment]
@maxrioux100 Just to clarify: Is the problem that for some of your files the motion correction works without problems, but for other it doesn't properly write a memory mapped file (for the same set of parameters)?

**Comment by j-friedrich** [comment]
@maxrioux100 your NBF.tif is somehow corrupted and doesn't load properly. Apparenlty the following lines create a repaired tiff
````
import tifffile
t = tifffile.TiffFile('NBF.tif')
tifffile.imwrite('repairedNBF.tif', np.array([tt.asarray() for tt in t.pages], dtype=np.uint16))
````
When I ran running motion correction on `repairedNBF.tif` it created a proper memmap file.

**Comment by j-friedrich** [comment]
I assume creating proper tiff files, e.g. using the code snippet in the last comment, solved the issue, thus closing it.
