### ISSUE TITLE
Saving nwb while using CNN. [Fix]

### ISSUE THREAD

**Issue by maxrioux100** [flatironinstitute/CaImAn#781]
Tell us a bit about your setup:

    Operating system (Linux/macOS/Windows):
    windows 10
    Python version (3.x):
    3.7.6
    Working environment (Python IDE/Jupyter Notebook/other):
    Jupyter Notebook
    Which of the demo scripts you're using for your analysis (if applicable):
    Custom one, with part from some of the demo (1p)
    CaImAn version*:
    1.8.4 dev_0
    CaImAn installation process (pip install ./pip install -e ./conda):
    I followed your guide for the github dev version

- Describe the issue that you are experiencing

![Error](https://user-images.githubusercontent.com/40430512/86938808-d4ac8380-c10e-11ea-894d-d1bb88891ddf.PNG)

The function to save the nwb was crashing if a CNN was used in the components evaluations step.

I changed both the lines 1598 and 1611 in estimates.py from
`if self.cnn_preds:`

to 

`if self.cnn_preds is not None:`

and everything was working fine for me

**Comment by epnev** [comment]
@maxrioux100 Thanks for this. Feel free to submit a PR with your fix.
