### ISSUE TITLE
Error at cnm.fit on 3D data: sequence argument must have length equal to input rank

### ISSUE THREAD

**Issue by SamBenezra** [flatironinstitute/CaImAn#784]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux

 2. Python version (3.x): 
 3.7

 3. Working environment (Python IDE/Jupyter Notebook/other):
 Spyder

 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 1.8.4
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I'm trying to run cnm.fit on 3D data containing dendrites, so sparse_nmf. The dimensions are 500x100x750x199 (t,x,y,z). I get an error about 1 hour into starting cnm.fit. I attached my wrapper. Here are the parameters I used:

fr = 10
p = 0                    # order of the autoregressive system
gnb = 3                  # number of global background components
merge_thr = 0.8         # merging threshold, max correlation allowed
rf = 100
# half-size of the patches in pixels. e.g., if rf=25, patches are 50x50
# for dendritic data use larger values compared to somatic imaging 
stride_cnmf = 32         # amount of overlap between the patches in pixels
K = 50                   # number of components per patch
# initialization method (if analyzing dendritic data using 'sparse_nmf')
method_init = 'sparse_nmf'
ssub = 2                     # spatial subsampling during initialization
tsub = 2                     # temporal subsampling during intialization
gSig = [20, 20, 20]

# parameters for component evaluation
opts_dict = {'fnames': fname_new,
             'p': p,
             'fr': fr,
             'nb': gnb,
             'rf': rf,
             'K': K,
             'gSig': gSig,
             'stride': stride_cnmf,
             'method_init': method_init,
             'merge_thr': merge_thr,
             'n_processes': n_processes,
             'only_init': True,
             'ssub': ssub,
             'tsub': tsub}

opts = params.CNMFParams(params_dict=opts_dict);
# %% RUN CNMF ON PATCHES
cnm = cnmf.CNMF(n_processes, params=opts, dview=None)
cnm = cnm.fit(images)

- **Copy error log below**
Traceback (most recent call last):

  File "/mnt/farscape/x1/sam/Python/3d_cnmf.py", line 119, in <module>
    cnm = cnm.fit(images)

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 606, in fit
    indices=indices)

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 259, in run_CNMF_patches
    file_res = list(map(cnmf_patches, args_in))

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 137, in cnmf_patches
    cnm = cnm.fit(images)

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 506, in fit
    self.initialize(Y)

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 975, in initialize
    **self.params.get_group('init'))

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/initialization.py", line 352, in initialize_components
    sigma_smooth=sigma_smooth_snmf, remove_baseline=remove_baseline, perc_baseline=perc_baseline_snmf)

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/initialization.py", line 569, in sparseNMF
    mode='nearest', truncate=truncate)

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/scipy/ndimage/filters.py", line 291, in gaussian_filter
    sigmas = _ni_support._normalize_sequence(sigma, input.ndim)

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/scipy/ndimage/_ni_support.py", line 65, in _normalize_sequence
    raise RuntimeError(err)

RuntimeError: sequence argument must have length equal to input rank

Wrapper:

[3d_cnmf.txt](https://github.com/flatironinstitute/CaImAn/files/4904591/3d_cnmf.txt)

**Comment by j-friedrich** [comment]
`sigma_smooth_snmf` has to be a tuple of length 4 for 3d data (3 spatial + 1 time dimension). Try setting it to (.5,.5,.5,.5) when defining the `opts_dict`

**Comment by SamBenezra** [comment]
Thanks for your response, that did the trick!

**Comment by SamBenezra** [comment]
Thanks again for your help. Caiman is pulling out some beautiful 3D dendrites! 

I have an unrelated question.

Is there a way to generate a single memmap file from a list of tifs?

Right now, I use cm.load_movie_chain to load in a list of tiffs. Then I save the 4D array to a single tif (fname). Then I run fname_new = cm.save_memmap([fname], base_name='Yr', is_3D=True, order='C') to generate the memmap file for cnmf.

This uses a lot of memory because I have to load in the entire 4D dataset first. What would you suggest?

**Comment by SamBenezra** [comment]
Okay, it looks like this isn't working.

I'm trying to generate a large 4D memmap file from a list of 3d tiffs (750 x 199 x 100). Each tiff is a timepoint. I try running:

fname_new = cm.save_memmap(file_names, base_name='Yr', is_3D=True, order='C')

When I do this, for each tiff in the list, it sets the 3rd dimension to 1, and the time dimension to 100. It should be the other way around. Below is an example filename.

Yr0059_d1_750_d2_199_d3_1_order_C_frames_100_.mmap

How can I correct this?

**Comment by pgunn** [comment]
Hi,
I'm not entirely sure this is right (this isn't something I've done), but try
```cm.load(tuple(file_list), ...)```

**Comment by SamBenezra** [comment]
Hey Pat, doesn't cm.load just load the data into memory? I'm not having any issues loading the tiff sequence into python. For that I use cm.load_movie_chain. The issue is, my entire dataset is ~200GB, so I would rather just memmap each individual tiff and combine them rather than loading the entire 4D dataset into memory.

**Comment by j-friedrich** [comment]
This has been an issue for tiffs that are individual frames. I just fixed it in master and dev, thus please do a fresh pull. You are correct, you can use `cm.save_memmap(fnames, order='C', is_3D=True)` to memmap each individual tiff and combine them.

Please reopen, if the issue still persists

**Comment by SamBenezra** [comment]
I'm running the conda-forge installation. Can I just replace mmapping.py with your new version?

When I did this, I got an error when running save_memmap:

Traceback (most recent call last):

  File "/mnt/farscape/x1/sam/Python/3d_cnmf.py", line 107, in <module>
    fname_new = cm.save_memmap([file_names], base_name='Yr', is_3D=True, order='C')

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/mmapping.py", line 414, in save_memmap
    if Yr.ndim == 3:

AttributeError: 'list' object has no attribute 'ndim'

**Comment by SamBenezra** [comment]
Never mind! the variable 'file_names' is already a list. I removed the brackets and it appears to be working.
