### ISSUE TITLE
Error reshaping spatial vectors (cnm.estimates.A)

### ISSUE THREAD

**Issue by connorjohnson1** [flatironinstitute/CaImAn#785]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows 10
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter
 

- **Describe the issue that you are experiencing**

these lines of code:

```
M = cnm1.estimates.A[:,cnm1.estimates.idx_components] 
masks = [np.reshape(np.array(M), dims, order='F')]
```

Give me this error:

- **Copy error log below**
```
ValueError                                Traceback (most recent call last)
<ipython-input-36-18b425c41e19> in <module>
      8 #temp['spatial'] = cnm1.estimates.A[:,cnm1.estimates.idx_components]
      9 M = cnm1.estimates.A[:,cnm1.estimates.idx_components]
---> 10 masks = [np.reshape(np.array(M), dims, order='F')]
     11 #scipy.io.savemat(r'Y:\Data 2018-2019\Anterior Cingulate Cortex\BehaviorMiniscopesACC\Organized\Sociability\608034_409\Day_2\Trial_001_0\spatial.mat', temp)
     12 #dims = (480,752)

<__array_function__ internals> in reshape(*args, **kwargs)

~\anaconda3\envs\caiman\lib\site-packages\numpy\core\fromnumeric.py in reshape(a, newshape, order)
    299            [5, 6]])
    300     """
--> 301     return _wrapfunc(a, 'reshape', newshape, order=order)
    302 
    303 

~\anaconda3\envs\caiman\lib\site-packages\numpy\core\fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     59 
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:
     63         # A TypeError occurs if the object does have such a method in its

ValueError: cannot reshape array of size 1 into shape (480,752)
```

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment]
To convert the sparse matrix M into a dense array you need to use `M.toarray()` not `np.array(M)`. Not sure what you are trying to do, but assuming there are more than 1 components, you probably want `M.toarray().reshape(dims+(-1,), order='F')`
