### ISSUE TITLE
contours of neurons outside plot

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#786]
Many neurons displayed in the contour plots of neurons after register_rois() appear outside the plot boundaries. The plot background is one of the correlation template of each session as mentioned in the demo example. 
one such plot is as below:
![register_op0](https://user-images.githubusercontent.com/721570/88614904-b7deec80-d0cb-11ea-8c96-b85e611b5b10.png)

how must the plot borders be enlarged to accommodate the neurons outside ?

**Comment by j-friedrich** [comment]
Are you using `plt.xlim(left,right)` to set the limits? If you do, try adjusting `right`

**Comment by akatav** [comment]
@j-friedrich  yes, i tried that but it did not help :(

**Comment by j-friedrich** [comment]
Looks as if the correlation background includes `None`s, thus there is some white space within the plot boundaries. You can check for that by simply plotting your correlation image `Cn` via `plt.imshow(Cn)`, which will likely look similar to this
![image](https://user-images.githubusercontent.com/11875432/89941000-631d9480-dbe8-11ea-97ab-e228bef54bb2.png)

**Comment by j-friedrich** [comment]
Closing due to inactivtity
