### ISSUE TITLE
Is there a way to use parallel processing without using a ton of memory?

### ISSUE THREAD

**Issue by SamBenezra** [flatironinstitute/CaImAn#787]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux

 2. Python version (3.x): 
3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
Spyder
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
N/A
 
 5. CaImAn version*: 
1.8.4
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I'm running cnm.fit on large 3D datasets (100x750x199) x 6000 volumes. Right now, I have dview = None. This uses about 250GB of RAM at its peak, and the job finishes in 23 hours.

I set up a cluster as shown below. I would like to use parallel processing to make the jobs go faster, but whenever I set dview = dview, the job crashes after a few hours because it consumes all of the memory on our server (400GB plus 500GB swap drive). Is there a way to set it up such that caiman can use multiple cores but not use up all the memory?

I set up a cluster like this:
c, dview, n_processes = cm.cluster.setup_cluster(
    backend='local', n_processes=20, single_thread=False)

and run cnmf:
cnm = cnmf.CNMF(n_processes, params=opts, dview=dview)
cnm = cnm.fit(images)

Here is the script I'm using:
[3d_cnmf.txt](https://github.com/flatironinstitute/CaImAn/files/4988864/3d_cnmf.txt)

**Comment by SamBenezra** [comment]
I also have a question about how parallelization works in caiman.

The way I have things set up, caiman runs 5 patches on my data, sequentially. If I use parallel processing by setting dview=dview, does that mean it tries to run all 5 patches in parallel? If that's the case, then it makes sense that it's using tons of memory.

If that's the case, is there a way to run only one patch at a time, but parallelize processing within that patch?

**Comment by pgunn** [comment]
Hi,
On your original question, try reducing n_processes from 20 to some smaller number in the setup_closter() call to reduce parallelism. Give that a go to see how your memory usage is, and reach back out once you have a handle on that - the problem might be gone then.

**Comment by SamBenezra** [comment]
Thanks, I'll give that a try

**Comment by SamBenezra** [comment]
Okay, reporting back. I tried setting n_processes to 2, but it still maxed out the memory on our server. This could just mean that the dataset is so large that we need to buy more memory. 

One thing to note, I get this message: "Parallel processing in a single patch is not available for loaded in memory or sliced data".

I'm curious why I would get this, because the data are .mmap and are not sliced. It seems like parallel processing in a single patch is actually what I want here, as opposed to parallel processing across multiple patches, which would require more memory. Is that correct or no?

**Comment by j-friedrich** [comment]
Multiple patches can be processed in parallel, there is no way to parallelize processing within a single patch. There's a time-memory trade-off by varying the number of patches that are processed in parallel, `n_processes`. Apparently your patches are so large that only one at a time can be processed. You could gain speedups by using smaller patches but more parallel processes, e.g. `rf=50; n_processes=8`.

**Comment by SamBenezra** [comment]
Thanks, I thought that might be the only way. I can play around and see if a smaller rf still works for my data.
