### ISSUE TITLE
Error during cnm.fit in estimates.normalize_components(): operands could not be broadcast together with shapes (146,) (147,) 

### ISSUE THREAD

**Issue by SamBenezra** [flatironinstitute/CaImAn#788]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Linux 

 2. Python version (3.x): 
3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
Spyder
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
See below
 
 5. CaImAn version*: 
1.8.4
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I'm running caiman on a 3d dendritic dataset. On some videos, the job finishes with no errors. On others, I get the error below. I've attached the script I'm using. Any ideas what might be the problem?

[3d_cnmf.txt](https://github.com/flatironinstitute/CaImAn/files/4989594/3d_cnmf.txt)

- **Copy error log below**
Traceback (most recent call last):

  File "/mnt/farscape/x1/sam/Python/3d_cnmf.py", line 142, in <module>
    cnm = cnm.fit(images)

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 653, in fit
    self.estimates.normalize_components()

  File "/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/estimates.py", line 814, in normalize_components
    self.bl = nA * self.bl

ValueError: operands could not be broadcast together with shapes (146,) (147,)

**Comment by SamBenezra** [comment]
It looks like the shape of the estimates are different:

print(cnm.estimates.C.shape)
(146, 6007)

print(cnm.estimates.YrA.shape)
(146, 6007)

print(cnm.estimates.R.shape)
(146, 6007)

print(cnm.estimates.bl.shape)
(147,)

print(cnm.estimates.c1.shape)
(147,)

print(cnm.estimates.neurons_sn.shape)
(147,)

**Comment by j-friedrich** [comment]
`bl`, `c1`, `g` and `neurons_sn` are all set to `None` in line 608. Apparently something goes awry in line 648 or line 651. Could you please check the shapes after the merging to tell whether the shape mismatch happens during `self.merge_comps(Yr, mx=np.Inf)` or during `self.update_temporal(Yr, use_init=False)`?

**Comment by SamBenezra** [comment]
Thanks for the quick response.

I pickled cnm, so I have that saved. Is there any way I can answer this question by quickly reloading cnm, or do I have to run the entire cnm.fit over again? If that's necessary, I'll have to get back to you in 2 days because our server is busy with another job right now.

**Comment by j-friedrich** [comment]
actually, no need to do that. after the merge step the values will still all be `None`. Can you load your pickled cnm and  `print(cnm.estimates.A.shape)`? Wondering whether that has 146 or 147 components.

**Comment by SamBenezra** [comment]
(14925000, 146)

Looks like 146

**Comment by SamBenezra** [comment]
I also get these warnings prior to the error:

/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py:441: RuntimeWarning: invalid value encountered in true_divide
  f /= np.sqrt((f**2).sum(1)[:, None])
/usr/local/bin/anaconda3/envs/caiman184/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py:454: RuntimeWarning: invalid value encountered in true_divide
  b /= nB
    80864110 [temporal.py:    update_iteration():403][19342] Aborting updating of temporal components due to possible numerical issues.

**Comment by j-friedrich** [comment]
Looks as if one of the background components is empty.
Try changing the lines to
`f /= np.sqrt((f**2).sum(1)[:, None]) + np.finfo(np.float32).eps`
and
`b /= nB + np.finfo(np.float32).eps`
This worked when I artificially set one row of `f` to zeros to emulate your presumed scenario, and the empty component was dropped later in the code.

Also, does your raw data have negative values? It seems this could lead to all-zero background components.

**Comment by SamBenezra** [comment]
I checked to see if the raw data has negative values. To do this, I loaded the tiffs into memory and checked for negatives:
data =  cm.load_movie_chain
isneg = np.sum(np.array(data) < 0)

isneg = 0, so I guess there's no negative values.

I checked cnm.estimates.bl and all values  were 0, however I did the same for another dataset that was successfully run and all values were also all zero. Is that typical or should they be non-zero?

I will try those changes you suggested and get back to you.

**Comment by j-friedrich** [comment]
all values of cnm.estimates.bl are expected to be zero if no deconvolution is performed, i.e. `p=0`. (If not processing in patches  cnm.estimates.bl will be `None`)

**Comment by SamBenezra** [comment]
Ah, thanks for the clarification. Yes, I have p = 0

**Comment by SamBenezra** [comment]
After changing those two lines, there is no more error, and 2 jobs that previously failed finish successfully now. I appreciate your time and help on this! Looks like this issue has been solved, so I'll close it.
