### ISSUE TITLE
Error with p value

### ISSUE THREAD

**Issue by oregonGCAMP** [flatironinstitute/CaImAn#792]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows
 2. Python version (3.x): 
 3.7.3
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I noticed that CaImAn crashes when the p value (autoregressive model) is 2, but works if it is changed to 1. I included 2 image files where this occurred.

- **Copy error log below**

ValueError Traceback (most recent call last)
in
183 #RE-RUN seeded CNMF on accepted patches to refine and perform deconvolution
184 cnm.params.change_params({'p': p})
--> 185 cnm2 = cnm.refit(images, dview=dview)
186
187

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in refit(self, images, dview)
414 cnm.estimates = estimates
415 cnm.mmap_file = self.mmap_file
--> 416 return cnm.fit(images)
417
418 def fit(self, images, indices=(slice(None), slice(None))):

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
564 self.params.set('temporal', {'p': self.params.get('preprocess', 'p')})
565 logging.info('update temporal ...')
--> 566 self.update_temporal(Yr, use_init=False)
567 # else:
568 # todo : ask for those..

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in update_temporal(self, Y, use_init, **kwargs)
899 self.estimates.g, self.estimates.YrA, self.estimates.lam = update_temporal_components(
900 Y, self.estimates.A, self.estimates.b, self.estimates.C, self.estimates.f, dview=self.dview,
--> 901 **self.params.get_group('temporal'))
902 self.estimates.R = self.estimates.YrA
903 return self

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\temporal.py in update_temporal_components(Y, A, b, Cin, fin, bl, c1, g, sn, nb, ITER, block_size_temp, num_blocks_per_run_temp, debug, dview, **kwargs)
215 logging.info("entering the deconvolution ")
216 C, S, bl, YrA, c1, sn, g, lam = update_iteration(parrllcomp, len_parrllcomp, nb, C, S, bl, nr,
--> 217 ITER, YrA, c1, sn, g, Cin, T, nA, dview, debug, AA, kwargs)
218 ff = np.where(np.sum(C, axis=1) == 0) # remove empty components
219 if np.size(ff) > 0: # Eliminating empty temporal components

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\temporal.py in update_iteration(parrllcomp, len_parrllcomp, nb, C, S, bl, nr, ITER, YrA, c1, sn, g, Cin, T, nA, dview, debug, AA, kwargs)
348 if 'multiprocessing' in str(type(dview)):
349 results = dview.map_async(
--> 350 constrained_foopsi_parallel, args_in).get(4294967)
351
352 elif dview is not None and platform.system() != 'Darwin':

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\multiprocessing\pool.py in get(self, timeout)
655 return self._value
656 else:
--> 657 raise self._value
658
659 def _set(self, i, obj):

ValueError: shapes (82,82) and (0,) not aligned: 82 (dim 1) != 0 (dim 0)
[ImageExample.zip](https://github.com/flatironinstitute/CaImAn/files/5024731/ImageExample.zip)
[ImageExample.zip](https://github.com/flatironinstitute/CaImAn/files/5024732/ImageExample.zip)

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment]
Please reproduce your error with setting `dview=None`

**Comment by oregonGCAMP** [comment]
Here it is..

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-3-da10c66b27be> in <module>
    183         #RE-RUN seeded CNMF on accepted patches to refine and perform deconvolution
    184         cnm.params.change_params({'p': p})
--> 185         cnm2 = cnm.refit(images, dview=dview)
    186 
    187 

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in refit(self, images, dview)
    414         cnm.estimates = estimates
    415         cnm.mmap_file = self.mmap_file
--> 416         return cnm.fit(images)
    417 
    418     def fit(self, images, indices=(slice(None), slice(None))):

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
    564                 self.params.set('temporal', {'p': self.params.get('preprocess', 'p')})
    565                 logging.info('update temporal ...')
--> 566                 self.update_temporal(Yr, use_init=False)
    567             # else:
    568             #     todo : ask for those..

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in update_temporal(self, Y, use_init, **kwargs)
    899         self.estimates.g, self.estimates.YrA, self.estimates.lam = update_temporal_components(
    900                 Y, self.estimates.A, self.estimates.b, self.estimates.C, self.estimates.f, dview=self.dview,
--> 901                 **self.params.get_group('temporal'))
    902         self.estimates.R = self.estimates.YrA
    903         return self

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\temporal.py in update_temporal_components(Y, A, b, Cin, fin, bl, c1, g, sn, nb, ITER, block_size_temp, num_blocks_per_run_temp, debug, dview, **kwargs)
    215     logging.info("entering the deconvolution ")
    216     C, S, bl, YrA, c1, sn, g, lam = update_iteration(parrllcomp, len_parrllcomp, nb, C, S, bl, nr,
--> 217                                                      ITER, YrA, c1, sn, g, Cin, T, nA, dview, debug, AA, kwargs)
    218     ff = np.where(np.sum(C, axis=1) == 0)  # remove empty components
    219     if np.size(ff) > 0:  # Eliminating empty temporal components

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\temporal.py in update_iteration(parrllcomp, len_parrllcomp, nb, C, S, bl, nr, ITER, YrA, c1, sn, g, Cin, T, nA, dview, debug, AA, kwargs)
    348             if 'multiprocessing' in str(type(dview)):
    349                 results = dview.map_async(
--> 350                     constrained_foopsi_parallel, args_in).get(4294967)
    351 
    352             elif dview is not None and platform.system() != 'Darwin':

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\multiprocessing\pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

ValueError: shapes (78,78) and (0,) not aligned: 78 (dim 1) != 0 (dim 0)

**Comment by j-friedrich** [comment]
You are still using multiprocessing which prevents the log to provide a more meaningful error message.
You need to set `dview=None` when creating the `CNMF` object and when calling `refit`, 
e.g. `cnm = cnmf.CNMF(n_processes, params=opts, dview=None)`
and `cnm2 = cnm.refit(images, dview=None)`

**Comment by oregonGCAMP** [comment]
Got it.

Here it is:

ValueError                                Traceback (most recent call last)
<ipython-input-2-0ffc2b10966c> in <module>
    183         #RE-RUN seeded CNMF on accepted patches to refine and perform deconvolution
    184         cnm.params.change_params({'p': p})
--> 185         cnm2 = cnm.refit(images, dview=None)
    186 
    187 

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in refit(self, images, dview)
    414         cnm.estimates = estimates
    415         cnm.mmap_file = self.mmap_file
--> 416         return cnm.fit(images)
    417 
    418     def fit(self, images, indices=(slice(None), slice(None))):

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
    564                 self.params.set('temporal', {'p': self.params.get('preprocess', 'p')})
    565                 logging.info('update temporal ...')
--> 566                 self.update_temporal(Yr, use_init=False)
    567             # else:
    568             #     todo : ask for those..

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in update_temporal(self, Y, use_init, **kwargs)
    899         self.estimates.g, self.estimates.YrA, self.estimates.lam = update_temporal_components(
    900                 Y, self.estimates.A, self.estimates.b, self.estimates.C, self.estimates.f, dview=self.dview,
--> 901                 **self.params.get_group('temporal'))
    902         self.estimates.R = self.estimates.YrA
    903         return self

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\temporal.py in update_temporal_components(Y, A, b, Cin, fin, bl, c1, g, sn, nb, ITER, block_size_temp, num_blocks_per_run_temp, debug, dview, **kwargs)
    215     logging.info("entering the deconvolution ")
    216     C, S, bl, YrA, c1, sn, g, lam = update_iteration(parrllcomp, len_parrllcomp, nb, C, S, bl, nr,
--> 217                                                      ITER, YrA, c1, sn, g, Cin, T, nA, dview, debug, AA, kwargs)
    218     ff = np.where(np.sum(C, axis=1) == 0)  # remove empty components
    219     if np.size(ff) > 0:  # Eliminating empty temporal components

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\temporal.py in update_iteration(parrllcomp, len_parrllcomp, nb, C, S, bl, nr, ITER, YrA, c1, sn, g, Cin, T, nA, dview, debug, AA, kwargs)
    366 
    367             else:
--> 368                 results = list(map(constrained_foopsi_parallel, args_in))
    369             # unparsing and updating the result
    370             for chunk in results:

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\temporal.py in constrained_foopsi_parallel(arg_in)
     55     T = np.shape(Ytemp)[0]
     56     cc_, cb_, c1_, gn_, sn_, sp_, lam_ = constrained_foopsi(
---> 57         Ytemp, bl=bl, c1=c1, g=g, sn=sn, **argss)
     58     gd_ = np.max(np.real(np.roots(np.hstack((1, -gn_.T)))))
     59     gd_vec = gd_**list(range(T))

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\deconvolution.py in constrained_foopsi(fluor, bl, c1, g, sn, p, method_deconvolution, bas_nonneg, noise_range, noise_method, lags, fudge_factor, verbosity, solvers, optimize_g, s_min, **kwargs)
    160                     c, sp, bl, g, lam = constrained_oasisAR2(
    161                         fluor.astype(np.float32), g, sn, optimize_b=True, b_nonneg=bas_nonneg,
--> 162                         optimize_g=optimize_g, penalty=penalty)
    163                 else:
    164                     c, sp, _, g, lam = constrained_oasisAR2(

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\deconvolution.py in constrained_oasisAR2(y, g, sn, optimize_b, b_nonneg, optimize_g, decimate, shift, window, tol, max_iter, penalty)
    764     # run ONNLS
    765     c, s = onnls(y - b, g, lam=lam, mask=mask,
--> 766                  shift=shift, window=window, tol=tol)
    767 
    768     if not optimize_b:  # don't optimize b, just the dual variable lambda

~\AppData\Local\Continuum\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\deconvolution.py in onnls(y, g, lam, shift, window, mask, tol, max_iter)
    629     s[i + shift:] = _nnls(KK[-(T - i - shift):, -(T - i - shift):],
    630                           K[:T - i - shift, :T - i -
--> 631                               shift].T.dot(_y[i + shift:]),
    632                           s[i + shift:], mask=mask[i + shift:])
    633     c = np.zeros_like(s)

ValueError: shapes (78,78) and (0,) not aligned: 78 (dim 1) != 0 (dim 0)

**Comment by j-friedrich** [comment]
While in practice the time series are thousands of frames long, I can recreate the error for exceptionally short time series with less than 100 frames. Is your recording really as short? 

If it is, adding the line `shift = min(w, shift)` after line [591](https://github.com/flatironinstitute/CaImAn/blob/e2de6f3350342f2f5762279b7059bdb739d58d84/caiman/source_extraction/cnmf/deconvolution.py#L591) fixes the error.

**Comment by j-friedrich** [comment]
Apparently the above fixed the issue, hence closing it.
