### ISSUE TITLE
Caiman Matlab

### ISSUE THREAD

**Issue by eltabbal** [flatironinstitute/CaImAn#794]
Where is the matlab / python script for seeded initialization method algorithm as described in elife paper. I couldn't find it. 

<img width="472" alt="algorithm3paper" src="https://user-images.githubusercontent.com/22963512/89637813-c2785d80-d8e5-11ea-9653-6d0930e14dfb.png">

**Comment by j-friedrich** [comment]
[Here](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_seeded_CNMF.ipynb) is a demo notebook for seeded initialization.
