### ISSUE TITLE
compute_metrics_motion_correction minor issues

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#796]
A little issue associated with `motion_correction.compute_metrics_motion_correction()` I found when running through `demo_motion_correction.ipynb`.  I am in caiman 1.8.3, Windows 10, installed using conda in a Jupyter notebook.

When I set `play_flow=True` the movie didn't show in the first column (it was just blank white). I think it is because the following line: 
`pl.imshow(fr, vmin=0, vmax=300, cmap='gray')`

with the following it worked fine:
`pl.imshow(fr, cmap='gray')`

Not going to submit a PR because you tend to want to incorporate more fancy options in your displays sometimes. :) Also, in my Jupyter notebook, the movie did not show as a movie but a bunch of inline plots, one new row generated for each frame, so I had to be sure to add some magic like `%matplotlib qt` to see the intended movie display.

Finally, there is a minor typo in the demo notebook:
```
tmpl_rig, correlations_orig, flows_orig, norms_orig, crispness_orig = cm.motion_correction.compute_metrics_motion_correction(
    fnames[0], final_size[0], final_size[1], swap_dim, winsize=winsize, play_flow=False, resize_fact_flow=resize_fact_flow)
```

The template name should be `templ_orig`, because `tmpl_rig` is already in use for the rigid estimator.

**Comment by j-friedrich** [comment]
Addressed in commit a955c8ac8afe6e2e0685ca7bb92a0c9e8e99ec0a.
