### ISSUE TITLE
Remove pin on tifffile

### ISSUE THREAD

**Issue by chrisroat** [flatironinstitute/CaImAn#797]
Tifffile has been pinned at 0.15.1 for 10 months, via a commit that indicates some sort of upstream breakage.

This prevents usage of recent scikit-image versions in caiman environments.

Is the upstream breakage from later tifffiles resolved?  Can this pin be lifted?

**Comment by pgunn** [comment]
I will look into it soon. We're also due to try harder to get Python 3.8 working.

**Comment by pgunn** [comment]
Will be done as part of #711
