### ISSUE TITLE
stacked tif resolution 

### ISSUE THREAD

**Issue by ywtsay** [flatironinstitute/CaImAn#798]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
docker Linux on macOS
 2. Python version (3.x): 
 3.7.8
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook
 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_pipeline
 5. CaImAn version*: 
 1.8.4

- **Describe the issue that you are experiencing**
hi, when i'm using version 1.8.1 and everything was fine.
since i update caiman to 1.8.4, issues happen when the input tiff resolution is larger than 300x300 pixel 
in the step "Re-run (seeded) CNMF on the full Field of View"
it shows "IndexError: index 3 is out of bounds for axis 0 with size 2"
is there any chance to fix this problem?

**Comment by pgunn** [comment]
Hi,
Can you give us more of the context of the error in the logs?

**Comment by ywtsay** [comment]
hi, this is the Jupyter Notebook log when i ran tif file larger than 300x300 pixel

[logs.txt](https://github.com/flatironinstitute/CaImAn/files/5060922/logs.txt)

(if tif image resolution is smaller than 300x300, then it runs ok)

**Comment by pgunn** [comment]
Those are not quite the logs I'm looking for. Is there any more logging in the notebook cell output?

**Comment by ywtsay** [comment]
my apologies, this is the logs from Jupyter Notebook cell in steps "Re-run (seeded) CNMF on the full Field of View"

[logs.txt](https://github.com/flatironinstitute/CaImAn/files/5060969/logs.txt)

**Comment by j-friedrich** [comment]
According to the logs the size of the tif is not the issue. It looks as if this error can occur if a neural component and a spatial component are empty.
Try replacing [lines 261-273](https://github.com/flatironinstitute/CaImAn/blob/e2de6f3350342f2f5762279b7059bdb739d58d84/caiman/source_extraction/cnmf/spatial.py#L261-L273) with the following
````
if any(ff < nr):
    A_ = csc_column_remove(A_, list(ff[ff < nr]))
    C = np.delete(C, list(ff[ff < nr]), 0)
    ff -= nr
    nr = nr - len(ff[ff < nr])
else:
    ff -= nr
if update_background_components:
    background_ff = list(filter(lambda i: i >= 0, ff))
    f = np.delete(f, background_ff, 0)
    if b_in is not None:
        b_in = np.delete(b_in, background_ff, 1)
````

**Comment by ywtsay** [comment]
@j-friedrich @pgunn  thanks for your help,

its working now !
