### ISSUE TITLE
refit() throws a ValueError

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#799]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows 10.

 2. Python version (3.x): 
 3.6.11

 3. Working environment (Python IDE/Jupyter Notebook/other):
Jupyter 

 4. Which of the demo scripts you're using for your analysis (if applicable):
demo_pipeline_cnmfE
 
 5. CaImAn version*: 
1.8.5
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda

- **Describe the issue that you are experiencing**
In the cnmf-e demo, after running `cnm = cnm.fit(images)` (which works fine), I tried to run `cnm2 = cnm.refit(images, dview=dview)` (I set dview to None before posting here), and got an error. Stack trace is copied below.

- **Copy error log below**

> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-51-cf73fa466ba2> in <module>
>       1 #%% RE-RUN seeded CNMF on accepted patches to refine
>       2 # Following does not work in cnmf-E pipeline get ValueError
> ----> 3 cnm2 = cnm.refit(images, dview=dview)
> 
> ~\miniconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in refit(self, images, dview)
>     415         cnm.estimates = estimates
>     416         cnm.mmap_file = self.mmap_file
> --> 417         return cnm.fit(images)
>     418 
>     419     def fit(self, images, indices=(slice(None), slice(None))):
> 
> ~\miniconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
>     541 
>     542             logging.info('update spatial ...')
> --> 543             self.update_spatial(Yr, use_init=True)
>     544 
>     545             logging.info('update temporal ...')
> 
> ~\miniconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in update_spatial(self, Y, use_init, **kwargs)
>     934             update_spatial_components(Y, C=self.estimates.C, f=self.estimates.f, A_in=self.estimates.A,
>     935                                       b_in=self.estimates.b, dview=self.dview,
> --> 936                                       sn=self.estimates.sn, dims=self.dims, **self.params.get_group('spatial'))
>     937 
>     938         return self
> 
> ~\miniconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\spatial.py in update_spatial_components(Y, C, f, A_in, sn, dims, min_size, max_size, dist, normalize_yyt_one, method_exp, expandCore, dview, n_pixels_per_process, medw, thr_method, maxthr, nrgthr, extract_cc, b_in, se, ss, nb, method_ls, update_background_components, low_rank_background, block_size_spat, num_blocks_per_run_spat)
>     216     # we create a memory map file if not already the case, we send Cf, a
>     217     # matrix that include background components
> --> 218     C_name, Y_name, folder = creatememmap(Y, np.vstack((C, f)), dview)
>     219 
>     220     # we create a pixel group array (chunks for the cnmf)for the parrallelization of the process
> 
> <__array_function__ internals> in vstack(*args, **kwargs)
> 
> ~\miniconda3\envs\caiman\lib\site-packages\numpy\core\shape_base.py in vstack(tup)
>     281     if not isinstance(arrs, list):
>     282         arrs = [arrs]
> --> 283     return _nx.concatenate(arrs, 0)
>     284 
>     285 
> 
> <__array_function__ internals> in concatenate(*args, **kwargs)
> 
> ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1000 and the array at index 1 has size 1
>

**Comment by j-friedrich** [comment]
Please check whether `cnm.estimates.f` is None.
If it is, try setting 
````
cnm.estimates.f = np.zeros((0, cnm.estimates.C.shape[1]), dtype=np.float32)
cnm.estimates.b = np.zeros((cnm.estimates.A.shape[0], 0), dtype=np.float32)
````
before calling
`cnm2 = cnm.refit(images, dview=dview)`

**Comment by EricThomson** [comment]
Yes `cnm.estimates.f` is empty (as is `estimates.b`). Populating with zeros removed the error. A runtime warning (divide by zeros) popped up but I assume such guys are handled.

**Comment by EricThomson** [comment]
Maybe I prematurely closed this issue. I see two ways we can go with this. One, @agiovann suggested that `refit()` is not supported for CNMFE, so maybe we should just mention this in the demo for CNMFE so people don't get confused (i.e., technically `refit()` will run without throwing an error, it doesn't do what it should). The second route, is maybe I am wrong about that and we could get it working (perhaps with some minor tweaking), and add it to the CNMFE demo.  It seems, as it stands now, we are in the first branch.

**Comment by j-friedrich** [comment]
Yes, refit() is not implemented for CNMF-E. For CNMF-E the code of refit
(lines 398-418 in cnmf.py) would need to be modified to keep
`only_init=True` and instead of the last call of `fit()` it would roughly
run lines 1238 to 1315 of initialization.py.

**Comment by EricThomson** [comment]
Good eye I will revise that description: it is run in the demo notebook before any wrangling into accepted/rejected components I will fix that in my current update that I'm working on.
 
My understanding is that `refit()` was built for CNMF because the spatial components look pretty weird sometimes initially, and typically isn't needed for CNMFE (though just about any rule will have an exception, so it would be good to support `Ain` for CNMFE instead of just seed pixels).
