### ISSUE TITLE
Strategy for manual removal of components?

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#802]
I am in caiman 1.8.5 (installed with conda on Windows) adapting the cnmfe demo notebook.

I apologize for the length of this post.  **TL;DR**: Is there a natural way to switch components from `estimates.idx_components` to `estimates.idx_components_bad`, so that those components will not be removed from the data structure, and such that the changes will persists even when you run `filter_components()`?

It seems that the most obvious method to start with would be `estimates.select_components()`. One problem here is that it resets the `idx` values to `None`. More importantly the components you want to remove are discarded from the data structure, not put on the bad list (There is a buffer  provided by `save_discarded_components`, but this would start to get gnarly if you remove lots of components in an iterative fashion.)

If I am right, one approach to do what I want to do would be to add a fourth evaluation metric (`user_feedback` or something) indicating that the user is overriding all the other evaluation metrics. Without *something* like that, every time you re-run `filter_components()` any components that pass your current evaluation criteria would automatically be put in with `idx_components` rather than stay in with the bad guys where you want them.

Another option is just to add, as a kind of final step, a parallel 'master list' of neurons that the user wants to analyze (e.g., take a set difference between the list of manually selected bad neurons and `idx_components`). This final master list could provide the actual neurons to be used for analysis. I think this seems a bit inelegant, but it is the only other possibility I came up with. 

I'm curious if folks have thought about this problem, if I am thinking about it right, and if anyone has come up with an elegant solution?

Related:
https://github.com/flatironinstitute/CaImAn/issues/401

**Comment by EricThomson** [comment]
Note just to make more clear what my issue is.

If you are OK having the removed components entirely removed from the estimate fields, the following works pretty well. This starts with the (manually constructed) list of indices you want removed from `idx_components`.

```
indices_to_remove = np.asarray([27, 52])  
units_to_remove = cnm.estimates.idx_components[indices_to_remove]
```

Then, run `select_components()` on that, and the re-run `evaluate_components()` to repopulate the `idx` lists:

```
num_components = C.shape[0]
new_inds = np.setdiff1d(np.arange(num_components), units_to_remove)
cnm.estimates.select_components(idx_components = new_inds, save_discarded_components=True);
cnm.estimates.evaluate_components(images, cnm.params, dview=dview);
```

The above works fine to remove the components in the list. The problem is that the discarded components are lost from the main estimates fields (though they are saved, at least this iteration, in `estimates.discarded_components`).  It would be convenient for users to be able to just put components on the naughty list manually, overriding the chosen evaluation criteria, but keeping them in the data structure for later evaluation, plotting, etc.. 

Anyway, this is what I am currently doing because it is easiest.  I'm just not sure if I've missed some obvious wrinkle in the code that would let me do what I want.

**Comment by j-friedrich** [comment]
You're using `select_components` correctly. Either execute `evaluate_components` followed by `select_components(use_object=True)` for automatic selection or `select_components(idx_components=new_inds)` for manual selection. I updated the code in the dev branch (commit 06b4eab180e193fa6f91e275ca7c294fb2c7b6a8), so that it is compatible with iterated component selection. Newly discarded components are now appended to `discarded_components` instead of overwriting them.
