### ISSUE TITLE
Indexing # out of bounds for axis 0 of size #

### ISSUE THREAD

**Issue by GarrettBlair** [flatironinstitute/CaImAn#808]
1. Operating system (Linux/macOS/Windows): Windows 10 64 bit, 128GB RAM, no GPU, running in parallel on AMD Ryzen 1950x

2. Python version (3.x): Python ver 3.7.6

3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook

4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline_cnmfe

5. CaImAn version: 1.8.5

6. CaImAn installation process (pip install ./pip install -e ./conda): pip install -e

- **Describe the issue that you are experiencing**

_IndexError: index 1 is out of bounds for axis 0 with size 0_

I recently upgraded from 1.8.1 to 1.8.5. Since the upgrade, some data sets I run give rise to an indexing error I hadn't encountered prior. I get the same error when running in parallel or single threaded. I found someone else post a comment in this closed thread with a very similar error: 

https://github.com/flatironinstitute/CaImAn/issues/754 (see last comment, not original issue)

- **Copy error log below**
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-17-ca34cc9bb0f9> in <module>
     72 ## Perform cnmfe
     73 cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, Ain=Ain, params=opts)
---> 74 cnm.fit(images)
     75 ## component eval
     76 min_SNR = 3            # adaptive way to set threshold on the transient size

c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
    604                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    605                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 606                     indices=indices)
    607 
    608             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    257 
    258     else:
--> 259         file_res = list(map(cnmf_patches, args_in))
    260 
    261     logging.info('Elapsed time for processing patches: \

c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\map_reduce.py in cnmf_patches(args_in)
    135         cnm = cnmf.CNMF(n_processes=1, params=opts)
    136 
--> 137         cnm = cnm.fit(images)
    138         return [idx_, shapes, scipy.sparse.coo_matrix(cnm.estimates.A),
    139                 cnm.estimates.b, cnm.estimates.C, cnm.estimates.f,

c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
    504             if self.estimates.A is None:
    505                 logging.info('initializing ...')
--> 506                 self.initialize(Y)
    507 
    508             if self.params.get('patch', 'only_init'):  # only return values after initialization

c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\cnmf.py in initialize(self, Y, **kwargs)
    964                 extra_1p = initialize_components(
    965                     Y, sn=estim.sn, options_total=self.params.to_dict(),
--> 966                     **self.params.get_group('init'))
    967             try:
    968                 estim.S, estim.bl, estim.c1, estim.neurons_sn, \

c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\initialization.py in initialize_components(Y, K, gSig, gSiz, ssub, tsub, nIter, maxIter, nb, kernel, use_hals, normalize_init, img, method_init, max_iter_snmf, alpha_snmf, sigma_smooth_snmf, perc_baseline_snmf, options_local_NMF, rolling_sum, rolling_length, sn, options_total, min_corr, min_pnr, seed_method, ring_size_factor, center_psf, ssub_B, init_iter, remove_baseline, SC_kernel, SC_sigma, SC_thr, SC_normalize, SC_use_NN, SC_nnn, lambda_gnmf)
    352             Y, Y_ds, max_number=K, gSiz=gSiz[0], gSig=gSig[0], min_corr=min_corr, min_pnr=min_pnr,
    353             ring_size_factor=ring_size_factor, center_psf=center_psf, options=options_total,
--> 354             sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter, seed_method=seed_method)
    355 
    356     elif method == 'sparse_nmf':

c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\initialization.py in greedyROI_corr(Y, Y_ds, max_number, gSiz, gSig, center_psf, min_corr, min_pnr, seed_method, min_pixel, bd, thresh_init, ring_size_factor, nb, options, sn, save_video, video_name, ssub, ssub_B, init_iter)
   1302                                  tuple([ssub] * len(dims))).ravel() / tsub) / ssub,
   1303             b_in=np.zeros((d1 * d2, 0), np.float32),
-> 1304             dview=None, dims=(d1, d2), **options['spatial_params'])
   1305         A = A.astype(np.float32)
   1306         logging.info('Updating temporal components')

c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\spatial.py in update_spatial_components(Y, C, f, A_in, sn, dims, min_size, max_size, dist, normalize_yyt_one, method_exp, expandCore, dview, n_pixels_per_process, medw, thr_method, maxthr, nrgthr, extract_cc, b_in, se, ss, nb, method_ls, update_background_components, low_rank_background, block_size_spat, num_blocks_per_run_spat)
    267             if low_rank_background:
    268                 background_ff = list(filter(lambda i: i >= nb, ff - nr))
--> 269                 f = np.delete(f, background_ff, 0)
    270             else:
    271                 background_ff = list(filter(lambda i: i >= 0, ff - nr))

<__array_function__ internals> in delete(*args, **kwargs)

~\Anaconda3\envs\caiman\lib\site-packages\numpy\lib\function_base.py in delete(arr, obj, axis)
   4404         else:
   4405             keep = ones(N, dtype=bool)
-> 4406             keep[obj,] = False
   4407 
   4408         slobj[axis] = keep

IndexError: index 1 is out of bounds for axis 0 with size 0

**Comment by GarrettBlair** [comment]
I've done some testing on this since posted, and it looks like the issue is being caused during source_extraction/cnmf/spatial.py in update_spatial_components by `f` returned from either test() or computing_indicator() being empty, so background subtraction in `np.delete(f, background_ff, 0)` failing.

I was able to circumvent the issue just by conditioning line 269 with:
```
if f.size>0:
    f = np.delete(f, background_ff, 0)
```
This let processing finish at least. It only skipped deletion 4 times out of ~1600 final components (of those skips, f was empty of course, ff was always an int, and bg_ff was empty 3 times and zero once). I can upload a sample movie if it's helpful. I think it could be caused by certain edges of the video having fairly low fluctuations? 

cnmf parameters are below
```
# parameters for source extraction and deconvolution
frate = 10                       # movie frame rate
decay_time = 1                 # length of a typical transient in seconds, 0.4 default
p = 2               # order of the autoregressive system
K = None            # upper bound on number of components per patch, in general None
gSig = (5, 5)       # gaussian width of a 2D gaussian kernel, which approximates a neuron default=(3,3)
gSiz = (21, 21)     # average diameter of a neuron, in general 4*gSig+1 default=(13,13)
Ain = None          # possibility to seed with predetermined binary masks
merge_thr = .7      # merging threshold, max correlation allowed
rf = 40             # half-size of the patches in pixels. e.g., if rf=40, patches are 80x80
stride_cnmf = 25    # amount of overlap between the patches in pixels
tsub = 2            # downsampling factor in time for initialization,
ssub = 1            # downsampling factor in space for initialization,
low_rank_background = None  # None leaves background of each patch intact,
gnb = 0             # number of background components (rank) if positive,
nb_patch = 0        # number of background components (rank) per patch if gnb>0,
min_corr = .75      # min peak value from correlation image default .8
min_pnr = 6         # min peak to noise ration from PNR image, default 10
ssub_B = 2          # additional downsampling factor in space for background
ring_size_factor = 1.4    # radius of ring is gSiz*ring_size_factor
optimize_g = True         # bool, default:False, flag for optimizing time constants
simultaneously = False  # bool, optional, If true, demix and denoise/deconvolve simultaneously. 
```

**Comment by j-friedrich** [comment]
Commit cb693585d1b28fac7c8414bd604d8cc3a1569a86 presumably already addresses this issue, but didn't make it from dev to master yet.
One could also simply set  `update_background_components=False` if no low-rank background but the ring model is used.

**Comment by GarrettBlair** [comment]
Thanks very much, I'll use those for now!
