### ISSUE TITLE
Motion Correcting Memmap Files: Assignment Error

### ISSUE THREAD

**Issue by willyh101** [flatironinstitute/CaImAn#811]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows):  Windows 10
 
 2. Python version (3.x):  3.7.8
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): NA, but roughly following demo_motion_correct.ipynb
 
 5. CaImAn version*:  1.8.5
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda):  conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

I'm trying to motion correct a memory mapped file using the MotionCorrect object and am receiving `ValueError: assignment destination is read-only`. I memory-map and attempt motion correction with:

```
mapfile = cm.save_memmap(order='C', ...)
mc = MotionCorrect(mapfile, ...)
mc.motion_correct()
```

I am using the default parameters from demo_motion_correction notebook, but using my own file, which is a 512 x 512, 6.36 Hz movie of 780 frames.

I inspected the code with the ipynb debugger and found that `self[i].flags.WRITEABLE = False` and `np.clip(cv2.warpAffine(frame, M, (w, h), flags=interpolation, borderMode=cv2.BORDER_REFLECT), min_, max_)` works as expected (without assignment). Attempting to set self/movie object to writeable fails with `ValueError: cannot set WRITEABLE flag to True of this array`

- **Copy error log below**

```     
7993458 [movies.py:      extract_shifts():371] [20784] Movie average is negative. Removing 1st percentile.
7993467 [movies.py:      extract_shifts():389] [20784] Movie average is negative. Removing 1st percentile.
7994023 [movies.py:      extract_shifts():371] [20784] Movie average is negative. Removing 1st percentile.
7994042 [movies.py:      extract_shifts():389] [20784] Movie average is negative. Removing 1st percentile.
7994570 [movies.py:      extract_shifts():371] [20784] Movie average is negative. Removing 1st percentile.
7994624 [movies.py:      extract_shifts():389] [20784] Movie average is negative. Removing 1st percentile.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-705a4721bf12> in <module>
----> 1 mc.motion_correct()

~\Anaconda3\envs\caiman-online\lib\site-packages\caiman\motion_correction.py in motion_correct(self, template, save_movie)
    252                                     np.max(np.abs(self.y_shifts_els))))
    253         else:
--> 254             self.motion_correct_rigid(template=template, save_movie=save_movie)
    255             b0 = np.ceil(np.max(np.abs(self.shifts_rig)))
    256         self.border_to_0 = b0.astype(np.int)

~\Anaconda3\envs\caiman-online\lib\site-packages\caiman\motion_correction.py in motion_correct_rigid(self, template, save_movie)
    303                 var_name_hdf5=self.var_name_hdf5,
    304                 is3D=self.is3D,
--> 305                 indices=self.indices)
    306             if template is None:
    307                 self.total_template_rig = _total_template_rig

~\Anaconda3\envs\caiman-online\lib\site-packages\caiman\motion_correction.py in motion_correct_batch_rigid(fname, max_shifts, dview, splits, num_splits_to_process, num_iter, template, shifts_opencv, save_movie_rigid, add_to_movie, nonneg_movie, gSig_filt, subidx, use_cuda, border_nan, var_name_hdf5, is3D, indices)
   2685         else:
   2686             template = caiman.motion_correction.bin_median(
-> 2687                     m.motion_correct(max_shifts[1], max_shifts[0], template=None)[0])
   2688 
   2689     new_templ = template

~\Anaconda3\envs\caiman-online\lib\site-packages\caiman\base\movies.py in motion_correct(self, max_shift_w, max_shift_h, num_frames_template, template, method, remove_blanks, interpolation)
    198                                              template=template,
    199                                              method=method)
--> 200         self = self.apply_shifts(shifts, interpolation=interpolation, method=method)
    201 
    202         if remove_blanks:

~\Anaconda3\envs\caiman-online\lib\site-packages\caiman\base\movies.py in apply_shifts(self, shifts, interpolation, method, remove_blanks)
    506                 min_, max_ = np.min(frame), np.max(frame)
    507                 self[i] = np.clip(cv2.warpAffine(frame, M, (w, h), flags=interpolation, borderMode=cv2.BORDER_REFLECT),
--> 508                                   min_, max_)
    509 
    510             elif method == 'skimage':

ValueError: assignment destination is read-only
```

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment]
It's unnecessary to memory map the file first. Nevertheless, addressed in commit 3c5bf4bc7b6923c3d094da2ac2f958e8e792570b
