### ISSUE TITLE
1p data processing error: IndexError: index 1 is 

### ISSUE THREAD

**Issue by jesusdpa1** [flatironinstitute/CaImAn#813]
Hi, 

I am having problems running cnmfe on 1p data. I manage to extract and save the data into tiff files, and was able to perform motion correction on the file without any problems. 

When I jump to the cnmf.CNMF I keep getting the following error:

IndexError: index 1 is out of bounds for axis 0 with size 0

I have updated the options dview to None and n_processes to 1 without any luck. The problem also appears in random stages of the processing. The first time it was originated after 2h of processing and now it is generated at the start. Moreover, I haven't experience this error using the provided Inscopix API.

The computer specs are:
I7 9th Gen
32Gb Ram
2070RTX
OS: Ubuntu 20.04
Environment: Installed following CaImAn website instructions 

Data: 1 trial recording Inscopix dataset. data extracted using the API

I am uploading three files with 3 different errors

With regard of the code I have use the first part of the demo_online_cnmfe

[error_report3.txt](https://github.com/flatironinstitute/CaImAn/files/5234681/error_report3.txt)
[error_report2.txt](https://github.com/flatironinstitute/CaImAn/files/5234682/error_report2.txt)
[error_report.txt](https://github.com/flatironinstitute/CaImAn/files/5234683/error_report.txt)

**Comment by GarrettBlair** [comment]
Just got help with this same issue - #808. Made the changes suggested and that fixed it.

**Comment by jesusdpa1** [comment]
Thanks Garret! that solved the issue.
