### ISSUE TITLE
Plot only a component by cnm.estimates.view_components

### ISSUE THREAD

**Issue by AK-Osaka** [flatironinstitute/CaImAn#814]
1. Operating system (Linux/macOS/Windows): Windows
 2. Python version (3.x): 3.7
 3. Working environment (Python IDE/Jupyter Notebook/other):Spyder (anaconda3)
 4. Which of the demo scripts you're using for your analysis (if applicable):demo_pipeline_cnmfE
 5. CaImAn version*: 1.8.4
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): pip install

Hi,
Uisng Caiman 1P demo-demo_cnmfE.py, 11 components are accepted as below. But only first component of the idx list is plotted. I want to check all spatial and temporal component. Can you please advise.

`cnm.estimates.plot_contours(img=cn_filter, idx=cnm.estimates.idx_components)`
`cnm.estimates.view_components(images, img=cn_filter, idx=cnm.estimates.idx_components) `

![components](https://user-images.githubusercontent.com/71511537/93609299-a5679c00-fa06-11ea-8f45-5e32d453df21.png)
![1component](https://user-images.githubusercontent.com/71511537/93609292-a3054200-fa06-11ea-995e-bdbc72a436e6.png)

**Comment by EricThomson** [comment]
@AK-Osaka have you figured this out?  

I would suggest trying the newer methods, either `hv_view_components()` or `nb_view_components()`. I haven't used the matplotlib based version. Looking at the code the widget at the bottom that is labeled `Component` is a slider -- have you tried clicking on it to get it to move to a new component? That is how the other (holoviews and notebook) versions work.

**Comment by j-friedrich** [comment]
As @EricThomson correclty stated, simply click the slider to change the component. 
Note that this requires a matplotlib backend that does not inline figures but shows them in a new window, e.g. `%matplotlib tk` not `%matplotlib inline`
