### ISSUE TITLE
Threshold has no effect in view_components/nb_view_components

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#818]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Windows
 
 2. Python version (3.x): 
 3.6

 3. Working environment (Python IDE/Jupyter Notebook/other):
Jupyter 

 4. Which of the demo scripts you're using for your analysis (if applicable):
cnmfe demo 

 5. CaImAn version*: 
1.8.5
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda

- **Describe the issue that you are experiencing**
If the estimates object is already populated with coordinates, when running `cnm.estimates.plot_contours()` or `plot_contours_nb()` the `thr` parameter has no effect. To get it to work, I commented out the line that checks to see if `self.coordinates is None`, so now coordinates is repopulated with each run. I'm sure there is probably a better way, but this works for now.

**Comment by j-friedrich** [comment]
Yes, you need to set the coordinates to `None` before calling `cnm.estimates.plot_contours()` if you want to recalculate them. I just added this to the Docstring.
