### ISSUE TITLE
environment.yml cannot resolve

### ISSUE THREAD

**Issue by tbenst** [flatironinstitute/CaImAn#821]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Linux
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): N/A
 
 4. Which of the demo scripts you're using for your analysis (if applicable): N/A
 
 5. CaImAn version*: N/A
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

- **Describe the issue that you are experiencing**

As of 2020-10-15, when installing the environment.yml, conda cannot resolve the dependencies within 20 minutes on a fresh environment. This is easily resolved by dropping all explicit versioning with `==`.

**Comment by j-friedrich** [comment]
As of 2020-10-26 conda resolves the dependencies within 4 minutes. Would be nice to drop explicit versioning, but currently tifffile requires it.

**Comment by j-friedrich** [comment]
Fixed in the dev branch (PR #827) which allows usage of newer versions of tifffile and dropping explicit versioning.
