### ISSUE TITLE
caimanmanager.py problems

### ISSUE THREAD

**Issue by tbenst** [flatironinstitute/CaImAn#822]
- **Describe the issue that you are experiencing**
After installing with `pip install -e .`, and running `python caimanmanager.py install`, the install initially fails due to `FileNotFoundError: [Errno 2] No such file or directory: '/home/tyler/lib/anaconda3/envs/caiman/share/caiman'`. This can be fixed by `mkdir /home/tyler/lib/anaconda3/envs/caiman/share/caiman`, and the install succeeds, however, `~/caiman_data` is completely empty, and running demo_pipeline results in `FileNotFoundError: File for requested model /home/tyler/caiman_data/model/cnn_model not found`. Any tips on how to get `cnn_model`? Thx!

**Comment by tbenst** [comment]
fixed with `cp -r model ~/caiman_data` from source directory; instructions may be missing

**Comment by j-friedrich** [comment]
If you run `python caimanmanager.py install --inplace` as the instructions state, i.e. do not skip the `--inplace`, it installs just fine.
