### ISSUE TITLE
Incorrect contours of estimates.manual_merge

### ISSUE THREAD

**Issue by neuroczy** [flatironinstitute/CaImAn#823]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows 10
 2. Python version (3.x): 
 Python 3.7.3
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Anaconda Prompt
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 1.6.3
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

When using estimates.manual_merge, the contour of the new component does not have any relation to the ROIs specified to be merged.  ROIs are specified according their "ID" (beginning at 1), and not indices, as described in the documentation.  The plot below shows the components to be merged (circled in green), and the resulting component (circled in red).

![DFOF_COMPONENTS Incorrect](https://user-images.githubusercontent.com/57941148/96993111-6c6a9c00-155d-11eb-885d-775cdda89bf2.png)

In estimates.py, line 1278-1279 (manual_merge function) is:
`Acsc = self.A.tocsc()[:, merged_ROI]`
`Ctmp = np.array(self.C[merged_ROI]) + np.array(self.YrA[merged_ROI])`

If it is replaced with:
`mergedIdx = [x - 1 for x in merged_ROI]`
 `Acsc = self.A.tocsc()[:, mergedIdx]`
 `Ctmp = np.array(self.C[mergedIdx]) + np.array(self.YrA[mergedIdx])v`

The correct contours (and presumably temporal traces) are obtained:
![DFOF_COMPONENTS correct](https://user-images.githubusercontent.com/57941148/96994221-f9fabb80-155e-11eb-8078-ab5f2fc3c208.png)

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by neuroczy** [comment]
Upon further testing, the original function works as expected if pythonic indices are passed into the "components" argument.  So perhaps only the documentation needs to be updated.

However, on line 1300 of estimates.py:
`nbmrg -= len(empty)`

I believe should read:
`nbmrg -= sum(empty)`

Otherwise the variable "new_indices" on line 1315 will always be empty and not added to self.idx_components.

Thanks!

**Comment by j-friedrich** [comment]
Thanks @neuroczy , great catch. I updated the documentation and incorporated your suggested changes in the dev branch (PR #827)
