### ISSUE TITLE
CaImAn ignores user-provided quantileMin by default, and may compute baseline fluorescence across cells rather than the time dimension

### ISSUE THREAD

**Issue by Hendriela** [flatironinstitute/CaImAn#824]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Windows 10
 
 2. Python version (3.x): 
 3.7.3

 3. Working environment (Python IDE/Jupyter Notebook/other):
Pycharm 

 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
1.6.2
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda install caiman -c conda-forge

- **Describe the issue that you are experiencing**

Caiman might not be calculating the dF/F traces as one might expect.
First, the function `estimates.detrend_df_f()` has the argument `flag_auto`. This parameter is not mentioned in any of the demos, but its default value of True leads to the fact that the function ignores the user-provided quantile `quantileMin` without telling the user. This might be unexpected from the user-side, but hard to track down.

Second, the quantiles might be calculated across the wrong dimension if `flag_auto = False`.
This is the code of the function `utilities.detrend_df_f()` that is called when `flag_auto=False` (and `frames_window > T`): 
https://github.com/flatironinstitute/CaImAn/blob/87c46b76c06f32bc3a992ebee8c3ec5b90214094/caiman/source_extraction/cnmf/utilities.py#L410-L413
Here, the quantiles are calculated across the first dimension of the fluorescence matrix F (given by the argument `(frames_window, 1)`) which has the shape (#neurons, #timesteps), meaning that the percentile is calculated across cells and not time. From my understanding, computing the percentiles across cells does not make sense, and it should be across time, so `(1, frames_window)`. The same problem also exists in the `utilities.extract_DF_F()` function [here](https://github.com/flatironinstitute/CaImAn/blob/87c46b76c06f32bc3a992ebee8c3ec5b90214094/caiman/source_extraction/cnmf/utilities.py#L290-L291).

On the other hand, when `flag_auto=True`, this is how the percentiles are calculated:
https://github.com/flatironinstitute/CaImAn/blob/87c46b76c06f32bc3a992ebee8c3ec5b90214094/caiman/source_extraction/cnmf/utilities.py#L374-L377
Here, the percentiles are calculated for each neuron separately by zipping F and B, hence they are automatically computed across the time dimension (which would make sense).

Is this a bug/typo or a deliberate choice of computation?
Since `flag_auto = True` is the default and is probably not changed by the average user, Caiman should usually compute the baselines the correct way (across time), but the fact that the automatic percentile computation (and thus the ignoring of the user-provided parameter) is hidden in this argument, might still create confusion and/or problems.

**Comment by j-friedrich** [comment]
Thanks @Hendriela, great catch. I incorporated your suggested changes in the dev branch (PR #827)
