### ISSUE TITLE
Optic flow norm for motion corrected movie is higher than original

### ISSUE THREAD

**Issue by EricThomson** [flatironinstitute/CaImAn#825]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Windows
 
 2. Python version (3.x): 
3.6 

 3. Working environment (Python IDE/Jupyter Notebook/other):
Jupyter 

 4. Which of the demo scripts you're using for your analysis (if applicable):
cnmf-e demo 

 5. CaImAn version*: 
1.8.5 

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda 

- **Describe the issue that you are experiencing**
For a movie I've been analyzing, the full-field motion correction seems to work well (eyeball test and using the correlation metric between motion-corrected frames and the mean frame). However,  the residual motion calculated using the norm of the optic flow yields higher values for the corrected movie than the original. 

You can see original side by side with corrected here:
https://drive.google.com/file/d/1-rcpQCCLBLGeUujcz0e_IIOIA-4N1jyH/view?usp=sharing

At least by eye, it seems the corrected movie should have less motion energy than the original. 

The code I'm using to extract evaluation metrics:
```
bord_px_rig = np.ceil(np.max(mc.shifts_rig)).astype(np.int)
final_size = np.subtract(mc.total_template_rig.shape, 2 * bord_px_rig) # remove pixels in the boundaries
winsize = 100
swap_dim = False
play_it = False  # if you want to play: %matplotlib qt
resize_fact_flow = .2    # downsample for computing optic flow

# metrics for original
template_orig, correlations_orig, flows_orig, norms_orig, crispness_orig = \
      cm.motion_correction.compute_metrics_motion_correction(fnames[0], 
                                                             final_size[0], 
                                                             final_size[1], 
                                                             swap_dim, 
                                                             winsize=winsize, 
                                                             play_flow= play_it, 
                                                             resize_fact_flow=resize_fact_flow);

# metrics for (full-field) motion corrected
template_rig, correlations_rig, flows_rig, norms_rig, crispness_rig = \
    cm.motion_correction.compute_metrics_motion_correction(mc.fname_tot_rig[0], 
                                                           final_size[0], 
                                                           final_size[1],
                                                           swap_dim, 
                                                           winsize = winsize, 
                                                           play_flow = play_it, 
                                                           resize_fact_flow = resize_fact_flow);
```

Then for examining the results of the analysis I use:
```
# Get mean motion
print(f"Motion original: {np.mean(norms_orig)}")
print(f"Motion rigid: {np.mean(norms_rig)}")

# Plot over full
plt.figure(figsize = (18,15))
plt.plot(norms_orig, linewidth = 3, color = 'tan', label = 'original'); 
plt.plot(norms_rig, linewidth = 2, color = 'lime', label = 'rigid'); 
plt.xlabel('frame')
plt.ylabel('motion')
plt.autoscale(enable=True, axis='x', tight=True);
plt.legend();
```
This plot shows norm of optic flow vs frame:
![motion_energy](https://user-images.githubusercontent.com/6643322/97227446-df695200-17ab-11eb-9c61-9baa7c32c842.png)

I wonder if anyone has seen this, and if there are some parameters I might try messing around with in the optic flow algorithm. Right now what I'm doing is relying on the correlation measure for my quantitative metrics because it seems to be very reliable indicator of motion correction quality.

**Comment by EricThomson** [comment]
Update: when I run with the flow viewer on (set `play_flow=True` (and comment out the `vmin/vmax` limits which make my video appear white), it seems what is happening is that because I am using 1p endoscope data when there are very large-scale fluctuations in bg activity, there are clearly high levels of motion energy in both x and y. So a few thoughts here:

- off the shelf, optic flow may not be the best option for evaluating 1p data, 
- the correlation metric seems very reliable so use that
- if I were to use optic flow, I would consider doing it to a high-pass filtered version of the motion-corrected data that has these background artifacts removed. I have not tried this out.

**Comment by j-friedrich** [comment]
On one of my datasets the optic flow norm for the motion corrected movie was indeed higher than original. That's not the case if the metrics are calculated on the high-pass filtered data that's used for motion correction of 1p data.
I added the `gSig_filt` argument to `compute_metrics_motion_correction()` to facilitate that in my commit to dev.

**Comment by EricThomson** [comment]
I wanted to mention that I finally got around to thoroughly testing this out today and it looks great now. Many thanks @j-friedrich

**Comment by j-friedrich** [comment]
Thanks for your feedback, great to hear!
