### ISSUE TITLE
OS: Windows 10

### ISSUE THREAD

**Issue by albilard** [flatironinstitute/CaImAn#828]
1. Operating system (Linux/macOS/Windows): Windows 10
 
 2. Python version (3.x): 3.7.8
 
 3. Working environment (Python IDE/Jupyter Notebook/other): 
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 1.8.5
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda-forge

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
When I run caimanmanager.py install or python ~/caimanmanager.py install the script doesn't run.

- **Copy error log below**
File "caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
  File "C:\Users\Mangana\Anaconda3\envs\caiman\lib\site-packages\caiman\__init__.py", line 4, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "C:\Users\Mangana\Anaconda3\envs\caiman\lib\site-packages\caiman\base\movies.py", line 18, in <module>
    import cv2
ImportError: DLL load failed: The specified module could not be found.

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi, from what directory are you trying to run this?

**Comment by albilard** [comment]
Hi, thanks for getting back to me. The directory was "C:\Users\Mangana\". I solved it finally yesterday after I reinstalled for the 3rd time Visual studio with the VC redistributable 2015-2019. Don't really know why was not working before.
