### ISSUE TITLE
Support pathlib for file paths

### ISSUE THREAD

**Issue by orena1** [flatironinstitute/CaImAn#830]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
Windows, but it does not matter
  2. Python version (3.x): 
 3.8

- **Describe the issue that you are experiencing**
As far as I see `get_file_size` - does not accept [pathlib Paths](https://docs.python.org/3/library/pathlib.html#pathlib.Path), https://github.com/flatironinstitute/CaImAn/blob/87c46b76c06f32bc3a992ebee8c3ec5b90214094/caiman/source_extraction/cnmf/utilities.py#L974 fails because Path is not a string

- **Copy error log below**
```
~\software\CaImAn\caiman\source_extraction\cnmf\utilities.py in get_file_size(file_name, var_name_hdf5)
   1052                 for fn in file_name])
   1053     else:
-> 1054         raise Exception('Unknown input type')

%debug
> c:\users\oamsalem\software\caiman\caiman\source_extraction\cnmf\utilities.py(1054)get_file_size()
   1052                 for fn in file_name])
   1053     else:
-> 1054         raise Exception('Unknown input type')
   1055     return dims, T
   1056 

ipdb> file_name
WindowsPath('D:/2p_data/scan/OAM3/201108_OAM3/201108_OAM3_003/plane_split/mean_over_planes.tiff')
ipdb> isinstance(file_name, list)
False
```

Thanks

**Comment by pgunn** [comment]
Right now I'm not sure whether removing this check would just cause a failure somewhere else; the APIs were not written with pathlib in mind. Before I dig further, what's driving this need?

**Comment by orena1** [comment]
Hi, I don't think you should remove the check, but actually, add another one:
https://stackoverflow.com/questions/58647584/how-to-test-if-object-is-a-pathlib-path

I assume the drive for this is future support, I think more people are going to use pathlib as time goes on, so it might be good to support it. 
(I just did str(path_for_file), and it is working well). It might be labeled as _enchantment_, and it is not a pressing issue.
 
Thanks!

**Comment by pgunn** [comment]
I'll look into rolling this into the next release. It's a good idea.

**Comment by pgunn** [comment]
@orena1 There may be some more things we'll want to change elsewhere in the code (and I should write some tests for pathlib), but at least that particular issue is now fixed in dev. I suspect (depending on available time from a coworker) we'll be cutting a new release within a week or so. Thanks for the suggestion!
