### ISSUE TITLE
motion correction bug?

### ISSUE THREAD

**Issue by SophiePinder** [flatironinstitute/CaImAn#833]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1.Linux: 
 
 2. Python version (3.x): 
 
 3. Working environment Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

Hi, i'm using the demo_online_CNMFE to analyse my data, i've used it before and its worked fine. But now it stops when it gets to the motion correction step and nothing happens, there is no error it runs 6 lines and then nothing else happens. Please see below.

This is the code I used. 
mc = MotionCorrect(fnames, dview=dview, **opts.get_group('motion'))
mc.motion_correct(save_movie=True)

this is the output 

105428 [movies.py:extract_shifts():371] [20584] Movie average is negative. Removing 1st percentile.
      105472 [movies.py:extract_shifts():389] [20584] Movie average is negative. Removing 1st percentile.
      106670 [movies.py:extract_shifts():371] [20584] Movie average is negative. Removing 1st percentile.
      106716 [movies.py:extract_shifts():389] [20584] Movie average is negative. Removing 1st percentile.
      107875 [movies.py:extract_shifts():371] [20584] Movie average is negative. Removing 1st percentile.
      107922 [movies.py:extract_shifts():389] [20584] Movie average is negative. Removing 1st percentile.

**Comment by j-friedrich** [comment]
Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

**Comment by SophiePinder** [comment]
> Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

Hi, when I changed dview=None, the same error message appeared and the kernel died

**Comment by SophiePinder** [comment]
I've reinstalled CaiMan and using the demo file and parameters and I'm still have the same problem

**Comment by agiovann** [comment]
Any update on this?

**Comment by SophiePinder** [comment]
its working now, I think it was a memory issue on my computer, thanks for the help!

**Comment by PLoizidou** [comment]
I am experiencing the same issue. Could you describe how you solved it?

**Comment by pgunn** [comment]
@PLoizidou Do you mind opening a new issue? I doubt what you're seeing has the same cause as this issue, and we don't want to bug the people who were active on this ticket.
