### ISSUE TITLE
Matrix C contains negative values

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#834]
I am not sure if this is a problem, however, the matrix C 
`np.take(cnm_est_eval.estimates.C, cnm_est_eval.estimates.idx_components, axis=0))` returns a N*t matrix (N is number of neurons, t is time). But it contains negative values. Is that normal ? If the above gives the fluorescent trace of each neuron, then i assumed they must have only positive (brightness) values ? Kindly help me understand. 
Although, our data is quite noisy, we used caiman's motion correction, cell detection and multisession registration methods using appropriate thresholding. Some sample images are in these issues raised in the past: https://github.com/flatironinstitute/CaImAn/issues/758

**Comment by j-friedrich** [comment]
You can enforce the non-negativity constraint on `C` by setting `bas_nonneg=True` when creating the `cnmf.params.CNMFParams` object.
See issue #783 for more details

**Comment by akatav** [comment]
@j-friedrich thank you. Because I have done motion correction and cell detection already, Can i simply set cnm.params.set('temporal',{'bas_nonneg':True}) and expect the same result ?
