### ISSUE TITLE
error when running caiman_gui

### ISSUE THREAD

**Issue by ASiliciano** [flatironinstitute/CaImAn#839]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
macOS Mojave 10.14.4
 
 2. Python version (3.x): 
3.7.8
 
 3. Working environment (Python IDE/Jupyter Notebook/other): 
other

 4. Which of the demo scripts you're using for your analysis (if applicable): 
bin/caiman_gui.py
 
 5. CaImAn version*: 
1.8.5
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda

- **Describe the issue that you are experiencing**
I'm trying to open the dendritic_analysis.hdf5 and the corresponding memory map using the caiman_gui and get the following error in the terminal window after trying to load dendritic_analysis.hdf5.  I also tried this on my own data and get the same error.

Thanks!

(caiman) Andrews-MacBook-Pro:bin andrewsiliciano$ python caiman_gui.py
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Not launched under iPython
objc[1952]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff901913c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x14f379f50). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "caiman_gui.py", line 293, in <module>
    draw_contours()
  File "caiman_gui.py", line 177, in draw_contours
    idx1 = np.where(SNRs[iidd] < 0.1)[0]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

**Comment by pgunn** [comment]
@caichangjia Any insights on this?

**Comment by caichangjia** [comment]
Hi @ASiliciano. Would you please tell me which demo you used for processing the data and how you output the dendritic_analysis.hdf5?

**Comment by ASiliciano** [comment]
I'm running the demo_dendritic notebook.  In the **save the object** kernel, uncommented and ran:
`
cnm2.estimates.Cn = CI # save the correlation image for displaying in the background
cnm2.save('dendritic_analysis.hdf5')
`

**Comment by caichangjia** [comment]
@ASiliciano I have checked the problem. The direct reason for causing this error is that there is no component evaluation and extract DF/F step in this demo. So the GUI can not load it. To solve that, just add the code I attached below before "play a movie with the results" part. I will ask pull request to fix this problem.
However, I also found that the current GUI is not suitable for visualizing the dendritic data. It can not show the spatial contour of dendrites well unfortunately. I suppose the best thing you can do currently is to use component evaluation part to select dendrites.

**Comment by caichangjia** [comment]
Component evaluation
```
min_SNR = 2  # signal to noise ratio for accepting a component
rval_thr = 0.85  # space correlation threshold for accepting a component
cnn_thr = 0.99  # threshold for CNN based classifier
cnn_lowest = 0.1 # neurons with cnn probability lower than this value are rejected

cnm2.params.set('quality', {'decay_time': decay_time,
                           'min_SNR': min_SNR,
                           'rval_thr': rval_thr,
                           'use_cnn': False, # do not use cnn for dentritic data
                           'min_cnn_thr': cnn_thr,
                           'cnn_lowest': cnn_lowest})

cnm2.estimates.evaluate_components(images, cnm2.params, dview=dview)
```
Extract DF/F values
```
cnm2.estimates.detrend_df_f(quantileMin=8, frames_window=250)
```
Visualize selected components
```
cnm2.estimates.hv_view_components(img=CI, idx=cnm2.estimates.idx_components)
```

**Comment by ASiliciano** [comment]
Thanks!
