### ISSUE TITLE
Math domain error during deconvolution

### ISSUE THREAD

**Issue by GarrettBlair** [flatironinstitute/CaImAn#840]
1. Operating system (Linux/macOS/Windows): Windows 10 64 bit, 128GB RAM, no GPU, running in parallel on AMD Ryzen 1950x

2. Python version (3.x): Python ver 3.7.6

3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Lab

4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline_cnmfe

5. CaImAn version: 1.8.5

6. CaImAn installation process (pip install ./pip install -e ./conda): pip install -e

- **Describe the issue that you are experiencing**

Math domain error during deconvolution. This started happening recently with an older data set that didn't have this issue before. Appreciate any help!

- **Copy error log below**
---------------------------------------------------------------------------

_3415437 [temporal.py:update_temporal_components():215] [9012] entering the deconvolution_ 
**c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\deconvolution.py:1051: RuntimeWarning: divide by zero encountered in log**
  'logmexp': lambda Pxx_ind: np.sqrt(np.exp(np.mean(np.log(old_div(Pxx_ind, 2)))))
ValueError                                Traceback (most recent call last)
<ipython-input-6-e371b8e58e36> in <module>
    109     ## Perform cnmfe
    110     `cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, Ain=Ain, params=opts)`
--> 111     `cnm.fit(images)`
    112     ## component eval
.
.
.
.
.
c:\users\blairlab-01\caiman\caiman\source_extraction\cnmf\deconvolution.py in constrained_oasisAR2(y, g, sn, optimize_b, b_nonneg, optimize_g, decimate, shift, window, tol, max_iter, penalty, s_min)
    745             g[1] = -d * r
    746             g11 = (np.exp(log(d) * np.arange(1, T + 1)) -
--> 747                    np.exp(log(r) * np.arange(1, T + 1))) / (d - r)
    748             g12 = np.append(0, g[1] * g11[:-1])
    749             g11g11 = np.cumsum(g11 * g11)

**ValueError: math domain error**

Screenshot of full error:
![error log full](https://user-images.githubusercontent.com/40305871/101421994-7563c280-38aa-11eb-881d-0645dcfd405f.png)

**Comment by pgunn** [comment]
@j-friedrich It seems most likely that either d or r is 0 or less for this user's data, as taking the log of a non-positive number is a cause of this exact error. Do you have any idea how this might happen in cnmf?

**Comment by GarrettBlair** [comment]
Just updating on the status, I've been running caiman for a few weeks now without this issue coming back up. Some combination of windows and python updates would be my guess to the fix.
