### ISSUE TITLE
How to run NoRMCorre?

### ISSUE THREAD

**Issue by mariakesa** [flatironinstitute/CaImAn#841]
- **If you're not reporting an error, type your message below**

Hello, I have a simple question. How do I use the MotionCorrection class to run the NoRMCorre algorithm:-)?

All the very best,
Maria

**Comment by pgunn** [comment]
My impression is that that's the default algorithm we use for motion correction.

**Comment by mariakesa** [comment]
Thanks:-)!

I have a file shaped (n_timep,n_planes,x_dim,y_dim). Do I have to reshape it to use MotionCorrection? What shape does it expect? Sorry, I couldn't find it in the code.

**Comment by mariakesa** [comment]
I have another question. What would be good values (approximately) of max_shifts, strides and overlaps for a 3D stack of size (21, 1024,1024)? Help would be appreciated!

**Comment by j-friedrich** [comment]
Assuming you don't have much z-motion, I'd try something in the ballpark of
```
strides = (4, 64, 64) 
overlaps = (2, 24, 24)
max_shifts = (1,6,6)
```
