### ISSUE TITLE
Structural segmentation

### ISSUE THREAD

**Issue by michaelthornton** [flatironinstitute/CaImAn#842]
Hello I am running experiments in which I am performing cell body neuronal calcium imaging, then applying a drug that silences neuronal firing, and then imaging the same 'silenced' cells after drug application. Therefore I would like to automatically segment the average projection and use those detected rois in order to retain the silenced neurons in the second condition. I think "Algorithm 3: Seeded Initialization" is what I am after, but I am having trouble finding more detailed information in the docs. Is there a detailed documentation (for a python novice) of how to implement this initialization?

I do have Caiman successfully installed on my PC, windows 10. 

Thanks

**Comment by j-friedrich** [comment]
You can run the pipeline on the data prior to silencing:
```
cnm = cnmf.CNMF(n_processes, params=opts)
cnm = cnm.fit(data)
```
and use the resulting ROIS to obtain the time series on the silenced data
```
cnm2 = deepcopy(cnm)
# initialize timeseries of neurons and background as zeros
cnm2.estimates.C = np.zeros((len(cnm2.estimates.C), len(images2)), dtype=np.float32)
cnm2.estimates.f = np.zeros((len(cnm2.estimates.f), len(images2)), dtype=np.float32)
cnm2.update_temporal(silenced_data.to_2D().T)
```
If you want to update the ROIS on the silenced data (which can be a bad idea, if you get higher quality ROIs on the data prior to silencing), you'd follow it up with
```
cnm2.fit(silenced_data)
```

For a more complete script based on the basic demo:
[silence.ipynb.zip](https://github.com/flatironinstitute/CaImAn/files/5821884/silence.ipynb.zip)

**Comment by agiovann** [comment]
@michaelthornton did this help?

**Comment by michaelthornton** [comment]
Hello, thank you so much for the thorough response and examples. My focus has shifted from these analyses but will respond back when I can try it out ASAP.
