### ISSUE TITLE
Errors running demo_Ring_CNN.ipynb

### ISSUE THREAD

**Issue by emackev** [flatironinstitute/CaImAn#844]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Linux
 
 2. Python version (3.x): Python 3.7.9
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_Ring_CNN.ipynb
 
 5. CaImAn version*: 1.8.6
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): pip install -e .

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

I recently started trying to use CaImAn on a GPU cluster, intending to use the ring CNN model.  The demo_pipeline_cnmfE.ipynb works with no bug.  But I run into bugs when I run the demo_Ring_CNN.ipynb demo (see below). 

- **Copy error log below**

     4020896 [movies.py:                load():1516] [156764] Loading a *.mat file. x- and y- dimensions might have been swapped.
/home/em3406/.conda/envs/caiman/lib/python3.7/site-packages/sklearn/decomposition/_nmf.py:1091: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  " improve convergence." % max_iter, ConvergenceWarning)
     4040412 [online_cnmf.py:          fit_online():1211] [156764] Now processing file /engram/aronov/emily/caiman_data/example_movies/blood_vessel_10Hz.mat
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-6496a5988657> in <module>
      3 if run_onacid:
      4     cnm = cnmf.online_cnmf.OnACID(params=opts)
----> 5     cnm.fit_online()
      6     fld_name = os.path.dirname(cnm.params.ring_CNN['path_to_model'])
      7     res_name_nm = os.path.join(fld_name, 'onacid_results_nm.hdf5')

/engram/aronov/emily/CaImAn/caiman/source_extraction/cnmf/online_cnmf.py in fit_online(self, **kwargs)
   1262                             frame_cor = frame_cor/self.img_norm
   1263                         # Fit next frame
-> 1264                         self.fit_next(t, frame_cor.reshape(-1, order='F'))
   1265                         # Show
   1266                         if self.params.get('online', 'show_movie'):

/engram/aronov/emily/CaImAn/caiman/source_extraction/cnmf/online_cnmf.py in fit_next(self, t, frame_in, num_iters_hals)
    549                 upscale_matrix=self.estimates.upscale_matrix if
    550                 (self.is1p and ssub_B > 1) else None,
--> 551                 max_img=self.estimates.max_img if use_corr else None)
    552 
    553             num_added = len(self.ind_A) - self.N

/engram/aronov/emily/CaImAn/caiman/source_extraction/cnmf/online_cnmf.py in update_num_components(t, sv, Ab, Cf, Yres_buf, Y_buf, rho_buf, dims, gSig, gSiz, ind_A, CY, CC, groups, oases, gnb, rval_thr, bSiz, robust_std, N_samples_exceptionality, remove_baseline, thresh_fitness_delta, thresh_fitness_raw, thresh_overlap, batch_update_suff_stat, sn, g, thresh_s_min, s_min, Ab_dense, max_num_added, min_num_trial, loaded_model, thresh_CNN_noisy, sniper_mode, use_peak_max, test_both, mean_buff, ssub_B, W, b0, corr_img, first_moment, second_moment, crosscorr, col_ind, row_ind, corr_img_mode, max_img, downscale_matrix, upscale_matrix, tf_in, tf_out)
   2227         loaded_model=loaded_model, thresh_CNN_noisy=thresh_CNN_noisy,
   2228         use_peak_max=use_peak_max, test_both=test_both, mean_buff=mean_buff,
-> 2229         tf_in=tf_in, tf_out=tf_out)
   2230 
   2231     ind_new_all = ijsig_all

/engram/aronov/emily/CaImAn/caiman/source_extraction/cnmf/online_cnmf.py in get_candidate_components(sv, dims, Yres_buf, min_num_trial, gSig, gHalf, sniper_mode, rval_thr, patch_size, loaded_model, test_both, thresh_CNN_noisy, use_peak_max, thresh_std_peak_resid, mean_buff, tf_in, tf_out)
   2085         local_maxima = peak_local_max(img_select_peaks,
   2086                                       min_distance=np.max(np.array(gSig)).astype(np.int),
-> 2087                                       num_peaks=min_num_trial,threshold_abs=thresh_img_sel, exclude_border = False)
   2088         min_num_trial = np.minimum(len(local_maxima),min_num_trial)
   2089 

/engram/aronov/emily/CaImAn/caiman/source_extraction/cnmf/utilities.py in peak_local_max(image, min_distance, threshold_abs, threshold_rel, exclude_border, indices, num_peaks, footprint)
    201 
    202     # Select highest intensities (num_peaks)
--> 203     coordinates = _get_high_intensity_peaks(image, mask, num_peaks)
    204 
    205     if indices is True:

TypeError: _get_high_intensity_peaks() missing 2 required positional arguments: 'min_distance' and 'p_norm'

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
@j-friedrich I think _get_high_intensity_peaks() is an internal call of skimage.feature.peak and thus doesn't have a stable API. Is there any way to write this demo so we're not using that call? I'm guessing this issue came about because a version difference shifted the internal API around.

**Comment by pgunn** [comment]
Looks like this scikit-image diff in particular refactored that function:

https://github.com/scikit-image/scikit-image/commit/a04bd6be9bce3ed0be557f68acc2cee658d9236d#diff-32fbdda8cb4ac28e0f020c9b3ee8ddc26ecea52825c77dc92c512db4ed1f1cddL9

**Comment by j-friedrich** [comment]
Just fixed it in the dev branch. Should I also update master?

**Comment by pgunn** [comment]
For this, as it's just a notebook, yes.
