### ISSUE TITLE
pw_rigid motion correction error

### ISSUE THREAD

**Issue by mariakesa** [flatironinstitute/CaImAn#845]
Hello,

I am trying to get the pw_rigid registration to work. 

I gave the model the following parameters:

```
max_shifts = (6, 6,6)  # maximum allowed rigid shift in pixels (view the movie to get a sense of motion)
    strides =  (48, 48)  # create a new patch every x pixels for pw-rigid correction
    overlaps = (24, 24)  # overlap between pathes (size of patch strides+overlaps)
    num_frames_split = 100  # length in frames of each chunk of the movie (to be processed in parallel)
    max_deviation_rigid = 3   # maximum deviation allowed for patch with respect to rigid shifts
    pw_rigid = True  # flag for performing rigid or piecewise rigid motion correction
    shifts_opencv = True  # flag for correcting motion using bicubic interpolation (otherwise FFT interpolation is used)
    border_nan = 'copy'  # replicate values along the boundary (if True, fill in with NaN)
    is_3D=True

    mc = MotionCorrect(h5_filename,max_shifts=max_shifts,
                      strides=strides, overlaps=overlaps,
                      max_deviation_rigid=max_deviation_rigid,
                      shifts_opencv=shifts_opencv, nonneg_movie=True,
                      border_nan=border_nan,is3D=is_3D,pw_rigid=True)

```
I get the following error:

Traceback (most recent call last):
  File "non_rigid_registration.py", line 4593, in <module>
    reg_pipeline(lif_filename,h5_filename,reg_file)
  File "non_rigid_registration.py", line 4576, in reg_pipeline
    mc.motion_correct(save_movie=True)
  File "non_rigid_registration.py", line 678, in motion_correct
    self.motion_correct_pwrigid(template=template, save_movie=save_movie)
  File "non_rigid_registration.py", line 792, in motion_correct_pwrigid
    _x_shifts_els, _y_shifts_els, _z_shifts_els, _coord_shifts_els = motion_correct_batch_pwrigid(
  File "non_rigid_registration.py", line 3376, in motion_correct_batch_pwrigid
    fname_tot_els, res_el = motion_correction_piecewise(fname, splits, strides, overlaps,
  File "non_rigid_registration.py", line 3577, in motion_correction_piecewise
    res = list(map(tile_and_correct_wrapper, pars))
  File "non_rigid_registration.py", line 3458, in tile_and_correct_wrapper
    mc[count], total_shift, start_step, xyz_grid = tile_and_correct_3d(img, template, strides, overlaps, max_shifts,
  File "non_rigid_registration.py", line 2830, in tile_and_correct_3d
    templates = [
  File "non_rigid_registration.py", line 2830, in <listcomp>
    templates = [
  File "non_rigid_registration.py", line 2399, in sliding_window_3d
    0, image.shape[2] - windowSize[2], strides[2])) + [image.shape[2] - windowSize[2]]
IndexError: index 2 is out of bounds for axis 0 with size 2

My question is, what does this error mean and does it mean I have to calculate special window sizes so that the dimensionalities are correct?

Thank you so much!

Maria

**Comment by pgunn** [comment]
Hi,
What version of the codebase are you using? I'm not familiar with a file called non_rigid_registration.py

**Comment by j-friedrich** [comment]
Hi @mariakesa 
for 3D data `strides`, `overlaps`and `indices` have to be a tuples of length 3. The following works:
```
max_shifts = (6, 6, 6)  # maximum allowed rigid shift in pixels (view the movie to get a sense of motion)
strides =  (48, 48, 48)  # create a new patch every x pixels for pw-rigid correction
overlaps = (24, 24, 24)  # overlap between pathes (size of patch strides+overlaps)
num_frames_split = 100  # length in frames of each chunk of the movie (to be processed in parallel)
max_deviation_rigid = 3   # maximum deviation allowed for patch with respect to rigid shifts
pw_rigid = True  # flag for performing rigid or piecewise rigid motion correction
shifts_opencv = True  # flag for correcting motion using bicubic interpolation (otherwise FFT interpolation is used)
border_nan = 'copy'  # replicate values along the boundary (if True, fill in with NaN)
is_3D=True
indices = (slice(0,None,1), slice(0,None,1), slice(0,None,1))

mc = cm.motion_correction.MotionCorrect(fnames,max_shifts=max_shifts,
                  strides=strides, overlaps=overlaps,
                  max_deviation_rigid=max_deviation_rigid,
                  shifts_opencv=shifts_opencv, nonneg_movie=True,
                  border_nan=border_nan,is3D=is_3D,pw_rigid=True, indices=indices)
``` 

See also the [3D demo notebook](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_caiman_cnmf_3D.ipynb)

**Comment by mariakesa** [comment]
Thank you so much!:-)

**Comment by j-friedrich** [comment]
Great! Note that for anisotropic data you'd want to use different values for different directions, cf. #841.
