### ISSUE TITLE
"ConvergenceWarning: Maximum number of iterations 100 reached. Increase it to improve convergence."

### ISSUE THREAD

**Issue by seasonqiu** [flatironinstitute/CaImAn#847]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux
 2. Python version (3.x): 
3.7
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Terminal
 4. Which of the demo scripts you're using for your analysis (if applicable):
 N/A
 5. CaImAn version*: 
 1.8.5
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda forge
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I experienced a convergence warning when using the cnmf fit method.
My question is how should I manage this, where can I modify the max_iter value. What is the best way goes about it?

Detail:
The warning occurs in
`
    c, dview, n_processes = cm.cluster.setup_cluster(backend='local', n_processes=n_p2, single_thread=False)
    cnm0 = cnmf.CNMF(n_processes, params=opts, dview=dview)
    cnm0 = cnm0.fit(images, indices=sls)
`
in the line that uses cnm0.fit(images, indices = sls)

the warning is:
```
.../anaconda3/envs/caiman/lib/python3.7/site-packages/sklearn/decomposition/_nmf.py:1077: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  " improve convergence." % max_iter, ConvergenceWarning)
```

This message appears more than twenty times, and the last message(different from all the previous message) is:
```
.../anaconda3/envs/caiman/lib/python3.7/site-packages/sklearn/decomposition/_nmf.py:1077: ConvergenceWarning: Maximum number of iterations 100 reached. Increase it to improve convergence.
  " improve convergence." % max_iter, ConvergenceWarning)
```

- **Copy error log below**
```
.../anaconda3/envs/caiman/lib/python3.7/site-packages/sklearn/decomposition/_nmf.py:1077: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  " improve convergence." % max_iter, ConvergenceWarning)
...(dozens of the same messages)
.../anaconda3/envs/caiman/lib/python3.7/site-packages/sklearn/decomposition/_nmf.py:1077: ConvergenceWarning: Maximum number of iterations 100 reached. Increase it to improve convergence.
  " improve convergence." % max_iter, ConvergenceWarning)
```

- **If you're not reporting an error, type your message below**

**Comment by agiovann** [comment]
Is this affecting visibly your results? If not, you should not worry too much since we refine these components in a the second portion of the algorithm.

**Comment by seasonqiu** [comment]
Thank you for answering. I moved forward without changing anything, and I got 257 components and 437 bad components from 
`len(cnm.estimates.idx_components), len(cnm.estimates.idx_components_bad)`
The result also shown a lot of good components from the fit does not look like cell, as shown in the image below:
![pCompCont](https://user-images.githubusercontent.com/5386553/106412700-4a998300-6483-11eb-870f-8b8419d37614.png)

When I proceed to examine closer into the cnm file, I found there was no discarded component in it. I wonder if this is the result of not reaching the conergence.
![pCompCont](https://user-images.githubusercontent.com/5386553/106413084-29856200-6484-11eb-8082-78f4f6d8fc5e.png)


Note: I have not started labeling the cell manually yet.

Thank you for your time.

**Comment by j-friedrich** [comment]
This warning can be safely ignored. 200 iterations are more than enough for NMF via coordinate decent (HALS). For rank-1 NMF, which is often our usage case, actually no iterations are needed at all with the SVD-based initialization because rank 1 SVD of (nonnegative) A = best rank-one NMF of A . (Perron-Frobenius)
