### ISSUE TITLE
Error: "No module named past"

### ISSUE THREAD

**Issue by adeyemi-lawal** [flatironinstitute/CaImAn#848]
Operating system: macOs

Python Version: 3.8

Working environment: Jupyter Notebook

CaImAn installation process: pip install -e

When I try to import caiman, I get the following error log, 'No modules named past'.  Does anyone know why this is?

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d8020da47a60> in <module>
----> 1 import caiman as cm

~/CaImAn/caiman/__init__.py in <module>
      2 
      3 import pkg_resources
----> 4 from .base.movies import movie, load, load_movie_chain
      5 from .base.timeseries import concatenate
      6 from .cluster import start_server, stop_server

~/CaImAn/caiman/base/movies.py in <module>
     14 from builtins import str
     15 from builtins import range
---> 16 from past.utils import old_div
     17 
     18 import cv2

ModuleNotFoundError: No module named 'past'

```

**Comment by pgunn** [comment]
Hi,
please activate the appropriate environment and do:
`conda list | grep future`

**Comment by adeyemi-lawal** [comment]
Hi Pat,

I followed your instructions and am still receiving the same error
message.  It seems like there is no package named "future" in my
environment.  Should I delete the environment, and create it again?

Best,
Yemi Lawal

**Comment by pgunn** [comment]
You could, but I'm puzzled how you ended up without it to begin with, and whether there are other modules you may also be missing.

Can you remind me how you made the environment, and whether you installed jupyter through conda or through some other means?

**Comment by adeyemi-lawal** [comment]
I pip installed jupyter a while back and I made the environment with
anaconda using the following commands

git clone https://github.com/flatironinstitute/CaImAncd CaImAn/conda
env create -f environment.yml -n caimansource activate caimanpip
install -e

Update: So I'm no longer getting the "no module named past" error, instead
I'm receiving a "No module named caiman" error.  This started after I
opened a jupyter notebook from the anaconda navigator dashboard (caiman
env).  So I think the problem is that maybe there are two conflicting
versions of jupyter notebook??

**Comment by pgunn** [comment]
I suspect you're not in the right environment for caiman to function. I don't have experience with conda navigator. If you can manage to do this, it should work:

delete existing caiman environment
remake it with `conda env create ...`
activate it
add jupyter to it with `conda install jupyter
install the caiman package into it with pip`
Use caimanmanager to install the datafiles
launch jupyter from the commandline (still in that environment)
run notebooks as you like from the jupyter you launched from your environment, not messing with kernels at all

**Comment by adeyemi-lawal** [comment]
Ok, so after some finagling, I realized that in order for CaImAn to work, I
had to downgrade the version of python that I was using on anaconda.  I
have done that and the line "import caiman as cm" seemed to be working
fine.  However, soon thereafter an error message was triggered.  It seems
to be an ImportError at the end of which it says "Failed to load the native
TensorFlow runtime". Which leads me to my question, Do I have to install
Tensorflow on Conda to be able to use caiman?

**Comment by agiovann** [comment]
@pgunn: can this be running with Python 3.8? Maybe that is the issue?

**Comment by adeyemi-lawal** [comment]
No worries, I figured it out last week.  I had to downgrade the version of
Python that I was using to 3.5 and then upgrade the version of tensorflow I
was using to 2.0.0.  Thanks for all the help though, I really appreciate it.

**Comment by pgunn** [comment]
Python 3.5 shouldn't be necessary. Closing this for now though.
