### ISSUE TITLE
Online demo getting weird flipped calcium transients

### ISSUE THREAD

**Issue by agiovann** [flatironinstitute/CaImAn#849]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 MAC and Linux
 2. Python version (3.x): 
 3.7
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Spyder
 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_onacid.py
 5. CaImAn version*:
 dev branch, current  
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e .
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)
not needed here, just run demo
- **Describe the issue that you are experiencing**

See example components that are plotted after running the demo. I think the same happens with demo_onacid_mesoscope.py. This is a serious error which should be fixed urgently!

- **Copy error log below**

- **If you're not reporting an error, type your message below**
![image](https://user-images.githubusercontent.com/7879758/105783483-9492de00-5f44-11eb-8bd0-847abf8e69bd.png)
![image](https://user-images.githubusercontent.com/7879758/105783518-a5435400-5f44-11eb-93d7-40e223fa99cf.png)

**Comment by j-friedrich** [comment]
Apparently using an average of the past M~50 denoised frames as a MC template harms for 2p data. Kept it for 1p, but restored the previous version (M=1) for 2p.
