### ISSUE TITLE
z-correction

### ISSUE THREAD

**Issue by mariakesa** [flatironinstitute/CaImAn#850]
Hello,

Is it possible to do z-correction in Caiman. My data is 3D+time. I gave the max_shifts parameter a 3D array. Will it do z-correction with this code?

```
mc = MotionCorrect(h5_filename,max_shifts=max_shifts,
                      strides=strides, overlaps=overlaps,
                      max_deviation_rigid=max_deviation_rigid,
                      shifts_opencv=shifts_opencv, nonneg_movie=True,
                      border_nan=border_nan,is3D=is_3D,use_cuda=True)
mc.motion_correct(save_movie=True)
```

Thank you for your help:-)

**Comment by j-friedrich** [comment]
Yes, it will do z correction. Just make sure strides, overlaps and max_shifts are 3-tuples.
For an example see the [3D demo](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_caiman_cnmf_3D.ipynb) that includes motion correction.
