### ISSUE TITLE
Using CNN in cnmfE pipeline

### ISSUE THREAD

**Issue by Bilalgp** [flatironinstitute/CaImAn#853]
Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 
 Windows 
 2. Python version (3.x): 
 
3.7.9

 3. Working environment (Python IDE/Jupyter Notebook/other):
 
Jupyter

 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo
 5. CaImAn version*: 
 1.8.

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

I am trying to use the CNN = True in the CNMFE pipeline but I keep running into an error "slice indices must be integers or None or have an __index__ method". I am not sure how to troubleshoot. 

- **Copy error log below**

![image](https://user-images.githubusercontent.com/26805330/107137199-ff92cc00-68d7-11eb-9949-3865c1473ef9.png)

- **If you're not reporting an error, type your message below**

**Comment by EricThomson** [comment]
Just as an fyi, I believe the cnn was trained on 2p data so I wouldn't use it for 1p data (devs can correct me if I am wrong). For instance see p 9 of caiman paper. I take it this is why that param is set to False in the CNMF-E demo. It might be helpful to explicitly discuss this in the demo.

**Comment by j-friedrich** [comment]
@EricThomson is correct. I added the explanation to the CNMF-E demo.
