### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'step'

### ISSUE THREAD

**Issue by SophiePinder** [flatironinstitute/CaImAn#854]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): linux
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other):jupyter notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_online_cmnfe
 
 5. CaImAn version*: latest
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

Whenever I try to analysis two files instead of one, I get the below error. I've seen that other people have had the same error and it was advised to change cnm.estimates.dims = (320, 320) and cnm.dims = (320, 320). I've tried this but it doesn't work. Does anyone else know how to solve this error?

- **Copy error log below**

TypeError                                 Traceback (most recent call last)
~/miniconda3/envs/caiman/lib/python3.7/site-packages/numpy/lib/index_tricks.py in __getitem__(self, key)
    162                     size.append(
--> 163                         int(math.ceil((key[k].stop - start)/(step*1.0))))
    164                 if (isinstance(step, (_nx.floating, float)) or

TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
~/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/estimates.py in plot_contours_nb(self, img, idx, thr_method, thr, params, line_color, cmap)
    256                 self.coordinates = caiman.utils.visualization.get_contours(self.A,
--> 257                                         self.dims, thr=thr, thr_method=thr_method)
    258             if idx is None:

~/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/utils/visualization.py in get_contours(A, dims, thr, thr_method, swap_dim)
    355         d1, d2 = dims
--> 356         x, y = np.mgrid[0:d1:1, 0:d2:1]
    357 

~/miniconda3/envs/caiman/lib/python3.7/site-packages/numpy/lib/index_tricks.py in __getitem__(self, key)
    192         except (IndexError, TypeError):
--> 193             step = key.step
    194             stop = key.stop

AttributeError: 'tuple' object has no attribute 'step'

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-12-fa931d91d378> in <module>
----> 1 cnm.estimates.plot_contours_nb(img=pnr)

~/miniconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/estimates.py in plot_contours_nb(self, img, idx, thr_method, thr, params, line_color, cmap)
    306             print("Bokeh could not be loaded. Either it is not installed or you are not running within a notebook")
    307             print("Using non-interactive plot as fallback")
--> 308             self.plot_contours(img=img, idx=idx, crd=crd, thr_method=thr_method,
    309                                thr=thr, params=params, cmap=cmap)
    310         return self

NameError: name 'crd' is not defined
- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
While some people have solved this by concatenating their files together using numpy or ImageJ, we should be able to support this in Caiman. Can you show me how you tried loading the files?

**Comment by SophiePinder** [comment]
@pgunn 

Hi, I tried combining two videos together and I was able to get pass this step, however my computer could only deal with two combined videos, when I tried to do more it just stopped working.

I use this code to load multiple videos. 

fnames = ('msCam1_H14_M27_S24.tif','msCam1_H14_M27_S24.tif')
fnames = [download_demo(fnames[0]), download_demo(fnames[1])]

thanks!

**Comment by j-friedrich** [comment]
Fixed it just now in the recent commit to dev.

**Comment by pgunn** [comment]
I'll cut a new release later this week to get this out there.
