### ISSUE TITLE
Reloading data to caiman file from hdf5

### ISSUE THREAD

**Issue by jesusdpa1** [flatironinstitute/CaImAn#860]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux
 2. Python version (3.x): 
 3.7
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Python IDE/ Pycharm
 4. Which of the demo scripts you're using for your analysis (if applicable):
 2p demo
 5. CaImAn version*: 
 latest
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e .
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**
Are there utils tools that allow to reload the data to the caiman structure for easy access to plotting and extracting data? if not, are there any demo files that can be use to go through the hdf5 files to reconstruct the cellmap, cell traces, etc.

**Comment by pgunn** [comment]
Take a look at demo_OnACID_mescoscope.py - it pulls demo data down (that's in hdf5 format) and may give you a start for what you're trying to do.

@j-friedrich do you have any recommendations for visualisation?

**Comment by jesusdpa1** [comment]
Hi Pat, thanks for the idea! 

I went  through the pipeline but couldn't find much information regarding reuploading the data output from caiman. I only saw the uploading of mmap files and hdf5 but I think this were movie files. 

If I go inside of the directory of the results file (hdf5) I see that in the structure I can find the estimates values A, C, etc. Is there a pipeline that shows how to reconstruct these values to their respective cell traces and images?

**Comment by j-friedrich** [comment]
Hi @jesusdpa1, you can load the saved  analysis results using `load_CNMF` or `load_OnlineCNMF`. I outline the usual workflow below.

Run pipeline to analyze data:
```
from caiman.source_extraction.cnmf import cnmf 
n_processes = ...
opts = ...
cnm = cnmf.CNMF(n_processes, params=opts)
cnm = cnm.fit_file()
cnm.save('results.hdf5')
```

Load results:
```
from caiman.source_extraction.cnmf import cnmf 
cnm = cnmf.load_CNMF('results.hdf5')
```

If you used an online method to analyze the data:
```
from caiman.source_extraction.cnmf import online_cnmf
cnm = online_cnmf.load_OnlineCNMF('results.hdf5')
```

**Comment by jesusdpa1** [comment]
Thanks Pat & Johannes! it worked great. closing this issue,
