### ISSUE TITLE
How to improve processing time?

### ISSUE THREAD

**Issue by jesusdpa1** [flatironinstitute/CaImAn#861]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux
 2. Python version (3.x): 
 3.7
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook, 
 4. Which of the demo scripts you're using for your analysis (if applicable):
demo_online_cnmfE.ipynb
 5. CaImAn version*: 
 latest 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e ./conda
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**
Hi, 

I am trying to run the the online cnfme for 1p data for ~40.000 frames. I am running this in a server, and have try the following configurations with multiple time outs:

srun -num-cpu=(16-32-64) -mem=(64-128) time=~300 min -> timed out 

I also tried running the algorithm with a GPU but it seemed that the system didn't had any progress overall. I am making this assumption because I didn't saw the following message as when its run only on CPU:

497358 [online_cnmf.py:fit_online():1213] [45287] Now processing file...

Is there an specific configuration that would improve the processing time?

**Comment by pgunn** [comment]
Hi,
Can you try with a smaller dataset? We should try to figure out whether it's progressing at all or not, and that would help.

**Comment by jesusdpa1** [comment]
Sure! 

**here is the output after 3h using the following configuration complete dataset:**

srun: 32 CPUs - 128

Output:

/home/jesus.penalozaa/.conda/envs/caiman/lib/python3.7/site-packages/numpy/core/_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)
      497358 [online_cnmf.py:fit_online():1213] [45287] Now processing file /blue/shreya.saxena/jesus.penalozaa/AT2_ACC-experiments/AT2_ACC_ang2-saline_inj/1010870/drv_caiman/180121-ACC-Baseline-1-1010870.tiff
/home/jesus.penalozaa/Downloads/CaImAn/caiman/summary_images.py:623: RuntimeWarning: invalid value encountered in sqrt
  sig = np.sqrt(second_moment - first_moment**2)
     2843171 [online_cnmf.py:fit_online():1213] [45287] Now processing file /blue/shreya.saxena/jesus.penalozaa/AT2_ACC-experiments/AT2_ACC_ang2-saline_inj/1010870/drv_caiman/180121-ACC-Saline-Inj-1010870.tiff
/home/jesus.penalozaa/Downloads/CaImAn/caiman/summary_images.py:624: RuntimeWarning: divide by zero encountered in true_divide
  M.data = ((crosscorr - first_moment[row_ind] * first_moment[col_ind]) / (sig[row_ind] * sig[col_ind]) /
/home/jesus.penalozaa/.conda/envs/caiman/lib/python3.7/site-packages/past/utils/__init__.py:95: RuntimeWarning: invalid value encountered in true_divide
  return a / b
     8174816 [online_cnmf.py:fit_online():1213] [45287] Now processing file /blue/shreya.saxena/jesus.penalozaa/AT2_ACC-experiments/AT2_ACC_ang2-saline_inj/1010870/drv_caiman/180121-ACC-Baseline-2-1010870.tiff

**On partial dataset**
dataset = ~6000 frames
fnames=['/path/case_id.tiff']
GPU 

16 CPUs 1 GPU 64Gb

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 3161004368878658389,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 23566610688
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 15900185949198760712
 physical_device_desc: "device: 0, name: Quadro RTX 6000, pci bus id: 0000:1a:00.0, compute capability: 7.5"]

       72230 [movies.py:extract_shifts():371] [97817] Movie average is negative. Removing 1st percentile.
       72265 [movies.py:extract_shifts():389] [97817] Movie average is negative. Removing 1st percentile.
       73163 [movies.py:extract_shifts():371] [97817] Movie average is negative. Removing 1st percentile.
       73198 [movies.py:extract_shifts():389] [97817] Movie average is negative. Removing 1st percentile.
/home/jesus.penalozaa/.conda/envs/caiman/lib/python3.7/site-packages/numpy/core/_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)
      107831 [online_cnmf.py:fit_online():1213] [97817] Now processing file ....tiff
/home/user/Downloads/CaImAn/caiman/summary_images.py:623: RuntimeWarning: invalid value encountered in sqrt
  sig = np.sqrt(second_moment - first_moment**2)

**gets stuck here for several hours**

**Comment by pgunn** [comment]
Does it finish with that smaller dataset?

**Comment by jesusdpa1** [comment]
Not with the GPU config

**Comment by pgunn** [comment]
Does it finish without the GPU? What happens if you do it in GPU mode, with a lower number of processes?

**Comment by jesusdpa1** [comment]
Do you mean less cpus? or is it a configuration in the opts params?

**Comment by pgunn** [comment]
In the code where you set up the multiprocessing, you can add parameters to set the level of parallelism. Changing those settings can be good for debugging.

**Comment by jesusdpa1** [comment]
srun --ntasks=32 --mem=64gb -t 300
**CPU**
[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 2533536870617919368]

**processing time = 22min**
dataset= 1file 6000frames
if 'dview' in locals():
    cm.stop_server(dview=dview)
c, dview, n_processes = cm.cluster.setup_cluster(
    backend='local', n_processes=2, single_thread=False)

**processing time = incomplete**
dataset= 1file 6000frames
if 'dview' in locals():
    cm.stop_server(dview=dview)
c, dview, n_processes = cm.cluster.setup_cluster(
    backend='local', n_processes=16, single_thread=False)

**GPU**
--ntasks=16 --mem=64gb --gpus=1 -t 300
[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 17598559772743362389,
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 10562902464
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 15221143663916768055
 physical_device_desc: "device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:1a:00.0, compute capability: 7.5"]

**processing time = 24min**
dataset= 1file 6000frames
if 'dview' in locals():
    cm.stop_server(dview=dview)
c, dview, n_processes = cm.cluster.setup_cluster(
    backend='local', n_processes=2, single_thread=False) #

**Comment by pgunn** [comment]
Hi,
Can you tell me the results of these runs?

**Comment by jesusdpa1** [comment]
Hi Pat! with the lower number of processes the algorithm manages to finish even with large datasets. It takes around 2 hours to process the 40.000 frames. In terms of the output data, it is really noisy and the cell contour shapes are quite odd compare to the offline processing. I think I am going to need to adjust some of the parameters.

**Comment by jesusdpa1** [comment]
Hi @pgunn just to give an update. The online version of the algorithm was taking to long to run and the output files where really noisy. I jumped back to the offline version reducing the number of processors in the script and diving the process (first running motion correction and later cnmfe in to different slurm sessions). Through this method the pipeline work fine but the processing time still remained high. When checking the CPUs usage throughout one run I notice that the processors are not being use in their max, (probably because I am using the tensorflor-gpu version?) 

The entire pipeline ran for around 4h to process ~40.000 frames. Are there any other methods or tweaks I could do to improve this processing time? 

I also wanted to ask if the final version of the mmap file (memmap__d1...) contains the rest of the files (memmap_0000_d1..., memmap_0001_d1..., etc.). this question is mostly to save memory by deleting the rest of them. 

├── [5.8G]  memmap_0000_d1_400_d2_640_d3_1_order_C_frames_6054_.mmap
├── [ 11G]  memmap_0001_d1_400_d2_640_d3_1_order_C_frames_12053_.mmap
├── [5.8G]  memmap_0002_d1_400_d2_640_d3_1_order_C_frames_6045_.mmap
├── [ 11G]  memmap_0003_d1_400_d2_640_d3_1_order_C_frames_12057_.mmap
├── [ 35G]  memmap__d1_400_d2_640_d3_1_order_C_frames_36209_.mmap

**Comment by pgunn** [comment]
I'm not well-versed in how performance tuning works with GPU code; there's a chance there's a lot of resource contention for the hardware. It might be worth trying to run it in a way where the code cannot access GPUs (or where there are no GPUs); if your slurm cluster lets you do such an allocation consider experiments along those lines (locally we have a separate GPU cluster and use gres to specify a gpu configuration, but your setup may vary). It'd be interesting to know if CPU scaling works out better that way.

I don't have a good feel for what kind of a speedup GPUs give you (I'm guessing motion correction doesn't use it at all).

**Comment by jesusdpa1** [comment]
Hi @pgunn, you were right! 

Using a higher number of CPUs improves the processing time significantly more compared with using the  GPU version at least in our datasets. I will be closing the issue, 

Thank you very much for your help,

**Comment by jesusdpa1** [comment]
Hi @pgunn, just a small update. 

So after running multiple times the code, I would say that the best approach (at least in our HPC) is to:

1. run motion correction without loading the GPU
2. then run the cnmfe using the GPU. 

For some reason when I was running everything with one (only GPU) or the other one (only CPU) the algorithm crashed or took longer periods of time in different points (either motion correction or cnfme). 

Hope this helps others,

**Comment by pgunn** [comment]
That's good to know; I think the common case (at least as we imagine it now) is that a CUDA-capable GPU won't be available, but this may change over the next few years. There's also the possibility that Tensorflow-on-CPUs will become dramatically more efficient in the years to come, to the level where most of this kind of work will best be implemented only in Tensorflow (or one of its competitors). We'll need to keep an eye on developments in this sphere.
