### ISSUE TITLE
Cannot install caiman in windows10

### ISSUE THREAD

**Issue by immj22** [flatironinstitute/CaImAn#864]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 3.7.3
 
 3. Working environment (Python IDE/Jupyter Notebook/other): anaconda3
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 1.8.9 (latest version)
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda-forge

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I followed the package-based process in the website (https://caiman.readthedocs.io/en/master/Installation.html#upgrading-and-source-based-installations). I could do create and activate caiman but my computer cannot finish installing the conda-forge and automatically stopped and poped-up a message failed to install (not exact error message). 

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hi,
What command led you to the part where you say it can't finish installing the conda-forge?

**Comment by immj22** [comment]
Hi! It's done collecting package metadata but it can't finish solving environment.

**Comment by pgunn** [comment]
Hi,
What command were you running that led to that message?

**Comment by immj22** [comment]
I attached the command window as below. My computer has been still running the command since 2 hours ago.
![image](https://user-images.githubusercontent.com/82422846/114754133-148f3f80-9d0d-11eb-84c0-3293e204fd96.png)

**Comment by pgunn** [comment]
Try this instead:
interrupt that
remove the environment:
`conda env remove -n caiman`

Then let's try recreating the environment like this:

`conda create -n caiman -c conda-forge caiman`

That'll make the environment all in one shot, with caiman already present.

**Comment by immj22** [comment]
Thanks for your suggestion however, it's not still working as the same problem I guess.
It's been running almost 1hr.
![image](https://user-images.githubusercontent.com/82422846/114766244-021c0280-9d1b-11eb-9379-a8172e45db93.png)

**Comment by pgunn** [comment]
How much RAM does your system have?

**Comment by immj22** [comment]
My computer has 64GB RAM and now it's eventually installed. I didn't expect it would take so long time like this because I've tried  in my laptop which has 8GB RAM taking less than 1hr. Anyway thanks so much for your help.

**Comment by pgunn** [comment]
If you've been using conda for awhile, doing `conda clean --all` occasionally can help. But generally creating complex environments can be slow. You definitely have enough RAM.

**Comment by ChangliangGuo** [comment]
Hi @immj22,

How are you doing? I got the same issue when I was installing the caiman in windows10. May I know how you figured it out finally? Should I just wait until the installing passes "Solving environment"? As I remember this issue did not happen when I installed caiman in Ubuntu. Thanks so much for that.

**Comment by pgunn** [comment]
@ChangliangGuo How much RAM do you have on your system? Did you try doing a `conda clean --all` first?

**Comment by immj22** [comment]
Hi @ChangliangGuo,

I just followed what @pgunn instructed as above, removed all and re-installed. I just waited for more than 1hr, caiman was eventually installed. I hope you can also solve this problem!
