### ISSUE TITLE
Documentation fixes for `update_temporal_components`

### ISSUE THREAD

**Issue by kabilar** [flatironinstitute/CaImAn#867]
Thank you for maintaining this package.  Noted below are two minor fixes for the documentation of [update_temporal_components](https://caiman.readthedocs.io/en/master/core_functions.html#caiman.source_extraction.cnmf.temporal.update_temporal_components).  (CaImAn 1.8.9 documentation)

1. The input arguments `A` and `b` should refer to the spatial footprints.

2. The output arguments should match the `return` of the [source code](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/source_extraction/cnmf/temporal.py#L244).

**Comment by akatav** [comment]
@kabilar hello, i have a question regarding using this function. Actually, let's say i have the spatial footprints A. I do not have the temporal traces C. Can I use the update_temporal_components() function to estimate C  using A and the original data (movie) matrix ?

**Comment by kabilar** [comment]
Hi @akatav, great question.  Unfortunately, I am not a developer of `CaImAn` so I am not best suited to answer this question.  @pgunn would be able to answer your question.   Their [Gitter message board](https://gitter.im/agiovann/Constrained_NMF?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is quite active.  Sorry I couldn't be of more help.

**Comment by pgunn** [comment]
I'm going to make some small adjustments to have the ordering match, which will partially address the second concern. Will discuss the first concern later.

**Comment by j-friedrich** [comment]
Addressed the 1st concern.
