### ISSUE TITLE
Conda-based install Fails

### ISSUE THREAD

**Issue by james-a-mcmanus** [flatironinstitute/CaImAn#868]
## Details
 1. Operating system (Linux/macOS/Windows): 
- Linux Mint 20 
 2. Python version (3.x): 
 - 3.8.5
 5. CaImAn version*: 
 - 1.8.8
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
- conda

## Issue
- I've tried to install Caiman through conda. I've tried different methods but mainly the problem is on solving the environment.
- the python installed on my system is 3.8.5, but I set up the conda environment with: `conda create -n caiman python=3.7.0`.
- Sometimes the package solving is killed, sometimes it hangs for hours, other times it freezes my computer.
- I'm able to install other packages in different conda environments.

## Example error log
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / Killed
```

Same story on two different computers both running Mint.
Thanks in advance!

**Comment by pgunn** [comment]
Hi,
How much memory do you have on the hosts?

**Comment by james-a-mcmanus** [comment]
Hi, 8gb on one PC, 16gb on the other

**Comment by pgunn** [comment]
My guess is that if you use dmesg to show the kennel log you'll see that you're running out of memory during the package solve. This easily happens with conda, particularly with low RAM systems, particularly if other things are running. 8G can be really tight. 16G should be doable unless you're running other memory hungry things.

**Comment by james-a-mcmanus** [comment]
Ah yes - I can confirm that was the problem on my 8gb machine. I'll try again later today on my 16gb and see if that was the problem - thanks

**Comment by james-a-mcmanus** [comment]
Yes it managed to work with my 16gb computer (used up approximately 80% of the memory available at one time). Is it worth noting this memory requirement in the installation instructions or is it assumed that people will normally doing this sort of analysis on high RAM machines?

**Comment by pgunn** [comment]
Next time I rework the docs I'll talk more about minimal system requirements.
