### ISSUE TITLE
Estimating temporal traces from spatial components

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#869]
Hi
Can i use the ````update_temporal_components()```` function to get the temporal trace matrix ````C```` using only the spatial components ````A```` and ````Yr```` (the 3D movie matrix). 
Can you please provide an example of this ?

**Comment by j-friedrich** [comment]
No, you also need to provide the spatial background `b` as well as initial estimates for the temporal components `C` and `f`. Using `A`, `b` and `Yr` you could get those initial estimates by solving the non-negative least squares problem, e.g. using block-coordinate decent as in [HALS](https://github.com/flatironinstitute/CaImAn/blob/1679463dc06199b600ffef2c577712d65924f532/caiman/source_extraction/cnmf/initialization.py#L1138).

```
def HALS4activity(Yr, A, b, iters=100):
    Ab =  np.c_[A, b]
    U = Ab.T.dot(Yr)
    V = Ab.T.dot(Ab) + np.finfo(Ab.dtype).eps
    Cf = U/V.diagonal()[:,None]
    for _ in range(iters):
        for m in range(len(U)):  # neurons and background
            Cf[m] = np.clip(Cf[m] + (U[m] - V[m].dot(Cf)) / V[m, m], 0, np.inf)
    return Cf
```
