### ISSUE TITLE
Alignment of movies from different sessions before cell detection

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#871]
Hello,

I have upto 6 sessions of movies with varying number of frames of the same brain region. So far, i have used caiman to motion correct and detect cells in each of these 6 sessions separately (using cnm.fit_file(motion_correct=True)), followed by multisession registration. 

I am wondering if it is possible to use caiman (in some way) to motion correct all the 6 sessions together first. After which cell detection can be performed in each of these sessions. My motive in doing this is to improve the cell tracking results (lesser false positives due to better alignment). 

(OR) Would it be enough to simply use the final .mmap files from each session and align the 6 3d arrays to each other before using the CNMF algorithm (cnmf.fit()) individually on the aligned .mmap files. 

It will be extremely helpful to have a discussion on this. 

Thanks.

**Comment by j-friedrich** [comment]
You can simply provide a list of the session filenames as parameter `fnames` to motion correct all sessions together. 

Or you can motion correct each session separately, calculate the shifts between the templates of each session, and align the sessions. The latter can be done by either calculating `total_shifts=in_session_shifts+between_session_shifts` and applying the `total_shifts` to the raw data, or by applying `between_session_shifts` to the separately motion corrected data.

See the attached [notebook](https://gist.github.com/j-friedrich/58faf178d1766e6705e2bb277b3a80fe) where both approaches seem to perform similar after tweaking `max_shifts` and `niter_rig`. Using border_nan='copy' yielded slightly better results than `True` or `min`.
