### ISSUE TITLE
summary_images.py: correlation_pnr function for 4D data

### ISSUE THREAD

**Issue by EOMMINHO** [flatironinstitute/CaImAn#875]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Linux
 
 2. Python version (3.x): 3.8
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Python IDE
 
 4. Which of the demo scripts you're using for your analysis (if applicable): None
 
 5. CaImAn version*: 1.8.9
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): pip install -e .

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

For the function "correlation_pnr" in the file summary_images.py,
"_, d1, d2 = Y.shape" does not work as the dimension does not match. (for 4D data)

- **Copy error log below**
ValueError: too many values to unpack (expected 3)

- **If you're not reporting an error, type your message below**

**Comment by amitakoren** [comment]
Hello, is it possible to share how you managed to solve this in the end?
