### ISSUE TITLE
Detected cells have square shape.How to finetune the cell boundaries?

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#876]
Hello,
I am using caiman on Windows 10 inside anaconda envrionment. 

I am using the method ````manually_refine_components```` to add more spatial components to the cell detection output. Please see below for a sample image. 
![download (2)](https://user-images.githubusercontent.com/721570/118426922-1b8fe000-b707-11eb-8066-913dad65c303.png)
As can be seen in the image, the manually added cells have a square shape. The rest of the cells detected by caiman's cell detection process (using ```` cnm.fit_file() ````) have non convex shapes. 

I'd like to know how to finetune the cell boundaries so that they follow the true cell boundaries more closely (than simply a square or round shape). 

Thanks

**Comment by j-friedrich** [comment]
The second argument of `manually_refine_components` specifies the dimensions of the square used to identify neurons. Increase those values. You can also use the `refit` method after manually adding components. 
```
...
Y = cm.load(fnames)
A,C = cm.source_extraction.cnmf.utilities.manually_refine_components(
    Y.transpose(1,2,0), (7,7), cnm.estimates.A, cnm.estimates.C, Cn)
cnm.estimates.A = scipy.sparse.csc_matrix(A, dtype=np.float32)
cnm.estimates.C = C
cnm2 = cnm.refit(Y)
```
