### ISSUE TITLE
Are neurons assigned with a near  number, near in physical space?

### ISSUE THREAD

**Issue by sofiapuvogel** [flatironinstitute/CaImAn#877]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 
 2. Python version (3.x): 
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

Hello CaIMAN tem, I have a doubt. How do you assign a number to each neuron? I am particularly interested in knowing if neurons that were assigned with a near number, Are they physically near inside the image?
Best regards and thanks a lot,
Sofía

**Comment by pgunn** [comment]
I think that even if they are, you should not count on this; I don't believe stable numbering is part of our documented API and could easily change in future releases.

**Comment by j-friedrich** [comment]
There's no spatial ordering. In the offline version the numbering reflects the size of the local maxima of the summary image used for initialization. In the online version (OnACID) the numbering reflects the time at which the neuron was detected.
