### ISSUE TITLE
Unable to install caiman

### ISSUE THREAD

**Issue by CeciliaVLing** [flatironinstitute/CaImAn#879]
1. Operating system: Linux
 
 2. Python version: 3.7
 
 3. Working environment: cluster
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process: $ conda install caiman -c conda-forge
 
- **Describe the issue that you are experiencing**

     There is no error message, only the process goes on forever. 

              Collecting package metadata: done
              Solving environment: -

**Comment by pgunn** [comment]
Hello,
It's preferable to install caiman into a new environment rather than an existing one; this way conda doesn't need to compromise between the package versions caiman wants versus those needed for conda itself to function. Try this:

```conda create -n caiman -c conda-forge caiman```

Note as well that right now conda can take a lot of RAM (and occasionally a fair bit of time) to solve an environment, and the performance of whatever filesystem you're working on can be a factor. This can come up in cluster configs. Although I'd be surprised if it took longer than 15 minutes except in exceptionally problematic cases.

**Comment by CeciliaVLing** [comment]
It doesn't work. Here below is the message I've got:

  Collecting package metadata (current_repodata.json): done
  Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
  Collecting package metadata (repodata.json): done
  Solving environment: \

Then it just stuck there.

**Comment by CeciliaVLing** [comment]
I can install it on my laptop instead of the cluster using "conda install caiman -c conda-forge" but now I have a new problem: I'm a little confused about how to set up the caimanmanager.py. The "caimanmanager.py install" seems doesn't make any sense and "pip install ." yields an error message: ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Can you be a little more specific or give step-by-step about how to set up the data directory and caimanmanager? I never used anaconda before. 
Thanks

**Comment by pgunn** [comment]
Hi,
You're mixing elements of two different install methods.

If you install it entirely with conda, using the caiman package, do not get the source tree and do not use pip.

If you just use conda to prebuild the environment and use pip, then don't do `conda install`.

Whichever of those two routes you pick, you'll want to do `caimanmanager.py install` afterwards to get a datadir and the demos.

**Comment by CeciliaVLing** [comment]
That's what I tried: I run 'caimanmanager.py install' in the caiman environment, then there is dialog window pops up asking how to open the file. Same thing for 'caimanmanger.py check'. What actually it should do when I run it? Basically I just followed your installation instruction here are the steps:
  conda create -n caiman  
  conda activate caiman
  conda install caiman -c conda-forge

It seemed to be successful and the environment variables were set automatically

     set "MKL_NUM_THREADS="
     set "OPENBLAS_NUM_THREADS="
     set MKL_NUM_THREADS=1
     set OPENBLAS_NUM_THREADS=1

Then I run the 'caimanmanager.py install', a dialog window pops up, whether I open the file or not seemed to make no difference. Once the window is closed, the conda promote goes to a new line but nothing happened. This is the same if I do 'caimanmanager.py check'. 

I'm not sure if I should run the 'caimanmanager.py install' in the 'caiman' environment or elsewhere? Can you be more specific on this part?

Thanks

**Comment by pgunn** [comment]
Oh, right, you're on windows. In that case, make sure you're in the right conda environment. Then you need to say `python` and then the path to caimanmanager.py

The file associations don't usually work right on Windows.

**Comment by CeciliaVLing** [comment]
That works! But what do you mean by "the file associations don't usually work right on Windows"? Will you suggest to use linux instead of windows? I can switch to linux if it is less troublesome.

Thanks

**Comment by pgunn** [comment]
The main difference here is that you'll need to explicitly invoke python on any script that uses Caiman. So long as you're cool doing that (as you just did), you should be fine.

We mainly develop Caiman on Linux or OSX, but Windows is a supported platform; use what makes sense to you.

**Comment by CeciliaVLing** [comment]
Thank you for the information and help.
