### ISSUE TITLE
Spatial components are absent in the first & last z-plane with 3D CNMF

### ISSUE THREAD

**Issue by kushalkolar** [flatironinstitute/CaImAn#880]
**Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 **Ubuntu 20.04 LTS**

 2. Python version (3.x): 
 **3.6 and 3.8 (same issue regardless)**

 3. Working environment (Python IDE/Jupyter Notebook/other):
 **jupyterlab**
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 `CaImAn/demos/notebooks/demo_caiman_cnmf_3D.ipynb`

 5. CaImAn version*: 
 **1.8.4**

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda):
 `pip install -e`

**Describe the issue that you are experiencing**

I notice that with 3D CNMF no components are ever detected in the first and last plane on the z-axis.
The notebook viewer, `cnmf.estimates.nb_view_components_3d` displays the first & last plane as zeroes. This leads me to think that something happens when `Yr` is created which causes the first and last plane to be zeroed?

More information:
- My data contains 5-7 z-planes.
- Changing the `z` component of `gSig` doesn't help, I tried 3, 2, 1, and 0.5.
- Using an odd or even number of z-planes doesn't seem to make a difference either.
- Adding a empty plane of zeros as the first and last plane allows the cells to be detected in the first & last z-plane of the real data.

Is this expected behavior? Are there any downsides to getting around this issue by adding empty planes to flank the entire stack?

Thanks!

**Comment by j-friedrich** [comment]
Fixed in the dev branch. The morphological closing operation lead to empty first and last planes. You can now set the structuring element `se` to e.g. `np.ones((3,3,1), dtype=np.uint8)` to avoid that, see the updated [3D demo](https://github.com/flatironinstitute/CaImAn/blob/dev/demos/notebooks/demo_caiman_cnmf_3D.ipynb)
