### ISSUE TITLE
Inferred spike rates depend on length of image stack

### ISSUE THREAD

**Issue by oregonGCAMP** [flatironinstitute/CaImAn#881]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows
 2. Python version (3.x): 
 3.7
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 N/A
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

Problem:
I noticed that if I take a 1-min long time series and repeat it 4 times to get a 5 
min long one, the deconvolution results are different.

![Five_min_rigmc](https://user-images.githubusercontent.com/40069618/120033591-9b903280-bfb0-11eb-97cc-7ee16aee32bb.jpg)
![One_min_rigmc-1](https://user-images.githubusercontent.com/40069618/120033607-9fbc5000-bfb0-11eb-8172-f2af86b33e10.jpg)
![SIF-graphsAsset-1](https://user-images.githubusercontent.com/40069618/120033613-a34fd700-bfb0-11eb-89bc-65c32aaeb51f.jpg)

**Comment by j-friedrich** [comment]
We forgot to include S in the `estimates.normalize_components()` method. Just fixed it in the dev branch. 
Note that the deconvolution results won't be 100% identical because concatenating the same movie leads to a discontinuity where one movie ends and the next begins which affects the estimates of noise level and auto-regressive parameters.

Minimal example
```
import matplotlib.pyplot as plt
from caiman.paths import caiman_datadir
from caiman.source_extraction.cnmf import cnmf, params

fnames = [caiman_datadir() + '/example_movies/demoMovie.tif']

opts = params.CNMFParams(params_dict={'fnames': fnames, 'only_init': False})
cnm = cnmf.CNMF(1, params=opts)
cnm = cnm.fit_file()

opts5 = params.CNMFParams(params_dict={'fnames': fnames*5, 'only_init': False})
cnm5 = cnmf.CNMF(1, params=opts5)
cnm5 = cnm5.fit_file()

plt.plot(cnm.estimates.S[0])
plt.plot(cnm5.estimates.S[0,:2000])
```

**Comment by oregonGCAMP** [comment]
Hi Johannes,

I included the S in the estimates.normalize_components, but it didn't fix the problem. When I run your example, I get this:

![image](https://user-images.githubusercontent.com/40069618/131722091-d3316349-3c8e-4a3a-9d88-41493b54bd3d.png)

Thanks,

Andrei

**Comment by j-friedrich** [comment]
If you use an updated CaImAn version (1.9.3 or 1.9.4) you get this:
![881](https://user-images.githubusercontent.com/11875432/131738155-cf5db8cd-ceee-4182-8043-5b99b2a26acf.png)

**Comment by oregonGCAMP** [comment]
Using the updated CaImAn, I obtained the same results as you did.

Thanks,
Andrei
