### ISSUE TITLE
Trouble installing caiman using conda

### ISSUE THREAD

**Issue by KangByungwoo** [flatironinstitute/CaImAn#882]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
MacOS 

 2. Python version (3.x): 
3.6 

 3. Working environment (Python IDE/Jupyter Notebook/other):
 N/A 

 4. Which of the demo scripts you're using for your analysis (if applicable):
 N/A  

 5. CaImAn version*: 
 The version that can be obtained by conda as of May 30, 2021

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I have trouble installing caiman using conda. See the error message below.

- **Copy error log below**
(base) Byungwoos-MacBook-Pro-2:~ byungwookang$ conda activate caiman
(caiman) Byungwoos-MacBook-Pro-2:~ byungwookang$ conda install caiman -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): | / failed

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hello,
Please do the following (when not in an environment):
`conda env remove -n caiman`
then
`conda create -n caiman -c conda-forge caiman`

This will remake the caiman environment with no preexisting packages; it's sometimes helpful to give the package solver the greatest latitude in finding a compatible set of versions.

**Comment by KangByungwoo** [comment]
@pgunn Thanks! I think that may not be a cause of the problem, since the problem occurred also when I created the environment for the first time and then install caiman, exactly following your suggested commands. 

I was able to bypass this problem by directly downloading the source. But, my collaborator experienced the exact same issue in Windows as well and it seems like this might be a general issue with conda-forge (see for e.g.  https://github.com/conda/conda/issues/9367).

**Comment by pgunn** [comment]
I'm glad you were able to get it working; we've seen a lot of reports recently of conda's solver having efficiency problems. It's not something that's directly our fault, but we try to help users anyhow as it's a path to getting our software installed.
