### ISSUE TITLE
Index out of bounds in demo_online_cnmfE.ipynb in fit_next()

### ISSUE THREAD

**Issue by fabinjoe** [flatironinstitute/CaImAn#883]
- **The Setup.**
 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 3.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_online_cnmfE.ipynb
 
 5. CaImAn version*: 1.8.9
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda 

- **Describe the issue that you are experiencing**
While trying to run the demo_online_cnmfE.ipynb with an input AVI file of 200 frames, I am seeing the error shown below. Each frame is a TIFF image of 512 x 512 32-bit pixels.

- **Copy error log below**
IndexError                                Traceback (most recent call last)
<ipython-input-12-e303b23db819> in <module>
      1 cnm_online = cnmf.online_cnmf.OnACID(params=online_opts, dview=dview)
----> 2 cnm_online.fit_online()

E:\Anaconda\envs\calciumImaging\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in fit_online(self, **kwargs)
   1268                             frame_cor = frame_cor/self.img_norm
   1269                         # Fit next frame
-> 1270                         self.fit_next(t, frame_cor.reshape(-1, order='F'))
   1271                         # Show
   1272                         if self.params.get('online', 'show_movie'):

E:\Anaconda\envs\calciumImaging\lib\site-packages\caiman\source_extraction\cnmf\online_cnmf.py in fit_next(self, t, frame_in, num_iters_hals)
    434                     AtW=self.estimates.AtW, AtWA=self.estimates.AtWA, iters=num_iters_hals,
    435                     groups=self.estimates.groups, ssub_B=ssub_B,
--> 436                     downscale_matrix=self.estimates.downscale_matrix if ssub_B > 1 else None)
    437             else:
    438                 self.estimates.C_on[:self.M, t], self.estimates.noisyC[:self.M, t] = HALS4activity(

IndexError: index 402 is out of bounds for axis 1 with size 402

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment]
If you're AVI file has only 200 frames the batch version ([demo](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_pipeline_cnmfE.ipynb)) is more appropriate. Online CNMF-E is initialized by running batch CNMF-E on a small initial batch, but even this small batch is usually around 200-500 frames.

If you nevertheless want to try a very small initial batch, the error message is curious. The index t is apparently 402, but your data has only 200 frames. Does caiman load your avi correctly (is `cm.load(filename).shape` indeed `(200, 512, 512)`)? Not sure about 32-bit TIFFs.

**Comment by EricThomson** [comment]
I think this may be a problem with windows/avi files specifically with cnmfe-online algorithm. I hit it tonight while debugging things in that branch of the decision tree. I have a 1000-frame avi and got `IndexError: index 2000 is out of bounds for axis 1 with size 2000` triggered on the same line.

**Comment by EricThomson** [comment]
In the fix for `load_iter()` which is used in online processing algorithms, the Windows avi loader should be working, and this error should be fixed. I no longer run into this error as of this morning in the `dev_load_pims_fallback` branch, which will be merged into `dev` soon (and will be merged into `main` soon probably in the next week or so).
