### ISSUE TITLE
get the original non-denoised temporal traces

### ISSUE THREAD

**Issue by LechenQian** [flatironinstitute/CaImAn#884]
- **If you're not reporting an error, type your message below**
 Hello,

I'm using Python version caiman and find the cnm.estimates.C denoises the temporal traces too much. Since in the hv_view_patches function, the temporal traces with noise and a denoised C are both plotted, I'm wondering if there's an easier way to get or calculate the original non-denoised temporal traces of each spatial component? Thank you and looking forward to your response.

Best,
Selina

**Comment by LechenQian** [comment]
And also, I found values in cnm.estimates.C below zero after I adding cnm.estimates.YrA and cnm.estimates.C together. I tried the method of setting 'bas_nonneg':True in the opts_dict but didn't work. Is it because I'm using the seeded Caiman by feeding it a mask of spatial components? Thank you.

**Comment by j-friedrich** [comment]
Yes, the undenoised temporal traces are obtained as `cnm.estimates.C+cnm.estimates.R`. This sum as well as `cnm.estimates.C` can have negative values. `cnm.estimates.C` includes a baseline, `cnm.estimates.bl`, and `cnm.estimates.C-cnm.estimates.bl[:,None]` will be non-negative. Setting `bas_nonneg` to True constraints `cnm.estimates.bl` to be non-negative.
