### ISSUE TITLE
How to change the location of caiman_data

### ISSUE THREAD

**Issue by KangByungwoo** [flatironinstitute/CaImAn#885]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux

 2. Python version (3.x): 
3.9
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
Sublime text 

 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
Most recent as of today 

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pin install .

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**
I am wondering how I can change the location of caiman_data. The default location upon running caiman manager.py install is /home/user/caiman_data, which is not ideal for me.

**Comment by pgunn** [comment]
Hello,
to do this, you can set the CAIMAN_DATA environment variable to whatever path you prefer. Remember to do so consistently for all future shell sessions where you use caiman, and remember to move your existing data dir (or use caimanmanager to make a new one).
