### ISSUE TITLE
Volpy mask R-CNN bug:  ValueError: None values not supported

### ISSUE THREAD

**Issue by Qixingithub-limlab** [flatironinstitute/CaImAn#887]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux

 2. Python version (3.x): 
 3.9.4

 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Notebook

 4. Which of the demo scripts you're using for your analysis (if applicable):
 demo_pipiline_voltage_imaging.py

 5. CaImAn version*: 
 1.8.9

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I installed Keras by "conda install -c conda-forge keras".
1. ~/anaconda3/envs/caiman/lib/python3.9/site-packages/caiman/source_extraction/volpy/mrcnn/model.py in log2_graph(x)
    344 def log2_graph(x):
    345     """Implementation of Log2. TF doesn't have a native implementation."""
--> 346     return tf.log(x) / tf.log(2.0)
    347 
    348 
    AttributeError: module 'tensorflow' has no attribute 'log'

    I was able to fix this with tf.math.log(x)

2. ValueError: None values not supported

- **Copy error log below**
ValueError                                Traceback (most recent call last)
<ipython-input-7-e095729ed937> in <module>
     11 elif method == 'maskrcnn':                 # Important!! Make sure install keras before using mask rcnn.
     12     weights_path = download_model('mask_rcnn')    # also make sure you have downloaded the new weight. The weight was updated on Dec 1st 2020.
---> 13     ROIs = utils.mrcnn_inference(img=summary_images.transpose([1, 2, 0]), size_range=[5, 22],
     14                                     weights_path=weights_path, display_result=True) # size parameter decides size range of masks to be selected
     15     cm.movie(ROIs).save(fnames[:-5] + 'mrcnn_ROIs.hdf5')

~/anaconda3/envs/caiman/lib/python3.9/site-packages/caiman/source_extraction/volpy/utils.py in mrcnn_inference(img, size_range, weights_path, display_result)
    127     DEVICE = "/cpu:0"  # /cpu:0 or /gpu:0
    128     with tf.device(DEVICE):
--> 129         model = modellib.MaskRCNN(mode="inference", model_dir=model_dir,
    130                                   config=config)
    131     model.load_weights(weights_path, by_name=True)

~/anaconda3/envs/caiman/lib/python3.9/site-packages/caiman/source_extraction/volpy/mrcnn/model.py in __init__(self, mode, config, model_dir)
   1839         self.model_dir = model_dir
   1840         self.set_log_dir()
-> 1841         self.keras_model = self.build(mode=mode, config=config)
   1842 
   1843     def build(self, mode, config):

~/anaconda3/envs/caiman/lib/python3.9/site-packages/caiman/source_extraction/volpy/mrcnn/model.py in build(self, mode, config)
   2045             # output is [batch, num_detections, (y1, x1, y2, x2, class_id, score)] in
   2046             # normalized coordinates
-> 2047             detections = DetectionLayer(config, name="mrcnn_detection")(
   2048                 [rpn_rois, mrcnn_class, mrcnn_bbox, input_image_meta])
   2049 

~/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    949     # >> model = tf.keras.Model(inputs, outputs)
    950     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
--> 951       return self._functional_construction_call(inputs, args, kwargs,
    952                                                 input_list)
    953 

~/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1088           layer=self, inputs=inputs, build_graph=True, training=training_value):
   1089         # Check input assumptions set after layer building, e.g. input shape.
-> 1090         outputs = self._keras_tensor_symbolic_call(
   1091             inputs, input_masks, args, kwargs)
   1092 

~/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py in _keras_tensor_symbolic_call(self, inputs, input_masks, args, kwargs)
    820       return nest.map_structure(keras_tensor.KerasTensor, output_signature)
    821     else:
--> 822       return self._infer_output_signature(inputs, args, kwargs, input_masks)
    823 
    824   def _infer_output_signature(self, inputs, args, kwargs, input_masks):

~/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py in _infer_output_signature(self, inputs, args, kwargs, input_masks)
    861           # TODO(kaftan): do we maybe_build here, or have we already done it?
    862           self._maybe_build(inputs)
--> 863           outputs = call_fn(inputs, *args, **kwargs)
    864 
    865         self._handle_activity_regularization(inputs, outputs)

~/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    668       except Exception as e:  # pylint:disable=broad-except
    669         if hasattr(e, 'ag_error_metadata'):
--> 670           raise e.ag_error_metadata.to_exception(e)
    671         else:
    672           raise

ValueError: in user code:

    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/caiman/source_extraction/volpy/mrcnn/model.py:815 call  *
        detections_batch = utils.batch_slice(
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/caiman/source_extraction/volpy/mrcnn/utils.py:823 batch_slice  *
        output_slice = graph_fn(*inputs_slice)
    /tmp/tmpbzi6qbdj.py:17 <lambda>  **
        detections_batch = ag__.converted_call(ag__.ld(utils).batch_slice, ([ag__.ld(rois), ag__.ld(mrcnn_class), ag__.ld(mrcnn_bbox), ag__.ld(window)], ag__.autograph_artifact((lambda x, y, w, z: ag__.converted_call(ag__.ld(refine_detections_graph), (ag__.ld(x), ag__.ld(y), ag__.ld(w), ag__.ld(z), ag__.ld(self).config), None, fscope))), ag__.ld(self).config.IMAGES_PER_GPU), None, fscope)
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/caiman/source_extraction/volpy/mrcnn/model.py:707 refine_detections_graph  **
        indices = tf.stack([tf.range(probs.shape[0]), class_ids], axis=1)
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:1856 range
        limit = ops.convert_to_tensor(limit, dtype=dtype, name="limit")
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:1540 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py:339 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py:264 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py:281 _constant_impl
        tensor_util.make_tensor_proto(
    /ems/elsc-labs/adam-y/qixin.yang/anaconda3/envs/caiman/lib/python3.9/site-packages/tensorflow/python/framework/tensor_util.py:445 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.

- **If you're not reporting an error, type your message below**

**Comment by caichangjia** [comment]
Hi, the current mask rcnn in VolPy is only compatible with tensorflow1. Would you please check your tensorflow and keras version. Tensorflow 1.15.1, keras 2.2.4, h5py 2.9.0 works.

**Comment by Qixingithub-limlab** [comment]
Thank you, it works now.

**Comment by cgaletzka** [comment]
Hi, I am receiving exactly the same error as the op ("ValueError: None values not supported"). I have tried installing Tensorflow=1.15.1 but it's not compatible with the python version in the caiman environment. Could you please let me know how to install the necessary versions of Tensorflow, Keras and h5py?

Operating system (Linux/macOS/Windows):
Windows

Python version (3.x):
3.9.4

Working environment (Python IDE/Jupyter Notebook/other):
spyder

Which of the demo scripts you're using for your analysis (if applicable):
demo_pipiline_voltage_imaging.py

CaImAn version*:
1.8.9

CaImAn installation process (pip install ./pip install -e ./conda):
conda
