### ISSUE TITLE
contour plots

### ISSUE THREAD

**Issue by SophiePinder** [flatironinstitute/CaImAn#888]
Hi, 

Can anyone tell me what's the difference between the white circles and the black circles in the contour plots, like the below.

Thanks!

Sophie 

![bokeh_plot(4)](https://user-images.githubusercontent.com/60217109/122571049-3a55ff00-d044-11eb-818e-938273a22f40.gif)

**Comment by SophiePinder** [comment]
Also I would like create a contour plot showing a group of selected cells with the cells corresponding number

how do I do this?

**Comment by caichangjia** [comment]
White is the contour of the neuron. Black is the center of the mask. 
There is an argument named idx, you can plot selected cells. Eg: cnm.estimates.plot_contours_nb(img=Cn, idx=[0,3, 5, 10])

**Comment by SophiePinder** [comment]
@caichangjia thank you!
do you know how to add more than one components to the below?

![index(2)](https://user-images.githubusercontent.com/60217109/125495476-cd318dc6-567e-4010-9fcb-9d26e5f8816f.jpg)

I use this code

plt.figure(); plt.imshow(np.reshape(cnm.estimates.A[:,cnm.estimates.idx_components[60]].toarray(), dims, order='F'))

**Comment by j-friedrich** [comment]
You can use `cnm.estimates.plot_contours` or your code modified to show 2 components would be
`plt.figure(); plt.imshow(np.reshape(cnm.estimates.A[:,cnm.estimates.idx_components[[1,6]]].max(1).toarray(), dims, order='F'))`
