### ISSUE TITLE
cnm2.estimates.evaluate_components(images, cnm2.params, dview = dview)

### ISSUE THREAD

**Issue by sanketgarg2000** [flatironinstitute/CaImAn#889]
Hi, 
I have been working on Jupyter Notebooks on Windows 10 and trying to run the various steps of the CaImAn procedure. 
I have been able to run the CNMF algorithm. However, I am unable to run the evaluate components part. 

Whenever I run the following:
**cnm2.estimates.evaluate_components(images, cnm2.params, dview = dview)**
I get:
FileNotFoundError: File for requested model C:\Users\sanke\caiman_data\model\cnn_model not found

Can you please help me with this issue.

**Comment by pgunn** [comment]
Hello,
When you did the install, did you do a `caimanmanager.py install` (or possibly on windows, you needed to state python first and give a full path to caimanmanager.py)? It's necessary to get all the datafiles.

**Comment by sanketgarg2000** [comment]
Hi, 
I installed CaImAn about 2 weeks back. I had installed it using caimanmanager.py. 
However, I noticed that the above cnn model files are present in the caiman folder.
C;\Users\sanke\caiman\model. So I copy-pasted the model folder into a caiman_data folder and it worked.

**Comment by pgunn** [comment]
caimanmanager should have done that for you; I'm surprised that you had a caiman_data folder that didn't have the model subdirectory.

**Comment by sanketgarg2000** [comment]
I had created the caiman_data folder manually.
Is there any method of correcting my installation procedure?

**Comment by pgunn** [comment]
remove it and go back through the `caimanmanager.py install` process.

**Comment by j-friedrich** [comment]
I assume that issue is solved, thus closing it
