### ISSUE TITLE
problems installing caimanmanager on windows 10

### ISSUE THREAD

**Issue by LW1989** [flatironinstitute/CaImAn#890]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 

Windows 10
 
 2. Python version (3.x): 

3.7.10
 
 3. Working environment (Python IDE/Jupyter Notebook/other):

Anaconda
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 

1.8.9
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

conda-forge

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

I have problems installing caimanmanager. It shows the following error when I try to use "caimanmanager.py install":

Traceback (most recent call last):
  File "C:\Users\Lutz\anaconda3\envs\caiman_2\bin\caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
ModuleNotFoundError: No module named 'caiman'

I found some already solved issues and tried some of it but untill now it does not work.

**Comment by pgunn** [comment]
Hello,
To run caimanmanager you must be outside the source directory for caiman. This is because of how the python search path interacts with python modules that have a compile phase.

**Comment by LW1989** [comment]
Ok, after trying a couple of times again and using "python [path to caimanmanager.py] install" within the anaconda eviroment instead of "caimanmanager.py install", it finally worked. Thank you
