### ISSUE TITLE
Problems installing CaImAn

### ISSUE THREAD

**Issue by franjmt** [flatironinstitute/CaImAn#891]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows):  Linux
 
 2. Python version (3.x): 3.9.5
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter
 
 4. Which of the demo scripts you're using for your analysis (if applicable): 
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): pip install -e . 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Installation problems. I can't execute the "pip install -e ."

- **Copy error log below**

ERROR: Command errored out with exit status 1:
     command: /home/fmartinezt/miniconda3/envs/caiman/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/fmartinezt/CaImAn/setup.py'"'"'; __file__='"'"'/home/fmartinezt/CaImAn/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/fmartinezt/CaImAn/
    Complete output (11 lines):
    running develop
    running egg_info
    writing caiman.egg-info/PKG-INFO
    writing dependency_links to caiman.egg-info/dependency_links.txt
    writing top-level names to caiman.egg-info/top_level.txt
    reading manifest file 'caiman.egg-info/SOURCES.txt'
    writing manifest file 'caiman.egg-info/SOURCES.txt'
    running build_ext
    building 'caiman.source_extraction.cnmf.oasis' extension
    gcc -pthread -B /home/fmartinezt/miniconda3/envs/caiman/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/fmartinezt/miniconda3/envs/caiman/include -fPIC -O2 -isystem /home/fmartinezt/miniconda3/envs/caiman/include -fPIC -I/home/fmartinezt/miniconda3/envs/caiman/lib/python3.9/site-packages/numpy/core/include -I/home/fmartinezt/miniconda3/envs/caiman/include/python3.9 -c caiman/source_extraction/cnmf/oasis.cpp -o build/temp.linux-x86_64-3.9/caiman/source_extraction/cnmf/oasis.o
    error: command 'gcc' failed: No such file or directory
 

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hello,
You need to have a compiler (ideally gcc) if you want to build Caiman from source. If you don't need to build caiman from source, remove your source tree and install caiman using the binary conda packages. If you're sure you need to build from source (we can talk about this if you like), install gcc and redo the steps.

Cheers,
Pat

**Comment by franjmt** [comment]
OK.  I am doing that instead.
Thank you
