### ISSUE TITLE
register_multisession not accepting spatial data

### ISSUE THREAD

**Issue by lizflem** [flatironinstitute/CaImAn#895]
- **Tell us a bit about your setup**: 
 1. Operating system: Windows 10 Pro
 
 2. Python version: 3.8.5
 
 3. Working environment: Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): modified Multisession Registration
 
 5. CaImAn version*: 1.8.8
 
 6. CaImAn installation process: `pip install .`

- **Describe the issue that you are experiencing**
Hello.  I have been successfully using Caiman batch processing for my 2p data, and now I am trying out your multisession registration function.  I am supplying spatial data for each session using the following code:

            with h5py.File('/data1.hdf5', 'r') as hdf:
                    A1a = hdf.get('/estimates/A')
                    A1 = csc_matrix((A1a.get('data'), A1a.get('indices'), A1a.get('indptr')))

            with h5py.File('/data2.hdf5', 'r') as hdf:
                    A2a = hdf.get('/estimates/A')
                    A2 = csc_matrix((A2a.get('data'), A2a.get('indices'), A2a.get('indptr')))

            spatial = [A1, A2]

I have also tried it this way, with cnm1 and cnm2 being output from different sessions:        

             spatial = [cnm1.estimates.A, cnm2.estimates.A]

Both ways, I receive the following error:
![image](https://user-images.githubusercontent.com/7605300/125396421-86ae0980-e37a-11eb-853a-3ab83fa2e76d.png)

I'm not great with python, so I may be making an obvious mistake.  Either way, any help would be greatly appreciated!

**Comment by pgunn** [comment]
After you do that import, can you tell me what the type is for A1 and A2?

**Comment by lizflem** [comment]
![image](https://user-images.githubusercontent.com/7605300/125648748-0b217415-159f-4a16-a0bc-67c26dc2ff83.png)
![image](https://user-images.githubusercontent.com/7605300/125648898-031eff31-604b-428e-a210-579a80ea4ce5.png)

**Comment by pgunn** [comment]
Could you just evaluate it outside of type()  ? That gives extra information that may be helpful.

**Comment by lizflem** [comment]
I'm sorry - would you show me an example of what you mean?

**Comment by pgunn** [comment]
Just evaluate A1. Put "A1" (no quotes) in a cell and run the cell.

**Comment by lizflem** [comment]
Ah.  Thank you.
![image](https://user-images.githubusercontent.com/7605300/125653757-234bc983-7325-41ff-80a9-d0d92f6d3dec.png)

**Comment by j-friedrich** [comment]
@lizflem The argument `dims` that you pass to function `register_multisession` has to be a tuple, not a list.

If you run the dem notebook you see that this works
`spatial_union, assignments, matchings = register_multisession(A=spatial, dims=tuple(dims), templates=templates)`
while this fails
`spatial_union, assignments, matchings = register_multisession(A=spatial, dims=list(dims), templates=templates)`

**Comment by lizflem** [comment]
I figured it was something silly like that that I wasn't seeing.  Thank you very much!!!  : )
