### ISSUE TITLE
Always getting same number of components when running multiple files

### ISSUE THREAD

**Issue by marielle-imba** [flatironinstitute/CaImAn#897]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.
Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting dview=None.
If you need to upgrade CaImAn follow the instructions given in the documentation.
•	Tell us a bit about your setup:
1.	Operating system (Linux/macOS/Windows): windows10
2.	Python version (3.x): 3.8.5
3.	Working environment (Python IDE/Jupyter Notebook/other): Jupyter notebook
4.	Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline_cnmfE
5.	CaImAn version*: 1.8.7
6.	CaImAn installation process (pip install ./pip install -e ./conda): conda-forge
*You can get the CaImAn version by creating a params object and then typing params.data['caiman_version']. If the field doesn't exist, type N/A and consider upgrading)
•	Describe the issue that you are experiencing
Hello, I'm trying to adapt caiman to extract and map back Calcium transients.  Since my recordings are 5 mins long and larger that 4 GB, I split the video into smaller tif files that I am trying to run with the pipeline. I was wondering if someone could help me adapt the code of the CNMF E pipeline to allow processing of multiple videos. I have tried adapting the code I got from this reported issue: How to run multiple tif files of the same session · Issue #866 · flatironinstitute/CaImAn (github.com) 
•	The pipeline works for one video at a time, but when I run multiple files by adapting fnames, I end up with 30 neurons regardless of the video I run and the inclusion/exclusion parameters I set. The total number of components is always 30.. even though when I run a single file it can be up to 200 components.
•	This is what I ran: 
fnames = ['GCaMP1.tif', 'GCaMP2.tif','GCaMP3.tif', 'GCamP4.tif', 'GCaMP5.tif']  # filename to be processed
fnames = [download_demo(name) for name in fnames] 
params_dict = {'fnames': fnames}

and later for CNMF

opts = params.CNMFParams(params_dict=params_dict)
cnm = cnmf.CNMF(n_processes=5, dview=dview, Ain=Ain, params=opts)
cnm = cnm.fit_file()

Thank you in advance!

**Comment by j-friedrich** [comment]
You have to set parameter K to a different value than the default 30, usually `None` if you want the number of component to be determined via the thresholds `min_corr` and `min_pnr`. Your `params_dict` should be similar to the one in the [demo](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_pipeline_cnmfE.ipynb) section "Parameter setting for CNMF-E". Once you create the CNMF object please make sure that `cnm.params.init['K']` is not 30.
