### ISSUE TITLE
Use PIMS for image loading

### ISSUE THREAD

**Issue by outlace** [flatironinstitute/CaImAn#91]
Enhancement

See < https://pypi.python.org/pypi/PIMS >

PIMS can load many video/image sequence formats into a consistent data structure.

**Comment by agiovann** [comment]
Can it load portions of th einput files without loading into menmory?

**Comment by outlace** [comment]
Yes, I believe so. From the docs:

> Videos loaded by pims (FramesSequence objects) are like lists of numpy arrays. Unlike Python lists of arrays they are "lazy", they only load the data from the harddrive when it is necessary.

and

> By subclassing FramesSequence, you get PIMS's lazy-loading and slicing behavior for free. You have to provide:
> 
> a method for reading a single frame into a numpy array
> a method for knowing the length of the sequence
> properties giving the shape and the numpy data type of each frame

So it's really flexible. It uses tifffile library under the hood for loading tif's which is what you're using already. If you want to extend it to be able to load mmap files, just need to implement a new class with the aforementioned properties and subclass FramesSequence.

**Comment by agiovann** [comment]
The proof would be trying to perform the full sum of a movie larger than
RAM memory using np.sum(). Memmap can do it. I doubt pims can do that.

**Comment by epnev** [comment]
I'm marking this issue as resolved. Feel free to re-open if you think PIMS can do out-of-core computations in addition to lazy loading.
