### ISSUE TITLE
pynwb 2.0.0 creates troubles

### ISSUE THREAD

**Issue by agiovann** [flatironinstitute/CaImAn#910]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
MAC 
 2. Python version (3.x): 
 3.7
 3. Working environment (Python IDE/Jupyter Notebook/other):
Spyder 
 5. CaImAn version*: 
  Spyder 1.9.3
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
Indeoendent

- **Describe the issue that you are experiencing**
NWB demo fails because of an update to pynwb. Need to updated a few files.

**Comment by EricThomson** [comment]
@pgunn is this still a problem or are we now up to date with nwb 2?

**Comment by pgunn** [comment]
We're good now
