### ISSUE TITLE
index 7 is out of bounds for axis 0 with size 7

### ISSUE THREAD

**Issue by Mtkostecki** [flatironinstitute/CaImAn#912]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): windows
 
 2. Python version (3.x): 3.7.10
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter 
 
 4. Which of the demo scripts you're using for your analysis (if applicable): https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_pipeline_cnmfE.ipynb
 
 5. CaImAn version*:  1.9.1
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
During running cnmf on motion corrected file I have error as below.

- **Copy error log below**

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\mkostecki\anaconda3\envs\caiman\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\mkostecki\anaconda3\envs\caiman\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\mkostecki\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\map_reduce.py", line 137, in cnmf_patches
    cnm = cnm.fit(images)
  File "C:\Users\mkostecki\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 507, in fit
    self.initialize(Y)
  File "C:\Users\mkostecki\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 968, in initialize
    **self.params.get_group('init'))
  File "C:\Users\mkostecki\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\initialization.py", line 354, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter, seed_method=seed_method)
  File "C:\Users\mkostecki\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\initialization.py", line 1264, in greedyROI_corr
    dview=None, dims=(d1, d2), **options['spatial_params'])
  File "C:\Users\mkostecki\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\spatial.py", line 240, in update_spatial_components
    parallel_result = list(map(regression_ipyparallel, pixel_groups))
  File "C:\Users\mkostecki\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\spatial.py", line 392, in regression_ipyparallel
    c = C[idxs_C[idx_px_from_0], :]
IndexError: index 7 is out of bounds for axis 0 with size 7
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
C:\Users\MKOSTE~1\AppData\Local\Temp/ipykernel_27344/2644938278.py in <module>
     66 
     67     cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, Ain=Ain, params=opts)
---> 68     cnm.fit(images)
     69 
     70     #%% COMPONENT EVALUATION

~\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
    605                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    606                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 607                     indices=indices)
    608 
    609             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~\anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    247     if dview is not None:
    248         if 'multiprocessing' in str(type(dview)):
--> 249             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    250         else:
    251             try:

~\anaconda3\envs\caiman\lib\multiprocessing\pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

IndexError: index 7 is out of bounds for axis 0 with size 7

- **If you're not reporting an error, type your message below**

**Comment by j-friedrich** [comment]
@Mtkostecki just staring at the code I can't see when this error would occur. Could you share a minimal example script and data where that happens? Then I could try to track it down.

**Comment by phildong** [comment]
I believe I'm hitting the same error. I'm happy to share the data and notebook that I'm working on but they are quite large. I'm wondering what's the best way to share the data?

**Comment by Mtkostecki** [comment]
Hi,

Just today I have solved the problem, I did two things: I have processed
the data in a whole chunk, without dividing it, and - what seems more
important - I have cropped the video so that I have no black background
from outside of the lens.

**Comment by j-friedrich** [comment]
Finally tracked down and fixed in dev.
