### ISSUE TITLE
Repository contains large, binary, files

### ISSUE THREAD

**Issue by orpinchasov** [flatironinstitute/CaImAn#916]
The repository is quite large (689MB), resulting in longer wait times for operations, slow cloning, and unnecessary disk usage (this propagates down the pipeline, for example, into the resulting docker image).
Plus, it contains some large binary files (in directories `model` and `example_movies` for example), which are not recommeded in a repository (diff/merge problems, not necessarily compressable), and which add extra size to the repository.

Taking out the large files to a separate location (git LFS or similar) would help the issue. Then, a bigger problem is removing them from history, which is essential, otherwise the data stays. It's difficult but definitely not impossible.

If you agree, I can perform both and open a PR.

**Comment by pgunn** [comment]
Hello,
This has been an issue for awhile; I've tried to control repository growth and there's a mechanism to retrieve files from external storage. The current repo size is a reasonable compromise between:
- having things in version control
- repo size
- having the pip/conda packages be complete-in-themselves without requiring phoning home or extra downloads
- difficulty in fixing it

The third concern, complete-in-itself, is why I haven't tried reducing this. It's nice that doing a `conda create -n caiman -c conda-forge caiman` gets you everything you need, in one go, and if you then hop on an airplane you won't find a sad surprise later that not everything is there. It's also nice for CI.

As you note, removing them from history is doable but troublesome - I am wary of rewriting git history to do so (although I've done that kind of thing before). If I were convinced it's the right thing to do, I could get through it.

As of right now, I'm not inclined to think of 700M as being large for purposes of infrastructure. I understand that recent versions of git have partial and shallow clones; you may be able to use some combination of those to reduce size. Alternatively, you could use the conda packages (which are still big, but if you're making docker images it may be a shorter pipeline).

Happy to chat further about this if you like.

**Comment by orpinchasov** [comment]
I understand your points and reasoning.

Before talking about them directly let me also point some other things that I've checked:
* GitHub's soft limit for repository size is 1GB, and soft limit for files is 50MB. I think that getting to around 70% of that limit shows that it's now the time to start reducing the size, or at least prevent additional growth.
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github
* I've looked at NumPy and DeepLabCut for some reference for implementations and file sizes. NumPy weighs 135MiB, DeepLabCut 233MiB. Most of the size comes from the .git folder.
* CaImAn's .git folder weighs 531MiB. Which means that just clearing up some history would significantly reduce the repository's size.

I think that the requirement for having everything available even if you go on a plane is a little strict, but I see that anyway that's not the majority of storage taken. I don't think that having video files in a repository is a good habit in general but here removing them won't make too big of a difference.

In any case, I will perform some changes in cleanups in my lab's fork of the project. I'll let you have a look in PRs, and we can discuss specifics at that time.

**Comment by orpinchasov** [comment]
Understood. I'll leave it to you to close this issue.

As I wrote above, I'll share any changes I'm doing using PRs, and we can discuss further.
(Though I think that the specific change of clearing the history is not shareable in that way).
Thanks

**Comment by EricThomson** [comment]
Useful discussion, but so suggesting we close b/c inactive unless there are objections?

**Comment by medigate-orp** [comment]
Can close. Might be addressed in other PRs. Thank you

**Comment by EricThomson** [comment]
Closing discussion, please let me know if I should reopen.
