### ISSUE TITLE
How to skip motion correction to save time

### ISSUE THREAD

**Issue by jorareshuaiwang** [flatironinstitute/CaImAn#917]
- **If you're not reporting an error, type your message below**

I got the CaImAn working well. Thanks for making this package! 

Since my videos do not have much motion during the recording, how could I skip the motion correction sessions and directly proceed to component extraction? The cnm.fit function seems to require a mmap file to run, which is the output from motion correction.

Best,
Shuai

**Comment by j-friedrich** [comment]
You can use the function `caiman.save_memmap` to save your movie data as mmap file. If you use the `fit_file` method of the `CNMF` object you can set the argument  `motion_correct=False`, which is actually the default.

**Comment by jorareshuaiwang** [comment]
It works. Thanks so much!
