### ISSUE TITLE
Install problems on Ubuntu

### ISSUE THREAD

**Issue by smbaca** [flatironinstitute/CaImAn#922]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 
 2. Python version (3.x): 
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**
Processing /home/serapio/Desktop/mesmer/CaImAn
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Building wheels for collected packages: caiman
  Building wheel for caiman (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/serapio/Desktop/mesmer/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2qj5oqsr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2qj5oqsr/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-c1o3pq26
       cwd: /tmp/pip-req-build-2qj5oqsr/
  Complete output (105 lines):
  running bdist_wheel
  running build
  running build_py
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/caiman
  copying caiman/paths.py -> build/lib.linux-x86_64-3.6/caiman
  copying caiman/__init__.py -> build/lib.linux-x86_64-3.6/caiman
  copying caiman/summary_images.py -> build/lib.linux-x86_64-3.6/caiman
  copying caiman/cluster.py -> build/lib.linux-x86_64-3.6/caiman
  copying caiman/motion_correction.py -> build/lib.linux-x86_64-3.6/caiman
  copying caiman/mmapping.py -> build/lib.linux-x86_64-3.6/caiman
  copying caiman/components_evaluation.py -> build/lib.linux-x86_64-3.6/caiman
  creating build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/__init__.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_tensorflow.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_pre_processing.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_demo.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_onacid.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_temporal.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/comparison_humans.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_deconvolution.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_memmapping.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/comparison_general.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/comparison_humans_online.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_movies.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_import.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_spatial.py -> build/lib.linux-x86_64-3.6/caiman/tests
  copying caiman/tests/test_toydata.py -> build/lib.linux-x86_64-3.6/caiman/tests
  creating build/lib.linux-x86_64-3.6/caiman/utils
  copying caiman/utils/__init__.py -> build/lib.linux-x86_64-3.6/caiman/utils
  copying caiman/utils/image_preprocessing_keras.py -> build/lib.linux-x86_64-3.6/caiman/utils
  copying caiman/utils/nn_models.py -> build/lib.linux-x86_64-3.6/caiman/utils
  copying caiman/utils/utils.py -> build/lib.linux-x86_64-3.6/caiman/utils
  copying caiman/utils/visualization.py -> build/lib.linux-x86_64-3.6/caiman/utils
  copying caiman/utils/unused.py -> build/lib.linux-x86_64-3.6/caiman/utils
  copying caiman/utils/stats.py -> build/lib.linux-x86_64-3.6/caiman/utils
  copying caiman/utils/labelling.py -> build/lib.linux-x86_64-3.6/caiman/utils
  creating build/lib.linux-x86_64-3.6/caiman/behavior
  copying caiman/behavior/__init__.py -> build/lib.linux-x86_64-3.6/caiman/behavior
  copying caiman/behavior/behavior.py -> build/lib.linux-x86_64-3.6/caiman/behavior
  creating build/lib.linux-x86_64-3.6/caiman/external
  copying caiman/external/__init__.py -> build/lib.linux-x86_64-3.6/caiman/external
  copying caiman/external/cell_magic_wand.py -> build/lib.linux-x86_64-3.6/caiman/external
  creating build/lib.linux-x86_64-3.6/caiman/source_extraction
  copying caiman/source_extraction/__init__.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction
  creating build/lib.linux-x86_64-3.6/caiman/base
  copying caiman/base/__init__.py -> build/lib.linux-x86_64-3.6/caiman/base
  copying caiman/base/rois.py -> build/lib.linux-x86_64-3.6/caiman/base
  copying caiman/base/timeseries.py -> build/lib.linux-x86_64-3.6/caiman/base
  copying caiman/base/traces.py -> build/lib.linux-x86_64-3.6/caiman/base
  copying caiman/base/movies.py -> build/lib.linux-x86_64-3.6/caiman/base
  creating build/lib.linux-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/__init__.py -> build/lib.linux-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/create_gt.py -> build/lib.linux-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/comparison.py -> build/lib.linux-x86_64-3.6/caiman/tests/comparison
  copying caiman/tests/comparison/regen_main_gt.py -> build/lib.linux-x86_64-3.6/caiman/tests/comparison
  creating build/lib.linux-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/__init__.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/plotting.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/estimation.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/measures.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/gat.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/regions.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/stats.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
  copying caiman/external/houghvst/demo_VST.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
  creating build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/__init__.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/params.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/merging.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/utilities.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/initialization.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/temporal.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/map_reduce.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/spatial.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/online_cnmf.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/deconvolution.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/pre_processing.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/cnmf_optional_outputs.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/cnmf.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  copying caiman/source_extraction/cnmf/estimates.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
  creating build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
  copying caiman/source_extraction/volpy/__init__.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
  copying caiman/source_extraction/volpy/utils.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
  copying caiman/source_extraction/volpy/volpy.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
  copying caiman/source_extraction/volpy/volpy_gui.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
  copying caiman/source_extraction/volpy/atm.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
  copying caiman/source_extraction/volpy/spikepursuit.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
  copying caiman/source_extraction/volpy/volparams.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
  creating build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
  copying caiman/source_extraction/volpy/mrcnn/__init__.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
  copying caiman/source_extraction/volpy/mrcnn/utils.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
  copying caiman/source_extraction/volpy/mrcnn/visualize.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
  copying caiman/source_extraction/volpy/mrcnn/neurons.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
  copying caiman/source_extraction/volpy/mrcnn/model.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
  copying caiman/source_extraction/volpy/mrcnn/config.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
  running build_ext
  building 'caiman.source_extraction.cnmf.oasis' extension
  /opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -g -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -I/home/serapio/Desktop/mesmer/lib/python3.6/site-packages/numpy/core/include -I/home/serapio/Desktop/mesmer/include -I/usr/include/python3.6m -c caiman/source_extraction/cnmf/oasis.cpp -o build/temp.linux-x86_64-3.6/caiman/source_extraction/cnmf/oasis.o
  In file included from /usr/include/python3.6m/Python.h:8:0,
                   from caiman/source_extraction/cnmf/oasis.cpp:26:
  /usr/include/python3.6m/pyconfig.h:3:12: fatal error: x86_64-linux-gnu/python3.6m/pyconfig.h: No such file or directory
   #  include <x86_64-linux-gnu/python3.6m/pyconfig.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for caiman
  Running setup.py clean for caiman
Failed to build caiman
Installing collected packages: caiman
    Running setup.py install for caiman ... error
    ERROR: Command errored out with exit status 1:
     command: /home/serapio/Desktop/mesmer/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2qj5oqsr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2qj5oqsr/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qgbokyy_/install-record.txt --single-version-externally-managed --compile --install-headers /home/serapio/Desktop/mesmer/include/site/python3.6/caiman
         cwd: /tmp/pip-req-build-2qj5oqsr/
    Complete output (110 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/caiman
    copying caiman/paths.py -> build/lib.linux-x86_64-3.6/caiman
    copying caiman/__init__.py -> build/lib.linux-x86_64-3.6/caiman
    copying caiman/summary_images.py -> build/lib.linux-x86_64-3.6/caiman
    copying caiman/cluster.py -> build/lib.linux-x86_64-3.6/caiman
    copying caiman/motion_correction.py -> build/lib.linux-x86_64-3.6/caiman
    copying caiman/mmapping.py -> build/lib.linux-x86_64-3.6/caiman
    copying caiman/components_evaluation.py -> build/lib.linux-x86_64-3.6/caiman
    creating build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/__init__.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_tensorflow.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_pre_processing.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_demo.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_onacid.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_temporal.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/comparison_humans.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_deconvolution.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_memmapping.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/comparison_general.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/comparison_humans_online.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_movies.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_import.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_spatial.py -> build/lib.linux-x86_64-3.6/caiman/tests
    copying caiman/tests/test_toydata.py -> build/lib.linux-x86_64-3.6/caiman/tests
    creating build/lib.linux-x86_64-3.6/caiman/utils
    copying caiman/utils/__init__.py -> build/lib.linux-x86_64-3.6/caiman/utils
    copying caiman/utils/image_preprocessing_keras.py -> build/lib.linux-x86_64-3.6/caiman/utils
    copying caiman/utils/nn_models.py -> build/lib.linux-x86_64-3.6/caiman/utils
    copying caiman/utils/utils.py -> build/lib.linux-x86_64-3.6/caiman/utils
    copying caiman/utils/visualization.py -> build/lib.linux-x86_64-3.6/caiman/utils
    copying caiman/utils/unused.py -> build/lib.linux-x86_64-3.6/caiman/utils
    copying caiman/utils/stats.py -> build/lib.linux-x86_64-3.6/caiman/utils
    copying caiman/utils/labelling.py -> build/lib.linux-x86_64-3.6/caiman/utils
    creating build/lib.linux-x86_64-3.6/caiman/behavior
    copying caiman/behavior/__init__.py -> build/lib.linux-x86_64-3.6/caiman/behavior
    copying caiman/behavior/behavior.py -> build/lib.linux-x86_64-3.6/caiman/behavior
    creating build/lib.linux-x86_64-3.6/caiman/external
    copying caiman/external/__init__.py -> build/lib.linux-x86_64-3.6/caiman/external
    copying caiman/external/cell_magic_wand.py -> build/lib.linux-x86_64-3.6/caiman/external
    creating build/lib.linux-x86_64-3.6/caiman/source_extraction
    copying caiman/source_extraction/__init__.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction
    creating build/lib.linux-x86_64-3.6/caiman/base
    copying caiman/base/__init__.py -> build/lib.linux-x86_64-3.6/caiman/base
    copying caiman/base/rois.py -> build/lib.linux-x86_64-3.6/caiman/base
    copying caiman/base/timeseries.py -> build/lib.linux-x86_64-3.6/caiman/base
    copying caiman/base/traces.py -> build/lib.linux-x86_64-3.6/caiman/base
    copying caiman/base/movies.py -> build/lib.linux-x86_64-3.6/caiman/base
    creating build/lib.linux-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/__init__.py -> build/lib.linux-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/create_gt.py -> build/lib.linux-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/comparison.py -> build/lib.linux-x86_64-3.6/caiman/tests/comparison
    copying caiman/tests/comparison/regen_main_gt.py -> build/lib.linux-x86_64-3.6/caiman/tests/comparison
    creating build/lib.linux-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/__init__.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/plotting.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/estimation.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/measures.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/gat.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/regions.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/stats.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
    copying caiman/external/houghvst/demo_VST.py -> build/lib.linux-x86_64-3.6/caiman/external/houghvst
    creating build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/__init__.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/params.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/merging.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/utilities.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/initialization.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/temporal.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/map_reduce.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/spatial.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/online_cnmf.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/deconvolution.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/pre_processing.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/cnmf_optional_outputs.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/cnmf.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    copying caiman/source_extraction/cnmf/estimates.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/cnmf
    creating build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
    copying caiman/source_extraction/volpy/__init__.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
    copying caiman/source_extraction/volpy/utils.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
    copying caiman/source_extraction/volpy/volpy.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
    copying caiman/source_extraction/volpy/volpy_gui.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
    copying caiman/source_extraction/volpy/atm.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
    copying caiman/source_extraction/volpy/spikepursuit.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
    copying caiman/source_extraction/volpy/volparams.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy
    creating build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
    copying caiman/source_extraction/volpy/mrcnn/__init__.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
    copying caiman/source_extraction/volpy/mrcnn/utils.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
    copying caiman/source_extraction/volpy/mrcnn/visualize.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
    copying caiman/source_extraction/volpy/mrcnn/neurons.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
    copying caiman/source_extraction/volpy/mrcnn/model.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
    copying caiman/source_extraction/volpy/mrcnn/config.py -> build/lib.linux-x86_64-3.6/caiman/source_extraction/volpy/mrcnn
    running build_ext
    building 'caiman.source_extraction.cnmf.oasis' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/caiman
    creating build/temp.linux-x86_64-3.6/caiman/source_extraction
    creating build/temp.linux-x86_64-3.6/caiman/source_extraction/cnmf
    /opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -g -fwrapv -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -I/home/serapio/Desktop/mesmer/lib/python3.6/site-packages/numpy/core/include -I/home/serapio/Desktop/mesmer/include -I/usr/include/python3.6m -c caiman/source_extraction/cnmf/oasis.cpp -o build/temp.linux-x86_64-3.6/caiman/source_extraction/cnmf/oasis.o
    In file included from /usr/include/python3.6m/Python.h:8:0,
                     from caiman/source_extraction/cnmf/oasis.cpp:26:
    /usr/include/python3.6m/pyconfig.h:3:12: fatal error: x86_64-linux-gnu/python3.6m/pyconfig.h: No such file or directory
     #  include <x86_64-linux-gnu/python3.6m/pyconfig.h>
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/serapio/Desktop/mesmer/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2qj5oqsr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2qj5oqsr/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qgbokyy_/install-record.txt --single-version-externally-managed --compile --install-headers /home/serapio/Desktop/mesmer/include/site/python3.6/caiman Check the logs for full command output.

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hello,
For some reason it looks like your build process is using the system version of the python development libraries rather than the conda ones. 

Can you send me the output of these two commands?

`which pip`
and
`which python`

Thanks.

**Comment by smbaca** [comment]
Not sure which pip was used. 
As I mentioned in the other thread, the graduate student that setup the workstation got caiman and mesmerized installed though it gives weird segmentation faults on closing. I will see if it runs through a dataset without issue.

Thanks for looking into the matter!

-smb

$ which python
/opt/anaconda3/bin/python
$ pip
Command 'pip' not found, but there are 18 similar ones.

**Comment by pgunn** [comment]
If pip is not in your path, something is wrong with the conda environment (or perhaps no conda environment is active); a conda environment always has pip in its path. To really fix this, we'd want to recreate the install from scratch.

**Comment by smbaca** [comment]
Yes, I think the installation is pretty wonky. We can close this out as I think it will run fine on a regular installation. Thanks for looking into it!

smb iPhone msg
