### ISSUE TITLE
Incorrect background indexing when using seeded ROIs

### ISSUE THREAD

**Issue by neuroczy** [flatironinstitute/CaImAn#927]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 
 Python 3.7.3
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
Anaconda Prompt
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 1.6.3

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

When using seeded ROIs, variables b and f are not calculated correctly in the function "computing_indicator" in spatial.py.  If the video contains zero values at pixels 0 and 1 across all frames, b and C are returned as nan arrays, leading to removal of all components in the pipeline.

- **Copy error log below**

- **If you're not reporting an error, type your message below**

The variable px on line 1060 is a boolean array, but the assignment of not_px on 1061 yields an integer array of 0s and 1s, therefore indexing of Y on line 1063 is incorrect.  A simple fix for line 1063 would be:

`f = Y[not_px > 0, :].mean(0)`

However I have not tested this against the else clause (possibly related to the comment about memory mapping failure).

Thanks!

**Comment by j-friedrich** [comment]
The correct assignment for not_px is `~px`instead of `1-px`. I also fixed the else clause, i.e. the calculation of the mean for long recordings. Pushed it to the dev branch.
