### ISSUE TITLE
Component indices not updated in update_spatial_components

### ISSUE THREAD

**Issue by neuroczy** [flatironinstitute/CaImAn#928]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 
 Python 3.7.3
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
Anaconda Prompt
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 1.6.3

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Index out of bounds error in function regression_ipyparallel (spatial.py, line 393) if there are components removed because of NaNs or empty (spatial.py, line 188-202)

- **Copy error log below**

- **If you're not reporting an error, type your message below**

Removal of components from A_in and C in line 188-202 does not also update component indices in ind2_.  Updating ind2_ as follows solves the issue:

```
origCompIdx = np.arange(nr)

#remove components that have a nan
ff = np.where(np.isnan(np.sum(C, axis=1)))
if np.size(ff) > 0:
    logging.info("Eliminating nan components: {}".format(ff))
    ff = ff[0]
    A_in = csc_column_remove(A_in, list(ff))
    C = np.delete(C, list(ff), 0)
    origCompIdx = np.delete(origCompIdx,list(ff))

#⁠remove empty components
ff = np.where(np.sum(C, axis=1)==0)
if np.size(ff) > 0:
    logging.info("Eliminating empty components: {}".format(ff))
    ff = ff[0]
    A_in = csc_column_remove(A_in, list(ff))
    C = np.delete(C, list(ff), 0)
    origCompIdx = np.delete(origCompIdx,list(ff))

newCompIdx = np.arange(origCompIdx.shape[0])
for ii in range(len(ind2_)):
    if len(ind2_[ii]) > 0:
        iil = ind2_[ii]
        iimask,nidx = ismember(iil, origCompIdx)
        iil[iimask] = newCompIdx[nidx]
        ind2_[ii] = iil[iimask]
```

The function "ismember" is an additionally installed library (pip install ismember) with functionality identical to MATLAB ismember.  You may wish to do your own implementation.

Thanks!

**Comment by j-friedrich** [comment]
Thanks @neuroczy for looking into that and providing code to solve the issue. I just realized that to solve issue #912 (and #851) I already changed the code to update component indices in ind2_, thus also solving this issue.
