### ISSUE TITLE
Installation, solving environment takes >50 minutes on ubuntu

### ISSUE THREAD

**Issue by JakeHeffley** [flatironinstitute/CaImAn#933]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux Ubuntu
 2. Python version (3.x): 
 3.8.8
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Spyder ( but problem is with installation)
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
 conda env create -f environment.yml -n caiman

- **Describe the issue that you are experiencing**
Solving environment takes >50min. I have cleaned conda, removed and recloned caiman repo, uninstalled and reinstalled anaconda3. 

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Hello,
Recently I've been recommending users use the `mamba` tool for this, working that recommendation into the docs a week or so ago. This is a general conda performance issue, and mamba is a very solid general solution.

**Comment by JakeHeffley** [comment]
Got it. Thanks.
