### ISSUE TITLE
CaImAn: cannot run caimanmanager.py install

### ISSUE THREAD

**Issue by NataliaFavila** [flatironinstitute/CaImAn#941]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows):  macOS
 
 2. Python version (3.x): Python 3.9.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): bash 
 
 4. Which of the demo scripts you're using for your analysis (if applicable): 
 
 5. CaImAn version*:  lastest?
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): I tried both with mamba and as developer with pip install -e 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I can create the environment correctly with : mamba create -n caiman -c conda-forge caiman 
But I get an error when running caimanmanager.py install

- **Copy error log below**
from ..base.rois import com
  File "/Users/favilan/opt/anaconda3/envs/caiman/lib/python3.9/site-packages/caiman/base/rois.py", line 30, in <module>
    from skimage.morphology import watershed
ImportError: cannot import name 'watershed' from 'skimage.morphology' (/Users/favilan/opt/anaconda3/envs/caiman/lib/python3.9/site-packages/skimage/morphology/__init__.py)

- **If you're not reporting an error, type your message below**

**Comment by NataliaFavila** [comment]
In case anyone is having the same issue. I managed to solved the problem by installing a previous version for scikit-image. Once caiman enviroment was activated I installed scikit-image version 0.18.0:

conda install -c conda-forge scikit-image=0.18.0

With this caimanmanager.py worked both in Mac and Windows

**Comment by pgunn** [comment]
It looks like 0.19.0 moved the watershed function from morphology to segmentation. I will look into pinning skimage to >= 0.19.0 and changing the import. Thanks for letting us know.

**Comment by pgunn** [comment]
This is now fixed in the dev branch; I will hopefully be able to do a new release later this week if this change doesn't hurt the build tree too much. For now, I recommend sticking with your modified environment.

**Comment by bendichter** [comment]
@pgunn this is still not fixed in the latest master.

**Comment by pgunn** [comment]
@bendichter 
We've had 2 releases since then; what I thought was a fix definitely should be in the master branch by now. Are you seeing the exact same error?

**Comment by bendichter** [comment]
@pgunn, sorry I hadn't pulled the most recent master, though after doing so I am still caught by https://github.com/flatironinstitute/CaImAn/issues/962
