### ISSUE TITLE
Can’t install caiman with poetry

### ISSUE THREAD

**Issue by ShogoAkiyama** [flatironinstitute/CaImAn#942]
I need to manage packages with poetry in my project, but when I try to install caiman I get the following error….
Maybe need to maintain pip install caiman.
Thank you.

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
maxOS 

 2. Python version (3.x): 
 3.9

 5. CaImAn version*: 
 latest

- **Copy error log below**
```
  PackageInfoError

  Unable to determine package info for path: /var/folders/s_/y4fx2bhd0sz4p6zch3mrqg980000gn/T/pypoetry-git-CaImAn3yfatagz
  
  Fallback egg_info generation failed.
  
  Command ['/var/folders/s_/y4fx2bhd0sz4p6zch3mrqg980000gn/T/tmp_dsp5tt3/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "/private/var/folders/s_/y4fx2bhd0sz4p6zch3mrqg980000gn/T/pypoetry-git-CaImAn3yfatagz/setup.py", line 7, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'
```

**Comment by pgunn** [comment]
Hello,
Conda is the supported way to install Caiman. If you want to install through poetry, you may be able to convert environment.yaml into the toml file poetry uses, but this will be a bit of work and you'll need to handle dependency pinning yourself. I don't expect us to add support for Poetry in the future.

Best wishes.
