### ISSUE TITLE
Seeded CNMF not fitting specified number of background components

### ISSUE THREAD

**Issue by mhmcc** [flatironinstitute/CaImAn#946]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 CentOS Linux release 7.9.2009
 
 2. Python version (3.x): 
 Python 3.7.12
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Lab
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 1.9.3
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
 conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Seeded CNMF only fits one global background component despite parameter nb=2 (or any nb>1). Running normal CNMF with CaImAn's default initialization while keeping all other parameters the same produces the expected number of background components.

- **If you're not reporting an error, type your message below**
I am using CNMF to segment 2p data with seeded initialisation using my own custom watershed script (i.e. passing Ain to CNMF and setting only_init=False). The results are fairly good but I want to try fitting the data with more than one component for the global background model so I set parameter nb=2.
However, after calling cnm.fit the resulting cnm.estimates.b and cnm.estimates.f only have one component. All instances of 'nb' in cnm.params are correctly shown as nb=2 as I specified but the model is only fitting one. The result is the same higher values of nb.
If I use the standard pipeline by setting only_init=False and not passing Ain while keeping all other parameters the same then everything works as expected and cnm.estimates.b has 'nb' components.
Is this expected behavior for seeded CNMF or could this be a bug or issue with my code?

Here are my parameters and the section of my code which calls CNMF:

paramters = {'
  fr': 0.94,
  'decay_time': 5.312,
  'noise_range': [0.25, 0.5],
  'p': 1,
  'nb': 2,
  'rf': None,
  'only_init': False,
  'do_merge': True,
  'merge_thr': 0.8,
  'max_merge_area': 64,
  'min_SNR': 2,
  'SNR_lowest': 0.9,
  'rval_thr': 0.8,
  'rval_lowest': -1,
  'use_cnn': False,
  'verbosity': False
}

opts = params.CNMFParams(
    params_dict=parameters
)

n_processes=1
if 'dview' in locals():
        caiman.stop_server(dview=dview)
        c, dview, n_processes = caiman.cluster.setup_cluster(
            backend='local',
            n_processes=n_processes,
            single_thread=True,
)

cnm = cnmf.CNMF(
    n_processes,
    params=opts,
    dview=dview,
    Ain=Ain
)
cnm.fit(Y)

Result after fitting:
> cnm.estimates.b.shape
(262144, 1)

**Comment by j-friedrich** [comment]
fixed in the recent commit to the dev branch
