### ISSUE TITLE
Size of ROI / area of neuron masks

### ISSUE THREAD

**Issue by lanluo9** [flatironinstitute/CaImAn#957]
Hi! I was wondering how to calculate the size of a neuron ROI, as in how many pixels are contained in a neuron in the imaging data.

I've tried to use the binary mask to calculate neuron area (see below), but I don't think the result is correct, since I see some neurons with a large contour getting cell_area = 0 using this method.

`masks_ws, _, _ = extract_binary_masks_blob(cnm.estimates.A[:, component_id], 
                                                       neuron_radius=gSig[0], dims=Cn.shape)`
`cell_area = np.sum(masks_ws)`

**Comment by j-friedrich** [comment]
Yes, that usually works. For example, if you run demo_caiman_basic.py you can execute `masks_ws, _, _ = extract_binary_masks_blob(cnm.estimates.A, neuron_radius=gSig[0], dims=Cn.shape)` to get binarized footprints. You get the cells' are via `masks_ws.sum(1).sum(1)`

If your cell area is 0 you should modify some of the parameters of `extract_binary_masks_blob`
