### ISSUE TITLE
Tensorflow error in Volpy

### ISSUE THREAD

**Issue by cgaletzka** [flatironinstitute/CaImAn#963]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 3.8.13
 
 3. Working environment (Python IDE/Jupyter Notebook/other): spyder
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline_voltage_imaging
 
 5. CaImAn version*: 1.9.9
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

The same error message was previously posted in issue #887. The solution was to downgrade tensorflow to 1.15.1 as well as keras and h5py. However, when I try to install an older version of tensorflow I cannot install anything below Tensorflow 2 since it is not compatible with the current version of python. I have tried installing caiman with an older version of python but ran into other problems. Could you please let me know how to install the necessary versions of Tensorflow, keras and h5py under the package-based installation?

- **Copy error log below**

runcell('methods for segmentation', 'C:/Users/cedri/caiman_data/demos/general/demo_pipeline_voltage_imaging.py')
C:\Users\cedri\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\volpy\mrcnn\model.py:2366: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if os.name is 'nt':
      117091 [utils.py:      download_model():165][6072] File mask_rcnn already downloaded

Configurations:
BACKBONE                       resnet50
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  512
IMAGE_META_SIZE                14
IMAGE_MIN_DIM                  128
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              pad64
IMAGE_SHAPE                    [512 512   3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [0 0 0]
MINI_MASK_SHAPE                (56, 56)
NAME                           neurons
NUM_CLASSES                    2
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         1000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (16, 32, 64, 128, 256)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    64
STEPS_PER_EPOCH                100
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           128
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001

WARNING:tensorflow:AutoGraph could not transform <bound method ProposalLayer.call of <caiman.source_extraction.volpy.mrcnn.model.ProposalLayer object at 0x0000023E033CE4F0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
      118068 [ag_logging.py:                warn():146][6072] AutoGraph could not transform <bound method ProposalLayer.call of <caiman.source_extraction.volpy.mrcnn.model.ProposalLayer object at 0x0000023E033CE4F0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method ProposalLayer.call of <caiman.source_extraction.volpy.mrcnn.model.ProposalLayer object at 0x0000023E033CE4F0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method PyramidROIAlign.call of <caiman.source_extraction.volpy.mrcnn.model.PyramidROIAlign object at 0x0000023E03337520>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
      118142 [ag_logging.py:                warn():146][6072] AutoGraph could not transform <bound method PyramidROIAlign.call of <caiman.source_extraction.volpy.mrcnn.model.PyramidROIAlign object at 0x0000023E03337520>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method PyramidROIAlign.call of <caiman.source_extraction.volpy.mrcnn.model.PyramidROIAlign object at 0x0000023E03337520>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method DetectionLayer.call of <caiman.source_extraction.volpy.mrcnn.model.DetectionLayer object at 0x0000023E0348A040>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
      118330 [ag_logging.py:                warn():146][6072] AutoGraph could not transform <bound method DetectionLayer.call of <caiman.source_extraction.volpy.mrcnn.model.DetectionLayer object at 0x0000023E0348A040>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method DetectionLayer.call of <caiman.source_extraction.volpy.mrcnn.model.DetectionLayer object at 0x0000023E0348A040>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Traceback (most recent call last):

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\impl\api.py:584 in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\impl\conversion.py:118 in convert
    transformed, module, source_map = _TRANSPILER.transform_function(

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py:411 in transform_function
    factory = self._transformed_factory(fn, caching_subkey, user_context,

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py:373 in _transformed_factory
    nodes, ctx = self._transform_function(fn, user_context)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\pyct\transpiler.py:339 in _transform_function
    node = self.transform_ast(node, context)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\impl\conversion.py:69 in transform_ast
    node = qual_names.resolve(node)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\pyct\qual_names.py:252 in resolve
    return QnResolver().visit(node)

  File ~\.conda\envs\caiman\lib\ast.py:371 in visit
    return visitor(node)

  File ~\.conda\envs\caiman\lib\ast.py:447 in generic_visit
    value = self.visit(value)

  File ~\.conda\envs\caiman\lib\ast.py:371 in visit
    return visitor(node)

  File ~\.conda\envs\caiman\lib\ast.py:456 in generic_visit
    new_node = self.visit(old_value)

  File ~\.conda\envs\caiman\lib\ast.py:371 in visit
    return visitor(node)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\pyct\qual_names.py:232 in visit_Subscript
    if not isinstance(s, gast.Index):

AttributeError: module 'gast' has no attribute 'Index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File ~\caiman_data\demos\general\demo_pipeline_voltage_imaging.py:173 in <module>
    ROIs = utils.mrcnn_inference(img=summary_images.transpose([1, 2, 0]), size_range=[5, 22],

  File ~\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\volpy\utils.py:129 in mrcnn_inference
    model = modellib.MaskRCNN(mode="inference", model_dir=model_dir,

  File ~\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\volpy\mrcnn\model.py:1841 in __init__
    self.keras_model = self.build(mode=mode, config=config)

  File ~\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\volpy\mrcnn\model.py:2047 in build
    detections = DetectionLayer(config, name="mrcnn_detection")(

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:925 in __call__
    return self._functional_construction_call(inputs, args, kwargs,

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:1117 in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\impl\api.py:255 in wrapper
    return converted_call(f, args, kwargs, options=options)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\impl\api.py:591 in converted_call
    return _fall_back_unconverted(f, args, kwargs, options, e)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\impl\api.py:398 in _fall_back_unconverted
    return _call_unconverted(f, args, kwargs, options)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\autograph\impl\api.py:339 in _call_unconverted
    return f(*args, **kwargs)

  File ~\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\volpy\mrcnn\model.py:815 in call
    detections_batch = utils.batch_slice(

  File ~\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\volpy\mrcnn\utils.py:823 in batch_slice
    output_slice = graph_fn(*inputs_slice)

  File ~\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\volpy\mrcnn\model.py:817 in <lambda>
    lambda x, y, w, z: refine_detections_graph(x, y, w, z, self.config),

  File ~\.conda\envs\caiman\lib\site-packages\caiman\source_extraction\volpy\mrcnn\model.py:707 in refine_detections_graph
    indices = tf.stack([tf.range(probs.shape[0]), class_ids], axis=1)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\util\dispatch.py:201 in wrapper
    return target(*args, **kwargs)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\ops\math_ops.py:1791 in range
    limit = ops.convert_to_tensor(limit, dtype=dtype, name="limit")

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\ops.py:1499 in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\constant_op.py:338 in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\constant_op.py:263 in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\constant_op.py:280 in _constant_impl
    tensor_util.make_tensor_proto(

  File ~\.conda\envs\caiman\lib\site-packages\tensorflow\python\framework\tensor_util.py:444 in make_tensor_proto
    raise ValueError("None values not supported.")

ValueError: None values not supported.

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Right now there's not a good way to address this concern; it's not possible (or at least hard, and it will get harder) to get Tensorflow 1.x for supportable versions of Python, and unless Volpy (which was a code contribution from outside) is ported to Tensorflow 2.x, there's not much we can do to make this work.

I am reaching out to the code contributors on the issue; if we can't fix it we may need to remove Volpy.

**Comment by caichangjia** [comment]
I will try to see if the code for mask r-cnn in VolPy can be upgraded to tensorflow2 in the next few days. 
VolPy itself could be run with manual annotation even without mask r-cnn for cell detection.
Thanks for pointing out the problem.

**Comment by cgaletzka** [comment]
Thank you for your replies @pgunn and @caichangjia. Please let me know if mask r-cnn can be upgraded to tensorflow2.
