### ISSUE TITLE
Problem while creating conda environment

### ISSUE THREAD

**Issue by krusean** [flatironinstitute/CaImAn#964]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows 10
 
 3. Python version (3.x): 
 3.9.7

 4. Working environment (Python IDE/Jupyter Notebook/other):
None  yet

 5. Which of the demo scripts you're using for your analysis (if applicable):
 None yet
 
 7. CaImAn version*: 
Trying to install the most recent version 

 8. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
 I am following the development mode installation process from this instruction: https://caiman.readthedocs.io/en/master/Installation.html

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
Cannot create a caiman environment using the environment.yml file due to the following error: 

Encountered problems while solving.
Problem: nothing provides c-blosc needed by z5py-1.0.0-py35h606b8d2_0

I thought the problem was related to vs build tools, so I reinstalled them, but it did not fix the issue apparently.

**Comment by pgunn** [comment]
It looks like something decided that a very old build of z5py was the right build for your environment; I'm not sure how that happened.

You might try pinning z5py to 2.0.15 in your environment.yml as I can see there are windows builds available for that version and it shouldn't have old dependencies that are impossible to satisfy.
