### ISSUE TITLE
The definitions of gSig across cnmf and cnmf-e

### ISSUE THREAD

**Issue by fatihdinc** [flatironinstitute/CaImAn#970]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 
 2. Python version (3.x): 
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

I wanted to ask about a clarification regarding gSig and gSiz. In CNMF-E pipeline, gSig is considered to be half radius of the neuron, whereas for CNMF it is considered to be radius. Also, does gSiz matter for 2p data? If so, how should be choose it? (2*gSig +1 or 4*gSig +1) Moreover, this is probably a typo, the demo.pipeline.ipynb file is defining gSig in box 5 but not setting it as a parameter in box 6.  Thanks!

**Comment by j-friedrich** [comment]
`gSig` determines the size of the Gaussian filter used during initialization. For 2p data it's purpose is denoising, for 1p data it also approximately removes the background, by centering the filter (`center_psf=True`). It seems that choosing a smaller filter for 1p data yields better results.
`gSiz` determines the size of the initial patch of a neurons spatial footprint. It matters for both, 1p and 2p data. If you chose a too small value, the neural footprints `cnm.estimates.A` will look cut off cause the true neural size doesn't fit in the patch of size gSiz x gSiz. If you choose an unnecessary large value, you risk that the patch includes more neighboring neurons, which complicates demixing, and processing will be slower for larger patch sizes.

**Comment by j-friedrich** [comment]
Thanks for pointing out the missing gSig in box 6. just fixed that.
