### ISSUE TITLE
Caiman_Gui Can't Open the Analysis Results

### ISSUE THREAD

**Issue by toparkshin** [flatironinstitute/CaImAn#971]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows
 
 2. Python version (3.x): 3.8
 
 3. Working environment (Python IDE/Jupyter Notebook/other): PyCharm
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipieline
 
 5. CaImAn version*: 1.9.10 & 1.9.7
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

When I trying to start caiman_gui with hdf5 & mmap file from demo_pipeline, I got the error like this.

Can you help me to solve this problem?

- **Copy error log below**

C:/Users/UserName/caiman_data/bin/caiman_gui.py:136: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  estimates.accepted_list = np.array([], dtype=np.int)
C:/Users/UserName/caiman_data/bin/caiman_gui.py:137: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  estimates.rejected_list = np.array([], dtype=np.int)
C:/Users/UserName/caiman_data/bin/caiman_gui.py:140: DeprecationWarning: Please use `center_of_mass` from the `scipy.ndimage` namespace, the `scipy.ndimage.measurements` namespace is deprecated.
  estimates.cms = np.array([scipy.ndimage.measurements.center_of_mass(comp) for comp in estimates.img_components])
C:/Users/UserName/caiman_data/bin/caiman_gui.py:177: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  contours = [cv2.findContours(cv2.threshold(img, np.int(thrshcomp_line.value()), 255, 0)[1], cv2.RETR_TREE,
Traceback (most recent call last):
  File "C:\Users\UserName\anaconda3\envs\caiman\lib\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-24fbd38cfc10>", line 1, in <module>
    runfile('C:/Users/UserName/caiman_data/bin/caiman_gui.py', wdir='C:/Users/UserName/caiman_data/bin')
  File "C:\Program Files\JetBrains\PyCharm 2021.3.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/UserName/caiman_data/bin/caiman_gui.py", line 298, in <module>
    draw_contours()
  File "C:/Users/UserName/caiman_data/bin/caiman_gui.py", line 193, in draw_contours
    cv2.drawContours(bkgr_contours, sum([contours[jj] for jj in idx1], []), -1, (255, 0, 0), 1)
**TypeError: can only concatenate list (not "tuple") to list**

- **If you're not reporting an error, type your message below**

**Comment by J0eky** [comment]
hi, Have you solved the problem? I met the same problem with you when I tried to use caiman_gui.py after running demo_pipeline.py.

**Comment by toparkshin** [comment]
> hi, Have you solved the problem? I met the same problem with you when I tried to use caiman_gui.py after running demo_pipeline.py.

hi, I couldn't solve the problem. I'm wating updating to solve this problem now..

**Comment by j-friedrich** [comment]
In newer opencv versions cv2.findContours returns a tuple instead of a list.

Fixed it in the dev branch.
