### ISSUE TITLE
Error Saving cnm file when selecting components

### ISSUE THREAD

**Issue by flmuk** [flatironinstitute/CaImAn#975]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux

 2. Python version (3.x): 
 Python 3.9

 3. Working environment (Python IDE/Jupyter Notebook/other):
 Jupyter Lab
 4. Which of the demo scripts you're using for your analysis (if applicable):
 custom, but data provided computed with the [demo_caiman_cnmf_3D.ipynb](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_caiman_cnmf_3D.ipynb) notebook.
 
5. CaImAn version*: 
 1.9.9

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install .
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I have problems selecting traces with the caiman methods `cnm.estimates.select_components()`, and I believe the same error occurs at different parts of the CAIMAN code.

-**Copy your error log below**
I have the following notebook debug_save.ipynb, where I load a cnm object from a disk, and then perform some trace filtering based on the properties of the traces that are loaded.
The function that causes trouble is cnm2.save().
In the code there are multiple issues, but I suspect that they are all related. Can you reproduce them?
However, as commented in the code, the lines
```
cnm2.estimates.dims = cnm2.dims 1)
cnm2.estimates.A_thr=None 2)
```
are necessary because otherwise:
![image](https://user-images.githubusercontent.com/50918576/168594321-29dd3a8f-b48b-4a36-81f5-0d6c2bc2a9c6.png)

```
cnm2.estimates.dims = cnm2.dims 1)
#cnm2.estimates.A_thr=None 2)
#lines 1) and 2) above are necessary because of some bug in CAIMAN. This might become superfluous in future caiman versions
#if comment out line 2) error will occur due to cnm2.estimates.remove_small_large_neurons!

cnm2.estimates.threshold_spatial_components(maxthr=0, dview=dview)# threshold by pure binary selection mask, i.e. everywhere A>0 considering the post-processing

#steps in threshold_spatial_components
minimum_volume = 2000
maximum_volume = 4000
#remove all components that have a volume smaller than minimum and larger than maximum
tokeep_volumes = cnm2.estimates.remove_small_large_neurons(minimum_volume, maximum_volume) #returns indeces of components with size within the acceptable range (https://caiman.readthedocs.io/en/master/core_functions.html?highlight=remove_small_large_neurons#caiman.source_extraction.cnmf.estimates.Estimates.remove_small_large_neurons)
print(tokeep_volumes)

OUTPUT(added here for readability):
A_thr already computed. If you want to recompute set self.A_thr to None

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_14275/2227088351.py in <module>
     11 maximum_volume = 4000
     12 #remove all components that have a volume smaller than minimum and larger than maximum
---> 13 tokeep_volumes = cnm2.estimates.remove_small_large_neurons(minimum_volume, maximum_volume) #returns indeces of components with size within the acceptable range (https://caiman.readthedocs.io/en/master/core_functions.html?highlight=remove_small_large_neurons#caiman.source_extraction.cnmf.estimates.Estimates.remove_small_large_neurons)
     14 print(tokeep_volumes)

/software/opt/focal/x86_64/caiman/1.9.9-python3.9/lib/python3.9/site-packages/caiman/source_extraction/cnmf/estimates.py in remove_small_large_neurons(self, min_size_neuro, max_size_neuro, select_comp)
   1424             raise Exception('You need to compute thresolded components before calling remove_duplicates: use the threshold_components method')
   1425 
-> 1426         A_gt_thr_bin = self.A_thr.toarray() > 0
   1427         size_neurons_gt = A_gt_thr_bin.sum(0)
   1428         neurons_to_keep = np.where((size_neurons_gt > min_size_neuro) & (size_neurons_gt < max_size_neuro))[0]

AttributeError: 'bytes' object has no attribute 'toarray'
```

Why is this? Why do I have to set cnm2.estimates.A_thr=None explicitly, and the code is not compatible with cnm2.estimates.A_thr as default being a “b’NoneType’”? What about the thresholding of the spatial components before?
Something similar happens when “cnm2.estimates.discarded_components.A_thr”, which again is an “Estimates()” object, is not set to “None” explicitly, and the error again occurs further below:
![image#size=1ß00](https://user-images.githubusercontent.com/50918576/168594445-37e2b613-d48c-4c8b-bab0-335438fc809b.png)

```
cnm2.estimates.select_components(tokeep_volume_and_random)

*** Variable F_dff has not the same number of components as A ***
*** Variable cnn_preds has not the same number of components as A ***
*** Variable SNR_comp has not the same number of components as A ***
*** Variable r_values has not the same number of components as A ***

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_15391/604762187.py in <module>
----> 1 cnm2.estimates.select_components(tokeep_volume_and_random)

/software/opt/focal/x86_64/caiman/1.9.9-python3.9/lib/python3.9/site-packages/caiman/source_extraction/cnmf/estimates.py in select_components(self, idx_components, use_object, save_discarded_components)
    919                                     getattr(self, field).tocsc()[:, idx_components_bad])
    920                             else:
--> 921                                 caiman.source_extraction.cnmf.online_cnmf.csc_append(
    922                                     getattr(self.discarded_components, field),
    923                                     getattr(self, field).tocsc()[:, idx_components_bad])

/software/opt/focal/x86_64/caiman/1.9.9-python3.9/lib/python3.9/site-packages/caiman/source_extraction/cnmf/online_cnmf.py in csc_append(a, b)
   1983     Much faster than scipy.sparse.hstack but assumes the type to be csc and overwrites
   1984     the first matrix instead of copying it. The data, indices, and indptr still get copied."""
-> 1985     a.data = np.concatenate((a.data, b.data))
   1986     a.indices = np.concatenate((a.indices, b.indices))
   1987     a.indptr = np.concatenate((a.indptr, (b.indptr + a.nnz)[1:]))

AttributeError: 'bytes' object has no attribute 'data'
```

## Most Importantly:
This is the reason for why in the demo-notebook provided there are two selection processes of the traces, just do demonstrate that the error does not occur at one function only.

If both  “cnm2.estimates.A_thr” and “cnm2.estimates.discarded_components.A_thr” are explicitly set to “None”, **then the proper error why I write arises when calling “cnm.save(…)”**:
cnm2_savepath_filtered = "/scratch-local/f.kiessler/hope_demo_filtered.hdf5"

```
cnm2.save(cnm2_savepath_filtered)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_13159/4098422353.py in <module>
      1 cnm2_savepath_filtered = "/scratch-local/f.kiessler/hope_demo_filtered.hdf5"
----> 2 cnm2.save(cnm2_savepath_filtered)

/software/opt/focal/x86_64/caiman/1.9.9-python3.9/lib/python3.9/site-packages/caiman/source_extraction/cnmf/cnmf.py in save(self, filename)
    667         if '.hdf5' in filename:
    668             filename = caiman.paths.fn_relocated(filename)
--> 669             save_dict_to_hdf5(self.__dict__, filename)
    670         else:
    671             raise Exception("File extension not supported for cnmf.save")

/software/opt/focal/x86_64/caiman/1.9.9-python3.9/lib/python3.9/site-packages/caiman/utils/utils.py in save_dict_to_hdf5(dic, filename, subdir)
    429 
    430     with h5py.File(filename, 'w') as h5file:
--> 431         recursively_save_dict_contents_to_group(h5file, subdir, dic)
    432 
    433 def load_dict_from_hdf5(filename:str) -> Dict:

/software/opt/focal/x86_64/caiman/1.9.9-python3.9/lib/python3.9/site-packages/caiman/utils/utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    529             h5file[path + key] = np.array(item)
    530         elif type(item).__name__ in ['CNMFParams', 'Estimates']: #  parameter object
--> 531             recursively_save_dict_contents_to_group(h5file, path + key + '/', item.__dict__)
    532         else:
    533             raise ValueError(f"Cannot save {type(item)} type for key '{key}'.")

/software/opt/focal/x86_64/caiman/1.9.9-python3.9/lib/python3.9/site-packages/caiman/utils/utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    514         # save dictionaries
    515         elif isinstance(item, dict):
--> 516             recursively_save_dict_contents_to_group(h5file, path + key + '/', item)
    517         elif 'sparse' in str(type(item)):
    518             logging.info(key + ' is sparse ****')

/software/opt/focal/x86_64/caiman/1.9.9-python3.9/lib/python3.9/site-packages/caiman/utils/utils.py in recursively_save_dict_contents_to_group(h5file, path, dic)
    531             recursively_save_dict_contents_to_group(h5file, path + key + '/', item.__dict__)
    532         else:
--> 533             raise ValueError(f"Cannot save {type(item)} type for key '{key}'.")
    534 
    535 

ValueError: Cannot save <class 'bytes'> type for key 'fnames'.
```
.

The files that I use here (both raw data, generated with the 3d) [demo_caiman_cnmf_3D.ipynb](https://github.com/flatironinstitute/CaImAn/blob/master/demos/notebooks/demo_caiman_cnmf_3D.ipynb) notebook (some minor parameter modifications in gen_data)
as well as the notebook to reproduce this issue are available here:
data: https://syncandshare.lrz.de/getlink/fiXj3AhHW5LgvTDdwmCXQLkG/hope_demo.hdf5
notebook: https://syncandshare.lrz.de/getlink/fiQJDvkqfw19jpqnHfXuCefa/debug_save.ipynb

**Comment by pgunn** [comment]
This may be the result of some recent changes I made to hdf5 serialisation; apologies. I'll dig through the code and see if I can figure out what broke.

**Comment by flmuk** [comment]
Hi, are there any news on this?
My master's project critically depends on this being solved, and I cannot move on if this is not fixed. Is there a time frame within which I can plan for this to be fixed?
I am very grateful for the time devoted to solving this issue!

**Comment by PaulinaWysmolek** [comment]
Hi Pat,
I am facing this problem too and this is what is holding me up at the moment as well...I would be grateful for your help.
Best wishes,
Paulina

**Comment by ElijahShelton** [comment]
I am also using the CAIMAN BATCH version 1.9.9 with same specs as above, to analyze 4d microscopy calcium imaging data, and am facing the same error. Posting to stay updated on this!

**Comment by pgunn** [comment]
I will spend time on this today and this weekend. If I don't have a solution by monday I will identify an older version that predates the hdf5 changes that should be usable.

**Comment by pgunn** [comment]
@flmuk I believe this should be fixed by this commit: https://github.com/flatironinstitute/CaImAn/commit/eb4ba348fe118af4f5afbf1e770736ae531098e8

It was an issue with hdf5 handling; a few releases ago I unpinned h5py after reworking the code that used it, and I didn't cover all the possibilities around type representation for empty data types. This diff should (hopefully) address the issue. It at least runs the notebook you provided with the data you provided.

If you're comfortable building the dev branch please give it a go; otherwise I will likely cut a new release sometime within the next few days and you'll be able to install the conda binary package.

Thanks for the bug report, particularly for providing your notebook and data upfront; that helps a lot in getting to the bottom of problems like this.

**Comment by flmuk** [comment]
@pgunn 
Hi Pat,
thank you so much for the effort! I am very glad that we seem to have gotten to the bottom of the issue so quickly.
I will try the dev branch today and let you know if anything still goes wrong :)

**Comment by j-friedrich** [comment]
While 2) and 3) could now be commented out 1) was still necessary.To fix this, I made a change to load_CNMF to populate `cnm.estimates.dims` from `cnm.dims` when loading a hdf5 file, as has already been the case for nwb files.

`cnm.dims` gets populated when calling `fit`, `cnm.estimates.dims` when the CNMF object is created if and only if  `fnames` is provided.
