### ISSUE TITLE
Unable to install CaImAn on MBP with M1

### ISSUE THREAD

**Issue by engineeringjoy** [flatironinstitute/CaImAn#980]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): macOSX Monterey 12.2.1
 
 2. Python version (3.x): 3.9.12
 
 3. Working environment (Python IDE/Jupyter Notebook/other): N/A -- issue is with installation through Terminal
 
 4. Which of the demo scripts you're using for your analysis (if applicable): N/A
 
 5. CaImAn version*: N/A
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): mamba create -n caiman -c conda-forge caiman

- **Describe the issue that you are experiencing**
I was unable to install CaImAn using the package and developer instructions on this website: [https://caiman.readthedocs.io/en/master/Installation.html#installation-on-macos-and-linux](url)

- **Copy error log below**

> (base) nerdette@Joys-MacBook-Pro ~ % mamba create -n caiman -c conda-forge caiman
Looking for: ['caiman']
pkgs/r/osx-arm64         [====================] (00m:00s) Done
pkgs/main/osx-arm64      [====================] (00m:00s) Done
pkgs/r/noarch            [====================] (00m:00s) Done
conda-forge/osx-arm64    [====================] (00m:02s) Done
pkgs/main/noarch         [====================] (00m:03s) Done
conda-forge/noarch       [====================] (00m:04s) Done
Encountered problems while solving.
Problem: nothing provides requested caiman
(base) nerdette@Joys-MacBook-Pro ~ % git clone https://github.com/flatironinstitute/CaImAn
Cloning into 'CaImAn'...
remote: Enumerating objects: 24825, done.
remote: Counting objects: 100% (281/281), done.
remote: Compressing objects: 100% (149/149), done.
remote: Total 24825 (delta 134), reused 254 (delta 123), pack-reused 24544
Receiving objects: 100% (24825/24825), 519.91 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (16602/16602), done.
(base) nerdette@Joys-MacBook-Pro ~ % cd CaImAn/
(base) nerdette@Joys-MacBook-Pro CaImAn % mamba env create -f environment.yml -n caiman
conda-forge/osx-arm64    Using cache
conda-forge/noarch       Using cache
pkgs/main/osx-arm64      [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/osx-arm64         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
Looking for: ["python[version='>=3.10']", 'bokeh', 'coverage', 'cython', 'future', 'h5py', 'holoviews', 'ipykernel', 'ipython', 'ipyparallel', 'jupyter', 'matplotlib', 'mypy', 'nose', 'numpy', 'numpydoc', 'opencv', 'peakutils', 'pims', 'psutil', 'pynwb', 'pyqtgraph', "scikit-image[version='>=0.19.0']", 'scikit-learn', 'scipy', "tensorflow[version='>=2.4.0']", 'tifffile', 'tk', 'tqdm', 'yapf', 'z5py']
Encountered problems while solving.
Problem: nothing provides requested z5py

**Comment by pgunn** [comment]
Hello,
For now the way to install caiman on an M1 requires starting with the x86 version of conda (which will work through the compatibility layer). 

If you have not yet used conda for anything else, if you remove the arm version and install the amd64/x86 version, that should fix it. If you are using conda for other things there's another route we can try that's a little bit more work.

If by any chance you're at the workshop in NYC please let me know; I can help with either very quickly in person. If not, I will still help you.

**Comment by pgunn** [comment]
(we took care of this in person)
