### ISSUE TITLE
Error with save_memmap

### ISSUE THREAD

**Issue by fatihdinc** [flatironinstitute/CaImAn#983]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 
 2. Python version (3.x): 
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

Hi,

This one is pretty straightforward. When I define the hdf5 dataset name in the CNMF options, it is not picked up by the cm.save_memmap function inside the cnmf.fit routine, instead the function returns that there is no dataset name called '/mov' (which is the default). When I checked the source code, I saw that the dataset name was nearly hard-coded, not receiving the option changes from the cnmf class. I wanted to notify you of the bug.

- **Copy error log below**

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
I'll give it a look; will update the ticket as I do. Thanks!

**Comment by fatihdinc** [comment]
No worries, good luck! You might also want to change the demos to incorporate this, where save_memmap would now receive the datasetname from outside, not using the default '/mov'. Just a suggestion though :)

**Comment by EricThomson** [comment]
Closing as it seems it was addressed in a PR. Please reopen if this was a mistake @fatihdinc
