### ISSUE TITLE
failed to save tif file from mmap

### ISSUE THREAD

**Issue by ywtsay** [flatironinstitute/CaImAn#985]
1. Operating system (Linux/macOS/Windows):  Linux
 
 2. Python version (3.x): 3.9
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_motion_correction.ipynb
 
 5. CaImAn version*:  1.9.9
 

hi there, 

when I ran demo_motion_correction.ipynb, everything is fine till i tried to save mmap to tiff

<img width="1379" alt="error" src="https://user-images.githubusercontent.com/24360030/173557628-3edde06b-a1bb-46b9-9b41-f0ca7e0fa338.png">

Is there any other way to save corrected video ?
Thx for your help

**Comment by pgunn** [comment]
Looks like the 2022.4.22 release of tifffile removed some parameters. I'll get a fix into the dev branch today. Thanks for letting me know.

**Comment by pgunn** [comment]
Should be solved in 51ecb7e16d628a3cb514eff74b82ec1a4b06cecf
