### ISSUE TITLE
`.h5` files are not dealt with properly -- chops off part of filename in output

### ISSUE THREAD

**Issue by benlansdell** [flatironinstitute/CaImAn#989]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Linux
 
 2. Python version (3.x): 3.10.4
 
 3. Working environment (Python IDE/Jupyter Notebook/other): VS Code
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 1.9.11
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): pip install -e .

- **Describe the issue that you are experiencing**

I have a set of h5 files I'm using as input to Caiman. These are distinguished by their final digit in the filename. For example: 

```
h5_files = ['TSeries-08232018-0823-002.h5', 'TSeries-08232018-0823-003.h5']

mc = MotionCorrect(h5_files,dview=dview, max_shifts=max_shifts,
                           strides=strides, overlaps=overlaps,
                           max_deviation_rigid=max_deviation_rigid, 
                           shifts_opencv=shifts_opencv, nonneg_movie=NONNEG_MOVIE,
                           border_nan=border_nan,splits_rig=splits_rig,num_frames_split=num_frames_split)
mc.motion_correct(save_movie=True)
```

I find that Caiman, when figuring out what to name the `mmap` file, just chops off the last 4 characters, and appends extra parameters, e.g.: it will make a file called `TSeries-08232018-0823-00_rig__d1_512_d2_512_d3_1_order_F_frames_36000_.mmap`

The problem is that in my case, since the file extension is only two characters -- h5 -- the final 4 characters of the input filename are `2.h5`. This results in the mmap file and final results files having the identifier `2` being removed. This causes issues when we process multiple files named similarly, as shown here. 

I can avoid this by naming the files `hdf5` instead. 

But seems this is a bug for inputs with extension `h5`.

### The solution?

I can see this behavior in [motion_correction.py](https://github.com/flatironinstitute/CaImAn/blob/a27587c877de728bb770565139a4d2b1e7109d6c/caiman/motion_correction.py), for example, here: 
2830: `base_name=os.path.split(fname[0])[-1][:-4] + '_rig_'`

But also other places.

If `.h5` files are to be accepted, then `os.path.split(fname[0])[-1][:-4]` should be changed to be something more robust. 

Happy to make a pull request addressing this if you agree.

**Comment by benlansdell** [comment]
Thanks. Will look out for the changes

**Comment by pgunn** [comment]
The code should probably use `os.path.splitext()` after cutting the pre-fn path part off; I think that will do the right thing.

**Comment by benlansdell** [comment]
Great, thanks. Tried it out. Worked for me.
