### ISSUE TITLE
error with functions using CNMFe saved

### ISSUE THREAD

**Issue by tawantayron** [flatironinstitute/CaImAn#990]
1. Operating system (Linux/macOS/Windows): Ubuntu 20
 
 2. Python version (3.x): Python 3.10.4
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 1.9.10
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): pip install -e 

- **Describe the issue that you are experiencing**
Hello everybody! After loading an already performed CNMFe, when applying it to some functions, I received this error. It happens with some .hdf5 that I use. I would like to know if there are any known suggestions for this error.
obs: this error also appears in this notebook: https://github.com/EricThomson/yacare/blob/main/normalize_1p_traces.ipynb

![image](https://user-images.githubusercontent.com/39952231/175003916-3e69e1f6-5048-4d34-9692-25217e835088.png)

**Comment by pgunn** [comment]
I'm currently looking into this; if you can share one of the files with me (share with pgunn@flatironinstitute.org if you can do this; don't share to the ticket as it's publicly viewable) it'd be faster, but I may be able to figure out how it happened without that.

**Comment by pgunn** [comment]
Also, if you can share the rest of the notebook (so I can see any warnings) that could be helpful.

**Comment by tawantayron** [comment]
Hi, I'm so sorry for the delay. I had to format my pc and when I reinstalled CaImAn, I started using the new version 1.9.11, and since then the errors that were occurring are gone. I think your update fixed it. If it happens again, I'll let you know, so for now, I'll close the issue. Thank you very much for your help and attention! All the best!
