### ISSUE TITLE
Volpy GUI unable to load summary images

### ISSUE THREAD

**Issue by cawarwick** [flatironinstitute/CaImAn#991]
- **Tell us a bit about your setup**: 
 1. Windows 10
 
 2. Python version: 3.7.12 
 
 3. Working environment: Jupyter Notebook 
 
 4. Which of the demo scripts you're using for your analysis (if applicable): demo_pipeline_voltage_imaging.py to get sample data and generate the summary images to test the GUI
 
 5. CaImAn version*:  1.9.6
 
 6. CaImAn installation process: conda

7. Windows machine specs: Intel i7 8700, 32gb RAM, GT 730, nVME drive.

- **Describe the issue that you are experiencing**
I ran the VolPy demo pipeline up to the point at which is saves summary images which are used in the VolPy GUI. This demo downloads demo data, so it the summary images should be generated by the small demo data. I then launched the GUI (volpy_gui.py) and used the GUI to load the file generated by the first part of the dmeo: "demo_voltage_imaging_summary_images.tif". Once I try to load the summary image into the GUI it 'crashes' in that it closes the GUI and the powershell says this:
'
WARNING:root:Your tif file is saved a single pagefile. Performance will be affected
tree changes:

<ActionParameter 'LOAD DATA' at 0x1dd67eac4c8>
activated
None
'
![image](https://user-images.githubusercontent.com/81972652/175108608-845617a1-dbeb-4d21-abaf-b25d1a8cb937.png)

PART 2:
Update on the original issue. I figured I should update and try it again. I updated Caiman using Conda Forge and also updated the caiman_data using the manager and now I get a different issue running the same demo file as above running a Jupyter Notebook. Info below:

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_4796\3448104306.py in <module>
    277 # versus from the CLI
    278 if __name__ == "__main__":
--> 279     main()

~\AppData\Local\Temp\ipykernel_4796\3448104306.py in main()
    154     summary_images = np.stack([img, img, img_corr], axis=0).astype(np.float32)
    155     # save summary images which are used in the VolPy GUI
--> 156     cm.movie(summary_images).save(fnames[:-5] + '_summary_images.tif')
    157     fig, axs = plt.subplots(1, 2)
    158     axs[0].imshow(summary_images[0]); axs[1].imshow(summary_images[2])

~\Anaconda3\envs\caiman\lib\site-packages\caiman\base\timeseries.py in save(self, file_name, to32, order, imagej, bigtiff, excitation_lambda, compress, q_max, q_min, var_name_hdf5, sess_desc, identifier, imaging_plane_description, emission_lambda, indicator, location, unit, starting_time, experimenter, lab_name, institution, experiment_description, session_id)
    173         if extension in ['.tif', '.tiff', '.btf']:
    174             with tifffile.TiffWriter(file_name, bigtiff=bigtiff, imagej=imagej) as tif:
--> 175                 if "%4d%02d%02d" % tuple(map(int, tifffile.__version__.split('.'))) >= '20200813':
    176                     def foo(i):
    177                         if i % 200 == 0:

TypeError: not all arguments converted during string formatting

**Comment by pgunn** [comment]
How much RAM do you have?

Also poking:
@caichangjia

**Comment by caichangjia** [comment]
I have talked with him in gitter. The GUI is not tested on windows machine. Will fix this when I have time.

**Comment by caichangjia** [comment]
So I did find and fix problems in the volpy_gui due to some changes in pyqt. I will ask for a pull request soon. Sorry for the delay.
However I didn't manage to reproduce the second problem. The demo works fine on spyder and should work similarly on the jupyter notebook as it is tested in google colab.
